### ISSUE TITLE
Python 3.9 error in setup.py blocks anaconda build

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#1001]
We need to remove the 3.9 error in the setup.py. anaconda builds VTK on Py3.9 so PyVista needs to support that.

Or we need to set Python < 3.9 in the conda-forge build recipe for PyVista

**Comment by banesullivan** [comment]
See https://github.com/conda-forge/pyvista-feedstock/pull/34

**Comment by akaszynski** [comment]
Addressed in #1004
