### ISSUE TITLE
PlotterITK breaks after using for loops in Jupyter notebook.

### ISSUE THREAD

**Issue by mpdprot** [pyvista/pyvista#1020]
**Describe the bug, what's wrong, and what you expect:**

PlotterITK stops displaying after certain commands, in this specific case after using a for loop to add a small number of spheres.

-----

**To Reproduce**

Behaviour is not consistent, but my most recent reproduction of the result is as follows.

I add some meshes via a for loop, for example:

```py
import random

plotter = pv.PlotterITK()
big_sphere = pv.Sphere(radius=10)
plotter.add_mesh(big_sphere, scalars=0.6 * np.ones(len(big_sphere.points)))
for point in random.sample(list(big_sphere.points), 10):
    plotter.add_mesh(pv.Sphere(center=point, radius=1))
plotter.show(True, use_panel=True)
```

This seems to work okay (although sometimes it doesn't). But if I increase the number of smaller spheres:

```py
import random

plotter = pv.PlotterITK()
big_sphere = pv.Sphere(radius=10)
plotter.add_mesh(big_sphere, scalars=0.6 * np.ones(len(big_sphere.points)))
for point in random.sample(list(big_sphere.points), 100):
    plotter.add_mesh(pv.Sphere(center=point, radius=1))
plotter.show(True, use_panel=True)
```

Now no output appears. The PlotterITK then stops working - no plots appear even if I run the same code block but without adding the smaller spheres. I have to restart the jupyter server to make it work again (and sometimes even that doesn't work).

**Screenshots**

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/72602392/99414507-cbb69480-28ee-11eb-9326-fe751e35300c.png">

-----

**System Information:**
 Please run the following code wherever you are experiencing the bug and paste the output below. This report helps us track down bugs and it is critical to addressing your bug:

```py
# Get system info
import pyvista as pv
print(pv.Report())
```
--------------------------------------------------------------------------------
  Date: Tue Nov 17 16:09:14 2020 GMT

                OS : Darwin
            CPU(s) : 8
           Machine : x86_64
      Architecture : 64bit
       Environment : Jupyter
        GPU Vendor : Intel Inc.
      GPU Renderer : Intel(R) Iris(TM) Plus Graphics OpenGL Engine
       GPU Version : 4.1 INTEL-14.7.8

  Python 3.8.2 (default, Sep 24 2020, 19:37:08)  [Clang 12.0.0
  (clang-1200.0.32.21)]

           pyvista : 0.27.2
               vtk : 9.0.1
             numpy : 1.19.4
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.6
            meshio : 4.3.5
        matplotlib : 3.3.3
           IPython : 7.19.0
          colorcet : 1.0.0
             scipy : 1.5.4
        itkwidgets : 0.32.0
--------------------------------------------------------------------------------
```txt
# Paste system info here

```

**Comment by akaszynski** [comment]
It might be best to post this issue on https://github.com/InsightSoftwareConsortium/itkwidgets as `pyvista` is merely providing an interface to the itkwidget.  To be fair, it could entirely be due to our implementation, but given that their interface has only one main entry point for plotting, it's likely not to be due to how we pass our meshes to `itkwidgets`.

Could you attempt to attempt to generate the plot without `PlotterITK` by following the examples at:
https://github.com/InsightSoftwareConsortium/itkwidgets/blob/master/examples/vtkPolyData.ipynb
https://github.com/InsightSoftwareConsortium/itkwidgets/blob/master/examples/pyvista.PolyData.ipynb

That way we can determine if it's a `itkwidgets` bug or a `pyvista` bug.

**Comment by mpdprot** [comment]
Thanks! Both of those examples work fine. I'm not sure where the error is happening, but you're right that it might well be an itkwidget issue.

In any case, your link offered me the alternative method of plotting, by using `itkwidgets.view` and passing obejects as a dictionary.

<img width="414" alt="image" src="https://user-images.githubusercontent.com/72602392/99520289-d45ca880-298a-11eb-82ec-2d5ed3ead72e.png">

**Comment by akaszynski** [comment]
Closing this as it appears to be an `itkwidgets` issue.
