### ISSUE TITLE
Adding slice from function resets scalar bar + additional opacity issue

### ISSUE THREAD

**Issue by lsawade** [pyvista/pyvista#1035]
**Calling slice with opacity resets scalar bar:**

I'm creating a plot with both opacity values and color and slice sliders.

When `opacity=False`, meaning slices are plotted with an opacity value of `1.0`, the scalarbar is updated, and so are all actors belonging to the same scalarbar. However, when any slice is moved, the scalar bar is reset to its original `clim`s. 

When `opacity=True`, meaning slices are plotted with an opacity that is assigned to the original value, the scalarbar is updated, and the main mesh, but not the opaque slices. Furthermore, when any slice is moved, the scalar bar is reset to its original `clim`s but the slice is plotted with the expected colors.

I have a feeling that this is somewhat expected, but I can't dive into the code right now.

Thanks!

Cheers,

Lucas

-----

**To Reproduce**

```py
import numpy as np
import pyvista as pv
from pyvista import examples


class MeshPlotOpacity():

    def __init__(self, opacity=False):
        # Init state
        self.not_init_state = False

        if opacity is False:
            self.opacity = 1.0
        else:
            self.opacity = 'opacity'

        # Mesh mount saint helens example
        self.meshname = 'TestSlices'
        self.mesh = examples.download_st_helens().warp_by_scalar()
        xmin, xmax, ymin, ymax, zmax, zmin = self.mesh.bounds
        # Get colorbounds
        self.minM, self.maxM = self.mesh.get_data_range()
        # Add scalar array with range (0, 100) that correlates with elevation
        self.mesh['values'] = \
            pv.plotting.normalize(self.mesh['Elevation']) * 100
        # Set opacity
        self.mesh['opacity'] = \
            self.mesh['values']/np.max(self.mesh['values'])

        # Get colormap range
        self.clim = [self.minM, self.maxM]
        self.initclim = [self.minM, self.maxM]
        self.cminrange = [self.minM, self.maxM]
        self.cmaxrange = [self.minM, self.maxM]

        self.p = pv.Plotter()
        self.p.add_orientation_widget(self.mesh)
        self.p.add_mesh(self.mesh, opacity=0.05, stitle=self.meshname)

        self.p.add_slider_widget(
            self.my_plane_funcx, value=np.mean([xmin, xmax]), title='X', rng=[xmin, xmax],
            pointa=(.225, .1), pointb=(.51, .1),)
        self.p.add_slider_widget(
            self.my_plane_funcy, value=np.mean([ymin, ymax]), title='Y', rng=[ymin, ymax],
            pointa=(.55, .1), pointb=(.84, .1))

        self.cmin_slider = self.p.add_slider_widget(
            self.cmin_callback, value=self.clim[0], title='cmin',
            rng=self.cminrange,
            pointa=(.025, .9), pointb=(.475, .9), event_type='always')
        self.cmax_slider = self.p.add_slider_widget(
            self.cmax_callback, value=self.clim[1], title='cmax',
            rng=self.cmaxrange,
            pointa=(.525, .9), pointb=(.975, .9), event_type='always')

        self.p.show_bounds(bounds=self.mesh.bounds, location='back')
        # p.show_grid()
        # p.add_axes()
        self.p.show()

        self.meshname = 'RF'

        # Get bounds
        self.xmin, self.xmax, self.ymin, self.ymax, self.zmin, self.zmax = \
            self.mesh.bounds

    def cmin_callback(self, val):
        self.clim = [val, self.clim[1]]

        self.p.update_scalar_bar_range(self.clim, name=self.meshname)

        if self.not_init_state:
            self.cmax_slider.GetRepresentation(
            ).SetMinimumValue(self.clim[0])

    def cmax_callback(self, val):
        self.clim = [self.clim[0], val]

        self.p.update_scalar_bar_range(self.clim, name=self.meshname)

        if self.not_init_state:
            self.cmin_slider.GetRepresentation(
            ).SetMaximumValue(self.clim[1])

    def my_plane_funcx(self, loc):
        # Compute Slice
        slc = self.mesh.slice(normal=[1, 0, 0], origin=[loc, 0, 0])
        self.p.add_mesh(slc, name='Xslice', opacity=self.opacity,
                        stitle=self.meshname, clim=self.clim)

    def my_plane_funcy(self, loc):
        # Compute Slice
        slc = self.mesh.slice(normal=[0, 1, 0], origin=[0, loc, 0])
        self.p.add_mesh(slc, name='Yslice', opacity=self.opacity,
                        stitle=self.meshname, clim=self.clim)


MeshPlotOpacity(opacity=True)
MeshPlotOpacity(opacity=False)


```

**Screenshots**

#### `Opacity=False`
After moving the car sliders:
<img width="966" alt="Screen Shot 2020-11-27 at 4 32 59 PM" src="https://user-images.githubusercontent.com/23224303/100485485-45f4cf00-30ce-11eb-8df8-3a6673e7d451.png">

After relocating the slices:
<img width="966" alt="Screen Shot 2020-11-27 at 4 33 05 PM" src="https://user-images.githubusercontent.com/23224303/100485531-6d4b9c00-30ce-11eb-94e1-f7a01558084c.png">
Color sliders are unchanged, but the scalarbar is reset.

---

#### `Opacity=True`

After moving the color sliders:
<img width="1093" alt="Screen Shot 2020-11-27 at 4 38 20 PM" src="https://user-images.githubusercontent.com/23224303/100485677-fb278700-30ce-11eb-865e-be7a41cb5b6c.png">
The color of the slices is not updated

After relocating the Y slice:
<img width="1093" alt="Screen Shot 2020-11-27 at 4 38 42 PM" src="https://user-images.githubusercontent.com/23224303/100485692-0d092a00-30cf-11eb-9936-b1e6b73c001c.png">
The color of the slice is now updated, but not of the main scalarbar is reset. 

---

Additional Info:

When actually slicing a 3D object and not just a shell. Slices with opacity of 1.0 still show up in the renderer with and opacity that is less then 1.0
<img width="902" alt="Screen Shot 2020-11-30 at 11 28 49 AM" src="https://user-images.githubusercontent.com/23224303/100636067-4a53fe80-32ff-11eb-95f4-82ad72b1ae5f.png">

<img width="893" alt="Screen Shot 2020-11-30 at 11 29 03 AM" src="https://user-images.githubusercontent.com/23224303/100636038-432cf080-32ff-11eb-98cb-1acc6ea4388f.png">

I do no know whether this is expected or not, But this doesn't seem to be the case in, e.g., Paraview.

-----

**System Information:**
 Please run the following code wherever you are experiencing the bug and paste the output below. This report helps us track down bugs and it is critical to addressing your bug:

```py
# Get system info
import pyvista as pv
print(pv.Report())
```

```txt
# Paste system info here
--------------------------------------------------------------------------------
  Date: Fri Nov 27 16:39:07 2020 EST

                OS : Darwin
            CPU(s) : 12
           Machine : x86_64
      Architecture : 64bit
               RAM : 16.0 GB
       Environment : IPython
        GPU Vendor : ATI Technologies Inc.
      GPU Renderer : AMD Radeon Pro 560X OpenGL Engine
       GPU Version : 4.1 ATI-3.10.16

  Python 3.8.5 | packaged by conda-forge | (default, Aug 29 2020, 01:18:42)
  [Clang 10.0.1 ]

           pyvista : 0.27.2
               vtk : 9.0.1
             numpy : 1.19.1
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.6
            meshio : 4.3.5
        matplotlib : 3.2.1
           IPython : 7.18.1
             scipy : 1.5.2
              tqdm : 4.45.0
--------------------------------------------------------------------------------
```

**Comment by banesullivan** [comment]
The reason your colorbars/mapping get updated each time is because you completely destroy the old ones and creat new ones with default values based on the slice being plotted when you call `self.p.add_mesh` in your slider callbacks.

What you should do instead is overwrite the mesh that was already plotted such that the actor, mapper, and colorbar all remain intact.

HTH

**Comment by lsawade** [comment]
Hi @banesullivan ,

Thanks for the feedback, I appreciate it!

I was following this example on sliders

```python

p = pv.Plotter()

def create_mesh(value):
    res = int(value)
    sphere = pv.Sphere(phi_resolution=res, theta_resolution=res)
    p.add_mesh(sphere, name='sphere', show_edges=True)
    return

p.add_slider_widget(create_mesh, [5, 100], title='Resolution')
p.show()

```

But I realize now that, indeed, here the mesh is changed. That should for sure make the program faster too.

Is there a specific function such as 

```
mesh.update_field()
```

?

**Comment by banesullivan** [comment]
> Is there a specific function such as `mesh.update_field()`?

There is `update_scalars`: https://docs.pyvista.org/plotting/plotting.html?highlight=update_scalars#pyvista.BasePlotter.update_scalars
