### ISSUE TITLE
Incorrect code in the documentation for adding a background image

### ISSUE THREAD

**Issue by Sinaxist** [pyvista/pyvista#1041]
In the first example of the tutorial discussing the background image (https://docs.pyvista.org/examples/02-plot/background_image.html#sphx-glr-examples-02-plot-background-image-py), The code is supposed to add a background to the plot, but it doesn't. It can be easily resolved by removing the comment from the 4th line.

**Comment by banesullivan** [comment]
Good point as the preceding text implies it should not be commented. Can you make a PR fixing this?

**Comment by Sinaxist** [comment]
> Good point as the preceding text implies it should not be commented. Can you make a PR fixing this?

I just made a PR to fix this. Since I'm new here, I encountered some problems while doing the automatic tests and building the documents on my own computer following the guidelines. I hope that is fine because it's a minor fix and there are automatic checks after pulling requests.
