### ISSUE TITLE
Plotter shows an empty window when using VTK 8.90.0

### ISSUE THREAD

**Issue by whophil** [pyvista/pyvista#1045]
Plotter shows an empty window.

Not working:
- `pyvista.Plotter()` within a script - displays an empty window (see screenshot), waits for me to close it
- `pyvistaqt.BackgroundPlotter()` - temporarily displays an empty window which closes itself 

Working:
- `pyvistaqt.BackgroundPlotter()` within a Jupyter Notebook
- `pyvistaqt.BackgroundPlotter()` within an IPython console

-----

**To Reproduce**

Contents of `test_plotter.py`
```py
import pyvista as pv

cube = pv.Cube(center=(0, 0, 0), x_length=1.0, y_length=1.0, z_length=1.0)

plotter = pv.Plotter()
plotter.add_mesh(cube)
plotter.show()
```

**Screenshots**
![image](https://user-images.githubusercontent.com/2186528/101214797-7807b300-3631-11eb-8bd8-0e1000939917.png)

-----

**System Information:**
```txt
--------------------------------------------------------------------------------
  Date: Fri Dec 04 13:04:11 2020 PST

                OS : Darwin
            CPU(s) : 12
           Machine : x86_64
      Architecture : 64bit
       Environment : Python
        GPU Vendor : ATI Technologies Inc.
      GPU Renderer : AMD Radeon Pro 555X OpenGL Engine
       GPU Version : 4.1 ATI-2.11.22

  Python 3.7.9 (default, Aug 31 2020, 07:22:35)  [Clang 10.0.0 ]

           pyvista : 0.27.2
               vtk : 8.90.0
             numpy : 1.19.1
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.6
            meshio : 4.2.0
        matplotlib : 3.3.0
         pyvistaqt : 0.2.0
             PyQt5 : 5.15.1
           IPython : 7.18.1
             scipy : 1.5.2
--------------------------------------------------------------------------------
```

**Comment by whophil** [comment]
After some more testing, it appears this is a problem specific to using the ParaView-installed VTK (8.90.0), as was the case with https://github.com/pyvista/pyvista/issues/1036. I will adjust the title to reflect this.

If non-official VTK is not supported, then please feel free to close this.

**Comment by akaszynski** [comment]
> If non-official VTK is not supported, then please feel free to close this.

I'd really like to be able to support VTK 8.90.0, but this isn't an official VTK release, and there aren't VTK wheels for this release either.  If you'd like, I'd really appreciate a fix for this behavior, but at the moment I'm too busy to be able to patch this on my own.

**Comment by whophil** [comment]
Closing, ParaView 5.9.0 ships with something called VTK `9.0.20201030`. I haven't tested whether this is still an issue with that version as I don't use ParaView-installed VTK anymore. If it is, someone can open a new issue.
