### ISSUE TITLE
Controlling slider title properties

### ISSUE THREAD

**Issue by demacdo** [pyvista/pyvista#1047]
I'm trying to control the font size of a slider widget title, but it seems to be directly tied to the window size and not controlled by anything in rcParams. I'm able to alter other parameters of the title and label directly (see below), but not the font size. 

Would expect to be able to alter the font size of each slider. I also wonder if I'm missing a more simple interface to slider title properties (within the `add_slider_widget` call perhaps).

(Edited for markdown formatting).

-----

**To Reproduce**

Please include a code snippet to reproduce the bug in the block below:

```py
# Insert code here

p = pv.Plotter()

def create_mesh(value):
    res = int(value)
    sphere = pv.Sphere(phi_resolution=res, theta_resolution=res)
    p.add_mesh(sphere, name='sphere', show_edges=True)
    return

slider = p.add_slider_widget(create_mesh, [5, 100], title='Resolution')

# Can alter these
slider.GetRepresentation().GetTitleProperty().SetOpacity(0.5)
slider.GetRepresentation().GetTitleProperty().SetColor((1.0,0.0,0.0))
slider.GetRepresentation().SetLabelFormat('%0.9f')

# Can't alter this
slider.GetRepresentation().GetTitleProperty().SetFontSize(1000)

p.show()
```

**Screenshots**
<img width="509" alt="slider_title" src="https://user-images.githubusercontent.com/26281358/101418289-7f41f180-38bb-11eb-9324-b4acdddc6389.png">

-----

**System Information:**
 Please run the following code wherever you are experiencing the bug and paste the output below. This report helps us track down bugs and it is critical to addressing your bug:

```py
# Get system info
import pyvista as pv
print(pv.Report())
```

```txt
# Paste system info here
--------------------------------------------------------------------------------
  Date: Mon Dec 07 18:32:10 2020 EST

                OS : Darwin
            CPU(s) : 4
           Machine : x86_64
      Architecture : 64bit
       Environment : IPython
        GPU Vendor : Intel Inc.
      GPU Renderer : Intel Iris OpenGL Engine
       GPU Version : 4.1 INTEL-14.5.22

  Python 3.8.6 | packaged by conda-forge | (default, Oct  7 2020, 18:42:56)
  [Clang 10.0.1 ]

           pyvista : 0.27.2
               vtk : 9.0.1
             numpy : 1.19.4
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.6
            meshio : 4.3.6
        matplotlib : 3.3.3
         pyvistaqt : 0.2.0
             PyQt5 : 5.12.3
           IPython : 7.19.0
             scipy : 1.5.3
--------------------------------------------------------------------------------
```

**Comment by banesullivan** [comment]
`slider.GetRepresentation().SetTitleHeight` seems to be the way to set the size of the text. Unfortunately this is a VTK-quirk.

```py
slider.GetRepresentation().SetTitleHeight(0.08)
```

As for the issue of not being able to control the display params, you are welcome to add keyword arguments to this method that set these properties. It would be an easy contribution.
