### ISSUE TITLE
Question about the option 'shrink' 

### ISSUE THREAD

**Issue by josepereiroml** [pyvista/pyvista#1050]
I'm just trying to use this example from the documentation: 
>>> import pyvista
>>> mesh = pyvista.Sphere()
>>> shrunk_mesh = mesh.shrink(shrink_factor=0.8)

I'm getting this error: 
'PolyData' object has no attribute 'shrink'

**Comment by tkoyama010** [comment]
@josepereiroml Thank you for reporting the error. I want to know your environment to reproduce the error. Could you please run the following command and report the result ?
```python
import pyvista as pv

print(pv.Report())
```

**Comment by josepereiroml** [comment]
Date: Thu Dec 10 00:52:40 2020 Hora est. Pacífico, Sudamérica

                OS : Windows
            CPU(s) : 8
           Machine : AMD64
      Architecture : 64bit
               RAM : 11.8 GB
       Environment : Jupyter
             Intel : GPU Vendor
Intel(R) UHD Graphics 620 : GPU Renderer
4.5.0 - Build 26.20.100.7926 : GPU Version

  Python 3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)]

           pyvista : 0.25.3
               vtk : 9.0.1
             numpy : 1.18.5
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.6
            meshio : 4.1.1
        matplotlib : 3.2.2
             PyQt5 : 5.9.2
           IPython : 7.16.1
             scipy : 1.5.0
              tqdm : 4.47.0

  Intel(R) Math Kernel Library Version 2020.0.1 Product Build 20200208 for
  Intel(R) 64 architecture applications

**Comment by tkoyama010** [comment]
Thanks @josepereiroml 
> pyvista : 0.25.3

Shrink filter is added at [version 0.27.0](https://github.com/pyvista/pyvista/releases/tag/0.27.0). So could you please upgrade pyvista version?
