### ISSUE TITLE
vtm writer not expanding user path

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#1052]
When saving a VTM (`pyvista.MultiBlock`) data object to a `vtm` archive the user path `~` is not expanded and you end up with a new directory `~/*` inn your working directory. This is inconsistent with other `save` methods on objects.

**Comment by JevinJ** [comment]
Would adding .expanduser() to line 67 in common.py Common.save() work?

**Comment by banesullivan** [comment]
I think it should be as simple as that.

**Comment by banesullivan** [comment]
We just need to make sure this is done everywhere paths are dealt with
