### ISSUE TITLE
`Plotter.update` fails with `interactive_update=True` if `auto_close=False` is not specified

### ISSUE THREAD

**Issue by yngvem** [pyvista/pyvista#1053]
If want to create interactive plots, then `Plotter.show` must be called with both `interactive_update=True` and `auto_close=False`. Otherwise, the plotter will close immediately after it's created and it won't be possible to programmatically interact with the plotter.

I expect the `auto_close` to be set equal to `True` automatically if `interactive_update=True`. If a user specifies `auto_close=True` with `interactive_update=True`, then a warning should be shown.

It seems be a relatively simple bug, and I would be happy to contribute a fix.

-----

**To Reproduce**

```py
import pyvista as pv
from pyvista import examples

dataset = examples.download_bunny_coarse()
p = pv.Plotter()
p.add_mesh(dataset, label='Clipped')

p.show(interactive_update=True)
p.camera_position = [(0.24, 0.32, 0.7),
                     (0.02, 0.03, -0.02),
                     (-0.12, 0.93, -0.34)]
p.update()

```
This will raise the error
<pre><font color="#CC0000">---------------------------------------------------------------------------</font>
<font color="#CC0000">AttributeError</font>                            Traceback (most recent call last)
<font color="#4E9A06">&lt;ipython-input-17-af2a9a2637e7&gt;</font> in <font color="#06989A">&lt;module&gt;</font>
<font color="#4E9A06">----&gt; 1</font><font color="#CC0000"> </font>p<font color="#3465A4">.</font>update<font color="#3465A4">()</font>

<font color="#4E9A06">~/anaconda3/envs/bio/lib/python3.8/site-packages/pyvista/plotting/plotting.py</font> in <font color="#06989A">update</font><font color="#3465A4">(self, stime, force_redraw)</font>
<font color="#4E9A06"><b>   1110</b></font>             Plotter<font color="#3465A4">.</font>last_update_time <font color="#3465A4">=</font> curr_time
<font color="#4E9A06"><b>   1111</b></font> 
<font color="#4E9A06">-&gt; 1112</font><font color="#CC0000">         </font>update_rate <font color="#3465A4">=</font> self<font color="#3465A4">.</font>iren<font color="#3465A4">.</font>GetDesiredUpdateRate<font color="#3465A4">()</font>
<font color="#4E9A06"><b>   1113</b></font>         <font color="#4E9A06">if</font> <font color="#3465A4">(</font>curr_time <font color="#3465A4">-</font> Plotter<font color="#3465A4">.</font>last_update_time<font color="#3465A4">)</font> <font color="#3465A4">&gt;</font> <font color="#3465A4">(</font><font color="#06989A">1.0</font><font color="#3465A4">/</font>update_rate<font color="#3465A4">):</font>
<font color="#4E9A06"><b>   1114</b></font>             self<font color="#3465A4">.</font>right_timer_id <font color="#3465A4">=</font> self<font color="#3465A4">.</font>iren<font color="#3465A4">.</font>CreateRepeatingTimer<font color="#3465A4">(</font>stime<font color="#3465A4">)</font>

<font color="#CC0000">AttributeError</font>: &apos;NoneType&apos; object has no attribute &apos;GetDesiredUpdateRate&apos;

</pre>

If we, instead, run
```py
import pyvista as pv
from pyvista import examples

dataset = examples.download_bunny_coarse()
p = pv.Plotter()
p.add_mesh(dataset, label='Clipped')

p.show(interactive_update=True, auto_close=False)
p.camera_position = [(0.24, 0.32, 0.7),
                     (0.02, 0.03, -0.02),
                     (-0.12, 0.93, -0.34)]
p.update()

```
then everything works as it should.

-----

**System Information:**

```txt
--------------------------------------------------------------------------------
  Date: Fri Dec 11 08:25:05 2020 CET

                OS : Linux
            CPU(s) : 8
           Machine : x86_64
      Architecture : 64bit
               RAM : 31.0 GB
       Environment : IPython
        GPU Vendor : NVIDIA Corporation
      GPU Renderer : Quadro P520/PCIe/SSE2
       GPU Version : 4.5.0 NVIDIA 455.38

  Python 3.8.5 | packaged by conda-forge | (default, Sep 24 2020, 16:55:52)
  [GCC 7.5.0]

           pyvista : 0.27.3
               vtk : 9.0.1
             numpy : 1.19.2
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.6
            meshio : 4.3.6
        matplotlib : 3.3.2
         pyvistaqt : 0.2.0
             PyQt5 : 5.12.3
           IPython : 7.19.0
             scipy : 1.5.3
              tqdm : 4.50.2

  Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for
  Intel(R) 64 architecture applications
--------------------------------------------------------------------------------


```

**Comment by akaszynski** [comment]
I'm seeing this occur on 0.27.4 as well.  Would you mind submitting a PR for this?

**Comment by banesullivan** [comment]
Just tested on main and I think this has resolved itself
