### ISSUE TITLE
Scalar bar moving upward

### ISSUE THREAD

**Issue by rodrigomologni** [pyvista/pyvista#1054]
Hi, Team!

When I update the grid' scalars, the scalar bar moves upward. This problem appeared after I updated PyVista to version 0.27.

![Sem título](https://user-images.githubusercontent.com/1608652/101947986-1666bc00-3bd0-11eb-9f4b-421030441d55.gif)

**Comment by akaszynski** [comment]
Seems like it's replacing the scalar bar without fully removing the old one (as if it's being hidden).  We'll have to patch this.

**Comment by banesullivan** [comment]
@rodrigomologni, can you share some minimal code to reproduce this bug?

**Comment by rodrigomologni** [comment]
@banesullivan [example-bug-1054.zip](https://github.com/pyvista/pyvista/files/5948189/example-bug-1054.zip)

**Comment by banesullivan** [comment]
Ah okay perfect, thanks @rodrigomologni.

It appears the scalar bar slots aren't reset when a scalar bar is removed. This should be an easy patch.
