### ISSUE TITLE
Legend Size moves legend location

### ISSUE THREAD

**Issue by d-chambers** [pyvista/pyvista#1067]
**Describe the bug, what's wrong, and what you expect:**

When using the `size` parameter of the `BasePlotter.add_leged` method the legend seems to resize with the lower left corner fixed which creates an awkward legend location. It would probably be better if the upper right corner remained fixed when the legend is resized.

-----

**To Reproduce**

```py
import pyvista
from pyvista import examples
mesh = examples.load_hexbeam()
othermesh = examples.load_uniform()
legend_entries = []
legend_entries.append(['My Mesh', 'w'])
legend_entries.append(['My Other Mesh', 'k'])
plotter = pyvista.Plotter()
_ = plotter.add_mesh(mesh)
_ = plotter.add_mesh(othermesh, 'k')
_ = plotter.add_legend(legend_entries, size=(.12, .08))
plotter.show() # doctest:+SKIP
```

**Screenshots**
![image](https://user-images.githubusercontent.com/11671536/102927008-f0041480-444a-11eb-9039-9a34bf8d29a6.png)

**System Information:**
--------------------------------------------------------------------------------
  Date: Tue Dec 22 11:45:42 2020 PST

                OS : Linux
            CPU(s) : 16
           Machine : x86_64
      Architecture : 64bit
               RAM : 62.8 GB
       Environment : IPython
        GPU Vendor : NVIDIA Corporation
      GPU Renderer : GeForce GTX 980/PCIe/SSE2
       GPU Version : 4.5.0 NVIDIA 390.138

  Python 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 23:03:20)
  [GCC 7.3.0]

           pyvista : 0.27.2
               vtk : 8.2.0
             numpy : 1.17.5
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.6
            meshio : 4.3.6
        matplotlib : 3.3.3
         pyvistaqt : 0.2.0
             PyQt5 : 5.12.3
           IPython : 7.19.0
             scipy : 1.5.3
              tqdm : 4.54.1
--------------------------------------------------------------------------------
```

**Comment by banesullivan** [comment]
This should be a rather easy fix. We should follow VTK's spec for this and set points 1 and 2 where one is LL and 2 is UR. I would approve a PR for adding an argument to set `Position1` in `add_legend` such that the position can be fully controlled. For example:

```py
# add `origin` kwarg with a default value of whater VTK is setting it as already
...
if origin:
    self.legend.SetPosition1(origin[0], origin[1])
if size: # this is already in there
    self.legend.SetPosition2(size[0], size[1])
```
