### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by gokhalen** [pyvista/pyvista#1074]
I'm using Windows 10 and WSL2 Ubuntu and Xvfb and I'm calling PyVista (0.27.2) in a loop and I'm getting the following error:

```
Maximum number of clients reachedFatal Python error: Segmentation fault

Current thread 0x00007f073745c740 (most recent call first):
  File "/home/gokhalen/.local/lib/python3.8/site-packages/pyvista/plotting/plotting.py", line 766 in render
  File "/home/gokhalen/.local/lib/python3.8/site-packages/pyvista/plotting/plotting.py", line 4102 in show
  File "pyvistatest.py", line 11 in plot_pyvista
  File "pyvistatest.py", line 38 in <module>
Segmentation fault
```

Am I not deacllocating some allocated resource?  A minimal example which reproduces it is given below:

```
import pyvista as pv
import numpy as np

def plot_pyvista(surf,suffix=''):
    # parameters for the colorbar
    sargs = dict(height=0.25, vertical=True, position_x=0.85, position_y=0.05)
    p = pv.Plotter()
    p.show_axes()
    p.add_mesh(surf,scalars='point1',scalar_bar_args=sargs)
    p.view_xy()
    p.show(screenshot='output'+suffix+'.png')
    p.close()

if __name__ == '__main__':
    # number of times plot_vista is called
    nn = 256

    # mesh points
    vertices = np.array([[0, 0, 0],
                         [1, 0, 0],
                         [1, 1, 0],
                         [0, 1, 0],
                         [2, 0, 0],
                         [3, 1, 0]])

    # mesh faces
    # the 4 indicates how many nodes are present
    # other numbers are indicies in the vertices array
    faces = np.hstack([[4, 0, 1, 2, 3],
                       [4, 1, 4, 5, 2]])   

    # define a surface or as PyVista calls it a 'mesh' object
    surf = pv.PolyData(vertices, faces)
    # define nodal/point data
    surf.point_arrays['point1'] = np.arange(surf.n_points)

    for ii in range(nn):
        plot_pyvista(surf,str(ii))

```

**Comment by akaszynski** [comment]
You'll need to setup a virtual framebuffer.  Please see the section on [Running on Binder](https://docs.pyvista.org/getting-started/installation.html?highlight=xvfb#running-on-mybinder).

**Comment by gokhalen** [comment]
Hmm. I think I was not clear in explaining my problem. I have installed Xvfb and I can produce images using PyVista. However, producing images from inside a loop the script crashes with the error

`Maximum number of clients reachedFatal Python error: Segmentation fault
`
Which makes me think that either I (or PyVista) am not decallocating a resource.

**Comment by akaszynski** [comment]
> Which makes me think that either I (or PyVista) am not decallocating a resource.

Actually, that's exactly what's going on.  VTK 9.0.1 has a bug with Linux where render windows don't close out.  We've been unable to patch this outside of VTK, so we're waiting for a fix from them with the next release.

To resolve this, you can downgrade to 8.1.2 or generate a maximum around 50 per script.  You'll have to loop it in bash.

**Comment by gokhalen** [comment]
Thank you very much.

**Comment by akaszynski** [comment]
Closing this as it's solved to the best of our ability with this version of VTK.
