### ISSUE TITLE
Can't set center of disc

### ISSUE THREAD

**Issue by Pytrik1** [pyvista/pyvista#1087]
**Describe the bug, what's wrong, and what you expect:**

**The disk mesh does not change position when I set the center. It stays centered at (0., 0., 0.).
Tested on two different windows pc's.**

**To Reproduce**

Code snippet to reproduce the bug in the block below:

```py
import pyvista as pv
import vtk

mesh = pv.Disc(center=(0,-5,0))

p = pv.Plotter()
p.show_axes()
p.show_bounds(grid='front', location='outer', all_edges=True)
p.add_mesh(mesh)
p.show()

```

**System Information:**
 Please run the following code wherever you are experiencing the bug and paste the output below. This report helps us track down bugs and it is critical to addressing your bug:

```py
# Get system info
import pyvista as pv
print(pv.Report())
```

```txt
--------------------------------------------------------------------------------
  Date: Fri Jan 15 21:17:42 2021 W. Europe Standard Time

                OS : Windows
            CPU(s) : 12
           Machine : AMD64
      Architecture : 64bit
       Environment : Python
        GPU Vendor : Intel
      GPU Renderer : Intel(R) UHD Graphics 630
       GPU Version : 4.5.0 - Build 26.20.100.7985

  Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64
  bit (AMD64)]

           pyvista : 0.27.4
               vtk : 8.1.2
             numpy : 1.19.5
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.6
            meshio : 4.3.8
--------------------------------------------------------------------------------

```

**Comment by tkoyama010** [comment]
Thank you for rerporting. I could reproduce it in my environment. It seems the bug of Disc function. I will fix it.
https://github.com/pyvista/pyvista/blob/94c0053703b8d584eadb6990dff96fd77b639e27/pyvista/utilities/geometric_objects.py#L547-L549
