### ISSUE TITLE
QtInteractor  wont resize in my pyQtWindow

### ISSUE THREAD

**Issue by ghazalbangash** [pyvista/pyvista#1095]
Hi guys :) when my window is small the interactor fits perfectly in my window like the picture below :
the pink part is a QtTable,the white part is the frame and the gray part is the interactor, the frame is passed to the interactor and is the centralWidget
![first](https://user-images.githubusercontent.com/47847589/105033657-a4568200-5a6d-11eb-89cf-6e56dec217f6.png)

but when i enlarge my window,it wont scale accordingly and has a fixed size,i want it to fill that white space inbetween too, is this a pyvistaQt issue or Pyqt5 issue,any ideas?
![2nd](https://user-images.githubusercontent.com/47847589/105033905-fe574780-5a6d-11eb-8e47-861b94b94ac6.png)

**Comment by akaszynski** [comment]
Seems that neither widget resizes.  Take a look at https://github.com/pyvista/pyvista-gui for how to resize widgets using the interactor.

**Comment by ghazalbangash** [comment]
thanks a lot solved my problem
