### ISSUE TITLE
Instructions for using mybinder with pyvista out of date.

### ISSUE THREAD

**Issue by jorgensd** [pyvista/pyvista#1123]
As I am very interesting in using mybinder for my jupyterbook, I found https://docs.pyvista.org/getting-started/installation.html#running-on-mybinder
However, the repository you are pointing to is very out of date, and cannot be used without modifications.

**Comment by banesullivan** [comment]
Ah yep, it is VERY out of date. I will see if I can update these docs soon here to leverage a docker iamge we have and the in-notebook interactivity via https://github.com/Kitware/ipyvtk-simple

**Comment by banesullivan** [comment]
This should be updated now. I had to update the cookiecutter's environment.yml: https://github.com/pyvista/cookiecutter-pyvista-binder

The examples on binder are now building with ipyvtklink for interactive plotting:


https://user-images.githubusercontent.com/22067021/143784846-55443228-ca12-4c3f-a47b-19ad7b805d2b.mov



----

Ideally we should have our CI that does this deployment copy the `environment.yml` from the pyvista repo so we don't have to keep that file updated in two places.

I'll deal with that later... when we inevitably move our docs building to GitHub actions
