### ISSUE TITLE
pyvista.start_xvfb() not exposed.

### ISSUE THREAD

**Issue by jorgensd** [pyvista/pyvista#1125]
Following: https://docs.pyvista.org/plotting/notebook_plotting/ipyvtk_plotting.html
the docs says that one can:
```
Or alternatively, start it using the built in pyvista.start_xvfb()
```
However, this function is not exposed in:
https://github.com/pyvista/pyvista/blob/master/pyvista/utilities/__init__.py
and is therefore not accessible.
Ref to location of function: https://github.com/pyvista/pyvista/blob/master/pyvista/utilities/xvfb.py

**Comment by banesullivan** [comment]
Huh, good catch. This should be an easy fix.
