### ISSUE TITLE
implementing undo/redo

### ISSUE THREAD

**Issue by ghazalbangash** [pyvista/pyvista#1128]
Hi. i am currently trying to develop a desktop application using pyvista and trying to implement undo/redo using momento and command pattern, is there any way to update my plotter with new states? what does update() function in the docs actually do? i tried giving it the parameters in wanted but would give me TypeError

**Comment by banesullivan** [comment]
`update()` simply re-executes the backend rendering pipeline.

Adding undo/redo functionality in your app goes a bit out of scope for PyVista and it will get rather complicated quickly (likely why we don't see this sort of functionality even in ParaView)

For that reason, I am going to close this...
