### ISSUE TITLE
Discussion: Change Theme to PyData Sphinx Theme

### ISSUE THREAD

**Issue by akaszynski** [pyvista/pyvista#1138]
### Documentation Theme Redesign
Recently, `numpy`, `pandas`, and `jupyterlab` have changed their sphinx themes to use the [The PyData Sphinx Theme](https://pydata-sphinx-theme.readthedocs.io/).  Personally, I really like it.  It's professional, the interface is clean and not busy, and it's immediately clear what's available on the landing page.   [pandas](https://pandas.pydata.org/docs/) has done a great job in particular developing their docs.

I've even implemented a fork of their theme with a different stylesheet for the `pyansys` project:
https://mapdldocs.pyansys.com/

#### Question:
Should we create a branch and demo the docs using the PyData theme?  I'm imagining that the top nav bar would contain 
5 categories:
- Getting Started
- User Guide
- API Reference
- Examples Gallery
- Development/Contributing

This isn't a mandatory change, but I would like to know how the @pyvista/developers and `pyvista` contributors/users feel about a documentation refactor.  Even if we propose redesigned documentation, it would be there for review until the next patch release (or thereafter).

Alternative proposals are welcome as well.

**Comment by tkoyama010** [comment]
+1 for `The PyData Sphinx Theme`. I think PyVista targets data scientists who want to plot 3D data with Jupyter. It is important that the document format is friendly to them.

**Comment by banesullivan** [comment]
+1 for this. Considering I've put the most effort into the organization of the current docs, I'd be happy to help do this transition and "refactor" the docs

**Comment by adeak** [comment]
I still need to get used to the new numpy website, but mostly because I was so used to the old one. Specifically the pyansis site looks great, I think it would work well for pyvista.
