### ISSUE TITLE
Plotter.image causes a segmentation fault

### ISSUE THREAD

**Issue by Aquan1412** [pyvista/pyvista#1140]
Description of the bug:

As mentioned in the title, calling plotter.image in order to access the image array of a PyVista plot causes a segmentation fault.
Using plotter.show() works fine, the error only occurs when I try to acces the image array (mostly for  plotting in matplotlib via imshow).

-----

Steps to reproduce:
The following snippet can be used to reproduce the error:

```py
import pyvista as pv

mesh = pv.Sphere()

plotter = pv.Plotter()
plotter.add_mesh(mesh)

# access some values of the image array
plotter.image[:20,0]
```
**System Information:**
While I originally noticed the bug in my "normal" conda environment, I was also able to reproduce it in a fresh conda environment with only the necessary packages installed (in order to minimize interference of other packages). Here is the output of pv.Report():

```txt
--------------------------------------------------------------------------------
  Date: Wed Feb 03 14:58:35 2021 CET

                OS : Linux
            CPU(s) : 20
           Machine : x86_64
      Architecture : 64bit
       Environment : Python
        GPU Vendor : NVIDIA Corporation
      GPU Renderer : Quadro P4000/PCIe/SSE2
       GPU Version : 4.5.0 NVIDIA 390.138

  Pyth oon 3.8.5 (default, Sep  4 2020, 07:30:14)  [GCC 7.3.0]

           pyvista : 0.27.4
               vtk : 8.2.0
             numpy : 1.19.2
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.6
            meshio : 4.3.8

  Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for
  Intel(R) 64 architecture applications
--------------------------------------------------------------------------------

```

If you need additional information, please let me know, I would be glad to help.

Edit: I just noticed that it there's no segementation fault if I use plotter.show(return_img=True). Maybe the image is not correctly rendered if I just call plotter.image?

**Comment by akaszynski** [comment]
> Edit: I just noticed that it there's no segementation fault if I use plotter.show(return_img=True). Maybe the image is not correctly rendered if I just call plotter.image?

That's exactly it.  We need to add to logic to ensure that accessing the `image` attribute checks if the image has actually been rendered.  Adding it to the milestone.  For now, can you work with the "workaround"?

**Comment by Aquan1412** [comment]
Thanky for the reply. Yes, I can easily change my scripts to include the workaround for now.
