### ISSUE TITLE
multi-window plotting: isolate click events

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#116]
Can we isolate click events to each renderer in the multi-plotting view? For example, if on click on one renderer to rotate the camera, as soon as you cross the boundary into the other renderer, it starts rotating the other window.

```py
import vtki
from vtki import examples

p = vtki.Plotter(shape=(1,2), notebook=False)

p.subplot(0,0)
p.add_mesh(examples.load_airplane())

p.subplot(0,1)
p.add_mesh(examples.load_globe())

p.show()
```

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/22067021/53703815-5b42a980-3dd3-11e9-809a-309bdd3436c1.gif)

**Comment by banesullivan** [comment]
Note that using the `.disable()` and `.enable()` functions from #115 might help mitigate this. 

Perhaps we could implement a trigger for when clicking on a renderer, we could call `.disable()` on all other renderers in the plotter then on the mouse release, call `.enable()` on them.

**Comment by akaszynski** [comment]
I agree that’s a little annoying in its current implementation.  Disabling the renders might work.
