### ISSUE TITLE
doctest isn't producing the same results as local script

### ISSUE THREAD

**Issue by rodrigomologni** [pyvista/pyvista#1181]
```python
>>> import pyvista as pv
>>> plotter = pv.Plotter(shape=(2, 2))
>>> plotter.subplot(0, 0)
>>> plotter.add_mesh(pv.Box(), name='box')
>>> plotter.subplot(0, 1)
>>> plotter.add_mesh(pv.Sphere(), name='sphere')
>>> plotter.subplot(1, 0)
>>> plotter.add_mesh(pv.Box(), name='box')
>>> plotter.subplot(1, 1)
>>> plotter.add_mesh(pv.Cone(), name='cone')
>>> plotter.where_is('box')
[(0, 0), (1, 0)]
```

The example above produces:

![image](https://user-images.githubusercontent.com/1608652/107866952-d4b6f380-6e54-11eb-922c-973e0e4fb4a1.png)

However, `doctest` produce a different result:

![image](https://user-images.githubusercontent.com/1608652/107866954-e8625a00-6e54-11eb-9ef0-895fa39f57ee.png)

_Originally posted by @rodrigomologni in https://github.com/pyvista/pyvista/issues/1175#issuecomment-778714753_

**Comment by adeak** [comment]
I think I know what's wrong, see https://github.com/pyvista/pyvista/pull/1192 for an attempted fix.
