### ISSUE TITLE
Disable the faulthandler warnning.

### ISSUE THREAD

**Issue by akaszynski** [pyvista/pyvista#1186]
Using IDLE, the fault handler warning pops up on windows and is somewhat discouraging when first using `pyvista`. 
 We should log it as a warning rather than using `warnings.warn`

Recommending that we disable it.  

Any objections?

**Comment by larsoner** [comment]
Personally I do not like the idea of individual libraries setting global states like `faulthandler.enable()` at all. Can we just get rid of it? When people hit segfaults they can do this step themselves after all.

**Comment by akaszynski** [comment]
Agreed.  We should limit the side effects of our module.  `faulthandler` is really a developer tool that we should enable selectively.
