### ISSUE TITLE
PyQt5 5.12 Crashing Unpredictably

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#119]
Windows users are reporting crashes/segfaults on Windows with `PyQt5` version `5.12`.

Immediate solution of downgrading `PyQt5` to version `5.11.3` works for now but we need a patch for this.

*Edit: Travis is also reporting failures on Linux*

**Comment by akaszynski** [comment]
I can debug this.  This might be mitigated if we can find a way to enable plotting on appveyor.

**Comment by banesullivan** [comment]
Thanks @akaszynski!

**Comment by akaszynski** [comment]
Any Idea where this is happening?  A quick check with  ``5.12`` isn't giving me any any trouble.  I'm using Python 3.7 and ``vtki==0.17.1``

**Comment by banesullivan** [comment]
Seeing it happen when trying to use the `BackgroundPlotter`

```py
plotter = vtki.BackgroundPlotter()
```

**Comment by akaszynski** [comment]
All ``test_qt_plotting`` tests passed.  I didn't test with iPython.  I'll try that out now.

**Comment by banesullivan** [comment]
Also, I hardest the `PyQt5` dependence to `5.11.3` in the CI scripts a while back because builds were failing right after the `5.12` release. Bernal branch and remove `5.11.3` dependence from the AppVeyor script and the `requirements_test.txt` file

**Comment by akaszynski** [comment]
AppVeyor doesn't test plotting since it seg-faults as there's no X11 equivalent on the windows server instance.  There's probably a way of enabling it.

Also, local testing using notebooks, ``5.12``, and ``vtki==0.17.1`` doesn't reveal any bugs.  All the menu actions and general plotting functions work fine.  Is there anything more specific?

**Comment by banesullivan** [comment]
Currently failing on Travis https://travis-ci.org/vtkiorg/vtki/builds/503217887

**Comment by mmagnuski** [comment]
Hi, I'm a windows user and `vtki` crashes for me.
Using it in notebook with:
```
from vtki import examples
```
crashes the kernel every time I tried.
My pyqt version is `5.9.2` though.

**Comment by banesullivan** [comment]
Hi @mmagnuski, thanks for posting your issue -that's definitely not good that a simple import of `vtki` crashes your kernel and if it crashes on import, is likely unrelated to PyQt.

Could you post your OS details, `vtki` version, and copy/paste the output from a `pip list` or `conda list` (whichever package manager you use) into a new issue along with the exact code that causes the crash?

Also, could you try importing `vtki` in simple Python interpreter from the command line in case there are error messages that the Jupyter Notebook is filtering?

**Comment by banesullivan** [comment]
Also, I'd be happy to go back and forth with you on slack to make sure you are up and running on Windows: http://slack.opengeovis.org

**Comment by mmagnuski** [comment]
@banesullivan Sorry I didn't reply earlier, I didn't have much time to go back to `vtki`. I will create a new issue today in the evening or tomorrow.
