### ISSUE TITLE
Embedding Pyvista into flask app

### ISSUE THREAD

**Issue by tjdodwell** [pyvista/pyvista#1195]
Hi All,

I hope this is right place to ask this sort of thing, sorry if not.

Is there an example which shows how you can embed pyvista plots/ functionality into a flask web application, say for example 

https://docs.pyvista.org/examples/02-plot/scalar-bars.html#sphx-glr-examples-02-plot-scalar-bars-py

Cheers in advance.

**Comment by akaszynski** [comment]
It's a good request.  There's lots you can do with `pyvista` within a webpage, especially with Jupyter, but I've not considered using flask with it.

I'm not that experienced with flask and web development, but I had fun learning to create a basic example.  Sadly, this example doesn't have any of the fancy plotting a real VTK plotting window would have, but you can generate static plots, which might be helpful to display data for certain cases.

![flask_example](https://user-images.githubusercontent.com/11981631/108668814-1a00a400-7499-11eb-8314-e091e07905b2.png)

```py
"""Simple flask app to display static images generated from pyvista.

Expected paths:
flask_example
└── app.py
    templates
    └── index.html

"""
import os
import pyvista
from flask import Flask, render_template, request


static_image_path = os.path.join('static', 'images')
if not os.path.isdir(static_image_path):
    os.makedirs(static_image_path)


app = Flask(__name__)

@app.route("/")
def index():
    return render_template('index.html')


@app.route("/getimage")
def get_img():
    """Generate a screenshot of a simple pyvista mesh.

    Returns
    -------
    str
        Local path within the static directory of the image.

    """
    # get the user selected mesh option
    meshtype = request.args.get('meshtype')
    if meshtype == 'Sphere':
        mesh = pyvista.Sphere()
    elif meshtype == 'Cube':
        mesh = pyvista.Cube()
    elif meshtype == 'Bohemian Dome':
        mesh = pyvista.ParametricBohemianDome()
    elif meshtype == 'Cylinder':
        mesh = pyvista.Cylinder()
    else:
        # invalid entry
        raise ValueError('Invalid Option')

    # generate screenshot
    filename = f'{meshtype}.png'
    filepath = os.path.join(static_image_path, filename)
    mesh.plot(off_screen=True,
              window_size=(300, 300),
              screenshot=filepath)
    return os.path.join('images', filename)


if __name__ == '__main__':
    app.run()
```

---

```html
<html>
  <head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  </head>
   <body>

     <select style="background-color: #ffffa0" name="country", id="meshtype" onchange="getState(this.value)">
       <option>Select Mesh Type</option>
       <option>Sphere</option>
       <option>Cube</option>
       <option>Bohemian Dome</option>
       <option>Cylinder</option>
     </select>

     <button type='button' id ='retrieve'>Plot</button>
     <img src="" id="myimg" />
   </body>
  <script>
    $(document).ready(function() {
       $('#retrieve').click(function(){
           $.ajax({
           url: "{{ url_for ('get_img') }}",
           type: "GET",
           data: { 
               meshtype:  $('#meshtype option:selected').val()
           },
           success: function(response) {
               $("#myimg").attr('src', '/static/' + response);
          },
          error: function(xhr) {
              alert("Please select a mesh type from the drop down menu.");
         }
         });
       });
    });
  </script>
</html>
```

It's likely that we could extend this example to display an interactive example using the [Scene Explorer](https://kitware.github.io/vtk-js/examples/SceneExplorer.html) by embedding the displayer in the frame and then exporting a vtkjs file and "reading" it in from the server.  It would take a bit of work to put it together, but I'd start by creating a template for flask with:

```html
<iframe src="./SceneExplorer/index.html" width="100%" height="500px"></iframe>
```

**Comment by banesullivan** [comment]
We could pair this with vtk.js to have a canvas to capture the mouse events and translate those into camera movements that we can push back to the render window

**Comment by akaszynski** [comment]
> We could pair this with vtk.js to have a canvas to capture the mouse events and translate those into camera movements that we can push back to the render window

Exactly what I was thinking.  Just don't have time to do anything but a basic example, but that's a more permanent solution.
