### ISSUE TITLE
Merging overlapping PolyData simply appends point_arrays

### ISSUE THREAD

**Issue by MarkusZimmerDLR** [pyvista/pyvista#1202]
## Description
If overlapping PolyData is merged, the duplicate points are removed. However, the point_arrays are only appended.
In partially overlapping meshes, this completely messes with the data association.

## Example Data
```python
pv.Sphere().point_arrays['Normals'].shape                                                    
>>> (842, 3)
```
```python
pv.Sphere().merge(pv.Sphere()).point_arrays['Normals'].shape                                                    
>>> (1684, 3)
```
Even with additional parameters of merge function:
```python
pv.Sphere().merge(pv.Sphere(),  merge_points=True, main_has_priority=True).point_arrays['Normals'].shape                                                    
>>> (1684, 3)
```

Is there a preferred way of merging partially overlapping meshes featuring point data?

**Comment by JevinJ** [comment]
@MarkusZimmerDLR What version of pyvista are you using? I can't seem to reproduce this from latest master or 0.28.1.

```
>>> import pyvista as pv
>>>
>>> pv.Sphere().point_arrays['Normals'].shape
(842, 3)
>>> pv.Sphere().merge(pv.Sphere()).point_arrays['Normals'].shape
(842, 3)
>>> pv.Sphere().merge(pv.Sphere(),  merge_points=True, main_has_priority=True).point_arrays['Normals'].shape
(842, 3)
>>>
```

**Comment by JevinJ** [comment]
@akaszynski Can you reproduce this on your end?

**Comment by adeak** [comment]
I can't repro it either with master(ish) and 0.28.0. Both with vtk 9 on linux if that matters.

**Comment by akaszynski** [comment]
Can't reproduce it either.  @MarkusZimmerDLR, can you post a `pv.Report()`

```py
>>> import pyvista as pv
>>> pv.Sphere().merge(pv.Sphere(),  merge_points=True, main_has_priority=True).point_arrays['Normals'].shape
(842, 3)
```

### Report
```py
>>> pv.Report()
```
```
--------------------------------------------------------------------------------
  Date: Wed Feb 24 18:50:22 2021 MST

                OS : Linux
            CPU(s) : 8
           Machine : x86_64
      Architecture : 64bit
       Environment : IPython
        GPU Vendor : NVIDIA Corporation
      GPU Renderer : Quadro M620/PCIe/SSE2
       GPU Version : 4.5.0 NVIDIA 460.32.03

  Python 3.8.5 (default, Jul 28 2020, 12:59:40)  [GCC 9.3.0]

           pyvista : 0.28.1
               vtk : 9.0.1
             numpy : 1.19.2
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.6
            meshio : 4.3.10
        matplotlib : 3.3.4
           IPython : 7.20.0
             scipy : 1.6.1
              tqdm : 4.57.0
--------------------------------------------------------------------------------
```

**Comment by MarkusZimmerDLR** [comment]
I can confirm the flakiness.
First, I assumed I might have overwritten a pyvista global variable. So, I reran the test with a fresh ipython shell three times before opening the issue. 

Now, after changing **nothing** and opening a new shell for a 4th time, the error disappeared.
I think this is the definition of craziness.

Sorry for the inconvenience.
```
--------------------------------------------------------------------------------
  Date: Thu Feb 25 10:26:26 2021 CET

                OS : Linux
            CPU(s) : 16
           Machine : x86_64
      Architecture : 64bit
               RAM : 251.4 GB
       Environment : IPython
        GPU Vendor : NVIDIA Corporation
      GPU Renderer : Quadro RTX 4000/PCIe/SSE2
       GPU Version : 4.5.0 NVIDIA 418.39

  Python 3.6.3 |Anaconda custom (64-bit)| (default, Oct 13 2017, 12:02:49)  [GCC 7.2.0]

           pyvista : 0.27.4
               vtk : 8.1.2
             numpy : 1.19.5
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.6
            meshio : 4.3.8
        matplotlib : 3.3.1
             PyQt5 : 5.6
           IPython : 7.16.1
             scipy : 1.5.3
              tqdm : 4.43.0

  Intel(R) Math Kernel Library Version 2018.0.0 Product Build 20170720 for
  Intel(R) 64 architecture applications
--------------------------------------------------------------------------------
```

**Comment by MarkusZimmerDLR** [comment]
If I update numpy of the second config to 1.19.5 it does not change the issue.

If I update vtk to 9.0.1 it resolves the issue regarding the mesh merging.

However, the latter causes an issue in which the plots do not close anymore (on linux, not the Windows issue). If a plot is closed, the image just freezes but the blockage in the shell is freed. The window remains and can not be interacted with anymore.

Updating imageio to 2.9.0 resolves the latter issue as well.

Maybe this helps you to have a look on your project dependecies. Potentially they need an update (or the ones of vtk do).

Thanks for pointing in the right direction.

**Comment by adeak** [comment]
The window closing bug with VTK 9 is a well-known issue that unfortunately we couldn't patch downstream, we'll have to wait for it to be fixed in VTK itself (see also https://github.com/pyvista/pyvista/issues/1033 and e.g. https://github.com/pyvista/pyvista/pull/1031).

**Comment by MarkusZimmerDLR** [comment]
> 
> 
>  I'd be surprised if updating `imageio` made that go away.

You Sir are correct and I am dumb. I have mixed up the enviroments again...

So turns out anaconda 2020.02 ships with vtk 8.2.0 which does not seem to be a stable release, as it is not distributed via pypy. So I downgraded to 8.1.2 -> no merge bug, no window issue.

Sorry for causing unnecessary work.

**Comment by akaszynski** [comment]
> Sorry for causing unnecessary work.

Thanks for posting your solution here, and now others can know that 8.2.0 isn't a reliable package!
