### ISSUE TITLE
Can not add more than 5 objects the interactive plotter pyvista.PlotterITK() 

### ISSUE THREAD

**Issue by micmitch** [pyvista/pyvista#1205]
**Describe the bug, what's wrong, and what you expect:**

When I try a add more than 5 objects to pyvista.PlotterITK() none of them are displayed and the visualization panel is not created. No warnings or error messages are displayed in the notebook. I can visualize all of the objects that I am trying to add individually or in various groups of 5 or less. I don't think that the objects I'm trying to visualize so I don't think that I should be a memory problem. Many times once I break it I am then unable to visualize any of the objects. Restarting the kernel does not help. I usually have to completely close my notebook, kill the terminal process, and relaunch the notebook before I am able to visualized them again.  Any thoughts?

I also noticed that changing the color and opacity fields in my add_mesh or add_points function calls does not have any impact on the plot.

**To Reproduce**

Please include a code snippet to reproduce the bug in the block below:
Zip file with input files
[pyvistaTest_Files.zip](https://github.com/pyvista/pyvista/files/6051685/pyvistaTest_Files.zip)

```py
import pyvista
%pylab inline
%matplotlib inline

ophioliteBottom_polyData1 = pyvista.read('./ophioliteBottom_polyData1.vtp')
ophioliteBottom_Surface1 = pyvista.read('./ophioliteBottom_Surface1.vtp')
ophioliteBottom_polyData2 = pyvista.read('./ophioliteBottom_polyData2.vtp')
ophioliteBottom_Surface2 = pyvista.read('./ophioliteBottom_Surface2.vtp')

ophioliteTop_polyData1 = pyvista.read('./ophioliteTop_polyData1.vtp')
ophioliteTop_Surface1 = pyvista.read('./ophioliteTop_Surface1.vtp')
ophioliteTop_polyData2 = pyvista.read('./ophioliteTop_polyData2.vtp')
ophioliteTop_Surface2 = pyvista.read('./ophioliteTop_Surface2.vtp')

p2 = pyvista.PlotterITK()
# Bottom of the Ophiolite
p2.add_points(ophioliteBottom_polyData1,color='black')
p2.add_mesh(ophioliteBottom_Surface1, color='w', scalars=None, opacity=1., smooth_shading=False)
p2.add_points(ophioliteBottom_polyData2,color='black')
p2.add_mesh(ophioliteBottom_Surface2, color='w', scalars=None, opacity=1., smooth_shading=False)

# Top of the Ophiolite
# p2.add_points(ophioliteTop_polyData1,color='black')
# p2.add_mesh(ophioliteTop_Surface1, color='w', scalars=None, opacity=1., smooth_shading=False)
# p2.add_points(ophioliteTop_polyData2,color='black')
# p2.add_mesh(ophioliteTop_Surface2, color='w', scalars=None, opacity=1., smooth_shading=False)
# # p2.background_color = 'k'
p2.show()

```

**Screenshots**
![image](https://user-images.githubusercontent.com/13682778/109340059-5deb0480-781d-11eb-8c8d-51da45a4ba38.png)
![image](https://user-images.githubusercontent.com/13682778/109340159-7eb35a00-781d-11eb-91a3-7331cefb9dbb.png)

-----

**System Information:**
 Please run the following code wherever you are experiencing the bug and paste the output below. This report helps us track down bugs and it is critical to addressing your bug:

```py
# Get system info
import pyvista as pv
print(pv.Report())
```

```txt
--------------------------------------------------------------------------------
  Date: Fri Feb 26 10:22:27 2021 Pacific Standard Time

                OS : Windows
            CPU(s) : 8
           Machine : AMD64
      Architecture : 64bit
               RAM : 15.8 GB
       Environment : Jupyter
        GPU Vendor : Intel
      GPU Renderer : Intel(R) UHD Graphics 620
       GPU Version : 4.5.0 - Build 26.20.100.8141

  Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]

           pyvista : 0.27.4
               vtk : 9.0.1
             numpy : 1.19.2
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.6
            meshio : 4.3.8
        matplotlib : 3.3.4
         pyvistaqt : 0.3.0
             PyQt5 : 5.12.3
           IPython : 7.20.0
          colorcet : 1.0.0
     ipyvtk_simple : 0.1.4
             scipy : 1.6.1
        itkwidgets : 0.32.0
              tqdm : 4.56.0

  Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for
  Intel(R) 64 architecture applications
--------------------------------------------------------------------------------

```

**Comment by akaszynski** [comment]
If possible, can you try to use [itkwidgets]( https://github.com/InsightSoftwareConsortium/itkwidgets) directly and see if the problem persists?  I have a feeling that the issue can be traced to that module.

**Comment by micmitch** [comment]
Using itkwidgets directly does seem more stable. Thanks!

`import pyvista
import itk
from itkwidgets import view

%pylab inline
%matplotlib inline

ophioliteBottom_polyData1 = pyvista.read('./ophioliteBottom_polyData1.vtp')
ophioliteBottom_Surface1 = pyvista.read('./ophioliteBottom_Surface1.vtp')
ophioliteBottom_polyData2 = pyvista.read('./ophioliteBottom_polyData2.vtp')
ophioliteBottom_Surface2 = pyvista.read('./ophioliteBottom_Surface2.vtp')

ophioliteTop_polyData1 = pyvista.read('./ophioliteTop_polyData1.vtp')
ophioliteTop_Surface1 = pyvista.read('./ophioliteTop_Surface1.vtp')
ophioliteTop_polyData2 = pyvista.read('./ophioliteTop_polyData2.vtp')
ophioliteTop_Surface2 = pyvista.read('./ophioliteTop_Surface2.vtp')

view(geometries={'ophioliteBottom_polyData1':ophioliteBottom_polyData1, 
                 'ophioliteBottom_Surface1':ophioliteBottom_Surface1,
                 'ophioliteBottom_polyData2':ophioliteBottom_polyData2, 
                 'ophioliteBottom_Surface2':ophioliteBottom_Surface2,
                 'ophioliteTop_polyData1':ophioliteTop_polyData1, 
                 'ophioliteTop_Surface1':ophioliteTop_Surface1,
                 'ophioliteTop_polyData2':ophioliteTop_polyData2, 
                 'ophioliteTop_Surface2':ophioliteTop_Surface2})`

![image](https://user-images.githubusercontent.com/13682778/109348509-75c88580-7829-11eb-85d8-004803b0c765.png)

**Comment by micmitch** [comment]
I tried to set the geometry colors using the following code but I doesn't have any effect on the plot.

```python
view(geometries={'ophioliteBottom_polyData1':ophioliteBottom_polyData1, 
                 'ophioliteBottom_Surface1':ophioliteBottom_Surface1,
                 'ophioliteBottom_polyData2':ophioliteBottom_polyData2, 
                 'ophioliteBottom_Surface2':ophioliteBottom_Surface2,
                 'ophioliteTop_polyData1':ophioliteTop_polyData1, 
                 'ophioliteTop_Surface1':ophioliteTop_Surface1,
                 'ophioliteTop_polyData2':ophioliteTop_polyData2, 
                 'ophioliteTop_Surface2':ophioliteTop_Surface2},
                  geometry_colors=['white', 'red', 'white', 'red', 'white', 'yellow', 'white', 'yellow'])
```

**Comment by akaszynski** [comment]
Colors _should_ work, but I'm not 100%.  I'd raise the issue on https://github.com/InsightSoftwareConsortium/itkwidgets/issues

**Comment by banesullivan** [comment]
Closing as the PlotterITK class was deprecated and removed in #3737
