### ISSUE TITLE
Focus point of a plot can not be set

### ISSUE THREAD

**Issue by bschumac** [pyvista/pyvista#1206]
I can not set a focus point as described in the documentation to "set_focus(point)".
Am I doing something wrong or is this a bug?
Expected behaviour would be that the focus point is set however it is set to [0,0,0] instead.

**To Reproduce**

```py

plane = pv.Plane()
p = pv.Plotter()
p.add_mesh(plane, color="tan", show_edges=True)
p.set_focus((10,2,0))
p.show()


```

**System Information:**
 Windows 10 with Python 3.6.9

--------------------------------------------------------------------------------
  Date: Fri Feb 26 23:50:25 2021 Mitteleuropäische Zeit

                OS : Windows
            CPU(s) : 4
           Machine : AMD64
      Architecture : 64bit
               RAM : 11.7 GB
       Environment : Jupyter
        GPU Vendor : Intel
      GPU Renderer : Intel(R) HD Graphics 5500
       GPU Version : 4.4.0 - Build 20.19.15.4835

  Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 14:00:49) [MSC v.1915
  64 bit (AMD64)]

           pyvista : 0.28.1
               vtk : 9.0.1
             numpy : 1.19.2
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.6
            meshio : unknown
        matplotlib : 3.3.2
             PyQt5 : 5.9.2
           IPython : 7.16.1
             scipy : 1.5.2
              tqdm : 4.50.2

  Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for
  Intel(R) 64 architecture applications
--------------------------------------------------------------------------------

**Comment by tkoyama010** [comment]
@bschumac Thank you for reporting. it seems the bug of pyvista.
https://github.com/pyvista/pyvista/blob/641415bb80e2fcf3106d196936eba3a64b130e19/pyvista/plotting/renderer.py#L1108
It should be `focal_point` . Not `focus` .

**Comment by akaszynski** [comment]
For now, you should be able to move your mouse to a point or face on the mesh and then press "f".  We'll have to fix the behavior for the API.

**Comment by tkoyama010** [comment]
FYI this script is working.
```python
import pyvista as pv
import vtk

plane = pv.Plane()
p = pv.Plotter()
p.add_mesh(plane, color="tan", show_edges=True)

focal_point = (10,2,0)

camera = vtk.vtkCamera()
camera.SetFocalPoint(focal_point)
p.renderer.SetActiveCamera(camera)

p.disable_parallel_projection()
p.show()
```
![test](https://user-images.githubusercontent.com/7513610/109374992-9f9eac80-78fc-11eb-8b4e-75fb1408abc7.png)
