### ISSUE TITLE
how to use decimate function?

### ISSUE THREAD

**Issue by ghazalbangash** [pyvista/pyvista#1208]
Hi there 
i want to reduce the triangles of my mesh and tried using decimate function but it doesnt seem to bring any change in the number of cells of my mesh 
here is my code:
```py
import pyvista as pv   
mesh = pv.read("bunny.stl")
mesh = pv.PolyData(mesh)
p = pv.Plotter()

p.add_mesh(mesh,show_edges=True,color=True)
print(mesh.n_cells)
dec_sphere = mesh.decimate(0.5, volume_preservation=True)
print(mesh.n_cells)
```

am i using it wrong?cause i have the same issue using subdivide

**Comment by akaszynski** [comment]
Hello,

There's a minor problem with your example.  Since you're not updating the mesh `in-place`, you have to use the returned value of `decimate`:
```py
import pyvista as pv
from pyvista import examples
bunny = examples.download_bunny()
dec_bunny = bunny.decimate(0.9)

p = pv.Plotter(shape=(2, 1))
p.add_mesh(bunny, show_edges=True)
p.camera_position = 'xy'
p.camera.zoom(2)
p.subplot(1, 0)
p.add_mesh(dec_bunny, show_edges=True)
p.camera_position = 'xy'
p.camera.zoom(2)
p.show()
```

![tmp](https://user-images.githubusercontent.com/11981631/109392577-1c6c5f00-78da-11eb-8bc2-85e0f6da066f.png)

**Comment by ghazalbangash** [comment]
thanks a lot :D
