### ISSUE TITLE
 clip by scalar  (#874)

### ISSUE THREAD

**Issue by ylada** [pyvista/pyvista#1220]
At this time the clip_scalar either clips above a value or below a value (use invert). Would it be possible to clip by setting upper and lower bounds? For instance I like to clip a volume with scalar in the range of [0.5, 0.8]. 

Thank you!

**Comment by ylada** [comment]
Never mind. I figured to get around this issue, by doing two clips. Thank you.

**Comment by akaszynski** [comment]
Glad you got it figured out.  If possible, please post the code you used so others can use the same solution and we can reference this issue for similar problems.

**Comment by ylada** [comment]
I like to clip a StructuredGrid with scalar in the range of [0.5, 0.8]. The code is quite simple as follows:
# struct_grid is a StructuredGrid 
lower_bound = struct_grid.clip_scalar(value=0.5, invert=False)
upper_bound = lower_bound.clip_scalar(value=0.8, invert=True)

The upper_bound is the results in [0.5, 0.8].

**Comment by akaszynski** [comment]
Thanks!
