### ISSUE TITLE
add_floor colors wrong

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#1230]
The `add_floor` method is coloring the floor mesh now. They used to be a single, solid color

See https://docs.pyvista.org/examples/02-plot/floors.html#sphx-glr-examples-02-plot-floors-py

![sphx_glr_floors_001](https://user-images.githubusercontent.com/22067021/111492251-21b31180-8702-11eb-982e-e234aac30cd8.png)

**Comment by akaszynski** [comment]
It's a feature!

We'll have to fix this, still, it looks cool at least.

**Comment by adeak** [comment]
According to `git bisect` this was broken in https://github.com/pyvista/pyvista/commit/4eeb7992df03937b3f5c478f78ed072ad86b3d1c.

I can't say I understand what's going on, but I presume the rotation transform is what's messing with the planes.

**Comment by adeak** [comment]
And is it not weird that the dragon is tan in the screenshot? There's nothing setting it in the example, and it does come out white in my local run.

**Comment by akaszynski** [comment]
> And is it not weird that the dragon is tan in the screenshot? There's nothing setting it in the example, and it does come out white in my local run.

It's because we're using the `'document'` theme:
https://github.com/pyvista/pyvista/blob/45fe8b1c38712776f9b628a60a8662d0716dd52b/docs/conf.py#L21

**Comment by adeak** [comment]
Ah, tricky, thanks. I didn't realize there was an `rcParam` for this.

**Comment by banesullivan** [comment]
> I can't say I understand what's going on, but I presume the rotation transform is what's messing with the planes.

All we really need to do is call `clear_arrays()` before adding the floor to the scene
