### ISSUE TITLE
adding title to scalar_bar_args gives "add_scalar_bar() got multiple values for argument 'title'

### ISSUE THREAD

**Issue by bigfooted** [pyvista/pyvista#1231]
**Describe the bug, what's wrong, and what you expect:**

adding title to scalar_bar_args gives the error "add_scalar_bar() got multiple values for argument 'title'

The documentation says that we can set an alternative title of the default scalar bar by adding the keyword "title" , referring to the add_scalar_bar keywords https://docs.pyvista.org/plotting/plotting.html#pyvista.BasePlotter.add_scalar_bar:

sargs = dict(
            title="blabla new title ", 
            title_font_size=20,
            label_font_size=16,
            shadow=True,
            n_labels=3,
            italic=True,
            fmt="%.1f",
            font_family="arial",
)

However, this works when adding a second scalar bar using add_scalar_bar but not for the inline keyword scalar_bar_args. An example that works without the title keyword, but gives an error with the title keyword is given below

```
# read the multiblock data
dataset_multiblock = pv.read('config.vtm')

# first, we need to get the internal points
dataset = dataset_multiblock['Zone 0 (Incomp. Fluid)']['Internal'][0]

dataset.set_active_scalars("Passive_Scalar")

plotter = pvqt.BackgroundPlotter()

sargs = dict(
            title="blabla", 
            title_font_size=20,
            label_font_size=16,
            shadow=True,
            n_labels=3,
            italic=True,
            fmt="%.1f",
            font_family="arial",
)


plotter.add_mesh(dataset,show_edges=True,scalar_bar_args=sargs)

plotter.view_xy(negative=False)

# Then in another cell, you can add more to the plotter
plotter.show_bounds()
```

--------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-82921243c316> in <module>
     23             font_family="arial",
     24 )
---> 25 plotter.add_mesh(dataset,show_edges=True,scalar_bar_args=sargs)
     26 
     27 plotter.view_xy(negative=False)

```
~/anaconda3/lib/python3.8/site-packages/pyvista/plotting/plotting.py in add_mesh(self, mesh, color, style, scalars, clim, show_edges, edge_color, point_size, line_width, opacity, flip_scalars, lighting, n_colors, interpolate_before_map, cmap, label, reset_camera, scalar_bar_args, show_scalar_bar, stitle, multi_colors, name, texture, render_points_as_spheres, render_lines_as_tubes, smooth_shading, ambient, diffuse, specular, specular_power, nan_color, nan_opacity, culling, rgb, categories, silhouette, use_transparency, below_color, above_color, annotations, pickable, preference, log_scale, render, **kwargs)
   1905         # Add scalar bar if available
   1906         if stitle is not None and show_scalar_bar and (not rgb or _custom_opac):
-> 1907             self.add_scalar_bar(stitle, **scalar_bar_args)
   1908 
   1909         self.renderer.Modified()

TypeError: add_scalar_bar() got multiple values for argument 'title'

```

**Comment by bigfooted** [comment]
I would like to add that of course setting the title with stitle="blabla" and removing title="" from the sargs dict is working, but the documentation suggest that the above should also work.

**Comment by akaszynski** [comment]
> There should be one-- and preferably only one --obvious way to do it.

I think this is a clear example how the args in the `add_mesh` method need to be cleaned up.  I'm about to propose in a PR that we depreciate `stitle` in favor of `scalar_bar_args['title'].  I'll provide a user warning first since this is a fairly big change, but I've been using `stitle` instead of `show_scalar_bar` and `scalar_bar_args`, which is the obvious choice.

**Comment by adeak** [comment]
@akaszynski can this be closed now?

**Comment by bigfooted** [comment]
Thank you for the fast response, I appreciate it.

**Comment by akaszynski** [comment]
> @akaszynski can this be closed now?

Yes.

@bigfooted, this will be out on our next release.
