### ISSUE TITLE
Saving/pickling the "entire plot"?

### ISSUE THREAD

**Issue by sampotter** [pyvista/pyvista#1234]
Sorry if this question has an obvious answer, but after setting up a plotter, adding meshes to it, etc.---that is, getting to the point where I am happily inspecting the plot, rotating it around, zooming in and out---can I save the whole thing to disk and reload it later? I know that I can take screenshots and make movies. However, I have a large number of plots that I'm generating for testing purposes. I'd like to be able to generate them all in a batch, then open them up and inspect them one at a time afterwards. I can't tell in advance which part of each plot I'm going to want to inspect.

**Comment by banesullivan** [comment]
You can export scenes to a couple of formats. See:

- https://docs.pyvista.org/plotting/plotting.html#pyvista.BasePlotter.export_obj
- https://docs.pyvista.org/plotting/plotting.html#pyvista.BasePlotter.export_vtkjs

However, this won't preserve many of PyVista's plotting options so it depends on what you are including in your scene (e.g. axes actors, widgets, special lighting, special render techniques

I would suggest preformatting all of your data (run filters, transforms, etc) then have that out and have a minimal PyVista script to plot those data

**Comment by banesullivan** [comment]
I'll leave this in PyVista as a feature request because I believe there are methods of serializing a VTK scene graph which we do not currently leverage but this needs further investigation

**Comment by sampotter** [comment]
Had no trouble with either of these methods, but at least for what I'm doing `export_obj` was close to useless. Compare a screenshot of the original scene:

![cutset](https://user-images.githubusercontent.com/6035363/112343124-34e15680-8c99-11eb-8417-e9e672e276a8.png)

with the macOS quicklook (spacebar) view of the exported OBJ:

<img width="780" alt="Screen Shot 2021-03-24 at 12 06 43 PM" src="https://user-images.githubusercontent.com/6035363/112343294-5c382380-8c99-11eb-9899-277f088cbfbd.png">

I haven't had any problems with using quicklook to preview OBJ files before, so I'm assuming this OBJ file is correctly displayed.

As for `export_vtkjs`, I was able to save a .vtkjs file to disk, but after 5 minutes of research was unable to figure out how to view the contents of this file. ;-)

---

For the feature request, it would be nice to be able to just do something like: `plotter.save('blah'); Plotter.from_file('blah').show()` (or similar).

**Comment by banesullivan** [comment]
the vtkjs file can be viewed with VTK.js' standalone scene loader which we host here: http://viewer.pyvista.org

And originated from here: https://kitware.github.io/vtk-js/examples/StandaloneSceneLoader.html

**Comment by banesullivan** [comment]
The issue you're noticing with the exporting OBJ file is likely because the VTK OBJ exporter isn't properly exporting the lighting, etc.

**Comment by banesullivan** [comment]
For this somewhat simple scene, the vtkjs exported should capture everything.

**Comment by banesullivan** [comment]
As I mention in https://github.com/pyvista/pyvista/pull/698#issue-409107010, there are some new features in VTK 9 that might handle this. I'll try to research this when/if I find time

**Comment by sampotter** [comment]
Thanks, that works. After dragging and dropping, got this:

<img width="687" alt="Screen Shot 2021-03-24 at 12 14 56 PM" src="https://user-images.githubusercontent.com/6035363/112344480-83432500-8c9a-11eb-8a98-8495fb7f2291.png">

Loading the scene took a while... maybe 3-4s. But this should work OK for now.
