### ISSUE TITLE
'UnstructuredGrid' object has no attribute 'cast_to_explicit_structured_grid'

### ISSUE THREAD

**Issue by alialigaga** [pyvista/pyvista#1235]
i try to use the 'cast_to_explicit_structured_grid'method 
![image](https://user-images.githubusercontent.com/47970933/112444196-bfed4a00-8d88-11eb-874c-cf9235492061.png)
![image](https://user-images.githubusercontent.com/47970933/112444870-74876b80-8d89-11eb-93e8-e7ffe1da365e.png)
I get back this error message and I dont know why T.T

**Comment by banesullivan** [comment]
Upgrade your version of PyVista. This is a recently released feature.
