### ISSUE TITLE
How to make spot lights cast a shadow?

### ISSUE THREAD

**Issue by subodh-malgonde** [pyvista/pyvista#1241]
I have tried looking for this in the docs and examples. Directional lights cast a shadow, however positional lights (like spot light) do not seem to cast a cast a shadow.

Here is an example of 3 planes, positioned one behind the other. **The spot light seems to pass through all the planes.**

```
plotter = pv.Plotter(lighting='none')
attenuation_values = (2, 0, 0)

for plane_y in [2, 5, 10]:
    screen = pv.Plane(center=(0, plane_y, 0), direction=(0, 1, 0), i_size=5, j_size=5)
    plotter.add_mesh(screen, color='white')

light = pv.Light(position=(0, 0, 0), focal_point=(0, 1, 0), color='cyan')
light.positional = True
light.cone_angle = 15
light.intensity = 5
light.attenuation_values = attenuation_values
light.show_actor()

plotter.add_light(light)

plotter.view_vector((1, -2, 2))
plotter.show()
```

![Screenshot from 2021-03-30 18-30-50](https://user-images.githubusercontent.com/5463437/112992802-25c14380-9186-11eb-991f-99428c8ab296.png)

**Comment by banesullivan** [comment]
Done in #1247 ?

**Comment by adeak** [comment]
Indeed, this is now implemented in master with the above example featured in the Examples section of the docs (with the next release).
