### ISSUE TITLE
error while making pyvista standalone 

### ISSUE THREAD

**Issue by ghazalbangash** [pyvista/pyvista#1244]
Hi 
i am trying to make a standalone of my application which is using pyvista,as instructed i added the hidden imports in my specs file  and it compiled just fine but i get the following error while running my .exe file 
i have vtk==9 installed 
![err](https://user-images.githubusercontent.com/47847589/113472316-ad090280-9477-11eb-8962-342b89b90f74.png)

**Comment by akaszynski** [comment]
When I freeze pyvista I add the following:
```py
# for pyinstaller

# vtk 8.1.2
try:
    from vtk import numpy_interface
except:
    pass

# from VTK 9+
try:
    from vtkmodules import numpy_interface
except:
    pass
```

Can you try adding a similar module to your `hiddenimports` and see if that fixes it?  If so, let me know and we can update the docs.

**Comment by ghazalbangash** [comment]
Yesss this fixed my problem, although  I had to add "vtkmodules.numpy_interface.dataset_adapter" to my hiddenimports too ,incase someone else encounters this issue.
Thanks a lot :
