### ISSUE TITLE
Extend multi_colors to allow custom cyclers to be passed through

### ISSUE THREAD

**Issue by adeak** [pyvista/pyvista#1270]
Currently `BasePlotter.add_mesh` supports the bool keyword `multi_colors`. When `True` and matplotlib is installed and the input mesh is a `MultiBlock`, each mesh will be plotted using colours from the default [matplotlib color cycler](https://matplotlib.org/stable/tutorials/intermediate/color_cycle.html).

We could extend the meaning of this keyword to allow custom cycler instances to be passed, allowing the user to customize their `MultiBlock` plotting with ease.

**Comment by abhiramtilakiiit** [comment]
This can be done easily, by using the `get_cycler` in [colors.py](https://github.com/pyvista/pyvista/blob/main/pyvista/plotting/colors.py). Can you assign me this, if this issue is still relevant

**Comment by adeak** [comment]
Sorry @abhiramtilakiiit, I don't even have the bandwidth to tell if this is still relevant. I've assigned the issue to you. Thanks a lot for your contribution :)
