### ISSUE TITLE
Why does pyvista.Cube return a mesh with 24 points instead of just 8 points?

### ISSUE THREAD

**Issue by subodh-malgonde** [pyvista/pyvista#1272]
If we create a cube get a `PolyData` object with 24 points.  
```
import pyvista as pv

cube = pv.Cube()
print(cube)
```
Here is the output of the print statement (only the header part is shown):

PolyData|Information
--|--
N Cells | 6
N Points | 24
X Bounds | -5.000e-01, 5.000e-01
Y Bounds | -5.000e-01, 5.000e-01
Z Bounds | -5.000e-01, 5.000e-01
N Arrays | 2

Shouldn't it have just 8 points, sufficient to define a cube? When we inspect the `points` attribute we can see that points are repeated 3 times:

```
>>> print(cube.points)
pyvista_ndarray([[-0.5, -0.5, -0.5],
                 [-0.5, -0.5,  0.5],
                 [-0.5,  0.5, -0.5],
                 [-0.5,  0.5,  0.5],
                 [ 0.5, -0.5, -0.5],
                 [ 0.5, -0.5,  0.5],
                 [ 0.5,  0.5, -0.5],
                 [ 0.5,  0.5,  0.5],
                 [-0.5, -0.5, -0.5],
                 [-0.5, -0.5,  0.5],
                 [ 0.5, -0.5, -0.5],
                 [ 0.5, -0.5,  0.5],
                 [-0.5,  0.5, -0.5],
                 [-0.5,  0.5,  0.5],
                 [ 0.5,  0.5, -0.5],
                 [ 0.5,  0.5,  0.5],
                 [-0.5, -0.5, -0.5],
                 [ 0.5, -0.5, -0.5],
                 [-0.5,  0.5, -0.5],
                 [ 0.5,  0.5, -0.5],
                 [-0.5, -0.5,  0.5],
                 [ 0.5, -0.5,  0.5],
                 [-0.5,  0.5,  0.5],
                 [ 0.5,  0.5,  0.5]], dtype=float32)
```

**Comment by whophil** [comment]
There are six faces, each face has 4 points. Naively, there are 24 points, but only 8 unique ones.

It would also be possible to create a cube from only 8 points, but this is not what the Cube method is doing. For what it's worth, this behavior comes from the vtkCubeSource filter that is being called under the hood.

**Comment by banesullivan** [comment]
Thanks, @whophil! Indeed this a "feature" of the underlying vtkCubeSource. You can run `.clean()` on the cube to merge the duplicate points.

Closing this due to it being an upstream issue out of our control
