### ISSUE TITLE
Widget examples on Binder are not interactive

### ISSUE THREAD

**Issue by aplowman** [pyvista/pyvista#1277]
**Describe the bug, what's wrong, and what you expect:**

I clicked the Binder link in `README.rst` and navigated to the `examples/03-widgets`. None of the notebooks within this directory appear to produce interactive widgets. Instead they generate static images (PNGs). I have tried in both Edge 91.0.852.0 and Firefox 87. I believe the notebooks are meant to produce interactive outputs due to the commonly included text: `After interacting with the scene, ...`

**System Information:**
N/A

**Comment by banesullivan** [comment]
This is fixed as of now
