### ISSUE TITLE
pyvista causes dead kernel in Github Actions using jupytext.

### ISSUE THREAD

**Issue by trhallam** [pyvista/pyvista#1282]
I'm running jupytext with --execute to convert py files to executed notebooks for documentation using Github Actions.

One example notebook uses pyvista for plotting and when the plotting is active is causes the kernel to die.

https://github.com/trhallam/segysak/runs/2401795495?check_suite_focus=true

Deactivating all of the pyvista components of the example allows the example to run ok.

Locally the example runs fine so I'm thinking:

- Graphics on the Server is required?, or
- The pyvista engine needs to be manually shut down somehow?

This is the example, currently the pyvista portion at the bottom is disabled.
https://github.com/trhallam/segysak/blob/main/examples/example_subsurface.py

And this is the plotting function in `subsurface`.

https://github.com/softwareunderground/subsurface/blob/7db7eabce2f16283484d40f0e2ee6b19d74464d1/subsurface/visualization/to_pyvista.py#L19-L73

Python=3.8
Host: ubuntu-latest

**Comment by akaszynski** [comment]
Sorry for the late reply.

> Graphics on the Server is required?

Yes.  The easiest way to do this is with `xvfb-run ...`.  For example:

```
xvfb-run make -C docs
```

**Comment by trhallam** [comment]
Works like a charm, cheers.

https://segysak.readthedocs.io/en/latest/examples/example_subsurface.html
