### ISSUE TITLE
jupyterlab pyvista.PlotterITK() resulting in Error displaying widget: model not found

### ISSUE THREAD

**Issue by muh-hassani** [pyvista/pyvista#1288]
Inside jupyterlab, I would like to use pyvista to visualize some data on a structured mesh. But I get `Error displaying widget: model not found`. I am using pyvista=0.29.1, itkwidgets=0.32.0 and Jupyterlab=3.0.14. I have installed all from conda-forge channel.
here is the script I used.
```python3
import pyvista as pv
from itkwidgets import view
import itk
inc=20
mesh = pv.read(os.path.basename(job.output_file.split('.')[0]) + f'_inc0{inc}.vtr')  #enter the file name you wish to view
pl = pv.PlotterITK()
pl.add_mesh(mesh)
pl.show()
```
I read in [some other issues](https://github.com/pyvista/pyvista/issues/332) that Ipython Widgets support is removed from PyVista. I wonder if there is an alternative?

**Comment by akaszynski** [comment]
We're in the process of updating the docs, but in short `itkwidgets` isn't supported as of yet in Jupyterlab 3.x:
https://github.com/InsightSoftwareConsortium/itkwidgets/issues/405

For the appropriate docs, see:
https://dev.pyvista.org/jupyter/index.html#state-of-3d-interactive-jupyterlab-plotting

We'll have update jupyterlab support soon.
