### ISSUE TITLE
start_position in streamlines filter does nothing

### ISSUE THREAD

**Issue by MatthewFlamm** [pyvista/pyvista#1291]
**Describe the bug, what's wrong, and what you expect:**

streamlines accepts a `start_position` parameter, but it is unused.  If `pointa` and `pointb` are not supplied, then a sphere source is always used.  This prevents `start_position` from having any effect.

-----

**To Reproduce**

Both of the lines below return sources with 100 points on a sphere at the same location.

```py
stream, src = mesh.streamlines(return_source=True)
# doesn't matter what start_position is
stream2, src2 = mesh.streamlines(return_source=True, start_position=(1, 1, 1))
```

**Screenshots**

-----

**System Information:**
 Please run the following code wherever you are experiencing the bug and paste the output below. This report helps us track down bugs and it is critical to addressing your bug:

```py
# Get system info
import pyvista as pv
print(pv.Report())
```

```txt


```

**Comment by guido-granda** [comment]
Hi, 
I get a streamline using a start_position on the following way:

`stream,src = mesh.streamlines('vectors',start_position=[x,y,z],n_points=1,return_source=True)`

However, when I plot the source like this:

`p.add_mesh(pv.PolyData(src), color='red', point_size=15, render_points_as_spheres=True)`

It is plotted in a different position than the provided one.
