### ISSUE TITLE
Instancing?

### ISSUE THREAD

**Issue by sampotter** [pyvista/pyvista#1295]
I've found that doing something like:

```py
...
for i in range(big_number):
    plotter.add_mesh(pv.Sphere(...), ...)
...
```

is _very_ slow. Is there a way to do this quickly? If `big_number` is only a `moderate_number` (say, `== 1000`), this still takes a very long time, but should be close to instantaneous. I can time how long this takes if it's helpful, but it easily takes 10+ seconds. I haven't looked into where the bottleneck is.

I was using this approach to plot vector fields, which is very slow, but eventually found the "glyph" feature, which solved the problem for `pv.Arrow`, but I had a hard time understanding whether I could use glyphs to do more general instancing.

For example, I'd like to be able to highlight certain edges in a triangle mesh by plotting a large number of `pv.Cylinder` instances.

**Comment by MatthewFlamm** [comment]
This seems better suited for https://github.com/pyvista/pyvista-support

According to the documentation you can use `pv.Cylinder` with `glyph` filter.   See first example [here](https://docs.pyvista.org/examples/01-filter/glyphs.html#plotting-glyphs-vectors-or-polydata) which has a comment saying it can be any `DataSet`, not just `pv.Arrow`.

**Comment by JBum21** [comment]
For a good glyph example of other instances, please see [pyvista-support #171](https://github.com/pyvista/pyvista-support/issues/171).

In addition to using the glyph feature (of which other geometries can be used than just arrows), I've found that adding individual meshes to a MultiBlock is _much_ faster than combining individual meshes.


for example:
`block = pv.MultiBlock()

for mesh in meshes:


Create your mesh

**Comment by MatthewFlamm** [comment]
I also like to use `MultiBlock` whenever possible, but here it only helps marginally when compared to `glyph`. This example gives a minor improvement when using `MultiBlock`, but another 10x improvement when using `glyph`.

```python
def use_glyph_spheres(n=100):
    p = pv.Plotter()
    line = pv.Line(resolution=100)
    glyphs = line.glyph(geom=pv.Sphere())
    p.add_mesh(glyphs)
    p.close()
    
def plot_inside(n=100):
    p = pv.Plotter()
    for i in range(n):
        p.add_mesh(pv.Sphere())
    p.close()
    
def plot_multiblock(n=100):
    p = pv.Plotter()
    spheres = pv.MultiBlock([pv.Sphere() for i in range(n)])
    p.add_mesh(spheres)
    p.close()

%timeit use_glyph_spheres()
%timeit plot_multiblock()
%timeit plot_inside()
```

gives:

```txt
175 ms ± 17.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
2.01 s ± 184 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
3.16 s ± 71.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

**Comment by sampotter** [comment]
Ah, I wasn't aware of pyvista-support!

At any rate, all of your examples are extremely helpful and completely solve my problem. Thanks!

I'll go ahead and close this, now...
