### ISSUE TITLE
pyvista installation on Mac 

### ISSUE THREAD

**Issue by adhikarig** [pyvista/pyvista#1307]
Hi all,

I could not install pyvista on my mac, with latest OS update.  I installed Python 3.9.5 via Homebrew.   I used pip installation.
Can anyone help me to install pyvista on mac.

Thanks in advance.

Gopal

**Comment by akaszynski** [comment]
``vtk`` isn't available for Python 3.9 on MacOS, unless you can install it using the Anaconda distribution.  I've found that except for Linux, the Anaconda distribution is a great way of managing Python environments, and you can often fine additional packages there.

If you'd prefer using homebrew, go with Python 3.8 until kitware can get the time to put out a vtk9 wheel for Python 3.8.
