### ISSUE TITLE
STL solid labelling not parsed from file

### ISSUE THREAD

**Issue by LucaZampieri** [pyvista/pyvista#1311]
[feature request]
I am reading multi-part STLs and would like then to get access to the solid labeling. This seems not supported by pyvista at the moment. 
I might do a PR, but if someone has an idea of where to look, I would gladly accept pointers :) 

This feature could be useful for:
- visualisation
- for splitting them (then either do some processing+viz, or saving them as separate files)

## Paraview screen shot of two solids of one facet each
<img width="670" alt="image" src="https://user-images.githubusercontent.com/26366811/118114194-8e3b4b80-b3e7-11eb-8413-5cdd18f671dc.png">
## Pyvista mesh information
<img width="226" alt="image" src="https://user-images.githubusercontent.com/26366811/118115261-022a2380-b3e9-11eb-8e3b-3a8001158550.png">

From here it would appear that vtk can read the different solid, but cannot write them (https://vtk.org/pipermail/vtkusers/2014-May/084077.html)

Data to reproduce (stl ascii with 2 solids of one facet each)
[solid_labels_altered.stl.zip](https://github.com/pyvista/pyvista/files/6471930/solid_labels_altered.stl.zip)

**Comment by LucaZampieri** [comment]
When reading with paraview, writing a vtp and loading it with pyvista I get what I expect:
<img width="668" alt="image" src="https://user-images.githubusercontent.com/26366811/118119727-1cff9680-b3ef-11eb-8b06-c4e9e859bc5a.png">

**Comment by whophil** [comment]
Hi Luca. The functionality you want is available in VTK, but is not exposed in PyVista yet.  However, this will do what you want.

```python
import pyvista as pv
import vtk

reader = vtk.vtkSTLReader()
reader.SetScalarTags(True)
mesh = pv.standard_reader_routine(reader, 'solid_labels_altered.stl')
```

**Comment by LucaZampieri** [comment]
Hi Phil, thanks a lot for your reply, this is exactly what I need. 

This issue can be closed, unless we think this is worth having directly in Pyvista: I think it makes sense at least for the STL reader, but does someone have a similar use case (i.e. needs the scalar tags to be read) with other formats supported by vtk?

**Comment by whophil** [comment]
The `standard_reader_routine` method takes an optional `attrs` argument which allows the user to invoke arbitrary methods of the VTK reader class. This is not exposed to pv.read(), but it could be. It might make the interface a bit more confusing, because pv.read() also delegates to non-VTK readers, depending on file extension.

If you know which VTK reader you are using and what you want to call on it, I think using `standard_reader_routine` directly is the best option. It is technically part of the public interface. Maybe it could have a better name and documentation.

**Comment by whophil** [comment]
I wrote a message earlier which was totally incorrect. Here is a one-liner.
```python
import pyvista as pv
mesh = pv.read('/Users/phil/Downloads/solid_labels_altered.stl', attrs={'SetScalarTags': True})
```

**Comment by LucaZampieri** [comment]
Ok thanks, I should have noticed that!

This then solves everything that was discussed in this issue which can now be closed! 
(whether these should be read by default is another discussion)
