### ISSUE TITLE
Removing a mesh actor doesn't remove its scalar bar in 0.30.1

### ISSUE THREAD

**Issue by JacobBumgarner** [pyvista/pyvista#1313]
The recent update has led to some scalar bar issues when removing/adding mesh actors. If clearing the entire plotter after removing the mesh, the scalar bar disappears, but the lighting is also disrupted.
In PyVista 0.29.1, removing a mesh also removed it's scalar bar. I am using PyVista 0.30.1 and pyvistaqt 0.4.0 in these videos.

After doing a bunch of digging,  this is happening because `def _remove_mapper_from_plotter(...)` was removed from the renderers.py file and wasn't replaced anywhere in the new ScalarBars class. I am happy to try to help get this figured out, but I have no experience with Github management.

**Comment by JacobBumgarner** [comment]
PyVista 0.29.1. When calling clear:

In the plotter:
```
    def clear(self):
        """Clear plot by removing all actors and properties."""
        for renderer in self.renderers:
            renderer.clear()
        self._shadow_renderer.clear()
        for renderer in self._background_renderers:
            if renderer is not None:
                renderer.clear()
        self._scalar_bar_slots = set(range(MAX_N_COLOR_BARS))
        self._scalar_bar_slot_lookup = {}
        self._scalar_bar_ranges = {}
        self._scalar_bar_mappers = {}
        self._scalar_bar_actors = {}
        self._scalar_bar_widgets = {}
        self.mesh = None
```

In the renderers:
```
    def clear(self):
        """Remove all actors and properties."""
        if self._actors:
            for actor in list(self._actors):
                try:
                    self.remove_actor(actor, reset_camera=False, render=False)
                except KeyError:
                    pass

        self.remove_all_lights()
        self.RemoveAllViewProps()
        self.Modified()
```

**Comment by JacobBumgarner** [comment]
In PyVista 0.30.1

In the plotter:
``` Python
    def clear(self):
        """Clear plot by removing all actors and properties."""
        self.renderers.clear()
        self.scalar_bars.clear()
        self.mesh = None
```

Renderers call:
``` Python
    def clear(self):
        """Remove all actors and properties."""
        if self._actors:
            for actor in list(self._actors):
                try:
                    self.remove_actor(actor, reset_camera=False, render=False)
                except KeyError:
                    pass

        self.remove_all_lights()
        self.RemoveAllViewProps()
        self.Modified()

        self._scalar_bar_slots = set(range(MAX_N_COLOR_BARS))
        self._scalar_bar_slot_lookup = {}
```


scalar_bars call:
``` Python
    def clear(self):
        """Remove all scalar bars and resets all scalar bar properties."""
        self._scalar_bar_ranges = {}
        self._scalar_bar_mappers = {}
        self._scalar_bar_actors = {}
        self._scalar_bar_widgets = {}
```

**Comment by JacobBumgarner** [comment]
PyVista 0.29.1 calling `plotter.remove_scalar_bar()`:

``` Python
    def remove_scalar_bar(self):
        """Remove the scalar bar."""
        if hasattr(self, 'scalar_bar'):
            self.remove_actor(self.scalar_bar, reset_camera=False)
```

PyVista 0.30.1 calling `plotter.scalar_bars.remove_scalar_bar()`
``` Python
    def remove_scalar_bar(self, title=None, render=True):
        """Remove a scalar bar.
        Parameters
        ----------
        title : str, optional
            Title of the scalar bar to remove.  Required if there is
            more than one scalar bar.
        render : bool, optional
            Render upon scalar bar removal.  Set this to ``False`` to
            stop the render window from rendering when an scalar bar
            is removed.
        """
        if title is None:
            if len(self) > 1:
                titles = ', '.join('"{key}"' for key in self._scalar_bar_actors)
                raise ValueError('Multiple scalar bars.  Specify the title of the'
                                 f'scalar bar from one of the following:\n{titles}')
            else:
                title = list(self._scalar_bar_actors.keys())[0]

        self._scalar_bar_ranges.pop(title)
        self._scalar_bar_mappers.pop(title)
        widget = self._scalar_bar_widgets.pop(title, None)
        if widget is not None:
            widget.SetEnabled(0)

        actor = self._scalar_bar_actors.pop(title)
        self._plotter.remove_actor(actor, render=render)
```

**Comment by akaszynski** [comment]
> After doing a bunch of digging, this is happening because def _remove_mapper_from_plotter(...) was removed from the renderers.py file and wasn't replaced anywhere in the new ScalarBars class.

Nice work figuring it out!  I think this warrants a patch release.

> I am happy to try to help get this figured out, but I have no experience with Github management.

It's actually not too bad, and it's impossible for you to mess something up since the pyvista developer community has to review your request.  There's a few approaches to creating a Pull Request (PR) with your suggested changes.  Here's one way:
- "Fork" the repo (upper right, can't miss it).  This makes a copy a user local copy of the repo that you can create branches on.
- Create a new branch (ether online using the web editor or locally after cloning with `git branch -b fix/scalarbar_remove_mapper`
- Create the changes, commit, push, and then create a PR with the target branch being `pyvista/master`
- Optionally, run the unit tests locally, and feel free to add in a new test to verify that the scalar bar is removed once the corresponding mesh is removed.

If this isn't your cup of tea, don't worry, we can create one.  You saved us a ton of time by pointing out the issue.  Please let us know what your intentions are.
