### ISSUE TITLE
DOCS: Links in method list inside filters page don't work

### ISSUE THREAD

**Issue by MatthewFlamm** [pyvista/pyvista#1320]
**Describe the bug, what's wrong, and what you expect:**

Definitions of filter methods don't link to the detailed definitions in the class summary below.  This works in other pages like object.  A picture is easier to explain.  `cell_centers` does not link to the more detailed description below in the page.  A user must do a ctrl-f to find it since this page is so long with multiple sections.

![image](https://user-images.githubusercontent.com/39341281/118518011-bbe50500-b705-11eb-9b9d-c9704ba8bbab.png)

**Comment by tkoyama010** [comment]
@MatthewFlamm Thanks for your report. I will fix it.

**Comment by adeak** [comment]
This seems to be fixed now as of https://github.com/pyvista/pyvista/pull/1385 and https://github.com/pyvista/pyvista/pull/1386, see https://dev.pyvista.org/api/core/_autosummary/pyvista.DataSetFilters.html#pyvista.DataSetFilters. Please check.

**Comment by MatthewFlamm** [comment]
Looks fixed!

**Comment by akaszynski** [comment]
Works for me.  Closing.

**Comment by tkoyama010** [comment]
@adeak  @akaszynski  Thanks for closing.
