### ISSUE TITLE
Parallel projection properties missing

### ISSUE THREAD

**Issue by Keou0007** [pyvista/pyvista#1333]
[This PR](https://github.com/pyvista/pyvista/pull/1021) was merged into 0.28.0, providing easy access to parallel projection options in the plotter. Since I've recently updated to 0.30.1 this functionality appears to have been removed, which has broken my code that was running just fine thanks. Why has this regressed?

**Comment by adeak** [comment]
I can see https://github.com/pyvista/pyvista/blob/0.30.1/pyvista/plotting/plotting.py#L470-L488 in `plotting,py` and https://github.com/pyvista/pyvista/blob/0.30.1/pyvista/plotting/renderer.py#L1209-L1229 in `renderer.py`. These seem to be the functionality you're referring to.

Can you show a specific example of the functionality that used to work but now does not?

**Comment by Keou0007** [comment]
Hmmm. That's interesting. 

This is how simple I got when I was trying to debug what wasn't working in my more complicated code. I was setting the attribute, which was working just fine except the output renders looked wrong because it wasn't actually changing anything. Now I'm going to have to investigate further and see why this isn't working for me. I've probably done something stupid...

```
import pyvista as pv
p = pv.Plotter()
p.parallel_scale
Traceback (most recent call last):
  File "/Users/shannon/opt/miniconda3/envs/pywakes/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-11-08b0e6e17f89>", line 1, in <module>
    p.parallel_scale
AttributeError: 'Plotter' object has no attribute 'parallel_scale'
```

**Comment by adeak** [comment]
Then the most obvious culprit would be that your env doesn't actually have 0.30. Can you check the `pv.Report()`?

**Comment by Keou0007** [comment]
yup, it was an env issue. I'm an idiot. Move along :P
