### ISSUE TITLE
Cells and points picking are broken after setting a scale

### ISSUE THREAD

**Issue by yorfy** [pyvista/pyvista#1335]
**Describe the bug, what's wrong, and what you expect:**

Cells or points picking are broken after setting a scale
-----

**To Reproduce**
```py
### code snipset from https://github.com/pyvista/pyvista-support/issues/72
### just adding "p.set_scale(zscale=10)" before show

import pyvista as pv
from pyvista import examples
import numpy as np

grid = pv.UnstructuredGrid(examples.hexbeamfile)

d = np.zeros_like(grid.points)
d[:, 1] = grid.points[:, 2]**3/250

array_name = 'Y Displacement'
grid[array_name] = d[:, 1]

grid.points += d
cpos = [(12, 6, 3.6),(0.0, 0.375, 2.0),(-0.425, 0.9, -0.068)]

p = pv.Plotter(notebook=0)
p.add_mesh(grid, show_edges=True, scalars=array_name, 
           clim=[-d.max(), d.max()])
p.add_axes()
p.camera_position = cpos

dargs = dict(name='labels', font_size=24)

def callback(mesh, pid):
    point = grid.points[pid]
    label = ['ID: {}\n{}: {}'.format(pid, 
                                     array_name, 
                                     grid[array_name][pid])]
    p.add_point_labels(point, label, **dargs)

p.enable_point_picking(callback=callback, show_message=True, 
                       color='pink', point_size=10, 
                       use_mesh=True, show_point=True)

p.set_scale(zscale=10)

p.show()
```

**Comment by akaszynski** [comment]
I can reproduce this, but I'm not sure if there's a fix for this outside of VTK.  I'll raise an issue for this within Kitware's VTK.

**Comment by yorfy** [comment]
Thank you Alex.
For information, the vtkAreaPicker does not seems to be impacted by this issue. I have been able to prototype a method that picks an area around the mouse display position. Then I use picker.GetFrustum() and the _clip_with_function filter to retrieve points of cells of the desired polydata inside this selection area.

**Comment by akaszynski** [comment]
Thanks for posting your solution here so others can workaround this issue.

**Comment by banesullivan** [comment]
@yorfy, so is the issue with our use of `vtkRenderedAreaPicker` here and using `vtkAreaPicker` mitigates this? If so, we could add a check at this line to use `vtkAreaPicker` if the plotter is scaled:

https://github.com/pyvista/pyvista/blob/fd14e16f22db6d485a8bfe4101b39bbcb83a88c6/pyvista/plotting/picking.py#L205

Though this would only work if setting the scale prior to enabling picking.

I haven't played around with this at all, but there is probably a good reason we're using `vtkRenderedAreaPicker` over `vtkAreaPicker` for general use.

**Comment by yorfy** [comment]
HI @banesullivan, there is no issue using `enable_cell_picking ` after setting a scale. The implementation using `vtkRenderedAreaPicker` seems ok. The problem is when using `enable_point_picking` with a scale. So my solution is to use `vtkAreaPicker` (or `vtkRenderedAreaPicker`) before processing the pick result with` _clip_with_function` in order to find the points inside the selected area
