### ISSUE TITLE
Documentation of pyvista

### ISSUE THREAD

**Issue by fgallardo-mpie** [pyvista/pyvista#1336]
Hello, 

In https://docs.pyvista.org/core/filters.html , for the parameters in the filter interpolate, it reads :

n_points (int, optional) – If given, specifies the number of the closest points used to form the interpolation basis. **This will invalidate the radius and sharpness arguments** in favor of an N closest points approach. This typically has poorer results.

When using a Gaussian Kernel (the one you have implemented in pyvista), you can select Kernel Footprint = ['N Closest','Radius']. This, as far as I know, is a method to get which points will be considered.

How many points are going to be considered? Well, if we apply Kernel Footprint = 'Radius = 1', all the points which distance is smaller than 1. 
If we apply Kernel Footprint = 'N Closest = 8', the 8 closest points.
Each Kernel Footprint excludes the other one.

However, sharpness is a parameter which affect the weighting of the selected points, no matter how we selected those points. For NClosest, it also affects. See image.
![diffSharpness](https://user-images.githubusercontent.com/54398148/119360009-777bdb00-bcaa-11eb-9bf1-07d83c88dd94.png)

To my understanding, it should read as follows:
n_points (int, optional) – If given, specifies the number of the closest points used to form the interpolation basis. **This will invalidate the radius** in favor of an N closest points approach. This typically has poorer results.

Many thanks,
Francisco José Gallardo Basile

**Comment by GuillaumeFavelier** [comment]
Hello @fgallardo-mpie and thank you for the detailed explanation. I personally agree with your suggested change, would you be ready to contribute by opening a PR for it? I believe it should not be too difficult and we can also guide you.

**Comment by fgallardo-mpie** [comment]
I get the following error when try to push the new branch with the dox fix.

git push --set-upstream origin doc/interpolation
Username for 'https://github.com': fgallardo-mpie
Password for 'https://fgallardo-mpie@github.com':
remote: Permission to pyvista/pyvista.git denied to fgallardo-mpie.
fatal: unable to access 'https://github.com/pyvista/pyvista.git/': The requested URL returned error: 403

**Comment by GuillaumeFavelier** [comment]
Closing through #1346
