### ISSUE TITLE
Hypothesis vs. numpy 1.21.0 breakage (heads-up)

### ISSUE THREAD

**Issue by adeak** [pyvista/pyvista#1337]
I noticed that two of our tests break using numpy's 1.21.0rc1 release candidate. The issue seems to be with hypothesis, and [I've opened an issue there](https://github.com/HypothesisWorks/hypothesis/issues/2975) (this might actually be a numpy issue so I've raised there too).

This is a heads-up that we will probably have to handle this temporary incompatibility of hypothesis and numpy (in that the soon-to-be numpy 1.21 release will break hypothesis until they push out a new release). Unless there's something we have to do differently in our tests using hypothesis.

Cc. @akaszynski

**Comment by akaszynski** [comment]
Might we just limit `numpy<1.21` in our testing requirements until hypothesis gets updated?

**Comment by adeak** [comment]
Yeah, that could work. But in the meantime I've realized that this might even be a numpy bug, so it could even happen that the final 1.21.0 release will not have this problem and we'll have nothing to do.

See https://github.com/numpy/numpy/issues/19085 for the numpy version of the issue.

**Comment by adeak** [comment]
This has now been fixed in https://github.com/numpy/numpy/pull/19174, so we've nothing to do here.
