### ISSUE TITLE
Add RaspberryPi Docs and ARM64 Wheels

### ISSUE THREAD

**Issue by akaszynski** [pyvista/pyvista#1338]
@Tchiimy did some really great work figuring out how to get pyvista + vtk on a raspberry pi in https://github.com/pyvista/pyvista-support/issues/432.  We should add that here.

**Comment by akaszynski** [comment]
This has ended up being a rabbithole.  For entertainment, there's the steps I've taken thus far:
- Try building VTK on a Raspberry Pi 3 b+.  Fails due to memory limitations (1 GB isn't enough).  It's also not the right architecture.
- Buy a Raspberry Pi 4.  Why not, they're cool anyway.
- Discover the 64-bit image isn't default.  Found an official beta and installed that.
- VTK builds just fine, but latest raspberry pi image is too new for a `manylinux2014-aarch64` wheel tag.
- Having a tough time finding a `manylinux2014` image.  Will probably have to install CentOS 7 or make a docker image for this.  I'm researching how `numpy` and `scipy` make their wheels since they have aarch builds.

**Comment by akaszynski** [comment]
Turns out aarch64 exists at:
https://quay.io/pypa/manylinux2014_aarch64/

Build works.  Script for those who might be interested:

### build_wheels.sh
```
#!/bin/bash
# builds python wheels on docker container and tests installation

set -e -x

# build based on python version from args
PYTHON_VERSION="$1"
case $PYTHON_VERSION in
2.7)
  PYBIN="/opt/python/cp27-cp27m/bin/python"
  ;;
3.5)
  PYBIN="/opt/python/cp35-cp35m/bin/python"
  ;;
3.6)
  PYBIN="/opt/python/cp36-cp36m/bin/python"
  ;;
3.7)
  PYBIN="/opt/python/cp37-cp37m/bin/python"
  ;;
3.8)
  PYBIN="/opt/python/cp38-cp38/bin/python"
  ;;
3.9)
  PYBIN="/opt/python/cp39-cp39/bin/python"
  ;;
esac

/bin/bash
yum install epel-release -y
yum install ninja-build -y
# yum install libgl1-mesa-dev -y

#PYTHON_VERSION=3.9
rm -rf /io/build_$PYTHON_VERSION

mkdir /io/build -p
cd /io/build

# mkdir /io/build_$PYTHON_VERSION -p
# cd /io/build_$PYTHON_VERSION


cmake -GNinja \
      -DCMAKE_BUILD_TYPE=Release \
      -DVTK_BUILD_TESTING=OFF \
      -DVTK_BUILD_DOCUMENTATION=OFF \
      -DVTK_BUILD_EXAMPLES=OFF \
      -DVTK_DATA_EXCLUDE_FROM_ALL:BOOL=ON \
      -DVTK_MODULE_ENABLE_VTK_PythonInterpreter:STRING=NO \
      -DVTK_WHEEL_BUILD=ON \
      -DVTK_PYTHON_VERSION=3 \
      -DVTK_WRAP_PYTHON=ON \
      -DVTK_OPENGL_HAS_EGL=False \
      -DPython3_EXECUTABLE=$PYBIN ../
ninja-build

$PYBIN setup.py bdist_wheel
rm -rf dist wheelhouse
auditwheel repair dist/*.whl
cp wheelhouse/vtk*.whl /io/wheels
```

Called with:
```
PYTHON_VERSION=3.8
docker run -e \
       --rm -v `pwd`:/io quay.io/pypa/manylinux2014_aarch64 \
       /io/build_wheels.sh $PYTHON_VERSION
```

**Comment by akaszynski** [comment]
Question for @pyvista/developers:
I've been running into issues with other closed/open source projects using Python 3.9 outside of Anaconda.  Since Kitware isn't going to release wheels for 3.9 (and probably not ARM either), would anyone be opposed to hosting our own wheels?  Something like `pyvista-vtk`?  We could provide an egl flavor as well as `pyvista-vtk-egl`.

**Comment by adeak** [comment]
```bash
rm -rf dist wheelhouse
auditwheel repair dist/*.whl
cp wheelhouse/vtk*.whl /io/wheels
```
That's a surprising triple of commands in that order :) I assume `auditwheel` does something surprising too.

> would anyone be opposed to hosting our own wheels?

What possible downsides could there be? Considering how much of a pain it is to build VTK locally, any additional possibility for wheels should be appreciated.

**Comment by akaszynski** [comment]
Updated script.  `auditwheel` makes the wheels pep 600 and 425 compliant.  See https://github.com/pypa/auditwheel.

**Comment by GuillaumeFavelier** [comment]
> would anyone be opposed to hosting our own wheels?

From recent questions on slack and pyvista-support, I think there is a growing interest in those wheels, thank you for taking this responsibility :+1:
