### ISSUE TITLE
Setting a default value for `off_screen`

### ISSUE THREAD

**Issue by dstansby** [pyvista/pyvista#1350]
It's possible to use `plotter = pv.Plotter(off_screen=True)` to e.g. save a screenshot of a plotter without showing the actual plotting window. I was wondering if there was any way to set a global default value of this parameter, perhaps through a pyvista configuration file or an environment variable? If not, this is a feature request for that functionality 😃

Apologies if I missed something in the docs; if I did this is a request for improved documentation, which I would be happy to try myself.

Our use case is having a set of pyvista gallery examples that don't produce a plotting window when run on continuous integration, but do when a user runs the examples locally. It would be idea if we could set a configuration option so that `off_screen=True` for all our CI runs, but `off_screen=False` (the default) for users locally running the examples.

**Comment by akaszynski** [comment]
There's a few ways of doing this:

```pv
import pyvista
pyvista.OFF_SCREEN
```
or, alternatively as an environment variable

```
export PYVISTA_OFF_SCREEN=True
```

**Comment by dstansby** [comment]
👍 amazing, thanks a lot! I can take a look into where I expected this to be in the docs, and put in a PR to make it more obvious

**Comment by akaszynski** [comment]
> I can take a look into where I expected this to be in the docs, and put in a PR to make it more obvious

That would be really helpful.  Thanks!
