### ISSUE TITLE
`title` key added to `scalar_bar_args` in `add_mesh`

### ISSUE THREAD

**Issue by MatthewFlamm** [pyvista/pyvista#1353]
**Describe the bug, what's wrong, and what you expect:**

`scalar_bar_args` is modified inside `add_mesh` inserting a `title` key.  This causes problems if the same variable is intended to be used for multiple calls to `add_mesh`

-----

**To Reproduce**

Please include a code snippet to reproduce the bug in the block below:

```py
import pyvista as pv
mesh = examples.load_uniform()

sargs = dict(vertical=True, title_font_size=16)
sargs_copy = sargs.copy()
plotter = pv.Plotter()
plotter.add_mesh(mesh, scalars="Spatial Point Data", scalar_bar_args=sargs)
plotter.show()

print(sargs == sargs_copy)
print(sargs)

plotter = pv.Plotter()
plotter.add_mesh(mesh, scalars="Spatial Cell Data", scalar_bar_args=sargs)
plotter.show()
```

```txt
False
{'vertical': True, 'title_font_size': 16, 'title': 'Spatial Point Data'}
```

**Screenshots**
Note that the two images have the same scalar bar title, despite the second one being generated with `'Spatial Cell Data'`
![image](https://user-images.githubusercontent.com/39341281/120536155-d24fb980-c3b1-11eb-8e31-825e5ea2f249.png)
![image](https://user-images.githubusercontent.com/39341281/120536178-d8de3100-c3b1-11eb-979a-dffcf1fe4bb7.png)

-----

**System Information:**
 Please run the following code wherever you are experiencing the bug and paste the output below. This report helps us track down bugs and it is critical to addressing your bug:

```py
# Get system info
import pyvista as pv
print(pv.Report())
```

```txt
--------------------------------------------------------------------------------
  Date: Wed Jun 02 14:47:21 2021 EDT

                OS : Linux
            CPU(s) : 4
           Machine : x86_64
      Architecture : 64bit
       Environment : IPython
        GPU Vendor : NVIDIA Corporation
      GPU Renderer : GRID V100D-8Q/PCI/SSE2
       GPU Version : 4.5.0 NVIDIA 450.80.02

  Python 3.8.2 (default, Jun  2 2020, 16:34:16)  [GCC 4.8.5 20150623 (Red Hat
  4.8.5-36)]

           pyvista : 0.30.1
               vtk : 9.0.1
             numpy : 1.20.1
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.6
            meshio : 4.3.9
        matplotlib : 3.3.4
             PyQt5 : 5.15.4
           IPython : 7.21.0
             scipy : 1.6.0
              tqdm : 4.58.0
--------------------------------------------------------------------------------


```

**Comment by adeak** [comment]
Good catch. We absolutely shouldn't be mutating that dict!

There's a `scalar_bar_args.setdefault` or two in there. It seems straightforward to just make a copy of the input dict if passed. Do you want to fix this?

**Comment by MatthewFlamm** [comment]
It also happens in `add_volume`.  I have a fix started, just need to add some tests.
