### ISSUE TITLE
2d streamlines from a sliced 3D mesh data not working

### ISSUE THREAD

**Issue by sthavishtha** [pyvista/pyvista#1360]
**Plotting 2D streamlines**

My aim is to plot 2D streamlines on a plane, obtained upon slicing a 3D mesh. Though this is possible in Paraview, the 2D streamlines are very densely arranged. As the plots from pyvista look cool, I plan to get this working using pyvista itself. For this, I have actually exported a 2D mesh data (VTK format) from the 3D mesh by slicing (performed this in Paraview itself). Following the pyvista examples, using _mesh.streamlines()_ function gives me an empty array. Would appreciate if someone can give me clues to proceed.

-----

The colab notebook I have used for this is accessible at [Link1](https://colab.research.google.com/drive/1rMCW8CD4Nyq84zuRPExvt_AGqKMiHofn?usp=sharing) and the VTK file to try this at [Link2](https://drive.google.com/file/d/1_Lzzr937f2ABacnRsVzS8IhWf8ntIUWY/view?usp=sharing). The 2D contours are working (as seen in the colab notebook), so I am not sure why this is not the case with streamlines.

Also added a few screenshots to depict this problem : 

![1](https://user-images.githubusercontent.com/13017787/121058972-8ef4b100-c7de-11eb-91aa-81da8acb70e5.png)
![2](https://user-images.githubusercontent.com/13017787/121058980-90be7480-c7de-11eb-8cc8-68fa2269f38d.png)
![3](https://user-images.githubusercontent.com/13017787/121059919-a1231f00-c7df-11eb-8f33-0f6fc9b44326.png)

-----

**System Information:**

```txt
Date: Mon Jun 07 16:53:02 2021 UTC

                OS : Linux
            CPU(s) : 2
           Machine : x86_64
      Architecture : 64bit
               RAM : 12.7 GiB
       Environment : IPython
        GPU Vendor : VMware, Inc.
      GPU Renderer : llvmpipe (LLVM 10.0.0, 256 bits)
       GPU Version : 3.3 (Core Profile) Mesa 20.0.8

  Python 3.7.10 (default, May  3 2021, 02:48:31)  [GCC 7.5.0]

           pyvista : 0.30.1
               vtk : 9.0.1
             numpy : 1.19.5
           imageio : 2.4.1
           appdirs : 1.4.4
            scooby : 0.5.7
            meshio : 4.4.6
        matplotlib : 3.2.2
           IPython : 5.5.0
          colorcet : 1.0.0
             scipy : 1.4.1
              tqdm : 4.41.1
--------------------------------------------------------------------------------

```

**Comment by MatthewFlamm** [comment]
It looks like you are running into the same issue as https://github.com/pyvista/pyvista-support/issues/414, where none of your seed points fall on your 2D dataset.  See my first comment on how you can do this on existing releases of pyvista. Also, make sure to use `surface_streamlines`.  The fix for `start_position` will be in the upcoming release.

I suspect that there will be continued confusion on this since the default in `streamlines` is to use a sphere source.  An example could be supplied for 2D meshes to point out this pitfall.

**Comment by MatthewFlamm** [comment]
You can also use `pointa` and `pointb` to use seed points along a line, which is pretty typical for 2D simulations.

**Comment by sthavishtha** [comment]
Thanks for your comments.

1. Using a `source_radius=0` does not seem to work in my case. I used it as : `mesh.streamlines('physVelocity', source_radius=0, n_points=1, source_center=(0.5, 0.5, 0.5))`, where `physVelocity` is the vector.
2. Using `pointa` and `pointb`, however works : 
`mesh.streamlines('physVelocity', n_points=1, pointa=[0.1, 0.1, 0.5], pointb = [0.9, 0.9, 0.5])`.
3. A good approach I have tried is upon randomly seeding some source points and generating `surface_streamlines` (your suggestion) from them. `stream = mesh.streamlines_from_source(point_cloud,'physVelocity', surface_streamlines=True)`. Maybe there are better approaches that I am unaware of, but this 3rd approach seems to work well enough.

The colab notebook where I have experimented with your proposed ideas is [here](https://colab.research.google.com/drive/1FlK7lfb_DaYBcVk9ublCr53y-RDOTiF9?usp=sharing). I do agree that documenting an example for 2D meshes and plotting 2D streamlines would be helpful for the users.

**Comment by MatthewFlamm** [comment]
Your current colab notebook has `source_radius=0.1`.  It doesn't work with `source_radius=0` and `surface_streamlines=True`?  If your center point has a low velocity, you may need to choose an off center point to see anything.  In 0.31.0, out just now, you can use `start_position` to use a single seeding point.

I quite like your example using random mesh points as the seed.

**Comment by sthavishtha** [comment]
Thanks for catching that mistake and other suggestions. 

1. I did try using `source_radius=0` without `surface_streamlines=True` earlier, which was giving me an empty mesh. Now, using both these arguments, as you mention works without any error : `mesh.streamlines('physVelocity', return_source=True,source_radius=0, n_points=1, source_center=(0.1, 0.5, 0.5), surface_streamlines=True)` 
2. Using a very small `source_radius` also seems to work : `mesh.streamlines('physVelocity', return_source=True,source_radius=0.01, n_points=10, source_center=(0.5, 0.5, 0.5), surface_streamlines=True)`
3. With v0.31.0 as you mention, using `start_position` also works : `mesh.streamlines('physVelocity', start_position = [0.2,0.5,0.5], return_source=True, n_points=1)` or `mesh.streamlines('physVelocity', start_position = [0.2,0.5,0.5], return_source=True, n_points=1, surface_streamlines=True)`.

The colab notebook [link](https://colab.research.google.com/drive/1FlK7lfb_DaYBcVk9ublCr53y-RDOTiF9?usp=sharing) used earlier is updated, for your reference.

**Comment by MatthewFlamm** [comment]
There is a [vtkEvenlySpacedStreamlines2D](https://vtk.org/doc/nightly/html/classvtkEvenlySpacedStreamlines2D.html) class that I am working on implementing in pyvista that should also address this usage in the future.
