### ISSUE TITLE
vtkAxes not supported by pyvista

### ISSUE THREAD

**Issue by ghazalbangash** [pyvista/pyvista#1363]
Hi Guys 
I want to add axes at given point and then rotate/translate about a given axes 
i tried making a vtk axes but pyvista doesnt seem to support one
is there any solution to this problem ?
![axes](https://user-images.githubusercontent.com/47847589/121146440-2a286d80-c855-11eb-9ae8-173cd78838c1.png)

**Comment by tkoyama010** [comment]
Thank you for your report.
`pyvista.wrap` does not support `vtkAxes`. If we want to use it, we should add `axes` class as a wrapper calss of `vtkAxes`.
If you want to rotate/translate the object, you can rotate/translate object using [points](https://docs.pyvista.org/core/dataset.html#pyvista.DataSet.points) property.
If you want to  rotate/translate the view, you can use [camera](https://docs.pyvista.org/core/camera.html#pyvista.Camera) class.

**Comment by ghazalbangash** [comment]
can you please explain more on how i can add axes to wrapper class of vtkAxes? :(

**Comment by tkoyama010** [comment]
OK. I will add an pyvista example for [this](https://kitware.github.io/vtk-examples/site/Python/Rendering/Rotations/).

**Comment by ghazalbangash** [comment]
thats really kind of you. thanks a lot

**Comment by tkoyama010** [comment]
@ghazalbangash I made PR #1379  . Please check that this is what yout want to do.

**Comment by ghazalbangash** [comment]
THANK YOU SOOOOO MUCH.
really appreciate your hardwork
