### ISSUE TITLE
Fail during set of "cmap" parameter if matplotlib is not installed

### ISSUE THREAD

**Issue by Keynaan** [pyvista/pyvista#1364]
**Describe the bug, what's wrong, and what you expect:**

Since the addition of themes, the package is failing during init, if `matplotlib` is not installed.

I think matplotlib needs to be in the install requirements of [setup.py](https://github.com/pyvista/pyvista/blob/master/setup.py).

-----

**To Reproduce**

To reproduce, install on a system where no matplotlib is installed and use it like:

```py
import pyvista as pv
pv.rcParams["cmap"] = "jet"
```
will result in:
```
Traceback (most recent call last):
  File "/opt/xxx/python-3.8.6-xxx/lib/python3.8/site-packages/pyvista/plotting/colors.py", line 396, in get_cmap_safe
    from matplotlib.cm import get_cmap
ModuleNotFoundError: No module named 'matplotlib'
```
-----

**System Information:**
It runs on an headless ci-runner testing https://github.com/pyansys/PyMAPDL-reader, so there is no helpful report output due to the missing xserver.

**Comment by akaszynski** [comment]
@natter1, sorry for the delay.  This is a critical bug and I'll have this fixed right away.

**Comment by akaszynski** [comment]
Actually, I on second thought, I don't think it makes sense to include the `matplotlib` dependency to `pyvista`.  Default `colormaps` work, and it's too heavy of a dependency to require for `pyvista`.

@pyvista/developers, what do you think?  New global theme raises this error right away on initialization, vs at runtime when setting the 'cmap'.  Downstream dependencies requiring custom cmaps will just have to require `matplotlib`.

**Comment by adeak** [comment]
I don't think we should depend on matplotlib just for its colormaps.

> Default colormaps work

It might be helpful to clearly document this, and to specify what colormaps are available. Probably mention it at the installation guide too.

And vendor a version of viridis to make it always available as default, if that isn't already the case.

**Comment by Keynaan** [comment]
One side note: I discovered the problem using `ansys-mapdl-reader`, which got istalled using pip as usual on a ci-runner to get the latest version to test against. It raised the error and could not be imported because `matplotlib` was never specified as dependency.

For me it is ok, if the dependency is too big of a deal for `pyvista` but then I think it needs to be a dependency for `ansys-mapdl-reader`. To be honest, I wasn't sure were to put this issue (`pyvista` or `ansys-mapdl-reader`), because of this.

**Comment by adeak** [comment]
If most of pyvista works without matplotlib and the parts that don't work are localized and well-defined then it should be an optional (or soft) dependency. We have a few of those, and [it turns out matplotlib is already listed as one](https://docs.pyvista.org/getting-started/installation.html#optional-dependencies):

> Package | Purpose
> -- | --
> matplotlib | Using Colormaps

So I think we're mostly OK, but as I said we might try making this more obvious, and making the dependency explicit in places like https://docs.pyvista.org/examples/02-plot/cmap.html. We even have this for the `cmap` parameter of `add_mesh()`:

> **cmap** (_str, list, optional_) –
> 
> Name of the Matplotlib colormap to use when mapping the scalars. See available Matplotlib colormaps. Only applicable for when displaying scalars. **Requires Matplotlib to be installed. colormap is also an accepted alias for this.** If colorcet or cmocean are installed, their colormaps can be specified by name.

(emphasis mine).

So if `ansys-mapdl-reader` breaks on import then they should make matplotlib a hard dependency.

**Comment by akaszynski** [comment]
Added as a requirement in `ansys-mapdl-reader` and `ansys-mapdl-core`.  Thanks for the discussion here.

**Comment by Keynaan** [comment]
@adeak I agree.
@akaszynski Thank you.
