### ISSUE TITLE
clim not updating when updating scale_bars.

### ISSUE THREAD

**Issue by math-artist** [pyvista/pyvista#1366]
Not sure if this is caused by refactoring or if this is a bug, or me not using scalars_bars as intended, but what I used to do is:

1.  Add a mesh with scalars and a scalar_bar
2. Update everything by just adding the same mesh with different scalars and a different scalar_bar **of the same name**.

It used to simply overwrite the previous scalar_bar, but now it keeps the clim intact because:

1.  the `clim` input is first passed to `mapper.scalar_range`
2.  `clim` is then overwritten by the old `clim` because in this code:

https://github.com/pyvista/pyvista/blob/aefb4df72450bedab5078d13d71978b61be2f915/pyvista/plotting/scalar_bars.py#L279-L290

There is some "keep extremum" logic, which means that I can only update `clim` by increasing its range.

Am I missing something? I was expecting a simple overwrite of clim. The definition is: _Color bar range for scalars._

**Comment by math-artist** [comment]
Just moved from 0.30 to 0.31, I was about to say no change, but then I removed that new  `remove_scalar_bar()` in my code and everything works like before. Now, I don't use `remove_scalar_bar()` but it may be worth noting that it doesn't fully delete the scalar_bar.

Thanks @akaszynski for these fixes. 

I did a jump from 0.26 to 0.30 last month, along with pyvistaqt, but I didn't expect any major refactoring and I was under delivery pressure. Bad timing... It ended up breaking so many things, I'm sure there are still a few lurking in a corner.

**Comment by akaszynski** [comment]
> Now, I don't use remove_scalar_bar() but it may be worth noting that it doesn't fully delete the scalar_bar.

We should raise an issue for this.  If you could track down where this isn't getting deleted that would be great, but opening an issue to point this out with a minimum reproducible example would be sufficient.
