### ISSUE TITLE
[Panel] Panel backend silently broken with browser console JavaScript errors

### ISSUE THREAD

**Issue by pietakio** [pyvista/pyvista#1367]
Panel integration appears to be fundamentally broken with the most recent stable releases of the PyVista and Panel stacks.

Visually, we see similar issues as those noted at holoviz/panel#1805. *All* of the examples listed in [the official "Using Panel with PyVista" documentation](https://docs.pyvista.org/user-guide/jupyter/panel.html#using-panel-with-pyvista) silently fail with *no* visible server-side errors, either in Jupyter (Notebook|Lab) itself or from the CLI terminal running the Jupyter (Notebook|Lab) server.

Luckily, Firefox's browser console displays this suspicious commentary for a Jupyter (Notebook|Lab) file `PyVista_fun.ipynb` with only one cell containing only the trivial example `from pyvista import demos;
demos.plot_logo(background='white', jupyter_backend='panel')`:

```
Bokeh: BokehJS not loaded, scheduling load and callback at 
Date Tue Jun 08 2021 16:35:51 GMT-0400 (Eastern Daylight Time)
main.min.js:45:13
Bokeh: injecting link tag for BokehJS stylesheet:  https://unpkg.com/tabulator-tables@4.9.3/dist/css/tabulator_simple.min.css main.min.js:68:15
Bokeh: injecting link tag for BokehJS stylesheet:  https://unpkg.com/@holoviz/panel@0.11.3/dist/css/json.css main.min.js:68:15
Bokeh: injecting link tag for BokehJS stylesheet:  https://unpkg.com/@holoviz/panel@0.11.3/dist/css/loading.css main.min.js:68:15
Bokeh: injecting link tag for BokehJS stylesheet:  https://unpkg.com/@holoviz/panel@0.11.3/dist/css/card.css main.min.js:68:15
Bokeh: injecting link tag for BokehJS stylesheet:  https://unpkg.com/@holoviz/panel@0.11.3/dist/css/alerts.css main.min.js:68:15
Bokeh: injecting link tag for BokehJS stylesheet:  https://unpkg.com/@holoviz/panel@0.11.3/dist/css/dataframe.css main.min.js:68:15
Bokeh: injecting link tag for BokehJS stylesheet:  https://unpkg.com/@holoviz/panel@0.11.3/dist/css/markdown.css main.min.js:68:15
Bokeh: injecting link tag for BokehJS stylesheet:  https://unpkg.com/@holoviz/panel@0.11.3/dist/css/widgets.css main.min.js:68:15
Bokeh: injecting script tag for BokehJS library:  https://cdn.bokeh.org/bokeh/release/bokeh-2.3.2.min.js main.min.js:100:15
Bokeh: injecting script tag for BokehJS library:  https://cdn.bokeh.org/bokeh/release/bokeh-widgets-2.3.2.min.js main.min.js:100:15
Bokeh: injecting script tag for BokehJS library:  https://cdn.bokeh.org/bokeh/release/bokeh-tables-2.3.2.min.js main.min.js:100:15
Bokeh: injecting script tag for BokehJS library:  https://unpkg.com/@holoviz/panel@^0.11.3/dist/panel.min.js main.min.js:100:15
Bokeh: all BokehJS libraries/stylesheets loaded main.min.js:51:17
Bokeh: BokehJS plotting callback run at 
Date Tue Jun 08 2021 16:35:51 GMT-0400 (Eastern Daylight Time)
main.min.js:156:15
[bokeh] setting log level to: 'info' bokeh-2.3.2.min.js:184:1350
Bokeh: all callbacks have finished
Uncaught TypeError: a.vtkns.OutlineFilter is undefined
    l panel.min.js:173
    _instantiate_object bokeh-2.3.2.min.js:165
    _instantiate_references_json bokeh-2.3.2.min.js:165
    from_json bokeh-2.3.2.min.js:165
    embed_items_notebook bokeh-2.3.2.min.js:589
    embed_document PyVista_fun.ipynb line 2 > injectedScript:5
    <anonymous> PyVista_fun.ipynb line 2 > injectedScript:8
    <anonymous> PyVista_fun.ipynb line 2 > injectedScript:24
    b jQuery
panel.min.js:173:2948
    l panel.min.js:173
    _instantiate_object bokeh-2.3.2.min.js:165
    _instantiate_references_json bokeh-2.3.2.min.js:165
    from_json bokeh-2.3.2.min.js:165
    embed_items_notebook bokeh-2.3.2.min.js:589
    embed_document PyVista_fun.ipynb line 2 > injectedScript:5
    <anonymous> PyVista_fun.ipynb line 2 > injectedScript:8
    <anonymous> PyVista_fun.ipynb line 2 > injectedScript:24
    jQuery 3
    _safe_append outputarea.js:458
    append_display_data outputarea.js:665
    append_output outputarea.js:345
    handle_output outputarea.js:256
    output codecell.js:399
    _handle_output_message kernel.js:1198
    i jQuery
    _handle_iopub_message kernel.js:1238
    _finish_ws_message kernel.js:1017
    _msg_queue kernel.js:1008
    (Async: promise callback)
    _handle_ws_message kernel.js:1008
    i jQuery
    (Async: EventHandlerNonNull)
    start_channels kernel.js:517
    _kernel_created kernel.js:412
    on_success kernel.js:317
    _on_success kernel.js:380
    jQuery 6
    ajax utils.js:797
    restart kernel.js:332
    restart_and_resolve notebook.js:2371
    click notebook.js:2398
    jQuery 10
    modal dialog.js:95
    _restart_kernel notebook.js:2402
    restart_kernel notebook.js:2357
    handler actions.js:127
    <anonymous> actions.js:917
    call actions.js:1019
    fun toolbar.js:116
    jQuery 2
```

The above client-side JavaScript `Uncaught TypeError: a.vtkns.OutlineFilter is undefined` exception suggests badness within PyVista itself rather than Panel. Maybe? On the offhand chance that Panel is actually the culprit here, let's also summon overworked Panel maintainer @philippjfr. <sup>Sorry, Philipp. It's one of those days.</sup>

-----

**System Information:**
 Please run the following code wherever you are experiencing the bug and paste the output below. This report helps us track down bugs and it is critical to addressing your bug:

```py
# Get system info
import pyvista as pv
print(pv.Report())
```

```txt
# Paste system info here
--------------------------------------------------------------------------------
  Date: Tue Jun 08 16:46:29 2021 EDT

                OS : Linux
            CPU(s) : 8
           Machine : x86_64
      Architecture : 64bit
               RAM : 31.3 GiB
       Environment : Jupyter
        GPU Vendor : NVIDIA Corporation
      GPU Renderer : GeForce GTX 1060/PCIe/SSE2
       GPU Version : 4.5.0 NVIDIA 460.80

  Python 3.8.5 (default, May 27 2021, 13:30:53)  [GCC 9.3.0]

           pyvista : 0.31.0
               vtk : 9.0.1
             numpy : 1.20.1
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.7
            meshio : 4.4.6
        matplotlib : 3.3.4
             PyQt5 : 5.14.1
           IPython : 7.22.0
          colorcet : 1.0.0
        ipyvtklink : 0.2.1
             scipy : 1.6.0
              tqdm : 4.59.0
--------------------------------------------------------------------------------
```

Thanks for all the gruelling hard work, everyone. Integrating multiple frameworks across multiple languages across client-server boundaries is clearly non-trivial to the extreme. :crying_cat_face:

**Comment by pietakio** [comment]
**Gladly!** And thanks so much for the lightning-fast reply, @akaszynski. That's gotta be a new world record for GitHub issue turnaround. You deserve vast sums of positive karma. :sparkles:

**Comment by akaszynski** [comment]
I think you got lucky I was on my lunch break :)

**Comment by pietakio** [comment]
**Sadness.** We wanted to reward your generous lunchtime contributions to all humanity with a success story; tragically, running your example in an isolated Jupyter notebook results in *the same exact behaviour including the same exact client-side JavaScript error.*

On the bright side, it's not `pyvista`. Yay! You're in the clear and can now finish your ham sandwich in blessed peace. On the dark side, someone else to blame and we have no idea who to point the arthritic RSI-wracked finger at.

Could this possibly be a lower-level `vtk` or `vtk.js` issue, do you think?

**Comment by akaszynski** [comment]
> Could this possibly be a lower-level vtk or vtk.js issue, do you think?

Could be a variety of issues, but what I usually run into is some issue with my jupyterlab environment.  What generally works out is creating a fresh environment with conda and installing the minimum requirements to get panel working.  Then I build "applications" or docker images from there (on Linux at least), or I stop there and ensure I label my environment for anaconda as jupyterlab-dev or something like that.

**Comment by pietakio** [comment]
> ...but what I usually run into is some issue with my jupyterlab environment.

**Ugh.** You were absolutely right. In fact, the issue *is* Jupyter Lab. The same PyVista examples work perfectly when run directly in our Panel-hosted web app outside of Jupyter Lab. There's some perfidious interaction here between Jupyter + Panel + VTK that destroys the safety of our space-time continuum as we know it. <sup>*...that's bad*</sup>

For now, we'll just avoid Jupyter entirely when developing the visualization portion of our app. Thanks again for the voluminous and luminous assistance, Alex! You are truly a king amongst data scientists. :crown:

**Comment by akaszynski** [comment]
Thanks for the feedback!

Going to close this, but for anyone in the future who runs into this issue, I really appreciate your discussion.  This is why I like to communicate on GitHub.  Someone in the future is going to discover this thread from google and save a ton of time.
