### ISSUE TITLE
remove_scalar_bar doesn't release the slot in _scalar_bar_slots and the slot limit can be reached

### ISSUE THREAD

**Issue by math-artist** [pyvista/pyvista#1368]
When using the method `remove_scalar_bar`, the code goes there:
https://github.com/pyvista/pyvista/blob/a3711401a7bd37f655fc346a558f7c67cb522eab/pyvista/plotting/scalar_bars.py#L37-L57

but `self._scalar_bar_mappers` is already empty so it never goes into the for loop and cannot reach the line `self._plotter._scalar_bar_slots.add(slot)` where it should release the slot.

the set of available slots follows this pattern: `{4, 5, 6, 7, 8, 9}` with always only one scalar_bar available and at some point it reaches the limit.

What is the expected behavior? What if there is one or many meshes using that scalar_bar when using that method?

P.S. I just tried overwriting multiple scale_bars with multiple meshes, trying to break it and it works as intented as long as I don't use `remove_scalar_bar` explicitely.

**Comment by adeak** [comment]
Thanks for the detailed report. This was changed in https://github.com/pyvista/pyvista/pull/1347/ and as I noted there, the control flow is not entirely clear to me (cc. @akaszynski). But my impression was that `self._scalar_bar_mappers` should only become empty after https://github.com/pyvista/pyvista/blob/a3711401a7bd37f655fc346a558f7c67cb522eab/pyvista/plotting/scalar_bars.py#L52 which is inside the loop. Which is to say I don't see how this situation arises.

Do you have a simple example that demonstrates the issue? Or is it as simple as adding meshes with scalar bars and then removing them, and observing the slots?
