### ISSUE TITLE
Volume examples in docs broken

### ISSUE THREAD

**Issue by MatthewFlamm** [pyvista/pyvista#1369]
**Describe the bug, what's wrong, and what you expect:**

Most plots look completely blank.

![image](https://user-images.githubusercontent.com/39341281/121564240-3e04d880-c9e9-11eb-87ce-cd71286636f0.png)

Is this related to https://github.com/pyvista/pyvista/issues/1355?

**Comment by MatthewFlamm** [comment]
Link to documentation page: https://docs.pyvista.org/examples/02-plot/volume.html

**Comment by adeak** [comment]
Yes, this looks like a duplicate https://github.com/pyvista/pyvista/issues/1355; all these examples are opacity-related, and I can reproduce the blank plots with a virtual framebuffer:

Normal run with on-screen rendering:
![tmp_xvfb_bug_correct](https://user-images.githubusercontent.com/17914410/121575650-e6d22880-ca27-11eb-8fe3-9686121f95ce.png)

Off-screen rendering with a virtual framebuffer:
![tmp_xvfb_bug](https://user-images.githubusercontent.com/17914410/121575707-f7829e80-ca27-11eb-8fb3-4b37677b603f.png)

**Comment by akaszynski** [comment]
EGL wheels will fix this.  I'm leaning towards uploading EGL flavored wheels as `pyvista-vtk-egl`.  Working on windows python 3.9 support at the moment...

**Comment by akaszynski** [comment]
> EGL wheels will fix this. I'm leaning towards uploading EGL flavored wheels as pyvista-vtk-egl. Working on windows python 3.9 support at the moment...

This actually only works if we can get an instance with a GPU, which isn't going to be free...
