### ISSUE TITLE
streamlines_from_source produce ERROR:root:

### ISSUE THREAD

**Issue by VVpipin** [pyvista/pyvista#1373]
**Describe the bug, what's wrong, and what you expect:**
Right now I'm trying to draw vector  magnetic field snapshots from simulations.
So I prepared the data in following  pyvista guide, eg.
I have the mesh grid
xm,ym,zm = broadcast_arrays( xm, ym, zm)
where xm,ym,zm corresponds to the spherical coordinates r,theta,phi. There the components of the magnetic field vector are defined
So I defined two meshes:
mesh = pv.StructuredGrid(xm, ym, zm)
sour = pv.StructuredGrid(xsee, ysee, zsee)
the second mesh defines the seed points (around B-field extrema). Similarly I attached the vector field to the mesh
dir = np.empty((xm.size, 3))
dir[:,0]=bxx.ravel('F')
dir[:,1]=byy.ravel('F')
dir[:,2]=bzz.ravel('F')
mesh['mf'] = dir
Then I tried to  compute streamlines and get
streamlines=mesh.streamlines_from_source(sour, vectors='mf',
                                                     integration_direction='both',
                                                     surface_streamlines=False,
                                                     initial_step_length=0.5,
                                                     step_unit='cl',
                                                     min_step_length=0.01,
                                                     max_step_length=1.0,
                                                     max_steps=2000,
                                                     terminal_speed=1e-06,
                                                     max_error=1e-10,
                                                     max_time=None,
                                                     interpolator_type='point')

In spyder shell I got :
ERROR:root:The update extent specified in the information for output port 0 on algorithm vtkTrivialProducer(0x5622ed828100) is 0 55 0 199 0 47, which is outside the whole extent 0 202 0 0 0 0.QApplication: invalid style override passed, ignoring it.
    Available styles: Windows, Fusion
2021-06-11 15:28:40.435 ( 910,928s) [        607EE740]vtkStreamingDemandDrive:871    ERR| vtkStreamingDemandDrivenPipeline (0x5622eca4f1d0): The update extent specified in the information for output port 0 on algorithm vtkTrivialProducer(0x5622ecf99900) is 0 55 0 199 0 47, which is outside the whole extent 0 202 0 0 0 0.
2021-06-11 15:31:47.492 (1097,985s) [        607EE740]vtkStreamingDemandDrive:871    ERR| vtkStreamingDemandDrivenPipeline (0x5622ed8187f0): The update extent specified in the information for output port 0 on algorithm vtkTrivialProducer(0x5622ed0f99d0) is 0 149 0 149 0 149, which is outside the whole extent 0 202 0 0 0 0.
2021-06-11 15:32:25.581 (1136,073s) [        607EE740]vtkStreamingDemandDrive:871    ERR| vtkStreamingDemandDrivenPipeline (0x5622f320cad0): The update extent specified in the information for output port 0 on algorithm vtkTrivialProducer(0x5622ecf99900) is 0 149 0 149 0 149, which is outside the whole extent 0 202 0 0 0 0.
2021-06-11 15:33:00.451 (1170,944s) [        607EE740]vtkStreamingDemandDrive:871    ERR| vtkStreamingDemandDrivenPipeline (0x5622f320e0a0): The update extent specified in the information for output port 0 on algorithm vtkTrivialProducer(0x5622ed0f99d0) is 0 149 0 149 0 149, which is outside the whole extent 0 202 0 0 0 0.
2021-06-11 15:52:09.607 (2320,100s) [        607EE740]vtkStreamingDemandDrive:871    ERR| vtkStreamingDemandDrivenPipeline (0x5622ed853570): The update extent specified in the information for output port 0 on algorithm vtkTrivialProducer(0x5622ed828100) is 0 55 0 199 0 47, which is outside the whole extent 0 202 0 0 0 0.

-----

**To Reproduce**

Please include a code snippet to reproduce the bug in the block below:

from numpy import *
from scipy import special

#### Calculate the field ####################################################
radius = 1  # Radius of the coils

x, y, z = [e.astype(float32) for e in
            ogrid[-2:2:50j, -2:2:50j, -2:2:50j]]

# express the coordinates in polar form
rho = sqrt(x ** 2 + y ** 2)
x_proj = x / rho
y_proj = y / rho

E = special.ellipe((4 * radius * rho) / ((radius + rho) ** 2 + z ** 2))
K = special.ellipk((4 * radius * rho) / ((radius + rho) ** 2 + z ** 2))
Bz = 1 / sqrt((radius + rho) ** 2 + z ** 2) * (
                K
                + E * (radius ** 2 - rho ** 2 - z ** 2) /
                    ((radius - rho) ** 2 + z ** 2)
            )
Brho = z / (rho * sqrt((radius + rho) ** 2 + z ** 2)) * (
                - K
                + E * (radius ** 2 + rho ** 2 + z ** 2) /
                    ((radius - rho) ** 2 + z ** 2)
            )
del E, K, rho
# On the axis of the coil we get a divided by zero. This returns a
# NaN, where the field is actually zero :
Brho[isnan(Brho)] = 0

Bx, By = x_proj * Brho, y_proj * Brho

del x_proj, y_proj, Brho
# In[]:
# define seed points concentrated to the pole on the sphere of r=1
xch=real(special.orthogonal.p_roots(8)[0])
phi=linspace(0,2*pi,16)
xse=zeros((8,16));yse=zeros((8,16));zse=zeros((8,16));
for i in range(8):
    xse[i,:]=sin(xch[i])*cos(phi);
    yse[i,:]=sin(xch[i])*sin(phi);
    zse[i,:]=cos(xch[i]);
# In[]:
import pyvista as pv
x, y, z = mgrid[-2.:2.:50j,-2.:2.:50j,-2.:2.:50j] 

mesh = pv.StructuredGrid(x, y, z)
sour = pv.StructuredGrid(xse, yse, zse)

# In[]:
vec = empty((x.size, 3))
vec[:,0]=Bx.ravel('F')
vec[:,1]=By.ravel('F')
vec[:,2]=Bz.ravel('F')
mesh['mf'] = vec
# In[]:
stream, src = mesh.streamlines('mf', return_source=True,
                               terminal_speed=0, n_points=120,
                               source_radius=0.99)
cpos = [(5, 5, 5), (-0.0, -0.0, -0.0), (0.0, 0.0, 1.0)]
stream.tube(radius=0.015).plot(cpos=cpos)

# In[]:
streamlines=mesh.streamlines_from_source(sour, vectors='mf',integrator_type=2,
                                                     integration_direction='both', 
                                                     surface_streamlines=False, 
                                                     initial_step_length=0.5, 
                                                     step_unit='cl', 
                                                     min_step_length=0.01,
                                                     max_step_length=1.0, 
                                                     max_steps=200, 
                                                     terminal_speed=1e-06, 
                                                     max_error=1e-06, 
                                                     max_time=None, 
                                                     interpolator_type='point')    

# Insert code here

```

**Screenshots**
If applicable, add screenshots to help explain your problem.

-----

I have the latest version of manjaro linux, gnome, I'm working in spyder5.03
```py
# Get system info
import pyvista as pv
print(pv.Report())
```
Output from spyder call 'get_namespace_view':

--------------------------------------------------------------------------------
  Date: Пт июн 11 18:20:23 2021 +08

                OS : Linux
            CPU(s) : 4
           Machine : x86_64
      Architecture : 64bit
               RAM : 23.2 GiB
       Environment : IPython
        GPU Vendor : Intel
      GPU Renderer : Mesa Intel(R) HD Graphics 620 (KBL GT2)
       GPU Version : 4.6 (Core Profile) Mesa 21.1.2

  Python 3.9.5 (default, May 24 2021, 12:50:35)  [GCC 11.1.0]

           pyvista : 0.31.0
               vtk : Version unknown
             numpy : 1.20.3
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.7
            meshio : 4.4.5
        matplotlib : 3.4.1
             PyQt5 : 5.12.3
           IPython : 7.24.0
             scipy : 1.6.3
              tqdm : 4.61.0
--------------------------------------------------------------------------------

```txt
# Paste system info here

```

**Comment by VVpipin** [comment]
Thanks! I'll try to use that way around

**Comment by MatthewFlamm** [comment]
I also found that your original code still produces valid streamlines even with the error message from vtk.  So it isn't even strictly necessary to `cast_to_unstructured_grid` 

That is:

```
streamlines = mesh.streamlines_from_source(sour, vectors='mf').plot()
```

gives the vtk error, but still produces the correct plot.

**Comment by VVpipin** [comment]
That's right! I did not know
