### ISSUE TITLE
Gempy - ImportError: cannot import name 'parse_color' from 'pyvista.plotting.theme'

### ISSUE THREAD

**Issue by mcoffey77** [pyvista/pyvista#1377]
Hello,
I am new to programming, I know some basic things of Python and I've been trying to use Gempy. I installed it with anaconda prompt, but when I try to "import gempy as gp", the following error comes up: 

**ImportError: cannot import name 'parse_color' from 'pyvista.plotting.theme'**

I see that the file at C:\Users\coffe\anaconda3\envs\gempy\lib\site-packages\pyvista\plotting\theme.py is not filled with code like other files, instead it is filled with:

__"""Here for backwards compatibility with pyvistaqt."""_

_from pyvista import rcParams  # pragma: no cover__

Does someone know how to solve this?

Thanks for your time

**Comment by akaszynski** [comment]
Made a release for this.  You can upgrade with:
```
pip install pyvista -U
```

**Comment by AlexanderJuestel** [comment]
@akaszynski, 

GemPy has still implemented `parse_color` in its API. I would like to change that as we are getting Deprecation Warnings to use the Color class (see below). Is it just a simple replacement as shown below?

```ruby
from pyvista.plotting import parse_color

parse_color('#34d42a')
```
.....\lib\site-packages\pyvista\plotting\tools.py:622: PyVistaDeprecationWarning: The usage of `parse_color` is deprecated in favor of the new `Color` class.
  warnings.warn(
(0.20392156862745098, 0.8313725490196079, 0.16470588235294117)

```ruby
pv.Color('#34d42a')
```

Color(hex='#34d42aff')

**Comment by banesullivan** [comment]
> Is it just a simple replacement as shown below?

Pretty much. I forget what `parse_color` exactly returned but do the above and then get the [`int_rgb`](https://docs.pyvista.org/api/utilities/_autosummary/pyvista.Color.int_rgb.html#pyvista.Color.int_rgb) property or whichever conversion you want from that `Color` object.

See https://docs.pyvista.org/api/utilities/_autosummary/pyvista.Color.html#pyvista.Color

**Comment by 66mengyu** [comment]
hello,please how to solve the question ?and I also have the same ploblem.

**Comment by AlexanderJuestel** [comment]
@66mengyu, do you have the same issue in GemPy? It should be fixed in the latest version of GemPy (2.3.1)by now.

Which GemPy Version are you using?

**Comment by 66mengyu** [comment]
@AlexanderJuestel gempy2.2.3

**Comment by AlexanderJuestel** [comment]
@66mengyu please update to GemPy 2.3.1 using `pip install gempy==2.3.1` in your current environment. This should fix your problem :)

**Comment by 66mengyu** [comment]
@AlexanderJuestel

**Comment by AlexanderJuestel** [comment]
If you have a GemPy specific question, please go to the GemPy repository and open a discussion :)

Cheers
Alex

**Comment by banesullivan** [comment]
Please follow up with GemPy, this doesn't look like a PyVista-specific issue but rather an issue in resolving gempys dependencies.
