### ISSUE TITLE
master --> main

### ISSUE THREAD

**Issue by akaszynski** [pyvista/pyvista#1389]
I'd like to know everyone's thoughts regarding https://github.com/github/renaming.

For me personally, I'm ambivalent regarding the name change; software to me has always been language agnostic, but I can see why some would take offense at the `master`/`slave` naming scheme often used within hardware interfaces and the same may apply to branch naming.

Given that the wider community appears to be adopting this, let's consider adopting it ourselves.  I'm not here to make a statement for or against it, but in this case I feel uniformity trumps tradition.

**Comment by tkoyama010** [comment]
+1 I agree with renaming. I know that `master/slave` doesn't mean the racisum, but it is importan to care about people who are uncomfortable about it.

**Comment by adeak** [comment]
I never quite understood why a `master` branch fits in the master/slave dichotomy, as there aren't any slave branches to speak of. Any other name that signifies superiority of that branch could have the same connotations of social inequity.

That being said, if there's just a single person on the planet who feels genuine distress or discomfort seeing a branch called `master`, we should rename it. It costs nothing to change the name, and this will only affect library developers anyway. It takes two days at most to update muscle memory.

**Comment by akaszynski** [comment]
Going to give a few more days for people to give their thoughts (for those of us who don't live on github), and then I'll pull the trigger on this.  Seems that they have done a great job automating branch name changes.

**Comment by adeak** [comment]
I'd expect that a lot of @pyvista/developers don't monitor the issues too often (myself included), so ping :)

**Comment by GuillaumeFavelier** [comment]
I'm +1 for this and I'm glad that `pyvista` contributors consider the change `master -> main`

**Comment by akaszynski** [comment]
Executing...

**Comment by adeak** [comment]
Here's hoping we won't end up with [dawizards](https://selinker.livejournal.com/32929.html) :)

Looking at `git grep -n master` we're almost clear. I suspect even things like `master_doc` in `docs/conf.py` are OK to be renamed `main_doc`. The few exceptions I could find at a glance:
```
README.rst:181:.. _discretize: https://discretize.simpeg.xyz/en/master/
README.rst:182:.. _creating compelling visualizations: https://discretize.simpeg.xyz/en/master/api/generated/discretize.mixins.vtk_mod.InterfaceVTK.html
docs/extras/building_vtk.rst:25:<https://github.com/conda-forge/vtk-feedstock/blob/master/recipe/build.sh>`__.

```

And depending on how automatic mybinder is:
```
README.rst:98:   :target: https://mybinder.org/v2/gh/pyvista/pyvista-examples/master
```
