### ISSUE TITLE
Vector mapping uses only first component when using cell data

### ISSUE THREAD

**Issue by MatthewFlamm** [pyvista/pyvista#1420]
**Describe the bug, what's wrong, and what you expect:**

After PR #1387, add_mesh no longer maps vector data that lies on cells correctly.  It seems to map to the first component ONLY.  I can't figure out the root cause of this yet.  If not, should we revert #1387?

 I only checked the first component when testing and it looked fine.  But, the other components and the magnitude are all broken.

-----

**To Reproduce**

Adapted from the existing test for point data:

```py
import pyvista as pv
import numpy as np
data = pv.Plane()
vector_values_cells = np.empty((data.n_cells, 3))
vector_values_cells[:, :] = [3., 4., 0.]
data['vector_values_cells'] = vector_values_cells

kwargs = {
    "clim": [0, 5],
    "show_scalar_bar": True
}

p = pv.Plotter(shape=(2, 2))
p.subplot(0, 0)
p.add_mesh(data, scalars="vector_values_cells",**kwargs)
p.subplot(0, 1)
p.add_mesh(data, scalars="vector_values_cells", component=0, **kwargs)
p.subplot(1, 0)
p.add_mesh(data, scalars="vector_values_cells", component=1, **kwargs)
p.subplot(1, 1)
p.add_mesh(data, scalars="vector_values_cells", component=2, **kwargs)
p.link_views()
p.show()
```

Second screenshot uses:

```py
vector_values_cells[:, :] = [5., 4., 0.]
```

EDIT: Stripped unneeded argument to `add_mesh` to reproduce behavior.

**Screenshots**

Using vectors of [3., 4., 0.]:
![image](https://user-images.githubusercontent.com/39341281/122986051-ea8d7580-d36c-11eb-9305-30e3289bb64e.png)

Using vectors of [5., 4., 0.]:
![image](https://user-images.githubusercontent.com/39341281/122986610-a6e73b80-d36d-11eb-8cb5-8d0ad495aef9.png)

-----

**System Information:**
 Please run the following code wherever you are experiencing the bug and paste the output below. This report helps us track down bugs and it is critical to addressing your bug:

```py
# Get system info
import pyvista as pv
print(pv.Report())
```

```txt
pyvista : 0.31.dev0

```

**Comment by akaszynski** [comment]
> After PR #1387, add_mesh no longer maps vector data that lies on cells correctly. It seems to map to the first component ONLY. I can't figure out the root cause of this yet. If not, should we revert #1387?

Documentation build on  `ansys-mapdl-reader` ran into issues directly related to this PR as well.  Let's revert #1387 and work on it again.
