### ISSUE TITLE
Meshes dissapear with large camera coordinate + large zoom

### ISSUE THREAD

**Issue by dstansby** [pyvista/pyvista#1445]
## Description
When setting the camera far away from the origin with a large zoom value, meshes disappear until the plotter is interacted with. In the example code below the camera is set to be far away at (100, 0, 0), but the zoom set large enough (20) so that an object should be visible.

When initially rendered no sphere is shown, but as soon as the plot window is interacted with (e.g. click to rotate) the sphere immediately appears and all seems normal. So the issue seems to be that the meshes are not rendered initially when the plotter window opens.

```python
import pyvista

grid = pyvista.Sphere()

plotter = pyvista.Plotter()
plotter.add_mesh(grid)
plotter.camera.zoom(20)
plotter.camera.position = (100, 0, 0)
plotter.show()
```

**Comment by akaszynski** [comment]
Transferred the issue here since it's a problem with `pyvista` and not "user error".  Thanks for describing the bug with a MWE.

Just resolved this in #1446, and it will be out in the next minor release.  Should you need a workaround now, run:
```
plotter.renderer.ResetCameraClippingRange()
```
Just prior to `plotter.show()`
