### ISSUE TITLE
Redirect old doc URLs to new

### ISSUE THREAD

**Issue by adeak** [pyvista/pyvista#1456]
Recently we changed the structure of the documentation a bit, adding autosummaries and putting the reference docs under `/api/`.

When searching for "pyvista threshold filter" in duckduckgo, I get this:
![Screenshot 2021-06-27 at 16-35-34 pyvista threshold filter at DuckDuckGo](https://user-images.githubusercontent.com/17914410/123548869-e6939600-d766-11eb-9e20-7e2a46414c18.png)

The doc links:
* https://docs.pyvista.org/core/filters.html
* https://docs.pyvista.org/examples/01-filter/using-filters.html
* https://docs.pyvista.org/examples/01-filter/clipping-with-surface.html
* https://docs.pyvista.org/examples/01-filter/compute-volume.html

The very first of these paths is broken in the dev docs, because it has moved:
* https://dev.pyvista.org/api/core/filters.html

I don't personally use search engines for our docs, but I suspect some people might. And those who do are probably looking for the library reference, because they are looking for a specific part of the API. So even though most of the docs is OK, the parts that have moved might be the most likely to be searched for.

It would be great if we could set up redirects for such moves, because even inaccurate redirects are a lot better than 404s.

**Comment by akaszynski** [comment]
It's been about a year, let's close this.

We can reopen this if we refactor our docs (again).
