### ISSUE TITLE
Feature Request: change legend symbol/label to other shapes instead of triangle only

### ISSUE THREAD

**Issue by WWIIWWIIWW** [pyvista/pyvista#1487]
`legend_elements = [[str(unique_label), cmap.colors[i]] for i, unique_label in enumerate(unique_labels)]`
`p.add_legend(legend_elements)`
![Capture](https://user-images.githubusercontent.com/45393386/124378187-6d3cfb80-dcb0-11eb-8383-ebb8a275673a.PNG)

Hi,
It will be good if we can have a feature to change the triangle to some other shapes. e.g. a circle or a rectangle with the right side numbers written within it.

Bests,
Kai.

**Comment by tkoyama010** [comment]
Ref https://github.com/pyvista/pyvista/discussions/1464
