### ISSUE TITLE
Remove `_ref` after references

### ISSUE THREAD

**Issue by akaszynski** [pyvista/pyvista#1493]
Remove `_ref` after references

It's become redundant especially when :ref:`ref_topo_map_example` is better represented as simply :ref:`topo_map_example`.  We can create another PR making this consistent.

_Originally posted by @akaszynski in https://github.com/pyvista/pyvista/pull/1482#r664083973_

**Comment by AdityaRanjanJha** [comment]
i want to work on this issue. Do you want me remove 'ref_' from ref_topo_map_example as well as from topo_map_example_ref ?

**Comment by akaszynski** [comment]
> i want to work on this issue. Do you want me remove 'ref_' from ref_topo_map_example as well as from topo_map_example_ref ?

Would be much appreciated!
