### ISSUE TITLE
Various Refactors

### ISSUE THREAD

**Issue by akaszynski** [pyvista/pyvista#1494]
Various refactors from #1482.

- [ ] https://github.com/pyvista/pyvista/pull/1482#discussion_r664015140 (refactor `MultiBlock.bounds`)
- [ ] https://github.com/pyvista/pyvista/pull/1482#discussion_r664019043 (refactor `MultiBlock.volume`)
- [ ] https://github.com/pyvista/pyvista/pull/1482#discussion_r664022363 (refactor `MultiBlock.get_block_name`)
- [ ] https://github.com/pyvista/pyvista/pull/1482#discussion_r664094024 (refactor `DataSetFilters.slice_along_axis`)

**Comment by adeak** [comment]
I've moved the API change discussion to https://github.com/pyvista/pyvista/issues/1507, so we can close this issue with the refactor PR.
