### ISSUE TITLE
Saving .ply files

### ISSUE THREAD

**Issue by T-AbdelAlim** [pyvista/pyvista#1503]
When trying to save a .ply file after some rotation and translation, the color values of the textures are not saved. Is there a way to do this?

Current attempt:
mesh = pv.read(mesh.ply)
mesh.rotate_x(90)
mesh.save(mesh_rotated.ply) --> no longer contains textures

**Comment by RichardScottOZ** [comment]
Thanks Alex.

**Comment by T-AbdelAlim** [comment]
This is a first for me. How long does such a feature request usually take? 
I ask this, because I can't get the vtk integration to work. 
Also, out of interest, why does it not work in pyvista? Are the rgb colors (actively) removed after a transformation or simply not bound/tracked w.r.t. the corresponding vertex?

**Comment by akaszynski** [comment]
> This is a first for me. How long does such a feature request usually take?

This will probably be merged by the end of today.  Won't be released until next week.  You can install from our `main` branch once it's merged with a simple git clone or pip install from git (google it if you've never installed from git using pip).

> Also, out of interest, why does it not work in pyvista? Are the rgb colors (actively) removed after a transformation or simply not bound/tracked w.r.t. the corresponding vertex?

They're simply not written to file.  You have to specify the name of the "color array" when saving and there's no option to do that right now.
