### ISSUE TITLE
streamlines_evenly_spaced_2D: Segmentation fault when using non-default argument values

### ISSUE THREAD

**Issue by liangwang0734** [pyvista/pyvista#1508]
**Describe the bug, what's wrong, and what you expect:**
When my test plot of a dipole field, changing some of the default parameters leads to a segmentation fault. I'm using the git dev0 version (e79c03369dcaf57292ae6b7b366410d82debcee7), NOT the 0.13.3 release (which does not have the `streamlines_evenly_spaced_2d` feature).

I have also tested the data in Paraview using the corresponding filter and it worked fine.

-----

**To Reproduce**

Please include a code snippet to reproduce the bug in the block below:

```py
# Full code https://gist.github.com/liangwang0734/5d734a82dedefcfeaf078ffa9f18eb60
        streamlines = grid.streamlines_evenly_spaced_2D(
            vectors='bfield',
            start_position=(-0.6, 0, 0),
            integrator_type=2,
            step_length=0.2,
            step_unit='cl',
            max_steps=2000,
            terminal_speed=1e-12,
            interpolator_type='point',
            separating_distance=10,
            separating_distance_ratio=0.004,  # default is None
            closed_loop_maximum_distance=0.5,
            loop_angle=20,
            minimum_number_of_loop_points=4,
            compute_vorticity=True)


```

**Screenshots**

-----

**System Information:**
 Please run the following code wherever you are experiencing the bug and paste the output below. This report helps us track down bugs and it is critical to addressing your bug:

```py
# Get system info
import pyvista as pv
print(pv.Report())
```

```txt
  Date: Fri Jul 09 22:40:43 2021 EDT

                OS : Linux
            CPU(s) : 8
           Machine : x86_64
      Architecture : 64bit
               RAM : 31.2 GiB
       Environment : Python
        GPU Vendor : NVIDIA Corporation
      GPU Renderer : NVIDIA GeForce MX130/PCIe/SSE2
       GPU Version : 4.5.0 NVIDIA 465.31

  Python 3.8.5 (default, Sep  4 2020, 07:30:14)  [GCC 7.3.0]

           pyvista : 0.31.dev0
               vtk : 8.2.0
             numpy : 1.19.2
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.7
            meshio : 4.4.6
        matplotlib : 3.3.2
           IPython : 7.25.0
             scipy : 1.6.2
              tqdm : 4.49.0

  Intel(R) Math Kernel Library Version 2020.0.4 Product Build 20200917 for
  Intel(R) 64 architecture applications

```

**Comment by akaszynski** [comment]
@MatthewFlamm, could you take a look at this?  This might be up your alley.

**Comment by MatthewFlamm** [comment]
Thanks for testing this new feature before release. I cannot test your code directly for a little over a week, but I have some comments/questions until then.  Is the segfault occurring during the streamline generation or plotting in matplotlib?

 I find it isn't uncommon for seg faults to occur in the streamlines filter with choices of small numbers for the `separating_distance`  and `separating_distance_ratio`.  `separating_distance_ratio` in particular sets the distance to terminate adjacent streamlines according to `separating_distance*separating_distance_ratio`, so your value is equal to .04 cell lengths.  You can try increasing `separating_distance_ratio` and see if it helps.  It is unclear what the default value is in the underlying vtk filter.

> I have also tested the data in Paraview using the corresponding filter and it worked fine.

Was this with the exact same parameters that fails here?  I'm not sure that the defaults in paraview are the same as in the underlying vtk filter or the values used in pyvista.

**Comment by liangwang0734** [comment]
The following parameters from Paraview (except for a few not exposed in Paraview GUI) still fails.

```python
        print('paraview default; dead')
        streamlines = grid.streamlines_evenly_spaced_2D(
            vectors='bfield',
            start_position=(-0.75, 0, 0),
            integrator_type=4,
            step_length=0.2,
            step_unit='cl',
            max_steps=2000,
            terminal_speed=1e-12,
            interpolator_type='point',
            separating_distance=2,
            separating_distance_ratio=0.4,
            closed_loop_maximum_distance=0.2,
            loop_angle=20,  # not exposed in paraview
            minimum_number_of_loop_points=4,  # not exposed in paraview
            compute_vorticity=True)
```
Following is the screenshot from Paraview. In addition, the Paraview result using the pyvista default values gives consistent results.
The Paraview result was using a `test.vtk` saved from pyvista. I uploaded here: https://file.io/05bYXhvuwaH8
![streamlines_evenly_spaced_2d_paraview_default_except_start_position](https://user-images.githubusercontent.com/1000547/125173069-15f4ca80-e18b-11eb-903b-d250150f80fa.png)

**Comment by MatthewFlamm** [comment]
I was able to take a peek earlier using pyvista.  I can run your code just fine.  I even lowered the `separating_distance` parameter quite a bit:

```py
        streamlines = grid.streamlines_evenly_spaced_2D(
            vectors='bfield',
            start_position=(-0.6, 0, 0),
            integrator_type=2,
            step_length=0.2,
            step_unit='cl',
            max_steps=2000,
            terminal_speed=1e-12,
            interpolator_type='point',
            separating_distance=0.5,
            separating_distance_ratio=0.004,  # default is None
            closed_loop_maximum_distance=0.5,
            loop_angle=20,
            minimum_number_of_loop_points=4,
            compute_vorticity=True)
```

![image](https://user-images.githubusercontent.com/39341281/125648716-ddfb2b10-37f5-4626-b621-f96351fc68aa.png)

Here is my pyvista.Report() for comparison.  Note that our vtk versions are different.  Could you test on your machine with the same vtk version?  I cannot get any version below 9.0.2 to install on my machine, and I don't even see version 8.2.0 available on pypi.

```txt
--------------------------------------------------------------------------------
  Date: Wed Jul 14 11:28:38 2021 EDT

                OS : Linux
            CPU(s) : 4
           Machine : x86_64
      Architecture : 64bit
               RAM : 31.3 GB
       Environment : IPython
        GPU Vendor : NVIDIA Corporation
      GPU Renderer : GRID V100D-8Q/PCI/SSE2
       GPU Version : 4.5.0 NVIDIA 450.80.02

  Python 3.8.2 (default, Jun  2 2020, 16:34:16)  [GCC 4.8.5 20150623 (Red Hat
  4.8.5-36)]

           pyvista : 0.31.dev0
               vtk : 9.0.1
             numpy : 1.20.1
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.6
            meshio : 4.3.11
        matplotlib : 3.3.4
           IPython : 7.21.0
          colorcet : 1.0.0
           cmocean : 2.0
        ipyvtklink : 0.2.1
             scipy : 1.6.3
        itkwidgets : 0.32.0
              tqdm : 4.59.0
--------------------------------------------------------------------------------
```

**Comment by liangwang0734** [comment]
Thank you, @MatthewFlamm . Yes, after updating the vtk version it works fine!

Somehow I was using the anaconda, instead of the conda-forge channel for vtk, which is out-of-date.

Sorry for this false alarm. I'm going to close this.

**Comment by MatthewFlamm** [comment]
Sounds like you uncovered a bug in vtk that was fixed.  I will update the title so it is easier to find for others that run into the same issue.

**Comment by akaszynski** [comment]
> Sounds like you uncovered a bug in vtk that was fixed. I will update the title so it is easier to find for others that run into the same issue.

Let's add a ``.. warning::`` directive in the method to let users know that it's less stable with vtk<9.0

**Comment by MatthewFlamm** [comment]
> Let's add a `.. warning::` directive in the method to let users know that it's less stable with vtk<9.0

This is a good idea, I cannot install 9.0.0 since it looks like there are no Linux wheels for that version.  I like the idea of keeping it as 9.0 without the patch version for this reason.

I'd like to add default parameters that I uncovered when trying to investigate this too.
