### ISSUE TITLE
Binder link is broken

### ISSUE THREAD

**Issue by tkoyama010** [pyvista/pyvista#1522]
**Describe the bug, what's wrong, and what you expect:**

Binder link in README.rst is broken. It is because the default branch of [`pyvista-examples` is still `master`](https://github.com/pyvista/pyvista-examples/tree/master) .

-----

**To Reproduce**

Click [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/pyvista/pyvista-examples/main)

**Screenshots**
![image](https://user-images.githubusercontent.com/7513610/126076678-a141867d-7fbb-491e-b605-43533e041b4f.png)

-----

**System Information:**
None

**Comment by akaszynski** [comment]
Just renamed the branch to main.  Should be good now.  I'll update the pipeline as well.
