### ISSUE TITLE
Add pip installation directions for pyembree

### ISSUE THREAD

**Issue by akaszynski** [pyvista/pyvista#1529]
### System
**OS:** Windows 10 x64, Build 1909
**Python:** 3.8.10

### Steps
1. Install [Embree v2.17.7 x64](https://github.com/embree/embree/releases/tag/v2.17.7) via the `msi` installer

> (***NOTE:*** To date, `pyembree` still relies on `Embree 2` and has not been updated for `Embree 3`.)

2. Install [Microsoft Visual Studio 2015](url)

> (***NOTE:*** `pyembree` requires version 2015. The error 
> ```
> error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": 
> https://visualstudio.microsoft.com/visual-cpp-build-tools/
> ```
> is incorrect. The version of Visual Studio *MUST* be exactly version 2015. Search for version 2015 [here](https://visualstudio.microsoft.com/vs/older-downloads/) under "Still want an older version?", which will take you to [https://my.visualstudio.com/Downloads](https://my.visualstudio.com/Downloads). You must now have a Microsoft account to install older versions of Visual Studio). This will be an ISO file that you must mount and run the contained executable (be prepared for several hours of downloading and installing)

3. Install the [Windows 10.0.19041.685 SDK](https://developer.microsoft.com/en-US/windows/downloads/windows-10-sdk/)

4. Install [Poetry 1.1.7](https://python-poetry.org/docs/master/#installation) via PowerShell

5. Create your project and initialize a virtual environment with `venv` and package management with `poetry`.

> (***NOTE:*** In this example, the virtual environment is contained in a folder named `.venv` within the project folder itself)

6. Open a `VS2015 x64 Native Tools Command Prompt` as an `Administrator`. Navigate to the `<project_folder>` and activate the virtual environment (`.venv\Scripts\activate.bat`)

> (***NOTE:*** The installation must be done in a command prompt terminal. Since we also need the build tools from VS2015, it is ideal to use the `VS2015 x64 Native Tools Command Prompt`. We need to set several environment variables and the `set` command is actually different in `PowerShell` than what it is in `Command Prompt`.)

7. Navigate to `<project_folder>\.venv\Lib\site-packages` and clone the `pyembree` repo with the following command:

```
git clone https://github.com/scopatz/pyembree.git
```

8. Activate appropriate build environment variables by running:

```
"%PROGRAMFILES(X86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
```

9. Set the path to the `Embree`, `Visual Studio`, and `Windows SDK` `include` and `lib` files and tell `msbuild` to use the `Windows_SDK` when compiling by running the following:

```
set INCLUDE=C:\Program^ Files\Intel\Embree^ v2.17.7^ x64\include;C:\Program^ Files\Intel\Embree^ v2.17.7^ x64\include\embree2;C:\Program^ Files^ (x86)\Microsoft^ Visual^ Studio^ 14.0\VC\include;C:\Program^ Files^ (x86)\Windows^ Kits\10\Include\10.0.19041.0
set LIB=C:\Program^ Files\Intel\Embree^ v2.17.7^ x64\lib;C:\Program^ Files^ (x86)\Microsoft^ Visual^ Studio^ 14.0\VC\lib;C:\Program^ Files^ (x86)\Windows^ Kits\10\Lib\10.0.19041.0
set DISTUTILS_USE_SDK=1
```

> (***NOTE:*** The carets are necessary so Windows properly handles the spaces in the file paths. At the time of this writing, double-quotes did not work, but your mileage may vary.)

10. Lastly, run

```
poetry run py setup.py install
```

If all goes according to plan, `python` will install `pyembree` in your virtual environment site-packages folder and finish with the statement:

```
Installed <project_folder>\.venv\lib\site-packages\pyembree-0.1.6-py3.8-win-amd64.egg
Processing dependencies for pyembree==0.1.6
Finished processing dependencies for pyembree==0.1.6
```

_Originally posted by @adamgranthendry in https://github.com/pyvista/pyvista-support/issues/468#issuecomment-882974167_

**Comment by adamgranthendry** [comment]
Pasting my updated instructions from [Install pyembree on Windows without Conda #468](https://github.com/pyvista/pyvista-support/issues/468) here:

## Installation Instructions

### *Tested on:*

**OS:** Windows 10 x64 Professional, Build 1909
**Python:** 3.8.5 x64
**Date:** 31-JULY-2021

### Steps

1. Install [Microsoft Visual Studio 2017 Build Tools and the Windows 10 SDK](https://wiki.python.org/moin/WindowsCompilers). These are required for building `cython` code.

> (**NOTE:** *FYI, Microsoft Visual Studio version numbers are not the same as Microsoft Visual C++ Compiler versions. MSVCv14X x64/x86 build tools are required for Python 3.8. Installing the Visual Studio 2017 Build Tools with the Windows 10 SDK. If you wish to install Visual Studio 2017, select the `Desktop development with C++` Workload and make sure the required Windows 10 SDK build tool is selected under Individual Components. Refer to [the Python Wiki](https://wiki.python.org/moin/WindowsCompilers) for the right build tool versions to install).*

2. Install [vcpkg](https://vcpkg.io/en/index.html) in `C:\vcpkg` and add the path to your `System Environment Variables`. Be sure to bootstrap and integrate `vcpkg`:

```powershell
cd C:\vcpkg
git clone https://github.com/Microsoft/vcpkg.git
bootstrap-vcpkg.bat
vcpkg integrate install
```

Alternatively, you can download and install the [embree-2.17.7.x64.msi Installer](https://github.com/embree/embree/releases/tag/v2.17.7) on Embree's GitHub page (to learn more about Embree, visit [their website](https://www.embree.org/)).

3. Install `embree2 64-bit`. If using `vcpkg`, this is done from the command-line as:

```powershell
vcpkg install embree2:x64-windows
```

> **NOTE:** *To date, `pyembree` relies on Embree 2 and has not been updated version 3. The above command will install version 2.17.7, which is the required version.*

4. Create your project folder and initialize a virtual environment with `venv`. In this example, `Python 3.8.5 x64-bit` is chosen, simply as it is the Python version used in `Miniconda py38_4.9.2`. (It may work for Python 3.6 and 3.7, but at the time of this writing, one should not go to higher than 3.8)

5. Install the following packages:

```powershell
py -m pip install numpy cython wheel setuptools pyvista pykdtree rtree trimesh
```

6. Navigate to `<virtual environment folder>\Lib\site-packages` and clone the `pyembree` repo:

```powershell
git clone https://github.com/scopatz/pyembree.git
```

and remove the underlying `.git` subfolder.

7. Move into `pyembree` folder and modify the `setup.py` file to:

```python
import os
from setuptools import find_packages, setup

import numpy as np
from Cython.Build import cythonize
from Cython.Distutils import build_ext


include_path = [
    np.get_include(),
]

ext_modules = cythonize("pyembree/*.pyx", language_level=3, include_path=include_path)

for ext in ext_modules:
    ext.include_dirs = include_path
    ext.libraries = [
        "pyembree/embree2/lib/embree",
        "pyembree/embree2/lib/tbb",
        "pyembree/embree2/lib/tbbmalloc",
    ]

setup(
    name="pyembree",
    version="0.1.6",
    cmdclass={"build_ext": build_ext},
    ext_modules=ext_modules,
    zip_safe=False,
    packages=find_packages(),
    include_package_data=True,
    package_data={"pyembree": ["*.cpp", "*.dll"]},
)
```

8. Move into the `pyembree` subfolder. Copy the folder `C:\vcpkg\installed\x64-windows\include\embree2` into this folder (if you installed from the `.msi`, this will be the folder `C:\Program Files\Intel\Embree v2.17.7 x64\include\embree2`). In addition, copy the libraries from `C:\vcpkg\installed\x64-windows\lib` into this `embree2` folder (if you installed from the `.msi`, this will be the folder `C:\Program Files\Intel\Embree v2.17.7 x64\lib\`). You only need the (static) libraries

```
embree.lib
tbb.lib
tbbmalloc.lib
```

and dynamic libraries

```
embree.dll
tbb.dll
tbbmalloc.dll
```

9. Add the following line to the top of every `*.pyx` and `*.pxd` file in `pyembree`:

```python
# distutils: language=c++
```

and change every relative import of an `rtcore` module to an absolute import in each file. For example, change:

```python
cimport rtcore as rtc
```

to

```python
cimport pyembree.rtcore as rtc
```

10. Create the following `MANIFEST.in` file in the top-level `pyembree` folder:

```
include *.h *.pxd *.dll
recursive-include embree2 *.h *.isph
recursive-include embree2/lib *.lib
```

11. At the end, your folder should look like this:

```
<virtual environment folder>\Lib\site-packages\pyembree
│   .authors.yml
│   .gitignore
│   .mailmap
│   .travis-install.sh
│   .travis.yml
│   AUTHORS
│   CHANGELOG.rst
│   LICENSE
│   MANIFEST.in
│   README.rst
│   rever.xsh
│   setup.py
│   
├───examples
│       attenuate.py
│       intersection.py
│       
├───news
│       TEMPLATE.rst
│       
├───pyembree
│   │   embree.dll
│   │   mesh_construction.h
│   │   mesh_construction.pyx
│   │   rtcore.pxd
│   │   rtcore.pyx
│   │   rtcore_geometry.pxd
│   │   rtcore_geometry_user.pxd
│   │   rtcore_ray.pxd
│   │   rtcore_scene.pxd
│   │   rtcore_scene.pyx
│   │   tbb.dll
│   │   tbbmalloc.dll
│   │   triangles.pyx
│   │   __init__.pxd
│   │   __init__.py
│   │
│   └───embree2
│       │   rtcore.h
│       │   rtcore.isph
│       │   rtcore_builder.h
│       │   rtcore_geometry.h
│       │   rtcore_geometry.isph
│       │   rtcore_geometry_user.h
│       │   rtcore_geometry_user.isph
│       │   rtcore_ray.h
│       │   rtcore_ray.isph
│       │   rtcore_scene.h
│       │   rtcore_scene.isph
│       │   rtcore_version.h
│       │
│       └───lib
│               embree.lib
│               tbb.lib
│               tbbmalloc.lib
│
├───recipes
│   └───pyembree
│           build.sh
│           meta.yaml
│
└───tests
        test_intersection.py
```

12. Build `pyembree` by running the following from the top-level `pyembree` folder (**TIP:** *To help debug errors, pipe stderr to a local file `errors.txt` that you can look at*):

```
py setup.py build_ext -i 2> errors.txt
```

13. Test that everything is working correctly by opening a python terminal in your virtual environment and running

```python
>>> import pyembree
>>> from pyembree import rtcore_scene
>>>
```

If you get no errors, then `pyembree` has been installed correctly. You can also create a `.egg` and install the library with

```
py setup.py install
```

The `setup.py` we created will copy the `dll`s and `cpp` files to the correct folder.

14. As a last optional step, create a `main.py` in your virtual environment and copy and paste the code from `Project to Finite Plane` demo. If it runs without errors in approximately 1-2 seconds, then `pyembree` is working properly with `trimesh` for vectorized ray tracing (**NOTE:** `trimesh` will work without `pyembree`, but it will be very slow. It should not take a long time to run this example code if `pyembree` is properly installed. `trimesh` resorts back to `trimesh.ray.ray_triangle.RayMeshIntersector` if it cannot import `pyembree` (see [pyembree ray casting acceleration #875](https://github.com/mikedh/trimesh/issues/875)), so you won't see any errors; just slow running code):

```python
import numpy as np
from pykdtree.kdtree import KDTree

import pyvista as pv
from pyvista import examples

# Load data
data = examples.load_random_hills()
data.translate((10, 10, 10))

# Create triangular plane (vertices [10, 0, 0], [0, 10, 0], [0, 0, 10])
size = 10
vertices = np.array([[size, 0, 0], [0, size, 0], [0, 0, size]])
face = np.array([3, 0, 1, 2])

planes = pv.PolyData(vertices, face)

# Subdivide plane so we have multiple points to project to
planes = planes.subdivide(8)

# Get origins and normals
origins = planes.cell_centers().points
normals = planes.compute_normals(cell_normals=True, point_normals=False)["Normals"]

# Vectorized Ray trace
points, pt_inds, cell_inds = data.multi_ray_trace(
    origins, normals
)  # Must have rtree, trimesh, and pyembree installed

# Filter based on distance threshold, if desired (mimics VTK ray_trace behavior)
# threshold = 10  # Some threshold distance
# distances = np.linalg.norm(origins[inds] - points, ord=2, axis=1)
# inds = inds[distances <= threshold]

tree = KDTree(data.points.astype(np.double))
_, data_inds = tree.query(points)

elevations = data.point_arrays["Elevation"][data_inds]

# Mask points on planes
planes.cell_arrays["Elevation"] = np.zeros((planes.n_cells,))
planes.cell_arrays["Elevation"][pt_inds] = elevations
planes.set_active_scalars("Elevation")  # Probably not necessary, but just in case

# Create axes
axis_length = 20
tip_length = 0.25 / axis_length * 3
tip_radius = 0.1 / axis_length * 3
shaft_radius = 0.05 / axis_length * 3
x_axis = pv.Arrow(
    direction=(axis_length, 0, 0),
    tip_length=tip_length,
    tip_radius=tip_radius,
    shaft_radius=shaft_radius,
    scale="auto",
)
y_axis = pv.Arrow(
    direction=(0, axis_length, 0),
    tip_length=tip_length,
    tip_radius=tip_radius,
    shaft_radius=shaft_radius,
    scale="auto",
)
z_axis = pv.Arrow(
    direction=(0, 0, axis_length),
    tip_length=tip_length,
    tip_radius=tip_radius,
    shaft_radius=shaft_radius,
    scale="auto",
)
x_label = pv.PolyData([axis_length, 0, 0])
y_label = pv.PolyData([0, axis_length, 0])
z_label = pv.PolyData([0, 0, axis_length])
x_label.point_arrays["label"] = [
    "x",
]
y_label.point_arrays["label"] = [
    "y",
]
z_label.point_arrays["label"] = [
    "z",
]

# Plot results
p = pv.Plotter()
p.add_mesh(x_axis, color="r")
p.add_point_labels(x_label, "label", show_points=False, font_size=24)
p.add_mesh(y_axis, color="r")
p.add_point_labels(y_label, "label", show_points=False, font_size=24)
p.add_mesh(z_axis, color="r")
p.add_point_labels(z_label, "label", show_points=False, font_size=24)
p.add_mesh(data)
p.add_mesh(planes)
p.show()
```

**Comment by akaszynski** [comment]
@adamgranthendry, we should be able to get a release out this week (or at worst, next week), and I'll make sure that we have a PR created prior to that for you to review.

**Comment by adamgranthendry** [comment]
@akaszynski Excellent! Looking forward to it!...Any chance I could become a contributor to `pyvista`? I'd love to continue helping and supporting.

**Comment by akaszynski** [comment]
Just sent the invite.  It would be great to have you part of the team!

**Comment by adamgranthendry** [comment]
@akaszynski Thanks so much! Just joined! 😃

**Comment by Hafplo** [comment]
@akaszynski @adamgranthendry 
Tried following the steps to install it, but failed miserably.
Adding pyembree to PyPi would remove a major blocker for Windows users.

**Comment by adam-grant-hendry** [comment]
@akaszynski I actually have added it to PyPI in my fork. Should we add this to the instructions now?

@Hafplo I have put my steps into a fork of the repo

[https://github.com/adam-grant-hendry/pyembree](https://github.com/adam-grant-hendry/pyembree)

and uploaded to PyPI

[https://pypi.org/project/pyembree/](https://pypi.org/project/pyembree/)

You can pip install this now. It will be at version 0.1.9.

**Comment by adam-grant-hendry** [comment]
@Hafplo Please thumbs up my PR request on the master pyembree repo:

[https://github.com/scopatz/pyembree/pull/34](https://github.com/scopatz/pyembree/pull/34)

The original owner has not been interested in maintaining the project. If this continues, I intend to maintain my separate fork and add `embree3` support along with many other features.

**Comment by adam-grant-hendry** [comment]
@akaszynski @Hafplo @pyvista/developers `pyembree` version `0.2.11` now has built MacOS, many-Linux, and Windows wheels. This was done through GitHub Actions.

**Comment by adam-grant-hendry** [comment]
@akaszynski We can probably close this issue now (adding install instructions to `pyvista` ) since you should be able to pip install pyembree now on all platforms now (only python 3.8 supported now).
