### ISSUE TITLE
Some Doc figures broken

### ISSUE THREAD

**Issue by AndrewAnnex** [pyvista/pyvista#1543]
I was reading the docs for https://docs.pyvista.org/examples/01-filter/clipping-with-surface.html?highlight=clip and I noticed some of the figures appear empty, just showing the colorbars/labels but not the actual meshes. for example:
![empty](https://docs.pyvista.org/_images/sphx_glr_clipping-with-surface_003.png)

**Comment by akaszynski** [comment]
Issue is caused by our virtual framebuffer being unable to render docs correctly.  Will be fixed in the next release when we manually regenerate the docs.

**Comment by tkoyama010** [comment]
Ref https://dev.pyvista.org/examples/01-filter/clipping-with-surface.html?highlight=clip
