### ISSUE TITLE
remove background causing issues in rendering

### ISSUE THREAD

**Issue by cakester** [pyvista/pyvista#1548]
if you add background to the plotter and then remove it, and then you do things such as rotation, you get a screwed image
-----

**To Reproduce**
add background image to plotter, then remove it, then rotate your image

```py

plotter = pv.Plotter()
plotter.add_mesh(pc, cmap='Reds')
plotter.add_mesh(mesh, cmap="Reds")
plotter.add_mesh(image_pv, rgb=True)
plotter.add_background_image(examples.mapfile)
plotter.remove_background_image()
plotter.add_axes(interactive=True)
plotter.show_axes()

plotter.show()

```

**Screenshots**
![image](https://user-images.githubusercontent.com/1713718/127701620-0dd2d664-c074-4fb7-bded-45c990b1ef3d.png)

-----

**System Information:**
 Please run the following code wherever you are experiencing the bug and paste the output below. This report helps us track down bugs and it is critical to addressing your bug:

```py
# Get system info
import pyvista as pv
print(pv.Report())
```

```txt
# Paste system info here

```
Python 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvista
>>> print(pyvista.Report())

--------------------------------------------------------------------------------
  Date: Fri Jul 30 20:19:13 2021 ric

                OS : Windows
            CPU(s) : 16
           Machine : AMD64
      Architecture : 64bit
               RAM : 29.7 GiB
       Environment : Python
        GPU Vendor : ATI Technologies Inc.
      GPU Renderer : AMD Radeon(TM) Pro Graphics
       GPU Version : 4.5.13596 Core Profile Context FireGL 20.10.30.12 27.20.11030.12004

  Python 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit
  (AMD64)]

           pyvista : 0.31.3
               vtk : 9.0.2
             numpy : 1.19.5
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.7
            meshio : 4.4.6
        matplotlib : 3.4.1
           IPython : 7.25.0
             scipy : 1.6.2
              tqdm : 4.60.0
--------------------------------------------------------------------------------

**Comment by akaszynski** [comment]
Thanks for pointing this out.  Will be fixed in #1551.
