### ISSUE TITLE
Tutorials in scipy2022

### ISSUE THREAD

**Issue by tkoyama010** [pyvista/pyvista#1556]
[Tutorials](https://www.scipy2022.scipy.org/tutorials) - We have to make 4 hours tutorial.

We can maybe use a tutorial in VTK example.
https://kitware.github.io/vtk-examples/site/Python/Tutorial/Tutorial_Step1/
https://kitware.github.io/vtk-examples/site/Python/Tutorial/Tutorial_Step2/
https://kitware.github.io/vtk-examples/site/Python/Tutorial/Tutorial_Step3/
https://kitware.github.io/vtk-examples/site/Python/Tutorial/Tutorial_Step4/
https://kitware.github.io/vtk-examples/site/Python/Tutorial/Tutorial_Step5/
https://kitware.github.io/vtk-examples/site/Python/Tutorial/Tutorial_Step6/

**Comment by tkoyama010** [comment]
Mayavi2 tutorial in  SciPy 2018 is a good example for us.
https://youtu.be/r6OD07Qq2mw

**Comment by tkoyama010** [comment]
dask community made a dask tutorial at SciPy 2020 in https://github.com/dask/dask-tutorial. @pyvista/developers Can we make pyvista-tutorial repository under pyvista organization?

**Comment by tkoyama010** [comment]
I made https://github.com/pyvista/pyvista-tutorial .

**Comment by tkoyama010** [comment]
Great tutorial thanks!

**Comment by banesullivan** [comment]
Materials are hosted at tutorial.pyvista.org

**Comment by akaszynski** [comment]
> Materials are hosted at https://tutorial.pyvista.org

Are the recordings up?

**Comment by tkoyama010** [comment]
Not yet it takes a little time to edit I think.
https://www.youtube.com/c/enthought/videos

**Comment by liududu** [comment]
Is the video available right now? I see most other videos were uploaded 5 days ago

**Comment by akaszynski** [comment]
The mayavi video is still not there, so either someone lost the HD or it's just waiting to be uploaded.

**Comment by liududu** [comment]
I guess they just forgot to upload the video, I'm quite interesting in the video content of this tutorial. Is there any chance that you could contact with the organizer to confirm the status? Many thanks!

**Comment by banesullivan** [comment]
I reached out today, and PyVista's tutorial is not the only one missing. It appears they are still working on getting all of the content uploaded. Thanks for bearing with us!
