### ISSUE TITLE
`PolyData` with square face not showing on `ipygany` backend

### ISSUE THREAD

**Issue by dstansby** [pyvista/pyvista#1558]
**Describe the bug, what's wrong, and what you expect:**

Plotting a `PolyData` with a square face using the `ipygany` backend doesn't show anything. The code snippet is below. Running this in a standard `.py` file and showing in a normal window is working fine, and shows a square.

Weirdly, appending one extra (redundant) vertex to `vertices` fixes the issue in `ipygany` - I suspect this will help with debugging!

-----

**To Reproduce**

In a jupyter notebook:

```py
import numpy as np
import pyvista as pv

# mesh points
vertices = np.array([[0, 0, 0],
                     [1, 0, 0],
                     [1, 1, 0],
                     [0, 1, 0]])

# mesh faces
faces = np.hstack([[4, 0, 1, 2, 3]])

surf = pv.PolyData(vertices, faces)

# plot each face with a different color
p = pv.Plotter()
p.add_mesh(surf)
p.show(jupyter_backend='ipygany')
```

**Screenshots**

-----

**System Information:**

```txt
--------------------------------------------------------------------------------
  Date: Tue Aug 03 10:39:12 2021 BST

                OS : Darwin
            CPU(s) : 4
           Machine : x86_64
      Architecture : 64bit
               RAM : 8.0 GiB
       Environment : Python
        GPU Vendor : Intel Inc.
      GPU Renderer : Intel Iris OpenGL Engine
       GPU Version : 4.1 INTEL-16.1.11

  Python 3.9.5 (default, May 18 2021, 12:31:01)  [Clang 10.0.0 ]

           pyvista : 0.31.3
               vtk : 9.0.3
             numpy : 1.20.2
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.7
            meshio : 4.4.6
        matplotlib : 3.4.2
             PyQt5 : 5.15.2
           IPython : 7.25.0
             scipy : 1.7.0
              tqdm : 4.54.0

  Intel(R) oneAPI Math Kernel Library Version 2021.2-Product Build 20210312
  for Intel(R) 64 architecture applications
--------------------------------------------------------------------------------

```

**Comment by akaszynski** [comment]
In the next release we're going to provide a better jupyterlab backend, please see https://github.com/pyvista/pyvista/pull/1557.  `ipygany` has some severe limitations and I need a backend that I have access to the lower level three.js backend.

**Comment by dstansby** [comment]
Ooh nice! I'm using `ipygany` to output examples in HTML documentation at the moment, so if it would be helpful for me to try out a development version `three.js` backend for feedback then let me know.

**Comment by akaszynski** [comment]
Checkout the `fix/ipygany_structured_mesh` branch and look at our documentation section to see its usage.

**Comment by banesullivan** [comment]
This is a limitation of the external ipygany package. We have other notebook rendering backends that better handle this so I'm going to close this issue as there isn't much action we can take
