### ISSUE TITLE
Subplots not working with ipygany backend

### ISSUE THREAD

**Issue by renefritze** [pyvista/pyvista#1559]
I'm trying to use the subplotting feature with the ipygany backend, following [this example](https://docs.pyvista.org/examples/00-load/create-geometric-objects.html#)

```py
import pyvista as pv
print(pv.__version__)
cyl = pv.Cylinder()
arrow = pv.Arrow()
sphere = pv.Sphere()
plane = pv.Plane()
line = pv.Line()
box = pv.Box()
cone = pv.Cone()
poly = pv.Polygon()
disc = pv.Disc()
p = pv.Plotter(shape=(3, 3))
# Top row
p.subplot(0, 0)
p.add_mesh(cyl, color="tan", show_edges=True)
p.subplot(0, 1)
p.add_mesh(arrow, color="tan", show_edges=True)
p.subplot(0, 2)
p.add_mesh(sphere, color="tan", show_edges=True)
# Middle row
p.subplot(1, 0)
p.add_mesh(plane, color="tan", show_edges=True)
p.subplot(1, 1)
p.add_mesh(line, color="tan", line_width=3)
p.subplot(1, 2)
p.add_mesh(box, color="tan", show_edges=True)
# Bottom row
p.subplot(2, 0)
p.add_mesh(cone, color="tan", show_edges=True)
p.subplot(2, 1)
p.add_mesh(poly, color="tan", show_edges=True)
p.subplot(2, 2)
p.add_mesh(disc, color="tan", show_edges=True)
# Render all of them
p.show(jupyter_backend='ipygany')
```
Instead of the 3x3 individual objects, I only see the last one added.

![screenshot-localhost_8889-2021 08 03-12_08_13](https://user-images.githubusercontent.com/47802/127998410-c0e9e81b-c3bb-487b-8cc0-9e246fb98ee9.png)

**Comment by akaszynski** [comment]
That's a known issue that we're going to try to address by using the `pythreejs` backend in https://github.com/pyvista/pyvista/pull/1557.  Might take a week to get that out, but it's coming.

**Comment by renefritze** [comment]
Ok, great. I'd be happy to test that PR once you think it _should_ work. Feel free to ping me there!

**Comment by akaszynski** [comment]
https://github.com/pyvista/pyvista/pull/1557 already works better than the `ipygany` backend.  Please checkout `fix/ipygany_structured_mesh` and let me know if you encounter further issues in #1557.
