### ISSUE TITLE
Inheritance of `pyvista.PolyData`, error by `.overwrite()`

### ISSUE THREAD

**Issue by Onandon11** [pyvista/pyvista#1565]
In our project we heavily rely on the `pyvista.PolyData` object, therefore we made our own class - which inherits from `pyvista.PolyData` - with our own custom methods.

However when using functions with the `inplace` argument, the underlying function `overwrite` causes an AssertionError because the types doesn't match.

Code to reproduce at Windows, PyVista version 0.31.1
```python
import pyvista
import numpy

class Foo(pyvista.PolyData):
    pass

foo = Foo()
foo.points = np.eye(3)
foo.delaunay_2d(inplace=True)


Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\git\geams-lib\.venv39\lib\site-packages\pyvista\core\filters.py", line 4971, in delaunay_2d
    poly_data.overwrite(mesh)
  File "C:\git\geams-lib\.venv39\lib\site-packages\pyvista\core\dataset.py", line 767, in overwrite
    raise TypeError('The Input DataSet type must match '
TypeError: The Input DataSet type must match the one being overwritten <class '__main__.Foo'>
```

We have a current workaround where we monkey-patch the original `PolyData` class, but this is farm from neat or ideal.

Proposal:
Maybe loosen the type-checking, or use `issubclass` instead of `isinstance`.

**Comment by MatthewFlamm** [comment]
Interesting use case.  I like this idea to allow for inherited datasets to allow for custom functionality, but I think we need to think through the implications before implementing.  I think this approach that you propose will work for the case where you can simply morph all `PolyData` objects into a `Foo` object.  In the case where you cannot, you will still want to use the same `isinstance` check.  Is there a one-size fits all approach here?

For now, I would recommend overwriting the `overwrite` method in Foo, which is inline with your strategy of extending the functionality of `PolyData`.  No monkeypatching needed in this method.

```py
import pyvista
import numpy as np

class Foo(pyvista.PolyData):
    def overwrite(self, mesh):
        if not issubclass(type(self), type(mesh)):
            raise TypeError(f'The Input DataSet type {type(mesh)} must match '
                            f'the one being overwritten {type(self)}')
        self.deep_copy(mesh)
        if pyvista.utilities.is_pyvista_dataset(mesh):
            self.copy_meta_from(mesh)
    pass

foo = Foo()
foo.points = np.eye(3)
foo.delaunay_2d(inplace=True)
```

**Comment by Onandon11** [comment]
Stupid that I didn't came up with that 🤦 

However, my stupidity had a befenit I didn't noticed at forehand. By monkey patching all the functions of `PolyData` - using either `inplace=True` or `inplace=False` - which would have returned a `PolyData` object now returns a `Foo` object.

If I would implement your suggestion I would have a `Foo` object only when using `inplace=True`. In all other cases I still get a `PolyData` object which I have to cast to my own object type...

**Comment by MatthewFlamm** [comment]
We could allow developers to override the default class that a vtk object is coerced to in `pyvista.wrap`.  I think this is the most elegant solution.

**Comment by Onandon11** [comment]
I agree that would be great!
