### ISSUE TITLE
Code coverage reporting is inaccurate

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#157]
The code coverage reported to codecov.io is not complete. The code is tested in a series of runs:

- [x] `python -m pytest -v --cov pyvista`
- [ ] `python -m pytest -v --cov --doctest-modules pyvista`
- [ ] `cd ./docs/; make doctest;`
- [ ] also the notebook gallery... I think this is inlcuded in `make doctest`

There is a way to combine the coverage results of all these runs before reporting to codecov.io but I don't know how to get it working.

**Comment by GuillaumeFavelier** [comment]
After reading the docs of [`coverage`](https://coverage.readthedocs.io/en/coverage-4.4.2/cmd.html#data-file) and [`pytest-doc`](https://pytest-cov.readthedocs.io/en/latest/config.html#reference), I think we could try:

First clean any coverage data:

```
coverage erase
```

Then create the default `.coverage` data at the root:

```
python -m pytest -v --cov pyvista
```

Start the second run and **append** the result:

```
python -m pytest -v --cov --doctest-modules pyvista --cov-append
```

For `./docs` I think the [`sphinx coverage extension`](https://www.sphinx-doc.org/en/master/usage/extensions/coverage.html) needs to be enabled in [`docs/conf.py`](https://github.com/pyvista/pyvista/blob/master/docs/conf.py#L30-L38) then `make coverage` could help but I couldn't manage to make it work locally. Maybe I missed something.

**Comment by akaszynski** [comment]
I'm closing this as our coverage is (just about) accurately reported with our unit testing.
