### ISSUE TITLE
Add linkcheck to sphinx build

### ISSUE THREAD

**Issue by tkoyama010** [pyvista/pyvista#1574]
### Discussed in https://github.com/pyvista/pyvista/discussions/1539

<div type='discussions-op-text'>

<sup>Originally posted by **tkoyama010** July 23, 2021</sup>
There is a option to check the integrity of all external links in [sphinx-build option](https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-b). This will be a good first issue in Scipy2022.</div>

**Comment by laysauchoa** [comment]
Hi, I'd love to contribute to the pyvista project. Would be possible to assign this issue to me? Thanks!

**Comment by tkoyama010** [comment]
@laysauchoa Thanks for contributing! We welcome your contribution.

**Comment by laysauchoa** [comment]
Before adding this workflow, let's clarify some important points:

I can add one workflow to run for all the files in every push
advantage: catch any link that fails in every push
disadvantage: it may make things slow if you have there are too many links
 
OR

I can add two workflows: 

- one to run in every push only in the changed files 
- one to run weekly in the whole file

advantage: runs faster and avoid false positive
disadvantage: maybe something fails in between and you will only catch in a week basis

**Comment by tkoyama010** [comment]
Nice analysis, I think it would be clearer if you measured the time with PullRequest.

**Comment by laysauchoa** [comment]
linkcheck will take 35 min or a bit more. wdyt? I'd say that running periodically would make more sense to not have to wait for this long. However, a link could break in between.

**Comment by akaszynski** [comment]
Might make sense to run this as a weekly cron job.
