### ISSUE TITLE
Creating grid from cells

### ISSUE THREAD

**Issue by kirillantonov2901** [pyvista/pyvista#1578]
Hi there! I'm newbie to pyvista but still trying to carry out my idea)
Goal is to plot (visualize) grid from geological simulator. Input data is vertices of cells + integer parameter - cell color (8 verticles for each cell) in XYZ parameter format. It contains several millions cells and I think I would be rather hard to plot the whole model so in my opinion it would be right to plot only it's  faces. But I have no idea to start from, need help. From examples it seems that unstructed grid is OK for my purpose. 
I'd like is to get this as a result
![Reservoir-model-used-for-history-matching-the-observed-changes-in-the-reservoir-showing](https://user-images.githubusercontent.com/55129933/128609112-79065d96-62df-4f70-a2fa-5a1adf087587.png)
</div>

**Comment by tkoyama010** [comment]
We have [Discussion of this](https://github.com/pyvista/pyvista/discussions/1570). Closing.
