### ISSUE TITLE
We also need to use `check_valid_vector` in rotate_* filters.

### ISSUE THREAD

**Issue by tkoyama010** [pyvista/pyvista#1580]
We also need to use `check_valid_vector` in rotate_* filters.

_Originally posted by @tkoyama010 in https://github.com/pyvista/pyvista/pull/1569#discussion_r684987584_

**Comment by RobPasMue** [comment]
This one looks also solved @tkoyama010 

Please look into https://github.com/pyvista/pyvista/blob/main/pyvista/core/dataset.py

All rotate methods seem to have the `check_valid_vector` implemented.

**Comment by RobPasMue** [comment]
Closing issue after face-to-face discussion with @tkoyama010 - implementation is already done

**Comment by tkoyama010** [comment]
@RobPasMue Thanks.
