### ISSUE TITLE
Feature Request: Allow for easier generation of docs with no internet connection

### ISSUE THREAD

**Issue by MatthewFlamm** [pyvista/pyvista#1588]
**Describe the bug, what's wrong, and what you expect:**

One roadblock I have in developing the documentation is that it is required to be able to download the data using the `examples.download_*` functions.  It is easier for me to generate the documentation on a system without direct access to download these files.

I have been able to get around this somewhat by cloning the vtk-data repository and then copying over all the files under Data.  In this way I get most of the files, but certain data files are zipped or inside nested folders.  It would be convenient if there was an option to allow the examples directory to be built from a local vtk-data repo source rather than having to download it.

This _might_ speed up the CI too, especially if the repo data could be shared amongst the test jobs.

**Comment by MatthewFlamm** [comment]
This has hampered my ability to fully add documentation for #1536 and #1584.

**Comment by akaszynski** [comment]
That's a good idea.  One option would be to check if there was an env var `PYVISTA_VTK_DATA` defined, and then use that path instead.

Would require a bit of rework in `downloads.py`, but I think this can be done without too much effort.

**Comment by MatthewFlamm** [comment]
I have a working implementation as this was really hampering my other PRs.  I will open a PR soon.

**Comment by akaszynski** [comment]
> I have a working implementation as this was really hampering my other PRs. I will open a PR soon.

Thanks!
