### ISSUE TITLE
Create a banner for home page

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#159]
We should create a banner of **really cool visualizations** produced with `vtki` to display on the README and the first page of the docs.

I think having some flashy visuals on the homepage would help communicate what `vtki` can do. Currently, if a new user comes across `vtki` that have to do some light reading to figure out what's capable of - graphics might help entice people to do the reading.

@akaszynski, perhaps some of the ones for the paper?

On that note, I'm wrapping up a big project this week (data has a creative commons license) and will have some big-time examples of geo-data/models

**Comment by akaszynski** [comment]
Perhaps a mutli-window of some of our best animations?  I really like the visualization of Mount St. Helens.  We could include that along with the world plot (for textures) and a vector plot.  Maybe the last one can be a geo-data model?

**Comment by banesullivan** [comment]
Perhaps something like this?:

![vtki-banner](https://user-images.githubusercontent.com/22067021/56105245-88b56380-5ef8-11e9-83c0-59862679616f.png)

**Comment by akaszynski** [comment]
Looks great!  How did you make that?

**Comment by banesullivan** [comment]
I made this with a free Mac app: [TurboCollage](http://www.turbocollage.com)

Unfortunately, I don't think it'll make what I want with ~50 small pictures but I really like the hexagon tiles

**Comment by banesullivan** [comment]
Note there's a new "Social preview" option in the settings for setting a social media image. This would be appropriate for that

**Comment by banesullivan** [comment]
We definitely need to make this a high priority so people simply glancing at the readme or docs homepage will see what PyVista can do

**Comment by akaszynski** [comment]
We've had a banner for quite some time.  Closing.
