### ISSUE TITLE
numpy type check failure

### ISSUE THREAD

**Issue by Arun-Niranjan** [pyvista/pyvista#16]
When running the demo for advanced numpy plotting from the docs http://vtkinterface.readthedocs.io/en/latest/index.html

I get the following error:
  File "C:\Users\aniranjan\AppData\Local\Continuum\anaconda3\envs\py35\lib\site-packages\vtkInterface\plotting.py", line 1090, in AddArrows
    pdata = vtkInterface.CreateVectorPolyData(cent, direction * mag)
  File "C:\Users\aniranjan\AppData\Local\Continuum\anaconda3\envs\py35\lib\site-packages\vtkInterface\utilities.py", line 138, in CreateVectorPolyData
    vcells.SetCells(npts, numpy_to_vtkIdTypeArray(cells, deep=True))
  File "C:\Users\aniranjan\AppData\Local\Continuum\anaconda3\envs\py35\lib\site-packages\vtk\util\numpy_support.py", line 192, in numpy_to_vtkIdTypeArray
    'Expecting a numpy.int32 array, got %s instead.' % (str(dtype)))
ValueError: Expecting a numpy.int32 array, got int64 instead.

The issue appears to be in numpy_to_vtkIdTypeArray(), or at least how it's called in AddArrows()->CreateVectorPolyData()->vtk.vtkCellArray().SetCells()

**Comment by akaszynski** [comment]
This is a bug due to windows vs Linux long size.  It’s been fixed as of 0.8.5, and it’s live on PyPi.

Now using Travis CI to avoid these types of bugs.

**Comment by akaszynski** [comment]
Looks like I needed to use appveyor to check in the windows environment.  Bug is eliminated as of 0.9.2 and available on PyPi.

**Comment by kinverarity1** [comment]
Just a note that I'm seeing this bug for all examples. I am using:

- Python 3.6.5 | packaged by conda-forge | (default, Apr  6 2018, 16:13:16) [MSC v.1900 32 bit (Intel)] on win32
- vtk                       8.1.0             py36_vc14_202    conda-forge
- pyvista from github master

Is this something wrong with my setup?

**Comment by akaszynski** [comment]
Could you please run and return what's reported?
```python
import scooby
scooby.Report()
```

**Comment by kinverarity1** [comment]
```
--------------------------------------------------------------------------------
  Date: Thu Jul 18 09:35:25 2019 Cen. Australia Standard Time

           Windows : OS
                 4 : CPU(s)
             AMD64 : Machine
             32bit : Architecture
           Jupyter : Environment

  Python 3.6.5 | packaged by conda-forge | (default, Apr  6 2018, 16:13:16)
  [MSC v.1900 32 bit (Intel)]

            1.16.4 : numpy
             1.2.1 : scipy
             6.3.1 : IPython
             2.2.2 : matplotlib
             0.4.3 : scooby
--------------------------------------------------------------------------------
```

**Comment by kinverarity1** [comment]
OK, I have found the problem (and a temporary workaround).

```python
>>> import pyvista
>>> pyvista.ID_TYPE
<class 'numpy.int64'>
>>> import vtk
>>> vtk.VTK_ID_TYPE
12
>>> vtk.vtkCommonCore.vtkIdTypeArray().GetDataTypeSize()
4
```

From what little I understand (out of my depth here), the last two commands should return the same number.

A minimal example is here: https://github.com/kinverarity1/pyvista-issue16

My temporary workaround is:

```python
import pyvista as pv
import numpy as np
pv.ID_TYPE = np.int32
```
