### ISSUE TITLE
Rectangle --> Quadrilateral 

### ISSUE THREAD

**Issue by akaszynski** [pyvista/pyvista#1604]
Our rectangle isn't constrained and should be called a Quadrilateral.

**Comment by StefRe** [comment]
Not sure if this is intended, but [Rectangle](https://docs.pyvista.org/api/utilities/_autosummary/pyvista.Rectangle.html?highlight=rectangle#pyvista.Rectangle) doesn't enforce neither flatness (2D) not order of points:

- `pv.Rectangle([[1.0, 0.0, 0.0], [1.0, 1.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]])`
![image](https://user-images.githubusercontent.com/19879328/170784724-588f6422-a3ef-4ec9-a674-43d25299bccb.png)

- `pv.Rectangle([[0.0, 0.0, 0.0], [1.0, 1.0, 0.0], [1.0, 0.0, 0.0], [0.0, 1.0, 0.0]])`
![image](https://user-images.githubusercontent.com/19879328/170784460-1da8d68c-e870-4f01-934e-48e5c5d10b93.png)

**Comment by akaszynski** [comment]
Let's add a co-planar and order check and rename this to `Quadrilateral`. You up to that @StefRe?
