### ISSUE TITLE
memory leaks with inplace=True filters

### ISSUE THREAD

**Issue by AndrewAnnex** [pyvista/pyvista#1606]
**Describe the bug, what's wrong, and what you expect:**

I tend to work with large 2 dimensional elevation models (6k by 10k or more) that I am converting to pyvista meshes and then using various pyvista filters (clip, triangulate, extract_surface, and decimate) in order to clean-up and reduce the mesh complexity.

However despite having 64gb of ram for a recent mesh I was processing with the newer I kept running into  a slowdown. After running each step and monitoring my memory usage it looks like most filters do not properly release memory when the inplace=True flag is used, and that I could reclaim some but not all memory by creating a new object and then manually attempting to free memory on the earlier mesh version by calling 
```
m.ReleaseData()
m.FastDelete()
m.Squeeze()
```

In particular, the decimate function seems to be a particular memory hog and seemingly doubles the memory usage.

Looking at the source code, it doesn't appear that any memory management is attempted when the inplace flag is used, and since the mesh is created inside the function and not returned there is no clear way to call delete it or access the underlying vtk object to attempt function calls on. 

-----

**To Reproduce**

I haven't attempted to make a reproducible code example but I imagine the following pseudo code on a sufficiently large enough initial mesh would illustrate the issue 

```py
# Insert code here
m = some_big_mesh

for i in range(100_000):
     m2 = m.decimate(0.6, progress_bar=True) # and watch your memory usage

```
-----

**System Information:**
 Please run the following code wherever you are experiencing the bug and paste the output below. This report helps us track down bugs and it is critical to addressing your bug:

```py
# Get system info
import pyvista as pv
print(pv.Report())
```

```txt
# Paste system info here

--------------------------------------------------------------------------------
  Date: Tue Aug 24 00:06:38 2021 EDT

                OS : Linux
            CPU(s) : 16
           Machine : x86_64
      Architecture : 64bit
       Environment : Jupyter
NVIDIA Corporation : GPU Vendor
GeForce GTX 1080 Ti/PCIe/SSE2 : GPU Renderer
4.5.0 NVIDIA 460.91.03 : GPU Version

  Python 3.8.5 | packaged by conda-forge | (default, Aug 21 2020, 18:21:27)
  [GCC 7.5.0]

           pyvista : 0.25.3
               vtk : 9.0.1
             numpy : 1.19.1
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.6
            meshio : 4.1.1
        matplotlib : 3.3.1
             PyQt5 : 5.9.2
           IPython : 7.17.0
          colorcet : 1.0.0
              tqdm : 4.48.2
--------------------------------------------------------------------------------

```

**Comment by MatthewFlamm** [comment]
I also find weird behavior with multiple filters that change the mesh size as well.  Sometimes a `clean` filter works, but I have struggled to come up with a reproducible example.  Your example does not have an issue in my testing on pyvista v0.31.0 either.

![image](https://user-images.githubusercontent.com/39341281/130690955-01fea747-ddc3-46bd-b492-940df5d8d30e.png)

This file is run using `mprof run file.py`

```py
import pyvista as pv
from tqdm import tqdm

@profile
def run_decimate(size, n):
    mesh = pv.Sphere(theta_resolution=size, phi_resolution=size)
    for _ in tqdm(range(n)):
        new_mesh = mesh.decimate(0.6, inplace=False)

if __name__ == '__main__':
    run_decimate(500, 100)    
```

**Comment by AndrewAnnex** [comment]
yeah.. I didn't test my example to see if it would work, the issue is that I am not just using decimate, I have a bit of a complicated workflow calling a number of filters first and the last step is decimate call, starting with a structured mesh that then is converted to a unstructured mesh and then finally to polydata, for reference the mesh starts out with hundreds of millions of faces, but I think I could potentially make a clearer demonstration with some publicly available data soon
