### ISSUE TITLE
vtkSurfaceReconstructionFilter: reconstruct surface from point cloud around 3D volume

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#1614]
Over time, I have seen a ton of questions asking how to triangulate the surface of a 3D object from a point cloud. As many examples have demonstrated, this is tough to do with delaunay triangualation:

- https://github.com/pyvista/pyvista-support/issues/397
- https://github.com/pyvista/pyvista-support/issues/213
- https://github.com/pyvista/pyvista-support/issues/170
- https://github.com/pyvista/pyvista-support/issues/178
- and many more...

This task is actually handled quite well by the [`vtkSurfaceReconstructionFilter` filter in VTK](https://vtk.org/doc/nightly/html/classvtkSurfaceReconstructionFilter.html#details) and we should work to make this a new filter in PyVista for `PolyData` meshes. Here is example usage:

```py
import pyvista as pv
import numpy as np
from pyvista import _vtk as vtk

points = pv.wrap(pv.Sphere().points)

alg = vtk.vtkSurfaceReconstructionFilter()
alg.SetInputDataObject(points)
alg.Update()
mc = vtk.vtkMarchingCubes()
mc.SetInputDataObject(alg.GetOutput())
mc.SetValue(0, 0.0)
mc.Update()
surf = pv.wrap(mc.GetOutput())
surf.clear_data()

p = pv.Plotter(shape=(1,2))
p.add_mesh(points)
p.add_title('Point Cloud of 3D Surface')
p.subplot(0,1)
p.add_mesh(surf, color=True, show_edges=True)
p.add_title('Reconstructed Surface')
p.show()
```

<img width="768" alt="Screen Shot 2021-08-28 at 1 28 00 PM" src="https://user-images.githubusercontent.com/22067021/131228784-a6dd7278-338c-404f-bf7f-2bd0da790979.png">

**Comment by akaszynski** [comment]
Had no idea VTK had this.  I'll write up an example.

**Comment by yixuanqi** [comment]
My problem is that I need to associate a scalar to every point in order to generated a colored surface (with a lookup-table). However the surface have always an unique color and seems that the scalar data are ignored (or maybe lost by the filters). How I can obtain that result?

Thanks

**Comment by emile0767** [comment]
> My problem is that I need to associate a scalar to every point in order to generated a colored surface (with a lookup-table). However the surface have always an unique color and seems that the scalar data are ignored (or maybe lost by the filters). How I can obtain that result?
> 
> Thanks

Have you find any solution to this problem ? 
thx in advance, 
Emile
