### ISSUE TITLE
Clip entire scene

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#162]
We should implement a feature to easily clip by a box all of the actors in a rendering scene, for example:

![308f50d2b9f7f1aa5d3bff619fd7704883c2976e_2_1326x1000](https://user-images.githubusercontent.com/22067021/55899715-b5791c00-5b82-11e9-916f-88f87b423fee.jpeg)

**Comment by banesullivan** [comment]
I don't think it's possible to do this without some seriously hacky solutions

Usage of the clip filter on `MultiBlock` datasets via #270 will resolve this

**Comment by T4mmi** [comment]
Beware that in a `MultiBlock` with no scalars this will crash !  
due to https://github.com/pyvista/pyvista/blob/1d27d8f331c75929a89e444770c21d81f031a25b/pyvista/plotting/widgets.py#L762
