### ISSUE TITLE
fix cell_data_to_point_data example

### ISSUE THREAD

**Issue by akaszynski** [pyvista/pyvista#1625]
See: 
https://dev.pyvista.org/api/core/_autosummary/pyvista.DataSetFilters.cell_data_to_point_data.html#pyvista.DataSetFilters.cell_data_to_point_data

**Comment by RobPasMue** [comment]
Hi @akaszynski! Not sure what the problem was in the past, but the docs look good to me now. Could you double check just in case? If not, let me know, I'll handle the change :)

**Comment by akaszynski** [comment]
Still an issue. Seems the scalars aren’t showing up in the plots.

**Comment by RobPasMue** [comment]
Great, now I know the problem. Thanks @akaszynski for letting me know. Starting it!
