### ISSUE TITLE
Screenshot silently fails with panel & ipygany backends

### ISSUE THREAD

**Issue by eudoxos** [pyvista/pyvista#1635]
This screenshot MWE is [from the docs](https://dev.pyvista.org/examples/02-plot/screenshot.html#saving-screenshots). 
```py
import pyvista as pv
from pyvista import examples
import matplotlib.pyplot as plt
filename=examples.planefile
mesh=pv.read(filename)
plotter=pv.Plotter(off_screen=True)
plotter.add_mesh(mesh, color="orange")
plotter.show(screenshot='airplane.png')
plt.imshow(plotter.image)
plt.show()
```
This works depending on what is the default jupyter backend. With `pv.set_jupyter_backend('panel')` (or `show(...,jupyter_backend='panel')`) or `ipygany`, there will be no screenshot saved, and no error message from `show`.

Tthere will only be error later when getting `plotter.image`: "This plotter has not yet been setup and rendered with `show()`. Consider setting `off_screen=True` for off screen rendering."

I expect `show(...)` to report an error rather than failing silently, or (even better) select suitable backend by itself.

**To Reproduce**

Run the above with `plotter.show(screenshot='airplane.png',jupyter_backed='panel')` or call `pv.set_jupyter_backend('panel')` before `plotter.show`. The correct behavior can be obtained by writing `pv.show(...,jupyter_backend='none')`.

-----

**System Information:**
 Please run the following code wherever you are experiencing the bug and paste the output below. This report helps us track down bugs and it is critical to addressing your bug:

```py
# Get system info
import pyvista as pv
print(pv.Report())
```

```txt
--------------------------------------------------------------------------------
  Date: Sat Sep 04 09:28:28 2021 CEST

                OS : Linux
            CPU(s) : 8
           Machine : x86_64
      Architecture : 64bit
               RAM : 30.4 GiB
       Environment : Jupyter
        GPU Vendor : X.Org
      GPU Renderer : AMD Ryzen Embedded V1605B with Radeon Vega Gfx (RAVEN, DRM 3.40.0, 5.11.0-27-generic, LLVM 9.0.1)
       GPU Version : 4.6 (Core Profile) Mesa 20.0.4

  Python 3.8.10 (default, Jun  2 2021, 10:49:15)  [GCC 9.4.0]

           pyvista : 0.31.3
               vtk : 9.0.3
             numpy : 1.17.4
           imageio : 2.9.0
           appdirs : 1.4.3
            scooby : 0.5.7
            meshio : 4.4.6
        matplotlib : 3.1.2
             PyQt5 : 5.14.1
           IPython : 7.24.1
          colorcet : 1.0.0
        ipyvtklink : 0.2.1
             scipy : 1.3.3
              tqdm : 4.61.0
--------------------------------------------------------------------------------
```

**Comment by akaszynski** [comment]
With 0.32.0, can you try the new pythreejs backend and see if that works instead?  See:

https://docs.pyvista.org/user-guide/jupyter/pythreejs.html

**Comment by tmatsuzawa** [comment]
Any progress on this matter? 
pyvista 0.32.1 still has the same issue with the Jupyter environment.
