### ISSUE TITLE
BUG: 'PolyData' object has no attribute 'reconstruct_surface'

### ISSUE THREAD

**Issue by adam-grant-hendry** [pyvista/pyvista#1653]
## Bug

When running this code

https://dev.pyvista.org/examples/01-filter/surface_reconstruction.html#surface-reconstruction-example

I get the error

`'PolyData' object has no attribute 'reconstruct_surface'`

## System

Windows 10 Enterprise, x64, Build 1909
Python 3.8.10
pyvista 0.31.3

**Comment by akaszynski** [comment]
Dev docs are for the upcoming release and the content in the development (`main`) branch of the repo.  If you follow our dev docs, please clone and install using a [development install](https://docs.pyvista.org/getting-started/installation.html#source-developers).

**Comment by akaszynski** [comment]
Just released [`pyvista==0.32.0`](https://pypi.org/project/pyvista/), which has `reconstruct_surface`.
