### ISSUE TITLE
Plotter.show() requires camera position to be returned if user wants the last image.

### ISSUE THREAD

**Issue by dgriffiths3** [pyvista/pyvista#1665]
**Describe the bug, what's wrong, and what you expect:**

When running `pv.Plotter().show()` the parameter `return_img` only works if `return_cpos` is also `True`. 

It looks from the code more a 'feature' than a bug, as after asking if `return_img` or `screenshot` is `True`, the code then asks if `return_cpos` is `True`:

https://github.com/pyvista/pyvista/blob/8b27bab0edef82d681d8fa0f6d40a7544ece319f/pyvista/plotting/plotting.py#L4909

Maybe I don't know enough about the code base for why this might be needed, but in either way its very unintuitive as the image returned is just `None`. 

I would recommend either:

```py
if return_img or screenshot is True:
    if return_cpos:
        return self.camera_position, self.last_image
    else:
        return self.last_image
```

If this is just a bug. Or if it's a feature for some reason:

```py
if return_img or screenshot is True:
    if not return_cpos:
        # some user warning here they will get None with return_cpos=True
    else:
        return self.camera_position, self.last_image
```

-----

**To Reproduce**

Please include a code snippet to reproduce the bug in the block below:

```py

plot = pv.Plotter(window_size=(512, 512), off_screen=True)
plot.background_color=[1.,1.,1.]

plot.add_points(np.random.rand(100, 3), color=[0.9, 0.9, 0.9], render_points_as_spheres=True, point_size=2)

plot.view_xy()
img = plot.show(return_img=True)

```

**Comment by dgriffiths3** [comment]
It also seems `return_img` never actually does anything, only `screenshot=True` will result in an image.

This is the only reference I could see in the `.show()` function.

https://github.com/pyvista/pyvista/blob/8b27bab0edef82d681d8fa0f6d40a7544ece319f/pyvista/plotting/plotting.py#L4856

**Comment by akaszynski** [comment]
Yep, that's annoying.  We're going to have to patch this.

**Comment by banesullivan** [comment]
This is tested handled in `test_plot_return_img_without_cpos`
