### ISSUE TITLE
jupyter widget problem: pythreejs

### ISSUE THREAD

**Issue by bujack** [pyvista/pyvista#1698]
I try a simple example of pyvista in a jupyter notebook, but there is no rendering. Instead, I get the following error message in the terminal: [W 10:09:59.253 NotebookApp] 404 GET /static/ipygany.js?v=20210929100904 (::1) 1.600000ms referer=http://localhost:8833/notebooks/create-poly.ipynb

-----

```py
import numpy as np
import pyvista as pv

# mesh points
vertices = np.array([[0, 0, 0],
                     [1, 0, 0],
                     [1, 1, 0],
                     [0, 1, 0],
                     [0.5, 0.5, -1]])

# mesh faces
faces = np.hstack([[4, 0, 1, 2, 3],  # square
                   [3, 0, 1, 4],     # triangle
                   [3, 1, 2, 4]])    # triangle

surf = pv.PolyData(vertices, faces)

# plot each face with a different color
surf.plot(scalars=np.arange(3), cpos=[-1, 1, 0.5])
```

-----

**System Information:**
 Please run the following code wherever you are experiencing the bug and paste the output below. This report helps us track down bugs and it is critical to addressing your bug:

```
--------------------------------------------------------------------------------
  Date: Wed Sep 29 10:13:44 2021 MDT

                OS : Darwin
            CPU(s) : 16
           Machine : x86_64
      Architecture : 64bit
       Environment : Jupyter
        GPU Vendor : ATI Technologies Inc.
      GPU Renderer : AMD Radeon Pro 5500M OpenGL Engine
       GPU Version : 4.1 ATI-3.10.22

  Python 3.9.2 (default, Feb 19 2021, 17:09:53)  [Clang 12.0.0
  (clang-1200.0.32.29)]

           pyvista : 0.32.1
               vtk : 9.0.3
             numpy : 1.20.1
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.7
            meshio : 4.4.6
        matplotlib : 3.3.4
           IPython : 7.28.0
        ipyvtklink : 0.2.1
             scipy : 1.6.1
```

**Comment by banesullivan** [comment]
It looks like there is some error happening with that specific jupyter backend, `ipygany`. Perhaps you should try using the jupyter backend `ipyvtklink` or `pythreejs`. At the top of your notebook (perhaps after importing pyvista), add the following line to set a different default notebook plotting backend:

```py
import pyvista as pv
pv.set_jupyter_backend('ipyvtklink')
```

I chose `'ipyvtklink'` because your `pv.Report()` showed that you have it installed, and I personally work with this one the most. `'pythreejs'` is another great option for in-notebook rendering. There are other options that might better suit your needs listed here: https://docs.pyvista.org/user-guide/jupyter/index.html

**Comment by bujack** [comment]
Thank you so much for your help, Bane! 
ipyvtklink did not change anything, but pythreejs works :)
There is only one tiny problem remaining: The triangle become invisible if I try to look at them from the other side
<img width="557" alt="Screen Shot 2021-10-04 at 11 48 13 AM" src="https://user-images.githubusercontent.com/20593413/135899526-d3cf09fe-716c-4148-98ab-595e41962bba.png">
<img width="535" alt="Screen Shot 2021-10-04 at 11 48 20 AM" src="https://user-images.githubusercontent.com/20593413/135899539-d3acb124-6453-48f7-a5cc-10df69c835ac.png">
.

**Comment by akaszynski** [comment]
Hi @bujack,

The reason for this is we've disabled "double side plotting" within pythreejs.  I can enable this, but it's generally not advisable as it can cause plotting artifacts for complex meshes.  Probably what we need to add is options for `pythreejs`.

**Comment by bujack** [comment]
Thank you @akaszynski! That totally explains it :)
I was able to work around it by inserting the polygons with opposite orientation, too, but think it would be great if it were possible to enable them for many examples, e.g.
<img width="436" alt="Screen Shot 2021-10-04 at 11 46 32 AM" src="https://user-images.githubusercontent.com/20593413/135921627-7bafeace-3e7f-4b5a-a74f-39bac228c522.png">
<img width="780" alt="Screen Shot 2021-10-04 at 2 39 18 PM" src="https://user-images.githubusercontent.com/20593413/135921635-15eec736-d1f8-469e-8fd7-e6dbc827b0bd.png">

**Comment by akaszynski** [comment]
Interesting.  The examples are rendering normally on my end.  I'm going to have to look into this.

Thanks for pointing out the bug!

**Comment by bujack** [comment]
@akaszynski, sure thing :) 
by the way, opacity and plotting polydata that has only points and no triangles also seems buggy on my end using pythreejs.

**Comment by dstansby** [comment]
> The reason for this is we've disabled "double side plotting" within pythreejs. I can enable this, but it's generally not advisable as it can cause plotting artifacts for complex meshes. Probably what we need to add is options for `pythreejs`.

Is there a way to enable it from the user end? I've just spend a while getting quite confused about only one side of the mesh being rendered by `pythreejs`, when both sides are rendered in a 'normal' pyvista plot.

**Comment by banesullivan** [comment]
Closing due to staleness and would like to point users to our new `trame`-based notebooks rendering backend coming in version `0.38`
