### ISSUE TITLE
untrack_click_position issue

### ISSUE THREAD

**Issue by ghazalbangash** [pyvista/pyvista#1729]
I have been using self.plotter.track_click_position(self.picker, side='right') with a callback function self.picker which gives the mouse_position to be ,but after my flag is set to false and i want to untrack by using self.plotter.untrack_click_position() nothing happens and it still keeps tracking_pick_position.Can anyone please guide me?

**Comment by avithal** [comment]
i have the same problem

**Comment by ghazalbangash** [comment]
@avithal could you solve the problem?
