### ISSUE TITLE
Regression of "Gaussian Smoothing" example image

### ISSUE THREAD

**Issue by tkoyama010** [pyvista/pyvista#1741]
**Describe the bug, what's wrong, and what you expect:**

https://dev.pyvista.org/examples/01-filter/gaussian-smoothing.html#sphx-glr-examples-01-filter-gaussian-smoothing-py
![sphx_glr_gaussian-smoothing_002](https://user-images.githubusercontent.com/7513610/138388722-f10a9056-55a6-4be4-93b2-5769b0fe2de6.png)

https://docs.pyvista.org/examples/01-filter/gaussian-smoothing.html#sphx-glr-examples-01-filter-gaussian-smoothing-py
![sphx_glr_gaussian-smoothing_002](https://user-images.githubusercontent.com/7513610/138389050-b532131c-5f73-4384-b6dd-caf233f13706.png)

-----

**To Reproduce**

Please include a code snippet to reproduce the bug in the block below:

```py
# Insert code here

```

**Screenshots**

-----

**System Information:**
 Please run the following code wherever you are experiencing the bug and paste the output below. This report helps us track down bugs and it is critical to addressing your bug:

```py
# Get system info
import pyvista as pv
print(pv.Report())
```

```txt
# Paste system info here

```

**Comment by banesullivan** [comment]
This is a part of the broader opacity issues with recent VTK releases

**Comment by tkoyama010** [comment]
Now we have fixed figure. Closing.
https://dev.pyvista.org/examples/01-filter/gaussian-smoothing.html#sphx-glr-examples-01-filter-gaussian-smoothing-py
![sphx_glr_gaussian-smoothing_002](https://user-images.githubusercontent.com/7513610/143664353-33a510b6-9daf-4ce1-a859-855f7d546b23.png)
