### ISSUE TITLE
Contributing to `pyvista/vtk-data`

### ISSUE THREAD

**Issue by adam-grant-hendry** [pyvista/pyvista#1790]
### Discussed in https://github.com/pyvista/pyvista/discussions/1789

<div type='discussions-op-text'>

<sup>Originally posted by **adam-grant-hendry** November  7, 2021</sup>
If I want to create a pull request to add a dataset to `pyvista/vtk-data`, should I fork the repository? It contains lfs files and downloading counts against the maintainer's bandwidth.

Are there details on contributing to `vtk-data`? The `Contributing.md` only talks about licenses (i.e. don't add a data set for which there isn't a license).</div>

The above may be a good opportunity to elaborate in ``Contributing.md``

**Comment by banesullivan** [comment]
I'm going to remove the LFS files stored in that repo and place them somewhere else (they're geo example files I put in there for another PyVista-based project). Unfortunately, the only way I've been able to find how to do this is to delete and recreate the whole repository removing history. I'm perfectly content doing this as the history of that repo really isn't important, though it may mean that our examples will go down for a bit as the files are re-uploaded and github's mirrors update.

@pyvista/developers, does anyone have a problem with me moving forward with this in the next few days?

**Comment by adeak** [comment]
I'm not personally affected, so just out of curiosity: why do the files need removing?

**Comment by banesullivan** [comment]
> why do the files need removing?

Honestly, I don't know... just when I was looking up how to remove git-lfs files from a repo, I stumbled up this: https://stackoverflow.com/questions/34579211/how-to-delete-a-file-tracked-by-git-lfs-and-release-the-storage-quota

There are a lot of mixed answers in there. First, I'm going to try to remove the files, uninstall LFS from the repo, and clean the history to see if this works. But there's some discussion about GitHub not actually purging the files and any clones will still count against the users LFS quota.

At the end of the day, it may just be easier to delete the repo and re-upload all non git-lfs files rather than spending an hour or so to get it right to preserve some history that really does not matter

**Comment by adeak** [comment]
So I take it the answer is "because they take up git LFS quota" :laughing:

**Comment by adam-grant-hendry** [comment]
As long as it doesn't affect the maintainer, I'm fine with any approach 🙂.  I have a PR to add a DICOM stack dataset thats around 65 MB, if I remember correctly, to implement the VTKDicomReader in pyvista

**Comment by banesullivan** [comment]
We already have a small dicom dataset that we use for testing: https://github.com/pyvista/vtk-data/blob/master/Data/DICOM_KNEE.dcm and https://github.com/pyvista/vtk-data/tree/master/Data/DICOMDirectory

its the `examples.download_knee()` data

Further the `vtkDICOMImageReader` is implemented in PyVista: 

https://github.com/pyvista/pyvista/blob/9d05d4d0357fbf503975c1c2bcebab7b35455d3b/pyvista/utilities/fileio.py#L33

**Comment by MatthewFlamm** [comment]
The DICOMDirectory example would probably suffice for testing. This data set would provide a more interesting example.

We have added Reader classes which allow for more control over reading data files.    This request was about adding more control.  See https://github.com/pyvista/pyvista/blob/main/pyvista/utilities/reader.py.

**Comment by banesullivan** [comment]
> This request was about adding more control

Ah, forgive me - drive by commenting here to be honest. I just wanted to make sure you all were aware we had and use that data since there was talk in https://github.com/pyvista/pyvista-support/issues/500#issuecomment-921103069 about adding a reader and a dataset

**Comment by MatthewFlamm** [comment]
For this PR, I think it is about whether this additional data set would provide some advantage for testing or example usage.  I'm not a DICOM user, so I'm not sure if the single file in the existing DICOMDirectory is sufficient.

**Comment by banesullivan** [comment]
> I'm not a DICOM user, so I'm not sure if the single file in the existing DICOMDirectory is sufficient.

Me either, I've assumed it is sufficient though. @adam-grant-hendry, would this new dataset improve our examples/tests to make sure we sufficiently cover what you hope to do?

**Comment by adam-grant-hendry** [comment]
> would this new dataset improve our examples/tests to make sure we sufficiently cover what you hope to do?

@banesullivan Yes, this will. In addition to porting over the `VTKDICOMReader` and add the ability to read a directory of files, there are two things my update to `add_volume()` does:

1. Fixes a memory leak that causes RAM to explode and `pyvista` to crash, and
2. Loads a volume at a speed comparable to `paraview`

I can run a memory profile before and after the commit that implements the change in the PR to show the improvement, both in memory usage and load time.

**Comment by adam-grant-hendry** [comment]
However, ignoring the multi-file reader, I could probably show the memory and time improvements with the knee discomfort example

**Comment by akaszynski** [comment]
Can this be closed?

**Comment by adam-grant-hendry** [comment]
> Can this be closed?

I think so, yes.
