### ISSUE TITLE
BugFix: Contributing Requires Updates

### ISSUE THREAD

**Issue by adam-grant-hendry** [pyvista/pyvista#1791]
For Windows,

1. `GDAL` and `Fiona` must be installed from the [Christop Gohlke binaries](https://www.lfd.uci.edu/~gohlke/pythonlibs/)
2. In `requirements_test.txt`, you must include `appdirs`, `scooby`, `vtk`, and `meshio`, unless it is understood that the user first performs an editable install (```py -m pip install -e .```), which would be worth clarifying in the `Contributing to pyvista through GitHub` section

**Comment by banesullivan** [comment]
> GDAL and Fiona must be installed from the Christop Gohlke binaries

These shouldn't be needed for PyVista???

**Comment by adam-grant-hendry** [comment]
@banesullivan It's a dependency of one or more of the libraries listed in `requirements_text.txt` or `requirements_static.txt`

**Comment by banesullivan** [comment]
I'm not seeing this. Can you please specify what is requiring GDAL? This is news to me

**Comment by banesullivan** [comment]
If an example is pulling in GDAL then we need to take that out or mark it as expected to fail

**Comment by banesullivan** [comment]
Ahhhh I see it is this example pulling in `osmnx`

https://docs.pyvista.org/examples/99-advanced/osmnx-example.html#plot-open-street-map-data

@pyvista/developers, this needs to be optional or placed somewhere else

**Comment by banesullivan** [comment]
I believe #1867 resolved this - if you still think there are unneeded, heavy dependencies for development contributions,  let us know!
