### ISSUE TITLE
vtkinterface.readthedocs pops up in google searches for vtki but is empty

### ISSUE THREAD

**Issue by mmagnuski** [pyvista/pyvista#183]
If [this page](https://vtkinterface.readthedocs.io/) is under your control it would be good to redirect to http://docs.vtki.org/

**Comment by banesullivan** [comment]
Yep, we recently (last week) had to switch over to github pages because they could handle making the fancy new [examples gallery](http://docs.vtki.org/examples/index.html). 

I deleted the project on ReadtheDocs, let me see if I can setup forwarding...

**Comment by banesullivan** [comment]
Done!

**Comment by banesullivan** [comment]
Note that I set up a new project under ReadtheDocs that has a dummy page that refreshes and sends the viewer to http://docs.vtki.org

This is definitely a temporary fix - how can we tell readthedocs to set up a redirect for that whole domain?

**Comment by mmagnuski** [comment]
Does this help:
https://docs.readthedocs.io/en/stable/user-defined-redirects.html
