### ISSUE TITLE
NotAllTrianglesError

### ISSUE THREAD

**Issue by antonino-tocco** [pyvista/pyvista#1839]
Hi, I tried to make a boolean union on multiple spheres but a NotAllTrianglesError raised.

**To Reproduce**
```py
    for index, row in df.iterrows():
        balls.append(pv.Sphere(row['r'], ([row['x'], row['y'], row['z']]), theta_resolution=30, phi_resolution=30).triangulate(),)

    ic(f'Start merge spheres')
    u = reduce(lambda x, y: x.boolean_union(y), balls[1:], balls[0])
```

**System Information:**
--------------------------------------------------------------------------------
  Date: Mon Nov 22 17:08:55 2021 CET

                OS : Linux
            CPU(s) : 16
           Machine : x86_64
      Architecture : 64bit
       Environment : Python
        GPU Vendor : NVIDIA Corporation
      GPU Renderer : NVIDIA GeForce RTX 2080 Ti/PCIe/SSE2
       GPU Version : 4.5.0 NVIDIA 470.82.00

  Python 3.8.5 (default, Sep  4 2020, 07:30:14)  [GCC 7.3.0]

           pyvista : 0.32.0
               vtk : 9.1.0
             numpy : 1.21.3
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.7
            meshio : 4.4.6
        matplotlib : 3.3.1
             PyQt5 : 5.9.2
             scipy : 1.4.1
              tqdm : 4.46.1

  Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904
  for Intel(R) 64 architecture applications
--------------------------------------------------------------------------------

**Comment by whophil** [comment]
Perhaps the output of each reduction also needs to be triangulated?  `x.boolean_union(y).triangulate()`?

**Comment by akaszynski** [comment]
Stale issue. Closing...

If this is still an issue and you can post a minimum working example, please reopen.
