### ISSUE TITLE
obj.cell_arrays.pop(k) fail to get array

### ISSUE THREAD

**Issue by bruno-imdex** [pyvista/pyvista#1840]
When using `arrays.pop`. This line is sometimes returning `None`. For me, when the array in question is a string.

https://github.com/pyvista/pyvista/blob/5150b062cf835c6c6a44f6aefa4d53a1ad832ba3/pyvista/core/datasetattributes.py#L901

**BUT**, I see that this issue was already been handled on `arrays.get_array`.

So, in `.pop`, can we replace:
```python
vtk_arr = self.GetArray(key)
```
with
```
vtk_arr = self.get_array(key)
```
?

**Comment by tkoyama010** [comment]
Thank you for pointing this out !
