### ISSUE TITLE
Support for vtkSuperquadric

### ISSUE THREAD

**Issue by janniklasrose** [pyvista/pyvista#1841]
**Describe what feature you would like added.**

It would be great to get support for [vtkSuperquadric](https://vtk.org/doc/nightly/html/classvtkSuperquadric.html) directly in pyvista.

I would like to be able to apply this directly to a dataset of tensors (to visualise them by scaling the superquadrics to the tensor eigenvalues, just like Paraview allows me to do), but also to create a `vtkSuperquadricSource` e.g. as a quick demo - I assume this will use the same underlying representation.

Right now I'm using this with good results:

```python
def make_superquadric(
    # shape
    xscale: float,
    yscale: float,
    zscale: float,
    /, *,
    size: float = None,  # isotropic size
    # resolution
    phi: int = None,    # number of points in the latitude direction
    theta: int = None,  # number of points in the longitude direction
    # optional toroid
    toroidal: bool = False,  # use toroidal shape instead of closed shape
    thickness: float = None,  # thickness of ring in case of toroidal
):

    # create
    superquadric = _vtk.vtkSuperquadricSource()

    # shape
    superquadric.SetScale(xscale, yscale, zscale)
    if size is not None:
        superquadric.SetSize(size)

    # resolution
    if phi is not None:
        superquadric.SetPhiRoundness(phi)
    if theta is not None:
        superquadric.SetThetaRoundness(theta)

    # toroidal
    superquadric.SetToroidal(toroidal)
    if toroidal:
        if thickness is not None:
            superquadric.SetThickness(thickness)

    # plotting
    superquadric.Update()
    surf = pyvista.wrap(superquadric.GetOutput())
    surf.plot()
```

**Comment by janniklasrose** [comment]
I'm happy to attemt a PR with some guidance, particularly regarding where to add this snippet above (with some improvements). The only thing I've found that is similar is [`ParametricSupertoroid`](https://github.com/pyvista/pyvista/blob/adfc718dd1097d5b1feb8269986efc3e954e7d96/pyvista/utilities/parametric_objects.py#L1046), but that uses `surface_from_para` (which does not seem to work with a `vtkSuperquadric` object).

I would also like to add `PhiResolution` and `ThetaResolution`, as available in [paraview.simple.Superquadric](https://kitware.github.io/paraview-docs/latest/python/paraview.simple.Superquadric.html)

**Comment by MatthewFlamm** [comment]
This sounds like a great addition!

This looks similar to the functions in the module below.  For some reason these are capitalized like a class, so I'd recommend just following the standard in that module. https://github.com/pyvista/pyvista/blob/main/pyvista/utilities/geometric_objects.py
