### ISSUE TITLE
Changing color of points in User Guide

### ISSUE THREAD

**Issue by tkoyama010** [pyvista/pyvista#1849]
### Discussed in https://github.com/pyvista/pyvista/discussions/1848

<div type='discussions-op-text'>

<sup>Originally posted by **tkoyama010** November 24, 2021</sup>
We cannot see the points of figure in [Using Python Lists or Tuples](https://dev.pyvista.org/user-guide/data_model.html#using-python-lists-or-tuples). It is because the color of point and background is same. It is better to change the color of point to red.
![data_model-1_00_00](https://user-images.githubusercontent.com/7513610/143205644-204442b1-8c87-4020-aa89-9f04960637fc.png)
</div>

**Comment by Carlosbogo** [comment]
Hi, I would like to work on this. Is there anyone doing it already?

**Comment by tkoyama010** [comment]
@Carlosbogo Not yet. Please solve this if you want. Welcome to contribution!

**Comment by Carlosbogo** [comment]
Great. Sorry but it's the first time I work in this repository. Where can I find the code you mention?

**Comment by MatthewFlamm** [comment]
I think it is here https://github.com/pyvista/pyvista/blob/main/doc/user-guide/data_model.rst#using-python-lists-or-tuples
