### ISSUE TITLE
running PyVista in sphinx examples causes segfault on a clean docs build

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#185]
When building the docs, a segfault occurs if its a clean build:

```bash
cd ./docs/
rm -r _build
rm -r examples
make html
```
note that a segfault occured. Then if you build again, no segfualt occurs

```
make html
```

This is an issue for `vtki` and other projects running `vtki` code in their docs/examples.

Note that in our `.travis.yml`, we build the docs twice to avoid this issue.

I have a feeling it has to do with some sort of object cleanup not happening - noticed this after implementing the `sphinx_gallery` scraper

**Comment by banesullivan** [comment]
This is still happening on Travis but not locally for me

**Comment by GuillaumeFavelier** [comment]
I think I reproduced this on [mne-python](https://github.com/mne-tools/mne-python/pull/6551) with my third test, I got a [segfault](https://circleci.com/gh/mne-tools/mne-python/14337?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link).

**Comment by banesullivan** [comment]
@GuillaumeFavelier, that segfault looks different than what I'm experiencing and likely has something to do with the code being run as it segfaults during execution rather than on closing/cleanup.

**Comment by banesullivan** [comment]
I think this segfault had to do with the interactive scalar bar widget cleanup found in #301 and fixed in a252c0d42d859536cc09e3c3f94e212b92d5ade0. Will test...

**Comment by banesullivan** [comment]
Nope - still experiencing this on Travis but not locally

**Comment by MuellerSeb** [comment]
I got this problem on read-the-docs and sphinx-gallery following https://docs.pyvista.org/getting-started/installation.html#running-with-sphinx-gallery.

Do I need to set anything else?

**Comment by akaszynski** [comment]
> Do I need to set anything else?

If you're running VTK 9.0 on Linux, this will occur as there's a bug with VTK not closing down the windows/figures even though they're in the background.

**Comment by MuellerSeb** [comment]
I also tested vtk 8.2 and got the same error on rendering.

**Comment by tkoyama010** [comment]
I think we should use vtk==8.1.2.
https://github.com/pyvista/pyvista/blob/94c0053703b8d584eadb6990dff96fd77b639e27/requirements_docs.txt#L18

**Comment by akaszynski** [comment]
@MuellerSeb, does this occur in 8.1.2?

**Comment by MuellerSeb** [comment]
@akaszynski Sorry, I meant `8.1.2`. Yepp, also not working on readthedocs.

**Comment by akaszynski** [comment]
Ok.  I'll look into this.  Thanks for pointing this out!

**Comment by tkoyama010** [comment]
FYI pyvista Japanese pages are working on readthedocs and does not occur this error.
https://github.com/tkoyama010/pyvista-doc-translations
https://pyvista-doc-ja.readthedocs.io/ja/latest/?badge=latest

**Comment by MuellerSeb** [comment]
But there the sphinx_gallery is turned off and the images are pre-generated AFAICT. Or did I miss sth?
PyVista works for everything except rendering on readthedocs.

**Comment by tkoyama010** [comment]
I apologize for the lack of explanation. This is a way if the problem does not solve. I use GitHubActions to render PyVista and use it to generate documentation. The best way is of course run with only readthedocs as you say.

**Comment by akaszynski** [comment]
Closing this as this is a VTK 9.0 issue.  See #1180
