### ISSUE TITLE
Document that the threshold filter is a cell-wise operation

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#1856]
I've seen this come up in the discussions a few times. We need to document that the threshold filter is a CELL-wise operation.

Ref https://github.com/pyvista/pyvista/discussions/1815#discussioncomment-1703827 and https://github.com/pyvista/pyvista/discussions/1758#discussioncomment-1671816

**Comment by RichardScottOZ** [comment]
Is there a simple 'make this ' these are cells, these are points example with pictures this could link to?

**Comment by banesullivan** [comment]
This guide goes into the differences of Point and Cell data a bit: https://docs.pyvista.org/user-guide/data_model.html

**Comment by banesullivan** [comment]
This was added as a warning in the docstring somewhere along the way
<img width="713" alt="Screen Shot 2022-12-22 at 3 35 46 PM" src="https://user-images.githubusercontent.com/22067021/209237126-f444a7bd-49c1-425f-b98f-5b4e6949e0da.png">
