### ISSUE TITLE
Remove the pin of the requirements_style.txt

### ISSUE THREAD

**Issue by tkoyama010** [pyvista/pyvista#1868]
We can remove the pin of the requirements_style.txt
https://github.com/pyvista/pyvista/blob/14e009a0a411720351d0e8e6a1388d1fc393b751/requirements_style.txt#L1-L2

_Originally posted by @banesullivan in https://github.com/pyvista/pyvista/pull/1865#discussion_r757722116_

**Comment by banesullivan** [comment]
My PR did remove that pin 😉
