### ISSUE TITLE
Store python lists/dictionaries in PolyData

### ISSUE THREAD

**Issue by supersubscript** [pyvista/pyvista#187]
I constantly find myself in situations where I want to store nested lists in my PolyData objects. An example would be when calculating point neighbours (which btw I think would be a nice feature to have as well), where I run into problems because the number of neighbours vary between points. 

While it wouldn't be a functionality (afaik) already existing in VTK, I think it would be a nice feature to have the option of storing objects of arbitrary types within the PolyData class in one way or another. At the moment this option doesn't seem to exist.

Thoughts?

**Comment by banesullivan** [comment]
This is an interesting idea - thanks for proposing it, @supersubscript 

Could you perhaps share an example like what you described? That way I can think about how this feature might fit in with what VTK currently supports it if we’ll need additional features on top of the VTK object like what I implemented for textures initially in #61

**Comment by supersubscript** [comment]
My neighbourhood example is the following:

```python
def get_connected_vertices(mesh, index, include_self=True):

    connected_vertices = []
    if include_self:
        connected_vertices.append(index)

    cell_id_list = vtk.vtkIdList()
    mesh.GetPointCells(index, cell_id_list)

    # Loop through each cell using the seed point
    for ii in range(cell_id_list.GetNumberOfIds()):
        cell = mesh.GetCell(cell_id_list.GetId(ii))

        # Loop through the edges of the point and add all points on these.
        for jj in range(cell.GetNumberOfEdges()):
            point_id_list = cell.GetEdge(jj).GetPointIds()

            # add the point which isn't the seed
            to_add = point_id_list.GetId(1) if point_id_list.GetId(0) == index else point_id_list.GetId(0)
            connected_vertices.append(to_add)

    connected_vertices = np.unique(connected_vertices)

    return connected_vertices

def get_connected_vertices_all(mesh, include_self=True):

    connectome = [[]] * mesh.n_points
    for ii in range(mesh.n_points):
        connectome[ii] = get_connected_vertices(mesh, ii, include_self)

    connectome = np.array(connectome)

    return connectome

connectome = get_connected_vertices_all(<some mesh, _mesh_>)
```

And here I would ideally want to do something like
```
mesh['neighbourhood'] = connectome
```
but fail with the following error:

```python
Traceback (most recent call last):

  File "<ipython-input-244-bc9c328934f9>", line 1, in <module>
    mesh['neighbourhood'] = connectome

  File "/home/henrik/projects/vtki/vtki/common.py", line 729, in __setitem__
    self.point_arrays[name] = scalars

  File "/home/henrik/projects/vtki/vtki/common.py", line 916, in __setitem__
    self.adder(val, key, deep=False)

  File "/home/henrik/projects/vtki/vtki/common.py", line 953, in adder
    self.data._add_point_scalar(scalars, name, set_active=False, deep=deep)

  File "/home/henrik/projects/vtki/vtki/common.py", line 367, in _add_point_scalar
    vtkarr = numpy_to_vtk(scalars, deep=deep)

  File "/home/henrik/.local/anaconda2/envs/surface/lib/python3.7/site-packages/vtk/util/numpy_support.py", line 146, in numpy_to_vtk
    vtk_typecode = get_vtk_array_type(z.dtype)

  File "/home/henrik/.local/anaconda2/envs/surface/lib/python3.7/site-packages/vtk/util/numpy_support.py", line 70, in get_vtk_array_type
    'Could not find a suitable VTK type for %s' % (str(numpy_array_type)))

TypeError: Could not find a suitable VTK type for object
```

I don't reckon VTK has a type compatible with np.object arrays, but regardless I think it would be nice to have the option of affiliating custom objects with polydata objects. Maybe with a parameter dictionary such that you could call (in my case) `mesh.data[''neighbourhood"]` for retrieval, or similar? Perhaps the texture attribute would be best suited in such a place, for consistency.

**Comment by banesullivan** [comment]
First, this is a really cool example - thanks for sharing @supersubscript!

Considering that your data array in this example has a length the same as the point's array it would be fairly straight forward to keep track of this data on the `vtki.Common` class. I propose adding an `.additional_data` dictionary property that only enforces that the first axis of the data array/list has the same number of elements as the number of points or cells in the mesh. 

```py
mesh.additional_data['<name>'] = connectome
```

Then, behind the scenes, we could add an integer array called `'_<name>_indexer'` which will be in the point/cell data of the VTK object and on filtering, we can add a hook within `vtki.filters._get_output` to use that indexing array to update which data to keep in the filtered object so that data also gets filtered when running `vtki` objects through VTK algorithms.

Caveat - this data will only be available during runtime - using the `save()` function to save to a VTK file would not support this additional data... perhaps, we could add a custom serializer (a better variant of `pickle`) to serialize `vtki` objects to help users keep track of textures and additional data like this?

**Comment by supersubscript** [comment]
Since string arrays are now supported (#200), an option could potentially be to store those kinds of objects (as strings) in vtkStringArrays under the FeatureData tag, as that would make saving as normal possible. It would, however, require some sort of protocol for conversion back-and-forth between string representations of different objects when saving/loading, so I'm not sure how feasible such a solution would be in practice. 

Runtime access only would be sufficient for many purposes, I reckon, but it'd be a pity if there weren't a better solution somewhere, somehow...

**Comment by banesullivan** [comment]
>  an option could potentially be to store those kinds of objects (as strings) in vtkStringArrays under the FeatureData tag, as that would make saving as normal possible. It would, however, require some sort of protocol for conversion back-and-forth between string representations of different objects when saving/loading, so I'm not sure how feasible such a solution would be in practice.

Unfortunately, I don't think that approach is feasible. The new string array support is very heavy weight - the arrays are converted between numpy and VTK using a Python `for`-loop every time the array is accessed. See:

https://github.com/vtkiorg/vtki/blob/423eb1ba000e2f7f0197ae1f643bcce953933c74/vtki/utilities.py#L44-L65


This is unlike normal numerical arrays where we have a true interface/buffer to the VTK data array from NumPy. If you had a rather large list of lists stored in this fashion, accessing it would have a lot of overhead and lag to the user.


Currently, I'm looking into a way to implement this feature using the underlying VTK data structure but so far don't have any progress... I'm inclined to move forward with the `.additional_data` approach with runtime access only at this time...

Also, this discussion brings up #203

**Comment by banesullivan** [comment]
At this time, we can support field data arrays but cannot add support for general lists of data. This feature would stray away from the VTK backend, potentially confuse users, and require a lot of maintenance. I am going to close this issue and mark it for future consideration.
