### ISSUE TITLE
Should we have net positive code coverage diff requirement on PRs?

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#1906]
Should we implement a hard CI check that requires a net positive code coverage on the diff? This would help ensure we are writing decent tests but I could also see it being a bit of a nuisance

**Comment by MatthewFlamm** [comment]
I think it should be implemented, but ignored when it makes sense.  For example, a style-only change that touches several modules should not be required to have net positive code coverage, but new feature additions should.
