### ISSUE TITLE
matplotlib usage hampered if pyvista is used

### ISSUE THREAD

**Issue by fbeaudo** [pyvista/pyvista#1909]
I am wondering about the following [issue](https://github.com/pyvista/pyvista-support/issues/232) on the old forum.

This issue was never marked as resolved, and I am currently experiencing the problem and looking for a solution.

The only workaround I found is to always use matplotlib before pyvista in my scripts but this is not very nice and not always possible.

**Comment by banesullivan** [comment]
I'm going to follow up in the linked issue. We'll use that thread and transfer here or to discussions as needed
