### ISSUE TITLE
Setting camera distance has no effect when creating animation

### ISSUE THREAD

**Issue by dstansby** [pyvista/pyvista#1931]
**Describe the bug, what's wrong, and what you expect:**

Setting the plotter camera distance has no effect when creating an animation. In the code below the camera roll changes from frame to frame as expected, but the distance does not.

-----

**To Reproduce**

Please include a code snippet to reproduce the bug in the block below:

```py
import pyvista as pv

pl = pv.Plotter()
pl.add_mesh(pv.Box())

pl.open_movie('cube.mp4')
for i in range(1, 10):
    pl.camera.distance = i
    pl.camera.roll = i
    pl.write_frame()
```

**Screenshots**
https://user-images.githubusercontent.com/6197628/145033273-3783998a-9cb0-4aae-be53-d2af2cc7e6ed.mp4

-----

**System Information:**
 Please run the following code wherever you are experiencing the bug and paste the output below. This report helps us track down bugs and it is critical to addressing your bug:

```py
# Get system info
import pyvista as pv
print(pv.Report())
```

```txt
--------------------------------------------------------------------------------
  Date: Tue Dec 07 12:58:33 2021 GMT

                OS : Darwin
            CPU(s) : 4
           Machine : x86_64
      Architecture : 64bit
               RAM : 8.0 GiB
       Environment : Python
        GPU Vendor : Intel Inc.
      GPU Renderer : Intel Iris OpenGL Engine
       GPU Version : 4.1 INTEL-16.5.4

  Python 3.9.7 (default, Sep 16 2021, 08:50:36)  [Clang 10.0.0 ]

           pyvista : 0.32.1
               vtk : 9.0.3
             numpy : 1.21.2
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.7
            meshio : 4.4.6
        matplotlib : 3.6.0.dev957+gfbe3273691
             PyQt5 : 5.15.2
           IPython : 7.27.0
             scipy : 1.7.1
              tqdm : 4.62.3

  Intel(R) oneAPI Math Kernel Library Version 2021.3-Product Build 20210617
  for Intel(R) 64 architecture applications
--------------------------------------------------------------------------------

```

**Comment by banesullivan** [comment]
We should make sure that `write_frame()` is not calling `ResetCamera()` under the hood. To doubly check, if you add `pl.camera_set = True` does it change? For example:

```py
import pyvista as pv

pl = pv.Plotter()
pl.add_mesh(pv.Box())

pl.open_movie('cube.mp4')
pl.camera_set = True
for i in range(1, 10):
    pl.camera.distance = i
    pl.camera.roll = i
    pl.write_frame()
```

**Comment by dstansby** [comment]
Thanks for the quick reply! That moves the camera to be above the cube instead of at an angle, but setting the distance still has no effect.

**Comment by dstansby** [comment]
Ah, I realised I interpreted the camera distance incorrectly - I've opened https://github.com/pyvista/pyvista/issues/1931 to clarify this in the docs.
