### ISSUE TITLE
Binder env not working

### ISSUE THREAD

**Issue by giswqs** [pyvista/pyvista#1951]
It seems the pyvista binder env no longer works. It throws an error `Error displaying widget: model not found`

https://mybinder.org/v2/gh/pyvista/pyvista-examples/master
![image](https://user-images.githubusercontent.com/5016453/146591194-23e9a5dc-fde4-45c3-8527-4f102fb95378.png)

**Comment by banesullivan** [comment]
AH! I literally just fixed this a week or so ago!

**Comment by banesullivan** [comment]
This should be resolved now by https://github.com/pyvista/cookiecutter-pyvista-binder/issues/4 and https://github.com/pyvista/pyvista-examples/pull/2

using the new base docker image provided in https://github.com/pyvista/pyvista/pkgs/container/pyvista
