### ISSUE TITLE
Segfault upon importing pyvista because of scooby (Windows, mambaforge, Python 3.8.12)

### ISSUE THREAD

**Issue by Huite** [pyvista/pyvista#1961]
I started with a fresh mambaforge environment on windows with python 3.8 from: https://github.com/conda-forge/miniforge

I installed my usual dependencies, which include pyvista. Starting either Python or IPython and running

```Python
import pyvista
```

results in an immediate segfault. 

I've been running some checks, older versions also segfault for me: 0.32.1, 0.31.0, 0.30.0, 0.29.1.
Importing `vtk` is not an issue, so I figured I'd move through the pyvista modules on by one:

importing scooby in `pyvista.plotting.helpers` looks to be the culprit.
Installing an older version of scooby (0.5.7) solves it, and importing pyvista 0.32.1 doesn't segfault my Python.

Importing scooby 0.5.8, 0.5.9, and 0.5.10 all result in an immediate segfault. I'll raise an issue in the scooby repo now.

-----

**System Information:**

```txt
--------------------------------------------------------------------------------
  Date: Thu Dec 23 16:23:12 2021 W. Europe Standard Time

                OS : Windows
            CPU(s) : 8
           Machine : AMD64
      Architecture : 64bit
               RAM : 31.9 GiB
       Environment : Python
        GPU Vendor : Intel
      GPU Renderer : Intel(R) HD Graphics 630
       GPU Version : 4.5.0 - Build 23.20.16.5018

  Python 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:22:46)
  [MSC v.1916 64 bit (AMD64)]

           pyvista : 0.32.1
               vtk : 9.1.0
             numpy : 1.20.3
           imageio : 2.13.4
           appdirs : 1.4.4
            scooby : 0.5.7
            meshio : 4.4.6
        matplotlib : 3.5.1
             PyQt5 : 5.12.3
           IPython : 7.30.1
             scipy : 1.7.3
              tqdm : 4.62.3
--------------------------------------------------------------------------------
```

**Comment by banesullivan** [comment]
I'll get a patch in scooby for this asap
