### ISSUE TITLE
`UniformGrid` with negative spacing results in wrong subset when using `extract_subset`

### ISSUE THREAD

**Issue by Onandon11** [pyvista/pyvista#1967]
**Describe the bug, what's wrong, and what you expect:**

The error occurs when extracting a subset from a `UniformGrid` with a negative spacing. The subset the origin of the data is thereafter not at the same location as the parent dataset. See example below: 

-----

**To Reproduce**

Please include a code snippet to reproduce the bug in the block below:

```py
import numpy as np
import pyvista

grid = pyvista.UniformGrid()
grid.dimensions = (4, 4, 4)
grid.origin = (0, 0, 0)
grid.spacing = (1, 1, -1)
grid.point_data["values"] = np.zeros((4, 4, 4)).ravel()
print(grid.origin)

plotter= pyvista.Plotter()
plotter.add_mesh(grid, color='white')

subgrid = grid.extract_subset(
    (
        1,
        2,
        0,
        3,
        0,
        3
    )
)
print(subgrid.origin) # Should return (1.0, 0.0, 0.0) not (1.0, 0.0, -3.0)
plotter.add_mesh(subgrid, color='blue')
plotter.show()

```

**Screenshots**
![image](https://user-images.githubusercontent.com/47885206/147449984-691c353f-2bf0-4eee-a8b9-8a620ad22a4c.png)
-----

**System Information:**
 Please run the following code wherever you are experiencing the bug and paste the output below. This report helps us track down bugs and it is critical to addressing your bug:

```py
# Get system info
import pyvista as pv
print(pv.Report())
```

```txt

--------------------------------------------------------------------------------
  Date: Mon Dec 27 09:07:59 2021 W. Europe Standard Time

                OS : Windows
            CPU(s) : 8
           Machine : AMD64
      Architecture : 64bit
               RAM : 31.9 GiB
       Environment : Python
        GPU Vendor : NVIDIA Corporation
      GPU Renderer : Quadro M1000M/PCIe/SSE2
       GPU Version : 4.5.0 NVIDIA 441.66

  Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit
  (AMD64)]

           pyvista : 0.32.1
               vtk : 9.0.3
             numpy : 1.21.2
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.7
            meshio : 4.4.6
        matplotlib : 3.4.3
         pyvistaqt : 0.5.0
             PyQt5 : 5.15.4
           IPython : 7.27.0
             scipy : 1.7.1
--------------------------------------------------------------------------------


```

**Comment by banesullivan** [comment]
*drive-by comment, so take with a grain of salt*

A negative spacing (while being logical), doesn't feel appropriate to me and is likely not handled by the underlying VTK filter in this case. A google search of this shows all kinds of weird behavior:

https://www.google.com/search?q=vtkImageData+negative+spacing&rlz=1C5CHFA_enUS897US897&oq=vtkImageData+negative+spacing&aqs=chrome..69i57j0i512l5j69i64l2.4797j0j3&sourceid=chrome&ie=UTF-8

I'd recommend trying to use positive spacing if possible.

**Comment by banesullivan** [comment]
On second glance, I see your problem:

```py
>>> import pyvista
>>> grid = pyvista.UniformGrid()
>>> grid.dimensions = (4, 4, 4)
>>> grid.origin = (0, 0, 0)
>>> grid.spacing = (1, 1, -1)
>>> grid.bounds
[0.0, 3.0, 0.0, 3.0, -3.0, 0.0]
```

Z points would be `0 -1 -2 -3` in that order

With the ROI,

```py
roi = (1, 2,  # x
          0, 3, # y
          0, 3 # z 
)
```

the `(0, 3)` Z (K-index) bounds should grab the points `0 -1 -2` with the Z-origin being 0 like you expect.

-----

Since we are only wrapping the underlying `vtkExtractVOI` filter, I don't think there is much we can do besides throwing a warning about negative spacing when present...
https://github.com/pyvista/pyvista/blob/ebf4a82191973e003e809d5ae0d257809c824d21/pyvista/core/filters/uniform_grid.py#L102

-----

I think we'd need to raise an upstream issue in VTK about this or explore the `vtkExtractVOI` filter to see if there is a better way to handle negative spacings

**Comment by banesullivan** [comment]
```py
>>> subgrid = grid.extract_subset(
...     (
...         1,
...         2,
...         0,
...         3,
...         0,
...         3
...     )
... )
>>> subgrid.origin
[1.0, 0.0, -3.0]
>>> subgrid.bounds
[1.0, 2.0, 0.0, 3.0, -6.0, -3.0]
```

Okay those bounds are really wrong

**Comment by banesullivan** [comment]
And using a negative rate doesn't work

```py
>>> subgrid = grid.extract_subset((1,2,0,3,0,3), rate=(1,1,-1))
[1]    10947 segmentation fault  python
```

**Comment by Onandon11** [comment]
> A negative spacing (while being logical), doesn't feel appropriate to me and is likely not handled by the underlying VTK filter in this case.

I agree, our machine produces a negative voxel size for one of the dimensions, why I don't know but if it's possible I would like to keep as close to the machine it's output as possible. However I can life with positive spacing 😄 

But the unexpected behavior is not intentional I think so indeed maybe raise an error/warning.
