### ISSUE TITLE
ModuleNotFoundError: No module named typing_extension

### ISSUE THREAD

**Issue by GuillaumeFavelier** [pyvista/pyvista#1997]
In [`pyvistaqt`](https://github.com/pyvista/pyvistaqt/runs/4723305422?check_suite_focus=true), all the CIs installing `pyvista 0.32` fail with:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pyvista/__init__.py", line 14, in <module>
    from pyvista.core import *
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pyvista/core/__init__.py", line 3, in <module>
    from .dataset import DataSet, DataObject
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pyvista/core/dataset.py", line 7, in <module>
    from typing_extensions import Literal # for python versions <3.8
ModuleNotFoundError: No module named 'typing_extensions'
```

When the instructions are:

```
pip install pyvista==0.32
python -c "import pyvista; print(pyvista.Report())"
```

I also reproduce locally on a conda environment and `python 3.9`.

It's apparently related to the import of `typing_extensions` and I noticed that there is a test based on `version_info` on `main` (6f44c89b73151a70491be18cbba743516d615d0e). Is it possible to backport the fix to `0.32` as well?

**Comment by MatthewFlamm** [comment]
#1592 caused this bug and was included in 0.32 while the fixes in #1658 and #1663 came in 0.33.  This would be a good candidate for a backport since it is critical for those use cases and is relatively straightforward.  Although, IMO PyVista moves fast enough that users should probably upgrade to 0.33 anyway.

**Comment by akaszynski** [comment]
We can backport. That's why we have those `release/*` branches anyway.

Busy at the moment to open a PR until the weekend unless someone else can do it before then.

**Comment by GuillaumeFavelier** [comment]
How should I proceed if I want to port the fix myself, should I open a PR based on `release/0.32` ?

**Comment by GuillaumeFavelier** [comment]
Hold on, I think the issue has been fixed recently because the latest CIs on `pyvistaqt` are green.

And it was solved locally after I ran `pip install pyvista==0.32 --no-cache --force`

Thank you!
