### ISSUE TITLE
Slider with discrete steps

### ISSUE THREAD

**Issue by martingrossman** [pyvista/pyvista#1998]
Thank you for making pyvista! I'm finding it very useful. I just have a small suggestion.

I would like to be able to add sliders which values are changing  in disrcete steps.

**Comment by banesullivan** [comment]
As far as I am aware, this is a limit of `vtkSliderRepresentation2D` which we use in `add_slider_widget` and we do not have much control over the discretization or steps of the value range on that slider. 

I'm going to have to point you [upstream to VTK proper](https://gitlab.kitware.com/vtk/vtk/-/issues) as this would need to be a feature request for `vtkSliderRepresentation2D` unless I am missing something or there is a different slider class we could use.
