### ISSUE TITLE
customize orientation axes color

### ISSUE THREAD

**Issue by nschloe** [pyvista/pyvista#2009]
With
```python
p = pv.Plotter()
p.show_axes()
```
one can show orientation axes:

![screenshot](https://user-images.githubusercontent.com/181628/148642650-2b1a1dcd-84a3-4d81-bcf9-18be6d8582cf.png)

I'd love to see more customization in the colors here, e.g.,
```python
p.show_axes(color="black")
# or
p.show_axes(color=("red", "green", "blue"))
```
That could be used to switch to a lighter blue if the background is dark, for example.

Related: [ux.stackexchange.com, _Why are X, Y and Z axes represented by Red, Green, and Blue?_](https://ux.stackexchange.com/q/79561/94820)

**Comment by banesullivan** [comment]
These are configurable with `add_axes()`:

```py
import pyvista as pv

p = pv.Plotter(notebook=0)
p.add_mesh(pv.Sphere())
p.add_axes(x_color='pink', y_color='navy', z_color='tan', line_width=5)
p.show()
```

<img width="137" alt="Screen Shot 2022-01-08 at 11 26 45 AM" src="https://user-images.githubusercontent.com/22067021/148655429-63216352-ef9d-4613-807d-d8f8023c7403.png">


See https://docs.pyvista.org/api/plotting/_autosummary/pyvista.Plotter.add_axes.html

**Comment by banesullivan** [comment]
There is a huge list of named colors here: https://github.com/pyvista/pyvista/blob/main/pyvista/plotting/colors.py

HEX and RGB values should also work

**Comment by banesullivan** [comment]
I think `show_axes()` is a legacy method and users should use `add_axes()`. I forget the status of this, cc @pyvista/developers

**Comment by nschloe** [comment]
That works, thanks!
