### ISSUE TITLE
vtkmodules.vtkRenderingContextOpenGL2 import error - PyVista 0.33 ,VTK 9.0.1 on Windows

### ISSUE THREAD

**Issue by whophil** [pyvista/pyvista#2012]
I'm getting a import error on a closed-source project which relies on PyVista. It seems to be due to the latest 0.33 release.

I am using conda to manage dependencies. My environment is resolving VTK 9.0.1 due to a hard requirement by another package. 

It appears the tests are run against 9.1.0 ([link to test](https://dev.azure.com/pyvista/PyVista/_build/results?buildId=8097&view=logs&j=09f0a5bc-9cbc-582e-eae5-2a9f4ac9c7a3&t=be931629-0121-5dca-4480-00fc512905cb&l=96)), but the issue is not seen there.

For now, I can pin `pyvista < 0.33` in my project, but this is of course not ideal.

Not sure what the root cause is - perhaps something odd about the VTK 9.0.1 Windows package on conda-forge?

```
  ..\..\_test_env\lib\site-packages\pyvista\__init__.py:12: in <module>
12:40:55       from pyvista.plotting import *
12:40:55   ..\..\_test_env\lib\site-packages\pyvista\plotting\__init__.py:4: in <module>
12:40:55       from .charts import Chart2D, ChartMPL, ChartBox, ChartPie
12:40:55   ..\..\_test_env\lib\site-packages\pyvista\plotting\charts.py:13: in <module>
12:40:55       from pyvista import _vtk
12:40:55   ..\..\_test_env\lib\site-packages\pyvista\_vtk.py:369: in <module>
12:40:55       import vtkmodules.vtkRenderingContextOpenGL2  # Necessary for displaying charts, otherwise crashes on rendering
12:40:55   E   ModuleNotFoundError: No module named 'vtkmodules.vtkRenderingContextOpenGL2'
```

To reproduce - on Windows:
```
conda create -n pyvista_import_test -c conda-forge vtk=9.0.1 pyvista=0.33
conda activate pyvista_import_test
python -c "import pyvista"
```

**Comment by akaszynski** [comment]
Same issue occurs for `vtk==9.0.1` under Ubuntu 20.04.

**Comment by akaszynski** [comment]
@whophil, I'm calling this a critical bug, so I'm pushing `pyvista==0.33.1`. Please let me know if you encounter any further issues. I use `pyvista` in a closed source project as well.

**Comment by whophil** [comment]
Thanks @akaszynski ! I appreciate the super-fast response.
