### ISSUE TITLE
Docker image should have all depends for examples gallery

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#2022]
I'd like to use the `docker/Dockerfile` as the base image for the examples on MyBinder. To do so, it'd be good if that base image had all the dependencies for running the examples gallery pre-installed

For:
- https://github.com/pyvista/pyvista/issues/1951
- https://github.com/pyvista/cookiecutter-pyvista-binder/issues/4

Ref https://github.com/pyvista/pyvista-examples/pull/2

**Comment by akaszynski** [comment]
That's fine. Just will mean a large image.

**Comment by banesullivan** [comment]
Perhaps we leave the base image as minimal requirements to run PyVista in Jupyter and then have a 2nd image for the examples

**Comment by banesullivan** [comment]
I have placed a GitHub Actions Workflow in the cookie-cutter: https://github.com/pyvista/cookiecutter-pyvista-binder

This is used in https://github.com/pyvista/pyvista-examples to build the image with all of the examples included. The image is built for the `master` branch of that repo (latest release) and for the `develop` branch of that repo (corresponding to the `main` branch of PyVista)
