### ISSUE TITLE
Clipping a mesh, e.g. to a ball

### ISSUE THREAD

**Issue by stla** [pyvista/pyvista#2026]
Hello,

  I want to request a feature: the possibility to clip a mesh to a general region. Let me show you what I mean with an example.

  Here is the Togliatti (iso)surface clipped to a box:

```python
from math import sqrt
import numpy as np
import pyvista as pv

def f(x, y, z):
    return (
        64
        * (x - 1)
        * (
            x ** 4
            - 4 * x ** 3
            - 10 * x ** 2 * y ** 2
            - 4 * x ** 2
            + 16 * x
            - 20 * x * y ** 2
            + 5 * y ** 4
            + 16
            - 20 * y ** 2
        )
        - 5
        * sqrt(5 - sqrt(5))
        * (2 * z - sqrt(5 - sqrt(5)))
        * (4 * (x ** 2 + y ** 2 - z ** 2) + (1 + 3 * sqrt(5))) ** 2
    )

# generate data grid for computing the values
X, Y, Z = np.mgrid[(-5):5:200j, (-5):5:200j, (-4):4:200j]
# create a structured grid
grid = pv.StructuredGrid(X, Y, Z)

values = f(X, Y, Z)
grid.point_data["values"] = values.ravel(order="F")
# compute the isosurface f(x, y, z) = 0
isosurf = grid.contour(isosurfaces=[0])

mesh = isosurf.extract_geometry()
# surface clipped to the box:
mesh.plot(smooth_shading=True, color="hotpink")
```

![Togliatti_pyvista_box](https://user-images.githubusercontent.com/4466543/149403901-b736fea3-5fff-40b4-b74f-7b19409640f6.png)

It is not highly pretty. You will see later that it is prettier when clipped to a ball (in particular it would be desirable to get rid of the non-connected components at the top).

A way to clip the surface to a ball consists in using `remove_points`:

```python
# surface clipped to the ball of radius 4.8, with the help of `remove_points`:
lengths = np.linalg.norm(mesh.points, axis=1)
toremove = lengths >= 4.8
mesh2, idx = mesh.remove_points(toremove)
mesh2.plot(smooth_shading=True, color="hotpink")
```

![Togliatti_pyvista_ball](https://user-images.githubusercontent.com/4466543/149404304-3e23dc9f-7871-410e-9241-b708fa9c599c.png)

That's not too bad, but that's not perfect: the borders are not smooth.

In the case of a ball, we can achieve a clipped surface with smooth borders by resorting to spherical coordinates:

```python
from math import sqrt, pi
import numpy as np
import pyvista as pv

def f(ρ, θ, ϕ):
    x = ρ * np.cos(θ) * np.sin(ϕ)
    y = ρ * np.sin(θ) * np.sin(ϕ)
    z = ρ * np.cos(ϕ)
    return (
        64
        * (x - 1)
        * (
            x ** 4
            - 4 * x ** 3
            - 10 * x ** 2 * y ** 2
            - 4 * x ** 2
            + 16 * x
            - 20 * x * y ** 2
            + 5 * y ** 4
            + 16
            - 20 * y ** 2
        )
        - 5
        * sqrt(5 - sqrt(5))
        * (2 * z - sqrt(5 - sqrt(5)))
        * (4 * (x ** 2 + y ** 2 - z ** 2) + (1 + 3 * sqrt(5))) ** 2
    )

# generate data grid for computing the values
Rho, Theta, Phi = np.mgrid[0:4.8:200j, 0:pi:200j, 0:(2*pi):200j]
# create a structured grid
grid = pv.StructuredGrid(Rho, Theta, Phi)

values = f(Rho, Theta, Phi)
grid.point_data["values"] = values.ravel(order="F")
# compute the isosurface f(ρ, θ, ϕ) = 0
isosurf = grid.contour(isosurfaces=[0])
mesh = isosurf.extract_geometry()

# spherical to Cartesian:
def sph2cart(sph):
    ρ = sph[:, 0]
    θ = sph[:, 1]
    ϕ = sph[:, 2]
    return np.array([
        ρ * np.cos(θ) * np.sin(ϕ),
        ρ * np.sin(θ) * np.sin(ϕ),
        ρ * np.cos(ϕ)
    ])

mesh.points = np.transpose(sph2cart(mesh.points))
mesh.plot(smooth_shading=True, color="hotpink")
```

Now the borders are smooth:

![Togliatti_pyvista_spherical](https://user-images.githubusercontent.com/4466543/149404723-c27de4a7-d3cc-4aa1-b1bd-1607d3634ab5.png)

Well, the point I want to raise is that there's no way in **PyVista** to properly clip a mesh to a given bounding region, or at least I didn't find one. Is there such a feature available?

Such a feature is available in the R package **rgl**: [clipMesh3d](https://rdrr.io/rforge/rgl/man/clipMesh3d.html) (this package is a wrapper of OpenGL). It would be nice to have this feature in **PyVista**.

**Comment by akaszynski** [comment]
You can accomplish this by clipping by a scalar:

```py
pv.set_plot_theme('document')

# clip by scalar
mesh['dist'] = np.linalg.norm(mesh.points, axis=1)
clipped = mesh.clip_scalar('dist', value=4.8)
clipped.plot(smooth_shading=True, cmap='plasma')
```
![tmp](https://user-images.githubusercontent.com/11981631/149416636-3dd7007a-75d7-4549-9c80-5782ce241870.png)

---

As for clipping by region (e.g. [Boolean Operations](https://docs.pyvista.org/examples/01-filter/boolean-operations.html), it's not as robust as I'd like. I think clipping via scalars would be your best bet, and then simply performing several clips(for each dimension), or providing a mask as the `scalars`.

**Comment by stla** [comment]
Wonderful, thanks !

**Comment by stla** [comment]
Stupid of me, I forgot I opened this issue, and I recently asked the same question in "Discussions".

**Comment by stla** [comment]
Note that **rgl**, as shown in the blog post, allows to clip to any region, not only a ball.

**Comment by stla** [comment]
I'm triply stupid guys. One can do the same as **rgl**. It suffices to replace the Euclidean norm by a function defining the desired isosurface!

And here is a tennis ball:

```python
import pyvista as pv

# Enneper surface: f=0
def f(x, y, z):
    return ( 
        64*z**9 - 128*z**7 + 64*z**5 - 702*x**2*y**2*z**3 - 18*x**2*y**2*z 
        + 144*(y**2*z**6-x**2*z**6) + 162*(y**4*z**2-x**4*z**2) + 27*(y**6-x**6) 
        + 9*(x**4*z+y**4*z) + 48*(x**2*z**3+y**2*z**3) - 432*(x**2*z**5+y**2*z**5) 
        + 81*(x**4*y**2-x**2*y**4) + 240*(y**2*z**4-x**2*z**4) - 135*(x**4*z**3+y**4*z**3)
    )

sphere_mesh = pv.Sphere(theta_resolution=200, phi_resolution=200)
vertices = sphere_mesh.points

dists = f(vertices[:,0], vertices[:,1], vertices[:,2])

mesh1 = sphere_mesh.copy()
mesh2 = sphere_mesh.copy()

mesh1["dist"] = dists
mesh2["dist"] = -dists
clipped1 = mesh1.clip_scalar("dist", value=0)
clipped2 = mesh2.clip_scalar("dist", value=0)

pv.set_plot_theme('document')
pltr = pv.Plotter(window_size=[512, 512], off_screen=False)
pltr.add_mesh(clipped1, smooth_shading=True, color="yellow")
pltr.add_mesh(clipped2, smooth_shading=True, color="purple")
pltr.show()
```

![pyvtennisball](https://github.com/pyvista/pyvista/assets/4466543/cb48aea1-5654-45e1-a18d-c395e55cba2a)

**Comment by stla** [comment]
PS: it could be a nice example for the doc. 

Here is how it is described in the **rgl** doc:

## Clip mesh or RGL object to general region

### Description

Modifies a mesh3d object so that values of a function are bounded.

### Details 

These functions transform a mesh3d object or other RGL objects by removing parts where fn violates the bound.

____ 

And if you want you can cite [my blog](https://laustep.github.io/stlahblog/posts/TennisBall.html) ;-)

**Comment by stla** [comment]
How to extract the boundary edges of one of the two clipped meshes, in order to plot the seam line ? I've just found `extract_feature_edges` in the doc.

**Comment by stla** [comment]
I've found but the line is not very well rendered. Some discontinuities appear.

```python
pltr = pv.Plotter(window_size=[512, 512], off_screen=False)
pltr.add_mesh(clipped1, smooth_shading=True, color="yellow")
pltr.add_mesh(clipped2, smooth_shading=True, color="purple")
pltr.add_mesh(boundary, color="black", line_width=5)
pltr.show()
```

**Comment by stla** [comment]
I've tried to do a tubular spline from the `boundary.points` but that does something ugly because these points are not ordered along the boundary I think.

**Comment by stla** [comment]
Option `render_lines_as_tubes`, perfect !!

```python
pltr = pv.Plotter(window_size=[512, 512], off_screen=False)
pltr.add_mesh(clipped1, smooth_shading=True, color="yellow")
pltr.add_mesh(clipped2, smooth_shading=True, color="purple")
pltr.add_mesh(boundary, color="black", line_width=3, render_lines_as_tubes=True)
pltr.show()
```

![pyvtennisball](https://github.com/pyvista/pyvista/assets/4466543/fe6793a5-2fc8-4683-98a8-be5e67279701)
