### ISSUE TITLE
Custom PyVista file format

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#203]
#187 brings up a need for `vtki` to have its own data file format that saves all the additional metadata we add to the underlying VTK data objects such as textures.

### Description

To address saving all the meta/additional data that we add to VTK data structures in `vtki`, I've been thinking about creating a way to serialize the meta/additional data into HDF files and then output the VTK data writers we currently use to a binary string instead of to a file and then put that string in the HDF file - I think this would provide a really clean way for us to serialize `vtki` objects that have associated textures, lists of lists for #187, boolean arrays from #64, etc., in a way that can be shared with other's easily.

### Current Issue

Say you want to share a dataset with a colleague or save out for viewing/processing later. Let's also assume you have a texture with mesh. When associating a texture (or many textures) with a mesh, currently you would need to save the textures as image files (`.png`, `.jpeg`, `.tif`, etc.) and you would need to save the mesh (`mesh.save('my_awesome_mesh.vtk')`). Managing all these data files can become cumbersome and you wouldn't have access to meta info that was live on your object when saving it out like which texture was active, which arrays should be converted as booleans, etc.

Also, there's no clear way of saving a `vtkOpenGLTexture` to a file so you'd need the original image data that made that texture and save that out. Then when reloading the mesh, you'd have to step through the whole process of converting the image to a texture and associating it with the mesh - this can get cumbersome if you have several textures (I usually have a handful for different overlays of maps/imagery on topography surfaces).

### Proposed New Feature

Create a standard for serializing all metadata and textures/additional data to an HDF file (or similar format like netCDF that could provide a lighter weight dependency) then add a flag to the current VTK dataset writers to send the output to a string stream instead of a file stream and save that string to the HDF-like file as well. Then a user could call `mesh.save('mesh.vtki')` and we would save to our custom `vtki` format. 

There are plenty of other ways to serialize data that could avoid adding a new dependency to `vtki` like creating a directory, serializing meta info to JSON files and pickling objects like `vtkOpenGLTexture`s, then zipping that directory and adding our custom extension (this is what the `vtkjs` exporter from #57 currently does.

Any thoughts on other ways to serialize `vtki` objects would be greatly appreciated!

**Comment by banesullivan** [comment]
We need to think about how locales like mentioned in #226 could affect this - or if this would resolve those issues

**Comment by marcomusy** [comment]
@banesullivan 
That's a very interesting idea... i wonder why not using numpy i/o for this? Has anybody ever considered anything like this? (also addressing #187 )

```python
import numpy as np

a = np.arange(50000)
b = np.arange(20000)
c = np.random.rand(20000, 3) # normals

connectome = a

########################################### meshes
objs = dict()

mesh = dict()
objs['mymesh'] = mesh

mesh['type'] = 'mesh' # or unstructuredgrid...
mesh['vertices'] = a
mesh['cells'] = b
mesh['pointarrays'] = [a]
mesh['cellarrays'] = [b, c]
# some optional default appearance
mesh['color'] = 'gold' # default color
mesh['alpha'] = 1 # default alpha
mesh['texture'] = 'path_to/file.jpg' # or some numpy obj
mesh['wireframe'] = False
mesh['pointsize'] = 0
mesh['linewidth'] = 0
#other custom stuff
mesh['neighbourhood'] = connectome
mesh['quality'] = 'fine'
mesh['displacements'] = [c]
mesh['stress'] = []
#...

########################################### volumes
X, Y, Z = np.mgrid[:10, :10, :10]
scalar_field = ((X-5)**2 + (Y-5)**2 + (Z-5)**2)/225
print(scalar_field.shape)

vol = dict()
objs['myvolume'] = vol

vol['type'] = 'volume'
vol['spacing'] = [1.,1.,1.]
vol['scalars'] = [scalar_field]
# optional default appearance
vol['color'] = [0, 0.5, 1] # some default transfer fncs
vol['alpha'] = [0, 0.5, 0.7, 1]
vol['alphagrad'] = []


###########################################write
np.save('multidataset.npy', objs) 

###########################################load
v = np.load('multidataset.npy', allow_pickle=True)
#print(v)
# recreating the vtk objs becomes then trivial
```

**Comment by banesullivan** [comment]
FYI: https://github.com/pyvista/pyvista-support/issues/59

**Comment by banesullivan** [comment]
At this time, a custom file format would require too much maintenance. Marking for future consideration and closing
