### ISSUE TITLE
Implement vtkPointSet now that it is no longer abstract

### ISSUE THREAD

**Issue by andrea-bistacchi** [pyvista/pyvista#2061]
Hello, this issue is about point clouds, and particularly the dense and heavy point clouds obtained from LIDAR or photogrammetry, generally including several tens of millions of points.

After a [recent discussion](https://discourse.vtk.org/t/proposal-adding-a-vtkpointcloud-data-structure/3872), the class vtkPointSet is being used for these objects in VTK, even if it is still possible to use vtkPolyData. The advantage is that instances of vtkPointSet are lighter than those of vtkPolyData since they do not have any cell array, not even Vertex cells.

The question is: do you plan to do the same for [PyVista's point clouds](https://docs.pyvista.org/examples/00-load/create-point-cloud.html#sphx-glr-examples-00-load-create-point-cloud-py)? The problem is that at the moment there is no method to plot vtkPointSet objects in PyVista.

Thanks very much!

**Comment by banesullivan** [comment]
The reason PyVista does not currently handle`vtkPointSet` is because it has historically been an abstract class. Only recently was it made concrete. I suppose we should add an interface to `vtkPointSet` in PyVista for recent versions of VTK to handle this use case.

**Comment by andrea-bistacchi** [comment]
Very good! Let us know if we cam do something. For instance providing some test data could be very easy for us.

**Comment by banesullivan** [comment]
It would be very helpful if you could provide a large LiDAR example point cloud so that we can demonstrate the performance differences between vtkPolyData and vtkPointSet

**Comment by andrea-bistacchi** [comment]
A large LIDAR or photogrammetric point cloud could mean between several tens and hundreds immion points. I guess I cannot simply upload it on GitHub.

**Comment by banesullivan** [comment]
Or perhaps you are aware of some existing public data that meets these criteria?

**Comment by andrea-bistacchi** [comment]
Hi, please send me an email.
