### ISSUE TITLE
Jittery Scalar Bar in Saved GIF

### ISSUE THREAD

**Issue by camUrban** [pyvista/pyvista#2073]
**Bug Description:**

When creating a GIF and rendering it onscreen, the scalar bar's color map shows a smooth color gradient. However, after the animation is saved, the color gradient becomes blocky and jittery.

This appears to be an issue with either a new version of PyVista or a new version of one of its dependencies (potentially VTK). I believe this because I have previously saved GIF files that show a smooth scalar bar. However, I've been unsuccessful in pinpointing which version of PyVista or its dependencies causes the issues.

-----

**To Reproduce**

The following code snippet is copied verbatim from the [Create a GIF Movie page](https://docs.pyvista.org/examples/02-plot/gif.html) on the documentation. I also thought that the issue might be my graphics card drivers, but the example GIF displayed in the documentation also appears to suffer from the same problem.

```py
import numpy as np

import pyvista as pv

x = np.arange(-10, 10, 0.25)
y = np.arange(-10, 10, 0.25)
x, y = np.meshgrid(x, y)
r = np.sqrt(x ** 2 + y ** 2)
z = np.sin(r)

# Create and structured surface
grid = pv.StructuredGrid(x, y, z)

# Create a plotter object and set the scalars to the Z height
plotter = pv.Plotter(notebook=False, off_screen=True)
plotter.add_mesh(grid, scalars=z.ravel(), smooth_shading=True)

# Open a gif
plotter.open_gif("wave.gif")

pts = grid.points.copy()

# Update Z and write a frame for each updated position
nframe = 15
for phase in np.linspace(0, 2 * np.pi, nframe + 1)[:nframe]:
    z = np.sin(r + phase)
    pts[:, -1] = z.ravel()
    plotter.update_coordinates(pts, render=False)
    plotter.update_scalars(z.ravel(), render=False)

    # must update normals when smooth shading is enabled
    plotter.mesh.compute_normals(cell_normals=False, inplace=True)
    plotter.render()
    plotter.write_frame()

# Closes and finalizes movie
plotter.close()

```

**Screenshots**
***Jittery Scalar Bar***
PyVista==0.30.0, VTK==9.0.3:
![wave_pyvista_0 30 0_vtk_9 0 3](https://user-images.githubusercontent.com/26682141/151202020-666697a9-253f-4941-9af5-ef3606b4a2a5.gif)

PyVista==0.33.2, VTK==9.0.0:
![wave_pyvista_0 33 2_vtk_9 0 0](https://user-images.githubusercontent.com/26682141/151202118-1c4374cd-e430-4742-b138-bbe60dc46c65.gif)

PyVista==0.33.2, VTK==9.0.3:
![wave_pyvista_0 33 2_vtk_9 0 3](https://user-images.githubusercontent.com/26682141/151202192-b7ee26bc-3f64-49c6-bf67-5ef7f50243fc.gif)

PyVista==0.33.2, VTK==9.1.0:
![wave_pyvista_0 33 2_vtk_9 1 0](https://user-images.githubusercontent.com/26682141/151202257-06b00e7a-3e16-42ba-b25d-ef98f6e77ed6.gif)

***Smooth Scalar Bar***
Animation Made A Few Months Ago Using Different Code (PyVista and VTK Versions Unknown):
![Animate Output](https://user-images.githubusercontent.com/26682141/151202612-bd7f0c70-d75f-40c4-9f18-2e0075020b09.gif)

-----

**System Information:**

```txt
--------------------------------------------------------------------------------
  Date: Wed Jan 26 11:08:26 2022 Eastern Standard Time
                OS : Windows
            CPU(s) : 8
           Machine : AMD64
      Architecture : 64bit
       Environment : Python
       File system : unknown
        GPU Vendor : Intel
      GPU Renderer : Intel(R) HD Graphics P530
       GPU Version : 4.5.0 - Build 27.20.100.8681
  Python 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit
  (AMD64)]
           pyvista : 0.33.2
               vtk : 9.1.0
             numpy : 1.22.1
           imageio : 2.14.1
           appdirs : 1.4.4
            scooby : 0.5.11
        matplotlib : 3.5.1
--------------------------------------------------------------------------------
```

**Comment by banesullivan** [comment]
This is a known issue... I have been under the impression that this is a limitation of the colorspace in GIFs but that example you show from another software clearly debunks that.

See also: https://github.com/pyvista/pyvista/discussions/1742

**Comment by banesullivan** [comment]
> This appears to be an issue with either a new version of PyVista or a new version of one of its dependencies (potentially VTK). I believe this because I have previously saved GIF files that show a smooth scalar bar. However, I've been unsuccessful in pinpointing which version of PyVista or its dependencies causes the issues.

This has been an issue with PyVista for as long as I can remember

**Comment by banesullivan** [comment]
I'm wondering if the good example you shared was created using a large resolution and then optimized to reduced file size?

**Comment by camUrban** [comment]
@banesullivan Thanks for the quick response! The good example was optimized and resized. However, I believe that the color bar was smooth before doing so. I'll try and find an archived version that was unoptimized if you think that will help!

**Comment by camUrban** [comment]
@banesullivan Also, I tried to use The Wayback Machine to see if the documentation ever smoothly displayed the example GIF's color bar. Unfortunately, it appears GIFs are converted to static images for archiving. Do you have any saved versions from early 2021?

**Comment by camUrban** [comment]
Update! I may have found a PyVista/VTK/code combination that creates the smooth color bar.

PyVista==0.29.0, VTK==9.0.3:
![animation](https://user-images.githubusercontent.com/26682141/151211678-a932006b-f9fa-4f25-955a-06364fd6323c.gif)

The source code I'm using is unsteady_ring_vortex_lattice_method_solver_variable_example.py in the [PteraSoftware package](https://github.com/camUrban/PteraSoftware).

This example calls the animate function within the output.py script. You can find output.py in the pterasoftware package/directory.

The code in the animate function is a bit different from the documentation's example code. Maybe the different implementations could hint at the solution? @banesullivan What are your thoughts?

**Comment by camUrban** [comment]
Here's the system information for the above "good" example:

```txt
--------------------------------------------------------------------------------
  Date: Wed Jan 26 12:23:13 2022 Eastern Standard Time
                OS : Windows
            CPU(s) : 8
           Machine : AMD64
      Architecture : 64bit
       Environment : Python
       File system : unknown
        GPU Vendor : Intel
      GPU Renderer : Intel(R) HD Graphics P530
       GPU Version : 4.5.0 - Build 27.20.100.8681
  Python 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit
  (AMD64)]
           pyvista : 0.29.0
               vtk : 9.0.0
             numpy : 1.20.0
           imageio : 2.14.1
           appdirs : 1.4.4
            scooby : 0.5.11
            meshio : 4.4.6
        matplotlib : 3.5.1
           cmocean : 2.0
             scipy : 1.7.3
              tqdm : 4.62.3
--------------------------------------------------------------------------------
```

I'm not sure why the report claims that I'm using VTK=9.0.0. According to my PyCharm, I'm using VTK=9.0.3:
![image](https://user-images.githubusercontent.com/26682141/151214667-d092f734-a97d-4eda-8948-fa1cc77dde92.png)

**Comment by camUrban** [comment]
**Update:**
So, I managed to modify the example code so that it produces a smooth scalar bar. Strangely, this seems to work with the latest versions of both PyVista (0.33.2) and VTK (9.1.0).

**Code:**
```py
import numpy as np

import pyvista as pv

x = np.arange(-10, 10, 0.25)
y = np.arange(-10, 10, 0.25)
x, y = np.meshgrid(x, y)
r = np.sqrt(x ** 2 + y ** 2)
z = np.sin(r)

grid = pv.StructuredGrid(x, y, z)

plotter = pv.Plotter()

plotter.add_mesh(
        grid,
        scalars=z.ravel(),
        smooth_shading=True,
        clim=[-1, 1],
        render=False,
)
plotter.add_scalar_bar(render=False)

print('Orient the view, then press "q" to close the window and produce the animation.')

plotter.show(cpos=(-1, -1, 1), full_screen=False, auto_close=False)

plotter.open_gif("wave.gif")

pts = grid.points.copy()

nframe = 15
for phase in np.linspace(0, 2 * np.pi, nframe + 1)[:nframe]:
    z = np.sin(r + phase)
    pts[:, -1] = z.ravel()

    plotter.clear()

    plotter.add_mesh(
        grid,
        scalars=z.ravel(),
        smooth_shading=True,
        clim=[-1, 1],
        render=False,
    )
    plotter.update_coordinates(pts, render=False)
    plotter.add_scalar_bar(render=False)
    plotter.update_scalars(z.ravel(), render=False)

    plotter.mesh.compute_normals(cell_normals=False, inplace=True)

    plotter.render()
    plotter.write_frame()

# Closes and finalizes movie
plotter.close()

```

**Screenshot:**
![wave](https://user-images.githubusercontent.com/26682141/151238321-1a67cd68-ca53-4602-a8b1-30c0860f684b.gif)

**Conclusions:**
It seems that the three tweaks necessary to achieve a smooth color bar are:
1. Calling ```add_scalar_bar``` after the first call of ```add_mesh```.
2. Clearing the plot, calling ```add_mesh```, and calling ```add_scalar_bar``` during each loop.
3. Hardcoding color map limits using the ```clim``` argument

While I've technically solved my problem with this workaround, it is definitely less efficient than the standard method of creating a GIF.

**Comment by banesullivan** [comment]
@camUrban, this is fantastic investigative work!! I've been dealing with this issue well before 2021 and have been consistently annoyed by it, so I'm excited to see you found a solution!

While this solution is indeed a bit convoluted, it will help us a ton in figuring out exactly why the scalar bar is jittery by default and perhaps fix this all together so that the examples will work as is.

**Comment by akaszynski** [comment]
These are some amazing gifs. @tkoyama010, could you add [camUrban/PteraSoftware](https://github.com/camUrban/PteraSoftware) as an external example?

I've been thinking about streamlining how we do animation anyway, this might be a good example to base the PR off of.

**Comment by akaszynski** [comment]
Turns out the trick is `plotter.clear()` because we remove lighting. The color space ends up being much more limited. This works:
```py
import numpy as np

import pyvista as pv

x = np.arange(-10, 10, 0.25)
y = np.arange(-10, 10, 0.25)
x, y = np.meshgrid(x, y)
r = np.sqrt(x ** 2 + y ** 2)
z = np.sin(r)

# Create and structured surface
grid = pv.StructuredGrid(x, y, z)

# Create a plotter object and set the scalars to the Z height
plotter = pv.Plotter(notebook=False, off_screen=True, lighting=None)
plotter.add_mesh(grid, scalars=z.ravel(), clim=[-1, 1])

# Open a gif
plotter.open_gif("wave.gif")

pts = grid.points.copy()

# Update Z and write a frame for each updated position
nframe = 15
for phase in np.linspace(0, 2 * np.pi, nframe + 1)[:nframe]:
    z = np.sin(r + phase)
    pts[:, -1] = z.ravel()
    plotter.update_coordinates(pts, render=False)
    plotter.update_scalars(z.ravel(), render=False)

    plotter.render()
    plotter.write_frame()

# Closes and finalizes movie
plotter.close()
```

**Comment by akaszynski** [comment]
One follow-up for this would be to display a warning when lighting is enabled when calling [open_gif](https://docs.pyvista.org/api/plotting/_autosummary/pyvista.Plotter.open_gif.html?highlight=open_gif#pyvista.Plotter.open_gif), letting the user know that there will be a degradation of quality when lighting is enabled.

**Comment by tkoyama010** [comment]
> These are some amazing gifs. @tkoyama010, could you add camUrban/PteraSoftware as an external example?

Yes. Let's add it.
Note: https://github.com/camUrban/PteraSoftware

**Comment by zakgrin** [comment]
I was able to fix this issue easily by specifying `n_colors` argument within `add_mesh()` method.

**Comment by camUrban** [comment]
@zakgrin Interesting! I reran the original script and specified `n_colors` in `a_mesh()`. For numbers of colors below 11, the jitteriness disappeared, but at higher values, it came back. Do you see the same thing on our machine?

**Comment by zakgrin** [comment]
@camUrban maybe you need to try to increase to decrease `n_labels` as well.

**Comment by camUrban** [comment]
@zakgrin it seems like changing `n_labels` has no effect on the jitteriness on my end. Do you see jitteriness with `n_colors` above 20 when you run the script?

**Comment by banesullivan** [comment]
The best trick is to set `lighting=None` when instantiated the `Plotter` or `lighting=False` in `add_mesh()` as @akaszynski and @camUrban point out above and our example in the docs highlights: https://docs.pyvista.org/version/stable/examples/02-plot/gif.html#generate-a-gif

However, this isn't ideal as lighting is often a critical part of visualizations and how we perceive them.

One alternative is to make an MP4 instead of a GIF (`pl.open_movie("wave.mp4")`) (my go-to since MP4 is supported pretty ubiquitously these days)

Otherwise, this is simply a limitation of GIF as I point out in https://github.com/pyvista/pyvista/discussions/1742#discussioncomment-1672054:

> GIFs have a limit of 256 colors and they have trouble interpolating between colors. There is a neat example of the issue and possible solutions here: https://en.wikipedia.org/wiki/GIF#True_color

Improving this any further is quickly gets out of scope for PyVista as our GIF writer implementation is nothing more than a thin wrapping of the standard routine for crating a GIF with `imageio`:

```py
import imageio
with imageio.get_writer('/path/to/movie.gif', mode='I') as writer:
    for ...:
        image = plotter.screenshot()
        writer.append_data(image)
```

**Comment by banesullivan** [comment]
Regarding the notes about `n_colors` here: You can mask this problem by significantly reducing the number of colors in the image.

The reason setting `n_colors=64`, etc, still looks jittery is because of the lighting. The lights in the scene illuminate the scalar values you are mapping on differently throughout the scene, hence increasing the actual number of colors in the scene well above the `n_colors` set for the lookup table

**Comment by banesullivan** [comment]
My non-answer to this whole problem is "just use MP4 😜"... I get that you want to use a GIF, but I genuinely wonder why? Why use GIF and not MP4? What is your specific use case for this? I feel like just about everything supports it these days... sans Google Slides

**Comment by camUrban** [comment]
@banesullivan I agree that, in general, using MP4s makes sense instead of GIFs. My use case is a little silly: it's mainly that I like having auto-playing animations in PteraSoftware's ReadMe and in Google Slides. My workaround has been to plot and save images using PyVista and then convert them into a WebP animation using the WebP package. WebPs don't have the same color limitations as GIFs, and they're supported by markdown for ReadMe files. An added benefit is that you can have transparent backgrounds!

The drawbacks are that I need to add another package as a dependency (WebP) to my project and that Google Slides doesn't support WebPs (even though WebP was developed by Google 🙄). My workaround for the second issue is just to manually convert the WebPs to GIFs using ezgif.com if I need to add them to a presentation.

**Comment by banesullivan** [comment]
> having auto-playing animations in PteraSoftware's ReadMe
I don't think that's silly at all! 

> My workaround has been to plot and save images using PyVista and then convert them into a WebP animation using the WebP package

Is this something we should support directly in PyVista?

**Comment by camUrban** [comment]
If possible, I think that would be great!

**Comment by azona** [comment]
Hi everyone, 

the issue reappears when setting _opacity_ in add_mesh, even using _lighting=None_


```

# Create a plotter object and set the scalars to the Z height
plotter = pv.Plotter(notebook=False, off_screen=True)
plotter.add_mesh(
    grid,
    scalars='Height',
    lighting=False,
    opacity=0.5,
    show_edges=True,
    clim=[-1, 1],
)

# Open a gif
plotter.open_gif('wave.gif')

# Update Z and write a frame for each updated position
nframe = 15
for phase in np.linspace(0, 2 * np.pi, nframe + 1)[:nframe]:
    z = np.sin(r + phase)
    # Update values inplace
    grid.points[:, -1] = z.ravel()
    grid['Height'] = z.ravel()
    # Write a frame. This triggers a render.
    plotter.write_frame()

# Closes and finalizes movie
plotter.close()
```


![Image](https://github.com/user-attachments/assets/86c805d4-3325-4ffb-b739-f7808dcff5b3)

**Comment by camUrban** [comment]
@azona I'm seeing the same thing. Here's my script
```py
import numpy as np

import pyvista as pv

x = np.arange(-10, 10, 0.25)
y = np.arange(-10, 10, 0.25)
x, y = np.meshgrid(x, y)
r = np.sqrt(x ** 2 + y ** 2)
z = np.sin(r)

grid = pv.StructuredGrid(x, y, z)

plotter = pv.Plotter(notebook=False, off_screen=True, lighting=None)

plotter.add_mesh(grid, scalars=z.ravel(), clim=[-1, 1], opacity=0.5, lighting=False)

plotter.open_gif("transparent_wave.gif")

pts = grid.points.copy()

num_frames = 15

for phase in np.linspace(0, 2 * np.pi, num_frames + 1)[:num_frames]:
    z = np.sin(r + phase)
    pts[:, -1] = z.ravel()
    plotter.update_scalars(z.ravel(), render=False)

    plotter.render()
    plotter.write_frame()

plotter.close()
```

**Comment by akaszynski** [comment]
Try reducing the number of colors down to 16. My guess is due to the overlapping of the surface with opacity, there are actually way more than just 16 colors.

```py
import numpy as np

import pyvista as pv

x = np.arange(-10, 10, 0.25)
y = np.arange(-10, 10, 0.25)
x, y = np.meshgrid(x, y)
r = np.sqrt(x**2 + y**2)
z = np.sin(r)


grid = pv.StructuredGrid(x, y, z)
grid["Height"] = z.ravel()

# Create a plotter object and set the scalars to the Z height
plotter = pv.Plotter(notebook=False, off_screen=True)
plotter.add_mesh(
    grid,
    scalars="Height",
    lighting=False,
    opacity=0.5,
    show_edges=True,
    clim=[-1, 1],
    n_colors=16,
)

# Open a gif
plotter.open_gif("/tmp/wave.gif")

# Update Z and write a frame for each updated position
nframe = 15
for phase in np.linspace(0, 2 * np.pi, nframe + 1)[:nframe]:
    z = np.sin(r + phase)
    # Update values inplace
    grid.points[:, -1] = z.ravel()
    grid["Height"] = z.ravel()
    # Write a frame. This triggers a render.
    plotter.write_frame()

# Closes and finalizes movie
plotter.close()
```

![Image](https://github.com/user-attachments/assets/2ff54ff9-9f84-4bed-9bd8-0e34ca4fab73)

---

We can actually check this. With this command we can get the number of colors per frame:

```
identify -format "%k\n" wave.gif
249
229
227
230
229
228
228
230
230
228
228
228
228
226
228
```
