### ISSUE TITLE
Renaming vtki → PyVista

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#208]
@akaszynski and I will be renaming `vtki` to avoid confusion between this library and other similarly named projects as well as to reflect that `vtki` is not a direct product of VTK or Kitware and to ensure that were are **absolutely not using VTK's name to endorse or promote a product derived from VTK.**

Renaming the software will require quite a lot of refactoring both internally and across dependent projects - even so, we feel renaming `vtki` is necessary.

## Call for Help

**Users of `vtki`:** we would like to solicit your help in making a new name for this software and we welcome any and all suggestions that are compliant with most open-source software licensing terms.

Please use this issue as a place to post your thoughts on what this software shall be named and be sure to give a +1 (👍) to any suggestions that you like!

**Comment by aashish24** [comment]
how about ipyvis?

**Comment by mmagnuski** [comment]
Off top of my head: **v**en**t**ri**k**le (or just ventricle) :)
<img src=https://upload.wikimedia.org/wikipedia/commons/1/12/CG_Heart.gif width="300px">

**Comment by banesullivan** [comment]
Thanks for the suggestion @aashish24!

I'm concerned it might be confused with https://github.com/WestHealth/pyvis

**Comment by banesullivan** [comment]
Thanks, @mmagnuski! That's a really cool visualization - did you make that leveraging `vtki`?!

**Comment by akaszynski** [comment]
This is of course right after we made the logo!

It used to be ``vtk_interface``, which is where ``vtki`` came from.  Ideally the module would be short and sweet, but still an informative pep8 name.  I'm thinking:
- ``visplot``
- ``easyvis``
- ``meshplot`` or ``gridplot`` or ``simplot`` (as in simple plotting)
- ``not_vtk`` (just kidding, it's not pep8)

``vtkplotter`` might have to change their name as well...

**Comment by thast** [comment]
how about simply `visualize`? (that is probably my `simpeg/discretize` bias ^^ ) and the repo name seems to not have been taken yet.

**Comment by tomtomatron** [comment]
How about `Envisage` or `nviz` for short. Maybe `nvz`.

**Comment by akaszynski** [comment]
``visualize`` sounds good.  I'm amazed the module name isn't taken.

I'll probably just end up importing as:
```python
import visualize as vis
```

It's a straightforward module name.  Thanks @thast 

It's also great to see the support.  Didn't know how many people were active here on the repo.

**Comment by banesullivan** [comment]
I'm shocked `visualize` and `visualizer` aren't taken on PyPI yet... we may want to jump on those

**Comment by craigmillernz** [comment]
Something that ties into OpenGeoVis, which is the parent project might be an idea?

**Comment by craigmillernz** [comment]
I like visualize, it's simple, generic easy to remember and shorten when importing

**Comment by banesullivan** [comment]
My current favorites (in no particular order) are:

- `visualize`
- `simplot`
- `Envisage`

**Comment by craigmillernz** [comment]
Envisage reminds me on Enthought... Not necessarily a good thing....

**Comment by banesullivan** [comment]
🤣 Good point, thanks @craigmillernz

**Comment by banesullivan** [comment]
It's worth noting that we'll also have to rename the organizational account @vtkiorg - likely to the same name as the main software library or something different if we land on `visualize` since that GitHub account is taken

Perhaps something in line with @OpenGeoVis like @craigmillernz mentioned?

- I love "vispy" and "pyviz" but these are taken 😞 
- "openvis"/"openviz" - again these are taken on GitHub but something similar would be nice

**Comment by leouieda** [comment]
I like `visualize` as well. Is there anything else that could be more unique? There are already so many `*vis*` packages out there. I feel like vtki has a very direct mission (a better VTK interface) that calling it `visualize` might be too generic.

**Comment by aashish24** [comment]
I like visplot, visualize (although it may be a hard search on google), easyvis, 

Simplot will be mixed with simulation..

**Comment by banesullivan** [comment]
Thanks, @leouieda! This is a great point - `vtki`'s mission has been to make VTK's data types, filtering algorithms, and rendering more accessible to new users and researchers looking for an easy-to-use mesh analysis and visualization toolset.

Considering most of the recent development has been to make analysis and filtering algorithms for all the datatypes - a name like `visualize` might not capture scope of what this software implements.

For example, we have all types of thresholding, slicing, mesh subsetting, etc. algorithms available

**Comment by banesullivan** [comment]
Another good point, @aashish24 - "simplot" does imply simulation in my mind so that likely isn't an appropriate name

`easyviz`/`easyvis` is growing on me - both GitHub org accounts (I just snagged them) and PyPI package names are available

**Comment by leouieda** [comment]
Why not have the repo under `opengeovis`? That way you don't have to worry about the account.

**Comment by leouieda** [comment]
How about something that plays on the concept of "improving a toolkit": knife sharpening, lubricating (WD-40), upgrading (hammer -> nail gun). I tend to like quirky names but there is benefit to being easily googled.

**Comment by banesullivan** [comment]
### Org Account

I suppose we avoided putting `vtki` under @OpenGeoVis from the start because `vtki`'s applications are more general than geo-visualization and we wanted to attract users from all disciplines. 

Considering that almost every project under @OpenGeoVis is built on top of `vtki` and we seem to be gaining traction mostly in the geoscience realm at this time, this might be appropriate. However, I want to make sure this software gains visibility from users across disciplines as it is used as a supporting module in more non-geo software packages at this time - see dependents graph for details.

@akaszynski, thoughts?

### Software Name

@leouieda: I very much like the "improving a toolkit" concept - I'll have to brainstorm this in regards to how `vtki` "sharpens"/improves VTK - do you have any projects in mind that do this kind of software improvement/wrapping?

**Comment by leouieda** [comment]
@banesullivan I imagined that was the case for opengeovis. Off the top of my head:

* [requests](https://2.python-requests.org/en/master/) wraps `urllib3` (somewhat) and is used by pretty much everyone doing we stuff. Tag line: HTTP for humans. 
* [gitless](https://gitless.com/) is a redesigned version of git built on top of git

**Comment by banesullivan** [comment]
what about `meshy`?

```py
import meshy

mesh = meshy.PolyData()

mesh.plot()
```

**Comment by mmagnuski** [comment]
A few ideas that aim to emphasise 3d:
* `thirdeye`
* `depth` (or `depthviz`)
* `trivis` (threevis is taken) or `freevi`

And another to retain the `vtk` + `i` identity:
`vistki` (`import vistki as vtki` ;P) which would translate to
"**vis**ualize **t**hreedimensional (**k**)onstructs **i**nteractively" to avoid any copyright issues :D

**Comment by leouieda** [comment]
On the 3D theme, how about "stereoscope" or "parallax"?

**Comment by craigmillernz** [comment]
or "perspective"

**Comment by craigmillernz** [comment]
> 
> 
> what about `meshy`?
> 
> ```python
> import meshy
> from meshy import examples
> 
> mesh = meshy.PolyData()
> # ... or ....
> mesh = examples.download_st_helens().warp_by_scalar()
> 
> p = meshy.Plotter()
> p.add_mesh(mesh)
> p.show()
> ```
> 
> inspired by @AntonBiryukovUofC - "Boaty McBoatface" → "Meshy McMeshface"

meshy implies its about creating meshes not visualizing. plus too much overlap with discretize which has a Mesh

**Comment by aashish24** [comment]
parallax would be misleading - it is used for stereo, meshy will sounds more like a mesh library. Also, I would think you want to make it general 2D and 3D library as opposed to just 3D.

**Comment by tomtomatron** [comment]
If 'Envisage' doesn't sit well, maybe `nviz` for `N-dimensional visualization`, or `Envison`.

**Comment by jmp75** [comment]
`nviz` is nice and short, but may also be misleading as `vtki` is not for any N-dimensional data. People searching for this may seek more something like [ggobi](http://www.ggobi.org).

**Comment by banesullivan** [comment]
On the comments about `vtki`'s focus - `vtki` is built to be both an underlying mesh creation and analysis utility as well as a 3D visualization tool for those mesh types. We want to emphasize that `vtki` is **not just 3D visualization** and it can be used as a supporting module for the underlying types in software that use discretized finite volume and element meshes with simple geometries using voxels/hexahedrons (think `discretize`) or complex geometries using tetrahedrons, etc. (think applications like [PyGIMLi](https://www.pygimli.org)). 

## Future of `vtki`

**My (somewhat overzealous) goal for `vtki`:** to become the underlying library of choice for Python-based finite volume/element analysis, processing, and simulation software. I envision`vtki`'s mesh types being used as the underlying data structures in finite mesh problems across a wide range of software libraries. This would bring interoperability amongst software to a whole new level - think of the possibilities if people from all disciplines collaborated on a single toolset for finite mesh problems. The caveat is that we have quite a bit of development to go before we could get to that point.

### Use Case

If you are developing a finite volume simulation software and dealing with 3D data, then the underlying mesh types need to be able to be visualized in 3D - rather than create your own mesh types which are likely equivalent to underlying structures in VTK, simply define your operators to work with `vtki` mesh types and you'll gain the all the additional features of `vtki`'s mesh analysis and filtering... The 3D plotting is a required feature after that which is why we have so much code dedicated to making the process of visualizing complex `vtki` datasets intuitive/easy - having powerful 3D viz features is how I hope to get folks using `vtki` and onboard with trying to use `vtki`'s types for their project.

### 2D vs. 3D

This is likely better suited for its own issue, but I think our focus with `vtki`'s viz efforts should be for 3D visualization. `matplotlib` is an excellent tool for 2D viz and if our users want 2D representations of their 3D `vtki` data, then I think it would be best for us to create an interface for visualizing `vtki` datasets with `matplotlib`... especially since `matplotlib` is in a far better state in regards to creating publication-quality images (reference #147 and #165)

**Comment by banesullivan** [comment]
how about **`meshviz`**

```py
import meshviz

mesh = meshviz.UniformGrid()
...
p = meshviz.Plotter()
...
```

**Comment by banesullivan** [comment]
Another (lazy) option is **`ivtk`** as in the "**I**nterface to the **V**isualization **T**ool**k**it" which avoids copyright issues (to the best of my knowledge) and adheres to our mission of building "A Streamlined Python Interface to the Visualization Toolkit"

**Comment by akaszynski** [comment]
`ivtk`, because I'm lazy and four characters is easier to type than 5.

**Comment by leouieda** [comment]
So Kitware would be fine with `ivtk` but not `vtki`?

**Comment by banesullivan** [comment]
We should do something different... if using `vtk` in our current name is an issue then we should avoid it altogether to make sure everyone is happy and adhering to copyright laws

**Comment by banesullivan** [comment]
Also, `mvis` which is a short, 4-letter verison of `meshvis`

```py
import mvis

mesh = mvis.UniformGrid()
...
p = mvis.Plotter()
...
```

**Comment by lheagy** [comment]
One that popped into my head: `vista` (def: a pleasing view)

**Comment by banesullivan** [comment]
I like `vista`... plus it's available on PyPI

**Comment by banesullivan** [comment]
Let's see how other's react but I'm liking `vista` (even though it implies visualization only which I have some hesitation about). 

This would also be easy for other tools that expand on `vtki`/`vista` to easily tag our name to the end and new users know to associate that new software with this software: e.g. `***vista`. 

With the name change to `vtki`, I will also be changing the names of offshoot projects for consistency like [`omfvtk`](https://github.com/OpenGeoVis/omfvtk) → `omfvista`.

**Comment by craigmillernz** [comment]
vista is nice but maybe a bit close to VisIT? [https://wci.llnl.gov/simulation/computer-codes/visit](visit)

**Comment by craigmillernz** [comment]
VisTK?

**Comment by banesullivan** [comment]
I think `vista` is different enough from VisIt - `VisTK` might be too close to both VTK and VisIt

**Comment by leouieda** [comment]
`vista` is my favorite so far. It sounds unique and pleasant. Might be tough to get a good domain name, though: https://www.fatiando.org/verde/

**Comment by dannyseim** [comment]
anthro-py-scene

**Comment by craigmillernz** [comment]
sciviz? Scientific Visualisation

**Comment by banesullivan** [comment]
oooooo... I like `sciviz`

**Comment by banesullivan** [comment]
I'm leaning towards `vistas` which has a bit more availability than `vista` when it comes to GitHub organization accounts, domains, and non-similarity with things like https://github.com/geovista, and `VistaPro`: https://en.wikipedia.org/wiki/VistaPro

**Comment by banesullivan** [comment]
I propose:

- rename `vtki` to `vistas` 
- rename @vtkiorg to @pyvistas 
- forward https://vtki.org to https://pyvistas.org

I already acquired those accounts/domains

**Comment by banesullivan** [comment]
Actually `vista` has the same availability:

- rename `vtki` to `vista` 
- rename @vtkiorg to @pyvista
- forward https://vtki.org to https://pyvista.org

I already acquired those accounts/domains

**Comment by craigmillernz** [comment]
i'm confused between the distinction of vista vs pyvista ?

**Comment by banesullivan** [comment]
domain names for `vista` are through the roof expensive... `pyvista` is way cheaper and more in line with what the organizational account is doing: "Creating Python visualization software leveraging the Visualization Toolkit (VTK)"

We could also call the software itself `pyvista` I just shortened because: 

```py
import vista
``` 

is easier/ cleaner than 

```py
import pyvista 
```
but I'm totally open to either

**Comment by lheagy** [comment]
Pytorch makes the same distinction - the website is: https://pytorch.org/, but the import is 
```
import torch 
```

:+1: from me on the shorter import `vista` plus the longer / more searchable website domain `pyvista`

**Comment by banesullivan** [comment]
I'm sold. @akaszynski, any reservations?

**Comment by craigmillernz** [comment]
but torch/pytorch have 
conda install pytorch torchvision cudatoolkit=9.0 -c pytorch

so is how is it labelled on pip/conda?

**Comment by banesullivan** [comment]
I'm thinking the organizational aspect of this project should be referred to as "pyvista" and the software itself be "vista" so all pip/conda installs would be `pip install vista`.. `pyvitsa`/`pytorch` seems redundant to me when working with a Python package manager...

**Comment by craigmillernz** [comment]
what about all the external facing names (website, pip, conda etc) should refer to pyvista, but within the code it gets shortened to vista?  Just thinking it is less confusing for new people to find and to make it clear that pyvista isnt just a wrapper on some other thing called vista, but is the actually code in its own right.  I agree the py is a bit redundant but i'm just aiming for clarity.

**Comment by banesullivan** [comment]
> Just thinking it is less confusing for new people to find and to make it clear that pyvista isnt just a wrapper on some other thing called vista, but is the actually code in its own right

That's an excellent point... "pyvista" might imply its some sort of python wrapping for another "vista" library. However, I think what I am proposing here is in line with pyviz: http://pyviz.org

**Comment by leouieda** [comment]
I am very much against naming the pip/conda packages one thing and importing another. This is terrible for users and causes a lot of confusion. It's fine if the website and github organization have different names because people usually don't have to know/remember those. The repository, package, and library names should be consistent, though.

**Comment by akaszynski** [comment]
Agreed with @leouied.  I like ``vista``, and a domain name of ``pyvista`` works, but the repo, package, and library should all be ``vista``.

**Comment by banesullivan** [comment]
It appears that we are all converging on:

```bash
pip install vista

conda install -c conda-forge vista
```

```py
import vista
```

Docs: https://docs.pyvista.org

Then related projects under the @pyvista organization can have subdomains under http://**.pyvista.org

And the main website http://pyvista.org will have a high level overview of everything we are building in this space

**Comment by craigmillernz** [comment]
so would this sit under here as well?
http://opengeovis.org/

**Comment by banesullivan** [comment]
Possibly... I might end up migrating @OpenGeoVis under @pyvistas as everything in that org is pretty much built on top of `vista`. 

I also snagged the @geopyvista account just in case we want to separate the geoscience applications

**Comment by aashish24** [comment]
I like vista and geovista 👍

**Comment by banesullivan** [comment]
We’ve landed!! 🚀 

I’ll begin the internal refactoring process in a PR then start switching ownership over to @pyvistas

Should we stage a release of `vtki` that will throw a runtime error on import telling users to install vistas instead?

Is there an easy way to link `pip install vtki` to `pip install vistas`? And same for conda?

**Comment by akaszynski** [comment]
Agreed.  Last release can include the runtime error.  We can remove it off of pypi after a few months have passed.

Goodbye old friend `vtki`, long live `vista`!

**Comment by leouieda** [comment]
@banesullivan, you can make `vista` a dependency of `vtki`.

**Comment by florian-wagner** [comment]
Just joking. I like the name and the software, independent of its name, a lot. Next pyGIMLi release will ship with a vista-based 3D viewer. Thanks for the great work.

**Comment by banesullivan** [comment]
The transition is almost complete! Shoutout to @lheagy for recommending the name `vista` 🎆  and major thanks to everyone here that posted suggestions and their thoughts! 

It really means a lot to us that all of you are so active and interested in seeing `vista` succeed - I never could have imagined this software would be embraced by you all so rapidly - thanks for the support everyone!

- `vista` version `0.19.0` is live on PyPI 🎉 
- `omfvista` version `0.1.0` is live on PyPI 🎉 
- `PVGeo` is showing green lights on after refactoring ✅ 
- I've raised issues with all external projects I know of leveraging `vtki`/`vista` to let them know the name has changed. Unfortunately, I didn't take a look at the dependents graph before changing the name so I may be forgetting a few

I'm in the process of fixing all the deployment tests but all is looking good at this point. 

I need some help fixing the Conda-forge deployment... @hadim originally implemented that for us and to be honest I have no idea what to do to fix it: https://github.com/conda-forge/vtki-feedstock/issues/14

**Comment by jcapriot** [comment]
I know it’s I’m late to the game, but vista just reminds me of the bad Windows operating system from like 2007...

**Comment by banesullivan** [comment]
I think I'm going to rename the repository `pyvista` but still keep the package on PyPI/conda as `vista`. I think if we officially call the software "PyVista", we can avoid any potential legal issues with the name being too similar to all the other "vista" things out there.

This is exactly what PyTorch does: https://github.com/pytorch/pytorch

Any objections?

**Comment by akaszynski** [comment]
Agreed

**Comment by banesullivan** [comment]
Note the discussion in https://github.com/softwareunderground/awesome-open-geoscience/pull/78

**Comment by leouieda** [comment]
I would suggest going all the way and renaming everything pyvista (package included). From my own experience, having my repository/pypi packages called `gmt-python` while the package itself was `gmt` generated a whole lot of trouble for new users and a bunch of confused bug reports.

**Comment by akaszynski** [comment]
That works as well and doesn’t conflict with the other vista package.

**Comment by banesullivan** [comment]
With a name that long, should we push an alias on import? Perhaps:

```py
import pyvista as pv

mesh = pv.StructuredGrid()
...

p = pv.Plotter()
```

**Comment by leouieda** [comment]
I like `pyvista as pv`. That leads nicely to `pvgeo` which could now be `pv -> paraview` or `pv -> pyvista`.

**Comment by banesullivan** [comment]
That’s an excellent point!

As for other offshoot projects like `omfvtk` which is `omfvista` at this moment, would `**vista` be appropriate (copyright/trademark friendly) or should we try to build a brand of `pv**` products that revolve around PyVista?

**Comment by banesullivan** [comment]
The name change appears to be complete! `pyvista` is live on both PyPI and Conda-forge and it looks to me like all of the dependents have caught up:

<img width="753" alt="Screen Shot 2019-05-15 at 1 37 17 PM" src="https://user-images.githubusercontent.com/22067021/57803904-b1f32a80-7716-11e9-8ac5-34a620517f6c.png">

I'm going to close this issue but see if I can keep it pinned
