### ISSUE TITLE
Auto merge dependabot PRs

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#2089]
Should we use https://github.com/marketplace/actions/dependabot-auto-merge and auto merge dependabot PRs?

**Comment by akaszynski** [comment]
Yes. While I love pressing the green button, we really should just automate it.

**Comment by tkoyama010** [comment]
@banesullivan I made PR for this. Please use if you like.

**Comment by adeak** [comment]
Would that only merge if CI is green?
