### ISSUE TITLE
Sample over spline or polyline

### ISSUE THREAD

**Issue by Aquan1412** [pyvista/pyvista#2095]
**Describe what feature you would like added.**

I'm looking for a way to extract values from a 3d mesh based on a spline or, generally, a curve that I can define. Currently, there are two functions that are close to what I would like to achieve: streamlines and sample_over_line. Both extract field values along a path in space. However, in my case the curve is neither a streamline nor a straight line, but instead a spline defined by a number of points.

Looking at the sample_over_line function, it simply takes two points to create a pyvista.Line object. Would it be possible to create a new function, sample_over_polyline, that takes an array of points to build a polyline and sample along this polyline?

**Comment by banesullivan** [comment]
Such a method would simply be a wrapper of the `sample()` filter (which `sample_over_line()` is). If you can create the polyline from your points, then calling the `.sample()` filter with it would handle your use case.

Check out [this example](https://docs.pyvista.org/examples/00-load/create-spline.html#sphx-glr-examples-00-load-create-spline-py) for creating polylines

Here is an example

```py
import numpy as np
import pyvista as pv

def make_points():
    """Helper to make XYZ points"""
    theta = np.linspace(-4 * np.pi, 4 * np.pi, 100)
    z = np.linspace(-2, 2, 100)
    r = z**2 + 1
    x = r * np.sin(theta)
    y = r * np.cos(theta)
    return np.column_stack((x, y, z))

def make_volume():
    theta = np.linspace(-4 * np.pi, 4 * np.pi, 100)
    z = np.linspace(-2, 2, 100)
    x = y = np.linspace(-5, 5, 100)
    mesh = pv.RectilinearGrid(x, y, z)
    mesh['r'] = mesh.points[:, -1]**2 + 1
    return mesh
    

points = make_points()

def polyline_from_points(points):
    poly = pv.PolyData()
    poly.points = points
    the_cell = np.arange(0, len(points), dtype=np.int_)
    the_cell = np.insert(the_cell, 0, len(points))
    poly.lines = the_cell
    return poly

polyline = polyline_from_points(points)
volume = make_volume()

sampled = polyline.sample(volume)

p = pv.Plotter(notebook=False, shape=(1,2))
p.add_mesh(polyline,  line_width=5)
p.add_mesh(volume, color=True, opacity=0.75)
p.subplot(0,1)
p.add_mesh(sampled,  scalars='r', line_width=5)
p.add_mesh(volume, scalars='r', opacity=0.75)
p.link_views()
p.show()
```
![Screen Shot 2022-01-28 at 9 36 39 AM](https://user-images.githubusercontent.com/22067021/151585863-53d34786-18ec-474e-8d17-b312735359a9.png)

**Comment by banesullivan** [comment]
IMO, we shouldn't have too many more `sample_over_*` methods. We could however include things like `polyline_from_points()` as a utility method

**Comment by Aquan1412** [comment]
Thank you for the quick reply! The above example is exactly what I need. Using the sample filter itself didn't occur to me, as I didn't think of the polyline as a mesh. Adding the polyline_from_points() utility would be nice, but for my personal use I can simply include the function in my scripts. 

I agree that there shouldn't be too many additional wrapper functions for specific cases, and since my use case is already covered anyways, I'll close the issue.
