### ISSUE TITLE
Pooch integration for downloading examples

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#210]
We should change our example downloading utilities to leverage Pooch: https://github.com/fatiando/pooch

Not sure how much effort this will require, but the download utility I made is a bit unpredictable on the CI's - downloads time out a lot... not sure if Pooch would fix that but it's probably worth switching to Pooch to make downloading data files outside of our example data repo a bit easier

**Comment by leouieda** [comment]
:+1: I'd be happy to help get this going

**Comment by leouieda** [comment]
With Pooch v0.4.0, we added some processors that can do things like unzip an archive upon download. So it should have all you need to replace the internals of `_download_file` and `_download_and_read` with pooch. You can also use `pooch.make_registry` to create a registry with hashes out of all your data files. They don't need to be versioned since these files don't change when PyVista changes.

**Comment by banesullivan** [comment]
Thank you for all the details @leouieda! It looks like it should be a fairly straightforward transisition from the current code to `pooch` since we're already using `appdirs`.

Unfortunately, this downloading issue seems to be getting worse - it feels like every other build I'm having to restart jobs where downloads timed out, so I'd like to move this to `priority-high`.

> I'd be happy to help get this going

How soon do you think you could kick off this transition?

Also, I'm totally down for getting rid of the underlying functions like `_download_file` and `_download_and_read` to use `pooch` equivalents.

**Comment by banesullivan** [comment]
NOTE: download testing is currently turned off on Travis and AppVeyor via an environmental variable

**Comment by leouieda** [comment]
> NOTE: download testing is currently turned off on Travis and AppVeyor via an environmental variable

I'm having some trouble with this in [RockHound](https://github.com/fatiando/rockhound) which has been making me rethink the package. I don't know of a good way around downloading on CI.

**Comment by banesullivan** [comment]
Hm. It might just be a CI internet connectivity issue? Specifically, are you having trouble on Travis vs Azure?

**Comment by leouieda** [comment]
Both actually. And it’s random. Plus, it seems wasteful to download large files all the time for no particular reason. I haven’t tried storing the files in the CI cache but that might help since it’s a local download for them.

**Comment by banesullivan** [comment]
It should be really easy to cache the appdirs directory where everything is downloaded  we’d just need to export that path to an environmental variable

**Comment by banesullivan** [comment]
@akaszynski and I talked yesterday, and I'd like to bring this up on to the to-do list. Alex, set the priority as you see fit, but I'm going to assign this to myself.

**Comment by banesullivan** [comment]
FWIW, I've been using pooch on a few other projects, and it's a real pleasure to work with. We can significantly reduce lines of code in the `downloads` module by switching to pooch and the additional dependencies are light enough for my taste:

```
install_requires =
    appdirs>=1.3.0
    packaging>=20.0
    requests>=2.19.0
```

**Comment by akaszynski** [comment]
Once I've gotten a few of the high priority PRs merged I'll start working on this. @ me if you make a branch/PR so we don't duplicate.
