### ISSUE TITLE
Try cleaning up the CONTRIBUTING.md/developer_notes.rst dichotomy

### ISSUE THREAD

**Issue by adeak** [pyvista/pyvista#2105]
https://github.com/pyvista/pyvista/pull/2104 made me realise that we have two files with almost the same contents: [CONTRIBUTING.md](https://github.com/pyvista/pyvista/blob/f0751e499d3ee3dfe5f77ff2af455eb8648b0792/CONTRIBUTING.md) and [doc/extras/developer_notes.rst](https://github.com/pyvista/pyvista/blob/f0751e499d3ee3dfe5f77ff2af455eb8648b0792/doc/extras/developer_notes.rst).

It seems to me that the two files _should_ have the same contents (other than the obvious markup differences), but they have diverged a bit over time. Now care must be taken to change anything in them in unison, otherwise the distance increases between the two.

So my question is: can we do something about this? Is there some way that we can generate either file from the other? Something like pypandoc perhaps, if our existing tooling can't do this? It seems like needless repetition and maintenance overhead that would be great to get rid of. Since `CONTRIBUTING.md` is a standard file, the ideal direction would be to generate `doc/extras/developer_notes.rst` from the former. From a quick glance it seems that all links are either completely external (i.e. fully qualified URLs) or internal to the same file. This should make this more feasible.

**Comment by banesullivan** [comment]
We could change `CONTRIBUTING.md` to be re-structured text (`.rst`) and then include its contents in `doc/extras/developer_notes.rst` when building the docs.

**Comment by banesullivan** [comment]
This is exactly what we do in `doc/getting-started/authors.rst`: https://github.com/pyvista/pyvista/blame/main/doc/getting-started/authors.rst#L11

**Comment by adeak** [comment]
Good idea @banesullivan.

For what it's worth I found [that pandas does the opposite of what I had in mind](https://pandas.pydata.org/docs/development/contributing_documentation.html):

> The `.rst` files are used to automatically generate Markdown and HTML versions of the docs. For this reason, please do not edit `CONTRIBUTING.md` directly, but instead make any changes to `doc/source/development/contributing.rst`. Then, to generate `CONTRIBUTING.md`, use pandoc with the following command:
`pandoc doc/source/development/contributing.rst -t markdown_github > CONTRIBUTING.md`

So if we want to go down that route we at least know how to do it. But networkx for instance [has a `CONTRIBUTING.rst`](https://github.com/networkx/networkx/blob/main/CONTRIBUTING.rst).

**Comment by tkoyama010** [comment]
Thank you for pointing this. I thought the same thing and made https://github.com/pyvista/pyvista/pull/2110.

**Comment by tkoyama010** [comment]
I have no problem putting the content I merge into `rst` format.
