### ISSUE TITLE
Median smooth filter for uniform grid datsets

### ISSUE THREAD

**Issue by njneeteson** [pyvista/pyvista#2114]
There is currently a gaussian smoothing filter implemented for uniform grid datasets as a wrapper around vtkImageGaussianSmooth. There is another very similar filter in VTK for smoothing 2D or 3D images called vtkImageMedian3D:

https://vtk.org/doc/nightly/html/classvtkImageMedian3D.html

The median image filter can be far more effective than gaussian smoothing depending on the characteristics of the noise, and it also has applications for filtering binarized images. It's possible to implement the median filter yourself on numpy data, but it's a bit tricky to implement efficiently (naive method with for loops is extremely slow, you have to use numpy.lib.stride_tricks to match the efficiency of the VTK implementation).

It could be implemented in:
https://github.com/pyvista/pyvista/blob/main/pyvista/core/filters/uniform_grid.py

By adding another method, "median_smooth," to the UniformGridFilters class. The structure of the new method could be modelled on the structure of the gauss_smooth method. The only relevant parameter in vtkImageMedian3D is the kernel size: the vtk class setter method needs three integers, setting the width of the kernel in each dimension. Setting one of these values to 1 makes the filter work on 2D data.

Usage of this filter would be identical to gaussian_smooth, with radius_factor and std parameters replaced with a kernel parameter that could take a list of length 2 or 3.

I'm very busy currently but in the near future I would be happy to try adding this myself if no-one else wants to and no-one else has any problems with any of the above. Otherwise, happy to hear feedback.

**Comment by akaszynski** [comment]
> By adding another method, "median_smooth," to the UniformGridFilters class. The structure of the new method could be modelled on the structure of the gauss_smooth method. The only relevant parameter in vtkImageMedian3D is the kernel size: the vtk class setter method needs three integers, setting the width of the kernel in each dimension. Setting one of these values to 1 makes the filter work on 2D data.

I think this would be a great addition and would really appreciate having this added to our project!

**Comment by njneeteson** [comment]
OK, feel free to assign to me. I will wait to create a feature branch until I know I will be able to spend time implementing and testing. Ideally I will have some free time in a week or two.

**Comment by njneeteson** [comment]
I have created the wrapper for vtkImageMedian3D and tested it on the "gourds" example image used in the gaussian example and it seems like it's working properly. I worked through the automated testing but had the following errors:


Running 'make doctest' in /doc:

> Sphinx-Gallery successfully executed 118 out of 121 files subselected by:
> 
>     gallery_conf["filename_pattern"] = '\\.py'
>     gallery_conf["ignore_pattern"]   = '__init__\\.py'
> 
> after excluding 0 files that had previously been run (based on MD5).
> 
> 
> Extension error:
> Here is a summary of the problems encountered when running the examples
> 
> Unexpected failing examples:
> /Users/nathanneeteson/Projects/active_development/pyvista/examples/02-plot/movie.py failed leaving traceback:
> Traceback (most recent call last):
>   File "/Users/nathanneeteson/Projects/active_development/pyvista/examples/02-plot/movie.py", line 37, in <module>
>     plotter.write_frame()  # write initial data
>   File "/Users/nathanneeteson/Projects/active_development/pyvista/pyvista/plotting/plotting.py", line 3238, in write_frame
>     self.mwriter.append_data(self.image)
>   File "/Users/nathanneeteson/opt/anaconda3/envs/pyvista-dev/lib/python3.7/site-packages/imageio/core/format.py", line 477, in append_data
>     self._checkClosed()
>   File "/Users/nathanneeteson/opt/anaconda3/envs/pyvista-dev/lib/python3.7/site-packages/imageio/core/format.py", line 269, in _checkClosed
>     raise RuntimeError(msg)
> RuntimeError: I/O operation on closed Writer.
> 
> 
> /Users/nathanneeteson/Projects/active_development/pyvista/examples/02-plot/isovalue.py failed leaving traceback:
> Traceback (most recent call last):
>   File "/Users/nathanneeteson/Projects/active_development/pyvista/examples/02-plot/isovalue.py", line 63, in <module>
>     plotter.write_frame()  # Write this frame
>   File "/Users/nathanneeteson/Projects/active_development/pyvista/pyvista/plotting/plotting.py", line 3238, in write_frame
>     self.mwriter.append_data(self.image)
>   File "/Users/nathanneeteson/opt/anaconda3/envs/pyvista-dev/lib/python3.7/site-packages/imageio/core/format.py", line 477, in append_data
>     self._checkClosed()
>   File "/Users/nathanneeteson/opt/anaconda3/envs/pyvista-dev/lib/python3.7/site-packages/imageio/core/format.py", line 269, in _checkClosed
>     raise RuntimeError(msg)
> RuntimeError: I/O operation on closed Writer.
> 
> 
> /Users/nathanneeteson/Projects/active_development/pyvista/examples/02-plot/chart_overlays.py failed leaving traceback:
> Traceback (most recent call last):
>   File "/Users/nathanneeteson/Projects/active_development/pyvista/examples/02-plot/chart_overlays.py", line 68, in <module>
>     event_type='always')
>   File "/Users/nathanneeteson/Projects/active_development/pyvista/pyvista/plotting/widgets.py", line 1012, in add_slider_widget
>     slider_widget.SetInteractor(self.iren.interactor)
> AttributeError: 'NoneType' object has no attribute 'interactor'
> 
> 
> -------------------------------------------------------------------------------
> make: *** [doctest] Error 2

Running 'make html -b linkcheck' in /doc:

> build finished with problems, 1 warning.
> 
> Sphinx-Gallery successfully executed 0 out of 0 files subselected by:
> 
>     gallery_conf["filename_pattern"] = '\\.py'
>     gallery_conf["ignore_pattern"]   = '__init__\\.py'
> 
> after excluding 121 files that had previously been run (based on MD5).
> 
> make: *** [linkcheck] Error 1

It doesn't seem to me like my changes would have caused these errors. Possibly I am missing some dependencies that weren't automatically installed when I used pip to install pyvista locally?

Should I submit a PR anyways or is there someting I need to do / check to resolve these errors first?

**Comment by banesullivan** [comment]
Go ahead and submit a PR! I wouldn't be too worried about those issues while building the docs. I suspect an offscreen setting is failing to get set.

The CI tests should pick up on any issues shall they arise
