### ISSUE TITLE
EGL not detected

### ISSUE THREAD

**Issue by christianbrugger** [pyvista/pyvista#2142]
**Describe the bug, what's wrong, and what you expect:**

I am trying to make pyvista work in headless mode with GPU acceleration in a Docker container. I am following the [documentation](https://docs.pyvista.org/extras/docker.html), but EGL is not detected and the program segfaults.

Am I missing a step?

**How to reproduce the above**

Using the official pyvista [jupyter Dockerfile](https://github.com/pyvista/pyvista/blob/main/docker/jupyter.Dockerfile) and the modifications described in the docs [about docker](https://docs.pyvista.org/extras/docker.html) and [building VTK](https://docs.pyvista.org/extras/building_vtk.html), I created the following Dockerfile. I named it `test.Dockerfile`:
```dockerfile
FROM ghcr.io/pyvista/pyvista:latest

USER root
RUN apt-get update \
 && apt-get install  -yq --no-install-recommends \
    libgl1-mesa-dev \
    libegl1-mesa-dev \
 && apt-get clean && rm -rf /var/lib/apt/lists/*
USER jovyan

RUN wget https://github.com/pyvista/pyvista/releases/download/0.31.0/vtk-egl-9.0.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl \
 && pip install ./vtk-egl-9.0.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl  --force-reinstall
```

I then build the docker image in the standard way:
```bash
docker build -t test-pyvista -f test.Dockerfile .
```

Start up a new container:
```bash
docker run --gpus all --tty -it --rm --entrypoint=/bin/bash test-pyvista
```

Run the following command:
```bash
python3 -c "import pyvista; pl = pyvista.Plotter();  print(pl.ren_win.ReportCapabilities())"
```

This results in:
```text
/opt/conda/lib/python3.9/site-packages/pyvista/plotting/plotting.py:122: UserWarning: 
This system does not appear to be running an xserver.
PyVista will likely segfault when rendering.

Try starting a virtual frame buffer with xvfb, or using
  ``pyvista.start_xvfb()``

  warnings.warn('\n'
display id not set
```

As you can see pyvista seems to try to use the xserver and crashes. I except it to run headless using EGL as described in the docs.

**Screenshots**

![image](https://user-images.githubusercontent.com/235346/152667954-ad9b9055-1d2d-4b7d-b378-dc0a641914c1.png)

-------

**System Information:**

 Please run the following code wherever you are experiencing the bug and paste the output below. This report helps us track down bugs and it is critical to addressing your bug:

```py
# Get system info
import pyvista as pv
print(pv.Report())
```

```
In [1]: import pyvista as pv
   ...: print(pv.Report())
/opt/conda/lib/python3.9/site-packages/pyvista/plotting/plotting.py:122: UserWarning: 
This system does not appear to be running an xserver.
PyVista will likely segfault when rendering.

Try starting a virtual frame buffer with xvfb, or using
  ``pyvista.start_xvfb()``

  warnings.warn('\n'
2022-02-06 04:39:50.225 (   0.249s) [        10BA9740]vtkXOpenGLRenderWindow.:448    ERR| vtkXOpenGLRenderWindow (0x5567b4435180): bad X server connection. DISPLAY=
ERROR:root:bad X server connection. DISPLAY=
Aborted (core dumped)
```

System info in docker:
```
Python       3.9.7
pyvista      0.33.2
vtk          vtk-egl 9.0.1
libegl       1.3.2-1
libegl-mesa  21.0.3
```

System info of the host:
```
Ubuntu          21.10
Kernel          5.13.0-28-generic
Docker version  20.10.7
nvidia driver   495
nvidia docker   2.9.0-1
GPU             RTX 3060 mobile
```

Here is what `nvidia-smi` prints within the docker container:
```text
Fri Feb  4 03:12:13 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.46       Driver Version: 495.46       CUDA Version: 11.5     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
| N/A   48C    P0    22W /  N/A |    622MiB /  5938MiB |      4%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```

**Comment by christianbrugger** [comment]
**How to reproduce the above**

I made a way to reproduce the above using the [jupyter Dockerfile ](https://github.com/pyvista/pyvista/blob/main/docker/jupyter.Dockerfile) and the [modifications described in the docs](https://docs.pyvista.org/extras/docker.html).


Create the file `test.Dockerfile`:
```dockerfile
FROM ghcr.io/pyvista/pyvista:latest

USER root
RUN apt-get update \
 && apt-get install  -yq --no-install-recommends \
    libgl1-mesa-dev \
    libegl1-mesa-dev \
 && apt-get clean && rm -rf /var/lib/apt/lists/*
USER jovyan

RUN wget https://github.com/pyvista/pyvista/releases/download/0.31.0/vtk-egl-9.0.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl \
 && pip install ./vtk-egl-9.0.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl  --force-reinstall
```

Build the dockefile:
```bash
docker build -t test-pyvista -f test.Dockerfile .
```

Start up a new container:
```bash
docker run --gpus all --tty -it --rm --entrypoint=/bin/bash test-pyvista
```

Run the following command:
```bash
python3 -c "import pyvista; pl = pyvista.Plotter();  print(pl.ren_win.ReportCapabilities())"
```

This results in:
```text
/opt/conda/lib/python3.9/site-packages/pyvista/plotting/plotting.py:122: UserWarning: 
This system does not appear to be running an xserver.
PyVista will likely segfault when rendering.

Try starting a virtual frame buffer with xvfb, or using
  ``pyvista.start_xvfb()``

  warnings.warn('\n'
display id not set
```

Here is what `nvidia-smi` prints:
```text
Fri Feb  4 03:12:13 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.46       Driver Version: 495.46       CUDA Version: 11.5     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
| N/A   48C    P0    22W /  N/A |    622MiB /  5938MiB |      4%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```

**Comment by christianbrugger** [comment]
I have  now rewritten the bug report using a reproducible example. Can someone maybe look into this? Am I missing a simple step?

**Comment by christianbrugger** [comment]
I got it working by compiling VTK by myself with the custom flags below. It seems like the pre-packaged wheels do fall back to OpenGL. After the issue with VTK was solved I had to install the NVIDIA driver, as also written here, in the docker image, otherwise it would fall back to the Mesa software renderer. With the driver I was then able to do off-screen GPU accelerated rendering. Here are the flags I used:

```
RUN apt-get update \
 && apt-get install -y \
	ninja-build \
	cmake \
	libegl1-mesa-dev \
	python3-dev \
 && rm -rf /var/lib/apt/lists/*
RUN cd / \
 && git clone https://github.com/Kitware/VTK \
 && mkdir VTK/build \
 && cd VTK/build \
 && git checkout v9.1.0
RUN cd /VTK/build \
 && cmake -GNinja \
      -DCMAKE_BUILD_TYPE=Release \
      -DVTK_BUILD_TESTING=OFF \
      -DVTK_BUILD_DOCUMENTATION=OFF \
      -DVTK_BUILD_EXAMPLES=OFF \
      -DVTK_MODULE_ENABLE_VTK_PythonInterpreter:STRING=NO \
      -DVTK_WHEEL_BUILD=ON \
      -DVTK_PYTHON_VERSION=3 \
      -DVTK_WRAP_PYTHON=ON \
      -DVTK_OPENGL_HAS_EGL:BOOL=ON \
      -DVTK_USE_X:BOOL=OFF \
      -DVTK_USE_COCOA:BOOL=OFF \
      -DVTK_DEFAULT_RENDER_WINDOW_HEADLESS:BOOL=ON \
      -DPython3_EXECUTABLE=/usr/bin/python3 ../ \
 && ninja
RUN cd /VTK/build \
 && python3 -m pip install wheel \
 && python3 setup.py bdist_wheel \
 && pip install dist/vtk-*.whl
```

**Comment by christianbrugger** [comment]
Maybe someone looking into this could update the Documentation, or fix the egl vtk compilation, if needed.

**Comment by akaszynski** [comment]
> I got it working by compiling VTK by myself with the custom flags below. It seems like the pre-packaged wheels do fall back to OpenGL. After the issue with VTK was solved I had to install the NVIDIA driver, as also written here, in the docker image, otherwise it would fall back to the Mesa software renderer. With the driver I was then able to do off-screen GPU accelerated rendering.

Nice work! I'm going to open a PR with this shortly.

**Comment by banesullivan** [comment]
I recently needed to create a Docker image with GPU access and documented my process here: https://github.com/banesullivan/vtk-cmake/tree/main/nvidia-docker

Seems things are a bit easier these days with improvements to VTK's build and the docker container toolkit

**Comment by josephko91** [comment]
Is there an updated version of either a Dockerfile or Docker image with GPU access? I tried to follow the link you provided @banesullivan but I'm getting a "404 - page not found" error. This would be a really helpful addition to the PyVista documentation in the Docker section because when I use the latest Jupyter compatible Docker image on an HPC which uses the vtk-osmesa wheel, the rendering is painfully slow because it can only use CPU.

**Comment by banesullivan** [comment]
@josephko91, I condensed the build to a single Dockerfile in that repository and pre-build a GPU image here now: https://github.com/banesullivan/vtk-cmake/pkgs/container/pyvista-gpu

**Comment by josephko91** [comment]
Thanks @banesullivan!!! Amazing. I am facing an issue trying to use this pre-built image on an HPC environment. I built a SIF file by directly pulling from the ghcr address you provided. However, when I try to run the image using apptainer on the HPC environment, I get the following errors: 
```
INFO:    fuse2fs not found, will not be able to mount EXT3 filesystems
INFO:    underlay of /usr/bin/nvidia-smi required more than 50 (255) bind mounts
```
I'm assuming this is something that might have to be resolved with my HPC admin. But I wanted to post it here as well just in case. 

I did have a follow up question for you @banesullivan. Do you happen to have a **pre-built image that also includes xarray and pyvista-xarray**? I tried building a custom docker image using one of the pre-built pyvista base images and then adding RUN pip install statements for xarray/pyvista-xarray, but I keep getting errors related to vtk. I've tried different things in the Dockerfile .e.g, uninstalling vtk and vtk-osmesa and then explicitly installing vtk-osmesa only (or vtk-egl). But I keep running into errors related to vtk modules. I noticed when you pip install pyvista-xarray, it installs vtk and I'm wondering if there's some weird conflict that happens with the vtk paths, even when I try to explicitly uninstall and reinstall vtk? 

Anyways, a pre-built image including xarray and pyvista-xarray would be super useful if you have on hand....Or tips on how to get this to work in a container on an HPC environment...

Thanks!

**Comment by jourdain** [comment]
vtk, vtk-egl, vtk-osmesa are actually the exact same package but built with different system dependencies. 
PyPI will consider them different (different names) but they write in the same spot... 

Since PyVista properly describe a dependency to vtk, when you want to leverage egl or osmesa, you need to do the following in that order (and not in parallel)

1. Install pyvista
2. remove vtk
3. install vtk-osmesa or vtk-egl

Sometime in my automated script I just have:
`pip uninstall -y vtk vtk-egl vtk-osmesa && pip install -y vtk-egl` 

Otherwise for singularity/apptainer: With docker to get access to GPU and have all the driver installed, we need to start from an nvidia image, which (I think) is not needed when using singularity/apptainer. So you should be able to create a simpler image and just redo what Bane is doing for the setup step to get it to work within a sif image. 

HTH

**Comment by josephko91** [comment]
@jourdain When I try `pip install vtk-egl` I get an error:

> ERROR: Could not find a version that satisfies the requirement vtk-egl (from versions: none)
> ERROR: No matching distribution found for vtk-egl

**Comment by josephko91** [comment]
Nevermind. I answered my own question, but for the record in case anyone else finds this helpful. 
`pip install --no-cache-dir --extra-index-url https://wheels.vtk.org vtk-egl`

**Comment by josephko91** [comment]
I'm still having trouble getting the interactive visualizations to work properly in a notebook. I've posted more details here in this related issue: https://github.com/pyvista/pyvista/issues/5848
