### ISSUE TITLE
imageio.plugins.ffmpeg.download() not always working on Travis

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#215]
We need the `ffmpeg` plugin for `imageio` when testing on Travis - downloading this plugin  on Travis from `python -c "import imageio; imageio.plugins.ffmpeg.download()"` periodically fails - usually I can simply restart the build and it'll work but this is not sustainable.

Does anyone know of the proper/a better way to download the plugin?

```bash
$ python -c "import imageio; imageio.plugins.ffmpeg.download()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/imageio/plugins/ffmpeg.py", line 79, in download
    get_remote_file(fname=fname, directory=directory, force_download=force_download)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/imageio/core/fetching.py", line 127, in get_remote_file
    _fetch_file(url, filename)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/imageio/core/fetching.py", line 189, in _fetch_file
    % os.path.basename(file_name)
OSError: Unable to download 'ffmpeg-linux64-v3.3.1'. Perhaps there is a no internet connection? If there is, please report this problem.
Imageio: 'ffmpeg-linux64-v3.3.1' was not found on your computer; downloading it now.
Error while fetching file: The read operation timed out.
Error while fetching file: The read operation timed out.
Error while fetching file: The read operation timed out.
Error while fetching file: The read operation timed out.
Imageio: 'ffmpeg-linux64-v3.3.1' was not found on your computer; downloading it now.
Error while fetching file: The read operation timed out.
Error while fetching file: The read operation timed out.
Error while fetching file: The read operation timed out.
Error while fetching file: The read operation timed out.
Imageio: 'ffmpeg-linux64-v3.3.1' was not found on your computer; downloading it now.
Error while fetching file: The read operation timed out.
Error while fetching file: The read operation timed out.
Error while fetching file: The read operation timed out.
Error while fetching file: The read operation timed out.
The command "python -c "import imageio; imageio.plugins.ffmpeg.download()"" failed and exited with 1 during .
```

**Comment by banesullivan** [comment]
Note the failed built at https://travis-ci.org/pyvista/pyvista/builds/533488928

Normally I just restart these but I'm getting sick of doing this

**Comment by banesullivan** [comment]
I'm guessing this is a network issue with Travis since we also experience timeouts when fetching the example datasets on these same builds

**Comment by banesullivan** [comment]
7d5668f did not resolve this 😞 

Worked locally for me... not sure how to fix this

**Comment by akaszynski** [comment]
We could try to load ffmpeg at the start of the test script and if it fails, skip the tests testing for ffmpeg.  That way it will test when it does succeed and let us know that it's skipped.

**Comment by GuillaumeFavelier** [comment]
I tried [this solution](https://github.com/epic-kitchens/epic-lib/issues/69) in #230. I really don't know how stable it is though.

**Comment by banesullivan** [comment]
Setting the `imageio` version seems to have done the trick, thanks @GuillaumeFavelier!

> I really don't know how stable it is though.

Yeah, I'd rather not have a single version set - since it's only on Travis, this should be fine for now

**Comment by banesullivan** [comment]
I spoke too soon! Builds are still failing 😞

**Comment by banesullivan** [comment]
Going to try @akaszynski's suggestion ^^ https://github.com/pyvista/pyvista/issues/215#issuecomment-495130650

**Comment by banesullivan** [comment]
5cb928a uses @akaszynski's https://github.com/pyvista/pyvista/issues/215#issuecomment-495130650 to only test the movie writers if ffmpeg is available
