### ISSUE TITLE
Syntax error in `RenderWindowInteractor._toggle_context_style`

### ISSUE THREAD

**Issue by Onandon11** [pyvista/pyvista#2160]
**Describe the bug, what's wrong, and what you expect:**

When using `Chart2D` in a multi window plot (eg. with `shape=(2, 1)`). An error is raised at line 179 in `render_window_interactor.py` when trying to activate the `chart` by right mouse button press on the chart. I think it should be `_charts` instead of `charts` (like at line 176)?
https://github.com/pyvista/pyvista/blob/1d0a487eaa66ed5b78715acdeebe2193de459ee7/pyvista/plotting/render_window_interactor.py#L171-L179

-----

**To Reproduce**

Please include a code snippet to reproduce the bug in the block below:

```py
import pyvista
import numpy as np

chart = pyvista.Chart2D()

x = np.random.randn(100)
y = np.random.randn(100)

chart.scatter(x, y, style="s", size=2)

pl = pyvista.Plotter(shape=(2, 1))
pl.background_color = "w"
pl.add_chart(chart)
pl.show()

```

-----

**System Information:**
 Please run the following code wherever you are experiencing the bug and paste the output below. This report helps us track down bugs and it is critical to addressing your bug:

```py
# Get system info
import pyvista as pv
print(pv.Report())
```

```txt
--------------------------------------------------------------------------------
  Date: Wed Feb 09 09:32:49 2022 W. Europe Standard Time

                OS : Windows
            CPU(s) : 8
           Machine : AMD64
      Architecture : 64bit
               RAM : 31.9 GiB
       Environment : Python
        GPU Vendor : NVIDIA Corporation
      GPU Renderer : Quadro M1000M/PCIe/SSE2
       GPU Version : 4.5.0 NVIDIA 441.66

  Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit
  (AMD64)]

           pyvista : 0.33.2
               vtk : 9.1.0
             numpy : 1.22.1
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.7
        matplotlib : 3.4.3
         pyvistaqt : 0.7.0
             PyQt5 : 5.15.4
           IPython : 7.29.0
             scipy : 1.7.3
            meshio : 4.4.6
--------------------------------------------------------------------------------


```

**Comment by tkoyama010** [comment]
@Onandon11 Thanks for reporting this.
