### ISSUE TITLE
broken link to contributing guide in README.RST

### ISSUE THREAD

**Issue by njneeteson** [pyvista/pyvista#2169]
After #2110, the link to the contributing guide in the main README.RST is broken:

> We absolutely welcome contributions and we hope that our [Contributing Guide](https://github.com/pyvista/pyvista/blob/main/CONTRIBUTING.md) will facilitate your ability to make PyVista better. PyVista is mostly maintained on a volunteer basis and thus we need to foster a community that can support user questions and develop new features to make this software a useful tool for all users while encouraging every member of the commutinity to share their ideas. To learn more about contributing to PyVista, please see the [Contributing Guide](https://github.com/pyvista/pyvista/blob/main/CONTRIBUTING.md) and our [Code of Conduct](https://github.com/pyvista/pyvista/blob/main/CODE_OF_CONDUCT.md).

https://github.com/pyvista/pyvista/blob/main/CONTRIBUTING.md

Should go here:

https://github.com/pyvista/pyvista/blob/main/CONTRIBUTING.rst

**Comment by tkoyama010** [comment]
@njneeteson Good catch. Thanks.
