### ISSUE TITLE
Functionality to attach callbacks to mouse clicks in the window

### ISSUE THREAD

**Issue by dstansby** [pyvista/pyvista#2194]
As far as I can tell there is no way to attach a custom callback to a mouse event/click within a pyvista plotting window. It would be great if this could be implemented. I imagine it would be similar to `Plotter.enable_point_picking()`, but pass the display coordinates of the mouse click to the callback.

**Comment by banesullivan** [comment]
`track_click_position` is what you're after: https://docs.pyvista.org/api/plotting/_autosummary/pyvista.Plotter.track_click_position.html

```py
import pyvista as pv

p = pv.Plotter(notebook=0)
p.add_mesh(pv.Sphere())

def callback(pos):
    p.add_text(f'{pos}', name='pos')
# Tracks right clicks
p.track_click_position(callback=callback)
p.show()
```
