### ISSUE TITLE
Image / UniformGrid Padding

### ISSUE THREAD

**Issue by njneeteson** [pyvista/pyvista#2201]
VTK has three image padding filters that all derive from the same image pad superclass:

https://vtk.org/doc/nightly/html/classvtkImageConstantPad.html
https://vtk.org/doc/nightly/html/classvtkImageMirrorPad.html
https://vtk.org/doc/nightly/html/classvtkImageWrapPad.html

The underlying VTK objects are pretty simple to work with. You set a constant value (if applicable), you get the "whole extents" of your input image and you set how much to pad by setting an output "whole extent" that is smaller/larger on the min/max for each dimension.

I propose to create a new method for uniform_grid datasets called "image_pad" which takes a "mode" parameter (to choose from "constant", "mirror", or "wrap"), a "value" parameter to set the pad value in constant mode, and a "pad size" parameter that could be either a single int, a length 3 tuple of ints, or a length 6 tuple of ints, to control how much to pad on the various sides of the image.

I don't work much with non-3D image data but I believe it could be 1D/2D compatible if you set the pad width to 0 in the unused dimension(s).

**Comment by RichardScottOZ** [comment]
Sounds good.
