### ISSUE TITLE
missing `f` of f-string formatting

### ISSUE THREAD

**Issue by phylsix** [pyvista/pyvista#2222]
An `f` seems to be missing for the below error message formatting.

https://github.com/pyvista/pyvista/blob/135fedcd637ae431985955119eff3f82af4074f4/pyvista/plotting/tools.py#L587

**Comment by banesullivan** [comment]
Thanks for pointing this out! I think this was removed during our recent reformatting of the codebase as flake8 did not detect this as a string needing the `f` prefix
