### ISSUE TITLE
Using `_get_output` in wrapping alg output

### ISSUE THREAD

**Issue by tkoyama010** [pyvista/pyvista#2226]
### Discussed in https://github.com/pyvista/pyvista/discussions/2225

<div type='discussions-op-text'>

<sup>Originally posted by **tkoyama010** February 17, 2022</sup>
I found that some `pyvista.wrap(alg.GetOutput())` is still left in the source code. This can be fixed to `_get_output(alg)`.
https://github.com/pyvista/pyvista/search?q=pyvista.wrap%28alg.GetOutput%28%29%29</div>

**Comment by banesullivan** [comment]
As a random note, future version of VTK will not require `pyvista.wrap(alg.GetOutput())` when using the changes from https://gitlab.kitware.com/vtk/vtk/-/merge_requests/8886 which make it possible to overwrite a VTK class with a Python subclass. We would simply do:

```py
import vtk, pyvista
vtk.vtkPolyData.overwrite(pyvista.PolyData)
o = vtk.vtkPolyData() # o is actually an instace of pyvista.PolyData
```
