### ISSUE TITLE
Grids defined with large origin values loose precision

### ISSUE THREAD

**Issue by madala70** [pyvista/pyvista#2236]
Context:  Mining operations often work with large Cartesian coordinate magnitudes for Easting/Northing (aka X,Y) and this applies to gridded models.   Following example demonstrates that there is a loss of precision (or truncation) in grid origin coordinates when writing/reading a Uniform grid.

**Grid creation**
```
import pyvista as pv
ugrid = pv.UniformGrid()
ugrid.origin = (615850.0, 5846925.0, 758)
ugrid.spacing = (5, 5, 3.5)
ugrid.dimensions = (4, 5, 3)
ugrid.cell_data['Data'] = np.arange(np.prod([v-1 for v in ugrid.dimensions]))
ugrid.save('uGridTest.vtk')
```

 "Pretty" formatted output of grid properties (to work around the truncation of numbers with the {:.3e} default by substituting {:.2f})

`print(pfmt(ugrid))`

```txt
_UniformGrid_ _(0x1fc244e49a8)_
  N Cells:	24
  N Points:	60
  X Bounds:	615850.00, 615865.00, 
  Y Bounds:	5846925.00, 5846945.00, 
  Z Bounds:	758.00, 765.00, 
  Dimensions:	4, 5, 3
  Spacing:	5.00, 5.00, 3.50, 
  N Arrays:	1
```

 **Read the Grid**
```
vgrid = pv.read('uGridTest.vtk')
print(pfmt(vgrid))
```
```txt
_UniformGrid_ _(0x1fc244e4dc8)_
  N Cells:	24
  N Points:	60
  X Bounds:	615850.00, 615865.00, 
  Y Bounds:	5846930.00, 5846950.00, 
  Z Bounds:	758.00, 765.00, 
  Dimensions:	4, 5, 3
  Spacing:	5.00, 5.00, 3.50, 
  N Arrays:	1
```
Y bounds have been truncated/rounded

```
vgrid == ugrid
ugrid.bounds
vgrid.bounds
[v-u for v,u in [[vgrid.bounds[i], ugrid.bounds[i]] for i in range(6)]]
```
```txt
False

(615850.0, 615865.0, 5846925.0, 5846945.0, 758.0, 765.0)

(615850.0, 615865.0, 5846930.0, 5846950.0, 758.0, 765.0)

[0.0, 0.0, 5.0, 5.0, 0.0, 0.0]
```

It doesn't appear that its possible to apply a translation component (offset) to help preserve precision as part of the grid data so that is an issue when visualising the grid with other tools eg ParaView.   

-----

**System Information:**
```txt
--------------------------------------------------------------------------------
  Date: Fri Feb 18 14:21:42 2022 E. Australia Standard Time

                OS : Windows
            CPU(s) : 8
           Machine : AMD64
      Architecture : 64bit
               RAM : 15.9 GB
       Environment : Jupyter
        GPU Vendor : NVIDIA Corporation
      GPU Renderer : Quadro M1200/PCIe/SSE2
       GPU Version : 4.5.0 NVIDIA 472.39

  Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64
  bit (AMD64)]

           pyvista : 0.33.2
               vtk : 9.1.0
             numpy : 1.21.4
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.6
        matplotlib : 3.5.0
             PyQt5 : Version unknown
           IPython : 7.31.1
          colorcet : 1.0.0
             scipy : 1.6.3
        itkwidgets : 0.32.0
              tqdm : 4.61.0
            meshio : 5.3.0

```

**Comment by RichardScottOZ** [comment]
Certainly have not seen in the code yet where this might be happening.

**Comment by madala70** [comment]
Richard

Further investigation (& code downloads) Im sure pyvista uses vtk as the reader & writer of files.  This is demonstrated in the following case whilst I was investigating how to get a vtk v4.2 format file instead of the default v5.1 (though after the fact it doesn't make any difference for a Structured Points Dataset) 

Source test file: Subset_vox_bin.vtk  
`file = 'Subset_vox_bin.vtk'`

Read & write via pyvista (0.33.2) -> Subset_pyvista_bin.vtk
`grid = pv.read(file)`
`grid.save('Subset_pyvista_bin.vtk', binary=True)`

Read & write using vtk (9.1.0) -> 'Subset_vtk_bin_v42.vtk'
`reader = vtk.vtkStructuredPointsReader()`
`reader.SetFileName(file)`
`reader.Update()`
`data = reader.GetOutput()`
` `
`writer = vtk.vtkStructuredPointsWriter()`
`writer.SetFileName('Subset_vtk_bin_v42.vtk') `
`writer.SetFileTypeToBinary()`
`writer.SetFileVersion(42)`
`writer.SetInputData(data)`
`writer.Write()`

#Comparison of the contents of the three files using WinMerge (launched from jupyter notebook) 
`!cmd /C C:\Win64App\WinMerge\WinMergeU.exe /t Text Subset_vox_bin.vtk    Subset_pyvista_bin.vtk     Subset_vtk_bin_v42.vtk`

![WinMerge_comp](https://user-images.githubusercontent.com/99940068/155824195-e09a1069-b856-4610-9a6d-d8a2075c6b8b.PNG)

I should have twigged that vtk was the writer based on 2nd line comment in the output files.  So it seems the issue of loss of precision of large origin values is not a bug of pyvista but a very undesirable feature of vtk and I'm struggling to find where in the vtk code base where this occurs  as Im not C++ familiar.  

Do I close this issue or allow the repo masters  do so?

**Comment by RichardScottOZ** [comment]
You can close it if you want.

**Comment by RichardScottOZ** [comment]
[[<html>
<body>
<h2 class="memtitle" style="transition: text-shadow 0.5s linear 0s; margin-right: 15px; padding: 8px; border-top: 1px solid rgb(168, 184, 217); border-left: 1px solid rgb(168, 184, 217); border-right: 1px solid rgb(168, 184, 217); border-top-right-radius: 4px; border-top-left-radius: 4px; margin-bottom: -1px; background-image: url(&quot;nav_f.png&quot;); background-repeat: repeat-x; background-color: rgb(226, 232, 242); line-height: 1.25; font-weight: 300; float: left;">WriteCoordinates()</h2><div class="memitem" style="font: 400 14px / 22px Roboto, sans-serif; padding: 0px; margin-bottom: 10px; margin-right: 5px; transition: box-shadow 0.5s linear 0s; width: 1883px; display: table !important;"><div class="memproto" style="font: bold 14px / 22px Roboto, sans-serif; border-top: 1px solid rgb(168, 184, 217); border-left: 1px solid rgb(168, 184, 217); border-right: 1px solid rgb(168, 184, 217); padding: 6px 0px; color: rgb(37, 53, 85); text-shadow: rgba(255, 255, 255, 0.9) 0px 1px 1px; background-color: rgb(223, 229, 241); box-shadow: rgba(0, 0, 0, 0.15) 5px 5px 5px; border-top-right-radius: 4px;"><table class="memname" style="font: 400 14px / 22px Roboto, sans-serif; margin-left: 6px;"><tbody><tr><td class="memname" style="font-weight: 400; margin-left: 6px; vertical-align: bottom;">int vtkDataWriter::WriteCoordinates</td><td style="vertical-align: bottom;">(</td><td class="paramtype" style="white-space: nowrap; vertical-align: bottom;">ostream * </td><td class="paramname" style="color: rgb(96, 32, 32); white-space: nowrap; vertical-align: bottom;"><em style="font-style: normal;">fp</em>,</td></tr><tr><td class="paramkey" style="text-align: right; vertical-align: bottom;"></td><td style="vertical-align: bottom;"></td><td class="paramtype" style="white-space: nowrap; vertical-align: bottom;"><a class="el" href="https://vtk.org/doc/nightly/html/classvtkDataArray.html" style="color: rgb(61, 87, 140); font-weight: bold; text-decoration: none;">vtkDataArray</a><span> </span>* </td><td class="paramname" style="color: rgb(96, 32, 32); white-space: nowrap; vertical-align: bottom;"><em style="font-style: normal;">coords</em>,</td></tr><tr><td class="paramkey" style="text-align: right; vertical-align: bottom;"></td><td style="vertical-align: bottom;"></td><td class="paramtype" style="white-space: nowrap; vertical-align: bottom;">int </td><td class="paramname" style="color: rgb(96, 32, 32); white-space: nowrap; vertical-align: bottom;"><em style="font-style: normal;">axes</em> </td></tr><tr><td style="vertical-align: bottom; color: rgb(37, 53, 85); font-family: Roboto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(223, 229, 241); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"></td><td style="vertical-align: bottom; color: rgb(37, 53, 85); font-family: Roboto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(223, 229, 241); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">)</td><td style="vertical-align: bottom; color: rgb(37, 53, 85); font-family: Roboto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(223, 229, 241); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"></td><br class="Apple-interchange-newline">
</body>
</html>WriteCoordinates()
int vtkDataWriter::WriteCoordinates	(	ostream * 	fp,
[vtkDataArray](https://vtk.org/doc/nightly/html/classvtkDataArray.html) * 	coords,
int 	axes 
)](https://vtk.org/doc/nightly/html/classvtkDataWriter.html#a72277fa7951dad76fbd7e61743b19d8e)](https://vtk.org/doc/nightly/html/classvtkDataWriter.html#a72277fa7951dad76fbd7e61743b19d8e)
