### ISSUE TITLE
Extract subset from the grid based on celltype

### ISSUE THREAD

**Issue by SunilAnandatheertha** [pyvista/pyvista#2246]
A method to extract a subset of a grid based on celltype would be great! Tried many places, could not find such a thing. I am not sure if its there. Here is what I have been doing to get around, but now[*not] exactly working in the way its supposed to:

So, I use pygmsh for meshing and get below mesh visualization from pyvista:
![image](https://user-images.githubusercontent.com/99408633/154852110-bbd20469-ef4a-449d-93df-0ff90ca7e15b.png)

CODE USED IS:
```
grid = pv.read("sunil.vtk")
pv.global_theme.background='maroon'
plotter = pv.Plotter(window_size = (900, 600))
_ = plotter.add_points(np.array([0,0,0]),
                        render_points_as_spheres = True,
                        point_size = 25)
_ = plotter.add_points(grid.points,
                        render_points_as_spheres = True,
                        point_size = 2)
#_ = plotter.add_bounding_box(line_width=2, color='black')
_ = plotter.add_mesh(grid,
                      show_edges = True,
                      edge_color = 'black',
                      line_width = 0.5,
                      render_points_as_spheres = False,
                      point_size = 1,
                      style = 'wireframe')
plotter.view_xy()
plotter.camera.zoom(1.0)
plotter.show()
```
I TRIED TO EXTRACT IT MANUALLY USING BELOW CODE:

```
CELLDATA = grid.cells
# vtk.VTK_TRIANGLE
triggerID = 3
TRIANGLES = np.array([[.0,.0,.0]])

actualcount = 0
increment = int(CELLDATA[0])
for count in range(len(CELLDATA)):
    if CELLDATA[actualcount] == triggerID:
        TRIANGLES = np.append(TRIANGLES,
                              np.array(CELLDATA[actualcount+1 : actualcount+1+increment])[np.newaxis],
                              axis = 0)
    actualcount += increment+1
    if actualcount < len(CELLDATA)-1:
        increment = CELLDATA[actualcount]
    else: 
        break
TRIANGLES = np.delete(TRIANGLES, 0, 0)
```

BUT SOMEHOW, MANY TRINAGLES ARE ILL-FORMED (PLOTTING USING MATPLOTLIB THOUGH): 

![image](https://user-images.githubusercontent.com/99408633/154852359-f9cf8b1c-7738-4224-bc80-51fe24e9e0a7.png)

Code used is below:

```
fig, ax1 = plt.subplots(dpi = 400)
for count in range(np.shape(TRIANGLES)[0]):
    x = [grid.points[int(TRIANGLES[count][0])][0], grid.points[int(TRIANGLES[count][1])][0], grid.points[int(TRIANGLES[count][2])][0]]
    y = [grid.points[int(TRIANGLES[count][1])][1], grid.points[int(TRIANGLES[count][2])][1], grid.points[int(TRIANGLES[count][2])][1]]
    ax1.fill(x, y, facecolor = 'none', edgecolor = 'black')
plt.show()
```

Not sure if this is due to clockwise or anti-clockwise data arrangement

A method to extract a sub-set of the grid would be very useful. Maybe added as an additional argument in 
[extract_subset](https://docs.pyvista.org/api/core/_autosummary/pyvista.StructuredGrid.extract_subset.html)

Maybe, already there in VTK, may in either of below? (not sure)
[classvtkExtractSelection](https://vtk.org/doc/nightly/html/classvtkExtractSelection.html) or 
[classvtkExtractUnstructuredGrid](https://vtk.org/doc/nightly/html/classvtkExtractUnstructuredGrid.html)

**Comment by whophil** [comment]
Is your goal just to extract triangles from this mesh? How about this?
```python
tri_cells = [i for i in range(grid.n_cells) if grid.cell_n_points(i) == 3]
grid_subset = grid.extract_cells(tri_cells)
```

**Comment by SunilAnandatheertha** [comment]
Thank you for the quick reply. Worked like a charm.
