### ISSUE TITLE
bug in track_click_position callback

### ISSUE THREAD

**Issue by ghazalbangash** [pyvista/pyvista#2253]
Hi there,  I have been having issues with track_click_position and untrack_click_postion. I am using track_click_position twice in my program and and it seems to be stuck in the callback functions of the track_click_position even though I call untrack.Please help me solve this issue

**Comment by ghazalbangash** [comment]
if I am not wrong in :
    def add_observer(self, event, call):
        """Add an observer."""
        call = partial(try_callback, call)
        self._observers[event] = self.interactor.AddObserver(event, call)

the call methods are added but never removed 

I think self.observers has to be cleared properly

**Comment by dcbr** [comment]
I can reproduce it locally (Windows 10, python 3.8) with following script.

```py
import pyvista


def click_event(pos):
    print(pos)


p = pyvista.Plotter()
p.add_mesh(pyvista.Sphere())
p.track_click_position(callback=click_event, side="left")
p.untrack_click_position()
p.show()
```

Clicking in the opened plotting window still calls the `click_event` callback and prints the click location to the console.

**Comment by ghazalbangash** [comment]
@dcbr thats exactly my problem and I want it to stop executing the callback.

**Comment by dcbr** [comment]
I found the problem @ghazalbangash, the fix should be ready in a couple of days :)

**Comment by ghazalbangash** [comment]
@dcbr  Thank you so much
