### ISSUE TITLE
Sphere slice

### ISSUE THREAD

**Issue by liangwang0734** [pyvista/pyvista#2286]
**Describe what feature you would like added.**

Paraview-like slice over a sphere.

With some help, I'm willing to explore by starting from Pyvista's existing (plane) slice [feature](https://github.com/pyvista/pyvista/blob/28914fc2236cd5850f536b151d0ef383855d8519/pyvista/core/filters/data_set.py#L452).

It looks like I will need to define a sphere and use it as the cutter's function?

**Comment by tkoyama010** [comment]
How about using the `sample` method? Please make sure that the Examples meet your needs.
https://docs.pyvista.org/api/core/_autosummary/pyvista.DataSet.sample.html

**Comment by liangwang0734** [comment]
> How about using the `sample` method? Please make sure that the Examples meet your needs. https://docs.pyvista.org/api/core/_autosummary/pyvista.DataSet.sample.html

Thanks @tkoyama010 That works (though it's still different from a slice and one needs to set the sampling resolution).
