### ISSUE TITLE
streamlines using highly nonuniform vector field

### ISSUE THREAD

**Issue by liangwang0734** [pyvista/pyvista#2301]
**Updates**

After I set the `max_time` to `10`, which is the default `Maximum Streamline Length` in Paraview, I can reproduce the Paraview results.

The default value `max_time=None` might not play well with certain data. In my case, the magnitude of the vector field varies greatly. Then, the default length figured out by the following [code](https://github.com/pyvista/pyvista/blob/ef205f48454bb5bef09b2d00e38c9b49ec31eb50/pyvista/core/filters/data_set.py#L3117)  does not work well:

```python
if max_time is None:
    max_velocity = self.get_data_range()[-1]
    max_time = 4.0 * self.GetLength() / max_velocity
```

I'm about to close this issue. But still,  the usage of the parameter `MaximumPropagation` might be improved, like I discussed in my own reply [below](https://github.com/pyvista/pyvista/issues/2301#issuecomment-1060201545).

------------------
**Describe the bug, what's wrong, and what you expect:**

`streamlines` using highly nonuniform vector field do not reproduce Paraview results.

I guess it could just be a parameter issue, but I haven't found the cause.

-----

**To Reproduce**

Please include a code snippet to reproduce the bug in the block below:

Input data (sorry for its nontrivial size ~ 10 MB; please remove the .zip extension which was added to be recognized by github issue system):
[bfield.vti.zip](https://github.com/pyvista/pyvista/files/8193436/bfield.vti.zip)

```py
import pyvista

bfield = pyvista.read('bfield.vti')

bfieldlines = bfield.streamlines(
    pointa=(-23, 0, 0),
    pointb=(-13, 0, 0),
    n_points=100,
    step_unit='cl',
    initial_step_length=0.2,
    min_step_length=0.01,
    max_step_length=0.5,
    max_steps=2000, # tried 20000, no difference
    terminal_speed=1e-12,
    max_error=1e-06,
    max_time=None,
)
plotter = pyvista.Plotter()
plotter.add_mesh(bfieldlines.tube(radius=0.01), color='r')
plotter.add_mesh(pyvista.Sphere(center=(-18,0,0), radius=0.3)) # just for reference
plotter.add_axes()
plotter.camera_position = 'xz'
plotter.show()
```

**Screenshots**
Pyvista results using `streamline` parameters taken from Paraview test:
![demo-pyvista](https://user-images.githubusercontent.com/1000547/156940368-0f3d1622-8a35-4db0-8cd9-5e9792715ac8.png)

Paraview results:
![demo-paraview](https://user-images.githubusercontent.com/1000547/156940329-b2b8e017-e8c7-4e74-8f9e-ab1511fa7270.png)

-----

**System Information:**
 Please run the following code wherever you are experiencing the bug and paste the output below. This report helps us track down bugs and it is critical to addressing your bug:

```py
# Get system info
import pyvista as pv
print(pv.Report())
```
```txt

--------------------------------------------------------------------------------
  Date: Sun Mar 06 15:19:38 2022 EST

                OS : Linux
            CPU(s) : 4
           Machine : x86_64
      Architecture : 64bit
               RAM : 15.5 GiB
       Environment : Jupyter
       File system : ext4
        GPU Vendor : Intel
      GPU Renderer : Mesa Intel(R) HD Graphics 4600 (HSW GT2)
       GPU Version : 4.6 (Core Profile) Mesa 21.3.6

  Python 3.8.12 (default, Oct 12 2021, 13:49:34)  [GCC 7.5.0]

           pyvista : 0.34.dev0
               vtk : 9.0.3
             numpy : 1.21.2
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.11
        matplotlib : 3.5.1
             PyQt5 : 5.9.2
           IPython : 7.31.1
          colorcet : 3.0.0
           cmocean : 2.0
        ipyvtklink : 0.2.2
             scipy : 1.8.0
        itkwidgets : 0.32.1
              tqdm : 4.62.3
            meshio : 5.3.2

  Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904
  for Intel(R) 64 architecture applications

```

**Comment by liangwang0734** [comment]
There seems to be a misunderstanding the `MaximumPropagation` property of `vtkStreamTracer`.

All documents I found so far ([vtk](https://vtk.org/doc/nightly/html/classvtkStreamTracer.html#a70651ab3baacf24081aac3f215111901) and [Paraview](https://github.com/Kitware/paraview-lite/blob/2679ca83dd92b2e6c1739c27babf7b5fa6cedc3c/src/modules/StreamTracer/script.js#L125), indicate that it is the maximum length, not the time.

As a result, it might be more consistent to simply set
```python
        if max_time is None:
            max_time = 4.0 * self.GetLength()
```
for this [code](https://github.com/pyvista/pyvista/blob/ef205f48454bb5bef09b2d00e38c9b49ec31eb50/pyvista/core/filters/data_set.py#L3117).

**Comment by MatthewFlamm** [comment]
> As a result, it might be more consistent to simply set
> 
> ```python
>         if max_time is None:
>             max_time = 4.0 * self.GetLength()
> ```
> 
> for this [code](https://github.com/pyvista/pyvista/blob/ef205f48454bb5bef09b2d00e38c9b49ec31eb50/pyvista/core/filters/data_set.py#L3117), and perhaps rename the argument to `max_length` from `max_time`.

I think we should do this.  This argument causes a lot of confusion.  As you point out, the implementation is also wrong.

The value by default is expressed in cell lengths, so we'd have to have two cases for the default for this parameter.  Maybe we should defer the default to vtk?  Or we could choose the default to be something like `dataset.n_cells/25`.

**Comment by MatthewFlamm** [comment]
The default in vtk is 1.0 for this parameter in either unit:

https://github.com/Kitware/VTK/blob/0e3d0202115be28c521b3116e664250a8c8368c1/Filters/FlowPaths/vtkStreamTracer.cxx#L71

I think it makes more sense to choose a more relevant default.

**Comment by liangwang0734** [comment]
Also, in Pyvista's current code, the following code seems to produce stream lines of physical length `5`:
```python
bfieldlines = bfield.streamlines(
    pointa=(-23, 0, 0),
    pointb=(-13, 0, 0),
    n_points=100,
    step_unit='cl',
    initial_step_length=0.2,
    min_step_length=0.01,
    max_step_length=# 0.5
    max_steps=2000
    terminal_speed=1e-12,
    max_error=1e-06,
    max_time=5, # seem to give arcs of physical length 5
)
```

**Comment by MatthewFlamm** [comment]
> In the Paraview GUI, the value of `"Maximum Streamline Length"` **_displayed_**, seems to be the domain length along the longest dimension. The document says "This property specifies the maximum streamline (i.e., physical arc length), beyond which line integration terminated."
> See [this](https://github.com/Kitware/ParaView/blob/76ae997e64a7ebd5370474cf42bb3ca7a03d30f5/Remoting/Application/Resources/filters_filtersflowpaths.xml#L827).

vtk [doc for vtkStreamTracer](https://vtk.org/doc/nightly/html/classvtkStreamTracer.html#a70651ab3baacf24081aac3f215111901) says:

> Specify the maximum length of a streamline expressed in LENGTH_UNIT.

So I think this may be an imprecise definition in ParaView, but I haven't dug into the vtk code in depth to see if this may be a bug in vtk.

> Also, in Pyvista's current code, the following code seems to produce stream lines of physical length `5`:

This could be a bug in vtk, or it will depend on the ratio of cell length to physical length.  Also will depend on all the other parameters.  It may be useful to simplify the investigation by using a much simpler example like a uniform velocity field in a UniformGrid.

**Comment by banesullivan** [comment]
+1 for the proposed change to `max_length`

IMO, we should try to have the same defaults as ParaView for most filters... especially more complicated ones like `streamlines`

**Comment by liangwang0734** [comment]
The change itself is easy. The default value is perhaps the maximum domain length, as I mentioned earlier.

I'm not sure how wide the impact is, though. Shall `max_time` be kept for backward compatibility (I don't think so as it is incorrect, anyway; and we haven't reached v1.0).

**Comment by MatthewFlamm** [comment]
I'm +1 on making the default the maximum domain length (either in a Cartesian direction or across the diagonal).

Could we deprecate `max_time` and move it to the end of the parameter list?
