### ISSUE TITLE
clip_box behavior is broken

### ISSUE THREAD

**Issue by eino** [pyvista/pyvista#2305]
Hi,

to follow up on the [thread started in Discussions,](https://github.com/pyvista/pyvista/discussions/2191) clip_box behavior is broken, as the clipped part doesn't match the passed box.

-----

**To Reproduce**

```py
import pyvista as pv
from pyvista import examples

mesh = examples.load_airplane()

# Use `pv.Box()` or `pv.Cube()` to create a region of interest
roi = pv.Cube(center=(0.9e3, 0.2e3, mesh.center[2]),
              x_length=500, y_length=500, z_length=500)

extracted = mesh.clip_box(roi, invert=False)

p = pv.Plotter(shape=(1,2))
p.add_mesh(roi, opacity=0.75, color="red")
p.add_mesh(mesh)
p.subplot(0,1)
p.add_mesh(extracted)
p.add_mesh(roi, opacity=0.75, color="red")
p.link_views()
p.view_isometric()
p.show()
```

-----

**Screenshots**
![Screenshot from 2022-03-07 17-14-12](https://user-images.githubusercontent.com/4985/157073276-e8b31314-7b76-4847-b3ca-fa2bf46874b2.png)

-----

**System Information:**

```txt

  Python 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0]

           pyvista : 0.33.2
               vtk : 9.0.1
             numpy : 1.21.0
           imageio : 2.14.1
           appdirs : 1.4.4
            scooby : 0.5.11
        matplotlib : 3.4.2
             PyQt5 : 5.12.3
           IPython : 7.22.0
              tqdm : 4.48.2
```

According to @banesullivan , the regresion occured in v.0.33.0

Also, from my investigations, in the previous example if instead of the `Cube` object, we pass its bounds, then clipping is sane. However if the cube is rotated, then the clipping breaks (albeit in a different way).

Edit: to complete, the bug is not linked to the `invert` parameter either

**Comment by banesullivan** [comment]
Thank you for reporting this! This is known and has been tracked in https://github.com/pyvista/pyvista/discussions/2191. This is indeed a big we need to track, so thank you for opening this issue

**Comment by eino** [comment]
Hi,
I ran a git bisect, and found the regression occurred in commit [4b83f5c9](https://github.com/pyvista/pyvista/commit/4b83f5c92068e8e6e8e27dc8b5fd974b56fbc7ee)

And more precisely, it's the change to `utilities/geometric_objects.py`, setting the parameter `clean=True` that made Cube not suitable to be passed to `clib_box`. If we change my example to pass `clean=False` in the Cube creation, then the clipping works as expected.

I wonder if the Cube should be cleaned by default. Else maybe a warning should be placed in `clip_box` doc, and examples amended. What do you think?

**Comment by banesullivan** [comment]
Aha! Thank you for running a git bisect to find the offending commit - this is incredibly helpful!

I do not think the cube needs to be cleaned by default, so perhaps we should look into changing this back.

**Comment by banesullivan** [comment]
@adeak, would you please look into this or elaborate on why `clean` is needed for `Cube`? I saw the note you added here:

https://github.com/pyvista/pyvista/blob/e61808110f174209467becc3188ca28b3350ed20/pyvista/utilities/geometric_objects.py#L538-L539

which implies `clean` is actually needed

**Comment by banesullivan** [comment]
I'm still concerned that this isn't working with the cleaned/manifold version of the cube... that seems wrong still

**Comment by eino** [comment]
Actually clipping uses face normals (by doing a `extract_cells(...)["Normals"][0]`)
https://github.com/pyvista/pyvista/blob/e61808110f174209467becc3188ca28b3350ed20/pyvista/core/filters/data_set.py#L220-L225

So I took a look, and clearing seems to change the normals returned when using `compute_normals` then `extract_cells`.
With no cleaning the results looks good:

```py
[cube.extract_cells(i)["Normals"] for i in range(6)]
[array([[-1.,  0.,  0.],
       [-1.,  0.,  0.],
       [-1.,  0.,  0.],
       [-1.,  0.,  0.]], dtype=float32),
array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32), 
array([[ 0., -1.,  0.],
       [ 0., -1.,  0.],
       [ 0., -1.,  0.],
       [ 0., -1.,  0.]], dtype=float32), 
array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.]], dtype=float32), 
array([[ 0.,  0., -1.],
       [ 0.,  0., -1.],
       [ 0.,  0., -1.],
       [ 0.,  0., -1.]], dtype=float32), 
array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]], dtype=float32)]
```

But with a clean, the normals are not right after the second one: 
```py
[cube_cleaned.extract_cells(i)["Normals"] for i in range(6)]
[array([[-1.,  0.,  0.],
       [-1.,  0.,  0.],
       [-1.,  0.,  0.],
       [-1.,  0.,  0.]], dtype=float32), 
array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32), 
array([[-1.,  0.,  0.],
       [-1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.]], dtype=float32), 
array([[-1.,  0.,  0.],
       [-1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.]], dtype=float32), 
array([[-1.,  0.,  0.],
       [-1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.]], dtype=float32), 
array([[-1.,  0.,  0.],
       [-1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.]], dtype=float32)]
```

**Comment by adeak** [comment]
Uuuh isn't this the problem then? https://github.com/pyvista/pyvista/blob/e61808110f174209467becc3188ca28b3350ed20/pyvista/core/filters/data_set.py#L220

`compute_normals()` is not in-place by default! This may have been changed during the recent in-place revamp, and this would easily explain subtle bugs! Could you please check if changing that line to `poly.compute_normals(inplace=True)` fixes the original bug?

**Comment by adeak** [comment]
Awesome, thank you for digging this up!
