### ISSUE TITLE
Regression: string scalar categories no longer supported

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#2311]
The following example no longer plots as expected:

```py
import numpy as np
import pyvista as pv

vol = pv.Cube()

vol['names'] = np.empty(vol.n_cells, dtype=str)

names = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']
for i in range(vol.n_cells):
    vol['names'][i] = names[i]
vol.plot(scalars='names')
```
![Screen Shot 2022-03-08 at 9 44 18 PM](https://user-images.githubusercontent.com/22067021/157374635-ecf66315-3e85-41b9-b651-27f0040448e9.png)

This used to work to label the scalar bar by the unique str values as can be seen in https://github.com/pyvista/pyvista-support/issues/25

This seemingly should be handled in:

https://github.com/pyvista/pyvista/blob/90feec68f40bb815ec6ad5ea53fa493904039b26/pyvista/plotting/mapper.py#L94-L104

but something has gone awry or something has changed and I'm not doing this right in my example

**Comment by FCalderon3006** [comment]
@banesullivan Hi, Was you able to solve the issue of scalar no longer supported ? to represent the boreholes with scalar data ("Geology"). Thank you in advance.

**Comment by akaszynski** [comment]
This works:

```py
import numpy as np
import pyvista as pv

vol = pv.Cube()

vol['names'] = np.empty(vol.n_cells, dtype=str)

names = ['a', 'b', 'c', 'd', 'e', 'f']

vol.plot(scalars=names)
```

![tmp](https://user-images.githubusercontent.com/11981631/180327950-4bbc870f-7289-47de-b219-329bcc6b74b0.png)

So does this:
```py
import numpy as np
import pyvista as pv

vol = pv.Cube()

vol['names'] = ['a', 'b', 'c', 'd', 'e', 'f']

vol.plot(scalars='names')
```
