### ISSUE TITLE
Clip without triangulate/crinkle

### ISSUE THREAD

**Issue by liangwang0734** [pyvista/pyvista#2313]
**Describe what feature you would like added.**

- Paraview allows turning these off/on.
- It appears that [`vtkBoxClipDataSet`](https://vtk.org/doc/nightly/html/c2_vtk_t_2.html#c2_vtk_t_vtkBoxClipDataSet) always triangulate.
- Examples of [crinkling](https://docs.paraview.org/en/latest/UsersGuide/filteringData.html#clip):
![](https://docs.paraview.org/en/latest/_images/CrinkleClipComparison.png)

**Comment by banesullivan** [comment]
I had thought we had a way to do this as I spent a ton of time a while back getting this right in PyVista for some sophisticated clipping I was having to do at the time. I will look back and submit a patch if needed to handle this

**Comment by banesullivan** [comment]
FYI: https://discourse.vtk.org/t/is-it-possible-to-turn-off-triangles-on-vtkclipdataset-filter/279

**Comment by banesullivan** [comment]
ParaView's "crinkle clip" is actually performing a cell extraction after the clip:

https://github.com/Kitware/ParaView/blob/b5deec590fabf272f28da27f2e10d0e42e13fc33/VTKExtensions/FiltersGeneral/vtkPVMetaClipDataSet.cxx#L60

Which is what I demo in https://discourse.vtk.org/t/is-it-possible-to-turn-off-triangles-on-vtkclipdataset-filter/279/10?u=banesullivan  and also show below (more simply):

```py
import pyvista as pv
import numpy as np

# Input mesh
mesh = pv.Wavelet()

# Add Cell IDs
ids = np.arange(0, mesh.n_cells, dtype=int)
mesh['ids'] = ids

# Perform the clip
normal = (1,1,1)
plane = pv.Plane(i_size=30, j_size=30, direction=normal)
clipped = mesh.clip(normal=normal)

# Crinkle the clip
crinkled = mesh.extract_cells(np.unique(clipped['ids']))

# Plot comparison
p = pv.Plotter(notebook=0, shape=(1,2))
p.add_mesh(clipped, show_edges=True)
p.add_mesh(plane.extract_feature_edges(), color='r')
p.subplot(0,1)
p.add_mesh(crinkled, show_edges=True)
p.add_mesh(plane.extract_feature_edges(), color='r')
p.link_views()
p.show()
```

![Screen Shot 2022-03-09 at 12 28 06 PM](https://user-images.githubusercontent.com/22067021/157517026-9ffdb816-f2f8-40b1-b8b3-9a588f6017e2.png)

---- 

We could add a new `crinkle` argument to `_clip_with_function` that performs the extra `extract_feature_edges` step to "crinkle" the clip.

**Comment by banesullivan** [comment]
For completeness, here is the same demo in ParaView:

| Clip | Crinkled Clip |
|---|---|
|![Screen Shot 2022-03-09 at 12 32 15 PM](https://user-images.githubusercontent.com/22067021/157517755-be224d0e-d895-458d-9868-a024209daed2.png) | ![Screen Shot 2022-03-09 at 12 32 20 PM](https://user-images.githubusercontent.com/22067021/157517791-1578143c-52fb-4f8e-81d2-b0ec6fbe3a1c.png) |

**Comment by liangwang0734** [comment]
@banesullivan this looks great (and sophisticated).  Thanks for the investigation!
