### ISSUE TITLE
Transferring PolyData Faces into a Numpy Array

### ISSUE THREAD

**Issue by Connor56** [pyvista/pyvista#2330]
A fast way to transfer the face data, as stored in the Polydata object, into a Numpy object array containing the indexes of all the points of each simplex.

This should be a fairly simple for loop in C, I would add it myself, but I A) don't know C yet, and B) don't know how to integrate C and Python. However, the pseudocode in Python could look something like this:

```python
simplexes = []
index = 0
while index < face_array.shape[0]:
    number_of_points = face_array[index]
    points = face_array[index+1:index+1+number_of_points]
    simplexes.append(points)```

**Comment by darikg** [comment]
It'd definitely be nice to have an official solution for this.

Maybe:

```python
from pyvista import _vtk
from numpy import split

def face_array(mesh: PolyData):
    cells = mesh.GetPolys()
    c = _vtk.vtk_to_numpy(cells.GetConnectivityArray())
    o = _vtk.vtk_to_numpy(cells.GetOffsetsArray())
    return split(c, o[1:-1])
```

**Comment by RichardScottOZ** [comment]
Yes, helpful for people learning this sort of thing too.

**Comment by adeak** [comment]
I would argue that object-dtype arrays are pretty much never the right tool. Use a list of arrays instead. Which is not to say we shouldn't support this.

**Comment by banesullivan** [comment]
This is a tough problem to solve generally and has come up many times in PyVista's history. I agree, we should provide some better solutions for converting the faces to numpy arrays.

Re C+Python: I am very hesitant to provide any Cython code in PyVista - IMO, PyVista should stay pure-Python as that is one of its strong selling points making installation into complex environments with VTK much simpler (e.g. installing PyVista into ParaView's Python environment). And we want PyVista to remain a lean layer on top of VTK.

@darikg's solution above is the best I've seen to date and I'd be +1 for including that in PyVista directly! One issue I have with it is that it's a `list` of numpy arrays rather than an `ndarray` (or it'd be an object-dtype `ndarray` which, like @adeak, I think isn't a great choice).

**Comment by banesullivan** [comment]
For meshes with uniform cell types (all tirangles or all quads), we could modify @darikg's to:

```py
from typing import List
from pyvista import _vtk, PolyData
from numpy import split, ndarray

def face_arrays(mesh: PolyData) -> List[ndarray]:
    cells = mesh.GetPolys()
    c = _vtk.vtk_to_numpy(cells.GetConnectivityArray())
    o = _vtk.vtk_to_numpy(cells.GetOffsetsArray())
    faces = split(c, o[1:-1])
    if len(np.unique(np.diff(o))) == 1:
        return np.array(faces)
    return faces
```
```py
>>> import pyvista as pv
>>> face_arrays(pv.Sphere()).dtype
dtype('int64')
````

**Comment by banesullivan** [comment]
That's the best solution I've seen to this problem so far, many kudos to @darikg! I think adding that method to `PolyData` would be a great addition. Though the mixed return type concerns me, and I think we may want to either always return a `list` of `ndarray`s or use my proposed change above with a warning when returning a `list` (i.e., when non-uniform cell types)

**Comment by adeak** [comment]
> One issue I have with it is that it's a list of numpy arrays rather than an ndarray (or it'd be an object-dtype ndarray which, like @adeak, I think isn't a great choice).

Just to be clear, this is inevitable, right? In the general case you can have face subarrays of non-uniform length, in which case you need a list or an object-dtype array. So if we want to support something like this then this is not an issue _per se_.

> For meshes with uniform cell types (all tirangles or all quads), we could modify @darikg's to the following wich would return an `ndarray` with `int64` dtype
> [...]

I don't know the overhead involved of grabbing and checking these VTK arrays, so we should also check a potential early return with something like
```py
    cells = mesh.faces
    first_size = cells[0]
    if np.unique(cells[first_size + 1 : : first_size + 1]).size == 1:
        return cells.reshape(-1, first_size + 1)[:, 1:].copy()
```
(untested)

> Re C+Python: I am very hesitant to provide any Cython code in PyVista - IMO, PyVista should stay pure-Python as that is one of its strong selling points making installation into complex environments with VTK much simpler (e.g. installing PyVista into ParaView's Python environment). And we want PyVista to remain a lean layer on top of VTK.

For completeness' sake [we discussed something similar almost exactly a year ago](https://github.com/pyvista/pyvista/pull/1213). Like I did back then, I would recommend numba or pythran (which still incur a dependency hit, but have very low maintainability burden). Once you go Cython the bus factor drops exponentially.

**Comment by darikg** [comment]
Maybe split the two different cases into `def regular_face_arrays` and `def irregular_face_arrays`, or alternatively `def face_arrays(mesh, regular: bool)`? The former would raise ValueError or whatever numpy uses for invalid array shapes if the user called it on a mesh with irregular faces.

**Comment by adeak** [comment]
By chance I ran into a partial solution: unstructured grids with fixed-size cells have a `cells_dict` attribute that contains 2d arrays of point indices for each cell type:
```py
import pyvista as pv

triangles = pv.Sphere()
quads = pv.Cube()
polys = pv.Dodecahedron()

print(triangles.cast_to_unstructured_grid().cells_dict)  # OK, only triangles
print(quads.cast_to_unstructured_grid().cells_dict)  # OK, only quads
print(polys.cast_to_unstructured_grid().cells_dict)  # error, because poly faces could have unequal length either though here they don't
```

The helper that does this is [`pyvista.utilities.cells.get_mixed_cells()`](https://github.com/pyvista/pyvista/blob/17ed84995c1aaeeedfb0121dc7c9ac3865b5a334/pyvista/utilities/cells.py#L345). The supported cell types are evaluated at runtime in https://github.com/pyvista/pyvista/blob/17ed84995c1aaeeedfb0121dc7c9ac3865b5a334/pyvista/utilities/cell_type_helper.py.
