### ISSUE TITLE
Poly strips are not exposed in our API

### ISSUE THREAD

**Issue by adeak** [pyvista/pyvista#2340]
I noticed something weird:
```py
>>> import pyvista as pv
>>> polygon = pv.Rectangle()
>>> extruded = polygon.extrude((0, 0, 1))
>>> extruded
PolyData (0x7f96e0eccee0)
  N Cells:	4
  N Points:	8
  X Bounds:	0.000e+00, 1.000e+00
  Y Bounds:	0.000e+00, 1.000e+00
  Z Bounds:	0.000e+00, 1.000e+00
  N Arrays:	0

>>> extruded.faces
array([], dtype=int64)
>>> extruded.lines
array([], dtype=int64)
>>> extruded.verts
array([], dtype=int64)
```

After extrusion the box-shaped polydata has 4 cells, but no faces/lines/verts. I would expect to have 8 triangles listed in the `.faces` property. The cell types can be queried:
```py
>>> [extruded.cell_type(n) for n in range(extruded.n_cells)]
[6, 6, 6, 6]
```
This corresponds to `VTK_TRIANGLE_STRIP` which makes sense.

Compare the poly before extrusion:
```py
>>> polygon.faces
array([4, 0, 1, 2, 3])
```

So it turns out that extrusion results in "strips" rather than "polys", and our `faces`/`lines`/`verts` properties don't catch this. Should we expose these too as a property? I don't have a use case for this (other than being surprised a bit), but it might make sense to expose this.

For reference, our implementation of `.faces` looks like this: https://github.com/pyvista/pyvista/blob/dbffcb772811f89dc3e1d2f4fab1d01ebf640d8d/pyvista/core/pointset.py#L646

We could do the same wrapping `GetStrips()`:
```py
>>> pv._vtk.vtk_to_numpy(extruded.GetStrips().GetData())
array([4, 0, 1, 4, 5, 4, 1, 2, 5, 6, 4, 2, 3, 6, 7, 4, 3, 0, 7, 4])
```

**Comment by banesullivan** [comment]
+1 for exposing this. I've never had a need for triangle strips either, but I think it'd be good to expose them like we do for `lines`

**Comment by akaszynski** [comment]
@AlejandroFernandezLuces, please take a look at this and see if you can expose this functionality.

Please see our documentation at https://docs.pyvista.org/ and contributing documentation at [CONTRIBUTING](https://github.com/pyvista/pyvista/blob/main/CONTRIBUTING.rst).

Feel free to ping me anytime. Ideally, open a draft PR early and we can collaborate there.

**Comment by AlejandroFernandezLuces** [comment]
PR is already up, please take a look and let me know what do you think about it 😄

**Comment by banesullivan** [comment]
Pretty sure this was resolved by https://github.com/pyvista/pyvista/pull/3208
