### ISSUE TITLE
Detection of self intersection for pyvista.polydata type

### ISSUE THREAD

**Issue by scarpma** [pyvista/pyvista#2345]
Hello everyone. Some time ago, I was generating new shapes (non-closed 3d surfaces) through a statistical shape model (SSM). Sometimes the SSM was giving shapes that self-intersected. By self-intersection, I mean when some part of the surface touches another part of the surface of the same pyvista.Polydata. I have attached an image to be as clear as possible.

![image](https://user-images.githubusercontent.com/13443357/158206508-1af5cefa-e27a-414e-a51f-2d2bfbcb3800.png)

I could not find any solution online to detect this kind of problem. The (not very robust) solution I came up with is to generate an inflated version of the same surface and then run the `pyvista.Polydata.intersection()` method to check if the two shapes intersect. This is the implementation:
```python
def check_self_intersections(mesh_orig):
    mesh_inflated = mesh_orig.copy()
    mesh_inflated = mesh_inflated.compute_normals(
        consistent_normals=True,
        cell_normals=False,
        split_vertices=True
    )
    mesh_inflated.points = mesh_inflated.points + mesh_inflated['Normals']*1.
    intersection = mesh_orig.intersection(mesh_inflated)
    return intersection[0].n_points
```

The problems with this solution are multiple:

1. VTK does not seem to like when `intersection` has zero points, i.e., the mesh does not intersect. In fact, some warning is always launched in the background;
2. `intersection` can have a small number of points even if there are no intersections. In fact, I check for self-intersections by asserting that `intersection.n_points < THRESHOLD_VALUE`.

I would like to know if there are some better solutions to the problem and, in that case, create a pull request with this feature.

Thanks everyone!

-----

**Comment by whophil** [comment]
@scarpma can you share your sample data?

**Comment by akaszynski** [comment]
The fastest way to do this is to use `pymeshfix` to detect self-intersections:

```py
import pymeshfix
import pyvista

mesh = pyvista.read('00043.vtp')

# Create TMesh object
tin = pymeshfix.PyTMesh()
tin.load_array(mesh.points, mesh.faces.reshape((-1, 4))[:, 1:])
tin.clean(max_iters=10, inner_loops=3)
```

This will actually "clean" the mesh and output to stdout. I could improve the interface and add a top level `check_for_self_intersections`, but I don't have time at the moment to add that.

**Comment by scarpma** [comment]
Could you confirm me that [this](https://github.com/pyvista/pymeshfix/blob/d160b3e612b662a86463bc678f7edf69c2a72f25/pymeshfix/cython/detectIntersections.cpp#L138) is the piece of code that checks for intersections ?

Could you explain to me how it works ? From the comments it seems that there is a brute force all to all check, but can I know specifically how the check is done in individual triangles ? I mean, how do you check mathematically if two triangles intersect ?

If I understand I can implement my own version. If you want I could try to expose a function to do the check, but for now I do not know cpp (and the interface with python)... I could implement something in numpy for pyvista @akaszynski 

Thanks

**Comment by akaszynski** [comment]
> I mean, how do you check mathematically if two triangles intersect ?

I've found this to be the most robust:
https://en.wikipedia.org/wiki/M%C3%B6ller%E2%80%93Trumbore_intersection_algorithm

It's brute force, but you can limit the triangles tested using a kdtree lookup.

**Comment by scarpma** [comment]
Ok, thank you very much. I will look into these in these days. As soon as I come up with something I will update this issue. Thanks !!

**Comment by scarpma** [comment]
I have spent time on this. Currently, I'm working on the mesh that I provided in this issue (20k nodes).

I have written a function leveraging numpy. This is vectorized, so runs pretty fast. Basically, you give a segment and a triangle, and then it computes if there's an intersection or not. Since it is vectorized, I can give multiple segments and multiple triangles.

In order to check if two triangles intersect I call the function 6 time, one for each segment of the two triangles. The two triangles intersect if two segments of one triangle intersect the other, or if one segment of each triangle intersect the other one.

Now, regarding the self-intersection problem, I use a kdtree in order to, for each triangle of the mesh, check intersections only with near triangles. I use the `KDTree.query_ball_point` from scipy library ([link](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.KDTree.query_ball_point.html)).

To check intersections for one triangle the function takes about 900 micro seconds. This is a problem, since for a mesh with 20k nodes the total time will be around 20 sec...

I have to do some optimization...

The main problem that I'm facing now is that I don't know how to vectorize the outer loop, since each triangle has a different number of near cells with which the intersection check has to be made. Doing this outer loop with a plain `for` loop would be too slow.

Any advice ? I can share my code if needed

**Comment by whophil** [comment]
Can you get rid of the outer loop?

`query_ball_point(x, r)` accepts vectors for `x` and `r`. This will return a list of lists - the inner list will have variable length, as you have noted. You should still be a able to unravel this to 1-D lists of edges/vertices (a Python for loop, but no math inside), which can be passed into your vectorized ray/triangle intersection method all at once.

**Comment by scarpma** [comment]
Thank you @whophil for the suggestion! You were right. I got rid of the outer loop and now the whole algorithm works in 1.09 seconds (on a mesh with 20k nodes).

I am profiling my code and I see that most of the time is spent eliminating neighboring cells from the ball returned by `KDTree.query_ball_point`. In fact, when I query a ball, even neighboring cells are returned, which will raise intersections. In order to remove this problem, for each ball I remove neighboring cells using this function:

```python
def remove_neig_cells(tria_idx, cell_idxs, near_cells):
    """
    tria_idx: int -- index of triangle in question inside `cell_idxs`
    cell_idxs: int[N,3] -- indices of points of each triangle of the mesh (cell_idxs = np.array(mesh.faces.reshape((-1,4))[:,1:]))
    near_cells: int[M] -- indices of triangles near the triangle num `tria_idx` returned by `KDTree.query_ball_point`
    N is the total number of triangles of the mesh. M is the number of triangles found near triangle num `tria_idx`.
    """
    near_points_idxs = cell_idxs[near_cells]
    idx1, idx2, idx3 = cell_idxs[tria_idx]
    non_neig_cells_bool = np.logical_not(np.any(
        np.array([
            near_points_idxs[:,0] == idx1,
            near_points_idxs[:,0] == idx2,
            near_points_idxs[:,0] == idx3,
            near_points_idxs[:,1] == idx1,
            near_points_idxs[:,1] == idx2,
            near_points_idxs[:,1] == idx3,
            near_points_idxs[:,2] == idx1,
            near_points_idxs[:,2] == idx2,
            near_points_idxs[:,2] == idx3,
        ]),
        axis=0,
    ))
    return near_cells[non_neig_cells_bool]
```
I think that this can be optimized. **Is there a better way to check if, given two triangles, they share one of their points ?**

There's another solution, but I think it is not ideal. I could modify the intersection algorithm in order to not detect intersections when triangles share one of their points. The problem is that, by doing this, I can remove the call to `remove_neig_cells`, but then the number of total intersections calculation to check is about 5 times bigger. This would still be an improvement in terms of performance (from 1.09 s to 0.8 s), but I think that the intersection algorithm would become less robust. Moreover, the call to `remove_neig_cells` is about 60% of the total time required for the algorithm, so maybe a bigger improvement would come by optimizing this.

**Comment by scarpma** [comment]
Are you interested in the actual final implementation ? I didn't manage to go below 0.8 seconds as running time, but anyway the algorithm works and only uses numpy arrays (It is completely vectorized) and scipy KDtree.
Maybe if not in the library itself, we could write an example in the documentation.

**Comment by whophil** [comment]
> Are you interested in the actual final implementation ? I didn't manage to go below 0.8 seconds as running time, but anyway the algorithm works and only uses numpy arrays (It is completely vectorized) and scipy KDtree. Maybe if not in the library itself, we could write an example in the documentation.

I am interested in taking a look.

I don't know how many "native" filters there are in PyVista, but I don't see why it couldn't happen.

Semi-related, #2446 discusses a separate project for generating CGAL Python bindings. I believe CGAL has its own self-intersection algorithm.

**Comment by scarpma** [comment]
yes, this is it
```python
import numpy as np
import scipy.spatial

EPSILON = 1e-5

def seg_tria_intersection(P0, P1, V0, V1, V2):
    """
    P0 first point of the segment
    P1 second point of the segment
    V0, V1, V2 vertices of triangle
    D normalized direction of segment
    l length of the segment
    u,v barycentric coordinated of intersection (inside triangle
    if 0 < u < 1. and 0. < v < 1.)
    t coordinate along segment of the intersection (inside segment
    if 0. < t < l.)
    3d space
    """
    O = P0
    D = P1 - P0
    l = np.sqrt((D**2.).sum(-1))
    D = (D.T / l).T

    E1 = V1 - V0 # edge 1 of triangle
    E2 = V2 - V0 # edge 2 of triangle
    P = np.cross(D, E2)
    det = np.einsum('...i,...i',E1, P)
    # if det is near 0, ray lies in triangle's plane
    det_bool = np.abs(det) > EPSILON

    # EPSILON2 must be >0 because otherwise segments that start
    # or finish in one of the triangle vertices are counted as
    # intersections
    EPSILON2 = 0.001

    inv_det = 1 / det
    T = O - V0
    u = np.einsum('...i,...i', T, P) * inv_det
    u_bool = np.logical_and(u > 0.+EPSILON2, u < 1.-EPSILON2)

    Q = np.cross(T, E1)
    v = np.einsum('...i,...i', D, Q) * inv_det
    v_bool = np.logical_and(v > 0.+EPSILON2, u+v < 1.-EPSILON2)

    t = np.einsum('...i,...i', E2, Q) * inv_det
    t_bool = np.logical_and(t > 0., t < 1.)

    return det_bool * u_bool * v_bool * t_bool


def tria_tria_intersection(tria1_coo, tria2_coo):

    """
    detects if edges of tria1 intersect tria2. Note that this is different from
    detecting if the two triangles intersect. I can use this shorter version of the
    intersection function because I loop among all triangles, so if only triangle2'edges
    intersect triangle1, the intersection will be spotted later in the loop
    If not in a loop, given two triangles, they interset iff:
        or one edge on each intersect
        or two edges of one intersect the other one
    """

    tria1_coo = tria1_coo.astype(np.float32)
    tria2_coo = tria2_coo.astype(np.float32)

    if tria1_coo.ndim == 2:
        tria1_coo = tria1_coo[(None)]
    if tria2_coo.ndim == 2:
        tria2_coo = tria2_coo[(None)]

    i = 0
    i += seg_tria_intersection(
        tria1_coo[:,0], tria1_coo[:,1],
        tria2_coo[:,0], tria2_coo[:,1], tria2_coo[:,2],
    )
    i += seg_tria_intersection(
        tria1_coo[:,1], tria1_coo[:,2],
        tria2_coo[:,0], tria2_coo[:,1], tria2_coo[:,2],
    )
    i += seg_tria_intersection(
        tria1_coo[:,2], tria1_coo[:,0],
        tria2_coo[:,0], tria2_coo[:,1], tria2_coo[:,2],
    )

    return i>0


def check_intersections(mesh, r=None):

    cell_idxs = np.array(mesh.faces.reshape((-1,4))[:,1:])
    cell_coords = np.array(mesh.points[cell_idxs])
    cell_center_coords = np.array(mesh.cell_centers().points)
    kdtree = scipy.spatial.KDTree(cell_center_coords)

    if r is None:
        max_distance_between_center_and_vertices = np.sqrt((
            (cell_center_coords[:,None,:] - mesh.points[cell_idxs])**2
        ).sum(-1)).max()
        r = max_distance_between_center_and_vertices * 1.05

    near_cells = kdtree.query_ball_point(cell_center_coords, r, return_sorted=False, workers=-1)

    tria1_idxs_tot, tria2_idxs_tot = [], []
    for tria1_idx, tria2_idxs in enumerate(near_cells):
        #tria2_idxs_non_neig = list(remove_neig_cells(tria1_idx, cell_idxs, np.array(tria2_idxs)))
        tria2_idxs_non_neig = tria2_idxs
        tria1_idxs_tot += [tria1_idx] * len(tria2_idxs_non_neig)
        tria2_idxs_tot += tria2_idxs_non_neig
    tria1_idxs_tot = np.array(tria1_idxs_tot)
    tria2_idxs_tot = np.array(tria2_idxs_tot)

    tria1_coo = cell_coords[tria1_idxs_tot]
    tria2_coo = cell_coords[tria2_idxs_tot]

    o = tria_tria_intersection(tria1_coo, tria2_coo)

    return tria1_idxs_tot[o]
```

and it is used simply like this
`check_intersections(surfaceMesh)` where `surfaceMesh` is a polydata object.

Probably the implementation is not very clear, so for any doubt ask me anything. I am also open to any suggestion / modification.

Thanks for your interest

**Comment by Alexboiboi** [comment]
Hi @scarpma (@bensnell)

thanks for sharing your work here ;) I was also looking for a way to detect self-intersection. From your code I noticed that some intersections were not detected. I didn't dive deep into finding the reason why it is the case but by playing with some test meshes i noticed it. Also your function returns `tria1_idxs_tot[o]` and some intersections may be missed if you don't add also `tria2_idxs_tot[o]`. 
I ended up implementing my own version, based on yours (see below)

### Code implementation
```python
import ipywidgets as ipw
import magpylib as magpy
import numpy as np
import plotly.graph_objects as go
import pyvista as pv
import scipy.spatial


def segments_intersect_facets(segments, facets, eps=1e-6):
    """Pair-wise detect if set of segments intersect set of facets.

    Parameters
    -----------
    segments: np.ndarray, shape (n,3,3)
        Set of segments.

    facets: np.ndarray, shape (n,3,3)
        Set of facets.

    eps: float
        Point to point tolerance detection. Must be strictly positive,
        otherwise some triangles may be detected as intersecting themselves.
    """
    if eps <= 0:
        raise ValueError("eps must be stricly positive")

    s, t = segments.swapaxes(0, 1), facets.swapaxes(0, 1)

    # compute the normals to each triangle
    normals = np.cross(t[2] - t[0], t[2] - t[1])
    normals /= np.linalg.norm(normals, axis=1, keepdims=True)

    # get sign of each segment endpoint, if the sign changes then we know this
    # segment crosses the plane which contains a triangle. If the value is zero
    # the endpoint of the segment lies on the plane.
    g1 = np.sum(normals * (s[0] - t[2]), axis=1)
    g2 = np.sum(normals * (s[1] - t[2]), axis=1)

    # determine segments which cross the plane of a triangle.
    #  -> 1 if the sign of the end points of s is
    # different AND one of end points of s is not a vertex of t
    cross = (np.sign(g1) != np.sign(g2)) * (np.abs(g1) > eps) * (np.abs(g2) > eps)

    v = []  # get signed volumes
    for i, j in zip((0, 1, 2), (1, 2, 0)):
        sv = np.sum((t[i] - s[1]) * np.cross(t[j] - s[1], s[0] - s[1]), axis=1)
        v.append(np.sign(sv))

    # same volume if s and t have same sign in v0, v1 and v2
    same_volume = np.logical_and((v[0] == v[1]), (v[1] == v[2]))

    return cross * same_volume


def get_intersecting_triangles(vertices, triangles, r=None, r_factor=1.5, eps=1e-6):
    """Return intersecting triangles indices from a triangular mesh described
    by vertices and triangles indices.

    Parameters
    ----------
    vertices: np.ndarray, shape (n,3)
        Vertices/points of the mesh.

    triangles: np.ndarray, shape (n,3), dtype int
        Triples of vertices indices that build each triangle of the mesh.

    r: float or None
        The radius of the ball-point query for the k-d tree. If None:
        r=max_distance_between_center_and_vertices*2

    r_factor: float
        The factor by which to multiply the radius `r` of the ball-point query.
        Note that increasing this value will drastically augment computation
        time.

    eps: float
        Point to point tolerance detection. Must be strictly positive,
        otherwise some triangles may be detected as intersecting themselves.
    """
    if r_factor < 1:
        raise ValueError("r_factor must be greater or equal to 1")

    vertices = vertices.astype(np.float32)
    facets = vertices[triangles]
    centers = np.mean(facets, axis=1)

    if r is None:
        radius = r_factor * np.sqrt(((facets - centers[:, None, :]) ** 2).sum(-1)).max()

    kdtree = scipy.spatial.KDTree(centers)
    near = kdtree.query_ball_point(centers, radius, return_sorted=False, workers=-1)
    tria1 = np.concatenate(near)
    tria2 = np.repeat(np.arange(len(near)), [len(n) for n in near])
    pairs = np.stack([tria1, tria2], axis=1)
    pairs = pairs[pairs[:, 0] != pairs[:, 1]]  # remove check against itself
    f1, f2 = facets[pairs[:, 0]], facets[pairs[:, 1]]
    sums = 0
    for inds in [[0, 1], [1, 2], [2, 0]]:
        sums += segments_intersect_facets(f1[:, inds], f2, eps=eps)
    return np.unique(pairs[sums > 0])
```

### Examples
As an example below how it behaves. To be noted that the tolerance for the ball point query radius is impacting the full detection of intersections. It also greatly influences computation speed as it increases the number of checks. So there is an annoying tradeoff between performance and accuracy.

```python
def update_fig(x=1, y=1, z=1, r_factor=1, eps=1e-5):
    with fig.batch_update():
        # create self intersecting object
        c1 = pv.Cube().triangulate()
        c2 = pv.Cube(center=(x, y, z)).triangulate()
        polydata = c1.merge(c2)
        vert = polydata.points
        tr = polydata.faces.reshape(-1, 4)[:, 1:]
        (x, y, z), (i, j, k) = vert.T, tr.T
        trace_mesh3d.update(x=x, y=y, z=z, i=i, j=j, k=k)

        # show edges
        edges = np.concatenate([tr[:, 0:2], tr[:, 1:3], tr[:, ::2]], axis=0)
        edges_uniq = np.unique(np.sort(edges, axis=1), axis=0)
        lines = vert[edges_uniq]
        lines = np.insert(lines, 2, None, axis=1).reshape(-1, 3)
        x, y, z = lines.T
        trace_all_edges.update(x=x, y=y, z=z)

        # intersecting triangles
        tri = tr[get_intersecting_triangles(vert, tr, r_factor=r_factor, eps=eps)]
        (x, y, z), (i, j, k) = vert.T, tri.T
        trace_intersect.update(x=x, y=y, z=z, i=i, j=j, k=k)


# create figure
fig = go.FigureWidget(layout_margin=dict(t=0, b=0, r=0, l=0))
fig.add_mesh3d(name="2Cubes", opacity=0.5, showlegend=True)
fig.add_scatter3d(
    line_width=2,
    name="all edges",
    line_color="black",
    mode="lines",
    opacity=0.5,
    showlegend=False,
)
fig.add_mesh3d(opacity=0.5, showlegend=True, name="Intersecting triangles")
trace_mesh3d, trace_all_edges, trace_intersect = fig.data

# add interactivity
slider = lambda **kwargs: ipw.FloatSlider(min=-1, max=1, **kwargs)
interact = ipw.interactive(
    update_fig,
    x=slider(value=-0.9),
    y=slider(value=0.9),
    z=slider(value=0.6),
    r_factor=ipw.FloatSlider(min=1, max=10, step=0.05, value=1.05),
    eps=ipw.FloatLogSlider(min=-16, max=0, value=1e-5),
)
display(ipw.HBox([interact, fig]))
```
As you can see in the examples below, with 5% radius tolerance some facets are not detected as intersections.

<img width="682" alt="image" src="https://user-images.githubusercontent.com/29252289/223216489-d5787e46-30c4-4f08-b597-32657ef0e98e.png">

Here with 10%:
<img width="686" alt="image" src="https://user-images.githubusercontent.com/29252289/223216090-84b56188-2fd4-4da6-8c46-3c2544f1b2e7.png">

And finally at 20%, where all intersections are found
<img width="670" alt="image" src="https://user-images.githubusercontent.com/29252289/223216336-ad47323b-bd39-4d73-a80a-16f17c63363f.png">

### Performance
This code works reasonably well as you can see below with around 10k elements and depending on the radius tolerance.
```pyhon
import magpylib as magpy
import pyvista

N = 10000
res = int(np.sqrt(N / 4))
sphere_a = pyvista.Sphere(theta_resolution=res, phi_resolution=res)
sphere_b = pyvista.Sphere(theta_resolution=res, phi_resolution=res, center=(0.5, 0, 0))
mesh = sphere_a.merge(sphere_b)
vertices = mesh.points
triangles = mesh.faces.reshape(-1, 4)[:, 1:]
print(len(triangles))
````
<img width="520" alt="image" src="https://user-images.githubusercontent.com/29252289/223220607-fc1b9098-7a9f-491c-bb62-980dad2bb66d.png">


However, there is a major caveat. When the mesh contains elements with very different mesh triangles sizes. The computation time with automatic radius calculation (`r=None`) is at least an order of magnitude slower! I'm open to ideas on how to solves his issue ;)

See here the intersection detection of a sphere and a cube of similar size but very different element sizes:
```python
import magpylib as magpy
import pyvista

N = 10000
res = int(np.sqrt(N / 4))
sphere_a = pyvista.Sphere(theta_resolution=res, phi_resolution=res)
cube = pyvista.Cube(center=(0.5, 0, 0)).triangulate()
mesh = sphere_a.merge(cube)
vertices = mesh.points
triangles = mesh.faces.reshape(-1, 4)[:, 1:]
print(len(triangles))
```
<img width="525" alt="image" src="https://user-images.githubusercontent.com/29252289/223220546-25346856-cee3-4d02-89f1-3b615a3179c6.png">

**Comment by scarpma** [comment]
Hi @Alexboiboi , very interesting implementation ! Thanks for the feedback and for the gorgeous work !

I will try to give you some feedback in the next days. In the mean time, I did not understand if the problem of 'not capturing some intersections' is still present in your implementation. In case it is, could you provide an example mesh where the error occurs ? Thanks
