### ISSUE TITLE
export_gltf doesn't work after thresholding mesh

### ISSUE THREAD

**Issue by eddjharrison** [pyvista/pyvista#2359]
I have satellite imagery as a .vtk, with RGB_Image values in the data array - the aim is to export this using export_gltf with other items as part of a PyVista.Plotter() object. Unfortunately even the compressed example .vtk is too large to upload - so got a 24hr link available here: https://wormhole.app/d1WzX#DqLz6I5brkNuL3cgCboWhw

* The original vtk loads, plots and exports as a gltf correctly to around 750mb. 
* The thresholded version loads and plots correctly, but results in a 341kb empty gltf file. I can export the thresholded version as a .vtk, reload it in, and plot it all fine.

```py
import pyvista as pv
sat_img = pv.read(/path/to/file)

# I tried two different thresholding methods, both result in the same failure to export gltf
# First method:
sat_img = sat_img.threshold((0,240), scalars="RGB_Image")

# Second method as shown in #2349
sat_img['R'] = sat_img['RGB_Image'][:,0]
sat_img['G'] = sat_img['RGB_Image'][:,1]
sat_img['B'] = sat_img['RGB_Image'][:,2]
sat_img = sat_img.threshold((0,240), 
                scalars='R').threshold((0,240), 
                scalars='G').threshold((0,240), 
                scalars='B')

# Tried this export routine with both (reloaded sat_img in between testing)
test = pv.Plotter()
test.add_mesh(sat_img, show_edges=False, scalars="RGB_Image", rgb=True)
test.show()

# The test object plots as expected
# Exporting does not fail, but results in an empty / erroneous file
test.export_gltf('test.gltf', inline_data=True, save_normals=True) 

```

**Screenshots**

A screenshot of the test pv.Plotter() working
<img width="606" alt="Screenshot 2022-03-17 at 11 07 21" src="https://user-images.githubusercontent.com/61405769/158786197-05c312da-7d95-429f-a116-11dd01af1c1c.png">

And an image of the data
<img width="751" alt="Screenshot 2022-03-17 at 11 19 35" src="https://user-images.githubusercontent.com/61405769/158788400-d936c1bc-fa99-4590-ba6b-5c8bb582c0bb.png">

A screenshot of the original, unthresholded file
<img width="743" alt="Screenshot 2022-03-17 at 11 08 27" src="https://user-images.githubusercontent.com/61405769/158786431-46569cc5-5e59-4554-95bb-1900ea6f0d28.png">

With an image of the data
<img width="603" alt="Screenshot 2022-03-17 at 11 20 01" src="https://user-images.githubusercontent.com/61405769/158788477-c6f38033-1b2a-4628-9c05-683c19f48554.png">

-----

**System Information:**
 Please run the following code wherever you are experiencing the bug and paste the output below. This report helps us track down bugs and it is critical to addressing your bug:

System info:

--------------------------------------------------------------------------------
  Date: Thu Mar 17 11:09:03 2022 CET

                OS : Darwin
            CPU(s) : 8
           Machine : x86_64
      Architecture : 64bit
       Environment : Jupyter
       File system : unknown
        GPU Vendor : Intel Inc.
      GPU Renderer : Intel(R) Iris(TM) Plus Graphics 645
       GPU Version : 4.1 INTEL-18.4.6

  Python 3.8.2 (v3.8.2:7b3ab5921f, Feb 24 2020, 17:52:18)  [Clang 6.0
  (clang-600.0.57)]

           pyvista : 0.33.3
               vtk : 9.1.0
             numpy : 1.21.5
           imageio : 2.15.0
           appdirs : 1.4.4
            scooby : 0.5.11
        matplotlib : 3.5.1
           IPython : 8.0.1
        ipyvtklink : 0.2.2
             scipy : 1.8.0
              tqdm : 4.62.3
```

**Comment by akaszynski** [comment]
@eddjharrison, please reupload the example and I'll look at it. Been busy with another project and I've got a second now.

**Comment by eddjharrison** [comment]
https://wormhole.app/zQ3lY#MouW32IxgEmk8ggkjim_mQ @akaszynski
