### ISSUE TITLE
Round Trip through pickle breaks `object` type

### ISSUE THREAD

**Issue by WesleyTheGeolien** [pyvista/pyvista#2370]
When assigning (at least) `object`  (others types not tested) to `PolyData` (presumably others but not tested). Pyvista works (casts to `|S`) however a round trip via pickle (to load dumped objects) does not work (example provided below).

Expected to work as normal without the dump.

The reason this fails is due to the `is` in this line: https://github.com/pyvista/pyvista/blob/6a9b5260213fad2939210c40c56d86c6a5ef1e0b/pyvista/utilities/helpers.py#L159
Not sure exactly what happens in pickle but the `np.dtype` `id` changes so the `is` test fails however the `==` test passes.

-----

**To Reproduce**

Please include a code snippet to reproduce the bug in the block below:

```py
import pyvista as pv
import numpy
import pickle

vertices = np.array([[0, 0, 0], [1, 0, 0], [1, 0.5, 0], [0, 0.5, 0]])
pts = pv.PolyData(vertices)
pts['var'] = np.arange(4).astype('O')

print(pts)

pts_bad = pv.PolyData(vertices)
# The next line throws a TypeError
pts_bad['var'] = pickle.loads(pickle.dumps(np.arange(4).astype('O')))

```

**Comment by MatthewFlamm** [comment]
I think this is a bug here.  `np.dtype('O')` creates a new object sometimes, but I guess not all the time.  I'm actually surprised this works the first time you use it.

**Comment by whophil** [comment]
The `id` of unpickled dtypes appears to be changed.  Changing `is` to `==` should fix it?

```python
import numpy as np
import pickle

arr = np.array([0, 1, 2, 3], dtype='O')
arr2 = np.array([0, 1, 2, 3], dtype='O')
arr3 = pickle.loads(pickle.dumps(arr))

print('dtype tests')
print(arr2.dtype is arr.dtype)
print(arr3.dtype is arr.dtype)
print(arr3.dtype == arr.dtype)

print('\narray ids')
print(id(arr.dtype))
print(id(arr2.dtype))
print(id(arr3.dtype))

dtype = np.dtype('O')
dtype2 = pickle.loads(pickle.dumps(dtype))

print('\ndtype ids')
print(id(dtype))
print(id(dtype2))
```

Outputs
```
dtype tests
True
False
True

array ids
140086266820160
140086266820160
140086274994064

dtype ids
140086266820160
140086274399856
```

**Comment by akaszynski** [comment]
@whophil, can we close this out now that #2394 is merged?

**Comment by whophil** [comment]
@akaszynski yes, this can be closed now! Thanks for the report @WesleyTheGeolien
