### ISSUE TITLE
Clip filter returns object of wrong type

### ISSUE THREAD

**Issue by supersubscript** [pyvista/pyvista#238]
```python
import pyvista as pv
sphere = pv.Sphere()
sphere
```
```python
PolyData (0x7f48fc3ae948)
  N Cells:	1680
  N Points:	842
  X Bounds:	-4.993e-01, 4.993e-01
  Y Bounds:	-4.965e-01, 4.965e-01
  Z Bounds:	-5.000e-01, 5.000e-01
  N Scalars:	1
```
```python
sphere.clip('x', [0,0,0])
```
```python
UnstructuredGrid (0x7f48fb5c68e8)
  N Cells:	980
  N Points:	561
  X Bounds:	-4.993e-01, 0.000e+00
  Y Bounds:	-4.965e-01, 4.965e-01
  Z Bounds:	-5.000e-01, 5.000e-01
  N Scalars:	1

```

**Comment by banesullivan** [comment]
Currently, the `.clip` filter always returns an unstructured grid (I intended for this when I implemented this filter) which, to my knowledge, is consistent with ParaViews “clip” filter. Generally speaking, the `.clip` filter will have to return an UnstructuredGrid when clipping Rectilinear or Structured mesh types but I suppose it could return PolyData when clipping PolyData. 

Docs for `vtkClipDataSet`: https://vtk.org/doc/nightly/html/classvtkClipDataSet.html#details

At the moment, the clip filter uses the `vtkClipDataSet` filter which is designed to handle any input and always yield an UnstructuredGrid. We could add a hook if the input is PolyData to use the `vtkClipPolyData` filter instead which should return a PolyData output.
