### ISSUE TITLE
pv.background_color is not iterable in v0.34.0

### ISSUE THREAD

**Issue by maxcapodi78** [pyvista/pyvista#2409]
**Describe the bug, what's wrong, and what you expect:**

New version of pyvista has made pv.background_color not iterable object.

-----

**To Reproduce**

```py
[i for i in pv.background_color]

```

**Comment by adeak** [comment]
@akaszynski I'd say absolutely, although semantically speaking tuples are not usually meant to be iterated :) But yes, I think we should make it iterable. Question is whether we also want to implement `__getitem__` to allow `color[i]` (this would automatically make the class iterable if memory serves).

**Comment by akaszynski** [comment]
> Question is whether we also want to implement `__getitem__` to allow `color[i]` (this would automatically make the class iterable if memory serves).

That would be a necessity as well I think.

**Comment by akaszynski** [comment]
@adeak, let me know if you want to take this one up. A few projects (like [pyaedt](https://github.com/pyansys/pyaedt)) depend on it.

**Comment by adeak** [comment]
I guess it's reasonable to think of the `Color` class as a namedtuple with some useful bells and whistles that help with conversions.

> @adeak, let me know if you want to take this one up. A few projects (like [pyaedt](https://github.com/pyansys/pyaedt)) depend on it.

Sure, I can do it if it's critical. Do you want to put this in a patch release?

**Comment by akaszynski** [comment]
> Do you want to put this in a patch release?

Yes, but let's wait a week to see if anything else crops up. There's an issue with docs where CGNSReader isn't showing up that's annoying.

**Comment by adeak** [comment]
In that case I'll wait a bit to see if @dcbr wants to do this themself.

**Comment by dcbr** [comment]
I can work on this yes. So a `Color` instance has to support indexing and iterating over its float RGB values (returning int values or including the alpha channel would break backward compatibility I guess)? I find that a bit unintuitive but if many users depend on that we can do so for backward compatibility.

@maxcapodi78 as a temporary workaround you can use `[c for c in pv.background_color.float_rgb]` to obtain the old behaviour.

**Comment by maxcapodi78** [comment]
@dcbr  thanks. 
Is float_rgb back compatible too or it has been added in latest version?

**Comment by dcbr** [comment]
No this was added in the latest version.

In short: the internal representation of colors was replaced by `Color` objects instead of `float` tuples, to support conversion between different representations. To get the old 'float tuple' representation, you can use the `float_rgb` property.
