### ISSUE TITLE
CGNSReader not showing up in the documentation

### ISSUE THREAD

**Issue by akaszynski** [pyvista/pyvista#2410]
The recently added CGNSReader isn't showing up in our documentation at https://docs.pyvista.org/api/readers/_autosummary/pyvista.get_reader.html

![image](https://user-images.githubusercontent.com/11981631/161254147-25f63843-2063-48dd-89b6-30ea9e2537e6.png)

**Comment by MatthewFlamm** [comment]
It also doesn't have it's own documentation page.

Since this has `good first issue` label, I will give a pointer for how to fix. It is missing in the list of Reader Classes at 
https://github.com/pyvista/pyvista/blob/542b37f2f0bc0c02c48655e0b1c00a4472c5c723/doc/api/readers/index.rst
