### ISSUE TITLE
a part of image not appear in screenshot images

### ISSUE THREAD

**Issue by minju967** [pyvista/pyvista#2425]
**Describe the bug, what's wrong, and what you expect:**

.obj file is rotated and showed and created screenshot image
when plotter.show(), object is complete all of part but creating image is not complete.

-----

**To Reproduce**

Please include a code snippet to reproduce the bug in the block below:

```py

    mesh = pv.read(path+'/'+file)
    plotter = pv.Plotter(off_screen=False, window_size=(1000,1000))
    plotter.add_mesh(mesh, color="gray")
    mesh.rotate_x(90)
    mesh.rotate_y(y)
    mesh.rotate_z(z)
    plotter.camera_position = (1.0, 0.0, 0.0)
    plotter.camera.elevation = e       # up, down
    plotter.camera.azimuth = a         # left. right
    plotter.camera.zoom(1.0)
    plotter.background_color = 'white'
    plotter.show(screenshot=name)
    plotter.screenshot(name)
    plotter.close()
```

**Screenshots**
**plotter.show()**
![스크린샷, 2022-04-04 15-30-07](https://user-images.githubusercontent.com/54441457/161487667-ad4e2c2e-d051-45e3-bcb0-7b81de2e72a4.png)

**plotter.screenshot(name)**
![screenshot_A0](https://user-images.githubusercontent.com/54441457/161487627-361bfb8b-4ce3-4960-841c-8d3e65fe374a.png)

-----

**System Information:**
 Please run the following code wherever you are experiencing the bug and paste the output below. This report helps us track down bugs and it is critical to addressing your bug:

```py
# Get system info
import pyvista as pv
print(pv.Report())
```

```txt
# Paste system info here
                OS : Linux
            CPU(s) : 20
           Machine : x86_64
      Architecture : 64bit
       Environment : Python
       File system : unknown
        GPU Vendor : NVIDIA Corporation
      GPU Renderer : NVIDIA GeForce RTX 3090/PCIe/SSE2
       GPU Version : 4.5.0 NVIDIA 510.47.03

  Python 3.9.7 (default, Sep 16 2021, 13:09:58)  [GCC 7.5.0]

           pyvista : 0.32.1
               vtk : 9.1.0
             numpy : 1.21.2
           imageio : 2.13.5
           appdirs : 1.4.4
            scooby : 0.5.11
            meshio : 4.4.6
        matplotlib : 3.5.1
             scipy : 1.7.3
              tqdm : 4.62.3
```

**Comment by akaszynski** [comment]
Hello,
Could you please zip and upload the file here? I think it just needs a simple scene bounds reset, but I'd like to double check.

**Comment by banesullivan** [comment]
Looks like a clipping planes issue. 

`plotter.camera.reset_clipping_range()` before screenshotting should fix it.
