### ISSUE TITLE
Sphere widget constant update

### ISSUE THREAD

**Issue by tomazbregar** [pyvista/pyvista#2455]
Hey,

I would have one question about changing the _sphere_widget_ observer from `EndInteractionEvent` to `InteractionEvent`. 

The reason why I am asking this is, because we are using _sphere_widgets_ in our package to move objects around the 3D display to enable the user to position them based on his requirements. We are also "snapping" objects to the mesh to help the user. But with the current  `EndInteractionEvent` the transducer only snaps when the interaction is finished. 

By changing the InteractionEvent, we could have it interactive all the time. We already tried that by hard-coding it in pyvista, as we are unable to change the state of the observer once it's initiated. 

Here how the interaction would like on your example:
![feature_1](https://user-images.githubusercontent.com/27701498/158837554-8a4953f7-4e7e-46e7-8fdc-45000e6e48dd.gif)

Here you can see how the interaction would look like on our application:
![feature](https://user-images.githubusercontent.com/27701498/158835337-63bc72d0-36bc-418a-96ce-f136c7a77cf5.gif)

Do you have an idea how to change that after the _sphere_widget_ is created? Or if that could be an additional option on your side? 

Best regards,
Tomaž

_Originally posted by @tomazbregar in https://github.com/pyvista/pyvista/discussions/2361_

**Comment by tomazbregar** [comment]
Hey,

is there any idea, if this functionality could be added to PyVista?

Best regards,
Tomaž

**Comment by banesullivan** [comment]
> Do you have an idea how to change that after the sphere_widget is created? Or if that could be an additional option on your side?

Changing after creation can be a bit of a pain.

We could add an option to use `InteractionEvent` in `add_sphere_widget()` or any custom interaction event, please see and review: #2882
