### ISSUE TITLE
Embedding Pyvista into flask with interactive UI.

### ISSUE THREAD

**Issue by raviraj3997** [pyvista/pyvista#2459]
Can we embed the pyvista plots in flask app with interactive UI?
Can someone share the example? 

This could be extension of #1195

**Comment by akaszynski** [comment]
@raviraj3997, this has been added in https://github.com/pyvista/pyvista/pull/2552. It's quite simplistic and I'd appreciate any additions to the example.

**Comment by ArioYD** [comment]
Did you find a solution on how to select an elements in pyvista flask using mouse (i.e. a  line or an area) and change its property interactively?

**Comment by banesullivan** [comment]
@ArioYD, That's not totally feasible at the moment, but with some of the changes coming in #3385, this may be improved and I will try to see if I can incorporate a flask+trame example when merging
