### ISSUE TITLE
Point data of a shallow-copied mesh is no longer a view after adding the mesh to a plotter

### ISSUE THREAD

**Issue by p-j-smith** [pyvista/pyvista#2461]
**Describe the bug, what's wrong, and what you expect:**

If I make a shallow copy of a mesh, I would expect that the point data of the copied mesh is a view into that of the original mesh (rather than a copy). As such, by modifying the point data of one mesh, the point data of the second mesh should also be modified. This is indeed the case currently. However, if one of the meshes is then added to a plotter, this behaviour breaks.

Note, this was not an issue in version 0.33.2 (point data were still modified after adding the mesh to a plotter), but I think versions >=0.33.3 all have this behaviour.

-----

**To Reproduce**

```py
import pyvista as pv

sphere = pv.Sphere()
sphere.point_data['numbers'] = np.arange(sphere.n_points)
sphere2 = sphere.copy(deep=False)

sphere['numbers'] *= -1  # sphere2 'numbers' are also modified

plotter = pv.Plotter()
plotter.add_mesh(sphere, scalars=None)

sphere['numbers'] *= -1  # sphere2 'numbers' are NOT modified

```
-----

**System Information:**
```txt

--------------------------------------------------------------------------------
  Date: Wed Apr 13 09:42:15 2022 BST

                OS : Linux
            CPU(s) : 16
           Machine : x86_64
      Architecture : 64bit
       Environment : Jupyter
        GPU Vendor : NVIDIA Corporation
      GPU Renderer : NVS 310/PCIe/SSE2
       GPU Version : 4.5.0 NVIDIA 390.144

  Python 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:57:06)
  [GCC 9.4.0]

           pyvista : 0.34.0
               vtk : 9.0.3
             numpy : 1.21.4
           imageio : 2.10.3
           appdirs : 1.4.4
            scooby : 0.5.7
        matplotlib : 3.5.1
         pyvistaqt : 0.7.0
           IPython : 7.29.0
             scipy : 1.7.2
              tqdm : 4.62.3
            meshio : 4.4.6
--------------------------------------------------------------------------------

```

**Comment by p-j-smith** [comment]
So I can't reproduce the desired behaviour (where point data is still modified after adding the mesh to a plotter). If I create a new environment with pyvista 0.33.2, point data is no longer a viewer after adding a copied mesh to a plotter. So it seems that the issue is probably not with pyvista, but with one of its dependencies instead.

**Comment by whophil** [comment]
The root cause seems to be that `MapperHelper.configure_scalars_mode` creates a deep copy of the data when setting its title.

https://github.com/pyvista/pyvista/blob/b50614a0034d6d4890fac22f162b0f739754e8d5/pyvista/plotting/mapper.py#L254-L263

Note that the third positional argument for `point_data.set_array()` is the flag for `deep_copy`, and it is currently set to `True`. I'm not sure why this is needed - perhaps @akaszynski knows?

Other note: The method `np.shares_memory()` can tell you whether one arrays is a view of another, and is extremely useful for debugging and _testing_ this type of thing.

**Comment by akaszynski** [comment]
> The root cause seems to be that `MapperHelper.configure_scalars_mode` creates a deep copy of the scalar point/cell data and reassigns it to the mesh.
> 
> https://github.com/pyvista/pyvista/blob/b50614a0034d6d4890fac22f162b0f739754e8d5/pyvista/plotting/mapper.py#L254-L263
> 
> Note that the third positional argument for `point_data.set_array()` is the flag for `deep_copy`, and it is currently set to `True`. I'm not sure why this is needed - perhaps @akaszynski knows?
> 
> Other note: The method `np.shares_memory()` can tell you whether one array is a view of another, and is extremely useful for debugging and _testing_ this type of thing.

You're correct, it should be shallow with `deep_copy=False`. Could you open a PR for this?

**Comment by akaszynski** [comment]
> Should this be added as a test if it wasn't already captured in #2754 ?

It's a cheap edge case to test. Testing in #2888.
