### ISSUE TITLE
Plotter.open_gif() increase the parameter that support framerate

### ISSUE THREAD

**Issue by YexiangYan** [pyvista/pyvista#2468]
**Plotter.open_gif() increase the parameter that support framerate**
Thanks for the excellent 3D visualization library. Recently, when drawing gif animations, I feel that the framerate is too fast. Can function Plotter.open_gif() increase the parameter that support framerate? Just like open_movie does. Thanks.

**Comment by akaszynski** [comment]
> Recently, when drawing gif animations, I feel that the framerate is too fast. Can function Plotter.open_gif() increase the parameter that support framerate?

Added that and more in #2484. We'll have this out in the next release, but if you want the bleeding edge, see our [installation documentation](https://docs.pyvista.org/getting-started/installation.html#installing-the-current-development-branch-from-github) for installing from our development branch.
