### ISSUE TITLE
Can PyVista run without display?

### ISSUE THREAD

**Issue by kjelljorner** [pyvista/pyvista#247]
I want to use PyVista on a compute node without display. If I don't install pyqt in my conda environment it works fine. Problem is that I need pyqt as a dependency for another package. Is there some way to prevent PyVista from trying to connect to the X display? Currently I get the following error:
```
qt.qpa.screen: QXcbConnection: Could not connect to display localhost:14.0
Could not connect to any X display.
Segmentation fault
```

**Comment by akaszynski** [comment]
I'm unable to reproduce this on a google cloud compute instance (Ubuntu 18.04, latest pyvivista).

Can you clone [no_qt_import](https://github.com/pyvista/pyvista/tree/no_qt_import)?  And check to see if the fix works for you?

**Comment by kjelljorner** [comment]
Sorry, my bad. I found out that the culprit was matplotlib. Pyvista is working fine. 
I googled around a bit yesterday and found something that seems to work generally:
`export QT_QPA_PLATFORM='offscreen'`
So if this environmental variable is set there is no crash upon import of matplotlib. Setting a different backend for matplotlib also works fine.
