### ISSUE TITLE
Add reader extension checks

### ISSUE THREAD

**Issue by akaszynski** [pyvista/pyvista#2471]
I'm not sure that we should be policing whether the input files have a suffix that matches, unless there is a reason for this particular reader.  For example, ANSYS Fluent can output Ensight files which are nice to read into vtk, but it outputs with nonstandard suffixes.  These sorts of checks would require the user to rename the files or subclass the reader.  Both not attractive options.  If we want to have a check for suffix, I would prefer a warning, although if there is no file or folder at all than the error makes sense.

It would be good to move this logic into the base class to keep the behavior consistent across Readers for these types of checks.

_Originally posted by @MatthewFlamm in https://github.com/pyvista/pyvista/pull/2460#discussion_r851623154_

**Comment by njneeteson** [comment]
I personally would vote against having any kind of suffix checks enforced on the file reader subclasses. If someone has specifically imported a particular reader to use it to load a file with a weir filename, they mostly likely know exactly what they are doing, and if they just use `pyvista.read` they'll get an appropriate reader for their suffix anyways, if it exists. Maybe you could add a flag to the init for the base class, that defaults to `False`, to enable suffix checking if people want to turn on guard rails - in that case you could add another parameter that defaults to `None` in the base class and is set in the sub-classes to (if not overridden), to let the user override the suffix to check for.

There's plenty of situations where your images/files came from some antiquated system and the extensions are messed up or capitalized or whatever. It's not difficult to fix extensions or even to automate fixing extensions as part of either your data transmission or visualization pipelines, but at the same time I don't see the up-side of forcing users to do it either.

**Comment by MatthewFlamm** [comment]
Since my comment is taken out of context, I want to also make it clear that I strongly prefer no suffix checking.  If there is, there should be ability to turn off.

**Comment by adam-grant-hendry** [comment]
I am completely fine with no suffix checking. This seems more aligned with python's duck typing approach.

Does `pyvista` need to handle warning messages from VTK for any reason? That was my only thought (it doesn't require an extension check though).

I agree type checking should be done by the user. If anything, supported file types for the reader should be listed in the documentation. I think we should be doing that.

**Comment by akaszynski** [comment]
Closing as it seems like there's agreement to not include suffix checking.
