### ISSUE TITLE
OpenFOAMReader.set_active_time_value doesn't work without re-initializing the reader

### ISSUE THREAD

**Issue by piyueh** [pyvista/pyvista#2473]
**Describe the bug, what's wrong, and what you expect:**

Says `reader` is an `OpenFOAMReader` instance. The member `reader.set_active_time_value(...)` only works when first time calling it. Further calls of `reader.set_active_time_value(...)` does not really change the temporal data that will be read later (though `reader.active_time_value` does get changed).

It's probably VTK's problem because directly calling `reader.reader.SetTimeValue(...)` does not resolve the problem. **_However, if I directly call_** `reader.reader.UpdateTimeStep(...)`**_, things work fine, as expected._** See CASE 3 in the code below.

Another way to make `set_active_time_value` (and `SetTimeValue`) work is to re-initialize the reader every time, which is annoying though. See CASE 2 in the code below.

Unfortunately, I'm not familiar with VTK enough to say we should change `SetTimeValue` to `UpdateTimeStep`.

This is related to #924 

-----

**To Reproduce**

The code below will download the OpenFOAM simulation results of cavity flow and then run the tests.

```py
import tarfile
import hashlib
import pathlib
import urllib.request
import pyvista

tar_loc = pathlib.Path(__file__).resolve().parent.joinpath("cavity.tar.gz")

# download the tarball if not exsit
if not tar_loc.exists():
    urllib.request.urlretrieve(
        "https://gwu.box.com/shared/static/acuvk11lxmk93bbrhhog59hgiyvbfq9t.gz",
        "cavity.tar.gz"
    )

# check if the existing/downloaded tarball is the correct one
with open(tar_loc, "rb") as fobj:
    assert (
        hashlib.sha256(fobj.read()).hexdigest() ==
        "18d26544c7a64396d4653b5c289e3d82a425828a059acef9772fd0616dfb36c7"
    ), "SHA256 of cavity.tar.gz did not match."

# decompress
with tarfile.open(tar_loc, "r") as fobj:
    fobj.extractall(tar_loc.parent)

# CASE 1: NOT WORKING
reader = pyvista.OpenFOAMReader('cavity/cavity.foam')
print("Not working:")
for t in reader.time_values:
    reader.set_active_time_value(t)
    data = reader.read()["internalMesh"].cell_data["U"]
    print(f"\tT={reader.active_time_value}, total energy:{(data**2).sum()}")

# CASE 2: WORKING
print("Working:")
for t in reader.time_values:
    reader = pyvista.OpenFOAMReader('cavity/cavity.foam')
    reader.set_active_time_value(t)
    data = reader.read()["internalMesh"].cell_data["U"]
    print(f"\tT={reader.active_time_value}, total energy:{(data**2).sum()}")

# CASE 3: WORKING
print("Working:")
reader = pyvista.OpenFOAMReader('cavity/cavity.foam')
for t in reader.time_values:
    reader.reader.UpdateTimeStep(t)
    data = reader.read()["internalMesh"].cell_data["U"]
    print(f"\tT={reader.active_time_value}, total energy:{(data**2).sum()}")
```

-----

**System Information:**

```txt
--------------------------------------------------------------------------------
  Date: Sun Apr 17 15:39:06 2022 EDT

                OS : Linux
            CPU(s) : 12
           Machine : x86_64
      Architecture : 64bit
       Environment : IPython
        GPU Vendor : Intel
      GPU Renderer : Mesa Intel(R) UHD Graphics (CML GT2)
       GPU Version : 4.6 (Compatibility Profile) Mesa 22.0.1

  Python 3.9.11 (main, Mar 29 2022, 19:08:29)  [GCC 7.5.0]

           pyvista : 0.33.3
               vtk : 9.1.0
             numpy : 1.21.2
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.12
        matplotlib : 3.5.1
             PyQt5 : 5.9.2
           IPython : 8.1.1
        ipyvtklink : 0.2.2
             scipy : 1.7.3

  Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904
  for Intel(R) 64 architecture applications
--------------------------------------------------------------------------------
```

**Comment by MatthewFlamm** [comment]
This `UpdateTimeStep` seems like an undocumented method, or at least I can't find the documentation. Good find!

> Unfortunately, I'm not familiar with VTK enough to say we should change `SetTimeValue` to `UpdateTimeStep`.

It seems like you have it mostly figured out to me.  I think you can swap out `SetTimeValue` to `UpdateTimeStep` here
 https://github.com/pyvista/pyvista/blob/18c299263a4038f004bb07ac35899f243b3b39b4/pyvista/utilities/reader.py#L650-L658

Adding some good tests would help convince that it is working and would catch regressions if this undocumented method changes in the future.  If you prefer not to implement I will

**Comment by MatthewFlamm** [comment]
Documented here https://vtk.org/doc/nightly/html/classvtkAlgorithm.html#af8c35754df1cb02cf74aa3ea0cd224ac

All readers subclassed from `vtkAlgorithm` might be able to use this method.

**Comment by piyueh** [comment]
@MatthewFlamm I created a PR (#2485 ). And I found an old discussion regarding using `UpdateTimeStep` in VTK 7.1:  [https://public.kitware.com/pipermail/vtkusers/2016-November/097070.html](https://public.kitware.com/pipermail/vtkusers/2016-November/097070.html). Seems `SetTimeValue` was already not working at that time.
