### ISSUE TITLE
Statically embed trame's client view

### ISSUE THREAD

**Issue by jorgepiloto** [pyvista/pyvista#2475]
🐞 **Problem**

All the examples listed in the [Brief Examples] section are interactive, meaning that you can rotate and zoom the rendered output. However, those collected in the [Examples] page show a static output.

This is because [sphinx-gallery] is not fully capturing the output or, at least, not allowing it to be interactive.

💡 **Solution**

There are two approaches here:

1. Investigate [sphinx-gallery capturing output representations] and how to properly implement those for PyVista graphics.
2. Use [jupytext] to convert examples from `*.py` to `*.ipynb` at doc buiilding time while applying `nbsphinx` to properly render notebooks output. Taking advantage of [nbsphinx-gallery], output should still be displayed in the gallery thumbnails. 

[Brief Examples]: https://docs.pyvista.org/#brief-examples
[Examples]: https://docs.pyvista.org/examples/index.html
[jupytext]: https://github.com/mwouts/jupytext
[sphinx-gallery]: https://sphinx-gallery.github.io/stable/index.html
[sphinx-gallery capturing output representations]: https://sphinx-gallery.github.io/stable/auto_examples/plot_3_capture_repr.html
[nbsphinx-gallery]: https://nbsphinx.readthedocs.io/en/0.6.1/subdir/gallery.html

**Comment by akaszynski** [comment]
I agree that this is a desired feature. Not all examples will be able to support his feature, but we can provide the option to enable or disable this on an example by example basis.

**Comment by panziyi1** [comment]
It there any progress here? Since it's been such a while..no offence

**Comment by banesullivan** [comment]
This isn't of the highest priority AFAIK... while it would be "nice", it's a rather challenging problem that will require a lot of other work to better "transfer/convert" a VTK render window to VTK.js so that a critical mass of the examples can be meaningfully interactive. Anything with special rendering techniques or with certain actors like bounds likely won't be able to be interactive in the browser.
