### ISSUE TITLE
Cone direction

### ISSUE THREAD

**Issue by kjelljorner** [pyvista/pyvista#249]
The current Cone class does not capture the direction argument. I think that his should be done with the src.SetDirection(direction) argument. Below is the current code.

```
    src = vtk.vtkConeSource()
    src.SetAngle(angle)
    src.SetCapping(capping)
    src.SetCenter(center)
    src.SetHeight(height)
    src.SetRadius(radius)
    src.SetResolution(resolution)
    src.Update()
    return pyvista.wrap(src.GetOutput())
```

**Comment by banesullivan** [comment]
Thanks for pointing this out, @kjelljorner! This is definitely a mistake on my part as I added some of those geometric objects during a code sprint. 

I will update the code and this will be on the next release.

**Comment by kjelljorner** [comment]
I think there are some more issues with this code. The "angle" and "radius" arguments are kind of mutually exclusive as the height together with either of these defines the cone. It will therefore depend on the order that they are applied. I adapted the code below for my purposes to define the code based on the angle only. Not sure how to handle both options. Also, it seems that the order below of Center, Direction, Height and either Radius or Angle gives the right result, while changing the order can give strange results.

```
src = vtk.vtkConeSource()
src.SetCapping(capping)
src.SetCenter(center)
src.SetDirection(direction)
src.SetHeight(height)
src.SetAngle(angle)
#src.SetRadius(radius)
src.SetResolution(resolution)
src.Update()
```

**Comment by banesullivan** [comment]
That's quite strange that the order matters here... typically the order doesn't matter with setting parameters of VTK algorithms as long as all calls are prior to the `Update()` call.

Considering the issue with the `angle` parameter, I propose we choose the same convention that ParaView uses and outright ignore the `angle` parameter since the cone can be defined using `direction`:

<img width="563" alt="Screen Shot 2019-06-13 at 4 46 47 PM" src="https://user-images.githubusercontent.com/22067021/59472174-d9631300-8dfa-11e9-9775-46f3c47fafe6.png">

Thoughts on this, @kjelljorner?

**Comment by kjelljorner** [comment]
I'll not have time to look at this until tomorrow, but I would do it something like this. As both options are possible in VTK, they should also in my opinion be so in PyVista. With the code below, there is preference for the radius if both arguments are given. The user is also warned. If none of them is given, the standard radius of 1 is used.
```
def Cone(..., angle=None, radius=None,...):
    src = vtk.vtkConeSource()
    src.SetCapping(capping)
    src.SetCenter(center)
    src.SetDirection(direction)
    src.SetHeight(height)
    if angle and radius:
        # Print warning to user and take radius as preference.
        print("Both radius and angle specified. Using radius.")
        src.SetRadius(radius)
    elif angle and not radius:
        src.SetAngle()
    elif not angle and radius:
        src.SetRadius()
    elif not angle and not radius:
        src.SetRadius(1)
    src.SetResolution(resolution)
    src.Update()
```
Best,
Kjell

**Comment by kjelljorner** [comment]
Hello again,

I tested again and this code seems to work as intended for me. It will raise an exception if both angle and radius is specified at once. I think this is the appropriate way to do it to alert the user of the unintented behavior. About the order, it doesn't seem to matter now that I tested it again. I must have been confused. The only disadvantage is that the default of radius 0.5 is not given explicitly, but it could be added in the docstring.

```
def Cone(center=(0., 0., 0.), direction=(1., 0., 0.), height=1.0, radius=None,
         capping=True, angle=None, resolution=6):
    """Create a cone
    Parameters
    ----------
    center : np.ndarray or list
        Center in [x, y, z]. middle of the axis of the cone.
    direction : np.ndarray or list
        direction vector in [x, y, z]. orientation vector of the cone.
    height : float
        height along the cone in its specified direction.
    radius : float
        base radius of the cone
    capping : bool
        Turn on/off whether to cap the base of the cone with a polygon.
    angle : float
        The angle degrees between the axis of the cone and a generatrix.
    resolution : int
        number of facets used to represent the cone
    """
    src = vtk.vtkConeSource()
    src.SetCapping(capping)
    src.SetDirection(direction)
    src.SetCenter(center)
    src.SetHeight(height)
    if angle and radius:
        raise Exception ("Both radius and angle specified. They are mutually exclusive.")
    elif angle and not radius:
        src.SetAngle(angle)
    elif not angle and radius:
        src.SetRadius(radius)
    elif not angle and not radius:
        src.SetRadius(0.5)
    src.SetResolution(resolution)
    src.Update()
    return pv.wrap(src.GetOutput())

```
Best,
Kjell

**Comment by banesullivan** [comment]
Thanks drafting and testing this, @kjelljorner! It looks good to me!

Would you want to make a pull request to add these changes? If not, id be happy to copy/paste them

**Comment by kjelljorner** [comment]
No problem, @banesullivan! I am a big fan of what you are doing with PyVista. VTK is intimidating at first but PyVista is just as simple and pythonic as it should be. I haven't really learned all this push/pull stuff yet so please go ahead and do the changes.

**Comment by banesullivan** [comment]
I’m so pleased to hear that! We couldn’t maintain PyVista without all the community support from issues like these, so thanks for contributing!

I’ll move forward with these changes

**Comment by banesullivan** [comment]
Hi @kjelljorner - would you mind if I quoted you on our soon-to-come landing page for the PyVista project? Specifically this quote from :

> I am a big fan of ... PyVista. VTK is intimidating at first but PyVista is just as simple and pythonic as it should be. 

Which would look like this (a sample from a website template I'm using. It'd have your GitHub profile picture and user name).

<img width="822" alt="Screen Shot 2019-06-18 at 12 18 14 PM" src="https://user-images.githubusercontent.com/22067021/59709177-66bfb200-91c3-11e9-978f-febd41ba9143.png">

**Comment by kjelljorner** [comment]
Hello @banesullivan! I would be happy to. Minor: "pythonic" should probably be with a capital P. I wouldn't mind if you removed the three dots as I can safely say that "I am a big fan of PyVista".

**Comment by banesullivan** [comment]
Sounds, good, thanks!
