### ISSUE TITLE
Align `pv.read` and `pv.get_reader`

### ISSUE THREAD

**Issue by MatthewFlamm** [pyvista/pyvista#2494]
**Describe what maintenance you would like added.**

It would be ideal to have `pv.read` be a shortcut for `pv.get_reader`.  This is a super simplified example, but in the most straightforward case, it would look like this:

```py
def read(filename):
    reader = pv.get_reader(filename)
    return reader.read()
```

Then we only need to maintain vtk readers in one location, while maintaining the one-liner of `pv.read()` as compared to the two liner above.

### Complexities

- Instead of allowing users to use the `attrs` argument to `pv.read`, it would be better to use the Reader class where we expose methods and attributes.  We should deprecate or remove this argument.
- Not all readers in `pv.read` are implemented as a class.  Here is a checklist of missing Reader classes:
- [ ] vtkBMPReader
- [ ] vtkDEMReader
- [ ] vtkJPEGReader
- [ ] vtkMetaImageReader
- [ ] vtkNrrdReader
- [ ] vtkPNGReader
- [ ] vtkPNMReader  <- not tested
- [ ] vtkSLCReader
- [ ] vtkTIFFReader
- [ ] vtkGLTFReader
- [ ] vtkHDRReader
- [ ] vtkFluentReader  <- not tested
- [ ] vtkMFIXReader  <- not tested
- [ ] vtkPTSReader
- [ ] vtkAVSucdReader
- [ ] vtkSegYReader
- [ ] vtkHDFReader

Seperate implementations in fileio that do not exist in Readers classes:
- [ ] vtkExodusIIReader

**Comment by MatthewFlamm** [comment]
I'm thinking that we could expose the most basic Reader class in the `readers` module for each of these, except for `vtkExodusIIReader` for the time being.  This would keep the scope of this initiative reasonable.

**Comment by akaszynski** [comment]
Agree with this approach.
