### ISSUE TITLE
link_views() not working for pythreejs

### ISSUE THREAD

**Issue by TermeHansen** [pyvista/pyvista#2499]
**Describe the bug, what's wrong, and what you expect:**

Using the the link_views() function on plotter for multiviews dows not work for pythreejs backends, but working fine for panel (vtk.,js). Is this a problem on pythreejs side or here?

-----

**To Reproduce**

Please include a code snippet to reproduce the bug in the block below:

```py
import pyvista as pv
from pyvista import examples
plotter = pv.Plotter(shape=(1, 2))

plotter.add_text("Airplane 1\n", font_size=30, color='grey')
plotter.add_mesh(examples.load_airplane(), show_edges=False, color='grey')

plotter.subplot(0, 1)
plotter.add_text("Airplane 2\n", font_size=30, color='grey')
plotter.add_mesh(examples.load_airplane(), show_edges=False, color='grey')

plotter.window_size = [1200, 400]
plotter.background_color = 'white'
plotter.link_views()
plotter.show(jupyter_backend='panel')

```

**Screenshots**
![image](https://user-images.githubusercontent.com/6922018/164710004-fa2a766d-a2fa-4d26-93f2-d869b2fb7888.png)

-----

**System Information:**
 Please run the following code wherever you are experiencing the bug and paste the output below. This report helps us track down bugs and it is critical to addressing your bug:

```py
# Get system info
import pyvista as pv
print(pv.Report())
```

```txt

--------------------------------------------------------------------------------
  Date: Fri Apr 22 13:59:16 2022 W. Europe Summer Time

                OS : Windows
            CPU(s) : 40
           Machine : AMD64
      Architecture : 64bit
               RAM : 255.9 GiB
       Environment : Jupyter
        GPU Vendor : NVIDIA Corporation
      GPU Renderer : Quadro K620/PCIe/SSE2
       GPU Version : 4.5.0 NVIDIA 511.79

  Python 3.10.4 | packaged by conda-forge | (main, Mar 24 2022, 17:34:17) [MSC
  v.1929 64 bit (AMD64)]

           pyvista : 0.34.0
               vtk : 9.1.0
             numpy : 1.22.3
           imageio : 2.17.0
           appdirs : 1.4.4
            scooby : 0.5.12
        matplotlib : 3.5.1
             PyQt5 : 5.12.3
           IPython : 8.2.0
        ipyvtklink : 0.2.2
              tqdm : 4.64.0
            meshio : 5.3.4
--------------------------------------------------------------------------------


```

**Comment by akaszynski** [comment]
> Is this a problem on pythreejs side or here?

This is a problem on our end and reasonably easy to fix (just use the same camera).

I'll have this fixed in a follow-up PR.

**Comment by TermeHansen** [comment]
What about the missing text (and I think the same goes for lines)‽

**Comment by akaszynski** [comment]
> What about the missing text (and I think the same goes for lines)‽

There are plenty of features that need to be ported over to the threejs representation. I'm working on auto-sizing first in https://github.com/jupyter-widgets/pythreejs/pull/374 and a follow-up https://github.com/jupyter-widgets/pythreejs/pull/376. It's going to be slow going for those because the maintainer is out, but I'll see about getting the pyvista side ready.
