### ISSUE TITLE
smooth shading and textures is broken

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#251]
it looks like texture coordinates are not preserved when smooth shading calls the `.extract_surface()` filter:

https://github.com/pyvista/pyvista/blob/c7c63eaa762baeae312fe23d9c6d69f20b9610bb/pyvista/plotting.py#L774-L782

Example:

```py
>>> from pyvista import examples
>>> sphere = examples.load_globe()
>>> sphere.plot(smooth_shading=True)
Traceback (most recent call last):
  File "/Users/bane/anaconda3/envs/dev/lib/python3.7/site-packages/sphinx_gallery/gen_rst.py", line 394, in _memory_usage
    out = func()
  File "/Users/bane/anaconda3/envs/dev/lib/python3.7/site-packages/sphinx_gallery/gen_rst.py", line 382, in __call__
    exec(self.code, self.globals)
  File "/Users/bane/Documents/OpenGeoVis/Software/pyvista/examples/02-plot/plot-shading.py", line 21, in <module>
    sphere.plot(smooth_shading=True)
  File "/Users/bane/Documents/OpenGeoVis/Software/pyvista/pyvista/plotting.py", line 228, in plot
    plotter.add_mesh(var_item, **kwargs)
  File "/Users/bane/Documents/OpenGeoVis/Software/pyvista/pyvista/plotting.py", line 928, in add_mesh
    raise AssertionError('Input mesh does not have texture coordinates to support the texture.')
AssertionError: Input mesh does not have texture coordinates to support the texture.
```

**Comment by GuillaumeFavelier** [comment]
I can't reproduce this bug on my configuration for some reason. I use the master version of the code.

This is what I tried:
```py
from pyvista import examples
sphere = examples.load_globe()
sphere.plot(smooth_shading=True)
```
![image](https://user-images.githubusercontent.com/18143289/59429344-e6bed400-8ddf-11e9-9894-ffacbe5851e5.png)
 
And inside a jupyter notebook (smooth shading not supported yet apparently):

![image](https://user-images.githubusercontent.com/18143289/59429415-0fdf6480-8de0-11e9-9cb7-ec388d1f4545.png)

**Comment by banesullivan** [comment]
> And inside a jupyter notebook (smooth shading not supported yet apparently):

Yeah... the VTKjs converter in PyVista needs to be overhauled to account for different plotting properties like shading, text, etc. and then it needs to be set up for plugging into `panel` per https://github.com/pyviz/panel/issues/408#issuecomment-500153052

This will be a rather big task so I'm not sure when I'll have the time to get around to this

**Comment by banesullivan** [comment]
> I can't reproduce this bug on my configuration for some reason. I use the master version of the code.

Okay weird... this works for me now. I must have been working on some older state of the project when I created this issue. Apologies!
