### ISSUE TITLE
Fix docstring and return of export_obj

### ISSUE THREAD

**Issue by tkoyama010** [pyvista/pyvista#2512]
**Describe what maintenance you would like added.**

- A clear and concise description of the maintenance problem.
https://github.com/pyvista/pyvista/blob/04516fe3b1b556d8df4f105fb6f43ff874a9939b/pyvista/plotting/plotting.py#L4397-L4408
The docstring says that `export_obj` returns `vtkOBJExporter`, but it actually returns nothing. Please modify the docstring and remove the return.

- If you are requesting maintenance for a specific line of source code, please include the permanent link for that line.
None

- Feel free to include pseudocode or screenshots of the requested outcome.
None

-----
_Ref https://github.com/pyvista/pyvista/pull/2451#discussion_r857139720_

**Comment by RobPasMue** [comment]
I'll take charge of this one.

**Comment by tkoyama010** [comment]
Thanks.
