### ISSUE TITLE
Picking doesn't work with render passes

### ISSUE THREAD

**Issue by apwebber** [pyvista/pyvista#2520]
**Describe the bug, what's wrong, and what you expect:**

When shadows are enabled on a plot, picking meshes either doesn't do anything or throws an error. I've encountered two errors, they seem to be different for either pressing p or left clicking.

pressing p:
vtkInteractorStyle.cxx:937   WARN| vtkInteractorStyleTrackballCamera (0000018DBE1A2D80): no current renderer on the interactor style.

left clicking:
2022-04-27 11:21:10.522 (   3.270s) [                ]vtkOpenGLHardwareSelect:203    ERR| vtkOpenGLHardwareSelector (00000216393A90B0): Too many props. Currently only 16777214 props are supported.

-----

**To Reproduce**

Run the dragon shadows example as found [here](https://docs.pyvista.org/examples/04-lights/shadows.html).

Add this code after the `pyvista.Plotter` is defined:

`pl.enable_mesh_picking(style='surface', left_clicking=True)`

run the example with and without the line `pl.enable_shadows()`

-----

**System Information:**

```txt
Date: Wed Apr 27 11:25:08 2022 GMT Summer Time

                OS : Windows
            CPU(s) : 8
           Machine : AMD64
      Architecture : 64bit
               RAM : 15.7 GiB
       Environment : Python
        GPU Vendor : Intel
      GPU Renderer : Intel(R) Iris(R) Xe Graphics
       GPU Version : 4.5.0 - Build 30.0.100.9864

  Python 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit
  (AMD64)]

           pyvista : 0.34.0
               vtk : 9.1.0
             numpy : 1.21.2
           imageio : 2.16.2
           appdirs : 1.4.4
            scooby : 0.5.12
        matplotlib : 3.4.3
         pyvistaqt : 0.9.0
             PyQt5 : 5.15.4
           IPython : 7.28.0
             scipy : 1.7.1
              tqdm : 4.62.3
```

**Comment by banesullivan** [comment]
I'm able to reproduce this, and it's unclear to me if there's a solution to this... it appears to be an issue with any render passes and not limited to just shadows.

**Comment by akaszynski** [comment]
#4254 fixes this. Minimum working code:

```py
import pyvista as pv

sphere = pv.Sphere(center=(1, 0, 0))
cube = pv.Cube()

pl = pv.Plotter()
pl.add_mesh(sphere, color='r')
pl.add_mesh(cube, color='b')
pl.enable_mesh_picking()
pl.enable_shadows()
pl.show()
```

@banesullivan, please note that the issues with @4521 likely stem from other issues.
