### ISSUE TITLE
Closing renderer window freezes tkinter

### ISSUE THREAD

**Issue by thatuserb** [pyvista/pyvista#2521]
Using pyvista from within a tkinter application and exiting the renderer window somehow freezes tkinter.
I encounter this problem using
- Windows 10 
- Python 3.9.7 64bit
- pyvista 0.34.1
- vtk 9.1.0

with either of the following code snippets
```python
import pyvista as pv
import tkinter as tk

class App(tk.Tk):
    def __init__(self):
        super().__init__()

        button = tk.Button(
            self,
            text="Plot Sphere",
            command=self.plot_sphere
        )
        button.pack()
    
    def plot_sphere(self):
        pv.Sphere().plot()
        print("Renderer Closed")

app = App()
app.mainloop()
```

```python
import pyvista as pv
import tkinter as tk

pv.Sphere().plot()
print("Renderer Closed")

class App(tk.Tk):
    def __init__(self):
        super().__init__()

        button = tk.Button(
            self,
            text="Print foo",
            command=self.print_foo
        )
        button.pack()
    
    def print_foo(self):
        print("foo")

app = App()
app.mainloop()
```

In both cases the tkinter window is not interactive after exiting the renderer window. Other code (like `print("Renderer Closed")`) will be executed without problems.

**Comment by akaszynski** [comment]
This runs fine on Linux/Ubuntu 20.04. Does anyone have a Windows box to debug this?

**Comment by dcbr** [comment]
This is a VTK issue and will be fixed in their next release, see pyvista/pyvista-support#232 for context.
