### ISSUE TITLE
Unable to save PointSet to file

### ISSUE THREAD

**Issue by SuborbitalPigeon** [pyvista/pyvista#2556]
**Describe the bug, what's wrong, and what you expect:**

Creating a PointSet instance and trying to save it to a file fails.

-----

**To Reproduce**

```py
import numpy as np
import pyvista

rng = np.random.default_rng()
points = rng.random((10, 3))
pset = pyvista.PointSet(points)
pset.save("pset.vtk")
```

**Screenshots**

Not really a screenshot, but the result of this is:

```txt
ValueError: Invalid file extension for this data type. Must be one of: dict_keys([])
```

This suggests there are no supported formats (trying `ply` also doesn't work, for example).

-----

**System Information:**

```txt
--------------------------------------------------------------------------------
  Date: Tue May 03 13:53:48 2022 BST
                OS : Linux
            CPU(s) : 12
           Machine : x86_64
      Architecture : 64bit
       Environment : Python
        GPU Vendor : AMD
      GPU Renderer : AMD Radeon RX 5600 XT (NAVI10, DRM 3.44.0, 5.17.4-200.fc35.x86_64, LLVM 13.0.0)
       GPU Version : 4.6 (Core Profile) Mesa 21.3.8
  Python 3.10.4 (main, Mar 25 2022, 00:00:00) [GCC 11.2.1 20220127 (Red Hat
  11.2.1-9)]
           pyvista : 0.34.1
               vtk : 9.1.0
             numpy : 1.22.3
           imageio : 2.19.0
           appdirs : 1.4.4
            scooby : 0.5.12
        matplotlib : 3.5.2
             scipy : 1.8.0
--------------------------------------------------------------------------------
```

**Comment by ihsienlee** [comment]
I run you code, and I can get 'pset.vtk'.
I creat a new virtual environments to test.
`python3 -m venv pyvista-env`

`python -m pip install --upgrade pip`
`pip install vtk`
`pip install numpy`
`pip install imageio`
`pip install appdirs`
`pip install meshio`
`pip install scooby`
`pip install pyvista`

The follow list is packages' version:
             python :3.8
             pyvista : 0.34.1
             vtk : 9.1.0
             numpy : 1.22.3
           imageio : 2.19.0
           appdirs : 1.4.4
            scooby : 0.5.12
        matplotlib : 3.5.2
             scipy : 1.8.0

**Comment by tkoyama010** [comment]
Partially solved by https://github.com/pyvista/pyvista/pull/2571. PointSet does not have a Writer for vtk, so only xyz format can be saved.

**Comment by tkoyama010** [comment]
You can also save as PolyData.
```python
pset.cast_to_polydata().save("pset.vtk")
```
