### ISSUE TITLE
Add DecomposePolyhedra option to OpenFOAMReader

### ISSUE THREAD

**Issue by Failxxx** [pyvista/pyvista#2559]
## Proposal

I think it would be nice to expose the `DecomposePolyhedra` option for OpenFOAMReaders. It is very useful in some cases.

## Possible solution

There are several methods available  in `vtkOpenFOAMReader` [(c++ class definition)](https://vtk.org/doc/nightly/html/classvtkOpenFOAMReader.html#a18ae532b114baee4653303b2ba05d161). Here would be my solution, which worked for a few examples but would probably need more testing (I don't know?): 
* Add the two following methods in the `OpenFOAMReader` (pyvista/utilities/reader.py):
```py
def decompose_polyhedra_on(self):
    self.reader.DecomposePolyhedraOn()

def decompose_polyhedra_off(self):
    self.reader.DecomposePolyhedraOff()
```

**Comment by MatthewFlamm** [comment]
I agree.  If you make it a property with a setter we can also inspect whether this option is on or not for the Reader.

Are you planning on submitting a PR?  We do not have any datasets with polyhedral cells, but we can test that the vtk reader object is updated, which is enough IMO.

**Comment by Failxxx** [comment]
Yes I agree, it would also be nice to be able to inspect the state of this option. I will work on it tomorrow.
And yes I plan to submit a pull request. Thank you!
