### ISSUE TITLE
How to pick a line?

### ISSUE THREAD

**Issue by lucca-zhang** [pyvista/pyvista#2566]
### Discussed in https://github.com/pyvista/pyvista/discussions/2565

<div type='discussions-op-text'>

<sup>Originally posted by **lucca-zhang** May  5, 2022</sup>
Hi, I want to implement lines-picking with a mesh only built from lines. But `enable_cell_picking` doesn't work. 
For example, two lines are created as followings. And the exception _**"KeyError: 'Data array (original_cell_ids) not present in this dataset."**_ is raised while pressing P.  Did I misunderstand something? I am using pyvista 0.34.0 and python 3.8.3.
```
import numpy as np
import pyvista as pv

v = np.array([[0,0,0], [1,1,1], [2,2,2], [3,3,3], [0,1,2], [0,2,4]]).astype('float')
lines =[4, 0, 1, 2, 3, 3, 0, 4, 5]

pl = pv.Plotter()
mesh = pv.PolyData(var_inp=v, lines=lines, n_lines=2)
pl.add_mesh(mesh, pickable=True)
pl.enable_cell_picking(through=False, color='r')
pl.show()
```

BTW, I have noticed this [issue ](https://github.com/pyvista/pyvista-support/issues/127), which example is running with error **"AttributeError: 'PolyData' object has no attribute 'wireframe'"**. And it is also useless for picking an edge to set `stype='wireframe'` in `add_mesh`, which only supports picking a triangle surface. </div>

**Comment by tkoyama010** [comment]
This is a duplicate discussion, so this one is closed.
