### ISSUE TITLE
K3D for Jupyter notebook rendering

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#258]
We should look into using this toolset for some of the notebook rendering. From a  glance, it looks more robust than panel (what we currently use)

Take a look at the graphics in their README: https://github.com/K3D-tools/K3D-jupyter

**Comment by banesullivan** [comment]
So I think I'm going to try to land this in #300. The K3D notebook plotting is a lot nicer than VTKjs or X3D. 

Also I think K3D can handle volumes 👀

Here's a **hack** of an example:


```py
import pyvista as pv
from pyvista import examples
import k3d # https://github.com/K3D-tools/K3D-jupyter
import numpy as np

m = examples.download_st_helens().warp_by_scalar()

plotter = pv.Plotter(notebook=True)
plotter.add_mesh(m,)
plotter.show(nb_backend=False, auto_close=False)

# Now convert the scene to K3D
bnds = plotter.bounds
kgrid = bnds[0], bnds[2], bnds[4], bnds[1], bnds[3], bnds[5]

notebook_plotter = k3d.plot(axes=['xtitle', 'ytitle', 'ztitle'],
                            menu_visibility=True,
                            height=plotter.window_size[1]//2,
                            #background_color=background_color,
                            grid_visible=True,
                            grid=kgrid,
                           )
# Make a K3D object
kobj = k3d.vtk_poly_data(m.extract_geometry(),
                         name='foo',
                         opacity=1.0,
                         color_attribute=(m.active_scalar_name, *m.get_data_range()),
                         wireframe=False,)

# Add data to the scene and display
notebook_plotter += kobj
notebook_plotter.display()
```

And a GIF of me experimenting with the interface in a Jupyter notebook:


![ezgif com-video-to-gif](https://user-images.githubusercontent.com/22067021/60834471-fda5db80-a17d-11e9-9fff-7a5e02eb6a71.gif)

**Comment by MattiaMartinelli** [comment]
This is great. 
However, when I try to run the code it gives me this error: show() got an unexpected keyword argument 'nb_backend'
Am I doing something wrong?

**Comment by banesullivan** [comment]
Are you running off of this branch? Because these changes never got merged and are incredibly out of date

**Comment by banesullivan** [comment]
Closing per https://github.com/pyvista/pyvista/pull/300#issuecomment-619589269
