### ISSUE TITLE
Add POpenFOAMReader to read decomposed dataset in OpenFOAM format

### ISSUE THREAD

**Issue by Failxxx** [pyvista/pyvista#2590]
I need to read and manipulate some OpenFOAM files which are produced from a parallel computation and which are not reconstructed. As far as I know it is impossible to read these files using the OpenFOAM reader.

A first idea would be to implement a new class named 'POpenFOAMReader' as it is the case in vtk ([class definition](https://vtk.org/doc/nightly/html/classvtkPOpenFOAMReader.html)). This class exposes a new property (CaseType) which lets the user to tell if a decomposed mesh or reconstructed mesh should be read.

I think there is already something similar in pyvista: vtkPDataSetReader. But I am not sure the implementation should be the same as this example.

**Comment by MatthewFlamm** [comment]
It would be good to have this reader. A similar thing was suggested in #924, but it is good to have a focused feature request. It has quirks or bugs in it that make it tricky to implement. For example, see the link to the vtk issue in this [comment](https://github.com/pyvista/pyvista/issues/924#issuecomment-998007903).

**Comment by Failxxx** [comment]
Thank you for these information. I am indeed able to reproduce the bug described in the vtk issue. If I have the time I will try to work on the vtk issue to solve it (hope it won't be too complicated). However, here is what I think we could implement for the moment:

* fileio.py (line 60)
```python

'.foam': _vtk.lazy_vtkPOpenFOAMReader,

```
* _vtk.py (lines 492 - 496)
```python

def lazy_vtkPOpenFOAMReader():
    """Lazy import of the vtkPOpenFOAMReader"""
    from vtkmodules.vtkIOParallel import vtkPOpenFOAMReader

    return vtkPOpenFOAMReader()

```

* reader.py (lines 990 - 1017)
```python

@property
def case_type(self):
    """The property indicates whether decomposed mesh or reconstructed mesh should be read.

    Returns
    -------
    bool
        If ``True``, reconstructed mesh should be read.

    Examples
    --------
    >>> import pyvista
    >>> from pyvista import examples
    >>> filename = examples.download_cavity(load=False)
    >>> reader = pyvista.OpenFOAMReader(filename)
    >>> reader.case_type = False
    >>> reader.case_type
    False

    """
    return self.reader.GetCaseType()

@case_type.setter
def case_type(self, value):
    if value:
        self.reader.SetCaseType(1)
    else:
        self.reader.SetCaseType(0)

```

However, I am not sure about the lazy import since this vtkPOpenFOAMReader would become the class_reader of OpenFOAMReader (and it is not listed in the 'less used readers'). So maybe there is no need to add this lazy import and simply use the vtkPOpenFOAMReader as the class_reader.

The issue for the moment is when you select the wrong case type it generates a segmentation fault. An idea would be to add a try / except to catch it but I don't think it is a relevant solution. Overall, I think the given implementation could be enough... or am I missing something?

**Comment by MatthewFlamm** [comment]
> Your first idea was mine too. But since vtkPOpenFOAMReader inherits from vtkOpenFOAMReader ([class definition](https://vtk.org/doc/nightly/html/classvtkPOpenFOAMReader.html)) I think there is no need to have two different readers which could almost do the same things.

I think to settle this, we would need to confirm whether the `P` version can do everything that the non-`P` version can do for non parallel datasets.  As a pragmatic approach, we could implement as a separate a reader and then deprecate the non-`P` version later.

**Comment by MatthewFlamm** [comment]
You can do it now if you are okay with fixing merge conflicts once it is merged.  I'm okay with fixing conflicts in that PR if yours is merged first too.
