### ISSUE TITLE
Thresholding doesn't seem to threshold based on point scalars

### ISSUE THREAD

**Issue by adeak** [pyvista/pyvista#2595]
This might be a VTK bug.

Let's create a simple PolyData with 4 points and a polyline, with  some non-trivial point scalars. Then try to threshold it based on said scalars:
```py
import numpy as np
import pyvista as pv


rng = np.random.default_rng()
points = np.random.rand(4, 3)
lines = [4, 0, 1, 2, 3]
mesh = pv.PolyData(points, lines=lines)  # bug
# mesh = pv.PolyData(points)  # no bug
mesh.point_data['scalars'] = [0, 0, 0, 2]

# sanity check
assert not mesh.cell_data
assert len(mesh.point_data) == 1
assert mesh.active_scalars_name == 'scalars'

# insanity check
print(mesh.n_points)  # 4
print(mesh.threshold(-10).n_points)  # 4
print(mesh.threshold(0.5).n_points)  # 4
print(mesh.threshold(1.5).n_points)  # 4
print(mesh.threshold(2.5).n_points)  # 0
```

The sanity check demonstrates that there's a single data array: a points array named `'scalars'` and it's active. The value of the scalars is 0 on 3 points and 2 on 1 point. So when we threshold by these scalars at half-integer steps we'd expect this:
1. `threshold < 0` gives 4 points
2. `0 < threshold < 2` gives 1 point
3. `2 < threshold` gives 0 points.

Instead we see
1. `threshold < 2` gives 4 points
2. `2 < threshold` gives 0 points.

If we remove the `lines` from the polydata the behaviour switches to the expected one.

So it looks like adding the `lines` confused `threshold` into thinking that all 4 point data are scalars with value 2. I could imagine the lines having some cell data that overrides the point data (???) but the mesh claims that it has no cell data.

In the same way that there's separate polylines and polystrips, could these have separate data arrays too, being set by VTK and inaccessible to us? And in either case, is there something we can do about this in PyVista?

**Comment by MatthewFlamm** [comment]
`mesh.n_cells` is only 1. I believe the threshold filter is a cell operation although it can use the associated point data for the cell. Since one point on this cell meets the criteria, it keeps the cell and all points associated with it.

**Comment by adeak** [comment]
Bah, I'm fairly sure we've talked about that @MatthewFlamm, yet I keep forgetting that. Thanks, I should then update the docs!

**Comment by MatthewFlamm** [comment]
I don't often use PolyData other than to use it for probing other datasets.  There is this filter that may be useful here, I'm not quite sure what it does with the cell information. https://vtk.org/doc/nightly/html/classvtkThresholdPoints.html#details

**Comment by adeak** [comment]
So the reason why it works with no lines is that we specifially define each point to be its own vertex cell... I guess I can try doing that to my polylined mesh and see if it helps. Really I'm just trying to select a subset of points. Might as well use a boolean mask on the scalars and extract points...

> I don't often use PolyData other than to use it for probing other datasets. There is this filter that may be useful here, I'm not quite sure what it does with the cell information. https://vtk.org/doc/nightly/html/classvtkThresholdPoints.html#details

Thanks, I'll take a look.
