### ISSUE TITLE
Geodesic Path Issues: Computing length of 1D mesh and finding shortest path doesn't always work

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#260]
The length calculation for the geodesic path is not correctly implemented:

https://github.com/pyvista/pyvista/blob/7909cbe833ed3499de650eb1fc8b53e381943f53/pyvista/pointset.py#L1413

The `GetLength()` method of a VTK mesh actually returns the length of the diagonal of that mesh's bounding box:

> ```
> V.GetLength() -> float
> C++: double GetLength()
> 
> Return the length of the diagonal of the bounding box. THIS
> METHOD IS THREAD SAFE IF FIRST CALLED FROM A SINGLE THREAD AND
> THE DATASET IS NOT MODIFIED
> ```

Note that this is relevant to #252 

Pinging @supersubscript - are you using this feature? If so you may be getting incorrect results...

**Comment by banesullivan** [comment]
Also note that the shortest path is not always found:

```py
import pyvista as pv
from pyvista import examples

sphere = examples.load_globe()

geodesic = sphere.geodesic(10, sphere.n_points-40)

p = pv.Plotter(notebook=0)
p.add_mesh(geodesic, line_width=10, color='red', label='Geodesic Path')
p.add_mesh(sphere, show_edges=True, )
p.camera_position = [-1,-1,1]
p.add_legend()
p.show()
```

<img width="624" alt="Screen Shot 2019-06-14 at 11 17 25 AM" src="https://user-images.githubusercontent.com/22067021/59526470-38299a80-8e96-11e9-8f47-b5379f05574e.png">

**Comment by banesullivan** [comment]
The length issue should be resolved by #261 but I'm still concerned that the path is not always the shortest path as shown in https://github.com/pyvista/pyvista/issues/260#issuecomment-502193783

**Comment by supersubscript** [comment]
Huh, that's confusing. Thanks for raising the issue, @banesullivan. It does indeed affect my computations. 

Also very strange that path isn't always the shortest one.

**Comment by banesullivan** [comment]
I suppose the shortest path issue is on the VTK side with the `vtkDijkstraGraphGeodesicPath` algorithm and not something we can fix in PyVista? I’ll post this issue on VTKs discourse to see if anyone there has insight.

**Comment by banesullivan** [comment]
Posted on https://discourse.vtk.org/t/shortest-path-with-vtkdijkstragraphgeodesicpath/1150

**Comment by banesullivan** [comment]
Closing issue as I don't think there is anything we can do on the PyVista side

**Comment by banesullivan** [comment]
So this is actually just an artifact of how I created this Globe mesh - it’s split of the meridian so the path has to go to the poles to get around it
