### ISSUE TITLE
DOC: Anti-aliased example plots are all black

### ISSUE THREAD

**Issue by StefRe** [pyvista/pyvista#2686]
### Describe the bug, what's wrong, and what you expected.

Plots produced with `enable_anti_aliasing()` are all black:
* 4th and 5th plot in [Types of Shading](https://docs.pyvista.org/examples/02-plot/shading.html#sphx-glr-examples-02-plot-shading-py)
* [pyvista.Renderer.enable_anti_aliasing](https://docs.pyvista.org/api/plotting/_autosummary/pyvista.Renderer.enable_anti_aliasing.html)
* [pyvista.Plotter.enable_anti_aliasing](https://docs.pyvista.org/api/plotting/_autosummary/pyvista.Plotter.enable_anti_aliasing.html)

(the 3rd plot in [Plotting](https://docs.pyvista.org/api/plotting/plotting.html?highlight=enable_anti_aliasing#plotting-in-a-jupyter-notebook) is OK though)

### Steps to reproduce the bug.

See online docs.

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Mon May 23 21:57:57 2022 CEST

                OS : Linux
            CPU(s) : 2
           Machine : x86_64
      Architecture : 64bit
               RAM : 3.7 GiB
       Environment : Python
       File system : ext4
        GPU Vendor : Mesa/X.org
      GPU Renderer : llvmpipe (LLVM 13.0.1, 128 bits)
       GPU Version : 4.5 (Core Profile) Mesa 22.0.1

  Python 3.10.4 (main, Mar 23 2022, 23:05:40) [GCC 11.2.0]

           pyvista : 0.34.1
               vtk : 9.1.0
             numpy : 1.22.3
           imageio : 2.19.2
           appdirs : 1.4.4
            scooby : 0.5.12
        matplotlib : 3.5.1
             PyQt5 : 5.15.6
           IPython : 8.2.0
             scipy : 1.8.0
--------------------------------------------------------------------------------
```

### Screenshots

![image](https://user-images.githubusercontent.com/19879328/169895660-4d139237-179c-430c-863a-d663d424d186.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by StefRe** [comment]
The examples work fine on Windows (Intel(R) UHD Graphics 630) but appear to fail on Linux (Mesa/X.org llvmpipe).

**Comment by akaszynski** [comment]
> appear to fail on Linux (Mesa/X.org llvmpipe).

This is a known issue with [OSMesa](https://docs.mesa3d.org/osmesa.html), and can't be fixed within pyvista. What we could do is issue a warning when using osmesa with anti-aliasing enabled.
