### ISSUE TITLE
Results of boolean_union between PolyData and primitive shapes are treated as non-manifold

### ISSUE THREAD

**Issue by Keisuki** [pyvista/pyvista#2720]
### Describe the bug, what's wrong, and what you expected.

Hi pyvista devs.  

It looks like there's an issue where manifold meshes output by `boolean_union` are incorrectly treated as non-manifold by some other filters.  

`boolean_union` claims that it will return a manifold mesh, and indeed it does, but the output is treated as non-manifold when calling the `is_manifold` property or the `clip_closed_surface` method.

### Steps to reproduce the bug.

Download the sphere attached.  This is a simple sphere exported from blender as an example.

[sphere.zip](https://github.com/pyvista/pyvista/files/8807259/sphere.zip)

I've attached this as a ZIP, as .stl files are not supported by github attachments.

Run the following code:

```python 
import pyvista


sphere = pyvista.read("sphere.stl")
cone = pyvista.Cone(center=(-5.8870034, -11.016771, -7.0480175), direction=(0.19072754681110382, -0.9620586633682251, 0.19510547816753387), height=3, radius=1, resolution=4).triangulate()

joined = sphere.boolean_union(cone)

print(joined.is_manifold)
joined.clip_closed_surface((0, -1, 0), (0, 0, 0))
 ```
 
 I get the following output:
 
 ```
False
Traceback (most recent call last):
  File "/mnt/d/projects/mfemtest1/boolean_bug.py", line 13, in <module>
    joined.clip_closed_surface((0, -1, 0), (0, 0, 0))
  File "/home/willo/.local/lib/python3.9/site-packages/pyvista/core/filters/poly_data.py", line 1491, in clip_closed_surface
    raise ValueError("This surface appears to be non-manifold.")
ValueError: This surface appears to be non-manifold.
 ```
 
 Curiously, when we save and re-load the exact same mesh:
 
 ```python
 import pyvista

sphere = pyvista.read("sphere.stl")
cone = pyvista.Cone(center=(-5.8870034, -11.016771, -7.0480175), direction=(0.19072754681110382, -0.9620586633682251, 0.19510547816753387), height=3, radius=1, resolution=4).triangulate()

joined = sphere.boolean_union(cone)

joined.save("joined.stl")
joined = pyvista.read("joined.stl")

print(joined.is_manifold)
joined.clip_closed_surface((0, -1, 0), (0, 0, 0))
 ```
 
 I get the expected output:
 
 ```
 True
 ```
 
 With no error.

 

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Tue May 31 17:57:37 2022 BST

                OS : Linux
            CPU(s) : 24
           Machine : x86_64
      Architecture : 64bit
       Environment : Python
       GPU Details : error

  Python 3.9.11 (main, Mar 17 2022, 07:20:01)  [GCC 11.2.0]

           pyvista : 0.34.1
               vtk : 9.1.0
             numpy : 1.21.5
           imageio : 2.19.2
           appdirs : 1.4.4
            scooby : 0.5.12
        matplotlib : 3.5.1
             PyQt5 : Version unknown
             scipy : 1.7.3
--------------------------------------------------------------------------------
```

### Screenshots

The resulting mesh (Opened in blender) is correctly manifold.

![image](https://user-images.githubusercontent.com/17048185/171231247-2d6a854a-3821-4fe6-b1b6-36730d362643.png)
![image](https://user-images.githubusercontent.com/17048185/171231416-27aae08b-4fed-475e-8627-d323f6f00e7a.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by akaszynski** [comment]
Good point. Looks like you're going to have to clean the mesh after the boolean operation with the [PolyData.clean](https://docs.pyvista.org/api/core/_autosummary/pyvista.PolyData.clean.html) filter

```py
import pyvista

sphere = pyvista.read("sphere.stl")
cone = pyvista.Cone(center=(-5.8870034, -11.016771, -7.0480175), direction=(0.19072754681110382, -0.9620586633682251, 0.19510547816753387), height=3, radius=1, resolution=4).triangulate()

joined = sphere.boolean_union(cone).clean()  # added clean() here

print(joined.is_manifold)
clipped = joined.clip_closed_surface((0, -1, 0), (0, 0, 0))
```

**Comment by Keisuki** [comment]
That seems certainly like a better workaround than my current save-and-load one.  Thanks.

**Comment by akaszynski** [comment]
Closing. Reopen if you think we need to explicitly state to use `clean`.
