### ISSUE TITLE
Use Set method insted of On and Off method

### ISSUE THREAD

**Issue by tkoyama010** [pyvista/pyvista#2769]
### Describe what maintenance you would like added.

Some code uses VTK's `*On()` and `*Off()` methods (ex: `QuadsOn()` and `QuadsOff()` in `vtkTessellatedBoxSource` class). These generally implement a method called `Set*()` (ex: `SetQuads()`), which can be refactored to avoid using if statements.

_Inspired by @adeak in https://github.com/pyvista/pyvista/pull/2767#discussion_r894997566_

### Links to source code.

You can find it by running `grep "On()" ./pyvista/*/*.py` in root path. For example:

https://github.com/pyvista/pyvista/blob/fc9cea791d3d8aa873ba3123ee9d1c0e8d065faa/pyvista/utilities/geometric_objects.py#L675-L678

### Pseudocode or Screenshots

```python 
 src.SetQuads(quads)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RobPasMue** [comment]
I'll be handling this issue if possible :)

**Comment by tkoyama010** [comment]
@RobPasMue Awesome! Thanks :)
