### ISSUE TITLE
visible cell selection ("select cells on")

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#277]
From @S0Phon in https://github.com/pyvista/pyvista-support/issues/20#issue-461475637

> I have an stl file and would like to get the indices of all the cells visible from a chosen viewpoint. I know this is possible in vtk using the vtkHardwareSelector but am curious if it is possible in pyvista?

We should implement an argument to the `enable_cell_picking` method that will on select cells ON and not through.

**Comment by banesullivan** [comment]
Perhaps one quick hack of a solution would be to set the frustum of the cell picker to be the entire render window?

**Comment by banesullivan** [comment]
Here's an example of the current behaviour:

```py
import pyvista as pv
from pyvista import examples

poly = examples.download_nefertiti()

p = pv.Plotter(notebook=False)
p.add_mesh(poly, color='w')
p.enable_cell_picking()
p.show()
```

In the gif below, I try to select on the cells around the eye of this sculpture, but the cell picking picks **through** the mesh and gets cells on the other side that are out of sight. I'd like on the cells **on** the selection so that I could extract cells only near the eye

[This example](https://lorensen.github.io/VTKExamples/site/Cxx/Filtering/ExtractVisibleCells/) looks insightful.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/22067021/60310602-e9a5e280-9910-11e9-9488-d0a5ac3088de.gif)

**Comment by banesullivan** [comment]
Solved by https://github.com/pyvista/pyvista/pull/278#issuecomment-507013038

**Comment by banesullivan** [comment]
@S0Phon: I have an experimental version of this working on the `visible-cell-picking` branch described in #281 if you'd like to toy with it. Do note that it is having issues with non-triangulated meshes and there cannot be more that one mesh in the scene

**Comment by S0Phon** [comment]
@banesullivan, after lassoan's advice about testing the gpu on the vtkhardware topic here: https://discourse.vtk.org/t/visible-cell-selection-hardwareselector-py-example-is-not-working-reliably/1262/6
I have tried this feature a little and found that when I ran it on my laptop (on an integrated intel gpu), I get inconsitent reults with the picker. I am not sure how to make a little embedded video thing like you have done above but have uploaded some pictures below. I replaced the file with the stl file I used in the projection post.

Once activating the picker, I select the whole object and get the following:

![image](https://user-images.githubusercontent.com/51328173/60628153-1ada5300-9de8-11e9-9392-035b83d4b6e1.png)

Then, if I select the whole object again I get this:

![image](https://user-images.githubusercontent.com/51328173/60628186-36455e00-9de8-11e9-9ede-ce051f00de0c.png)

I exported the  anaconda environment I used to my other computer to try it with an nVidea GPU and, using the same script, got consistant results where the whole object was selected every time.

![image](https://user-images.githubusercontent.com/51328173/60628564-dfd91f00-9de9-11e9-9233-b75296458c78.png)

I hope this helps in some way. I am going to try to make a beam with brick elements next. If there is a better place to post about this, that then please let me know.

**Comment by S0Phon** [comment]
I have tried the beam with similar results. The same anaconda environment and script were used in both cases with the only difference being the computers.

With an integrated intel GPU:

![intelgpu](https://user-images.githubusercontent.com/51328173/60629836-50366f00-9def-11e9-92c2-7674fb97fa47.gif)

And with the nVidea GPU:

![nVideagpu](https://user-images.githubusercontent.com/51328173/60629856-63e1d580-9def-11e9-8280-dcf8d64c16d6.gif)

With the intel GPU, there is much worse performance (the lag is from the gif though). The same cells seem to be picked each time and the dont always correspond to where to selection box is.
The nVidea one is pretty smooth, although it seems to pick only the cells which are wholly inlcuded in the selection box. This could be a good or a bad thing depending on what people are trying to do with it.

**Comment by banesullivan** [comment]
@S0Phon - thanks so much for all your investigative work. Considering this seems to be a hardware issue (I have a Radeon Pro Vega GPU, not intel or NVIDIA), I'm going to clean up and marge the changes in #281 while adding a warning about using this tool without an NVIDIA GPU until we can figure out a way to tell what GPU people are using with [`scooby`](https://github.com/banesullivan/scooby) (ref https://github.com/banesullivan/scooby/issues/1).

Once `scooby` provides a way to tell what kind of GPU the user has, we'll change the warning to only people without an NVIDIA card.

**Comment by banesullivan** [comment]
FYI - I made a super cool example in https://github.com/pyvista/pyvista/pull/281#issuecomment-510153639
