### ISSUE TITLE
BackgroundPlotter not responding

### ISSUE THREAD

**Issue by coloss** [pyvista/pyvista#280]
I am trying to run the `BackgroundPlotter` example but it only seems to works only when I run it from a python shell. When I execute it as a script, the plotter windows pops up and just hangs forever.  

```python
import pyvista as pv

sphere = pv.Sphere()

plotter = pv.BackgroundPlotter()
plotter.add_mesh(sphere)

# can now operate on the sphere and have it updated in the background
sphere.points *= 0.5
```

Furthemore, a simple change when executing in a shell makes the `BackgroundPlotter` hang also from the shell. 

```python
import pyvista as pv
import time

sphere = pv.Sphere()

plotter = pv.BackgroundPlotter()
plotter.add_mesh(sphere)

# can now operate on the sphere and have it updated in the background
while True:
    sphere.points *= 0.5
    time.sleep(5) # just do add some delay
```

My guess is the `BackgroundPlotter` is not really running in another thread. What is the right way to do this? 
My plan is to visualize a real-time running simulation in the `BackgroundPlotter`.

Alternatively, I have tried this with the QtInteractor but the viewer in the interactor only seems to update when there's an actual UI event happening over the window (like clicking on it). If I could trigger the update programatically, it would solve my problem, too, but I did not find a way to do so. 

I'm running Python 3.7.3, PyVista version is  0.20.3 and PyQt5 on Windows 10. 

Any tips will be appreciated.

**Comment by banesullivan** [comment]
Hi @coloss - thanks for posting your issue!

As a tip to get you up and running ASAP, could you try run your code in IPython or Jupyter? I typically use the `BackgroundPlotter` in interactive Python sessions which is likely why we might have overlooked this behavior.

As for how we can correct this issue, we may need @akaszynski's expertise here - Alex created the `BackgroundPlotter` and I believe Alex uses it for similar types of projects in some external software.

This issue is likely very related to #279

**Comment by coloss** [comment]
Thanks @banesullivan for your suggestion. I quickly tested the same code with Jupyter. 

```python 
import pyvista as pv
import time

sphere = pv.Sphere()

plotter = pv.BackgroundPlotter()
plotter.add_mesh(sphere)
```

This part runs just fine. The viewer is opened and shows the sphere. But unfortunately, running the endless loop freezes the viewer in this case, too. 

```python 
while True:
    sphere.points *= 0.5
    time.sleep(5) # just to add some delay
```

**Comment by banesullivan** [comment]
Hmm.. that's weird as we do not expect the `BackgroundPlotter` to freeze from that `while True` loop. Thanks for reporting this, I'll investigate

I think it has to do with how we spawn a background thread - we're having that thread control the rendering rather than the app itself so maybe that's our issue?

**Comment by coloss** [comment]
Let me know if you do manage to reproduce the issue. If you can't, maybe it's a problem of my setup...

Your suggestion makes sense. If the actual `QApplication` runs on the main thread, I could see how it could freeze if the thread is busy ... but I would also kind of expect that the call that creates the application to be a blocking one. I quickly checked in the `BackgroundPlotter` code, where the call to the `self.app.exec()` function is and I did not find it. If I'm correct, this is the call that puts the app into it's event loop and since it's missing (as far as I can see but maybe this is take care of somewhere else), the application is not in its event loop and therefore frozen. ... 

If this turns out to be the case, maybe the answer is to do what you suggest - make the background thread control the entire app and not just the rendering. Or maybe even spawning to threads, one for the GUI of the app and one to control the rendering loop. 

These are just off the top of my head. I didn't dig too deep.

Thanks a lot for your help.

**Comment by banesullivan** [comment]
#293 might have resolved this

**Comment by GuillaumeFavelier** [comment]
I tried the code snippet proposed by @coloss and it didn't work locally for me even after #293.

I was thinking about a callback system created by the user for more flexibility and I would like to have your opinion on this @banesullivan , @akaszynski 

```py
import pyvista as pv

sphere = pv.Sphere()
plotter = pv.BackgroundPlotter()
plotter.add_mesh(sphere)


#  create custom callback class including the sphere
class CallBack:
    def __init__(self, sphere=None):
        self.sphere = sphere

    def update(self):
        # can now operate on the sphere and have it updated in the background
        self.sphere.points *= 0.5


# create the callback instance and ship it with the sphere
plotter.add_callback(CallBack(sphere), 'update')
```

And inside the `add_callback()` function in `BackgroundPlotter`:

```py
def add_callback(self, callback, func, timeout=1000):
    timer = QTimer(parent=self.app_window)
    timer.timeout.connect(getattr(callback, func))
    self.app_window.signal_close.connect(timer.stop)
    timer.start(timeout)
```

**Comment by GuillaumeFavelier** [comment]
Or alternatively:

```py
...

# create the callback instance and ship it with the sphere
callback = CallBack(sphere) 
plotter.add_callback(callback.update)
```

And:

```py
def add_callback(self, func, timeout=1000):
    timer = QTimer(parent=self.app_window)
    timer.timeout.connect(func)
    self.app_window.signal_close.connect(timer.stop)
    timer.start(timeout)
```

**Comment by banesullivan** [comment]
Rather than the callback being a class with a function, why not just a fucntion? That seems more general and user-friendly to me. Also it'd be consistent with some other callback functionality we have with cell picking.

```py
import pyvista as pv

sphere = pv.Sphere()

plotter = pv.BackgroundPlotter()
plotter.add_mesh(sphere)

# user-defined callback function
# can now operate on the sphere and have it updated in the background
# the sphere object should be withing this function's scope
mycallback = lambda: sphere.points *= 0.5

plotter.add_callback(mycallback)
```

And inside the `add_callback()` function in `BackgroundPlotter`:

```py
def add_callback(self, callback, timeout=1000):
    """Callback is callable."""
    timer = QTimer(parent=self.app_window)
    timer.timeout.connect(callback)
    self.app_window.signal_close.connect(timer.stop)
    timer.start(timeout)
```

**Comment by banesullivan** [comment]
Then if you wanted to get fancy with a class that keeps track of more data objects in the scene, you could make the class with a `__call__` method:

```py
#  create custom callback class including the sphere
class CallBack:
    def __init__(self, sphere):
        self.sphere = sphere

    def __call__(self):
        # can now operate on the sphere and have it updated in the background
        self.sphere.points *= 0.5

...

# create the callback instance and ship it with the sphere
callback = CallBack(sphere) 
plotter.add_callback(callback.update)
```

**Comment by banesullivan** [comment]
Also, what about executing something N times rather than over a span of time? How would we do that?

**Comment by GuillaumeFavelier** [comment]
In the case you mention, we can modify the `add_callback()` function like this:

```py
def add_callback(self, func, interval=1000, count=None):
    timer = QTimer(parent=self.app_window)
    timer.timeout.connect(func)
    timer.start(interval)
    self.app_window.signal_close.connect(timer.stop)
    # link a counter to the timer if needed
    if count is not None:
        counter = Counter(count)
        counter.signal_finished.connect(timer.stop)
        timer.timeout.connect(counter.decrease)
        self.counters.append(counter) # initialized as an empty list in __init__()
```

With the `Counter` class:

```py
class Counter(QObject):
    signal_finished = pyqtSignal()

    def __init__(self, count):
        super(Counter, self).__init__()
        if isinstance(count, int) and count > 0:
            self.count = count
        else:
            raise TypeError('Expected `count` to be'
                            '`int` but got: {}'.format(type(count)))

    @pyqtSlot()
    def decrease(self):
        self.count -= 1
        if self.count <= 0:
            self.signal_finished.emit()
```

**Comment by GuillaumeFavelier** [comment]
So now with #293 and #304, if I run [this code](https://github.com/pyvista/pyvista/pull/304#issue-296598407) as a script with the `Python` interpreter:

```sh
$ python sphere.py
$
```
For me, it executes the script entirely, doesn't hang anymore and just closes. I think this behaviour is expected since the main purpose of the `pyvista.BackgroundPlotter` is in fact not to hold the context with an event loop to allow interactions in the background compared to the `pyvista.Plotter` which manages its own event loop.

On the other side, if I call the script with `IPython`:

```sh
$ ipython 
In [1]: run sphere.py
In [2]:
```

The script is executed and as long as I use `IPython`, I can continue interacting with the window.

Can we consider that this bug is fixed? @coloss , @banesullivan
