### ISSUE TITLE
add_mesh_slice origin bug

### ISSUE THREAD

**Issue by rabiislimane** [pyvista/pyvista#2815]
### Describe the bug, what's wrong, and what you expected.

Hello,

For example if you have two cubes (side to side) seperated by a small gap and you use add_mesh_slice (to add a slicer between the cubes) you will get ValueError: Empty meshes cannot be plotted. Input mesh has zero points.
This is because add_mesh_slice uses by default mesh.center position as origin for the plane widget.

I also noticed that this bug only appeared on initialization and did not appear if the slicer was: 1- initialized correctly (with a mesh in the center) 2- moved to an empty location 3- then back to the mesh.

Is there any way to specifie the origin when using plotter.add_mesh_slice ?
Is there another way to avoid this bug ?

Thanks

### Steps to reproduce the bug.

```python 
import pyvista as pv
pl = pv.Plotter()

mesh_a = pv.Box((0.1, 1, 0, 1, 0, 1))
mesh_b = pv.Box((-0.1, -1, 0, 1, 0, 1))
mesh = mesh_b+mesh_a

pl.add_mesh(mesh, show_edges=True,opacity=0.7)
pl.add_mesh_slice(mesh, opacity=1, name='slicer_x', normal='x', normal_rotation=False,outline_translation=False, implicit=False,show_scalar_bar=False)
pl.show()
 ```

### System Information

```shell
--------------------------------------------------------------------------------
Date: Fri Jun 17 16:17:53 2022 Est (heure d’été)



OS : Windows
CPU(s) : 12
Machine : AMD64
Architecture : 64bit
Environment : Python
File system : unknown
GPU Vendor : NVIDIA Corporation
GPU Renderer : Quadro K2200/PCIe/SSE2
GPU Version : 4.5.0 NVIDIA 471.41



Python 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit
(AMD64)]



pyvista : 0.34.1
vtk : 9.1.0
numpy : 1.22.2
imageio : 2.15.0
appdirs : 1.4.4
scooby : 0.5.11
matplotlib : 3.5.1
pyvistaqt : 0.9.0
PyQt5 : Version unknown
IPython : 8.0.1
scipy : 1.8.0
meshio : 5.3.0
--------------------------------------------------------------------------------



Process finished with exit code 0
```

### Screenshots

![image](https://user-images.githubusercontent.com/76795483/174395991-2249f3b1-b88c-4ea7-9807-0c1b72c459d9.png)
![image](https://user-images.githubusercontent.com/76795483/174396047-df211b6d-5c08-483e-812d-b2c1d7672a93.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by banesullivan** [comment]
The `add_plane_widget()` method has an option for `origin` which `add_mesh_slice()` does not currently expose. I just added a PR to implement a user choice for this: #2883
