### ISSUE TITLE
Point labels appear as though meshes are transparent

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#282]
This is strange VTK behavior that I'm wondering if we can avoid... when using the `Plotter.add_point_labels` function, the `vtkLabeledDataMapper` shows the labels at all times even if a mesh should be blocking the view. Here's an example where I have point labels on on slop of the St. Helens dataset that should be block by the summit when looking from the other side:

```py
import pyvista as pv
from pyvista import examples

# Low res version of St. Helens dataset
mesh = examples.download_st_helens().warp_by_scalar().extract_geometry().triangulate().decimate(0.99).elevation()

dargs = dict(name='labels', font_size=18)

p = pv.Plotter(notebook=0)
p.add_mesh(mesh, show_edges=True)
callback = lambda selected: p.add_point_scalar_labels(selected, 'Elevation', **dargs)
p.enable_cell_picking(callback=callback, line_width=2)
p.show()
```

![ezgif com-video-to-gif-3](https://user-images.githubusercontent.com/22067021/60412029-e1f27200-9b8c-11e9-897d-58bce38f09f8.gif)

**Comment by akaszynski** [comment]
Tried a different point labeling class and still ran into the same issue.  I opened a topic [here](https://discourse.vtk.org/t/culling-of-point-labels/1243)

**Comment by akaszynski** [comment]
Also, see this code snippet for the point label class that we might prefer:
```python

import random
from vtk import *

n = 100

# qinit = vtkQtInitialization()

pd = vtkPolyData()
pts = vtkPoints()
verts = vtkCellArray()
orient = vtkDoubleArray()
orient.SetName('orientation')
label = vtkStringArray()
label.SetName('label')
for i in range(n):
  pts.InsertNextPoint(random.random(), random.random(), random.random())
  verts.InsertNextCell(1)
  verts.InsertCellPoint(i)
  orient.InsertNextValue(random.random()*360.0)
  label.InsertNextValue(str(i))

pd.SetPoints(pts)
pd.SetVerts(verts)
pd.GetPointData().AddArray(label)
pd.GetPointData().AddArray(orient)

hier = vtkPointSetToLabelHierarchy()
hier.SetInputData(pd)
hier.SetOrientationArrayName('orientation')
hier.SetLabelArrayName('label')
hier.GetTextProperty().SetColor(0.0, 0.0, 0.0)

lmapper = vtkLabelPlacementMapper()
lmapper.SetInputConnection(hier.GetOutputPort())
# strategy = vtkQtLabelRenderStrategy()
# lmapper.SetRenderStrategy(strategy)
lmapper.SetShapeToRoundedRect()
lmapper.SetBackgroundColor(1.0, 1.0, 0.7)
lmapper.SetBackgroundOpacity(0.8)
lmapper.SetMargin(3)

lactor = vtkActor2D()
lactor.SetMapper(lmapper)

mapper = vtkPolyDataMapper()
mapper.SetInputData(pd)
actor = vtkActor()
actor.SetMapper(mapper)

ren = vtkRenderer()
ren.AddActor(lactor)
ren.AddActor(actor)
ren.ResetCamera()

win = vtkRenderWindow()
win.AddRenderer(ren)

iren = vtkRenderWindowInteractor()
iren.SetRenderWindow(win)

iren.Initialize()
iren.Start()
```

Code taken and modified (slightly) from [here](https://vtk.org/gitweb?p=VTK.git;a=blob;f=Examples/Infovis/Python/labels.py).

**Comment by banesullivan** [comment]
That's much better! - already implemented it in #286

This makes a major difference but it would still would be awesome if we could find a way to only render visible point labels

**Comment by akaszynski** [comment]
@banesullivan, got a helpful reply at [vtk discourse](https://discourse.vtk.org/t/culling-of-point-labels/1243).  I’m not able to implement this at the moment, could you try chipping away at it?

**Comment by banesullivan** [comment]
I tried mimicking [that example](https://github.com/Slicer/Slicer/blob/master/Modules/Loadable/Markups/VTKWidgets/vtkSlicerMarkupsWidgetRepresentation3D.cxx) but I think we'd have to been on the latest release of VTK for it to work, not sure... there some work in progress on the `visible-labels` branch that we could come back to

**Comment by banesullivan** [comment]
I have a somewhat working solution on the `point-labels` branch using `vtkSelectVisiblePoints`. There are some issues, but its generally working. See https://github.com/pyvista/pyvista/commit/8e16dd16574138d37345dd61181172d36fe13b59

The tolerance likely needs to be tweaked. Currently, if I zoom too close hidden labels become visible:

![2019-08-20 18 05 42](https://user-images.githubusercontent.com/22067021/63392753-27554380-c375-11e9-8be3-b6ce5d12ac90.gif)
