### ISSUE TITLE
Inconsistent behavior of property `extent` for different data structures

### ISSUE THREAD

**Issue by normanius** [pyvista/pyvista#2820]
### Describe the bug, what's wrong, and what you expected.

**Problem 1:** I don't get the difference between `extent` and `bounds` from the documentation. Following the docs of [UniformGrid.extent](https://docs.pyvista.org/api/core/_autosummary/pyvista.UniformGrid.extent.html) and [UniformGrid.bounds](https://docs.pyvista.org/api/core/_autosummary/pyvista.UniformGrid.bounds.html), it should be the same: `(x_min, x_max, y_min, y_max, z_min, z_max)`. However, this seems not to be the case, as demonstrated below. I think it would help if the documentation of extent would make this distinction clear. 

Apparently, for UniformGrid, it holds that extent = bounds * spacing. (Well, spacing (sx, sy, sz) here is (sx, sx, sy, sy, sz, sz), to match the lengths of bounds and extent).

**Problem 2:** Unexpectedly, [extent](https://docs.pyvista.org/api/core/_autosummary/pyvista.PolyData.extent.html) returns None for valid meshes. I would expect it to return the correct extent of the mesh. For UniformGrids, the property seems to work. I did not have a look at other data structures.

**Conclusion:** Behavior of extent is inconsistent and the documentation of that property incomplete.

[PolyData.extent](https://docs.pyvista.org/api/core/_autosummary/pyvista.PolyData.extent.html)
[UniformGrid.extent](https://docs.pyvista.org/api/core/_autosummary/pyvista.UniformGrid.extent.html)

### Steps to reproduce the bug.

```python 
from pyvista import examples
poly = pv.read(examples.planefile)
print("Extent:", poly.extent)
print("Bounds:", poly.bounds)
print()
poly = examples.download_teapot()
print("Extent:", poly.extent)
print("Bounds:", poly.bounds)
print()
grid = examples.download_knee_full()
print("Extent:", grid.extent)
print("Bounds:", grid.bounds)


# Extent: None
# Bounds: (139.06, 1654.93, 32.09, 1319.95, -17.74, 282.13)
# 
# Extent: None
# Bounds: (-3.0, 3.43, 0.0, 3.0, -2.0, 2.0)
# 
# Extent: (0, 207, 0, 247, 0, 200)
# Bounds: (0.0, 149.66, 0.0, 178.58, 0.0, 200.0)
 ```

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Sun Jun 19 13:09:50 2022 CEST

                OS : Darwin
            CPU(s) : 8
           Machine : x86_64
      Architecture : 64bit
               RAM : 16.0 GiB
       Environment : IPython
       File system : apfs
        GPU Vendor : Intel Inc.
      GPU Renderer : Intel Iris Pro OpenGL Engine
       GPU Version : 4.1 INTEL-12.10.31

  Python 3.8.0 (v3.8.0:fa919fdf25, Oct 14 2019, 10:23:27)  [Clang 6.0
  (clang-600.0.57)]

           pyvista : 0.34.1
               vtk : 9.1.0
             numpy : 1.22.3
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.12
        matplotlib : 3.4.1
             PyQt5 : 5.15.2
           IPython : 8.1.1
             scipy : 1.6.1
              tqdm : 4.55.1
--------------------------------------------------------------------------------
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by akaszynski** [comment]
Duplicated by #2821.
