### ISSUE TITLE
All dragon in Plotting Themes section is black

### ISSUE THREAD

**Issue by tkoyama010** [pyvista/pyvista#2832]
### Describe the bug, what's wrong, and what you expected.

All dragon in [Plotting Themes](https://dev.pyvista.org/user-guide/themes.html) section is black.
| [docs.pyvista.org](https://docs.pyvista.org/user-guide/themes.html) | [dev.pyvista.org](https://dev.pyvista.org/user-guide/themes.html) |
| --- | --- |
| ![docs](https://user-images.githubusercontent.com/7513610/174690695-3c79db19-22d7-4d1f-8de1-1f555c13f9e6.png) | ![devs](https://user-images.githubusercontent.com/7513610/174690773-d484fcd9-370b-433e-be9f-caed67b64200.png) |

### Steps to reproduce the bug.

None

### System Information

```shell
None
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adeak** [comment]
I wonder if this is due to a `show_edges=True` somehow sneaking in. I wonder why that would only affect these plots... it seems that the theme changes don't affect the plots at all? That can't be right. (Un)fortunately my local build reproduces the issue.

**Comment by tkoyama010** [comment]
It may be a matter of statistical observation, but I have the impression that the documentation often does not keep the release version status. Perhaps a comparison to the release version images needs to be added to the regression test.
