### ISSUE TITLE
Grid and PolyData cells indexes switched 

### ISSUE THREAD

**Issue by gbene** [pyvista/pyvista#2834]
### Discussed in https://github.com/pyvista/pyvista/discussions/2752

<div type='discussions-op-text'>

<sup>Originally posted by **gbene** June  7, 2022</sup>
Hello,
I'm currently trying to create a 3D GPR data volume using Uniform grids. Since the dataset is pretty big about 338,310,000 points I was wondering if there are any resources or more effective methods to create the volume other than interpolate the point cloud using grid.interpolate. For example how were the knee_full or brain example volumes constructed? 

Thanks!</div>

**Comment by tkoyama010** [comment]
Duplicate with https://github.com/pyvista/pyvista/discussions/2752 closing.
