### ISSUE TITLE
Expose SkipZeroTime property of vtkOpenFOAMReader

### ISSUE THREAD

**Issue by Failxxx** [pyvista/pyvista#2843]
### Describe the feature you would like to be added.

I think it would be nice to expose the property named "SkipZeroTime" in the OpenFOAMReader.

### Links to VTK Documentation, Examples, or Class Definitions.

vtkOpenFOAMReader : https://vtk.org/doc/nightly/html/classvtkOpenFOAMReader.html#ada0ff6f0dcc570b5f4145dc71944fbde

### Pseudocode or Screenshots

It seems that this property could be implemented the same way as the `case_type` property. It looks like an import settings or something like that.

![skip_zero_time_in_paraview](https://user-images.githubusercontent.com/22941087/174971275-5dee1f49-8537-438f-a97c-ce64f88c35b2.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MatthewFlamm** [comment]
Good idea.  We _might_ need to use `UpdateInformation` after changing value.
