### ISSUE TITLE
Array segmentation fault

### ISSUE THREAD

**Issue by akaszynski** [pyvista/pyvista#2864]
As pointed out by @adeak in [this comment](https://github.com/pyvista/pyvista/pull/1953#issuecomment-1166383011), the following leads to a segmentation fault: 

```py
>>> import numpy as np
>>> from pyvista import examples
>>> puppy = examples.download_puppy()
>>> puppy.clear_data()
>>> puppy['scalars'] = np.arange(puppy.n_points, dtype=float)
>>> puppy['scalars'] *= 2/3
>>> puppy['scalars']
Process Python segmentation fault (core dumped)
```

**Comment by akaszynski** [comment]
Interestingly enough, this has no issues:

```py
import numpy as np
import pyvista

dataset = pyvista.Sphere()
dataset['scalars'] = np.arange(dataset.n_points, dtype=float)
dataset['scalars'] *= 0.666
dataset['scalars']
```

Nor does this:
```py
def test_pyvistandarray_inplace_update(datasets):
    for dataset in datasets:
        data = np.arange(dataset.n_points, dtype=float)
        dataset.point_data['data'] = data
        dataset.point_data['data'] *= 0.5
        assert np.allclose(dataset.point_data['data'], data)

    for dataset in datasets:
        dataset.point_data['more_data'] = np.arange(dataset.n_points, dtype=float)
        dataset.point_data['more_data'] *= 0.5
        assert isinstance(dataset.point_data['more_data'], np.ndarray)
```

Minimum reproducible issue is:

```py
import numpy as np
import pyvista

dataset = pyvista.UniformGrid(dims=(500, 500, 1))
dataset['scalars'] = np.arange(dataset.n_points, dtype=float)
dataset['scalars'] *= 0.5
dataset['scalars']
```

**Comment by adeak** [comment]
Weird, although I'd be cautious about extrapolating too much from these weird results. A segfault means "code tried to write to memory outside what's allocated to the process". If things get deallocated but the resulting unallocated memory still belongs to the process, accessing (or even writing) that will not lead to a segfault, only to reading garbage or corrupting the memory of the running process.

So it's possible that some of the "non segfault" cases are also problematic, it's just that there's no segmentation violation in those cases. E.g. the uniform grid case is large enough that its deallocated memory gets taken back by the OS, something like that.

**Comment by adeak** [comment]
Case in point: uncommenting the `Sphere` line makes the segfault go away for me here:
```py
import numpy as np
import pyvista

dataset = pyvista.Sphere(theta_resolution=50000)

dataset = pyvista.UniformGrid((500, 500, 1))
dataset['scalars'] = np.arange(dataset.n_points, dtype=float)
dataset['scalars'] *= 0.5
print(dataset['scalars'])
```
even though that line should have absolutely no bearing on the rest of the snippet. And the values are a bit fishy:
```py
[6.90863948e-310 3.98530267e-316 3.98530267e-316 ... 1.24998500e+005
 1.24999000e+005 1.24999500e+005]
```
those `1e-300` denormal numbers have no place in there, especially since the scalars should start as `[0, 0.5, 1, 1.5, ...]` and these would be exact floating-point numbers.

Trying to count the values (transformed back to integers) shows that data was mangled:
```py
print(np.bincount((dataset['scalars'] * 2).astype(int)))
# [4 0 0 ... 1 1 1]
```
If the data were intact we'd get a 1 everywhere (give or take an edge case).

**Comment by akaszynski** [comment]
Looks like this occurs for datatypes:
```py
>>> points = np.zeros((10000000, 3))
>>> dataset = pyvista.PointSet(points)
>>> data = np.arange(dataset.n_points, dtype=float)
>>> dataset['scalars'] = data.copy()
>>> dataset['scalars'] *= 0.5
>>> dataset['scalars']
```
