### ISSUE TITLE
Change default window title

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#287]
Can we change the default render title from "Visualization Toolkit ..." to "PyVista [something]"?

This would help brand screen grabs a bit better.

Currently it looks like:

<img width="624" alt="Screen Shot 2019-07-01 at 9 58 29 PM" src="https://user-images.githubusercontent.com/22067021/60481821-5a6c3800-9c4c-11e9-88a8-80b368e624f9.png">

It was done here: https://github.com/mne-tools/mne-python/pull/6475#issue-290127885 by @GuillaumeFavelier 

![59834537-73b9de00-9348-11e9-9f62-be5ce84512c6](https://user-images.githubusercontent.com/22067021/60481804-445e7780-9c4c-11e9-8d9b-ab11745ee46d.png)

**Comment by GuillaumeFavelier** [comment]
Just throwing some ideas:

1) `PyVista` *(short and simple)*
2) `PyVista Window` *(accurate description)*
3) `PyVista Application` *(maybe more trending?)*
4) `PyVista Scene` *(maybe too technical?)*

**Comment by banesullivan** [comment]
@GuillaumeFavelier I like all of those! I’m curious, how did you al change the window name?

**Comment by GuillaumeFavelier** [comment]
I modified the `title` parameter of the [`pyvista.Plotter.show()` function](https://docs.pyvista.org/plotting/plotting.html?highlight=show#pyvista.Plotter.show) !

**Comment by banesullivan** [comment]
🤦‍♂ I totally forgot about that 😄

**Comment by banesullivan** [comment]
Actually... I guess I forgot about it because it doesn't work on Mac!
