### ISSUE TITLE
Code style: Black, autopep8, or yapf?

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#288]
I'm playing around with [Black](https://black.readthedocs.io/en/stable/index.html) and it's super easy to integrate into projects with a pre-commit hook. 

I'm curious how the active contributors would feel about embracing an automatic code-styler like Black (or another)? This would give us all more consistent formatting of code across the API. It's also designed to produce easier-to-navigate diffs and remove the need for formatting by hand.

It looks like each contributor would have to set up the pre-commit hook I think?

Ping @akaszynski

**Comment by banesullivan** [comment]
[Interesting resource](https://medium.com/3yourmind/auto-formatters-for-python-8925065f9505) and alternative to Black: https://github.com/kenneth-reitz/white

**Comment by akaszynski** [comment]
I agree with adding a coding style, and ``black`` sounds good to me.  I don't think we must adhere to 79 characters (the default 88 in black works), though we should keep most lines within 79 and use 88 as the exception to the rule.

**Comment by GuillaumeFavelier** [comment]
+1 for black

Or just integrating the checks in the CIs (`pydocstyle`, `flake8`, ...) is already is a step forward I think. Even if it's not automatic, it gives an estimation.

**Comment by leouieda** [comment]
Not really a contributor here but from my own experience using Black really makes the contribution process a lot easier. I don't have to try to figure what style the project uses. I run `black` and it's done. As a maintainer, I don't have to comment on silly code style (break lines here, indentation after parenthesis, etc). I can tell people to run `black` and all is fine. So it's one less thing to think about and I can focus the review on the important stuff: tests, variable names, proper use of types, documentation, design. 

The one caveat are docstrings. I made the mistake of making them 88 chars as well. In Jupyter/IPython, that means that docstrngs are basically unreadable. Black doesn't touch docstrings so it's not a huge problem.

**Comment by tkoyama010** [comment]
@GuillaumeFavelier Thank you for your mention. I'm +1 for black.

**Comment by tkoyama010** [comment]
And black + [isort](https://github.com/timothycrosley/isort) is good to use. ➡️ #516

**Comment by banesullivan** [comment]
isort is really awesome - I manually use it on PyVista every once in a while as imports do not change that often

**Comment by tkoyama010** [comment]
FYI it became major to add type annotation to python code. It maybe good to add type annotation and check by mypy (from [Oh my(py)](https://blog.zulip.org/2016/10/13/static-types-in-python-oh-mypy/) and [mypy](https://github.com/python/mypy)).

**Comment by GuillaumeFavelier** [comment]
Any news on this one? :)

**Comment by tkoyama010** [comment]
Now we use pylint, pycodestyle, flake8, black, mypy, isort in pyvistaqt.
https://github.com/pyvista/pyvistaqt/pull/38
https://github.com/pyvista/pyvistaqt/pull/40
https://github.com/pyvista/pyvistaqt/pull/43
https://github.com/pyvista/pyvistaqt/pull/45
https://github.com/pyvista/pyvistaqt/pull/46
https://github.com/pyvista/pyvistaqt/pull/47

**Comment by akaszynski** [comment]
We probably can close this issue then.  Thanks for pointing this out @tkoyama010

**Comment by banesullivan** [comment]
> We probably can close this issue then

agreed. I think we've converged on which things to use if we go that route so I will close this issue.

It may be a long time before we actually follow through with an autoformatter here though (just such a large codebase to try to do it all at once)
