### ISSUE TITLE
Depth mapping not working on jupyterlab3

### ISSUE THREAD

**Issue by mllobera** [pyvista/pyvista#2953]
### Describe the bug, what's wrong, and what you expected.

I have tried running the following [example](https://docs.pyvista.org/examples/02-plot/image_depth.html) and I get the following error. While this example does not include the `off_screen = True` parameter I included it within `show()` but still get an error

### Steps to reproduce the bug.

```python 
 import pyvista as pv
from pyvista import examples

# Load an interesting example of geometry
mesh = examples.load_random_hills()

# Establish geometry within a pv.Plotter()
p = pv.Plotter()
p.add_mesh(mesh, color=True)
p.store_image = True  # permit image caching after plotter is closed
p.show()

zval = p.get_image_depth() 
 ```

### System Information

```shell
--------------------------------------------------------------------------`
AttributeError                            Traceback (most recent call last)
Input In [13], in <cell line: 1>()
----> 1 zval = p.get_image_depth()

File C:\Python\Miniconda\envs\test_3d\lib\site-packages\pyvista\plotting\plotting.py:3488, in BasePlotter.get_image_depth(self, fill_value, reset_camera_clipping_range)
   3485         zval[self._image_depth_null] = fill_value
   3486     return zval
-> 3488 self._check_rendered()
   3489 self._check_has_ren_win()
   3491 # Ensure points in view are within clipping range of renderer?

File C:\Python\Miniconda\envs\test_3d\lib\site-packages\pyvista\plotting\plotting.py:1241, in BasePlotter._check_rendered(self)
   1239 """Check if the render window has been shown and raise an exception if not."""
   1240 if not self._rendered:
-> 1241     raise AttributeError(
   1242         '\nThis plotter has not yet been set up and rendered '
   1243         'with ``show()``.\n'
   1244         'Consider setting ``off_screen=True`` 
   1245         'for off screen rendering.\n'
   1246     )

AttributeError: 
This plotter has not yet been set up and rendered with ``show()`
Consider setting ``off_screen=True`` for off screen rendering. '
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by banesullivan** [comment]
The plotter likely closed after the `p.show()` call. Try changing this to `p.show(auto_close=False)`

**Comment by mllobera** [comment]
Thank for the prompt response!
Tried it but I still get the same error.

**Comment by akaszynski** [comment]
Can you try with `off_screen=True` set on the `Plotter`?

**Comment by banesullivan** [comment]
I suspect this is related to https://github.com/pyvista/pyvista/pull/2795 in that a `jupyter_backend` is being used that doesn't actually render anything. Indeed, `off_screen=True` and/or `jupyter_backend='none'` should work around this

**Comment by mllobera** [comment]
@banesullivan your suggested worked! I was wondering if it is possible to obtain this information without rendering the scene interactively (which holds up execution of remaining cells)?

**Comment by banesullivan** [comment]
> obtain this information without rendering the scene interactively

Then @akaszynski's suggestion of `off_screen=True` should be the way to go!

Try:

```py
import pyvista as pv

mesh = pv.Sphere()

p = pv.Plotter(off_screen=True, notebook=False)
p.add_mesh(mesh, color=True)
p.store_image = True  # permit image caching after plotter is closed
p.show(auto_close=False)

zval = p.get_image_depth()
```

```
import matplotlib.pyplot as plt
plt.imshow(zval)
```
![download](https://user-images.githubusercontent.com/22067021/178053138-c8563028-733a-4301-b5b8-d8835e35908e.png)

**Comment by mllobera** [comment]
Great thanks!! I tried this and something weird happened.
If I run it without the `off_screen` parameter I get the popup window and when I quit it, I get z-values as expected. However, when I try with  `off_screen = True`  all I get is `nan`.
