### ISSUE TITLE
Error in `point_data_to_cell_data`

### ISSUE THREAD

**Issue by MarkusZimmerDLR** [pyvista/pyvista#2974]
Dear pyvista-team,

I am having an issue with `point_data_to_cell_data` which causes the internal pointing of the arrays to be wrong.

I think the easiest way is to give you an example:

```python
import pyvista as pv
import numpy as np
from copy import deepcopy

res = 10
p = pv.Plane(j_resolution=res, i_resolution=res)
kek = np.arange(res + 1)
kek = np.tile(kek, (res,1))
u = deepcopy(kek.flatten())  # deepcopy simply for indication
v = deepcopy(kek.T.flatten())

p.point_data['u'] = u
p.point_data['v'] = v

p.plot(scalars='u')
```
![u1](https://user-images.githubusercontent.com/77002394/178431225-db19aada-bc0b-4790-b6a1-8eae69ff4673.png)

```python
p.plot(scalars='v')
```
![v1](https://user-images.githubusercontent.com/77002394/178431233-39f80cbd-cdbd-4146-b124-80a07e228c25.png)
```python
ppp = p.copy()  # keep the original for safety
pp = point_data_to_cell_data(pass_point_data=True)

pp.plot(scalars='u')
```
![u2](https://user-images.githubusercontent.com/77002394/178431230-640503b7-c919-4c7b-868a-0e975d680f35.png)

```python
pp.plot(scalars='v')
```
![v2](https://user-images.githubusercontent.com/77002394/178431239-e2472912-69d6-40f6-94de-da33dcd1f40e.png)

Now the PLOTTED data is wrong.
Checking the converted data:

```python
all(pp.point_data['u'] == ppp.point_data['u'])  # True
all(pp.point_data['v'] == ppp.point_data['v'])  # True
pd.Series(pp.point_data['u'] == pp.point_data['v']).value_counts()
'''
False    110
True      11
dtype: int64
'''
pd.Series(pp.cell_data['u'] == pp.cell_data['v']).value_counts()
'''
False    90
True     10
dtype: int64
'''

```
Thus, data arrays actually seem correct.
The issue does not appear, if I delete/rename either the cell or point data. Therefore, I believe it is a pointer/namespace issue.
However, for the current implementation, I am relying on using the same name for point and cell data.

One last funny thing:
```python
plotter = pv.Plotter(shape=(2,2))
plotter.subplot(0,0)
plotter.add_mesh(ppp, scalars='u')
plotter.subplot(0,1)
plotter.add_mesh(ppp, scalars='v')
plotter.subplot(1,0)
plotter.add_mesh(pp, scalars='u')
plotter.subplot(1,1)
plotter.add_mesh(pp, scalars='v')
plotter.show()
```
![u1v1u2v2](https://user-images.githubusercontent.com/77002394/178434845-0f817ae1-3aff-42f1-90c0-230cf323f67c.png)
Now the dataset is plotted wrong on both meshes. However, each in a different way. If the originally `ppp` is plotted individually, the plot is correct...

I had a data array related issue once before, which was related to the `vtk` version #1202, so you might want to have a look at the report below. 

## System Report

I was able to reproduce this on a completely separate system with a fresh installation with python 3.9. However, I cannot reach the system from here to generate a separate report. 

--------------------------------------------------------------------------------
  Date: Tue Jul 12 09:43:36 2022 CEST

                OS : Linux
            CPU(s) : 16
           Machine : x86_64
      Architecture : 64bit
               RAM : 251.4 GiB
       Environment : IPython
        GPU Vendor : NVIDIA Corporation
      GPU Renderer : Quadro RTX 4000/PCIe/SSE2
       GPU Version : 4.5.0 NVIDIA 515.48.07

  Python 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:56:21)
  [GCC 10.3.0]

           pyvista : 0.35.1
               vtk : 9.1.0
             numpy : 1.21.6
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.7
        matplotlib : 3.5.2
         pyvistaqt : 0.9.0
             PyQt5 : 5.12.3
           IPython : 7.33.0
             scipy : 1.8.1
              tqdm : 4.60.0
            meshio : 4.4.6
--------------------------------------------------------------------------------

Thanks a lot,
Markus

**Comment by MatthewFlamm** [comment]
Just to clarify, does this only happen with `point_data_to_cell_data` like in the example, or in both as indicated by your title?

**Comment by MarkusZimmerDLR** [comment]
So far, only tested with `point_data_to_cell_data`. The title was a mistake of me working in a hurry. I'll change that right away.

**Comment by akaszynski** [comment]
Can reproduce the error. Working on a fix.
