### ISSUE TITLE
Shallow Copy Behavior

### ISSUE THREAD

**Issue by akaszynski** [pyvista/pyvista#2979]
Our shallow copy behavior appears somewhat counter-intuitive:

```py
import pyvista as pv
import numpy as np

# create a new mesh
mesh = pv.Sphere()
mesh.clear_data()

# add data
data = np.arange(mesh.n_points)
mesh.point_data['data'] = data

# create a shallow copy
mesh_copy = mesh.copy(deep=False)
```

Let's modify the `data` array:
```py
>>> data[:] += 1
>>> mesh_copy == mesh
True
```

So far, so good. Now, let's add a new array to `mesh_copy`. It's a shallow copy, so the new array should show up in `mesh`:
```py
>>> mesh_copy.point_data['new'] = range(mesh_copy.n_points)
>>> mesh_copy == mesh
False
```

Turns out it doesn't:
```py
>>> mesh.point_data.keys()
['data']
>>> mesh.point_data.keys()
['data', 'new']
```

### Why?
When we create a shallow copy using [ShallowCopy](https://vtk.org/doc/nightly/html/classvtkDataObject.html#a04a5fb60bdbc929ce84f0cd14d911dbe), it creates a shallow copy of all the data arrays, but not of the `vtkPointData`:

```py
>>> mesh.GetPointData() is mesh_copy.GetPointData()
False
```

This is despite the fact that the data arrays are indeed the same:

```py
>>> mesh.GetPointData().GetArray(0) is mesh_copy.GetPointData().GetArray(0)
True
```

### What do we about this?

I'd like to point out that while this seems counter intuitive, there are certain advantages to this approach, one of those being in #2980. We can shallow copy the data in a dataset without incurring a copy cost, but keep them separate such that we can now add data in the new dataset without also adding it in the old one.

I think we should keep it, but I wanted to bring this behavior up and make sure all are fine with it. I prefer remaining similar to the VTK implementation unless it's faulty, and this is (to me at least) in the grey zone of being either a "bug that's a feature", or a "feature that's a bug".

**Comment by banesullivan** [comment]
IMO, this should stay as is. Though it may be good to document this behavior in the `shallow_copy` docstring.

From my perspective, VTK datasets act as a container for the actual data we care about such that something like the `vtkPolyData` and its `vtkPointData`/`vtkCellData`, etc are simply containers to reference the data we care about. With that in mind, when we "shallow copy" a dataset, I would expect to get new containers that share a reference to the original data we care about. In this mental model, this behavior is expected (to me at least).

I think that #2980 and (the rather old) #542 make it clear that this behavior is advantageous.

Additionally, I'd like to draw a parallel to other data structures/libraries that have shallow copy methods that perform similarly:

### dict

```py
import numpy as np

arr1 = np.random.rand(100)
arr2 = np.random.rand(100)

a = {'arr1': arr1}
b = a.copy()  # Docstring: D.copy() -> a shallow copy of D
b.setdefault('arr2', arr2)
assert len(a.keys()) == 1
assert len(b.keys()) == 2
assert np.may_share_memory(b['arr1'], a['arr1'])
```

### pandas

```py
import numpy as np
import pandas as pd

arr1 = np.random.rand(100)
arr2 = np.random.rand(100)

dfa = pd.DataFrame(data={'arr1': arr1})
dfb = dfa.copy(deep=False)
dfb['arr2'] = arr2

assert len(dfa.keys()) == 1
assert len(dfb.keys()) == 2
assert np.may_share_memory(dfb['arr1'], dfa['arr1'])
```

**Comment by akaszynski** [comment]
Closing, agree with @banesullivan.
