### ISSUE TITLE
Legend not showing up when using panel backend

### ISSUE THREAD

**Issue by jorgepiloto** [pyvista/pyvista#2982]
### Describe the bug, what's wrong, and what you expected.

When using the `Plotter.show(jupyter_backend="panel")` method, the legend does not show up even after calling the `Plotter.add_legend()` method.

### Steps to reproduce the bug.

```python 
import pyvista as pv
sphere = pv.Sphere()
pl = pv.Plotter()
pl.add_mesh(sphere, label="Sphere")
pl.add_legend()
pl.show(jupyter_backend="panel")
```

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Wed Jul 13 21:16:48 2022 CEST

                OS : Linux
            CPU(s) : 8
           Machine : x86_64
      Architecture : 64bit
               RAM : 15.2 GiB
       Environment : Jupyter
       File system : ext4
        GPU Vendor : Intel
      GPU Renderer : Mesa Intel(R) UHD Graphics 620 (KBL GT2)
       GPU Version : 4.6 (Core Profile) Mesa 22.1.1

  Python 3.10.5 (main, Jun  8 2022, 02:00:39) [GCC 10.2.1 20201203]

           pyvista : 0.35.1
               vtk : 9.2.0
             numpy : 1.22.0
           imageio : 2.19.3
           appdirs : 1.4.4
            scooby : 0.5.12
        matplotlib : 3.5.2
           IPython : 8.4.0
           cmocean : 2.0
        ipyvtklink : 0.2.2
             scipy : 1.8.1
              tqdm : 4.64.0
        jupyterlab : 3.4.3
         pythreejs : Version unknown
--------------------------------------------------------------------------------
```

### Screenshots

Using panel backend            |  Using default backend
:-------------------------:|:-------------------------:
![](https://user-images.githubusercontent.com/28702884/178814275-56cc6531-482b-4d6a-8458-153771adafeb.png)  |  ![](https://user-images.githubusercontent.com/28702884/178814445-7052a586-c8c1-45ad-ad97-a8d627e087e6.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by akaszynski** [comment]
I don't think that's supported quite yet, but you could always raise an issue on https://github.com/holoviz/panel.

**Comment by banesullivan** [comment]
Closing as this is not something we can implement. Specifically for panel, they'd need to handle this when serializing the scene
