### ISSUE TITLE
Better handle breaking changes in PRs and Release Notes

### ISSUE THREAD

**Issue by MatthewFlamm** [pyvista/pyvista#3032]
It would be nice to have a Breaking Changes section by default in the PR template.  We can have instructions to delete if not needed.  The instructions could also suggest PR authors to provide examples of changing syntax, if appropriate.

If we can label the PRs that contain breaking changes (can this be done automatically?), then we can sort them in the release notes under the first heading as they are the most important.

See discussion from: 
https://github.com/pyvista/pyvista/issues/3031#issuecomment-1189431988_

**Comment by MatthewFlamm** [comment]
cc @tkoyama010 for your awareness.  You have been handling a lot of CI tasks related to labeling and release notes, so you may have some good thoughts here.

**Comment by tkoyama010** [comment]
When adding a breaking change, I don't think it can be labeled automatically like other labeling. It is possible that the test file could be determined by the changes made, but then labeling would be done for all feature additions as well. I think a practical solution would be to label PRs for changes that break into the Contribution Guide.
Adding a section to the release notes is +100 :)

**Comment by tkoyama010** [comment]
Alternatively, a new rule for branch names allows for automatic labeling.

**Comment by MatthewFlamm** [comment]
It sounds very difficult to automate.  I would suggest that we start small and add a Breaking Change section to the suggested PR description fields, start using the `breaking-change` label, and adding this to the release labeler.

**Comment by adeak** [comment]
+1 for some transparency and discoverability of breaking changes. Arguably we'd even need more "release notes" than what's generated now, e.g. put somewhere on docs.pyvista.org. But that would be a lot of additional maintenance burden.

> Alternatively, a new rule for branch names allows for automatic labeling.

I'd much prefer using labels over branches. Branch names can easily be wrong, scopes often change during development, and in any case a single PR might fit `feat/` and `fix/` and `breaking-change/`; a label sounds a lot more practical. Of course the difficulty is then
1. realising that a breaking change happens in a PR, and
2. remembering to label and/or note this fact somewhere.

In any case it's considerable overhead that's easy to miss, but it would be pretty helpful downstream.

**Comment by MatthewFlamm** [comment]
> 1. realising that a breaking change happens in a PR, and
> 2. remembering to label and/or note this fact somewhere.

Number 1 should already be part of the authoring and review process.  I'm suggesting that _if_ we note it, to include a breaking change section (it doesn't have to be lengthy if not a complicated breaking change), and to add a label.  

We aren't at a stable version, but helping users transition through breaking changes is still important.

**Comment by akaszynski** [comment]
> . I'm suggesting that _if_ we note it, to include a breaking change section (it doesn't have to be lengthy if not a complicated breaking change), and to add a label.

Fully agree there. That way we can look up what changed in the notes of the PR when running through the blame in GitHub.
