### ISSUE TITLE
Adding a mesh to a plotter with smooth_shading=True leads to a deep copy of the mesh

### ISSUE THREAD

**Issue by p-j-smith** [pyvista/pyvista#3069]
### Describe the bug, what's wrong, and what you expected.

Hi,

I'm not sure if this behaviour is intended or not, but when a mesh is added to a plotter, if `smooth_shading=True` then a deep copy of the mesh is created.

This is because [point normals are calculated inplace](https://github.com/pyvista/pyvista/blob/2f77c141794de181d1f9cd9a1c39e7a0321d34b5/pyvista/plotting/_plotting.py#L86-L88):
```py
mesh.compute_normals(cell_normals=False, inplace=True)
```

Perhaps calculating normals and adding point data would be preferable? Something like:
```py
normals = mesh.compute_normals(cell_normals=False, inplace=False)['Normals']
mesh.point_data.set_array(normals, 'Normals')
```

Or if this behaviour is intended, perhaps it's worth adding a note to the docstring to clarify a deep copy of the mesh will be made.

### Steps to reproduce the bug.

This test was added in #2888, but it fails if `smooth_shading=True` when adding the mesh to the plotter.
```py
import numpy as np
import pyvista

sphere = pyvista.Sphere()
sphere.point_data['numbers'] = np.arange(sphere.n_points)
sphere2 = sphere.copy(deep=False)

sphere['numbers'] *= -1  # sphere2 'numbers' are also modified

assert np.array_equal(sphere['numbers'], sphere2['numbers'])
assert np.shares_memory(sphere['numbers'], sphere2['numbers'])

plotter = pyvista.Plotter()
plotter.add_mesh(sphere, scalars=None, smooth_shading=True)

sphere[
    'numbers'
] *= -1  # sphere2 'numbers' are also modified after adding to Plotter.  (See  issue #2461)

assert np.array_equal(sphere['numbers'], sphere2['numbers'])
assert np.shares_memory(sphere['numbers'], sphere2['numbers'])

```

### System Information

```shell
Date: Mon Jul 25 18:06:02 2022 BST

                OS : Darwin
            CPU(s) : 20
           Machine : x86_64
      Architecture : 64bit
       Environment : Python
        GPU Vendor : ATI Technologies Inc.
      GPU Renderer : AMD Radeon Pro 5700 XT OpenGL Engine
       GPU Version : 4.1 ATI-4.6.21

  Python 3.9.12 (main, Jun  1 2022, 06:36:29)  [Clang 12.0.0 ]

           pyvista : 0.36.dev0
               vtk : 9.0.3
             numpy : 1.22.4
           imageio : 2.19.3
           appdirs : 1.4.4
            scooby : 0.5.12
        matplotlib : 3.5.2
         pyvistaqt : 0.10.dev0
           IPython : 8.3.0
             scipy : 1.8.1
              tqdm : 4.64.0
            meshio : 5.3.4
```

**Comment by akaszynski** [comment]
Quite true. That's something we can optimize, but this will break down when splitting sharp edges as it modifies the topology of the mesh.

**Comment by p-j-smith** [comment]
Yeah that's a good point, changing the topology necessarily means you end up with a new mesh. But it would be nice to be able to use smooth shading without a copy being made. I'll submit a pr with the above changes :)

**Comment by banesullivan** [comment]
@akaszynski and @p-j-smith, the issue is that when `inplace=True`, we leverage `copy_from()` to override the mesh, which in fact, is a `DeepCopy` operation. 

https://github.com/pyvista/pyvista/blob/1ef0bb3814eb13dfd7f433d99b07e704f6123fe5/pyvista/core/filters/poly_data.py#L1589-L1591

https://github.com/pyvista/pyvista/blob/188fab8bb86da8ceb6ad6293347e5b51a58c8f4a/pyvista/core/dataset.py#L1990

I'm actually surprised this issue didn't pop up anywhere else as this effectively means all `inplace=True` operations leveraging `copy_from()` are invalid and creating deep copies.

IMO, #3087 is only a patch specifically for `compute_normals` and `smooth_shading` when used together. A proper fix would be to not deep copy in `copy_from`
