### ISSUE TITLE
Clip Plane Filter Doesn't Automatically Update

### ISSUE THREAD

**Issue by kevinatrix15** [pyvista/pyvista#3079]
### Describe the bug, what's wrong, and what you expected.

I am trying to apply the clip plane filter to a mesh. The visualization window appears with the original clipping applied, but when I move the plane around it fails to update.

### Steps to reproduce the bug.

```python 
import pyvista as pv
from pyvista import examples

vol = examples.download_brain()

p = pv.Plotter()
p.add_mesh_slice_orthogonal(vol)
p.show()

p.plane_clipped_meshes
 ```

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Tue Jul 26 09:20:19 2022 Mountain Daylight Time

                OS : Windows
            CPU(s) : 16
           Machine : AMD64
      Architecture : 64bit
               RAM : 31.7 GiB
       Environment : Python
        GPU Vendor : Intel
      GPU Renderer : Intel(R) UHD Graphics 630
       GPU Version : 4.5.0 - Build 27.20.100.9664

  Python 3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)]

           pyvista : 0.35.2
             numpy : 1.18.5
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.12
        matplotlib : 3.2.2
             PyQt5 : 5.11.3
           IPython : 7.16.1
          colorcet : 3.0.0
           cmocean : 2.0
             scipy : 1.8.1
              tqdm : 4.64.0
        jupyterlab : 2.1.5

  Intel(R) Math Kernel Library Version 2020.0.1 Product Build 20200208 for
  Intel(R) 64 architecture applications
--------------------------------------------------------------------------------
```

### Screenshots

![image](https://user-images.githubusercontent.com/10439130/181045009-fce8f253-c231-496d-9f4a-eaf845fc1c33.png)

**Comment by akaszynski** [comment]
Thanks for pointing this out.

Looks like a regression. We really should be testing our widgets in our CI/CD.

I'll come up with a patch for this soon.

**Comment by banesullivan** [comment]
ooof, haven't run this to verify but that's a bad regression. Happy to help where needed, @akaszynski

**Comment by p-j-smith** [comment]
I think this is linked to https://github.com/pyvista/pyvista/issues/3066#issuecomment-1194121987. I just tested it out, and if `plotter.add_mesh` doesn't make a copy of the mesh, then the plotter updates as expected
