### ISSUE TITLE
Display grid with pythreejs backend

### ISSUE THREAD

**Issue by leilakany** [pyvista/pyvista#3091]
### Describe the feature you would like to be added.

Hi,
Is it possible to use the `show_grid` method of the potter in a notebook with pythreejs backend?

https://docs.pyvista.org/api/plotting/_autosummary/pyvista.Plotter.show_grid.html

**Comment by akaszynski** [comment]
I'm afraid not. Ideally it would be, and I'm highly considering that since k3d is well supported, we add support for `k3d` and eventually deprecate `pythreejs`
