### ISSUE TITLE
Saving mesh and texture after texture mapping

### ISSUE THREAD

**Issue by Weafre** [pyvista/pyvista#3119]
Hi  @banesullivan
I have the same question as @shakasaki, how do we save both mesh and texture in a single file after texture mapping. 

Hello, I have a question that relates to this post. I am able to load a topographic map and apply textures to it. I create a dictionary of textures as shown above 

e.g.,

`# Associate the texture with the mapped mesh
mapped_surf.textures["aerial"] = pv.numpy_to_texture(image)`

and then I save a vtk file using surf.save(filename)

But when I open the vtk file in paraview, I can not load the textures. I see the topographic map, and the texture coordinates, but not the texture dictionary anywhere?

I can also post this as a separate question, but I thought it relates well to this post.
Thanks for the input!

_Originally posted by @shakasaki in https://github.com/pyvista/pyvista-support/issues/159#issuecomment-706712507_

**Comment by akaszynski** [comment]
Looks like we're not properly exporting the texture when saving the dataset. Ping me if we don't resolve this in a week.

**Comment by banesullivan** [comment]
PyVista's `textures` attribute that tracks associated textures is unique to PyVista and not reflected upstream in VTK. This is why a simple `save()` call does not output the textures. You will have to `save()` the mesh after mapping the texture (adding `Texture Coordinates`) *and* save out the texture as an image (PNG, JPEG, etc) to load separately in ParaView.

**Comment by banesullivan** [comment]
Not actionable and texture tracking is being deprecated in #4515
