### ISSUE TITLE
Bug: Circular Import - `pyvista.FieldAssociation`

### ISSUE THREAD

**Issue by adam-grant-hendry** [pyvista/pyvista#3141]
### Describe the bug, what's wrong, and what you expected.

Reposting from [`pyvistaqt` issue #168](https://github.com/pyvista/pyvistaqt/issues/168), for some unknown reason, `pyvista` seems to have a circular import bug when importing in some (but not all) virtual environments.

### Steps to reproduce the bug.

1. `py -m venv .venv && .venv\Scripts\Activate.ps1`
2. `py -m pip install pyvista`
3. Run python in terminal:

```python
Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvista
Traceback (most recent call last):   
  File "<stdin>", line 1, in <module>
  File "%USERPROFILE%\example\.venv\lib\site-packages\pyvista\__init__.py", line 14, in <module>
    from pyvista.core import *
  File "%USERPROFILE%\example\.venv\lib\site-packages\pyvista\core\__init__.py", line 3, in <module>
    from .dataset import DataSet, DataObject
  File "%USERPROFILE%\example\.venv\lib\site-packages\pyvista\core\dataset.py", line 36, in <module>
    from .filters import DataSetFilters, _get_output
  File "%USERPROFILE%\example\.venv\lib\site-packages\pyvista\core\filters\__init__.py", line 58, in <module>
    from .data_set import DataSetFilters
  File "%USERPROFILE%\example\.venv\lib\site-packages\pyvista\core\filters\data_set.py", line 9, in <module> 
    from pyvista import FieldAssociation, _vtk
ImportError: cannot import name 'FieldAssociation' from partially initialized module 'pyvista' (most likely due to a circular import) (%USERPROFILE%\example\.venv\lib\site-packages\pyvista\__init__.py)
```

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Mon Aug 08 13:26:22 2022 Pacific Daylight Time

                OS : Windows
            CPU(s) : 96
           Machine : AMD64
      Architecture : 64bit
       Environment : Python
        GPU Vendor : NVIDIA Corporation
      GPU Renderer : Quadro RTX 8000/PCIe/SSE2
       GPU Version : 4.5.0 NVIDIA 516.94

  Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64
  bit (AMD64)]

           pyvista : 0.36.1
               vtk : 9.1.0
             numpy : 1.23.1
           imageio : 2.21.1
           appdirs : 1.4.4
            scooby : 0.5.12
        matplotlib : 3.5.2
--------------------------------------------------------------------------------
```

**Comment by adam-grant-hendry** [comment]
I see the error. The repo `pyvista.__init__.py` has a specific sort order:

```python
from pyvista._version import __version__
from pyvista.plotting import *
from pyvista.utilities import *
from pyvista.core import *
from pyvista.utilities.misc import _get_vtk_id_type, vtk_version_info, _set_plot_theme_from_env
from pyvista import _vtk
from pyvista.jupyter import set_jupyter_backend, PlotterITK
from pyvista.themes import set_plot_theme, load_theme, _rcParams
from pyvista.themes import DefaultTheme as _GlobalTheme  # hide this
```

My environment uses `isort` to sort imports on save, so when I viewed and saved, it put them in alphabetical order per PEP8:

```python
from pyvista._version import __version__
from pyvista.core import *
from pyvista.jupyter import PlotterITK, set_jupyter_backend
from pyvista.plotting import *
from pyvista.themes import DefaultTheme as _GlobalTheme  # hide this
from pyvista.themes import _rcParams, load_theme, set_plot_theme
from pyvista.utilities import *
from pyvista.utilities.misc import (
    _get_vtk_id_type,
    _set_plot_theme_from_env,
    vtk_version_info,
)
```

I'll see if I can turn off `isort` for `site-packages`, but I think it would be good to add an `# isort: skip` to modules that must retain import order, or an `isort:skip_file` to the module docstring to turn off `isort` for the file and add a note or two stating the sort order is important ([relevant `isort` docs](https://pycqa.github.io/isort/#skip-processing-of-imports-outside-of-configuration)).

**Comment by adeak** [comment]
In `pyproject.toml` we have
https://github.com/pyvista/pyvista/blob/7ca5c227f9111dd1c280da06a3959e37ec047541/pyproject.toml#L1-L8

This explicitly ignores `__init__.py` files for `isort`. And it works: if I add a dummy edit to `pyvista/__init__.py` and run `pre-commit run`, it's green.

So the question is why your tooling doesn't pick up on all that. You said

> My environment uses `isort` to sort imports on save,

Sounds like your tooling does things it shouldn't. It should respect the `pre-commit` setup for the project.

**Comment by adam-grant-hendry** [comment]
> So the question is why your tooling doesn't pick up on all that. 

It's a separate project altogether that imports `pyvista`, not a fork/clone of `pyvista` itself. It has its own `pyproject.toml`, which is why I didn't catch it.

I was looking at `pyvista` source in that project's virtual environment site packages.

**Comment by adeak** [comment]
Then it's not clear to me why `isort` would touch anything outside your repo. Is your env inside the repo?

**Comment by adam-grant-hendry** [comment]
> Then it's not clear to me why `isort` would touch anything outside your repo. Is your env inside the repo?

No, its outside the repo. It's just in `.venv/Lib/site-packages` like usual. In VSCode, I had

```json
"[python]": {
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        },
        "editor.defaultFormatter": "ms-python.python",
        "editor.formatOnSave": true,
}
```

and my `pyproject.toml` `[tool.isort]` settings didn't have any restrictions against sorting imports on `__init__.py` files (my `skip_glob` was completely empty).

This was just a silly uncaught error on my end.

**Comment by adeak** [comment]
Well, I still don't get it, but as long as it's fixed.

**Comment by adam-grant-hendry** [comment]
> Well, I still don't get it, but as long as it's fixed.

I literally opened the file in my editor and hit save (force of habit), so I'm sure that's why it edited it.

**Comment by adeak** [comment]
Ah, I see, thanks. Sounds like a dangerous feature! Consider adopting pre-commit hooks instead.

Closing as non-issue.

**Comment by adam-grant-hendry** [comment]
> Ah, I see, thanks. Sounds like a dangerous feature! Consider adopting pre-commit hooks instead.

I use both. They're both incredibly useful.

> Closing as non-issue.

Definitely a non-issue. Only thing I didn't realize is that we had an import-order dependency. 

**RECOMMENDATION:** It'd be nice to avoid this import order dependency if at all possible. This is kind of like the issue you have with `setuptools` where, in some cases, it has to be imported before other imports. This can make things brittle, and it wasn't clear to me from any of the comments in the file that the imports had to be in a certain order or else a circular imports would occur. e.g.

I said `PEP 8` before, but its actually not in `PEP 8`, but something that `isort` does. Sorting alphabetically makes it easier to search through and find imported packages when reading.

**Comment by adam-grant-hendry** [comment]
@adeak It's also possible to disable the `isort` behavior of sorting entirely for the file by adding an [` # isort: skip_file` to the module docstring](https://pycqa.github.io/isort/#skip-processing-of-imports-outside-of-configuration).

This would prevent `isort` from ever sorting the imports and make it clear to readers that we rely on a certain import order.

Can I make a PR for that?

**Comment by adeak** [comment]
> It'd be nice to avoid this import order dependency if at all possible.

I agree, but not exactly because of this issue.

> This is kind of like the issue you have with setuptools where, in some cases, it has to be imported before other imports. This can make things brittle, and it wasn't clear to me from any of the comments in the file that the imports had to be in a certain order or else a circular imports would occur.

Arguably this isn't too much like `setuptools` because all this is internal to `pyvista`. downstream users doing `import pyvista` should not be affected in any way, unless they go out of their way to edit `pyvista`'s code ;) It is brittle for people developing pyvista, but
1. we have `isort` as part of pre-commit hooks, so nobody should want to force `isort` on `__init__.py` files to break things
2. even if someone does that, they'll see that things blow up and realise why `isort` was disabled in the first place.

Now, from an ivory-tower purity standpoint, I'd absolutely prefer to remove this order dependence, but the question is what the cost is. Breaking up reference cycles usually involves moving imports around, inside functions or sometimes to the bottom of modules. That's a pretty high cost. Unless some of these order issues are purely due to typing (but I doubt that).

> It's also possible to disable the isort behavior of sorting entirely for the file by adding an[ # isort: skip_file to the module docstring](https://pycqa.github.io/isort/#skip-processing-of-imports-outside-of-configuration).

I figured that's possible. I don't have a strong opinion about this: it would do what the current tooling does: make `isort` ignore the imports. So adding that header would be mostly redundant. But I also understand your motivation to signal something to contributors. I leave it up to you to decide about opening a PR, other members might have different opinions.
