### ISSUE TITLE
[BUG] Spurious vertex added in a PolyData after `clean`

### ISSUE THREAD

**Issue by tbridel** [pyvista/pyvista#3172]
### Describe the bug, what's wrong, and what you expected.

It seems the `clean` method for PolyData generates spurious vertices that were not part of the original mesh. And no face is actually connected to those "new" spurious vertices.

### Steps to reproduce the bug.

The [example in the doc of PolyData clean](https://docs.pyvista.org/api/core/_autosummary/pyvista.PolyData.clean.html) actually breaks.

```python
import pyvista as pv
import numpy as np
points = np.array([[0, 0, 0], [0, 1, 0], [1, 0, 0]], dtype=np.float32)
faces = np.array([3, 0, 1, 2, 3, 0, 3, 3])
mesh = pv.PolyData(points, faces)
mout = mesh.clean()
```

Then, `mout.points` yields

```python
pyvista_ndarray([[0.000e+00, 0.000e+00, 0.000e+00],
                 [0.000e+00, 1.000e+00, 0.000e+00],
                 [1.000e+00, 0.000e+00, 0.000e+00],
                 [9.669e-44, 1.459e-42, 0.000e+00]], dtype=float32)
```

with an extra spurious vertex that 1/ has senseless coordinates and 2/ is actually a duplicate of a pre-existing vertex.

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Tue Aug 16 08:07:08 2022 UTC

                OS : Linux
            CPU(s) : 8
           Machine : x86_64
      Architecture : 64bit
               RAM : 54.9 GiB
       Environment : Python
        GPU Vendor : Mesa/X.org
      GPU Renderer : llvmpipe (LLVM 12.0.0, 256 bits)
       GPU Version : 4.5 (Core Profile) Mesa 21.2.6

  Python 3.8.10 (default, Mar 15 2022, 12:22:08)  [GCC 9.4.0]

           pyvista : 0.33.2
               vtk : 9.0.1
             numpy : 1.19.5
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.7
        matplotlib : 3.3.4
           IPython : 7.16.1
             scipy : 1.8.1
              tqdm : 4.60.0
            meshio : 4.4.1
--------------------------------------------------------------------------------
```

**Comment by darikg** [comment]
I think that example is ill-formed -- the faces array is referencing a point (3) that doesn't exist, so the senseless coordinates you mention are presumably coming from out-of-bounds array access or something.

Changing `faces = np.array([3, 0, 1, 2, 3, 0, 3, 3])` to `faces = np.array([3, 0, 1, 2, 3, 0, 2, 2])` behaves as expected.

**Comment by akaszynski** [comment]
Thanks for pointing this out. Want to push a quick PR to fix this?
