### ISSUE TITLE
mesh.rotate_*( ) & mesh.translate( ) move camera even though camera.position is specified

### ISSUE THREAD

**Issue by leo2r** [pyvista/pyvista#3174]
### Describe the bug, what's wrong, and what you expected.

When applying rotations or translations to meshes, it seems like the camera moves around even though a camera.position is specified. This seems like undesired behaviour, as when I specify a camera I would like it to be fixed and not be influenced by a mesh being rotated or translated. Seems like even the axis changes sometimes (couldn't get a screenshot this time).

### Steps to reproduce the bug.

```python
from pyvista import examples
filename = examples.planefile
plane = pv.read(filename)

# Alternate between different translations and rotations here
plane_mesh = plane.translate((100, 0, 100), inplace=False)
plane_mesh = plane_mesh.rotate_z(-30, inplace=False)

p = pv.Plotter()
p.show_axes()
p.add_mesh(plane, color=True, show_edges=True, opacity=0.5)
p.add_mesh(plane_mesh, color=True, show_edges=True, opacity=0.5)
p.camera.position = (0, 3000, 2000)
p.show()
```

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Tue Aug 16 12:06:34 2022 CEST

                OS : Darwin
            CPU(s) : 8
           Machine : x86_64
      Architecture : 64bit
               RAM : 16.0 GiB
       Environment : Jupyter
       File system : apfs
        GPU Vendor : ATI Technologies Inc.
      GPU Renderer : AMD Radeon Pro 560 OpenGL Engine
       GPU Version : 4.1 ATI-4.8.54

  Python 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 05:57:50)
  [Clang 11.1.0 ]

           pyvista : 0.36.1
               vtk : 9.1.0
             numpy : 1.21.6
           imageio : 2.21.1
           appdirs : 1.4.4
            scooby : 0.5.12
        matplotlib : 3.5.2
           IPython : 7.33.0
          colorcet : 3.0.0
           cmocean : 2.0
        ipyvtklink : 0.2.2
             scipy : 1.7.3
              tqdm : 4.64.0
            meshio : 5.3.4
        jupyterlab : 3.4.4
--------------------------------------------------------------------------------
```

### Screenshots

<img width="1277" alt="Screenshot 2022-08-16 at 12 02 00" src="https://user-images.githubusercontent.com/27723482/184854059-59f2585f-6609-4ff6-a6b5-c5f3f6deb41e.png">
<img width="1281" alt="Screenshot 2022-08-16 at 12 01 36" src="https://user-images.githubusercontent.com/27723482/184854073-ccbbde91-f6b9-4f10-aa82-1bd4a89743dc.png">
<img width="1279" alt="Screenshot 2022-08-16 at 12 01 01" src="https://user-images.githubusercontent.com/27723482/184854081-f06c10cd-5b20-4da0-b52f-b06b70228411.png">

**Comment by leo2r** [comment]
Hey, thanks for the suggestion, that does work indeed! Sorry for opening an issue about this 😅 Closing now 🙏🏽

**Comment by leo2r** [comment]
Sorry actually this sets the focal point on the centre of the original plane, but does it have to be dependent on a mesh? Or can it be set to the global origin instead? I'm not sure for my use case that I'll always want the focal point to be centred on a mesh as they'll be moving about the global origin!

**Comment by MatthewFlamm** [comment]
> Sorry actually this sets the focal point on the centre of the original plane, but does it have to be dependent on a mesh? Or can it be set to the global origin instead?

In my example, `plane.center` is a sequence (X, Y, Z).  You can use any point in space.  Try `(0, 0, 0)` to use the world origin.

**Comment by leo2r** [comment]
> > Sorry actually this sets the focal point on the centre of the original plane, but does it have to be dependent on a mesh? Or can it be set to the global origin instead?
> 
> In my example, `plane.center` is a sequence (X, Y, Z). You can use any point in space. Try `(0, 0, 0)` to use the world origin.

Oh duh of course, thank you! 🙏🏽
