### ISSUE TITLE
Pyvista doesn't run on ubuntu 22.04

### ISSUE THREAD

**Issue by Danzip** [pyvista/pyvista#3176]
### Describe the bug, what's wrong, and what you expected.

When running any pyvista plot I run into the following error: 
`libGL error: MESA-LOADER: failed to open radeonsi: /usr/lib/dri/radeonsi_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open radeonsi: /usr/lib/dri/radeonsi_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
2022-08-16 15:37:37.583 (   0.752s) [        6395F740]vtkXOpenGLRenderWindow.:651    ERR| vtkXOpenGLRenderWindow (0x55bea2f15d20): Cannot create GLX context.  Aborting.
ERROR:root:Cannot create GLX context.  Aborting.
`

I tested pyvista on another laptop with ubuntu 21.04 and there were no issues, 
I've looked for GLX drivers and Mesa-loader but didn't find the answer 
can anyone clarify What is going on with the the drivers?
Ive seen another open [discussion](https://github.com/pyvista/pyvista/discussions/2783)
I'd love an answer here or there.
Thank you

### Steps to reproduce the bug.

```python
from pyvista import demos
demos.plot_wave()
```

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Tue Aug 16 15:41:14 2022 IDT
                OS : Linux
            CPU(s) : 16
           Machine : x86_64
      Architecture : 64bit
               RAM : 62.2 GiB
       Environment : IPython
       File system : ext4
       GPU Details : error
  Python 3.8.10 (default, May 19 2021, 18:05:58)  [GCC 7.3.0]
           pyvista : 0.36.1
               vtk : 9.1.0
             numpy : 1.19.4
           imageio : 2.13.1
           appdirs : 1.4.4
            scooby : 0.5.12
        matplotlib : 3.3.3
           IPython : 8.4.0
          colorcet : 3.0.0
           cmocean : 2.0
        ipyvtklink : 0.2.2
             scipy : 1.5.3
              tqdm : 4.64.0
         pythreejs : Version unknown
--------------------------------------------------------------------------------
```

### Screenshots

![Screenshot from 2022-08-16 15-44-49](https://user-images.githubusercontent.com/34044636/184882686-e738b2fb-293c-4403-b730-472c5adddffa.png)

**Comment by akaszynski** [comment]
Curious, is that with `pip install pyvista` or `conda install pyvista`?

**Comment by Danzip** [comment]
Both
