### ISSUE TITLE
Reader memory  usage/memory usage when wrapping vtkDataSets

### ISSUE THREAD

**Issue by MatthewFlamm** [pyvista/pyvista#3178]
As pointed out in https://github.com/pyvista/pyvista-support/issues/500#issuecomment-921108703 and https://github.com/pyvista/pyvista-support/issues/500#issuecomment-921106561, readers seem to duplicate memory usage.

Using this code shows that the mesh data is copied from the reader to the mesh object.  This is only released when deleting the reader object.

```py
import pyvista as pv
from pyvista import examples

from memory_profiler import profile

@profile
def run():
    filename = examples.download_parched_canal_4k(load=False)
    reader = pv.get_reader(filename)
    mesh = reader.read()
    del reader

if __name__ == "__main__":
    run()
```

```txt
$python test.py 
Filename: test.py

Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
     6    110.2 MiB    110.2 MiB           1   @profile
     7                                         def run():
     8    110.2 MiB      0.0 MiB           1       filename = examples.download_parched_canal_4k(load=False)
     9    110.4 MiB      0.2 MiB           1       reader = pv.get_reader(filename)
    10    302.8 MiB    192.3 MiB           1       mesh = reader.read()
    11    206.8 MiB    -96.0 MiB           1       del reader
```

**Comment by MatthewFlamm** [comment]
Trying to isolate which part of the `read` method:

https://github.com/pyvista/pyvista/blob/e827dcc131b4e640337b17fa092c71a577038f7f/pyvista/utilities/reader.py#L294-L312

A minimal set of steps used in `read` is:

```py
self.Update()
output = self.GetOutputDataObject(0)
pv.wrap(output)
```

If I use this minimal set in the above code as:

```py
@profile
def run():
    filename = examples.download_parched_canal_4k(load=False)
    reader = pv.get_reader(filename)
    reader.reader.Update()
    output = reader.reader.GetOutputDataObject(0)
    mesh = pv.wrap(output)
    del output
    del reader
```

```
Filename: test.py

Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
     6    110.2 MiB    110.2 MiB           1   @profile
     7                                         def run():
     8    110.2 MiB      0.0 MiB           1       filename = examples.download_parched_canal_4k(load=False)
     9    110.4 MiB      0.2 MiB           1       reader = pv.get_reader(filename)
    10    206.6 MiB     96.2 MiB           1       reader.reader.Update()
    11    206.6 MiB      0.0 MiB           1       output = reader.reader.GetOutputDataObject(0)
    12    302.8 MiB     96.2 MiB           1       mesh = pv.wrap(output)
    13    302.8 MiB      0.0 MiB           1       del output
    14    206.8 MiB    -96.0 MiB           1       del reader
```

This suggests that it is not the reader itself, but the pyvista wrap that duplicates the memory usage.  This can also be confirmed by removing the wrap line.

```py
@profile
def run():
    filename = examples.download_parched_canal_4k(load=False)
    reader = pv.get_reader(filename)
    reader.reader.Update()
    mesh = reader.reader.GetOutputDataObject(0)
    del reader
```

```
Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
     6    110.2 MiB    110.2 MiB           1   @profile
     7                                         def run():
     8    110.2 MiB      0.0 MiB           1       filename = examples.download_parched_canal_4k(load=False)
     9    110.4 MiB      0.2 MiB           1       reader = pv.get_reader(filename)
    10    206.6 MiB     96.2 MiB           1       reader.reader.Update()
    11    206.6 MiB      0.0 MiB           1       mesh = reader.reader.GetOutputDataObject(0)
    12    206.6 MiB      0.0 MiB           1       del reader
```

**Comment by MatthewFlamm** [comment]
cc @adam-grant-hendry

At least in the case of this exact file/dataset, I think I have pinpointed the issue not to be in the readers themselves, but in the wrapping operation to get a `pyvista.DataSet`.

**Comment by adam-grant-hendry** [comment]
> At least in the case of this exact file/dataset, I think I have pinpointed the issue not to be in the readers themselves, but in the wrapping operation to get a `pyvista.DataSet`.

Thanks for looking into this!

That seems consistent with the [#500 error](https://github.com/pyvista/pyvista-support/issues/500#issuecomment-919387362) and the additional [mutation side effects](https://github.com/pyvista/pyvista/pull/3170#issuecomment-1216916394) I've been seeing.

**Comment by MatthewFlamm** [comment]
`UniformGrid` uses `DeepCopy` when we pass it vtkImageData object.  This is very inefficient.  I wonder why we cannot use `ShallowCopy`?  Switching this fixes the issue for me.

**Comment by adam-grant-hendry** [comment]
> Switching this fixes the issue for me.

Which issue specifically? The [memory leak](https://github.com/pyvista/pyvista-support/issues/500#issuecomment-919387362) or simply [extra memory being allocated by wrapping](https://github.com/pyvista/pyvista/issues/3178#issuecomment-1217063639)?

Are you able to run [the memory leak code](https://github.com/pyvista/pyvista-support/issues/500#issuecomment-919387362)  without memory leaking?

**Comment by MatthewFlamm** [comment]
It fixes the issue raised in this PR, which is that wrapping certain vtk datasets doubles memory and may seem to leak memory unless there vtk dataset is garbage collected.  This manifests in the reader since the reader keeps a reference to the vtk dataset object.

**Comment by adam-grant-hendry** [comment]
Awesome! I think the next steps are to turn this into a PR, run it against the test suite, and get feedback from the other developers. I'm not sure why `deep_copy` was used, but someone else might know why.

**Comment by MatthewFlamm** [comment]
It turns out that some datasets, like PolyData, use shallow copy by default with an option.  Others only allow deep copy.  This seems like a straightforward PR at this point.
