### ISSUE TITLE
Mesh operators

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#321]
Should we implement the `__add__` (`+`) operator for all mesh types under `pyvista.Common` to make combining/appending meshes a bit easier/more intuitive? The `pyvista.PolyData` class already has this operator but it could easily be implemented for all mesh types and return an `UnstrucutredGrid` (or `PolyData` if all inputs are `PolyData`).

What about other operators - what would their roles be?

These seem useful for mesh operations:

- `__eq__` (`mesha == meshb`) are the meshes equivalent - i.e. same points/cells (how would we avoid ordering differences?)
- `__ne__` (`mesha != meshb`) meshes don't have the same spatial reference
- `__contains__` (`x in mesh`) perhaps allow string names for point/cell/field data arrays or coordinates for a point location (this would need some sort of tolerance)
- `__len__` (`len(mesh)`) maybe return the number of points?
- `__sub__` (`mesha - meshb`) something like `PolyData.boolean_difference`? but how would this generalize to all (non-`PolyData`) meshes?

Maybe? I'm not sure about these and would appreciate community input:

- `__mul__` (` mesh * x`) maybe apply the multiplier to all arrays in the mesh?
- `__mod__` (`mesh % x`) ?
- `__truediv__` (`mesha / meshb` or `mesha / x`) ?
- `__lt__` (`mesha < meshb`) ?
- `__le__` (`mesha <= meshb`) ?
- `__gt__` (`mesha > meshb`) ?
- `__ge__` (`mesha >= meshb`) ?

**Comment by akaszynski** [comment]
Ordering differences for the ``__eq__`` operator could only be avoided with a nearest neighbors comparison of the two meshes once the number of points and faces were verified.  Still, this depends on what the definition of "equals" is.  Considering a nearest neighbor calculation would be computationally expensive, maybe a ``np.all_close`` would be sufficient.  Same applies to ``__ne__``

The length of a mesh is a bit ambiguous.  I'd leave it out for most ``pyvista`` objects but apply it to blocks.

Subtracting meshes using a boolean difference would work for meshes, but it's not implemented AFAIK for unstructured or structured grids.

I think that many of the operators aren't applicable to most ``pyvista`` objects as they would seem to be applied quite ambiguously to the user.  For example, would the ``__mul__`` operator be operating on the points or the faces, or all the point/cell arrays of the mesh?
