### ISSUE TITLE
node.js v6.10.0 or higher is needed

### ISSUE THREAD

**Issue by pinshuai** [pyvista/pyvista#322]
I installed pyvista using conda. Then when I opened Anaconda Navigator and launch Jupyter Lab, I try to import pyvista and got the following error.

<img width="1017" alt="Screenshot 2019-07-26 15 50 54" src="https://user-images.githubusercontent.com/34693887/61985267-4b637600-afbd-11e9-9a1c-ec1509ca1132.png">
<img width="983" alt="Screenshot 2019-07-26 15 51 36" src="https://user-images.githubusercontent.com/34693887/61985271-4f8f9380-afbd-11e9-8556-67c22f84d644.png">

I have the latest version of nodejs installed using `conda install nodejs`. 

Name |                   Version|                   Build  Channel
---|---|---
nodejs    |                10.13.0     |         h0a44026_0  

Any idea?

**Comment by banesullivan** [comment]
First, can you share the output of:

```py
import scooby
# Mandatory packages.
core = ['pyvista', 'vtk', 'numpy', 'imageio', 'appdirs', 'scooby']

# Optional packages.
optional = ['matplotlib', 'PyQt5', 'IPython', 'ipywidgets', 'colorcet',
            'cmocean', 'panel']

report = scooby.Report(core=core, optional=optional,)
print(report)
```


-----

I suspect you either have an outdated version of `panel` which is a soft dependency of PyVista or this is outright a [`panel`](https://github.com/pyviz/panel) issue. If Panel is at the latest version, then you may want to raise an issue with them. You can reproduce this with just:

```py
import panel
panel.extension('vtk')
```

----

I just pushed a patch avoid this issue on the master branch if you're comfortable installing from a git source:

```bash
pip install git+git://github.com/pyvista/pyvista@master
```

**Comment by pinshuai** [comment]
This is the report. I think I have the latest `panel`.

```
--------------------------------------------------------------------------------
  Date: Fri Jul 26 21:27:47 2019 PDT

            Darwin : OS
                 8 : CPU(s)
            x86_64 : Machine
             64bit : Architecture
            Python : Environment

  Python 3.7.3 (default, Mar 27 2019, 16:54:48)  [Clang 4.0.1
  (tags/RELEASE_401/final)]

  Could not import : pyvista
  Could not import : vtk
            1.17.0 : numpy
             2.5.0 : imageio
             1.4.3 : appdirs
             0.4.3 : scooby
             7.6.1 : IPython
             7.5.0 : ipywidgets
             0.6.0 : panel
--------------------------------------------------------------------------------
```

**Comment by pinshuai** [comment]
After upgrading `pyvista` from github, the issue is resolved. Thanks.

**Comment by banesullivan** [comment]
I cross-posted this in https://github.com/pyviz/panel/issues/551 as it seems like a `panel` issue and not something we can address in PyVista other than catching and ignoring the `RuntimeError`
