### ISSUE TITLE
Add "Pyvista->PyVista" as a optional dictionaries of codespell 

### ISSUE THREAD

**Issue by tkoyama010** [pyvista/pyvista#3233]
### Describe what maintenance you would like added.

We can add "Pyvista->PyVista" as an optional dictionary of [codespell ](https://github.com/codespell-project/codespell#usage).
Inspired by #3231 .

### Links to source code.

`.codespellrc`
```cfg
[codespell]
builtin = dictionary.txt
```
`dictionary.txt`
```txt
Pyvista->PyVista
```

### Pseudocode or Screenshots

None

**Comment by banesullivan** [comment]
Handling directly in #3231

**Comment by banesullivan** [comment]
Nevermind. This doesn't seem to work. Codespell does not seem to support capitalization corrections.

**Comment by tkoyama010** [comment]
That's too bad..
