### ISSUE TITLE
Export Scalar bars with export_html function

### ISSUE THREAD

**Issue by rajesh1359** [pyvista/pyvista#3253]
### Describe the feature you would like to be added.

Hello,

Currently, the plotter.export_html function just exports the html file with mesh, rendering etc but it does not export scalar bars showing the values for the color range of the contours. Would it be possible to add this capability?
It is mentioned under the Caveats  here (https://docs.pyvista.org/user-guide/jupyter/pythreejs.html)

### Pseudocode or Screenshots

```python
Insert code here
```
Or drag your screenshot here!

**Comment by cuesy** [comment]
Hello! Any news on this?

**Comment by banesullivan** [comment]
Still on our radar but no progress yet. Thank you for being patient
