### ISSUE TITLE
Open an Issue when linkcheck fails

### ISSUE THREAD

**Issue by laysauchoa** [pyvista/pyvista#3268]
### Describe the feature you would like to be added.

**Problem**
Recently, we have added linkcheck to run periodically, every week. However, someone has to go and look for the failed build and do the fixes. This could go unseen or unnoticed.

**Proposed solution**
Automatically open an Issue when the ``linkcheck`` fails. So we can better monitor it and fix it. We can also assign to some of the maintainers

I will be happy to work on that

**Comment by tkoyama010** [comment]
It is  a great idea to have auto Pull Requests. We always welcome your contribution.

**Comment by laysauchoa** [comment]
@tkoyama010 this would be more like an issue saying that it failed, not the pull request with the fix.

**Comment by tkoyama010** [comment]
I'm sorry. I misunderstood your suggestion (I was imagining something like dependabot.). In this case, I also think Issue would be better.

**Comment by tkoyama010** [comment]
First of all, we don't know the correct URL automatically :sweat_smile:

**Comment by banesullivan** [comment]
@laysauchoa, I think this is a great idea. Would you be willing to take this on?

I believe there are GitHub Actions that can open an issue like this easily.

I would set up the CI on a cronjob which:

1. runs link check and captures output as text
2. if fails, opens the issue with error text as body of the issue

**Comment by adeak** [comment]
> @laysauchoa, I think this is a great idea. Would you be willing to take this on?
> 
> I believe there are GitHub Actions that can open an issue like this easily.
> 
> I would set up the CI on a cronjob which:
> 
> 1. runs link check and captures output as text
> 2. if fails, opens the issue with error text as body of the issue

@laysauchoa humbly didn't link to it, but we already have https://github.com/pyvista/pyvista/pull/3166 thanks to them :) this machinery could be upgraded to open the issue.

**Comment by banesullivan** [comment]
Ah, thanks for pointing that out @adeak, and thank you @laysauchoa for already implementing most of this!

**Comment by laysauchoa** [comment]
Opening the issue works fine but I tried to catch the output from previous steps to add to the body of the issue and does not work because the GitHub action that I use for the issue does not support such a long output. I am trying to find an alternative for that, but so far nothing worked.

**Comment by banesullivan** [comment]
Do you have a prototype of the code pushed somewhere? I'd be happy to help

**Comment by laysauchoa** [comment]
@banesullivan I did with another forked repo cause pyvista takes too long to run. I've the fork here and everything is in the main: https://github.com/laysauchoa/devportal-forked/actions

The main problem is writing the output into the issue body. Now, I am thinking if I need to use github cli or something. I've tried the following options for github action to create an issue:

https://github.com/marketplace/actions/create-an-issue
https://github.com/actions-ecosystem/action-create-issue

Let me know. Maybe I am just missing something.

**Comment by laysauchoa** [comment]
Hi @banesullivan I think it can be something like the PR I linked

**Comment by laysauchoa** [comment]
can this issue be eligible for the hacktoberfest? If yes, can we add the label for it? thanks!

**Comment by adeak** [comment]
> can this issue be eligible for the hacktoberfest? If yes, can we add the label for it? thanks!

My understanding is that PRs are what eligible, and approved, merged PRs are valid automatically. That being said, @tkoyama010 diligently labels our merged PRs for hacktoberfest :)

**Comment by tkoyama010** [comment]
I mistook this for a PR, it is an ISSUE.

**Comment by laysauchoa** [comment]
Alright, clear! Thanks for clarifying :)

**Comment by laysauchoa** [comment]
Can I assign this issue to me? I've an open pull request about it.

**Comment by adeak** [comment]
> Can I assign this issue to me? I've an open pull request about it.

I don't think you can, but I've assigned you now.

**Comment by tkoyama010** [comment]
This will be closed after a certain period of time. Thank you for your cooperation.
