### ISSUE TITLE
`pyvista` (`pythreejs` or `ipygany` backend) incompatible with `ipywidgets>7.7.2.`

### ISSUE THREAD

**Issue by jorgensd** [pyvista/pyvista#3274]
### Describe the bug, what's wrong, and what you expected.

The jupyter backend `pythreejs` does not work with the newest release if `ipywidgets`. No plot is produced

### Steps to reproduce the bug.

```docker
FROM ubuntu:22.04


WORKDIR /tmp/

# pyvista dependencies from apt
RUN apt-get -qq update && \
    apt-get -y install libxrender-dev libgl1-mesa-dev xvfb python3-pip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /var/tmp/*

# Install python dependencies
RUN pip3 install --upgrade pip 


# Install components from dolfinx/lab
RUN pip3 install pyvista pythreejs ipygany pyvista jupyterlab && \
    pip3 cache purge && \
    jupyter nbextension enable --py --sys-prefix ipygany


EXPOSE 8888/tcp

ENV SHELL /bin/bash
ENTRYPOINT ["jupyter", "lab", "--ip", "0.0.0.0", "--no-browser", "--allow-root"]

```

```python
import pyvista as pv

sphere = pv.Sphere(center=(1, 0, 0))
cube = pv.Cube()
pv.set_jupyter_backend("pythreejs")
pl = pv.Plotter()
pl.add_mesh(sphere, color='r')
pl.add_mesh(cube, color='b')
pl.show()
```
Downgrading `ipywidgets` resolves the issue.

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Tue Sep 06 11:23:32 2022 UTC

                OS : Linux
            CPU(s) : 8
           Machine : x86_64
      Architecture : 64bit
               RAM : 15.5 GiB
       Environment : Jupyter
       GPU Details : error

  Python 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0]

           pyvista : 0.36.1
               vtk : 9.2.0
             numpy : 1.23.2
           imageio : 2.21.2
           appdirs : 1.4.4
            scooby : 0.5.12
        matplotlib : 3.5.3
           IPython : 8.5.0
        jupyterlab : 3.4.6
         pythreejs : Version unknown
--------------------------------------------------------------------------------
```

### Screenshots

![ipywidgets](https://user-images.githubusercontent.com/8554300/188623720-1b90cb9f-099d-4c0f-bf01-c8d9ee7a7b9f.png)

**Comment by jorgensd** [comment]
Similar issue with `ipygany` as jupyter backend

**Comment by astroboylrx** [comment]
Thanks a lot for finding this! Experimenting with `pyvista` with `pythreejs/ipygany` but obtained zero plot at all regardless of Mac/Win/Linux and various browsers has been super frustrating for me in the past few days.

I did try `panel`. But the bug mentioned in holoviz/panel/issues/2429 has been halting me from using it (I'm trying to visualize some local data in `vtk` files).

Thanks again!

**Comment by banesullivan** [comment]
@pyvista/developers, we ought to try to uncover what's going wrong here... I've had a few colleagues use PyVista lately and run into this issue needing to downgrade `ipywidgets`. If we cannot track it down, should I pin/limit the version of ipywidgets in `ipyvtklink` directly?

**Comment by adeak** [comment]
> If we cannot track it down, should I pin/limit the version of ipywidgets in `ipyvtklink` directly?

I don't see a reason why we shouldn't do that. If the functionality flat-out doesn't work with that version then this is exactly the kind of incompatibility that we have version pins for.

**Comment by akaszynski** [comment]
Would it be better to raise this in https://github.com/jupyter-widgets/pythreejs? I'm guessing that the issue is actually with `pythreejs` and not `pyvista`.

@banesullivan, this really emphasises the need to have a solid jupyter widget from either Kitware or PyVista.

**Comment by akaszynski** [comment]
> But the bug mentioned in holoviz/panel/issues/2429 has been halting me from using it (I'm trying to visualize some local data in vtk files).

I bet there's a VTK object that doesn't support `GetPoints`. Can you create a minimum working example for them? I can't reproduce anything from the example.

**Comment by banesullivan** [comment]
I just pushed out `ipyvktlink==0.2.3` which pins `ipywidgets` to `~=7.7` to help mitigate these issues (at least for ipyvtklink)
