### ISSUE TITLE
VTK data type (vtkPointSet) is not currently supported by pyvista.

### ISSUE THREAD

**Issue by gbene** [pyvista/pyvista#3292]
### Describe the bug, what's wrong, and what you expected.

Hi!

When I create a vtkPointSet object I am unable to plot it using the pyvista.Plotter() even though PointSets are now ufficially supported. 
In fact when creating a pyvista.PointSet() instance and doing a ShallowCopy of the vtkPointSet everything runs as intended. 
Is this normal? 
I'd rather not use the ShallowCopy route since in my case the vtk objects are modified and I'd prefer to use one instance of the data without copying It every time I need to plot the results. 

Have a nice weekend!

### Steps to reproduce the bug.

```python
import pyvista as pv
import vtk 

plotter = pv.Plotter()

pc = some_VTK_FLOAT_data

points = vtk.vtkPoints()

points.SetData(pc)

vtk_ps = vtk.vtkPointSet()
vtk_ps.SetPoints(points)
vtk_ps.Modified()

plotter.add_points(vtk_ps)
```
returns
> WARNING:root:VTK data type (vtkPointSet) is not currently supported by pyvista.

but when doing:

```python
pv_ps = pv.PointSet()
pv_ps.ShallowCopy(vtk_ps)
plotter.add_points(pv_ps)
```
Everything runs fine

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Fri Sep 09 18:10:06 2022 CEST

                OS : Linux
            CPU(s) : 8
           Machine : x86_64
      Architecture : 64bit
               RAM : 15.5 GiB
       Environment : Python
       File system : ext4
        GPU Vendor : NVIDIA Corporation
      GPU Renderer : NVIDIA GeForce GTX 1050/PCIe/SSE2
       GPU Version : 4.5.0 NVIDIA 515.48.07

  Python 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:56:21)
  [GCC 10.3.0]

           pyvista : 0.34.0
               vtk : 9.1.0
             numpy : 1.22.3
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.12
        matplotlib : 3.5.2
         pyvistaqt : 0.9.0
             PyQt5 : 5.12.3
           IPython : 8.1.1
          colorcet : 3.0.0
           cmocean : 2.0
             scipy : 1.8.1
              tqdm : 4.64.0
--------------------------------------------------------------------------------
```

**Comment by akaszynski** [comment]
We should add this. Should be an easy PR.

**Comment by banesullivan** [comment]
Does add mesh not fallback to `pv.wrap()`? I'm curious where this warning is coming from

**Comment by MatthewFlamm** [comment]
It looks like PointSet wasn't added to list of wrappable vtk objects:

https://github.com/pyvista/pyvista/blob/4b3eaffb7c975f929503a2170f1e01c34670bed8/pyvista/utilities/wrappers.py#L25-L36

**Comment by banesullivan** [comment]
Then this should be a 1 line fix

**Comment by gbene** [comment]
I applied locally the fix by adding to the wrappers.py file the line:
```python
'vtkPointSet': pyvista.PointSet,
```
When running the code to plot vtkPointSet the following error occurs:

>  path/to//lib/python3.9/site-packages/pyvista/utilities/helpers.py", line 471, in vtk_points
    raise TypeError('Points must be a numeric type')
   TypeError: Points must be a numeric type

**Comment by banesullivan** [comment]
Huh, maybe this isn't as straightforward... we will investigate and get a fix out soon!

**Comment by MatthewFlamm** [comment]
These are very informative reports @gbene.  `pyvista.PointSet` also currently doesn't support being directly initialized with a `vtkPointSet` object.  It only currently supports a numpy ndarray like object, which isn't consistent with the rest of the API here.  I _think_ that after this is added, it should work.

https://github.com/pyvista/pyvista/blob/7d65054dff4717338519e73d287c7709caef1b20/pyvista/core/pointset.py#L406-L410
