### ISSUE TITLE
Cell Picking Enabled Only for Last Actor Added to Plotter

### ISSUE THREAD

**Issue by adam-grant-hendry** [pyvista/pyvista#3317]
### Describe the bug, what's wrong, and what you expected.

Following the [Enable Cell Picking Example](https://docs.pyvista.org/api/plotting/_autosummary/pyvista.Plotter.enable_cell_picking.html?highlight=cell+picking#pyvista.Plotter.enable_cell_picking), I found only the last actor added to the plotter is enabled for cell picking, with or without `pickable=True`).

This smells of #3180 ...

### Steps to reproduce the bug.

```python
import pyvista as pv

mesh = pv.Sphere(center=(1, 0, 0))
cube = pv.Cube()
p = pv.Plotter()

p.add_mesh(mesh, pickable=True)
p.add_mesh(cube, pickable=True)  # Only this actor is pickable
p.enable_cell_picking(color='blue')

p.show()
```

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Tue Sep 13 19:49:34 2022 Pacific Daylight Time

                OS : Windows
            CPU(s) : 96
           Machine : AMD64
      Architecture : 64bit
               RAM : 190.7 GiB
       Environment : Python
        GPU Vendor : NVIDIA Corporation
      GPU Renderer : Quadro RTX 8000/PCIe/SSE2
       GPU Version : 4.5.0 NVIDIA 516.40

  Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64
  bit (AMD64)]

           pyvista : 0.37.dev0
               vtk : 9.1.0
             numpy : 1.23.3
           imageio : 2.21.2
           appdirs : 1.4.4
            scooby : 0.5.12
        matplotlib : 3.5.3
         pyvistaqt : 0.9.0
           IPython : 8.5.0
              tqdm : 4.64.1
            meshio : 5.3.4
--------------------------------------------------------------------------------
```

### Screenshots

![CellPickingBug](https://user-images.githubusercontent.com/59346180/190048010-e4b356ed-7a46-4d56-87cb-11801c761e5c.gif)

**Comment by banesullivan** [comment]
Hm. I haven't verified this but if so, this is a regression we can fix

**Comment by banesullivan** [comment]
I want to confirm that this is indeed a regression and at odds with the documentation for the method:

https://github.com/pyvista/pyvista/blob/20cd0177ef9d924d3497e397ac45f6069f48c6cd/pyvista/plotting/picking.py#L244-L251

I think the best bet here is to git bisect to see where the regression was introduced.

Further, I'd like for us to implement a test of picking multiple meshes in a scene after we figure this out

**Comment by banesullivan** [comment]
Able to reproduce and can confirm that this is only an issue for "through" picking (`through=True`, the default). 

Inside `enable_cell_picking`, you can see the difference in implementations where the visible cell picking uses the selection nodes to determine the input mesh and the through picking uses the last `mesh` object. 

These two methods need to converge.

@adam-grant-hendry, I'm happy to take on this issue or work with you if you want to tackle it

**Comment by adam-grant-hendry** [comment]
@banesullivan Feel free to take this on! I will contribute where I can. Thank you for looking into this!
