### ISSUE TITLE
UniformGrid -> ImageData

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#3320]
A long, long time ago, I made the decision (ref #24) to call PyVista's wrapping of `vtkImageData` `UniformGrid` -- this decision made a lot of sense at the time and was intuitive to me, my colleagues, and the users of PyVista at the time. Unfortunately, this is at odds with the `vtkUniformGrid` class. Further, PyVista is seeing massive growth lately and more adoption from the VTK community, and I am hoping to bring VTK and PyVista closer together. In doing so, I would like to propose that PyVista move more towards VTK class names in its wrappings (this is only an issue for the wrapping of `vtkImageData`).

This will also add consistency to PyVista's core API as every other wrapped VTK class is the same name just without the `vtk` prefix

Related to #3313

I would like to use this issue as a place to develop a transition plan for renaming `pyvista.UniformGrid` to `pyvista.ImageData` with the intention of later wrapping `vtkUniformGrid` and `vtkStructuredPoints` in PyVista as well.

<img width="369" alt="Screen Shot 2022-09-13 at 9 25 56 PM" src="https://user-images.githubusercontent.com/22067021/190052761-40ab9548-cb54-400a-80b5-2878876cc3d0.png">

This ***will not*** be an easy feat as `pyvista.UniformGrid` is used ***all over the place*** and we need to come up with a thoughtful transition/deprecation plan. My initial thoughts on how this will play out:

Phase 1: Rename and issue a deprecation warning

1. Rename `pyvista.UniformGrid` to `pyvista.ImageData`, wrap the new class as a shell `UniformGrid` class and issue a Deprecation warning in its `__init__`
2. Update all internal examples and documentation to use the new `pyvista.ImageData` class
3. Issue a release and let the chaos ensue

Phase 2: Raise an error, but keep `pyvista.UniformGrid` around.

1. Increase the severity or importance of the Deprecation notice. This could be done through a harsher warning of sorts that can't just be ignored or by outright raising a runtime error. This would be much like what we did for the PyVistaQt `BackgroundPlotter` when migrating it out.

Phase 3: Full deprecation and removal

1. at this point, we may be able to introduce a wrapping of `vtkUniformGrid` as `pyvista.UniformGrid` if the community requests it. However, we should delay wrapping this class as long as possible to avoid issues in the transition

**Comment by adam-grant-hendry** [comment]
Love the effort going into this! I definitely want dibs on helping with the impacts to volume rendering on this 😉
