### ISSUE TITLE
Consider implement a pyvista.testing module

### ISSUE THREAD

**Issue by jorgepiloto** [pyvista/pyvista#3324]
🐞 **Problem description**
For libraries depending on PyVista, it would be interesting to have some utility for validating PyVista figures. This would allow to maintain or even increase code coverage on these libraries.

📝 **Background**
So far, PyVista validates its `Plotter` class through the [verify_cache_image](https://github.com/pyvista/pyvista/blob/6aedb562ee8aeebba90fe163b757bd6a355b40a0/tests/plotting/test_plotting.py#L167), which is defined in [tests/plotting/test_plotting.py](https://github.com/pyvista/pyvista/blob/main/tests/plotting/test_plotting.py#L167).

Previous function is passed as a parameter to the `Plotter.plot(before_close_callback=verify_cache_image)` method that looks into the "image_cache/" directory. The `verify_cache_image` looks into the `image_cache/` directory and looks for the associated expected image from the test name.

However, the main issue is that the `verify_cache_image` with all its dependencies are not exposed in PyVista: they are specified in the `tests/` directory. This blocks libraries using PyVista from accessing this useful testing routine.

💡 **Proposed solutions**
Looking at other popular libraries in the Python ecosystem, most of them ship with a `testing` module so all the testing auxiliary routines can be reused:

- Matplotlib testing: https://github.com/matplotlib/matplotlib/tree/main/lib/matplotlib/testing
- NumPy testing: https://github.com/numpy/numpy/tree/main/numpy/testing
- Pandas testing: https://github.com/pandas-dev/pandas/blob/main/pandas/testing.py

This way, third libraries could run:

```
from pyvista.testing import verify_image_cache
```

and use all its functionality in their own test suite.

Additional solutions may include creating a Pytest plugin for comparing PyVista figures, see [pytest-mpl](https://github.com/matplotlib/pytest-mpl), a plugin for testing matplotlib figures.

**Comment by MatthewFlamm** [comment]
I like this idea.  I want to take your suggestion one step further on `verify_cache_image` that it should be a Pytest plugin itself.  Then downstream libs do not even need to import it and could consider wrapping it to make an `autouse=True` fixture.  A start for this is in #3454, which makes this functionality into an internal Pytest fixture.
