### ISSUE TITLE
Add tests for `vtk_points`

### ISSUE THREAD

**Issue by MatthewFlamm** [pyvista/pyvista#3333]
`pyvista.vtk_points` doesn't have unit tests.  #3311 adds some tests, but there is more functionality to test more fully, including `force_float`.

> I noticed that `vtk_points` doesn't have any direct tests.  I added relevant tests for the functionality being tested here for my own sanity.  I can open an issue to fully flesh out the tests.

_Originally posted by @MatthewFlamm in https://github.com/pyvista/pyvista/issues/3311#issuecomment-1248276490_

**Comment by sgaist** [comment]
Hi,

I would like to take a shot at it for the Hacktober fest.

**Comment by MatthewFlamm** [comment]
Take a shot and please ask questions either here or in the slack channel if you need pointers.

**Comment by banesullivan** [comment]
@sgaist, happy hactober fest!!! (well in a few days) We're happy to have your contributions! When making your PR, please remind us to add the `hacktoberfest-accepted` label to your PR to make sure you get credit for your work

**Comment by sgaist** [comment]
My merge request is currently just a starting point.

One of the question I have is whether the tests should cover only the PointSet class or through them the _PointSet mixin as well ?

**Comment by MatthewFlamm** [comment]
This issue was specifically for `vtk_points`, which is used in that module.  If you want to open more PRs to add more test coverage for PointSet and _PointSet that would be great!

**Comment by sgaist** [comment]
My bad ! I misread the content of #3311 and mixed things up.

I'll cleanup my current request to match the scope of this issue and see what I can do for PointSet.
