### ISSUE TITLE
pythreejs backend not showing grid in jupyterlab

### ISSUE THREAD

**Issue by panziyi1** [pyvista/pyvista#3348]
### Describe the bug, what's wrong, and what you expected.

**Problem description:** I am trying to plot a cube along with grid and axes in jupyterlab, with pythreejs backend. The cube and axes were successfully plotted while grid plotting failed.

### Steps to reproduce the bug.

Just run the following code in jupyterlab.
```
import pyvista
import os
mesh = pyvista.Cube()
plotter = pyvista.Plotter()    # instantiate the plotter
plotter.add_mesh(mesh, opacity=0.3)    # add a mesh to the scene
plotter.show_axes()
plotter.show_grid()
plotter.show()            # show the rendering window
```

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Wed Sep 21 16:59:34 2022 CST

                OS : Linux
            CPU(s) : 8
           Machine : x86_64
      Architecture : 64bit
               RAM : 15.4 GiB
       Environment : Jupyter
       File system : ext4
        GPU Vendor : Intel
      GPU Renderer : Mesa Intel(R) Xe Graphics (TGL GT2)
       GPU Version : 4.6 (Core Profile) Mesa 21.2.6

  Python 3.10.4 (main, Mar 31 2022, 08:41:55) [GCC 7.5.0]

           pyvista : 0.36.1
               vtk : 9.2.0
             numpy : 1.23.2
           imageio : 2.21.1
           appdirs : 1.4.4
            scooby : 0.5.12
        matplotlib : 3.5.3
         pyvistaqt : 0.9.0
             PyQt5 : 5.15.7
           IPython : 8.4.0
        ipyvtklink : 0.2.2
              tqdm : 4.64.1
        jupyterlab : 3.4.4
         pythreejs : Version unknown
--------------------------------------------------------------------------------
```

### Screenshots

![1663750657(1)](https://user-images.githubusercontent.com/107454683/191461682-6c883ec9-cac8-4530-bdc7-fc343b48a509.png)

**Comment by banesullivan** [comment]
`pythreejs` cannot plot the axes grids - it's simply not a capability of that library or threejs AFAIK without a bit of custom logic

**Comment by banesullivan** [comment]
I added the `wontfix` label here because we do not plan to continue supporting the `pythreejs` notebook rendering backend moving forward. We are still working on a plan and building a new notebook rendering backend that will be more feature rich and will leverage VTK.js for client-side rendering.

**Comment by panziyi1** [comment]
Thanks, that's rather clear.  Problem solved so I just close this one.
