### ISSUE TITLE
parallel projection (2D rendering)

### ISSUE THREAD

**Issue by laserman781** [pyvista/pyvista#337]
Can I view the 2D plane as a parallel projection? I know this can be done in paraview so I assume it can also be done in pyvista.

**Comment by banesullivan** [comment]
This isn't currently implemented, but we can put it on the todo list!

**Comment by banesullivan** [comment]
@laserman781 - there is actually a pretty simple solution to this which I am about to implement. All you need to do is call `.SetParallelProjection(True)` on the active camera:

```py
import pyvista as pv
from pyvista import examples
mesh = examples.download_st_helens().warp_by_scalar()

p = pv.Plotter(notebook=False)
p.add_mesh(mesh)
p.camera_position = 'xy'
p.camera.SetParallelProjection(True)
p.show()
```

I just implemented some helper methods to make this easier and also be able to toggle it with the `BackgroundPlotter` in e7ec9f0. The new methods are `enable_parallel_projection()` and `disable_parallel_projection()` which can be called from any plotter:

```py
p = pv.Plotter(notebook=False)
p.add_mesh(mesh)
p.enable_parallel_projection()
p.show()
```

Or better yet, check out the menus in the `BackgroundPlotter`:

```py
p = pv.BackgroundPlotter()
p.add_mesh(mesh)
p.show()
```

![2019-08-02 10 07 38](https://user-images.githubusercontent.com/22067021/62383629-68dc9680-b50d-11e9-8087-b0b6880ce744.gif)

**Comment by banesullivan** [comment]
Also, you might be interested in the `enable_image_style()` function on the plotters which makes thee rendering truly 2D with parallel projection:

```py
import pyvista as pv
from pyvista import examples

# This is a 2D image on the XY plane
mesh = examples.download_st_helens()

p = pv.Plotter(notebook=False)
p.add_mesh(mesh)
p.enable_parallel_projection()
p.enable_image_style()
p.view_xy()
p.show()
```
