### ISSUE TITLE
Plotter should redraw chartMPL instances if axes is modified with set_xxxx

### ISSUE THREAD

**Issue by Gustafferson** [pyvista/pyvista#3380]
### Describe the feature you would like to be added.

In the [chart overlays](https://docs.pyvista.org/examples/02-plot/chart_overlays.html#sphx-glr-examples-02-plot-chart-overlays-py) tutorial, it is shown how to draw standard and chartMPL charts side by side and update them with a `p.add_slider_widget` that is referred to by a user defined function:
```python
# Method and slider to update all visuals based on the time selection
def update_time(time):
    k = np.count_nonzero(t < time)
    h_line.set_xdata(t[: k + 1])
    h_line.set_ydata(h[: k + 1])
    v_line.update(t[: k + 1], v[: k + 1])
    p.add_mesh(pv.Sphere(1, center=(0, 0, h[k])), name="sphere", render=False)
    p.update()


time_slider = p.add_slider_widget(
    update_time, [np.min(t), np.max(t)], 0, "Time", (0.25, 0.9), (0.75, 0.9), event_type='always'
)

# Start incrementing time automatically
for i in range(1, 50):
    ax.set_xlim([0, t[i]])
    time_slider.GetSliderRepresentation().SetValue(t[i])
    update_time(t[i])

```

I think this works as a [chartMPL._redraw](https://docs.pyvista.org/_modules/pyvista/plotting/charts.html#ChartMPL) event is detected when the SliderRepresentation is updated.

When modifying plotted data outside of Widget use --- for example if animating a series of data alongside a mesh object --- with one of matplotlib's `set_xxxx` type functions to modify collections, this update does not occur and the chart is not redrawn, leaving animations not updating. 

Minimum working example:
```python
from time import sleep
import pyvista as pv #meshing
import numpy as np #data
from matplotlib import pyplot as plt #plotting


x_data = np.random.rand(20,1)*100
y_data = np.random.rand(20,1)*100

fig,ax=plt.subplots()
scat = ax.scatter(x=[],y=[])

ax.set_ylim([0, 100])
ax.set_xlim([0, 100])
cb=plt.colorbar(scat,ax=ax)

p = pv.Plotter(shape=(2, 1),window_size=([1200, 800]))
p.show(auto_close=False,interactive=False,interactive_update=True)
#add mesh
sphere = pv.Sphere()
sphere.cell_data["data"] = np.random.random(sphere.n_cells)
p.add_mesh(sphere, scalars="data", clim=[0, 1])

#add chart
p.subplot(1,0)
chart = pv.ChartMPL(fig, size=(0.8, 0.8), loc=(0.1, 0.1))
p.add_chart(chart)

for idx,r in enumerate(x_data):
    p.subplot(1,0)
    scat.set_offsets( np.column_stack(   (x_data[0:idx],y_data[0:idx])  ) )
    
    p.subplot(0,0)
    sphere.cell_data["data"] = np.random.random(sphere.n_cells)

    p.update()
    sleep(1)

```

Here, the plotter will appear but no data in the chart is shown.

Add the hidden `chart._redraw()` function below the set_offsets call:
```python

for idx,r in enumerate(x_data):
    p.subplot(1,0)
    scat.set_offsets( np.column_stack(   (x_data[0:idx],y_data[0:idx])  ) )
    chart._redraw()

    p.subplot(0,0)
    sphere.cell_data["data"] = np.random.random(sphere.n_cells)

    p.update()
    sleep(1)


```

The plotter now appears and the chartMPL object is animated.

## Solutions
This is a fairly expected use case of the chartMPL functionality in my opinion, allowing for much greater control of animated charts than the core PyVista chart capability. It took me a very long time trying to debug and hunting through the source to find the missing `chart._redraw()` call. 
So to that end, either:

1. The chartMPL object is redrawn when p.update is called (this seems most intuitive to me)
2. The chartMPL detection for a draw event is extended to the `set_xxxx` functions from mpl (might be hard to do as I don't think `set_xxxx` functions are an mpl_connect event)
3. At least mention the need for manually using `chart._redraw()` in one of the tutorials or a new tutorial based on this above MWE.

Thanks!

**Comment by dcbr** [comment]
Thanks for your extensive analysis! The ChartMPL's are redrawn whenever the underlying matplotlib figure is redrawn (using `fig.canvas.redraw()`), so there is no need to use the `_redraw` method manually. But I agree that the documentation should be improved in this regard and I quite like your suggestion of automatically redrawing ChartMPL's whenever the plotter's `update` method is called. We should however prevent the `_redraw` method from being called too readily (see #2932), so I would make this "auto redraw" behavior optional and opt-in. I'll try to setup a PR for this functionality later today!
