### ISSUE TITLE
add_axes and create_axes_marker problems

### ISSUE THREAD

**Issue by MatthewFlamm** [pyvista/pyvista#3389]
`pyvista.Plotter.add_axes` allows passing a `marker_args` which allows to pass parameters to `pyvista.create_axes_marker`.  There are a few issues currently:

1) `create_axes_marker` isn't included in the documentation
2)  `marker_args` cannot contain parameters that are already allowed in `add_axes`, e.g. `add_axes(marker_args={'line_width': 6})` is not allowed.

I propose the the following items to address these problems:

- [ ] add `create_axes_marker` to documentation
- [ ] allow `**kwargs` in `add_axes` and deprecate `marker_args`.  Pass `kwargs` to `create_axes_marker`.

**Comment by Abhijnan-Bajpai** [comment]
Hey @MatthewFlamm! I'd like to work on this for my Hacktoberfest contributions. Could I be assigned?

**Comment by MatthewFlamm** [comment]
Yes, thank you!  Please ask questions if you need help at any point.

**Comment by banesullivan** [comment]
And please don't let us forget to add the `hactoberfest-accepted` tag to your PRs! Happy to have you contributing, @Abhijnan-Bajpai

**Comment by MatthewFlamm** [comment]
There is no hard requirement on branch name as we can tag appropriately after the PR is opened.  You should open the PR from a branch on your fork of pyvista to the main branch of pyvista.  If you want to follow PyVista branch naming convention, you can read here: https://docs.pyvista.org/extras/developer_notes.html#branch-naming-conventions
