### ISSUE TITLE
sample_over_line has trouble reading mesh values

### ISSUE THREAD

**Issue by GeoMattB** [pyvista/pyvista#3426]
### Describe the bug, what's wrong, and what you expected.

I create or load a triangular mesh surface.
Then using the example from plot_over_line I generate a line, then show that line on the surface. This works.

I then sample the line over the surface using sample_over_line and the resulting object has 0's for the attribute data

### Steps to reproduce the bug.

```python
import matplotlib.pyplot as plt
import pyvista as pv

cloud2=pv.read('test_mesh.vtk')
a = [cloud2.center[0]-100000, cloud2.bounds[2], cloud2.bounds[5]]
b = [cloud2.center[0]-100000, cloud2.bounds[3], cloud2.bounds[5]]

# Preview how this line intersects this mesh
line = pv.Line(a, b)

p = pv.Plotter()
p.add_mesh(cloud2)
p.add_mesh(line, color="white", line_width=5)
p.add_point_labels([a, b], ["A", "B"], font_size=48, point_color="red", text_color="red")
p.show()

sampleline=cloud2.sample_over_line(a,b,tolerance=5000,resolution=499)
x=sampleline['Distance']
y=sampleline['Elevation']
plt.ylim(-200,800)
plt.plot(x,y)

## plot over line code
cloud2.plot_over_line(
    a,
    b,
    tolerance=500,
    resolution=400,
    title="Elevation Profile",
    figsize=(10, 5),
    
)

### System Information

```shell
Date: Fri Oct 07 06:30:19 2022 UTC

                OS : Linux
            CPU(s) : 24
           Machine : x86_64
      Architecture : 64bit
               RAM : 54.9 GiB
       Environment : Jupyter
        GPU Vendor : Mesa/X.org
      GPU Renderer : llvmpipe (LLVM 11.0.1, 256 bits)
       GPU Version : 4.5 (Core Profile) Mesa 20.3.5

  Python 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]

           pyvista : 0.36.1
               vtk : 9.2.2
             numpy : 1.21.3
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.12
        matplotlib : 3.4.3
           IPython : 7.28.0
           cmocean : 2.0
             scipy : 1.7.1
              tqdm : 4.62.3
            meshio : 5.0.2
--------------------------------------------------------------------------------
```

### Screenshots

![image](https://user-images.githubusercontent.com/29564171/194482538-a9e9969e-282d-4125-b1ea-aafa3ad3b128.png)

**Comment by MatthewFlamm** [comment]
Can you also provide the working example with `plot_over_line`?  It is curious as it uses `sample_over_line` under the hood.

If you could provide the data, we could test directly. I'm interested in the bounds of your mesh, if you could provide that.

I suspect based on the large tolerance that your mesh doesn't exactly fall along this line.  The large tolerance might have unintended consequences like finding the first point within the tolerance.  It would be better to use a better line or reorient the mesh position sightly.

**Comment by GeoMattB** [comment]
[test_mesh.zip](https://github.com/pyvista/pyvista/files/9737817/test_mesh.zip)

I've attached the vtk file (zipped) here, and editted the original bug to include the plot_over_line code.

**Comment by MatthewFlamm** [comment]
> The nodes/points in the mesh are ~2000m apart with only a couple of hundred meters of elevation difference, there are places on the mesh where the values dip into negative.

I haven't had a chance to look at the data yet, but thank you for providing.  It sounds like based on your description that your mesh does not lie on a plane, but has variation in z.  This _will_ cause problems.  Using tolerance to fix this will cause issues unless the 'out-of-plane' variation is much much smaller than the cell sizes.  Since you loop over multiple meshes, this will be difficult to generalize.  There are probably multiple workarounds here.  One is to project your mesh to the xy plane, i.e. set z=0.  Then these functions should work well.  Another is to do a ray trace in the z-direction for multiple points along a line towards the existing mesh.

**Comment by GeoMattB** [comment]
Great, thanks for the detailed response. It looks like setting z=0 works as you describe. It looks like this is expected behaviour so I'll close this. Thanks again.
