### ISSUE TITLE
Add Reader utility for Ansys .cdb meshes

### ISSUE THREAD

**Issue by EntPyle** [pyvista/pyvista#3440]
### Describe the feature you would like to be added.

I would like to add the ability to read in meshes from Ansys .cdb files. I currently plan on doing this myself but wanted to add the feature request to make sure it wasn't already being worked on somewhere I couldn't find. 

### Links to VTK Documentation, Examples, or Class Definitions.

Link to the [file specification](https://knowledge.autodesk.com/search-result/caas/CloudHelp/cloudhelp/2017/ENU/SimMech-UsersGuide/files/GUID-E7A29D11-250D-47E2-871D-15F406EA80C0-htm.html ) I've found.

### Pseudocode or Screenshots

```python
filename = 'ansys_exported_mesh.cdb'
reader = pyvista.get_reader(filename)
mesh = reader.read()
```

**Comment by banesullivan** [comment]
I think this would be an excellent thing to implement and want to make sure @akaszynski is in the loop.

I think the best place for such a file reader would by in [one of the PyAnsys libraries](https://github.com/pyansys) which have excellent interoperability with PyVista. Perhaps if available in PyAnsys, we could implement a plugin mechanism for a downstream library to register new file readers (this actually shouldn't be too tough with what's currently implemented)

**Comment by EntPyle** [comment]
Did you have a thought as to where it should belong? I'll say that I'm not an Ansys user myself; I'm just partnering with someone who has Ansys and provided me mesh files in .cdb format. Looking through those modules, most of them seem to work in tandem with Ansys. The "independent" modules I see are focused on postprocessing, while the cdb format is specifically preprocessed data. It contains only a mesh with no material properties and no results. 

My project is actually a preprocessing step to assign element specific material properties (for a femoral bone). Is there a PyAnsys-Pre package that I'm missing?

**Comment by banesullivan** [comment]
I've pinged @akaszynski and will let him chime in as the creator of PyAnsys

**Comment by akaszynski** [comment]
Hi @EntPyle,

https://github.com/pyansys/pymapdl-reader should work for you. See https://reader.docs.pyansys.com/api/archive.html

```py
>>> from ansys.mapdl import reader as pymapdl_reader
>>> from ansys.mapdl.reader import examples
>>> hex_beam = pymapdl_reader.Archive(examples.hexarchivefile)
print(hex_beam)
ANSYS Archive File HexBeam.cdb
  Number of Nodes:              40
  Number of Elements:           321
  Number of Element Types:      1
  Number of Node Components:    2
  Number of Element Components: 2
```

**Comment by akaszynski** [comment]
If you'd like to access the [UnstructuredGrid](https://docs.pyvista.org/api/core/_autosummary/pyvista.UnstructuredGrid.html?highlight=unstructured+grid#pyvista.UnstructuredGrid) of the CDB, access the `grid` attribute:

```py
>>> from ansys.mapdl import reader as pymapdl_reader
>>> from ansys.mapdl.reader import examples
>>> archive = pymapdl_reader.Archive(examples.hexarchivefile)
archive.grid
UnstructuredGrid (0x7ffa237f08a0)
  N Cells:      40
  N Points:     321
  X Bounds:     0.000e+00, 1.000e+00
  Y Bounds:     0.000e+00, 1.000e+00
  Z Bounds:     0.000e+00, 5.000e+00
  N Arrays:     13
```
