### ISSUE TITLE
Opacity for NaN-values does not work when adding mesh

### ISSUE THREAD

**Issue by georg-walther** [pyvista/pyvista#3445]
Dear PyVista-Team,
Dear PyVista-Community,

When creating a mesh from a UniformGrid with some NaN-values, it is not possible to hide those NaNs (opacity=0).
When setting the parameter nan_opacity to 0, the NaNs appear in grey (see screenshot [1]). When setting nan_opacity to 1 (or 0) and nan_color='black' (can be any color) the NaNs are finally hidden in the plot but the opacity of the remaining values also changed (somewhere below 1 - see screenshot [2]). When using this paradoxical workaround for my actual project (same data range), the NaNs in the volume got nearly invisible but the non-NaNs (which I actually want to show) totally diappeared (see screenshot [3]).

### Steps to reproduce the bug.

NaNs are grey:
```
import pyvista as pv
import numpy as np

noise = pv.perlin_noise(0.1, (1, 1, 1), (0, 0, 0))
grid = pv.sample_function(noise, [0, 1.0, -0, 1.0, 0, 1.0], dim=(20, 20, 20))

minV = min(grid['scalars'])
maxV = max(grid['scalars'])
grid['scalars'] = (grid['scalars'] - minV) / (maxV - minV)
grid['scalars'] *= 100

grid['scalars'] = np.where(grid['scalars'] < 20, np.nan, grid['scalars'])
p = pv.Plotter()

print(grid.get_data_range())
p.add_mesh(grid, nan_opacity=0)
p.show(window_size=[500, 500])
```

NaNs are invisible but the remaining values have a low opacity:
```
import pyvista as pv
import numpy as np

noise = pv.perlin_noise(0.1, (1, 1, 1), (0, 0, 0))
grid = pv.sample_function(noise, [0, 1.0, -0, 1.0, 0, 1.0], dim=(20, 20, 20))

minV = min(grid['scalars'])
maxV = max(grid['scalars'])
grid['scalars'] = (grid['scalars'] - minV) / (maxV - minV)
grid['scalars'] *= 100

grid['scalars'] = np.where(grid['scalars'] < 20, np.nan, grid['scalars'])
p = pv.Plotter()

print(grid.get_data_range())
p.add_mesh(grid, nan_color='black', nan_opacity=1)
p.show(window_size=[500, 500])
```

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Tue Oct 11 15:04:01 2022 CEST

                OS : Linux
            CPU(s) : 16
           Machine : x86_64
      Architecture : 64bit
               RAM : 62.5 GiB
       Environment : Python
       File system : ext4
        GPU Vendor : Intel
      GPU Renderer : Mesa Intel(R) UHD Graphics (TGL GT1)
       GPU Version : 4.6 (Core Profile) Mesa 21.2.6

  Python 3.7.6 (default, Jan  8 2020, 19:59:22)  [GCC 7.3.0]

           pyvista : 0.36.1
               vtk : 9.1.0
             numpy : 1.18.4
           imageio : 2.6.1
           appdirs : 1.4.4
            scooby : 0.5.12
        matplotlib : 3.2.1
             PyQt5 : 5.9.2
           IPython : 7.12.0
             scipy : 1.4.1
              tqdm : 4.46.0
        jupyterlab : 1.2.6

  Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for
  Intel(R) 64 architecture applications
--------------------------------------------------------------------------------
```

### Screenshots

Screenshot [1]:
![nan_opacity=0](https://user-images.githubusercontent.com/62775496/195098570-b309aafb-f26f-40c6-8f6d-e425bd797302.png)

Screenshot [2]:
![pyvista bug](https://user-images.githubusercontent.com/62775496/195098524-05a4909f-1acd-4a4f-88b7-0b2442563f37.png)

Screenshot [3]:
![nearly invisible](https://user-images.githubusercontent.com/62775496/195100571-b1a69cb3-3427-466b-928d-288dbc1412a4.png)

**Comment by banesullivan** [comment]
+1 just noticed this as well. This is a regression introduced by #2175 (found via git bisect):

```
c7303f207d7b5e5c6ba630b1748dc6276dffea78 is the first bad commit
commit c7303f207d7b5e5c6ba630b1748dc6276dffea78
Author: dcbr <15089458+dcbr@users.noreply.github.com>
Date:   Thu Mar 3 09:07:29 2022 +0100

    Unified Color class and color_like type. (#2175)
```

with this script:

```py
import pyvista as pv
import numpy as np
from pyvista import examples

mesh = examples.load_uniform()
mesh['Spatial Point Data'][:55] = np.nan

p = pv.Plotter(notebook=0)
p.add_mesh(mesh, nan_opacity=0)
p.show()
```


The following diff appears to resolve the issue, but I'd like to consult @dcbr on the difference between `opacity` and `default_opacity` for the `Color` class:

```diff
diff --git a/pyvista/plotting/_plotting.py b/pyvista/plotting/_plotting.py
index 50f5ad9b..c6cec190 100644
--- a/pyvista/plotting/_plotting.py
+++ b/pyvista/plotting/_plotting.py
@@ -252,7 +252,7 @@ def _common_arg_parser(
         # check if this actor already exists
         remove_existing_actor = True

-    nan_color = Color(nan_color, default_opacity=nan_opacity, default_color=theme.nan_color)
+    nan_color = Color(nan_color, opacity=nan_opacity, default_color=theme.nan_color)

     if color is True:
         color = theme.color
```

**Comment by dcbr** [comment]
- `default_opacity` was meant to be a last resort fallback value for the opacity of the color, i.e. it is only used when the provided `color` (or `default_color` if `color` is not provided) has no alpha channel value and the provided `opacity` is `None`.

- `opacity` on the other hand is meant as an override, i.e. it is always used (except if it's `None`) even when the provided `color` (or `default_color` if `color` is not provided) has an alpha channel value.

So I believe for this use case (`add_mesh`) the usage of `opacity` is correct. You want to override any alpha values of the provided (or theme) `nan_color`.

**Comment by banesullivan** [comment]
@georg-walther, on your note of:

> NaNs are invisible but the remaining values have a low opacity:

enabling depth peeling on the plotter should fix that:

```py
p = pv.Plotter()
p.add_mesh(grid, nan_opacity=0)
p.enable_depth_peeling()
p.show()
```
