### ISSUE TITLE
Colormap not rendering correctly in VTKjs

### ISSUE THREAD

**Issue by pinshuai** [pyvista/pyvista#345]
I downloaded the example notebook from https://docs.pyvista.org/examples/02-plot/cmap.html?highlight=cmap, but I could not get the colormap to show up. I have matplotlib installed and imported.

This is what I got for the first plot in the example. The second plot also showed one solid color instead of "viridis" cmap.

<img width="522" alt="Screenshot 2019-08-01 10 12 05" src="https://user-images.githubusercontent.com/34693887/62313156-e5f00900-b444-11e9-8da1-136dd0060ce2.png">

**Comment by banesullivan** [comment]
Could you please share your system info by running the following in that same notebook:

```py
import pyvista as pv
print(pv.Report('panel'))
```

**Comment by banesullivan** [comment]
I suspect you're using the notebook rendering - which is still somewhat of a prototype.

When you instantiate the `Plotter` or call `.plot()` on a mesh, can you pass `notebook=False` and let me know if the issue persists?

**Comment by pinshuai** [comment]
When I pass `notebook=False`, a new window popped up with the correct color rendering. 

Then I tried Jupyterhub on a remote server, the kernel died. Do you have a solution for that?
```
--------------------------------------------------------------------------------
  Date: Thu Aug 01 12:32:59 2019 PDT

             Linux : OS
                64 : CPU(s)
            x86_64 : Machine
             64bit : Architecture
          503.1 GB : RAM
           Jupyter : Environment

  Python 3.6.7 | packaged by conda-forge | (default, Jul  2 2019, 02:18:42)
  [GCC 7.3.0]

             0.6.0 : panel
            0.21.1 : pyvista
             8.2.0 : vtk
            1.15.4 : numpy
             2.5.0 : imageio
             1.4.3 : appdirs
             0.4.3 : scooby
             2.2.2 : matplotlib
             5.9.2 : PyQt5
             7.0.1 : IPython
             7.4.2 : ipywidgets

  Intel(R) Math Kernel Library Version 2018.0.3 Product Build 20180406 for
  Intel(R) 64 architecture applications
--------------------------------------------------------------------------------
```

**Comment by banesullivan** [comment]
This is a `panel` issue that will be addressed when #268 is finished.

In the meantime, set this variable right after importing `pyvista`:

```py
import pyvista as pv
pv.rcParams['use_panel'] = False
```

**Comment by banesullivan** [comment]
> Then I tried Jupyterhub on a remote server, the kernel died. Do you have a solution for that?

If you pass `notebook=False` when running on a remote server, it will crash the kernel or freeze it because it's trying to open up a window on the headless system. This is expected.

**Comment by pinshuai** [comment]
Thank you. I am exited for the fix.  Using `pv.rcParams['use_panel'] = False` does show the colormap, although it is a static plot.

**Comment by banesullivan** [comment]
> Using `pv.rcParams['use_panel'] = False` does show the colormap, although it is a static plot.

That's expected, yet unfortunate. We have a ways to go before the notebook rendering will support all features that the flagship `pyvista.Plotter` (or `pyvista.BackgroundPlotter`) supports.
