### ISSUE TITLE
BackgroundPlotter not cleaning up app menu

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#347]
The File, View, and Tools menus are still available after the `BackgroundPlotter` closes. If you open a normal `Plotter` after closing a `BackgroundPlotter`, the File, View, and Tools menus are available and cause errors if used.

This only happens on Mac because those menus appear in the System menu bar whereas on Windows and Linux, they appear in the plotter's window:

<img width="267" alt="Screen Shot 2019-08-02 at 10 31 09 AM" src="https://user-images.githubusercontent.com/22067021/62384828-abec3900-b510-11e9-8303-282c23147a92.png">

**Comment by GuillaumeFavelier** [comment]
But the 'Camera' menu closes correctly?

**Comment by GuillaumeFavelier** [comment]
Whoops. My bad this one is in in 'View'

**Comment by GuillaumeFavelier** [comment]
What happens if you modify the line 388 of the `qt_plotting.py` file by:
```py
main_menu = QMenuBar(0)
self.app_window.signal_close.connect(main_menu.close)
```

**Comment by banesullivan** [comment]
Calling `main_menu.clear` did the trick - `main_menu.close` had no effect.
