### ISSUE TITLE
plt.add_legend() can't support chinese labels

### ISSUE THREAD

**Issue by moonckk** [pyvista/pyvista#3501]
### Describe what maintenance you would like added.

hello, i meet a trouble,
**plt.add_legend() can't support chinese labels**
could you give me some suggestion?

### Pseudocode or Screenshots

```python
# 定义颜色
        geo_color_dict = project_entity.surface_color_dict
        color_num = len(geo_color_dict)
        color_list = []
        for i in range(color_num):
            geo_color_rgb = geo_color_dict[str(i + 1)]
            color_list.append(numpy.array([geo_color_rgb[0] / 256,
                                           geo_color_rgb[1] / 256,
                                           geo_color_rgb[2] / 256,
                                           1.0]))
        geo_grid_color_map = ListedColormap(color_list)
        geo_surface_color_map = ListedColormap(color_list)
        geo_slice_color_map = ListedColormap(color_list)
        geo_clip_color_map_list = []
        for i in range(color_num):
            geo_clip_color_map_i = ListedColormap(color_list[i])
            geo_clip_color_map_list.append(geo_clip_color_map_i)

        # 渲染图例legend
        label_list = []
        geo_surface_dict = project_entity.surface_dict
        surface_num = len(geo_surface_dict)
        for i in range(surface_num):
            label = (geo_surface_dict[str(i + 1)], color_list[i])
            label_list.append(label)
        self.add_legend(label_list,
                        bcolor='w',
                        size=(0.2, 0.2),
                        loc='lower right',
                        face='rectangle')
```

![image](https://user-images.githubusercontent.com/108472093/197328777-d1127c00-a7a6-499f-bf02-6bb4cb848c1b.png)

**Comment by banesullivan** [comment]
Would you please provide the string labels in `label_list` of the Chinese text/characters?

**Comment by banesullivan** [comment]
FYI, this might be helpful: https://discourse.vtk.org/t/chinese-characters-rendering-issue/4457

**Comment by adam-grant-hendry** [comment]
@moonckk If you are on Windows, by default that OS uses `cp1252` encoding instead of `utf-8`, so in that case whenever `open` is used (or similar from the `io` module), the encoding has to be explicitly specified. as in `with open('myfile.txt', encoding='utf-8')`. All other OSs use `utf-8` by default.

What OS are you using?

**Comment by moonckk** [comment]
i have solved it, thank you.

**Comment by Jimmy-KL** [comment]
> i have solved it, thank you.

@moonckk can you share how you solve this issue? Thanks
