### ISSUE TITLE
Inherited methods are documented too many times

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#3546]
### Describe what maintenance you would like added.

In the documentation (most notable with the filter classes) inherited methods are documented everywhere they are inherited. This can be overwhelming to find the "right" reference of the method and I suspect the examples for these methods are getting executed and saved for each place they show up.

It's confusing to see the same filter appear in 13+ places for each of the inherited filter classes and actual data classes:

<img width="1038" alt="Screen Shot 2022-11-03 at 10 16 18 AM" src="https://user-images.githubusercontent.com/22067021/199776035-3206c48a-7e7d-486b-accd-465145142746.png">

<img width="1296" alt="Screen Shot 2022-11-03 at 10 16 58 AM" src="https://user-images.githubusercontent.com/22067021/199776098-fc0f4f37-8b2d-4420-8366-2d32292a52c4.png">

**Comment by akaszynski** [comment]
Thanks for pointing this out, agreed that it's quite annoying.

**Comment by MatthewFlamm** [comment]
I also agree with this.  I expect this will reduce build times for the documentation as well.

Is there a way to still list the inherited methods for each downstream class, but with a link back to the original method?  The vtk docs have a collapsed section for these for easier discovering.  I think completely removing the inherited methods will make the documentation harder to parse in other ways.

**Comment by banesullivan** [comment]
I think we want to use `numpydoc_show_inherited_class_members`: https://numpydoc.readthedocs.io/en/latest/install.html#configuration

However, this might make it tough to find common attributes like `n_cells` when looking an `PolyData` as you would have to look at `DataSet`.

-----

Further this is causing examples to run and be saved for the same methods countless times. For instance, I'm pretty sure sphinx/autosummary is running the Python code for each occurrence:

- https://docs.pyvista.org/api/core/_autosummary/pyvista.PointSet.clip.html
- https://docs.pyvista.org/api/core/_autosummary/pyvista.PolyData.clip.html
- https://docs.pyvista.org/api/core/_autosummary/pyvista.UniformGrid.clip.html
- ... etc
