### ISSUE TITLE
`show(screenshot=...)` regression

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#3548]
### Describe the bug, what's wrong, and what you expected.

In previous versions of PyVista, passing the `screenshot` keyword argument to `Plotter.show()` would take a screenshot on-close so that the user could navigate the scene and position the camera for their screenshot.

This is no longer the case and the screenshot is saved on-show (as the scene is initialized).

This is a regression and is counterintuitive.

### Steps to reproduce the bug.

```python
import pyvista as pv

mesh = pv.Cone()

p = pv.Plotter(notebook=0)
p.add_mesh(mesh)
p.show(screenshot='foo.png')
```

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Thu Nov 03 19:33:31 2022 MDT

                OS : Darwin
            CPU(s) : 8
           Machine : arm64
      Architecture : 64bit
               RAM : 24.0 GiB
       Environment : Jupyter
       File system : apfs
        GPU Vendor : Apple
      GPU Renderer : Apple M2
       GPU Version : 4.1 Metal - 76.3

  Python 3.9.13 (main, Aug 25 2022, 18:24:45)  [Clang 12.0.0 ]

           pyvista : 0.38.dev0
               vtk : 9.2.2
             numpy : 1.23.1
           imageio : 2.22.1
            scooby : 0.5.12
             pooch : v1.6.0
        matplotlib : 3.6.1
           IPython : 8.5.0
          colorcet : 3.0.1
           cmocean : 2.0
        ipyvtklink : 0.2.3
             scipy : 1.9.2
              tqdm : 4.64.1
            meshio : 5.3.4
        jupyterlab : 3.4.8
         pythreejs : Version unknown
--------------------------------------------------------------------------------
```

### Screenshots

| Window on close | saved screenshot |
|---|---|
| <img width="624" alt="Screen Shot 2022-11-03 at 7 34 00 PM" src="https://user-images.githubusercontent.com/22067021/199866283-8096a056-5d15-417c-a6c5-8c47b2218326.png"> | ![foo](https://user-images.githubusercontent.com/22067021/199866268-807ebd21-5abe-4a18-b1c9-943841896470.png) |

**Comment by akaszynski** [comment]
Let's fix this in `v0.37.1`. This is an annoying regression.
