### ISSUE TITLE
 points_gaussian color default does not respect the theme

### ISSUE THREAD

**Issue by akaszynski** [pyvista/pyvista#3551]
The `points_gaussian` default color does not respect the theme:

```py
pv.set_plot_theme('document')
pv.plot(points, style='points_gaussian', opacity=0.5, point_size=15)
```

![image](https://user-images.githubusercontent.com/11981631/200049458-d4ee3143-5970-4156-951d-82e6ee8b136c.png)

**Comment by banesullivan** [comment]
I'm pretty sure this resolved itself... at least it's working for me and the docs look good: https://dev.pyvista.org/examples/02-plot/point-clouds.html#point-cloud-plot-styles
