### ISSUE TITLE
Line Picking

### ISSUE THREAD

**Issue by emielkemmm** [pyvista/pyvista#3564]
### Describe the feature you would like to be added.

It would be great to be able to pick a line, or multiple lines, from an imported mesh. Currently, you can somewhat do this with `enable_cell_picking`, but this limits your selection ability to using the selection window tool, and also doesn't appear to capture all lines in the mesh. A minimal working example of what I've done is below. If there is some way to do this with the current code base, I haven't come across it, but let me know if there is.

### Pseudocode or Screenshots

```python
import pyvista as pv
p = pv.Plotter(notebook=False)
thing = pv.read(<path_to_mesh.stl>)
p.add_mesh(thing,pickable=True)
p.enable_cell_picking(through=True,color='r')
```

**Comment by banesullivan** [comment]
Do you want to specifically pick line cells existing in the mesh? Can you elaborate more on the result you are looking for?

**Comment by emielkemmm** [comment]
My end-goal is to have a CAD-like environment, where I could import a mesh (let's say a cylinder or cube) and could select specific edges of the shape. Those edges would probably already exist in the mesh, although I would likely need to select a number of edges to get the enclosed shape (for example, if I wanted to select the circle on a cylinder, I'd likely need to select a large number of edges all around).

**Comment by banesullivan** [comment]
After #4254, this is done as:

```py
import pyvista as pv
from pyvista.plotting.opts import ElementType, PickerType
from pyvista import examples

mesh = examples.download_bunny_coarse()

p = pv.Plotter()
p.add_mesh(mesh, show_edges=True, pickable=True)
p.enable_element_picking(mode=ElementType.EDGE, line_width=10)
p.show()
```
![screenshot (18)](https://github.com/pyvista/pyvista/assets/22067021/8056b406-6e51-4d86-8265-1987e430bcb8)
