### ISSUE TITLE
Adding connectivity methods to DataSet

### ISSUE THREAD

**Issue by beroda** [pyvista/pyvista#3598]
### Describe the feature you would like to be added.

Following the work of @MatthewFlamm (https://github.com/pyvista/pyvista/pull/2897), I would like to go further and add more methods to **DataSet**  that will enable to access the vtk connectivity (read-only).

### Links to VTK Documentation, Examples, or Class Definitions.

I found these vtk examples/functions/ideas that could be interesting to have in pyvista (correct me if they are already in the library):

1. https://vtk.org/doc/nightly/html/classvtkDataSet.html#a36d1d8f67ad67adf4d1a9cfb30dade49
2. https://kitware.github.io/vtk-examples/site/Cxx/PolyData/CellPointNeighbors/
3. https://kitware.github.io/vtk-examples/site/Cxx/PolyData/CellEdgeNeighbors/
4. A method to get all the point neighbors of a given point

Please, feel free to add some suggestions in subsequent comments and I can update the issue description.
Let's make it collaborative :)

### Pseudocode or Screenshots

I will propose a PR promptly.
I plan to propose the following method names:

1. https://vtk.org/doc/nightly/html/classvtkDataSet.html#a36d1d8f67ad67adf4d1a9cfb30dade49
```python
def point_cell_ids(self,ind: int) -> List[int]:
```
2. https://kitware.github.io/vtk-examples/site/Cxx/PolyData/CellPointNeighbors/
```python
def cell_point_neighbors_ids(self,ind:int) -> List[int]:
```
3. https://kitware.github.io/vtk-examples/site/Cxx/PolyData/CellEdgeNeighbors/
```python
def cell_edge_neighbors_ids(self,ind:int) -> List[int]:
```
4. A method to get all the point neighbors of a given point
```python
def point_neighbors_ids(self, ind: int) -> List[int]:
```

**Comment by banesullivan** [comment]
These would be a great addition - I too think that each of these would make sense to bind to the `DataSet` class but I want to make sure we really do our homework to make sure the implementations will work with all `DataSet` subtypes as most of the examples are given for `PolyData`.

A problem will likely arise when dealing with implicitly defined meshes like `vtkImageData`/`pyvista.UniformGrid` and `vtkRectilinearGrid`/`pyvista.RectilinearGrid` where there are no actual POINTS in the mesh. If this comes up as an issue, I'd recommend putting these methods in the `pyvista._PointSet` class which wraps `vtkPointSet` and is a base class for point based meshes like `PolyData`, `StructuredGrid`, etc.

Look forward to seeing your PR!

**Comment by beroda** [comment]
> A problem will likely arise when dealing with implicitly defined meshes like `vtkImageData`/`pyvista.UniformGrid` and `vtkRectilinearGrid`/`pyvista.RectilinearGrid` where there are no actual POINTS in the mesh. If this comes up as an issue, I'd recommend putting these methods in the `pyvista._PointSet` class which wraps `vtkPointSet` and is a base class for point based meshes like `PolyData`, `StructuredGrid`, etc.

Yes, I completely agree with you @banesullivan.
I intended to test my implementations with various grid types, as opposed to most tests in **test_dataset.py** that relies on the **hexbeam** example (vtkUnstructuredGrid) only.

**Comment by MatthewFlamm** [comment]
As we collect more of these, we should consider having a cell and/or point class.  Otherwise, we will balloon the methods of our DataSets even farther.  An example would be something like:

```py
mesh  # pyvista.DataSet
mesh.cells_list   # needs better naming
mesh.cells_list[0].point_ids  # the point ids associated with cell 0
```

Having said this, I think it is fine to add one by one as filters now, then we can deprecate later if we choose to move to the above framework.

**Comment by beroda** [comment]
> As we collect more of these, we should consider having a cell and/or point class. Otherwise, we will balloon the methods of our DataSets even farther. An example would be something like:
> 
> ```python
> mesh  # pyvista.DataSet
> mesh.cells_list   # needs better naming
> mesh.cells_list[0].point_ids  # the point ids associated with cell 0
> ```
> 
> Having said this, I think it is fine to add one by one as ~filters~ `DataSet` methods now, then we can deprecate later if we choose to move to the above framework.

@MatthewFlamm Excellent idea, I think I will go towards that direction.
I started working on it [here](https://github.com/beroda/pyvista/tree/feat/add_connectivity_methods) but it is not ready for a PR yet (some implementations, docstrings and tests are missing).
