### ISSUE TITLE
Verbosity control

### ISSUE THREAD

**Issue by PBrockmann** [pyvista/pyvista#3612]
### Describe the feature you would like to be added.

From a code that extrat edges, I get some messages coming from vtk.
vtkExtractEdges.cxx:435
-->
vtkLog(INFO, "Executing edge extractor: points are renumbered");

Is there a way to control this from pyvista ?

![image](https://user-images.githubusercontent.com/5402758/202430504-f1b187be-79b4-443f-98a3-138f40d39609.png)

**Comment by banesullivan** [comment]
What version of VTK are you using? I think something changed in a more recent VTK where the logging verbosity was set to INFO-level

**Comment by PBrockmann** [comment]
The latest. 9.2.2

I have warnings not errors. So
```
pv.set_warning_output_file("errors.txt") 
```
does not work.
Not very important but just would be nice.

**Comment by banesullivan** [comment]
Did you do the other part with VTK to turn off VTK's output of these warnings and errors:

```py
import vtk
vtk.vtkObject.GlobalWarningDisplayOff()
```

**Comment by banesullivan** [comment]
Huh. Yeah something has changed in VTK 9.2.2 where verbosity has increased and isn't being suppressed in the ways is used to be able to be. I will look into this.

**Comment by banesullivan** [comment]
This is fixable by:

```py
import vtk
vtk.vtkLogger.SetStderrVerbosity(vtk.vtkLogger.VERBOSITY_OFF)
```

**Comment by banesullivan** [comment]
The difference is what you are seeing from this filter is from the `vtkLogger` where as some other filters throw `vtkWarning`. `vtk.vtkLogger.SetStderrVerbosity(vtk.vtkLogger.VERBOSITY_OFF)` turns off all logging (what most people want) and `vtk.vtkObject.GlobalWarningDisplayOff()` turns off all errors and warnings

**Comment by PBrockmann** [comment]
Nice.
Great thanks.

**Comment by user27182** [comment]
> This is fixable by:
> 
> import vtk
> vtk.vtkLogger.SetStderrVerbosity(vtk.vtkLogger.VERBOSITY_OFF)

There is now a getter/setter/context manager for this, added in #7313

``` python
import pyvista as pv
pv.vtk_verbosity('off')
```

See docs:
https://dev.pyvista.org/api/utilities/_autosummary/pyvista.vtk_verbosity.html#pyvista.vtk_verbosity
