### ISSUE TITLE
Artifacts in ```compute_implicit_distance```

### ISSUE THREAD

**Issue by lorinczszabolcs** [pyvista/pyvista#3613]
### Describe the bug, what's wrong, and what you expected.

After using `compute_implicit_distance` the result contains artifacts. The distance values are in general correct, but there appears to be some kind of noise that I can't really comprehend where does it come from. The surface is triangulated and stripped.

### Steps to reproduce the bug.

```python
grid = pv.UniformGrid()
grid.origin = origin
grid.spacing = spacing
grid.dimensions = shape
grid.compute_implicit_distance(surf, inplace=True)
dist = grid['implicit_distance'].reshape(shape, order='F')
```

Unfortunately can't reproduce it with e.g. `pv.Sphere`, since it won't result in such errors, using the code below:
```python
grid = pv.UniformGrid()
grid.origin = (-0.5, -0.5, -0.5)
grid.spacing = (0.025, 0.0097, 0.0097)
grid.dimensions = (50, 103, 103)
grid.compute_implicit_distance(surf, inplace=True)
dist = grid['implicit_distance'].reshape((50, 103, 103), order='F')
```

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Thu Nov 17 12:54:51 2022 CET

                OS : Linux
            CPU(s) : 8
           Machine : x86_64
      Architecture : 64bit
               RAM : 11.7 GiB
       Environment : Jupyter
       File system : ext4
       GPU Details : error

  Python 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:56:21)
  [GCC 10.3.0]

           pyvista : 0.37.0
               vtk : 9.1.0
             numpy : 1.23.4
           imageio : 2.22.0
            scooby : 0.5.12
             pooch : v1.6.0
        matplotlib : 3.6.2
             PyQt5 : 5.12.3
           IPython : 8.6.0
        ipyvtklink : 0.2.3
             scipy : 1.9.3
        jupyterlab : 3.5.0
```

### Screenshots

Surface that I am trying to calculate signed distances from:
![image](https://user-images.githubusercontent.com/13637835/202439921-efa24a18-2ac9-4ad6-b8eb-ccecdd720980.png)

Resulting in distances with artifacts:
![image](https://user-images.githubusercontent.com/13637835/202440041-c07a9179-e7b7-4185-aadd-c2e8d7046c20.png)

Same code with `pv.Sphere` not resulting in artifacts:
![image](https://user-images.githubusercontent.com/13637835/202440144-ff046c8f-3cf7-4adc-8e09-eb2ec7781cd1.png)

**Comment by banesullivan** [comment]
Can you share the `surf` surface that it is computing the distances from?

**Comment by lorinczszabolcs** [comment]
[Here](https://github.com/pyvista/pyvista/files/10036623/surf.zip) it is. Couldn't upload the .vtk file directly, needed to zip it.
