### ISSUE TITLE
argument "name" in Plotter.update_scalar_bar_range(clim, name=None) is not working

### ISSUE THREAD

**Issue by Jimmy-KL** [pyvista/pyvista#3625]
### Describe the bug, what's wrong, and what you expected.

If I give a value to the argument _name_ in Plotter.update_scalar_bar_range(clim, name=None), there will be an error message as follow ([API Reference](https://docs.pyvista.org/api/plotting/_autosummary/pyvista.Plotter.update_scalar_bar_range.html)):
AttributeError: 'Plotter' object has no attribute '_scalar_bar_mappers'

What I tried to do is that when I change the data array, I want the color map to change its value range and the tile of the color bar automatically. Then I find this method Plotter.update_scalar_bar_range(). Unfortunately, the 2nd argument cannot work.
BTW, if there any other way to do what I expect? Thanks!

### Steps to reproduce the bug.

```python
import pyvista as pv
import numpy as np

mesh = pv.Sphere()
mesh.point_data['data1'] = np.arange(mesh.n_points)
mesh.point_data['data2'] = 10*np.arange(mesh.n_points)

pl = pv.Plotter()
pl.add_mesh(mesh, scalars='data2')
mesh.set_active_scalars('data1')
min_value = min(mesh.get_array('data1'))
max_value = max(mesh.get_array('data1'))
pl.update_scalar_bar_range([min_value, max_value], name='data1')
pl.show()
```

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Sun Nov 20 22:48:25 2022 中国标准时间

                OS : Windows
            CPU(s) : 16
           Machine : AMD64
      Architecture : 64bit
       Environment : Python
        GPU Vendor : Intel
      GPU Renderer : Intel(R) UHD Graphics
       GPU Version : 4.5.0 - Build 31.0.101.1999

  Python 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit
  (AMD64)]

           pyvista : 0.36.1
               vtk : 9.1.0
             numpy : 1.22.0
           imageio : 2.22.0
           appdirs : 1.4.4
            scooby : 0.5.12
        matplotlib : 3.5.1
           IPython : 8.0.1
        ipyvtklink : 0.2.3
             scipy : 1.7.3
            meshio : 5.3.4
         pythreejs : Version unknown
--------------------------------------------------------------------------------
```

**Comment by adeak** [comment]
I first thought it was only an issue with how we raise an uninformative error. Since you plotted the mesh with `scalars='data2'` and no explicit title for the scalar bar, you can only try changing the limits with `name='data2'`. But this leads to the same error. I think due to a recent refactor the name of scalar bars might have detached from the title of the scalar bar. In any case I'll look into this and try to fix it.

Thanks for the report @Jimmy-KL!
