### ISSUE TITLE
ImportError: DLL load failed while importing vtkPythonContext2D: The specified module could not be found.

### ISSUE THREAD

**Issue by TasminSarkany** [pyvista/pyvista#3635]
### Describe the bug, what's wrong, and what you expected.

I have installed pyvista using conda. However when I try and import it into a Jupyter notebook I receive the error "ImportError: DLL load failed while importing vtkPythonContext2D: The specified module could not be found." I have also tried installing pyvista using pip (after uninstalling the conda version) but when I try to import it the same error occurs. Any help on this would be much appreciated.

### Steps to reproduce the bug.

```python
import pyvista as pv
```

### System Information

```shell
Since pyvista does not import I cannot carry out this step. However the pyvista version is

# Name                    Version            Build           Channel
pyvista                   0.37.0             pyhd8ed1ab_0    conda-forge

and I am using Python 3.11.0, conda 22.9.0.
```

### Screenshots

![image](https://user-images.githubusercontent.com/97968653/203175000-9de8a8a5-960d-4362-8651-79950e5e1333.png)

**Comment by dcbr** [comment]
Some issues with this import have also been reported in #3224 and I was going to address this in #2868. I'll try to wrap up that PR asap, sorry for the delay and inconvenience.
Are you using a custom built VTK package? Otherwise upgrading VTK through pip (or conda) could also resolve the import error I believe.

**Comment by TasminSarkany** [comment]
That worked - thanks a lot!
