### ISSUE TITLE
Cannot build documentation locally

### ISSUE THREAD

**Issue by beroda** [pyvista/pyvista#3663]
### Describe the bug, what's wrong, and what you expected.

Trying to build the doc locally following the instructions on the **README** file with:
```shell
make -C doc html
```
I end up with the following error:

![image](https://user-images.githubusercontent.com/117822458/204923088-70386ab9-d249-4f85-8908-08a8e97519f6.png)
 I tried python3.8 and python 3.9  unsucessfully.

It is weird because I **can** find the `charts` attribute interactively:
![image](https://user-images.githubusercontent.com/117822458/204923850-4e52c52e-7346-47e2-a6f1-f7cecf6337e5.png)

### Steps to reproduce the bug.

```shell
make -C doc html
```

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Wed Nov 30 23:34:10 2022 CET

                OS : Linux
            CPU(s) : 8
           Machine : x86_64
      Architecture : 64bit
               RAM : 15.5 GiB
       Environment : IPython
       File system : ext4
        GPU Vendor : Intel
      GPU Renderer : Mesa Intel(R) HD Graphics 630 (KBL GT2)
       GPU Version : 4.6 (Core Profile) Mesa 21.2.6

  Python 3.9.13 (main, May 23 2022, 22:01:06)  [GCC 9.4.0]

           pyvista : 0.38.dev0
               vtk : 9.2.2
             numpy : 1.23.5
           imageio : 2.22.4
            scooby : 0.7.0
             pooch : v1.6.0
        matplotlib : 3.6.2
           IPython : 8.7.0
          colorcet : 3.0.1
           cmocean : 2.0
        ipyvtklink : 0.2.3
             scipy : 1.9.3
        itkwidgets : 0.32.4
              tqdm : 4.64.1
            meshio : 5.3.4
        jupyterlab : 3.5.0
         pythreejs : Version unknown
--------------------------------------------------------------------------------
```

**Comment by MatthewFlamm** [comment]
I'm wondering if you are importing the local pyvista package when you get a repl, but a different version when making the docs, maybe in the virtual environment or some user or global environment.  If you `cd`, assuming Linux, into the `doc` folder and then launch the python repl and import pyvista, do you have the same error?

**Comment by beroda** [comment]
@MatthewFlamm You are right, there is something weird when I go to the `doc` folder. 
It sees pyvista as a namespace ...

See attached:
![image](https://user-images.githubusercontent.com/117822458/205008695-8dcced43-78d7-4071-95f4-cad82cb80f56.png)

**Comment by MatthewFlamm** [comment]
Something weird is going on with your environment. I have no idea what they problem is, if it were me, I would try either uninstalling pyvista from this environment from the doc folder and then doing an editable install from inside the root repo folder, or nuke the environment and start over.

**Comment by banesullivan** [comment]
I've seen a similar issue lately on other projects where `import pyvista` might be trying to import a directory called `pyvista` in your path rather than the actual Python package. See if there is a folder called `pyvista` in your Python Path that isn't the package directory.

**Comment by beroda** [comment]
@banesullivan You were right !
I forgot a **$PYTHONPATH** that was pointing to the `pyvista` root folder, this is why it conflicted with the pip install.

I removed it and was able to generate the documentation ! This issue can be closed

**Comment by banesullivan** [comment]
Yeah, I didn't know this was possible until recently... I thought a directory had to have an `__init__.py` file?

```py
➜  mkdir foobar
➜  python
Python 3.9.13 (main, Aug 25 2022, 18:24:45)
[Clang 12.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import foobar
>>>
```

**Comment by beroda** [comment]
Apparently since python 3.3
https://packaging.python.org/en/latest/guides/packaging-namespace-packages/

**Comment by banesullivan** [comment]
I need to get with the times 🙃
