### ISSUE TITLE
Return image depth from camera

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#368]
Currently, the `image_depth` attribute of plotter returns a depth mapping from 0 to 1. We should fix this to return a true mapping of the distance from the camera to the meshes in the scene. A solution for this is posted on the VTK discourse: https://discourse.vtk.org/t/absolute-values-for-depth-image/326/5?u=banesullivan

https://github.com/pyvista/pyvista/blob/78e65f544f102ff9f488190a2938c68e4c89c55a/pyvista/plotting/plotting.py#L2578

Should be updated to:

```py
relative = self._run_image_filter(ifilter)
near, far = self.camera.GetClippingRange()
z_val = 2*near*far/((relative[:, :, 0] - 0.5) *2*(far - near)  - near - far)
z_val[z_val <= -far] = np.nan
return z_val
```

Ping @tomtomatron

**Comment by banesullivan** [comment]
Another thing to think about is that that implementation will return negative distances.... should we make them positive?

Also, let's definitely be sure to add an example for this in the gallery to catch computer vision folks' attention

**Comment by banesullivan** [comment]
And another afterthought... if the clipping range is within the data range, then we'll run into issues when filling the NaNs. Perhaps we should reset the clipping range to ensure it is greater than the data range?

**Comment by banesullivan** [comment]
AND.... since we allow parallel projections in the render scene, we'll also need to have a condition that checks if the scene is parallel or perspective:

```py
if self.camera.GetParallelProjection():
    z_val = (relative[:, :, 0] - near) / (far - near)
else:
    z_val = 2*near*far/((relative[:, :, 0] - 0.5) *2*(far - near)  - near - far)
```

**Comment by tomtomatron** [comment]
> Another thing to think about is that implementation will return negative distances.... should we make them positive?

I think we should keep the coordinate convention of VTK and the benefits of a right-handed coordinate system.  Especially if things like cross-products start being used we will want a right-handed coordinate system.

**Comment by tomtomatron** [comment]
> And another afterthought... if the clipping range is within the data range, then we'll run into issues when filling the NaNs. Perhaps we should reset the clipping range to ensure it is greater than the data range?

To do this we would have to measure the distance from all points in the scene to the camera, then reset the clipping range -- it could become expensive.

**Comment by banesullivan** [comment]
> To do this we would have to measure the distance from all points in the scene to the camera, then reset the clipping range -- it could become expensive.

I think a simple call to `self.renderer.ResetCameraClippingRange()` should handle this for us actually

**Comment by tomtomatron** [comment]
> ```python
>     z_val = (relative[:, :, 0] - near) / (far - near)
> ```

Adding this to pending fix

**Comment by tomtomatron** [comment]
> self.renderer.ResetCameraClippingRange

Makes sense this exists haha

**Comment by tomtomatron** [comment]
I think we should add a boolean flag to reset the clipping range and default the flag to True.  [The accuracy of the depth image is strongly relate to the clipping range](https://www.khronos.org/opengl/wiki/Depth_Buffer_Precision) so we want to support turning off this behaviour for CV folks.

**Comment by banesullivan** [comment]
I think we should convert `image_depth` from an `@property` to a plain old method with configurable keyword arguments. This will not be backwards compatible but I don't think anyone is actually using the `image_depth` attribute besides us so it *should be* fine.

> I think we should add a boolean flag to reset the clipping range and default the flag to True.

Perhaps have a `clipping_range` argument in the method that defaults to `None` which will reset the clipping range, but a user could also pass `False` to do nothing with the clipping range (leave it alone), or it could take a tuple of 2 values and explicitly set the min/max of the clipping range... We'll need to manually test this to make sure it works as I think the scene might have to be rerendered when the clipping range is reset

**Comment by banesullivan** [comment]
Perhaps refactor the name of this method to something other than `image_depth` and leave the old property to raise an error alerting users this functionality has changed? New name suggestion: `get_depth_image`?

**Comment by banesullivan** [comment]
And of course add a `fill_value` keyword argument to use values other than NaN (and alone None to not replace any values)

**Comment by tomtomatron** [comment]
> Perhaps refactor the name of this method to something other than `image_depth` and leave the old property to raise an error alerting users this functionality has changed? New name suggestion: `get_depth_image`?

What kind of error should it raise when someone tries accessing the old `image_depth` property?

**Comment by banesullivan** [comment]
An `AttributeError` with a message pointing the user to the new method 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pablospe** [comment]
> I think we should keep the coordinate convention of VTK and the benefits of a right-handed coordinate system. Especially if things like cross-products start being used we will want a right-handed coordinate system.

And what is the coordinate system used in VTK? +X left, +Y down, +Z forward?

```
    ^
   /
 z
/
--- x --->
|
y
|
v
```

I am trying to figure out how to get the vtk camera from intrinsic/extrinsic parameters.

**Comment by pablospe** [comment]
I created a separeted issue for this: Issue https://github.com/pyvista/pyvista/issues/1215
