### ISSUE TITLE
2D plots: VTK or Matplotlib?

### ISSUE THREAD

**Issue by andrea-bistacchi** [pyvista/pyvista#3702]
### Discussed in https://github.com/pyvista/pyvista/discussions/3641

<div type='discussions-op-text'>

<sup>Originally posted by **andrea-bistacchi** November 23, 2022</sup>
Hello, I was wondering whether 2D plots in PyVista are based upon VTK or Matplotlib. The reason I ask is we are having poor performance plotting many data in Matplotlib and I am considering using PyVista instead.

Another important point is whether mouse interaction is possible in these plots and if there are examples.

Thanks!</div>

**Comment by andrea-bistacchi** [comment]
At the moment we are using Matplotlib but it is very slow. We have a huge mass of data to plot interactively since we are using it to plot geometries,  meshes, grids etc. in 2D maps and cross sections.

That's why we are looking for alternatives.

We also need interaction to pick objects and draw (we are doing this with Matplotlib mouse interaction at the moment).

Thanks!

**Comment by dcbr** [comment]
I have no experience with very large datasets, so for me personally matplotlib is usually fine for 2D plotting.
But in pyvista you really have the choice:

* If it's simple 2D charts you want to draw, you can have a look at the [Charts API](https://docs.pyvista.org/api/plotting/charts/index.html). These are all VTK wrappers, so I assume they will be fast for large datasets. There's also the special [ChartMPL class](https://docs.pyvista.org/api/plotting/charts/_autosummary/pyvista.ChartMPL.html#pyvista.ChartMPL) which can be used to embed existing matplotlib charts in a pyvista plotting window. Note that this last option is probably not what you want, as you are just using matplotlib (which is already too slow for your purpose) with the extra overhead of converting the figure to an image and embedding it in the plotting window.
* For more complex 2D plots (meshes, grids), I think you can just use the existing [3D plotting capabilities](https://docs.pyvista.org/api/plotting/index.html) of pyvista (leveraging VTK under the hood, so fast for large datasets), while keeping the z-component fixed (e.g. 0) and then use the [view_xy method](https://docs.pyvista.org/api/plotting/_autosummary/pyvista.Plotter.view_xy.html) to obtain a 2D look of the scene?

**Comment by dcbr** [comment]
And mouse interaction is possible with each of these alternatives, except for `ChartMPL` (embedded matplotlib charts).

**Comment by andrea-bistacchi** [comment]
Very good, this clarifies!

In the documentation you say "Matplotlib-like plotting in PyVista" and from this comes the uncertainty.

Do you recall any examples of mouse interaction in 2D charts?

In any case we will try and let you know if we see a noticeable increase in performance.

Thanks very much!

**Comment by dcbr** [comment]
You can check the [Chart basics](https://docs.pyvista.org/examples/02-plot/chart_basics.html) and [Chart overlays](https://docs.pyvista.org/examples/02-plot/chart_overlays.html) examples to get started. To enable interaction with the chart you have to double click (interaction is disabled by default).

**Comment by andrea-bistacchi** [comment]
Thanks!

Could this default behavior be changed by setting a property?

And is it possible to pick an actor and/or get the mouse click coordinates?

Thanks!

**Comment by dcbr** [comment]
> Could this default behavior be changed by setting a property?

At the moment not, you would have to manually call the `SetInteractive` method of the chart and change the render window interaction style. This might be simplified in a future release though.

> And is it possible to pick an actor and/or get the mouse click coordinates?

For 3D plots both are possible, you can check the corresponding examples in the docs. For 2D charts some more manual work is needed, but you can get the mouse position of a click event using [the `track_click_position` method](https://docs.pyvista.org/api/plotting/_autosummary/pyvista.Plotter.track_click_position.html).

**Comment by andrea-bistacchi** [comment]
Thanks very much!!!!

**Comment by banesullivan** [comment]
This doesn't feel terribly actionable to me, so I'm closing

I suppose #3756 implements what's requested here

**Comment by andrea-bistacchi** [comment]
Thanks!!
