### ISSUE TITLE
BackgroundPlotter menu bar hidden on linux

### ISSUE THREAD

**Issue by GuillaumeFavelier** [pyvista/pyvista#371]
Since around #350 I think, the menu bar is not visible on my linux Manjaro:

![image](https://user-images.githubusercontent.com/18143289/64615744-6ce8b780-d3db-11e9-8b16-4f7b3882f4e2.png)

May I suggest to use :

```py
self.main_menu = QMenuBar(parent=self.app_window)
self.app_window.setMenuBar(self.main_menu) # suggested line here!
self.app_window.signal_close.connect(self.main_menu.clear)
```

I tested it locally and it worked for me but I dont want to introduce any regression regarding the work of #350. As the original issue (#347) was discovered on Mac, could you maybe try it out @banesullivan when you have the time?

![image](https://user-images.githubusercontent.com/18143289/64616022-eed8e080-d3db-11e9-915c-0307c80efbaa.png)

**Comment by banesullivan** [comment]
Huh, that's weird. Thanks for pointing this out @GuillaumeFavelier! I'll look into this ASAP

**Comment by banesullivan** [comment]
Sorry, I forgot about this...

You're solution works as expected on Mac and the menu bar still gets cleanup on close

**Comment by GuillaumeFavelier** [comment]
Thank you for trying it out @banesullivan and glad that it works!
