### ISSUE TITLE
Mesh Unions/Intersections

### ISSUE THREAD

**Issue by peterdsharpe** [pyvista/pyvista#373]
Hey @banesullivan !

As always, thank you so much for your great work on this project.

I wanted to ask if it's possible to calculate mesh unions and intersections in PyVista. As a minimum illustrative example of what I'd like to do, consider the following:

```py
import pyvista as pv

sphere1 = pv.Sphere(radius = 1, center=(0,0,0))
sphere2 = pv.Sphere(radius = 1, center=(1,0,0))

p = pv.Plotter()
p.add_mesh(mesh = sphere1, show_edges = True, color = 'red')
p.add_mesh(mesh = sphere2, show_edges = True, color = 'green')
p.show()
```

Would it be possible to generate a PolyData object that represents the union of these two spheres? What about generating a PolyData object that represents the intersection of these spheres? This capability would be very helpful for my research!

Thanks again,
Peter

**Comment by akaszynski** [comment]
Looks like this is already a capability within ``pyvista``.  The ``boolean_union`` method makes sense, but we might think about changing ``boolean_cut`` to ``boolean_intersection``.

Here's the pertinent code:

```python
import pyvista as pv

sphere1 = pv.Sphere(radius = 1, center=(0,0,0))
sphere2 = pv.Sphere(radius = 1, center=(1,0,0))

# mesh intersection
inter = sphere1.boolean_cut(sphere2)

# mesh union
union = sphere1.boolean_union(sphere2)

plt = pv.Plotter()
plt.add_mesh(union, style='wireframe', color='red')
plt.add_mesh(inter, show_edges=False, color='w')
plt.add_legend([['union', 'r'], ['intersection', 'w']])
plt.show()
```

![PyVista_099](https://user-images.githubusercontent.com/11981631/64714885-b3174700-d4bf-11e9-8d85-cb00706b5cb5.png)

**Comment by peterdsharpe** [comment]
Thanks all - this is perfect! :)
