### ISSUE TITLE
Pyvista cannot draw and show all edges of the mesh

### ISSUE THREAD

**Issue by LXHCSMX** [pyvista/pyvista#3738]
### Describe the bug, what's wrong, and what you expected.

I found a bug!

When I used Pyvista to display the mesh model in vtk file, I found that Pyvista could not draw and show all edges of the mesh.
The following file shows the data in vtk file.
Delete the. txt suffix and you can use it.
Please help solve this problem. Many thanks.
[test.vtk.txt](https://github.com/pyvista/pyvista/files/10276098/test.vtk.txt)

### Steps to reproduce the bug.

```python
import pyvista as pv

my_mesh = pv.read("D:/cae_test/mesh_file/test.vtk")
plotter = pv.Plotter()
_ = plotter.add_mesh(my_mesh, color = '#BBFFFF', style = 'surface', show_edges = True,
                     edge_color = '#EE8262', line_width = 0.5, opacity = 1.0)
plotter.show()
```

[test.vtk.txt](https://github.com/pyvista/pyvista/files/10276081/test.vtk.txt)

### System Information

```shell
OS : Windows
            CPU(s) : 20
           Machine : AMD64
      Architecture : 64bit
       Environment : Python
        GPU Vendor : Intel
      GPU Renderer : Intel(R) Iris(R) Xe Graphics
       GPU Version : 4.5.0 - Build 31.0.101.3616

  Python 3.8.15 (default, Nov 21 2022, 10:47:13) [MSC v.1916 64 bit (AMD64)]

           pyvista : 0.37.0
               vtk : 9.2.2
             numpy : 1.23.5
           imageio : 2.23.0
            scooby : 0.7.0
             pooch : v1.6.0
        matplotlib : 3.6.2
         pyvistaqt : 0.9.0
             PyQt5 : 5.15.2
            meshio : 5.3.4
```

### Screenshots

![fig3](https://user-images.githubusercontent.com/39549745/208860802-89d58b53-5674-492a-b323-b53fd0c9ab52.png)
![fig2](https://user-images.githubusercontent.com/39549745/208860811-cbe1d687-acf7-4756-a3c1-d6500a6675ad.png)
![fig1](https://user-images.githubusercontent.com/39549745/208860813-775feae1-67fd-48db-a379-f62bf6fa86f8.png)

**Comment by banesullivan** [comment]
I'm able to reproduce this issue, and something weird is going on with the mesh itself. It appears to have overlapping surfaces, and the surface on top in those suspect areas is not rendering edges. I tried playing with the `culling` options (which usually help in these kinds of scenarios) without luck.

If you turn on the opactiy, you can see another surface behind those areas where edges are being rendered:

```py
import pyvista as pv

my_mesh = pv.read("~/Desktop/test.vtk")
plotter = pv.Plotter(notebook=0)
_ = plotter.add_mesh(my_mesh, color = '#BBFFFF', style = 'surface', show_edges = True,
                     edge_color = '#EE8262', line_width = 0.5, opacity = 0.75)
plotter.enable_depth_peeling()
plotter.show()
```
<img width="624" alt="Screen Shot 2022-12-21 at 9 00 51 AM" src="https://user-images.githubusercontent.com/22067021/208948664-576a2d06-f1d5-463e-81a7-597d86936507.png">

You can see a slight difference in color as they are being rendered behind a transparent surface.

I don't have an immediate solution for this... I'd recommend taking this issue to the VTK discourse to see if they have an idea of what rendering options to use to resolve the issue with overlapping surfaces like this and we can then help you leverage those in PyVista: https://discourse.vtk.org/

**Comment by cquammen** [comment]
This unstructured mesh has both surface data (triangles) and volume data (tetrahedra and wedges). I don't know how PyVista is extracting surfaces for display and enabling wireframe, but my bet is only the wireframe is being displayed from one of the surfaces that is extracted.

If PyVista has exposed `vtkExtractCellsByType`, you could use that to extract only the triangles and display that surface in wireframe.

**Comment by ansmhoeij** [comment]
@banesullivan I ran into similar visualization bug that is possibly related. In my case this occurs when trying to visualize a mesh with both beams and triangles defined. See also https://github.com/pyansys/pydpf-core/issues/741 for the original issue. I managed to reproduce on a simple sphere: 

![image](https://user-images.githubusercontent.com/102799582/234052712-613e3cc1-5a99-4a62-9c54-e289d01c5196.png)

MWE
```Python
"""Pyvista beam visualization bug"""

import pyvista as pv
import numpy as np

poly_sphere = pv.Sphere(radius=10)
grid_sphere = poly_sphere.cast_to_unstructured_grid()

# create unstructured grid with line-elements only on bottom half of sphere.
mask = grid_sphere.points[:,2] < 0

num_lines = np.sum(mask)
cell_types = np.array([pv.CellType.LINE] * num_lines)
cells_lines = np.hstack(
    [
        np.array(([2] * num_lines))[:, None],
        np.argwhere(mask),
        np.argwhere(mask),
    ]
)
cells_lines[:, -1] += 1
cells_lines = np.reshape(cells_lines, (cells_lines.shape[0] * 3))

grid_beams = pv.UnstructuredGrid(cells_lines, cell_types, grid_sphere.points)

# combine sphere and beam-only grid
combined = grid_sphere + grid_beams

# plot all grids
plotter = pv.Plotter(shape=(1,3))
# dpf grid
plotter.subplot(0,0)
plotter.add_mesh(grid_sphere, show_edges=True )
plotter.add_title("Sphere")
# reconstructed grid
plotter.subplot(0,1)
plotter.add_mesh(grid_beams, show_edges=True)
plotter.add_title("Beams")
# combined
plotter.subplot(0,2)
plotter.add_mesh(combined, show_edges=True)
plotter.add_title("Combined")

plotter.link_views(True)
plotter.show()
```

**Comment by akaszynski** [comment]
@ansmhoeij, open a new issue please with this MWE. This looks like a VTK issue, but we might be able to work around it with some creative settings.
