### ISSUE TITLE
Preserve the original VTK object when wrapping

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#375]
We should implement a way to wrap VTK data objects without creating a copy of the object - i.e. wrap the original object. For example, when wrapping, we actually copy the dataset into a new object which is inefficient.

```py
import vtk
import pyvista as pv
import numpy as np

original = vtk.vtkPolyData()
wrapped = pv.PolyData(original)
wrapped.points = np.random.rand(100, 3)

print('Original:', original.GetNumberOfPoints())
print('Wrapped:', wrapped.GetNumberOfPoints())
```
Original: 0
Wrapped: 100

-----

### Why?

I'm working to speed up some of the widgets for clipping, etc., and I need to have PyVista wrapped pointers to the clip filters output mesh. Also... in my mind, if the `deep` kwarg is False then it should be a direct wrapping of the object, not a copy.

@akaszynski, any thoughts on how to do this? The typical Python casting of setting the `.__class__` attribute isn't working for me.

**Comment by banesullivan** [comment]
Also, monkey patching a VTK object doesn't work....

```py
>>> def foo(self, arg):
>>>     print(arg)
    
>>> original.foo = foo
>>> original.foo(0)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-68-161926f77b1a> in <module>
      3 
      4 original.foo = foo
----> 5 original.foo(0)

TypeError: foo() missing 1 required positional argument: 'arg'

```

**Comment by akaszynski** [comment]
Turns out we don't really copy the dataset:

```python
import vtk
import pyvista as pv
from vtk.util.numpy_support import vtk_to_numpy

import numpy as np

points = vtk.vtkPoints()
points.InsertNextPoint(0.0, 0.0, 0.0)
points.InsertNextPoint(1.0, 0.0, 0.0)
points.InsertNextPoint(2.0, 0.0, 0.0)

original = vtk.vtkPolyData()
original.SetPoints(points)
wrapped = pv.PolyData(original, deep=False)

wrapped.points[:] = 0

orig_points = vtk_to_numpy(original.GetPoints().GetData())
print(orig_points)
print(wrapped.points)
```

###### Problem:
When two vtk objects are shallow copied, the pointers from the shallow copy point to the original.  When we use ``wrapped.points = ``, we're changing that pointer by using ``SetPoints``.  We should be using
```python
pdata = self.GetPoints()
pdata.SetData(vtk_points.GetData())
```

However, when a vtk object doesn't have an existing pointer (as in your example), the pointer isn't copied over into the new ``pyvista.PolyData`` object through a shallow copy.  We could fix this, but that would mean adding an empty ``vtkPoints`` object to the original with:
```python
original.SetPoints(vtk.vtkPoints())
```

Adding both these changes will make your example work.  I'm fine with implementing the first change, what do you think about the second?

**Comment by banesullivan** [comment]
Okay, that makes sense that we need to make sure we aren't overriding the pointer to the Points. In that example, `original.GetPoints() == wrapped.GetPoints()` is True since they both point to the same object.

One weird problem... Point/CellData containers always have different pointers and I can't find an elegant way to add point/cell data arrays back to the original object when adding them to the wrapped object. `original.GetPointData() == wrapped.GetPointData()` evaluates to `False`, but the following and the array present on the original object is able to be referenced by both the original and the wrapped, but if I add an array to the wrapped object, the original object is not aware of that array:

```py
import vtk
import pyvista as pv
from vtk.util.numpy_support import vtk_to_numpy

import numpy as np

points = vtk.vtkPoints()
points.InsertNextPoint(0.0, 0.0, 0.0)
points.InsertNextPoint(1.0, 0.0, 0.0)
points.InsertNextPoint(2.0, 0.0, 0.0)

data = vtk.vtkFloatArray()
data.InsertNextValue(3.0)
data.InsertNextValue(4.0)
data.InsertNextValue(5.0)
data.SetName('Foo')

original = vtk.vtkPolyData()
original.SetPoints(points)
original.GetPointData().AddArray(data)


wrapped = pv.PolyData(original, deep=False)

wrapped.point_arrays['Foo'][:] = 8.0
wrapped.point_arrays['New'] = np.random.rand(wrapped.n_points)

print(original.GetPointData() == wrapped.GetPointData())

orig_data = vtk_to_numpy(original.GetPointData().GetAbstractArray('Foo'))
print(orig_data)
print(wrapped.point_arrays['Foo'])
orig_data = vtk_to_numpy(original.GetPointData().GetAbstractArray('New'))
print(orig_data)
print(wrapped.point_arrays['New'])
```

```
False
[8. 8. 8.]
[8. 8. 8.]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-c0aaa7bff028> in <module>
     31 print(orig_data)
     32 print(wrapped.point_arrays['Foo'])
---> 33 orig_data = vtk_to_numpy(original.GetPointData().GetAbstractArray("New"))
     34 print(orig_data)
     35 print(wrapped.point_arrays['New'])

~/anaconda3/envs/dev/lib/python3.7/site-packages/vtkmodules/util/numpy_support.py in vtk_to_numpy(vtk_array)
    214 
    215     """
--> 216     typ = vtk_array.GetDataType()
    217     assert typ in get_vtk_to_numpy_typemap().keys(), \
    218            "Unsupported array type %s"%typ

AttributeError: 'NoneType' object has no attribute 'GetDataType'
```

perhaps we'd need to keep a reference of the original object around and add/set data on that object in these cases? That will get really messy though....

**Comment by banesullivan** [comment]
Overall, my goal is to be able to grab the output object refernce from a VTK algorithm and wrap it before the algorithm runs so that the algorithm can update the wrapped object. Normally, I could just create a data object using PyVista's constructors and set that object as the output of the algorithm using the standard `SetOutput()` method but I have a unique use case with the `vtkBoxClipDataSet` algorithm where that doesn't work because `SetOutput()` can only handle port 0.

When using the `vtkBoxClipDataSet` filter, you can either grab the inside of the clip (output port 0 which is handled by `SetOutput()`/`GetOutput()`) or you can grab the outside of the clip through port 1 (when `GenerateClippedOutputOn()` is called) but I am not aware of a way to set the output data object for that port. I opened a thread on VTK's discourse about this: https://discourse.vtk.org/t/setoutput-data-object-for-non-zero-port/1773

Honestly, it might be easier to just open a PR in VTK to allow setting the data object for that port on this specific filter rather than worrying about keeping track of references to copied datasets


Here's the use case from the `widgets-patch` branch:
<details>

```py
def add_mesh_clip_box(self, mesh, invert=False, rotation_enabled=True,
                          widget_color=None, **kwargs):
        """Add a mesh to the scene with a box widget that is used to clip
        the mesh interactively.

        The clipped mesh is saved to the ``.box_clipped_mesh`` attribute on
        the plotter.

        Parameters
        ----------
        mesh : pyvista.Common
            The input dataset to add to the scene and clip

        invert : bool
            Flag on whether to flip/invert the clip

        rotation_enabled : bool
            If ``False``, the box widget cannot be rotated and is strictly
            orthogonal to the cartesian axes.

        kwargs : dict
            All additional keyword arguments are passed to ``add_mesh`` to
            control how the mesh is displayed.
        """
        name = kwargs.pop('name', str(hex(id(mesh))))
        kwargs.setdefault('clim', mesh.get_data_range(kwargs.get('scalars', None)))

        port = 1 if invert else 0

        alg = vtk.vtkBoxClipDataSet()
        alg.SetInputDataObject(mesh)
        alg.GenerateClippedOutputOn()
        if port == 1:
            self.box_clipped_mesh = alg.GetOutput(port)
        else:
            self.box_clipped_mesh = pyvista.UnstructuredGrid()
            alg.SetOutput(self.box_clipped_mesh)

        def callback(planes):
            bounds = []
            for i in range(planes.GetNumberOfPlanes()):
                plane = planes.GetPlane(i)
                bounds.append(plane.GetNormal())
                bounds.append(plane.GetOrigin())

            alg.SetBoxClip(*bounds)
            alg.Update()
            self.box_clipped_mesh.Modified()
            if port == 1:
                _ = self.add_mesh(self.box_clipped_mesh, name=name, reset_camera=False,
                              **kwargs)

        self.enable_box_widget(callback=callback, bounds=mesh.bounds,
                factor=1.25, rotation_enabled=rotation_enabled,
                use_planes=True, color=widget_color)

        actor = self.add_mesh(self.box_clipped_mesh, name=name, reset_camera=False,
                      **kwargs)

        return actor
```

Which allows the filter to rerun and immediately update the mesh in the render scene.

</details>

**Comment by banesullivan** [comment]
Perhaps the best way to achive my desired effect without the risk of overriding pointers to the original data object would be to create a monkey patching routine in the `pyvista.wrap` method that would bind all the PyVista properties and methods to the original VTK object and then return that object... but that is *super hacky*.

Another thing to consider is the native VTK dataset adapter module that appears to do somtehing along the lines of what I want... maybe I should dive into that source code.

```py
from vtk.numpy_interface import dataset_adapter as dsa

original = vtk.vtkPolyData()

wrapped = dsa.WrapDataObject(original)
wrapped.Points = np.random.rand(100, 3)
np.allclose(wrapped.GetPoints(), vtk_to_numpy(original.GetPoints().GetData()))
```
True

**Comment by banesullivan** [comment]
So in order to do what I need, I can just set up a callback on the algorithm execution that will shallow copy the output dataset to the PyVista wrapped dataset (maybe a callback could be useful on a modified call for the dataset?).

Considering how much of a mess it would be to set up tracking of the original data object and that we already shallow copy datasets upon wrapping, I'm closing this issue.
