### ISSUE TITLE
Triangle strips won't work with pythreejs backend

### ISSUE THREAD

**Issue by zou000** [pyvista/pyvista#3752]
### Describe the bug, what's wrong, and what you expected.

When using `pv.Tube()` with  `pythreejs` backend in google colab, the mesh cannot be added to the plotter, with the error message:
```
/usr/local/lib/python3.8/dist-packages/pyvista/jupyter/pv_pythreejs.py:436: UserWarning: Empty or unsupported dataset attached to actor
  warnings.warn('Empty or unsupported dataset attached to actor')
```

### Steps to reproduce the bug.

In a google colab notebook:
```python
!pip install pyvista pythreejs

from google.colab import output
output.enable_custom_widget_manager()

import pyvista as pv
pv.global_theme.notebook = True
pv.global_theme.jupyter_backend = 'pythreejs'

import numpy as np

p1 = pv.Plotter()
p1.add_mesh(pv.Tube(), color = 'cyan')
p1.show()
```

### System Information

```shell
Mon Dec 26 00:26:17 2022 UTC
OS	Linux	CPU(s)	2	Machine	x86_64
Architecture	64bit	RAM	12.7 GiB	Environment	IPython
GPU Details	error
Python 3.8.16 (default, Dec 7 2022, 01:12:13) [GCC 7.5.0]
pyvista	0.34.2	vtk	9.2.2	numpy	1.21.6
imageio	2.9.0	appdirs	1.4.4	scooby	0.7.0
matplotlib	3.2.2	IPython	7.9.0	colorcet	3.0.1
scipy	1.7.3	tqdm	4.64.1
```

Related: https://github.com/pyvista/pyvista/issues/3439

**Comment by banesullivan** [comment]
Tubes are generated from triange strips and the converter from PyVista to 3JS does not account for this.

```py
>>> import pyvista as pv
>>> mesh = pv.Tube()
>>> mesh.GetCell(0)
(vtkmodules.vtkCommonDataModel.vtkTriangleStrip)0x10d33cf40
```

We are actually soon to deprecate the `pythreejs` notebook rendering backend for various reasons including this sort of mismatch. See #3690. The bad news is that this is unlikely to get fixed for the `pythreejs` backend. The good news is that these sorts of issues will be resolved with the new backend we are creating.

**Comment by banesullivan** [comment]
A work around is to use the `triangulate()` filter to convert the triange strip cells to separate triangle cells:

```py
import pyvista as pv
pv.global_theme.notebook = True
pv.global_theme.jupyter_backend = 'pythreejs'

import numpy as np

mesh = pv.Tube().triangulate()

p1 = pv.Plotter()
p1.add_mesh(mesh, color = 'cyan')
p1.show()
```

**Comment by banesullivan** [comment]
Closing with the recommendation of using the `triangulate()` filter. I'd welcome a fix to the threejs conversion in `pyvista/jupyter/pv_pythreejs.py` that automatically traingulates in the presence of unsupported cells, but I don't think we'll take this work on with the movement towards the new, vtk.js/trame-based backend
