### ISSUE TITLE
Example Chart Overlays doesn't work

### ISSUE THREAD

**Issue by Jimmy-KL** [pyvista/pyvista#3753]
### Describe the bug, what's wrong, and what you expected.

I tried to run example [Chart Overlays](https://docs.pyvista.org/examples/02-plot/chart_overlays.html) and got an error as follow:
`AttributeError: 'NoneType' object has no attribute 'GetDesiredUpdateRate'`

### Steps to reproduce the bug.

The code is as same as in this [example](https://docs.pyvista.org/examples/02-plot/chart_overlays.html).

### System Information

```shell
OS : Windows
            CPU(s) : 16
           Machine : AMD64
      Architecture : 64bit
       Environment : Python
        GPU Vendor : Intel
      GPU Renderer : Intel(R) UHD Graphics
       GPU Version : 4.5.0 - Build 31.0.101.1999

  Python 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit
  (AMD64)]

           pyvista : 0.37.0
               vtk : 9.1.0
             numpy : 1.22.0
           imageio : 2.22.0
            scooby : 0.5.12
             pooch : v1.6.0
        matplotlib : 3.5.1
           IPython : 8.0.1
        ipyvtklink : 0.2.3
             scipy : 1.7.3
            meshio : 5.3.4
         pythreejs : Version unknown
```

**Comment by dcbr** [comment]
This is a known issue and will be fixed in the next release (see #3617).
