### ISSUE TITLE
tarball filename not very descriptive

### ISSUE THREAD

**Issue by MarDiehl** [pyvista/pyvista#3759]
### Describe what maintenance you would like added.

The filename of the tarball is currently `v0.37.0.tar.gz` which is not very descriptive. Would it be possible to change it to `pyvista-0.37.0.tar.gz`?

I know that most users relying on pip or Anaconda don't have this problem, but as an Arch Linux user (and contributor of the python-pyvista package) this is a minor annoyance.

Note: I think the name is a GitHub default for releases and I don't even know whether it can be changed.

### Links to source code.

https://github.com/pyvista/pyvista/archive/refs/tags/v0.37.0.tar.gz

### Pseudocode or Screenshots

```python
Insert code here
```
Or drag your screenshot here!

**Comment by banesullivan** [comment]
I don't think that is something we can control, and it is up to GitHub and your browser. GitHub is directly archiving the repo for you to download. When I go to the [`0.37.0` release page](https://github.com/pyvista/pyvista/releases/tag/v0.37.0) and download the tarball:

<img width="285" alt="Screen Shot 2022-12-29 at 10 53 48 AM" src="https://user-images.githubusercontent.com/22067021/209990904-59355ceb-b2c2-40e5-b7fc-06b516414e2c.png">

The tarball link under the releases is: https://github.com/pyvista/pyvista/archive/refs/tags/v0.37.0.tar.gz

My browser (Chrome on Mac), downloads it as `pyvista-0.37.0.targ.gz`:

<img width="243" alt="Screen Shot 2022-12-29 at 10 55 57 AM" src="https://user-images.githubusercontent.com/22067021/209991115-f0b54d13-7ba1-4084-9ebf-d8e4cb2d596d.png">

Same if I just clink that link in your issue description.

I don't think this is something we have any control over and recommend you raise the issue with GitHub support as I bet you'll see the same in your browser for any repository.

-----

On another note, PyVista's official distribution is hosted on PyPI: https://pypi.org/project/pyvista/#files

**Comment by MarDiehl** [comment]
@banesullivan thanks for the quick reply
It seems that GitHub automatically offers (at least) two links:
- https://github.com/pyvista/pyvista/archive/refs/tags/v0.36.0.tar.gz
- https://github.com/pyvista/pyvista/archive/v0.36.0/pyvista-0.36.0.tar.gz

The first one seems to be the "real" one, it is shown on mouseover but GitHub automatically converts it to the more readable version (if JavaScript is enabled).

**Comment by banesullivan** [comment]
Ah, good catch! Thanks for figuring that out!
