### ISSUE TITLE
q-key doesn't close BackgroundPlotter

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#379]
I just realized that the `q`-key doesn't destroy the app window for the `BackgroundPlotter` when resolving #371 

In this screen capture, I hit the q-key just after interacting with the `BackgroundPlotter` and the render window goes black but the window does not close.

![2019-09-17 14 45 54](https://user-images.githubusercontent.com/22067021/65078362-17bc2100-d95a-11e9-82b1-a315e288d66e.gif)

**Comment by GuillaumeFavelier** [comment]
Good catch! I'll take care of this one. Basically, in #314 the 'q' press event is not connected to the action `self.app_window.close()` I think
