### ISSUE TITLE
Enable multi-version documentation

### ISSUE THREAD

**Issue by jorgepiloto** [pyvista/pyvista#3835]
### Describe what maintenance you would like added.

Multi-version documentation allows to present various documentations (latest, stable, old) in the same website. In [pyansys/actions](https://actions.docs.pyansys.com), we devised a reusable workflow that only requires:

* The usage of pydata-sphinx-theme (already used by PyVista)
* The usage of GitHub pages

The generation of the documentation artifact is performed by PyVista while [doc-deploy-dev](https://actions.docs.pyansys.com/release/3.0/doc-actions/index.html#doc-deploy-dev-action) and [doc-deploy-stable](https://actions.docs.pyansys.com/release/3.0/doc-actions/index.html#doc-deploy-dev-action) only need to know the name of the documentation artifact to operate with it.

### Links to source code.

* PyAnsys actions: https://actions.docs.pyansys.com
* PyAnsys developers guide: https://dev.docs.pyansys.com/dev/how-to/documenting.html#enabling-multi-version-documentation

**Comment by jorgepiloto** [comment]
If this is a desired feature, I would love to see @AlejandroFernandezLuces working on this.

Pinging here @akaszynski, @banesullivan, @tkoyama010.

**Comment by tkoyama010** [comment]
Good idea. It would be helpful also to be able to switch between multiple languages.
Japanese Page: https://pyvista.github.io/pyvista-docs-dev-ja/

**Comment by jorgepiloto** [comment]
May you please assing this to @AlejandroFernandezLuces too, @tkoyama010?

**Comment by jorgepiloto** [comment]
Awesome!

**Comment by banesullivan** [comment]
If @AlejandroFernandezLuces has the bandwidth to do this, I'm happy to provide guidance having set up most of the original documentation hosting
