### ISSUE TITLE
.msh physical group error

### ISSUE THREAD

**Issue by FrankFrank9** [pyvista/pyvista#3850]
Hi,

when I write .gmsh file I lose all the informations about physical groups
If I use 
`Mesh.SaveAll = 1`
I cannot read the .msh file with meshio in python because of 

`ValueError: Incompatible cell data 'gmsh:physical'. 286 cell blocks, but 'gmsh:physical' has 19 blocks.`

Any idea on how to solve this issue?

**Comment by akaszynski** [comment]
Could you please post the full code and traceback? I'm not sure if this is a pyvista issue.
