### ISSUE TITLE
Trame Jupyter support on Google Colab

### ISSUE THREAD

**Issue by francesco-ballarin** [pyvista/pyvista#3851]
Hi @banesullivan,
as mentioned in #3690 I am interested in testing the new trame backend on online jupyter notebook services.
Since #3385 is now ready, I have started looking into it.

My first try was with Google Colab, see
https://colab.research.google.com/drive/1608zRoubwfN2KgTRcEk5hOq3tQJSF0XQ?usp=sharing

I currently get an error at
```
await pv.set_jupyter_backend('client')
```
namely
```
ERROR:root:Exception raised by task = <Task finished name='Task-2' coro=<AiohttpWslinkServer.start() done, defined at /usr/local/lib/python3.8/dist-packages/wslink/backends/aiohttp/__init__.py:101> exception=OSError(99, "error while attempting to bind on address ('::1', 0, 0, 0): cannot assign requested address")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/trame_server/core.py", line 533, in on_done
    task.result()
  File "/usr/local/lib/python3.8/dist-packages/wslink/backends/aiohttp/__init__.py", line 123, in start
    await my_site.start()
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/web_runner.py", line 121, in start
    self._server = await loop.create_server(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1463, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 99] error while attempting to bind on address ('::1', 0, 0, 0): cannot assign requested address
```
Do you have any idea what could be the issue here? Thanks!

**Comment by banesullivan** [comment]
hi @francesco-ballarin, I'm excited to hear you're trying out the new jupyter backend! The problem you're facing is a common one which I may address directly in #3385. The default `host` for `wslink` (the server mechanism behind Trame) is `'localhost'` and some containerized environments do not particularly like that. You will need to switch the host to `'127.0.0.1'`. This can be done through the `TRAME_DEFAULT_HOST` environment variable.

I added some notes in #3385 about needing this in Docker but didn't realize it's probably the case for a lot of containerized environments (Colab included). 

@jourdain, I'm thinking about making the `host` default to `'127.0.0.1'` in PyVista when launching the Trame server to avoid this issue, what do you think? This may have issues on Windows, so perhaps I could have this logic:

```py
# Defualt host to "127.0.0.1":
if os.name == "nt" and host == "127.0.0.1":
        host = "localhost"
```

------

@francesco-ballarin, let me know if that works for you and then let me know if you manage to get all this working on Google Colab (since you'll also need to set up `jupyter-server-proxy`)

**Comment by jourdain** [comment]
`127.0.0.1` should work everywhere and that seems fine to use that as default.

**Comment by banesullivan** [comment]
Okay, I'll modify where PyVista launches the server to use `"127.0.0.1"` as the default to work around this issue

**Comment by francesco-ballarin** [comment]
Thanks @banesullivan !

Setting `TRAME_DEFAULT_HOST` to `127.0.0.1` does indeed solve the error in the opening post. Good to know that it will become the default in future.

I am afraid I need a bit more help with `jupyter-server-proxy`. I have never used that, and thus my experience is limitated to copying the environment variable from the README ;), and that didn't work out of the box.

The link is still
https://colab.research.google.com/drive/1608zRoubwfN2KgTRcEk5hOq3tQJSF0XQ?usp=sharing

A few observations:
- without `pv.start_xvfb()`, the final cell crashes. However, I thought the whole point of the `client` mode was not to require `xvfb` at all, that's why my first attempt was without it.
- with `pv.start_xvfb()` (you may uncomment the third-to-last cell for this), the final cell hangs.
- `vtk` gets currently installed by pip. From our previous discussions in #3690 I seem to remember that it would have been better to use a `osmesa` wheel, but unfortunately I can't use any `vtk_osmesa-9.2.5-cp*-cp*-linux_x86_64.whl` from https://github.com/pyvista/pyvista-wheels because Colab is still on python 3.8 (and kaggle, which I want to try next, even on python 3.7 :( )

**Comment by banesullivan** [comment]
@francesco-ballarin, I'm looking into this. 

Google Colab isn't exactly jupyter so we may not be able to use `jupyter-server-proxy` but maybe another mechanism. The iframe needs authenticated access to the server which I'm looking into... stay tuned...

> without pv.start_xvfb(), the final cell crashes.

Hm... This is odd and not typically the case (for example in Docker this is fine)

> with pv.start_xvfb() (you may uncomment the third-to-last cell for this), the final cell hangs.

This is because PyVista does not detect the environment to be a notebook (because it's Google Colab and not exactly Jupyter). You have to pass `notebook=True` when instantiating the `Plotter`.


> would have been better to use a osmesa wheel, but unfortunately I can't use any ...

We will *soon* have more osmesa wheels across Python versions directly from VTK

**Comment by francesco-ballarin** [comment]
> without pv.start_xvfb(), the final cell crashes.
> with pv.start_xvfb() (you may uncomment the third-to-last cell for this), the final cell hangs.

ok, both of these are solved with `notebook=True`. The iframe now does appear, but cannot connect to the server, as you were expecting.

**Comment by francesco-ballarin** [comment]
FYI @banesullivan  I am trying to keep the above notebook on colab up to date with recent changes, e.g. merge of #3385 to main and #3875.

**Comment by banesullivan** [comment]
Thanks @francesco-ballarin! I haven't forgotten about this and will try to get this work by the 0.38 release

**Comment by banesullivan** [comment]
A note on xvfb and using it with the client mode. It is not needed but there is a limitation of `system_supports_plotting` that causes a warning regardless: reference: https://github.com/pyvista/pyvista/issues/3746

**Comment by banesullivan** [comment]
This should work, but it doesn't... I'm wondering if we should open a ticket with Google Colab...

In this guide: https://colab.research.google.com/notebooks/snippets/advanced_outputs.ipynb

It states:

> Outputs in the browser can request resources from the kernel by requesting https://localhost:{port}. The protocol will automatically be translated from https to http and the localhost will be the kernel executing the code.

This implies that we shouldn't need `jupyter-server-proxy` at all and can use the trame backend the same way as a local notebook. 

I tried this and the the generated iframe is:

```
<iframe src='http://localhost:38879/index.html?ui=P_0x7f17a6d5f8e0_3&reconnect=auto' style='width: 99%; height: 600px;'></iframe>
```

```py
pl = pv.Plotter(notebook=True)
pl.add_mesh(mesh, color='lightgrey')
iframe = pl.show(return_viewer=True)
print(iframe.value)  # shows that value above
iframe
```

Yet it still fails to display in Colab. And using the inspector, indeed, the `localhost` URL was not automatically converted:
<img width="1526" alt="Screen Shot 2023-01-29 at 5 32 24 PM" src="https://user-images.githubusercontent.com/22067021/215365367-174618ab-1c0b-49f0-881e-36e073bef61f.png">

**Comment by banesullivan** [comment]
Unless we can get that to work, this may have to wait until https://github.com/Kitware/wslink/issues/129 is implemented

**Comment by francesco-ballarin** [comment]
I am not fully sure if what I did make sense, and it is definitely not reproducible unless you manually carry out the steps marked as TODO, but I did manage to get the following
![Screenshot from 2023-01-29 20-07-35](https://user-images.githubusercontent.com/11783908/215367858-7c747c61-a3c9-4d17-9df3-d0ad19062b57.png)
which, even though it doesn't work yet, it's more promising than what we had before.

If we don't manage to sort this out by ourselves, the repo to open tickets for Colab is 
https://github.com/googlecolab/colabtools/issues
I wouldn't hold my breath for a quick response though :(

**Comment by francesco-ballarin** [comment]
(the link is still the same as the opening post)

**Comment by banesullivan** [comment]
Aha!! That's excellent! It's at least connecting to the port now! I'll toy with what you did and see if I can get it working

**Comment by banesullivan** [comment]
`output.serve_kernel_port_as_iframe` looks like exaclty what we want to use but indeed, the output is always empty... 😕

**Comment by francesco-ballarin** [comment]
got one step closer: there is an overload of that function in which you can pass the path, which for us is something like `"index.html?ui=P_0x7fd70f6416a0_0&reconnect=auto"`. With that `output.serve_kernel_port_as_iframe` displays the same "Connection error" as the image above

**Comment by banesullivan** [comment]
Made some progress with:

```py
from trame.app import get_server
from IPython import display

pl = pv.Plotter(notebook=True)
pl.add_mesh(mesh, color='lightgrey')
widget = pl.show(return_viewer=True)
widget.viewer

path = f'index.html?ui={widget.viewer.plotter._id_name}&reconnect=auto'

server = get_server(pv.global_theme.trame.jupyter_server_name)

output.serve_kernel_port_as_iframe(server.port, path=path)
```
<img width="1483" alt="Screen Shot 2023-01-29 at 6 34 30 PM" src="https://user-images.githubusercontent.com/22067021/215369748-d6b51867-b908-4224-9d92-ae6efec3b365.png">


Problem is the websocket communication seems blocked...

**Comment by francesco-ballarin** [comment]
> Problem is the websocket communication seems blocked...
Is https://github.com/googlecolab/colabtools/issues/2529 relevant? (if so,  that is bad news)

**Comment by banesullivan** [comment]
Yep... that looks like a blocker for us...

Though, if I remember correctly, ImJoy might use websocket for communication and `itkwidgets` was able to everything working in a very similar manner to this on Colab using ImJoy. (ImJoy and wslink are synonymous). 

Maybe we can learn something from: https://github.com/imjoy-team/imjoy-rpc/blob/master/python/imjoy_rpc/connection/colab_connection.py

**Comment by francesco-ballarin** [comment]
@jourdain thanks, it would be great if you had a look. The link to the notebook on Colab is https://colab.research.google.com/drive/1608zRoubwfN2KgTRcEk5hOq3tQJSF0XQ?usp=sharing (same as in the opening post, but reposted here for your ease), and already contains the updates from the 20 comments in this discussion.

**Comment by francesco-ballarin** [comment]
> Maybe we can learn something from: https://github.com/imjoy-team/imjoy-rpc/blob/master/python/imjoy_rpc/connection/colab_connection.py

I have tested the notebook linked in the original PR https://github.com/imjoy-team/imjoy-rpc/pull/54 and can confirm it still works. Still, I am not much knowledgeable in websocket, imjoy or wslink to understand where the actual trick is :(

**Comment by jourdain** [comment]
So looking at it quickly, Google Colab seems to not have any WebSocket connection at all. They use `socket.io` in long polling mode... So out of the box, trame will not work in such setup. I guess I'll have to dig deeper on imjoy to see if we can rely on that communication layer.

**Comment by banesullivan** [comment]
Thanks for taking a look!

**Comment by jourdain** [comment]
So after browsing ImJoy a little bit more, I don't see a quick path. I'm not saying it is not possible, but either way it will take sometime to figure out a solution while properly integrating it into the full stack.

**Comment by banesullivan** [comment]
I want to cross-post from https://github.com/pyvista/pyvista/issues/313#issuecomment-1820128071 with an update about the new embeddable backend coming in https://github.com/pyvista/pyvista/pull/5168 (this is effectively exporting the scene, so very limited compared to our default backend)

**Comment by francesco-ballarin** [comment]
Thanks @banesullivan , I am looking forward to seeing #5168 merged and included in the next release. I'll test it out afterwards on Colab.

Can you expand on "very limited"? From the second post there, at least the user can interact with the plot, which is still better than nothing and could work well for (my) basic needs :)
