### ISSUE TITLE
Clipping planes issues when camera set before mesh added

### ISSUE THREAD

**Issue by AlexanderJuestel** [pyvista/pyvista#3866]
### Describe the bug, what's wrong, and what you expected.

When trying to plot one of my meshes within a Jupyter notebook or within a new window, the first screen that appears is just white. I can at least get an image in the interactive window when I start rotating the model. However, I cannot take proper screenshots. 

### Steps to reproduce the bug.

```python

import pyvista as pv

sargs = dict(
    n_labels=4,
    fmt="%.2f",
    color='black',
    title_font_size=36,
    label_font_size=28,
)

mesh_mittlerer_kohlenkalk = pv.read('03_Base_Kohlenkalk.vtk')

p = pv.Plotter(notebook=True)
p.camera_position =[(32296547.031916864, 5604180.621483791, 37669.91989055014),
 (32306743.116174523, 5629525.126203569, -2489.703491812879),
 (0.118242938013253, 0.8259174095389241, 0.5512522473700286)]

p.add_mesh(mesh_mittlerer_kohlenkalk, cmap='gist_earth', clim=[-2000,400], scalar_bar_args=sargs)

p.set_background('white')
p.show_grid(color='black')
p.show()
```
[Mesh.zip](https://github.com/pyvista/pyvista/files/10487267/Mesh.zip)

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Tue Jan 24 08:32:27 2023 Mitteleuropäische Zeit

                OS : Windows
            CPU(s) : 16
           Machine : AMD64
      Architecture : 64bit
               RAM : 15.2 GiB
       Environment : Jupyter
        GPU Vendor : ATI Technologies Inc.
      GPU Renderer : AMD Radeon(TM) Graphics
       GPU Version : 4.5.14761 Core Profile Context 21.30.40.09 30.0.13040.9001

  Python 3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 08:41:22) [MSC
  v.1929 64 bit (AMD64)]

           pyvista : 0.37.0
               vtk : 9.2.5
             numpy : 1.21.0
           imageio : 2.24.0
            scooby : 0.7.0
             pooch : v1.6.0
        matplotlib : 3.6.2
             PyQt5 : 5.15.7
           IPython : 8.8.0
             scipy : 1.10.0
              tqdm : 4.64.1
            meshio : 4.4.6
--------------------------------------------------------------------------------
```

### Screenshots

New Window
![image](https://user-images.githubusercontent.com/45469915/214234898-0bde4a9f-4383-4f1a-be2b-4b4a39a3f8b3.png)

Jupyter Notebook
![image](https://user-images.githubusercontent.com/45469915/214234982-6ab2f898-d50f-40f3-85ae-b2374eb36c80.png)

**Comment by banesullivan** [comment]
This is because you set the camera position before adding data to the scene. When you set that camera position, there is no data in the scene, so the clipping range of the camera is not going to be very tiny and not work when you add data with a largish extent.

To avoid this, either set the camera position after adding data to the scene or call `p.renderer.camera.reset_clipping_range()` after adding the data and before the `show()` call.

To be fair, we could (maybe should) have a call to `reset_clipping_range()` during `add_actror()`, but this might have consequences and IMO, the camera position should just be set after data are added

**Comment by AlexanderJuestel** [comment]
@banesullivan, that certainly solves the issue. It is mostly the being in front of the computer, right :D 

Thanks a lot!
