### ISSUE TITLE
Trame viewer UI buttons only work for active renderer

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#3880]
### Describe the bug, what's wrong, and what you expected.

Try out `examples_trame/basic/multi_views.py` and notice that the UI buttons only work for the last active renderer on the subplot. 

We may want to add a mechanism so that the buttons apply to all renderers.

### Steps to reproduce the bug.

```bash
python examples_trame/basic/multi_views.py
```

### System Information

```shell
latest
```

**Comment by psavery** [comment]
I just gave this a try, and it appears that the buttons are applying to all renderers. Was this issue fixed?

**Comment by banesullivan** [comment]
Ah, yep. I fixed this in https://github.com/pyvista/pyvista/pull/3983
