### ISSUE TITLE
add_ruler allow user to set text color and tick color

### ISSUE THREAD

**Issue by chen112p** [pyvista/pyvista#3888]
### Describe the feature you would like to be added.

I found plotter.add_ruler function pretty useful lately. unfortunately it doesnt allow user to modify the color of ticks and texts. It would be very useful it can be added in the next release.
https://docs.pyvista.org/api/plotting/_autosummary/pyvista.Plotter.add_ruler.html
Thanks

### Pseudocode or Screenshots

```python
Insert code here
```
Or drag your screenshot here!

**Comment by banesullivan** [comment]
Done in #3716

**Comment by chen112p** [comment]
> Done in #3716
wow speedy response... thanks a lot

**Comment by banesullivan** [comment]
I was working on this already 😉 

FYI, there seems to be a bug in VTK where setting the color at all forces it to be black. So it looks like the color can either be white or black. Setting to anything other than white will set it to black.
