### ISSUE TITLE
No serializer Error when plot in Jupyter Notebook

### ISSUE THREAD

**Issue by Jimmy-KL** [pyvista/pyvista#3895]
### Describe the bug, what's wrong, and what you expected.

When plotting a model in Jupyter Notebook, the plotting is ok, but there is an error message.
`!!!No serializer for vtkActor2D with id 00000228e1a8f860
      !!!No serializer for vtkAxesActor with id 00000228e1c46000
      !!!No serializer for vtkActor2D with id 00000228e1a8f860
      !!!No serializer for vtkAxesActor with id 00000228e1c46000`

### Steps to reproduce the bug.

Update pyvista to the latest main branch and plot any model in Jupyter Notebook.
```
import pyvista as pv
mesh = pv.Sphere()
mesh.plot()
```

### System Information

```shell
OS : Windows
            CPU(s) : 16
           Machine : AMD64
      Architecture : 64bit
       Environment : Python
        GPU Vendor : Intel
      GPU Renderer : Intel(R) UHD Graphics
       GPU Version : 4.5.0 - Build 31.0.101.1999

  Python 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit
  (AMD64)]

           pyvista : 0.38.dev0
               vtk : 9.1.0
             numpy : 1.22.0
           imageio : 2.22.0
            scooby : 0.5.12
             pooch : v1.6.0
        matplotlib : 3.6.3
           IPython : 8.0.1
          colorcet : 3.0.1
        ipyvtklink : 0.2.3
             scipy : 1.7.3
            meshio : 5.3.4
         pythreejs : Version unknown
             trame : 2.2.6
      trame_client : 2.5.1
      trame_server : 2.8.1
         trame_vtk : 2.0.16
```

### Screenshots

![Dingtalk_20230129001510](https://user-images.githubusercontent.com/114913030/215277171-5777ed28-17df-4c9f-b152-58cf9f4d7657.jpg)

**Comment by banesullivan** [comment]
The `.plot()` method adds an axes actor by default (`show_axes=True`) : https://dev.pyvista.org/api/core/_autosummary/pyvista.DataSet.plot.html#plot

That axes widget is not serializable/convertible to VTK.js. The default trame Jupyter backend has both server- and client-side rendering modes simultaneously. The client mode can't display that axes widget. Hence the error message.

These errors were `print` statements in VTK directly prior to version 9.2.5. I fixed this upstream in VTK to use logging in https://gitlab.kitware.com/vtk/vtk/-/merge_requests/9766

In PyVista, we suppress that logging, so they do not appear in Jupyter:

https://github.com/pyvista/pyvista/blob/86d7356aa60e7ffd22a6905c531588e5ac833240/pyvista/trame/jupyter.py#L86-L91

Please update to VTK 9.2.5 for the best experience using trame and PyVista
