### ISSUE TITLE
Make point-merging behavior of `PolyDataFilters.merge()` consistent with `MultiBlock.combine()` and `DataSetFilters.merge()`

### ISSUE THREAD

**Issue by whophil** [pyvista/pyvista#3920]
### Describe the feature you would like to be added.

Currently, `MultiBlock.combine()` and `DataSetFilter.merge()` use `vtkAppendFilter`'s built-in point merging when point merging is requested. In contrast, `PolyDataFilters.merge()` delegates the point-merging to `vtkCleanPolyData`, which is considerably slower for large meshes.

Performance differences aside, since all of these are using `vtkAppendFilter` under the hood, I would expect the behavior to be consistent.

See performance numbers below for a simple test case.

```python
import pyvista as pv
import time

s = pv.Sphere(theta_resolution=2000, phi_resolution=2000)
h1 = s.clip(normal='x', invert=False)
h2 = s.clip(normal='x', invert=True)

t0 = time.time()
r = pv.MultiBlock([h1, h2]).combine(merge_points=True)
print('MultiBlock.combine():', time.time() - t0)

t0 = time.time()
r = h1.cast_to_unstructured_grid().merge(h2, merge_points=True)
print('UnstructuredGrid.merge():', time.time() - t0)

t0 = time.time()
r = h1.merge(h2, merge_points=True)
print('PolyData.merge():', time.time() - t0)
```

Outputs:
```
MultiBlock.combine(): 1.3390300273895264
UnstructuredGrid.merge(): 1.6437718868255615
PolyData.merge(): 9.812441110610962
```

**Comment by whophil** [comment]
Correction - 

`PolyDataFilters.merge()` actually does _not_ use `vtkAppendFilter`, it uses `vtkAppendPolyDataFilter`, which does **not** have any point merging built in like `vtkAppendFilter` does.

Given that, I don't know if there's anything left to really change here. It's certainly unintuitive that `PolyDataFilters.merge(merge_points=True)` and `DataSetFilters.merge(merge_points=True)` have such drastically difference performance - an **hour** in my use case - but given the current state of VTK filters, I don't know what else can be done.

For my use case, the workaround is to cast PolyData -> UnstructuredGrid, then `merge()`, and then to extract a PolyData again.

CC @akaszynski @adeak whose names appear in this filter's blame.

**Comment by banesullivan** [comment]
I have a suspicion that somewhere under the hood in VTK, the clean operation on the UnstructredGrid is happening with a VTKm filter (why its so much faster)... perhaps https://vtk.org/doc/nightly/html/classvtkmCleanGrid.html

This is just a hunch, though... I haven't looked at any of this code

**Comment by banesullivan** [comment]
@whophil, what version of VTK are you using and is it the conda build?

**Comment by whophil** [comment]
> @whophil, what version of VTK are you using and is it the conda build?

The original benchmarks were using VTK 9.2.2 from conda-forge, but I just bumped up to VTK 9.2.5 from conda-forge and got roughly the same performance.

**Comment by whophil** [comment]
Other findings - [vtkAppendDataSets](https://vtk.org/doc/nightly/html/classvtkAppendDataSets.html) seems to be a front-end of sorts for appending unstructured and poly data.

- vtkAppendFilter [implements its own point merging tree algorithm](https://gitlab.kitware.com/vtk/vtk/-/blob/ac57bc6cda04b0c71f791c797fe6f315f8843e66/Filters/Core/vtkAppendFilter.cxx#L245-272)
- vtkAppendDataSets [delegates to either vtkAppendFilter or vtkAppendPolyData](https://gitlab.kitware.com/vtk/vtk/-/blob/ac57bc6cda04b0c71f791c797fe6f315f8843e66/Filters/Core/vtkAppendDataSets.cxx#L121-187) depending on the desired OutputModeDataSetType
