### ISSUE TITLE
Pyvista with Trame backend for jupyter-book

### ISSUE THREAD

**Issue by jorgensd** [pyvista/pyvista#3932]
### Describe the bug, what's wrong, and what you expected.

With all jupyter backends but `trame` being deprecated, I'm no longer certain there is any way of generating interactive plots in 
`jupyter-book`.

Trame is not able to show the plots interactively in the jupyter-book, as opposed to `panel`, `pythreejs` and `ipygany`.
It would be a shame if this functionality disappears, as I heavily rely on this in my projects.

### Steps to reproduce the bug.

I've made a minimal github repository: https://github.com/jorgensd/jupyter-book_trame
which builds a one-page jupyter-book with pyvista as the plotting backend.
Artifacts for each backend are available at: 
https://github.com/jorgensd/jupyter-book_trame/actions/runs/4065602894

### System Information

```shell
Reports for each build is available in each artifact
https://github.com/jorgensd/jupyter-book_trame/actions/runs/4065602894
```

### Screenshots

# Trame
![image](https://user-images.githubusercontent.com/8554300/216075265-c3357e45-b984-4808-8e6e-a153716f2720.png)
# Panel
![image](https://user-images.githubusercontent.com/8554300/216075430-d73a7126-8448-4c4b-8a82-5d6fd80e4b43.png)

**Comment by banesullivan** [comment]
This is because the Trame backend requires a live kernel. 

We will have the ability to statically embed the client view in the next release (0.39). This is tracked by #2475

**Comment by jorgensd** [comment]
Thanks for the update. I guess I will stick with `panel` for now (on pyvista 0.37, and 0.38 once released). Feel free to close the issue since its already tracked
