### ISSUE TITLE
lines_from_points fails with odd number of points

### ISSUE THREAD

**Issue by AndrewAnnex** [pyvista/pyvista#394]
**Describe the bug, what's wrong, and what you expect:**

It appears that lines_from_points function fails when presented an odd number of points in a line, specifically a value error from numpy, such as what I get below from the code below:

```
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 1 and the array at index 2 has size 2
```
-----

**To Reproduce**

```py
# Insert code here
import pyvista
import numpy
pyvista.lines_from_points(numpy.array([[0, 0, 0], [1, 0, 0], [1, 0, 0]]))
```

**Screenshots**

-----

**System Information:**
 Please run the following code wherever you are experiencing the bug and paste the output below. This report helps us track down bugs and it is critical to addressing your bug:

```py
# Get system info
import pyvista as pv
print(pv.Report())
```

```txt
--------------------------------------------------------------------------------
  Date: Tue Oct 08 21:02:33 2019 EDT

            Darwin : OS
                 8 : CPU(s)
            x86_64 : Machine
             64bit : Architecture
           16.0 GB : RAM
           IPython : Environment

  Python 3.7.3 (default, Mar 27 2019, 09:23:15)  [Clang 10.0.1
  (clang-1001.0.46.3)]

            0.22.2 : pyvista
             8.1.2 : vtk
            1.17.0 : numpy
             2.5.0 : imageio
             1.4.3 : appdirs
             0.4.3 : scooby
             3.1.1 : matplotlib
            5.11.2 : PyQt5
             7.0.1 : IPython
             7.4.2 : ipywidgets
             1.0.0 : colorcet
--------------------------------------------------------------------------------

```

**Comment by akaszynski** [comment]
Just ran into this issue as well.

**Comment by banesullivan** [comment]
Yeah, this was my bad... @akaszynski is this what we were talking about a while back?

**Comment by banesullivan** [comment]
Or wait, no. This is working as I intended, albeit not well and documented poorly. The `lines_from_points` function available in the PyVista utilities module is designed to handle explicit creation of line segments - thus an even number of points must be given as it makes non-connected segments.

If you want connected segments then check out the various options I added in [this example](https://docs.pyvista.org/examples/00-load/create-spline.html#sphx-glr-examples-00-load-create-spline-py) and specifically this additional helper in that example which is more in line with what you want:

```py
import pyvista
import numpy as np

def lines_from_points(points):
    """Given an array of points, make a line set"""
    poly = pv.PolyData()
    poly.points = points
    cells = np.full((len(points)-1, 3), 2, dtype=np.int)
    cells[:, 1] = np.arange(0, len(points)-1, dtype=np.int)
    cells[:, 2] = np.arange(1, len(points), dtype=np.int)
    poly.lines = cells
    return poly

pts = np.array([[0, 0, 0], [1, 0, 0], [1, 0, 0]])
lines_from_points(pts)
```

**Comment by banesullivan** [comment]
@akaszynski, should we update that helper method in the `utilities` module to that function? And should we add the other helpers I have in that spline example to the utilities module?

I still think the current implementation of `pyvista.lines_from_points` is very useful, we may just need to add better error messages and description.

**Comment by akaszynski** [comment]
I think adding a better error message and pointing the user to the right function would be the best way to go.

It’s true the original function was a bit messy and the current implementation is good.  Though we should still provide a way of converting an odd number of points to a line.

**Comment by banesullivan** [comment]
What if we rename the current function to `line_segements_from_points` and add the needed error messages, then add the method I shared in the comment above as the `lines_from_points` method as it is a bit more robust and likely what most folks are looking for

**Comment by akaszynski** [comment]
Agreed.  That's much clearer.
