### ISSUE TITLE
Missing docs for Plotter inherited classes

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#3956]
We are missing docs for the base classes of `BasePlotter`:

- `PickingHelper`
- `WidgetHelper`

We should consider making an exception to the exclusion of inherited methods specifically for the `Plotter` class.

**Comment by larsoner** [comment]
And `add_scalar_bar` etc. according to recent MNE-Python failures

https://app.circleci.com/pipelines/github/mne-tools/mne-python/17761/workflows/1edc2bad-44dc-4364-ae43-d473a14d1929/jobs/52035?invite=true#step-140-2022
