### ISSUE TITLE
Matplotlib should be a hard requirement

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#3970]
So much of PyVista's plotting API depends on Matplotlib for colormaps and color cyclers. Many features are unsafely failing without MPL installed.

Considering how much PyVista leverages MPL and how prevalent MPL is in just about any Python environment (think ParaViewPython) and how easy it is to install, I think there would be minimal impact adding it as a hard requirement.

Up to this point, MPL has been a soft dependency but treated implicitly as a hard dependency. We should just go all out and make it a hard requirement

**Comment by banesullivan** [comment]
An alternative to this is to isolate the usage of MPL and guarantee that it is not a hard requirement. I'm open to either route here but leaning towards the easier solution of just requiring it.

**Comment by adeak** [comment]
> Up to this point, MPL has been a soft dependency but treated implicitly as a hard dependency. 

I'm surprised to hear that because I always thought that we've done a really good job of keeping it optional, and looking at `git grep matplotlib 'pyvista/*.py'` seems to support this. I agree with the conclusion though, especially since VTK depends on matplotlib now.

**Comment by banesullivan** [comment]
>  I always thought that we've done a really good job of keeping it optional,

Mostly we have and this was my general impression as well. However, I remember running into so issues were using the majority of PyVista would fail without matplotlib installed -- if we truly left it optional, then all of the "matplotlib is not installed" errors would default out to some native VTK mechanism -- which we do not do
