### ISSUE TITLE
PyPI Development Status

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#3975]
I just noticed that PyVista is listed as "Beta"... should we update this to `Development Status :: 5 - Production/Stable`? We're still sub version `1.x` (arbitrarily) so I guess "Beta" fits, but IMO does not reflect how PyVista is being used.

https://github.com/pyvista/pyvista/blob/bdb60e1f7ff8872ba9073d194825aa9c1726ced7/pyproject.toml#L16

ref https://pypi.org/classifiers/

**Comment by akaszynski** [comment]
Looking back to Scipy's releases, there's [scipy==0.19.1](https://pypi.org/project/scipy/0.19.1/), which was right before their 1.0.0 release.

We can remove this take and just make it "stable". It's "stable enough".

I'd also like to see a `v1.0` release by the end of the year. We're vectored for it and our API has been, for the most part, stable for the past year. That might change though, so maybe we should consider our "roadmap" for the next year and beyond and determine if we really will be stable.
