### ISSUE TITLE
Trame widget timeout issues on remote server

### ISSUE THREAD

**Issue by dannymcculloch** [pyvista/pyvista#3979]
### Describe the bug, what's wrong, and what you expected.

So I'm trying to run the [compute normals ](https://docs.pyvista.org/examples/01-filter/compute-normals.html#sphx-glr-examples-01-filter-compute-normals-py)example on a headless display. I run Jupyter with `jupyter lab --no-browser --port=1234` on the host machine then connect with `nohup ssh -NL localhost:1234:localhost:1234 HOSTMACHINE@IP`. Before the addition of `trame` Pyvista did not work with any 3D rendering with this setup ([host machine doesn't have xvfb](https://github.com/pyvista/pyvista/issues/177)), but I thought to try it out now with the new backend. I **can** now run the other examples such as [clipping with a surface](https://docs.pyvista.org/examples/01-filter/clipping-with-surface.html#sphx-glr-examples-01-filter-clipping-with-surface-py) or [surface reconstruction](https://docs.pyvista.org/examples/01-filter/surface_reconstruction.html#sphx-glr-examples-01-filter-surface-reconstruction-py) with a 3D interface (yay!), but both examples in the compute normals page result in the connection being terminated. This error occurs before doing the `mesh.compute_normals` command in the example, but just when plotting the base example mesh. The error also occurs when running the `nefertiti` example on the same page, so I'm not sure if its an issue with these particular examples or something more sinister. The pyvista window alternates between a blank page (with only the options bar for moving the 3d interface around) to the "connection closed" as shown in the screenshot, alternating after ~1 second. It then repeats the error message below of 

> WARNING:aiohttp.websocket:Client protocols [''] don’t overlap server-known ones ()
ERROR:root:Exception raised
ERROR:root:ConnectionResetError(104, 'Connection reset by peer')
ERROR:root:Traceback (most recent call last):
  File "/home/dm575/miniconda3/lib/python3.9/site-packages/wslink/backends/aiohttp/__init__.py", line 501, in onMessage
    await self.sendWrappedMessage(
  File "/home/dm575/miniconda3/lib/python3.9/site-packages/wslink/backends/aiohttp/__init__.py", line 638, in sendWrappedMessage
    await ws.send_bytes(attachments[key])
  File "/home/dm575/miniconda3/lib/python3.9/site-packages/aiohttp/web_ws.py", line 315, in send_bytes
    await self._writer.send(data, binary=True, compress=compress)
  File "/home/dm575/miniconda3/lib/python3.9/site-packages/aiohttp/http_websocket.py", line 688, in send
    await self._send_frame(message, WSMsgType.BINARY, compress)
  File "/home/dm575/miniconda3/lib/python3.9/site-packages/aiohttp/http_websocket.py", line 659, in _send_frame
    await self.protocol._drain_helper()
  File "/home/dm575/miniconda3/lib/python3.9/site-packages/aiohttp/base_protocol.py", line 87, in _drain_helper
    await asyncio.shield(waiter)
  File "/home/dm575/miniconda3/lib/python3.9/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/home/dm575/miniconda3/lib/python3.9/asyncio/tasks.py", line 328, in __wakeup
    future.result()
  File "/home/dm575/miniconda3/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/home/dm575/miniconda3/lib/python3.9/asyncio/selector_events.py", line 941, in _write_ready
    n = self._sock.send(self._buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

TIA for any help! 

### Steps to reproduce the bug.

```
import pyvista as pv
import numpy as np
from pyvista import examples

pv.global_theme.trame.server_proxy_enabled = True
pv.set_jupyter_backend("client")

mesh = examples.download_topo_global()
mesh.plot(cmap="gist_earth", show_scalar_bar=False, notebook=True)
```

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Wed Feb 08 11:07:34 2023 GMT

                  OS : Linux
              CPU(s) : 72
             Machine : x86_64
        Architecture : 64bit
                 RAM : 157.3 GiB
         Environment : Jupyter
         File system : ext4
         GPU Details : error

  Python 3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 15:55:03)
  [GCC 10.4.0]

             pyvista : 0.38.1
                 vtk : 9.2.5
               numpy : 1.24.2
             imageio : 2.25.0
              scooby : 0.7.1
               pooch : v1.6.0
          matplotlib : 3.6.3
               PyQt5 : 5.15.7
             IPython : 8.9.0
          ipyvtklink : 0.2.2
               scipy : 1.7.1
                tqdm : 4.64.1
              meshio : 5.3.4
          jupyterlab : 3.4.4
           pythreejs : 2.3.0
               trame : 2.2.6
        trame_client : 2.5.1
        trame_server : 2.8.1
           trame_vtk : 2.0.17
jupyter_server_proxy : 3.2.2
--------------------------------------------------------------------------------
```

### Screenshots

![image](https://user-images.githubusercontent.com/74662033/217512617-16606f48-d8dc-481d-90c8-80e167245b5b.png)

cc @dennissergeev who is also interested in this!

**Comment by banesullivan** [comment]
I'm able to reproduce... I think I know what's happening and will try to have a patch as soon as I can

**Comment by dennissergeev** [comment]
Many thanks for the quick reply @banesullivan!

**Comment by banesullivan** [comment]
Well, I thought I had a lead on what was causing this... having a bit of trouble tracking it down now. This may not get fixed immediately

**Comment by banesullivan** [comment]
So, we tracked this down to a network timeout issue with `jupyter-server-proxy`. I need to investigate if we can easily increase that limit to prevent this issue.

If you have control over the host machine and access to arbitrary ports, you could do something like this:

```py
import os
os.environ['TRAME_DEFAULT_HOST'] = 'mydomain.com'

import pyvista as pv

pv.global_theme.trame.server_proxy_enabled = True
pv.global_theme.trame.server_proxy_prefix = 'http://mydomain.com:'
```

This allows you to avoid jupyter-server-proxy and communicate directly with the open port on the machine. I'm currently doing this on a remote server I have and it fixes the issue.

**Comment by dannymcculloch** [comment]
Awesome, I'll give this a test tomorrow. Thanks for the quick fix @banesullivan!

**Comment by dannymcculloch** [comment]
Not sure about what `proxy_prefix` is trying to achieve, is that linking to the local port or to the domain that I SSH into?
e.g. 
1. `pv.global_theme.trame.server_proxy_prefix = 'localhost:PORT'`
2. `pv.global_theme.trame.server_proxy_prefix = 'USERNAME@HOSTMACHINE.com'`

**Comment by banesullivan** [comment]
Go with option 2. This is the URL prefix used in your web browser to connect to the remote host.

**Comment by banesullivan** [comment]
`username@` is not needed when accessing an exposed port

**Comment by dannymcculloch** [comment]
So getting a new error now, this one looks more familiar. I connect to Jupyter via `localhost:8892`, might this be because its assuming a specific port which I'm not specifying?
![image](https://user-images.githubusercontent.com/74662033/218437777-2fa29fcd-6081-493d-8e9e-f5f9dff5daaf.png)

**Comment by banesullivan** [comment]
try `host_address = "mydomain.ak.uk:` with the colon so that the port is properly mapped. 

Otherwise, can you inspect the `src` URL of the widget:

```py
p = pv.Plotter()
p.add_mesh(mesh)
viewer = p.show(return_viewer=True)
print(viewer.src)
viewer
```

**Comment by dannymcculloch** [comment]
Tried with a `:`, now just gets a blank image (but at least no errors!)
![image](https://user-images.githubusercontent.com/74662033/218502432-6ae36158-611e-4b8a-82f9-9a56919e9a18.png)

**Comment by banesullivan** [comment]
That's better! Have you tried clicking/interacting with the white space?

**Comment by banesullivan** [comment]
Can you use the dev tools and network tab to see if anything under the `ws` group is failing?

**Comment by dannymcculloch** [comment]
White space is not interactive. RE: dev tools, not sure if I have permission, whats the command?

**Comment by dannymcculloch** [comment]
This is from the Jupyter output (where I ran `jupyter lab`). So it is trying to do _something_ with `ws`.
![image](https://user-images.githubusercontent.com/74662033/218504126-7b96d6d9-353a-4800-9cdc-a2b0eb21f301.png)

**Comment by banesullivan** [comment]
Are you sure that's recent? You're no longer using Jupyter server proxy.

Re dev tools: https://developer.chrome.com/docs/devtools/network/

**Comment by dannymcculloch** [comment]
That's what is showing up when I run the cell I posted before, from the terminal where I ran `jupyter lab --no-browser --port=8892`. Could it be that it's not properly redirecting it via the server proxy?

**Comment by banesullivan** [comment]
Ah. I see now that you're using the same `host_address` variable for `TRAME_DEFAULT_HOST` and the `server_proxy_prefix`. These need to be different.

We just release pyvista 0.38.2 which makes this a little bit better. Please try:

```py
import pyvista as pv
from pyvista.trame.jupyter import elegantly_launch, launch_server

host_address = "mydomain.ac.uk"

pv.global_theme.trame.server_proxy_enabled = True
pv.global_theme.trame.server_proxy_prefix = f"{host_address}:"

# Needs PyVista 0.38.2
elegantly_launch(host=host_address)
# or:
# await launch_server(host=host_address).ready

pv.set_jupyter_backend('trame')  # it's the default, so not totally needed

...

pv.Cone().plot()
```

**Comment by dannymcculloch** [comment]
So this is now resolved - turns out that the amount of data being sent via the `ssh` and port forwarding was too much for the renderer and the Jupyter lab. The fix was to set the 3D renderer in Jupyter to display from a different port and then port forward to that port as well. 
Schematic of the problem:
![image](https://user-images.githubusercontent.com/74662033/219061049-140510c8-067a-4cd0-98ec-333a25c06587.png)
Schematic of the fix:
![image](https://user-images.githubusercontent.com/74662033/219061202-39b5abc8-e41c-4476-9799-99704bb9fe1d.png)

Code:
```
import os
os.environ['TRAME_DEFAULT_HOST'] = host_address

import pyvista as pv
import numpy as np
from pyvista import examples
from pyvista.trame.jupyter import elegantly_launch, launch_server

elegantly_launch(host_address)
# or:
# await launch_server(host_address).ready

pv.global_theme.trame.server_proxy_enabled = True
pv.global_theme.trame.server_proxy_prefix = f"{host_address}:"

pv.set_jupyter_backend("client")

mesh = examples.download_topo_global()
p = pv.Plotter(notebook = True)
p.add_mesh(mesh)
viewer = p.show(return_viewer = True)
print(viewer.src)
viewer
```

**Comment by banesullivan** [comment]
Thanks for the follow up! But didn't you map a port on your localhost to the port on the remote machine you ssh'd into? Could you provide general commands to do that sort of port forwarding?

**Comment by dannymcculloch** [comment]
So I used another server to jump to the host. 
The command from my PC:
`ssh -NL localhost:8892:localhost:8892 USERNAME@FIRSTSERVER.COM`
The command from the jump server
`ssh -NL localhost:8892:localhost:8892 USERNAME@SECONDSERVER.COM`
This forwards the port `8892` which is running Jupyter on the server side. 
Essentially, I just repeat that but with a different port for the 3D renderer.

**Comment by ggrrll** [comment]
> pv.global_theme.trame.server_proxy_enabled = True

mind that in v. 0.39.0 that raises an error as it's read-only 

I use `pv.themes._TrameConfig.server_proxy_enabled = True`

**Comment by banesullivan** [comment]
@ggrrll, that should definitely not be the case and I'm unable to reproduce. Would you please open a new bug report on the read-only error you are facing with a stack trace and `pyvista.Report()`?

**Comment by ggrrll** [comment]
I don't what happened yesterday -- now it is working (able to assign True value)
