### ISSUE TITLE
`add_mesh_slice_orthogonal` turns grey on move

### ISSUE THREAD

**Issue by prisae** [pyvista/pyvista#400]
**Describe the bug, what's wrong, and what you expect:**

(This is a carry-over from Slack discussions on the PyVista and SimPEG workspaces.)

Using the new widget feature `add_mesh_slice_orthogonal`, the slices turn grey as soon as they are moved.

Casting the dataset or removing the clipping resolves the issue.

Might be related to 
- https://github.com/pyvista/pyvista/issues/111
- https://github.com/pyvista/pyvista/pull/263

-----

**To Reproduce**

The dataset is from the example at https://github.com/empymod/emg3d-examples/blob/master/2a_SEG-EAGE_3D-Salt-Model.ipynb (the coarse model). The original dataset is licensed CC By 4.0, Society of Exploration Geophysicists, see https://wiki.seg.org/wiki/SEG/EAGE_Salt_and_Overthrust_Models.

You have to extract the following zip to get the data file:
[data.zip](https://github.com/pyvista/pyvista/files/3710816/data.zip)

The following fails:
```py
import pyvista as pv 
  
mesh = pv.read("./data.vtk") 
mesh = mesh.clip("z", origin=(0,0,0)) 
  
p = pv.Plotter(notebook=0) 
p.add_mesh_slice_orthogonal(mesh) 
p.show_grid() 
p.show()     
```
![Peek 2019-10-10 08-40](https://user-images.githubusercontent.com/8020943/66545072-2dc49800-eb3a-11e9-82df-320d21d313d7.gif)

Not clipping works fine:
```py
import pyvista as pv 
  
mesh = pv.read("./data.vtk") 
  
p = pv.Plotter(notebook=0) 
p.add_mesh_slice_orthogonal(mesh) 
p.show_grid() 
p.show()     
```
![Peek 2019-10-10 08-42](https://user-images.githubusercontent.com/8020943/66545122-5056b100-eb3a-11e9-812a-2ab8e18b0c68.gif)

Casting it to float again (it is already float) also works:
```py
import pyvista as pv 
  
mesh = pv.read("./data.vtk") 
mesh["res"] = mesh["res"].astype(float) 
mesh = mesh.clip("z", origin=(0,0,0)) 
  
p = pv.Plotter(notebook=0) 
p.add_mesh_slice_orthogonal(mesh) 
p.show_grid() 
p.show()     
```
![Peek 2019-10-10 08-43](https://user-images.githubusercontent.com/8020943/66545159-62385400-eb3a-11e9-84ef-e7b819e0eeca.gif)

-----

**System Information:**
```
--------------------------------------------------------------------------------
  Date: Thu Oct 10 08:30:13 2019 CEST

             Linux : OS
                 4 : CPU(s)
            x86_64 : Machine
             64bit : Architecture
           IPython : Environment

  Python 3.7.4 (default, Aug 13 2019, 20:35:49)  [GCC 7.3.0]

            0.22.2 : pyvista
             8.1.2 : vtk
            1.17.2 : numpy
             2.6.1 : imageio
             1.4.3 : appdirs
             0.4.3 : scooby
             3.1.1 : matplotlib
             5.9.2 : PyQt5
             7.8.0 : IPython

  Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for
  Intel(R) 64 architecture applications
--------------------------------------------------------------------------------
```
It says `pyvista=0.22.2`; it was installed with pip from master on 9th October 2019.

**Comment by banesullivan** [comment]
Awesome, thanks @prisae!

**Comment by banesullivan** [comment]
Now, this is happening to me with another dataset except the whole mesh is turning to the color of the max in the scalar range... I can't figure it out. Casting doesn't help, clipping doesn't help, nothing works. 

Unfortunately, the mesh is too large to upload here
