### ISSUE TITLE
Removing the ipy_tools module

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#402]
Now that we have widgets, I see no reason to keep the `ipy_tools` module around. All of the tools there have better (more efficient/fast/robust) implementations with the new `widgets` module which is far more extensible.

I would like to deprecate (completely remove) the IPython tools in the `ipy_tools` module soon here in favor of the new widgets.

**Anyone feel strongly about this?**

The IPython tools are able to be replaced with:

- `OrthogonalSlicer` -> `.add_mesh_slice_orthogonal()`
- `ManySlicesAlongAxis` -> could be replaced by a callback with the slider widget (solution given in comments of #403)
- `Threshold` -> `.add_mesh_threshold()`
- `Clip` -> `.add_mesh_clip_box()` and `.add_mesh_clip_plane()`
- `Isocontour` -> `.add_mesh_isovalue()` from #403 

This would really help to reduce complexity and help us not maintain these IPython tools which I don't think many people are using anyways. 

Also, the widgets can be used in Qt based plotters or the vanilla `pyvista.Plotter` class and they are not limited to IPython environments.

Removing the module in favor of widgets would close #70 and close #332

**Comment by akaszynski** [comment]
Agreed, less to maintain and more universal.
