### ISSUE TITLE
pl.render() lights the scene with the trame backend and a client mode 

### ISSUE THREAD

**Issue by PBrockmann** [pyvista/pyvista#4030]
### Describe the bug, what's wrong, and what you expected.

Testing the client mode of the trame backend from https://docs.pyvista.org/user-guide/jupyter/trame.html#trame-jupyter,
I have discovered that when I add a plotter render, the scene is clearer.

```
import pyvista as pv
pl = pv.Plotter(window_size=[600,500])
pl.add_mesh(pv.Cone())
pl.show(jupyter_backend='client')
```
gives 
![image](https://user-images.githubusercontent.com/5402758/219074064-1f7eaf5a-5648-4542-b577-1924c90179d2.png)

whereas 
```
import pyvista as pv
pl = pv.Plotter(window_size=[600,500])
pl.add_mesh(pv.Cone())
pl.show(jupyter_backend='client')
pl.render()
```

gives
![image](https://user-images.githubusercontent.com/5402758/219074334-3608b5e3-adf2-4490-9e58-02f3fd94cf6a.png)

Notice the scene that is much more clearer after a ```pl.render()```. Is there a light activated by defauft ?
Tested with pythreejs backend, the scene appears the same way with a pl.render() present or not.

### Steps to reproduce the bug.

```python
Insert code here
```

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Wed Feb 15 16:29:37 2023 CET

                OS : Linux
            CPU(s) : 8
           Machine : x86_64
      Architecture : 64bit
               RAM : 7.5 GiB
       Environment : Jupyter
       File system : ext4
        GPU Vendor : Intel Open Source Technology Center
      GPU Renderer : Mesa DRI Intel(R) UHD Graphics 620 (KBL GT2)
       GPU Version : 4.6 (Core Profile) Mesa 20.0.8

  Python 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:20:04) [GCC
  11.3.0]

           pyvista : 0.38.1
               vtk : 9.2.5
             numpy : 1.23.5
           imageio : 2.25.1
            scooby : 0.7.1
             pooch : v1.6.0
        matplotlib : 3.6.3
             PyQt5 : 5.15.7
           IPython : 8.10.0
             scipy : 1.10.0
              tqdm : 4.64.1
        jupyterlab : 3.6.1
         pythreejs : 2.4.1
             trame : 2.3.1
      trame_client : 2.6.1
      trame_server : 2.9.0
         trame_vtk : 2.0.17
```

**Comment by banesullivan** [comment]
These lighting differences are tracked here: https://github.com/Kitware/trame-vtk/issues/17

**Comment by akaszynski** [comment]
> I hope this client viewer will use VTK/WASM instead of VTK.js solving these sorts of subtle differences... but until then, I doubt this will get fixed

+1000
