### ISSUE TITLE
Error messages when using new `trame` backend and display axes (pyvista v0.38)

### ISSUE THREAD

**Issue by Alexboiboi** [pyvista/pyvista#4038]
### Describe the bug, what's wrong, and what you expected.

Since pyvista v0.38 and the new `trame` jupyter backend I get some annoying warning messages when displaying 3d axes.

### Steps to reproduce the bug.

```python
import pyvista as pv
pl = pv.Plotter()
pl.add_mesh(pv.Sphere())
pl.show_axes() # if commented does not produce error messages
pl.show()
```

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Fri Feb 17 16:16:08 2023 CET

                OS : Darwin
            CPU(s) : 8
           Machine : x86_64
      Architecture : 64bit
       Environment : Jupyter
        GPU Vendor : NVIDIA Corporation
      GPU Renderer : NVIDIA GeForce GT 750M OpenGL Engine
       GPU Version : 4.1 NVIDIA-16.0.13

  Python 3.9.5 (default, May 18 2021, 12:31:01)  [Clang 10.0.0 ]

           pyvista : 0.38.2
               vtk : 9.1.0
             numpy : 1.20.3
           imageio : 2.16.2
            scooby : 0.5.12
             pooch : v1.6.0
        matplotlib : 3.6.3
             PyQt5 : 5.15.7
           IPython : 7.24.1
        ipyvtklink : 0.2.2
        ipywidgets : 8.0.4
             scipy : 1.8.0
              tqdm : 4.62.0
        jupyterlab : 3.6.1
         pythreejs : Version unknown
             trame : Version unknown
      trame_client : 2.7.0
      trame_server : 2.9.1
         trame_vtk : Version unknown
      nest_asyncio : Version unknown
--------------------------------------------------------------------------------
```

### Screenshots

<img width="550" alt="image" src="https://user-images.githubusercontent.com/29252289/219693114-4529c00e-c14d-4857-b390-c7a16e9b46bb.png">

**Comment by banesullivan** [comment]
These messages will go away if you upgrade VTK to 9.2.5+

Prior to that, these were print statements in VTK which we cannot suppress

**Comment by Alexboiboi** [comment]
@banesullivan  Thanks for the prompt response, I guess I can close the issue then ;)

**Comment by Alexboiboi** [comment]
@banesullivan 
One a side note, I wanted to upgrade our `magpylib` docs with the the `trame` backend, but I could not manage to make it work. 
We are using `myst-nb` to build the docs from jupyter notebooks as markdown files but the output remains empty (see https://magpylib.readthedocs.io/en/pyvista-v0.38-deprecations-fixes/examples/examples_30_coil_field_lines.html)

I tried the diferent options listed here but to no avail :(
 https://docs.pyvista.org/user-guide/jupyter/trame.html#jupyter-server-proxy

Do you have any hints?

**Comment by banesullivan** [comment]
I think you're trying to embed the 3D view in your docs? This is not currently implemented but is tracked here: https://github.com/pyvista/pyvista/issues/2475

You can use the `'static'` backend to produce a PNG screenshot that is displayed in your docs.

**Comment by Alexboiboi** [comment]
Yes I want to have an interactive plot and so far it was working, while using `jupyter_backend="panel"` 🤔

**Comment by banesullivan** [comment]
We are not actively supporting the previous panel backend any longer and it has been mark deprecated and planned for removal. 

With that in mind, we do plan to enable static embedding for the new jupyter backend soon.
