### ISSUE TITLE
Remove `_add_row_array` in Table class.

### ISSUE THREAD

**Issue by tkoyama010** [pyvista/pyvista#4051]
### Describe what maintenance you would like added.

I found `_add_row_array` is defined as a closed method. This method is not referenced in the project and the processing content can be handled without this method. I guess we can remove this method.

### Links to source code.

https://github.com/pyvista/pyvista/blob/bd927d6c2c48513c2fe327c6111c1b20d2364ae9/pyvista/core/objects.py#L188-L204

### Pseudocode or Screenshots

None

**Comment by banesullivan** [comment]
Indeed this looks like a leftover artifact from a refactor in the last 4 years. This is safe to remove

**Comment by banesullivan** [comment]
I suspect there are others like it

**Comment by Chaitu-Tatipamula** [comment]
Hey people hi im new out here need some help to get started

**Comment by tkoyama010** [comment]
@Chaitu-Tatipamula Hi. Can I help you?

**Comment by Chaitu-Tatipamula** [comment]
yes..! 
sir

**Comment by tkoyama010** [comment]
@Chaitu-Tatipamula Yes. All you do is delete the above repository. Could you create a PullRequest for it?

**Comment by Chaitu-Tatipamula** [comment]
yes i''ll create it right now..!

**Comment by Chaitu-Tatipamula** [comment]
@tkoyama010 is it done
