### ISSUE TITLE
Documentation:  MultiBlock class does not describe the ways it can be instantiated

### ISSUE THREAD

**Issue by MatthewFlamm** [pyvista/pyvista#413]
Most of the other pyvista data classes have examples that explain the possible ways of instantiating the class like [Rectlinear Grid](https://docs.pyvista.org/core/grids.html#pyvista.RectilinearGrid).  [MultiBlock](https://docs.pyvista.org/core/composite.html#pyvista.MultiBlock) does not have such a set of descriptions.  I had to go to the source code to see the options.

**Comment by banesullivan** [comment]
Thanks for pointing this out! Will fix

**Comment by banesullivan** [comment]
Just added some changes that should give insight into how you can instantiate these objects from lists and dictionaries which will be live at https://docs.pyvista.org/core/composite.html#pyvista.MultiBlock in about 20-30 minutes

**Comment by MatthewFlamm** [comment]
Looks great!
