### ISSUE TITLE
PyVista cannot find module named "vtk" after VTK is installed using cmake

### ISSUE THREAD

**Issue by NamTran838P** [pyvista/pyvista#4144]
### Describe what maintenance you would like added.

I am using Ubuntu 20.04. I installed VTK (EGL mode) with no errors using the instructions and egl.cmake from [https://github.com/banesullivan/vtk-cmake](url). Finally, I ran `pip3 install dist/vtk-*.whl` to install the wheel in the dist folder (screenshot). 

After the installation, using `pip3 freeze`, I can only see vtk_egl being listed, but not vtk itself. Whenever I use PyVista, PyVista will say that it cannot find the module "vtk". Please help me. 

### Pseudocode or Screenshots

![Screenshot from 2023-03-17 15-49-40](https://user-images.githubusercontent.com/26189749/225844792-61ee6284-402f-422f-8006-b16ff888ba38.png)
![2 (2)](https://user-images.githubusercontent.com/26189749/225844808-eb9614a9-c007-4f5e-81a9-e5394372b629.png)
![1 (2)](https://user-images.githubusercontent.com/26189749/225844812-30265edc-ada8-4db9-9a5f-9cf794810b21.png)

**Comment by banesullivan** [comment]
Are you sure the wheel was installed in the same Python viruta env? I suspect `pip != python3` for you. Perhaps try `python3 -m pip install dest/vtk-*.whl`

**Comment by banesullivan** [comment]
> vtk_egl being listed, but not vtk itself.

"vtk_egl" is simply the distribution name, but the package name is still "vtk". So a `pip list` will show it as `vtk-egl`, but you'll import it like `import vtk`.

I suspect the wheel wasn't installed into the correct virtual environment

**Comment by NamTran838P** [comment]
You are right. It recognizes vtk now when I import vtk. Thanks a lot for your help.
