### ISSUE TITLE
Deprecate `inplace` parameter

### ISSUE THREAD

**Issue by tkoyama010** [pyvista/pyvista#4158]
### Describe what maintenance you would like added.

It appears that the inplace parameter has been deprecated in pandas 
(see https://github.com/pandas-dev/pandas/issues/16529). 
Personally, I think PyVista should follow suit. Please let me know your opinion.

> Why is this bad?
Using inplace=True encourages mutation rather than immutable data, which is harder to reason about and may cause bugs. It also removes the ability to use the method chaining style for pandas operations.
>
> Further, in many cases, inplace=True does not provide a performance benefit, as pandas will often copy DataFrames in the background.

[Why You Should Probably Never Use pandas inplace=True](https://towardsdatascience.com/why-you-should-probably-never-use-pandas-inplace-true-9f9f211849e4)

### Links to source code.

```python
mercury.translate((0.0, 0.0, 0.0), inplace=True)
```

### Pseudocode or Screenshots

Use instead:
```python
mercury = mercury.translate((0.0, 0.0, 0.0))
```

**Comment by MatthewFlamm** [comment]
I also prefer the suggested style.  However, we should be sure that that this is mostly a usage convention before doing this.  If there is a memory benefit to `inplace=True` usage, we should not scrap it.

**Comment by akaszynski** [comment]
> If there is a memory benefit to inplace=True usage, we should not scrap it.

I don't think there is. @banesullivan and I wrestled with this for a while and we concluded that there isn't really any memory improvement.

**Comment by adeak** [comment]
This would be a super intrusive API change for those who use the feature, so I'd be careful and try to solicit feedback before going forward with the actual deprecation @tkoyama010. Definitely ask @pyvista/developers and @pyvista/collaborators first to see if they have any critical use cases.

I'd also make sure there aren't any "inplace only" filters left. This issue came up a while back in https://github.com/pyvista/pyvista/pull/1860#issuecomment-980202764 but I don't remember the outcome. I also vaguely remember some opinions  around returning meshes in inplace cases; this sounded like people using inplace. But I can now only find https://github.com/pyvista/pyvista/issues/1296#issuecomment-833893547 that might just be a downstream library's constraint to support inplace (which could be solved by deprecating it).

**Comment by tkoyama010** [comment]
@adeak Thank you for mentions to the developers. I don't communicate much, which is not good for me.
When I converted it using the conversion tool for pandas, I noticed that the `name` variable in `texture_map_to_plane` is only available when `inplace=True`. Reading the source, there is no problem to make it available with `inplace=False`, so maybe the specification should be changed. There may be other arguments that can only be used with `inplace=False`.
https://github.com/pyvista/pyvista/blob/c4cbfdb526a908d6282e4feb202d1f6f266c18ed/pyvista/core/filters/data_set.py#L1752-L1796

**Comment by banesullivan** [comment]
I'm utterly in favor of stripping out things like `inplace`.

With that said, I don't necessarily think we should.

Considering the headache around #1860 (previous and following PRs), I think the in-place operations have gained a good bit of adoption, and it would be a significant burden to users if we deprecated them after working so hard to make them stable and consistent.

**Comment by akaszynski** [comment]
I use it for my own work, but it's something we could soft deprecate over a long period of time. A `FutureWarning` or `PendingDeprecationWarning` that are easily suppressed would be the first step, followed by a `PyVistaPendingDeprecationWarning`, or equivalent.

We have just a slew of logic that could be cleaned up, but if we do, we do this slowly given that there is adoption of it.

I was under the impression that it improved performance at one point, but if we can show definitive proof that there isn't any benefit of it, we should deprecate it.

We're still sub 1, I vote we stabilize the API now before we get locked into a `1.X` and have to make a `2.X` release at some point.

**Comment by larsoner** [comment]
>> I don't think there is. @banesullivan and I wrestled with this for a while and we concluded that there isn't really any memory improvement.

> I was under the impression that it improved performance at one point, but if we can show definitive proof that there isn't any benefit of it, we should deprecate it.

In MNE we have large ~100k vertex meshes and use VTK to [compute the normals](https://docs.pyvista.org/api/core/_autosummary/pyvista.PolyDataFilters.compute_normals.html#pyvista.PolyDataFilters.compute_normals) for (all of?) them with `inplace=True`. The overhead of `inplace=False` is probably negligible for us, but I could imagine it might not be negligible for larger meshes assuming the underlying point and cell data is copied in memory. :shrug: 
But if it helps a lot with maintenance, for that one use case a `mesh.add_normals` or something added that makes it clear that it's added to the current mesh.

I don't know the extent to which VTK itself does in-place versus not, but it might make sense to take their implementations into account. If they support a lot of in-place operations (or none!) it gives a sense of the extent to which it's probably used in real-world 3D workflows.

**Comment by banesullivan** [comment]
> I don't know the extent to which VTK itself does in-place versus not, but it might make sense to take their implementations into account. If they support a lot of in-place operations (or none!) it gives a sense of the extent to which it's probably used in real-world 3D workflows.

My impression of VTK is that there are no in-place operations and that things that modify data (algorithms) have an input and an output -- never altering the input. However, this is just my impression of VTK

**Comment by tkoyama010** [comment]
I will close this as no particular request has been raised by users and the discussion is stale.
