### ISSUE TITLE
enable_area_selection

### ISSUE THREAD

**Issue by fire8flag** [pyvista/pyvista#4162]
### Describe the feature you would like to be added.

Hello, I found a very good and amazing tool, in view of my professional background, the shallow knowledge of computer programming, I would like to ask the developers to develop a function: draw a rectangular area, can select the points in the area, or ready-made methods can also tell me how to achieve, if you can really help me a lot!

### Pseudocode or Screenshots

```python
Insert code here
```
Or drag your screenshot here!

**Comment by fire8flag** [comment]
import pyvista as pv
# Read PolyData data
mesh = pv.read('polydata_file.vtk')
# Create a plot window and add data
p = pv.Plotter()
p.add_mesh(mesh)
# Enable area selection
p.enable_area_selection()
# Show the plotting window and wait for the user to select an area
p.show()
# Get the points and cells in the selected area
selected_points = mesh.points[p.selected_points]
selected_cells = mesh.cells[p.selected_cells]

**Comment by fire8flag** [comment]
The effect achieved：
https://kitware.github.io/vtk-examples/site/Cxx/Picking/AreaPicking/

**Comment by tkoyama010** [comment]
@fire8flag Have you tried `enable_cell_picking()` or `enable_point_picking()` ?

- https://docs.pyvista.org/api/plotting/_autosummary/pyvista.Plotter.enable_cell_picking.html
- https://docs.pyvista.org/api/plotting/_autosummary/pyvista.Plotter.enable_point_picking.html

**Comment by tkoyama010** [comment]
Or [enable_rubber_band_style](https://docs.pyvista.org/api/plotting/_autosummary/pyvista.Plotter.enable_rubber_band_style.html) may work for you.

**Comment by fire8flag** [comment]
enable_cell_picking() Only can selected the cell but what I want is selected all the point in the rectangle area.&nbsp;
Thank your answer.



发自我的iPhone


------------------ Original ------------------
From: Tetsuo Koyama ***@***.***&gt;
Date: Mon,Mar 20,2023 7:56 PM
To: pyvista/pyvista ***@***.***&gt;
Cc: fire8flag ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [pyvista/pyvista] enable_area_selection (Issue #4162)





 
@fire8flag Have you tried enable_cell_picking() or enable_point_picking() ?
  
https://docs.pyvista.org/api/plotting/_autosummary/pyvista.Plotter.enable_cell_picking.html
 
https://docs.pyvista.org/api/plotting/_autosummary/pyvista.Plotter.enable_point_picking.html

**Comment by fire8flag** [comment]
thank,u,enable_rubber_band_style()can drawed a rectangle but the rectangle can not hold in the view.
any way to hold the rectangle ?
another problem is that&nbsp;enable_rubber_band_style() can selected the object,but I want select the surface point of object,please tell what should I do?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tetsuo ***@***.***&gt;; 
发送时间: 2023年3月20日(星期一) 晚上8:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [pyvista/pyvista] enable_area_selection (Issue #4162)





 
Or enable_rubber_band_style may work for you.

**Comment by fire8flag** [comment]
and I want the function is that like enable_cell_picking()but the select point not cell






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pyvista/pyvista"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月20日(星期一) 晚上8:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pyvista/pyvista] enable_area_selection (Issue #4162)





 
Or enable_rubber_band_style may work for you.

**Comment by banesullivan** [comment]
There should be more options for this after #4254 with `enable_rectangle_picking()` and `enable_rectangle_visible_picking()`.

**Comment by fire8flag** [comment]
Thank you for your efforts to do this. Also is it possible to give specific examples and tutorials



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Bane ***@***.***&gt;; 
发送时间: 2023年6月26日(星期一) 凌晨5:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [pyvista/pyvista] enable_area_selection (Issue #4162)





 
There should be more options for this after #4254 with enable_rectangle_picking() and enable_rectangle_visible_picking().

**Comment by banesullivan** [comment]
Here is an example to use the existing area based selection tools to get the selected points:

```py
import pyvista as pv
from pyvista import examples

mesh = examples.load_random_hills()

pl = pv.Plotter(notebook=0)
pl.add_mesh(mesh)

class Selector:
    def __init__(self, plotter):
        self.plotter = plotter
        self.points = None
    
    def __call__(self, selected):
        self.plotter.add_mesh(selected, style='points', color='magenta', pickable=False, name='selection')
        self.points = selected.points
        
s = Selector(pl)

pl.enable_rectangle_visible_picking(s, show=False)
pl.show()
```
