### ISSUE TITLE
Matplotlib inline vs. Qt backend issues

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#418]
We need to figure out how to resolve issues around https://github.com/pyvista/pyvista-support/issues/53 where the plotter might automatically close unless using the qt backend with matplotlib. I have a feeling that IPython must be closing Qt windows when using inline plotting.

I haven't been able to reproduce this on my Mac - it seems that everyone reporting this issue is using Windows.

Possibly has relevance to #186

**Comment by pytzcarraldo** [comment]
Has there been any progress on this? I'm experiencing similar issues: 

The plotter works for the first run since starting/restarting a jupyter noteobok. Any consecutive opening of the plotter immediately closes after opening. If I set `%matplotlib qt` it crashes my kernel instead of opening/closing.

```

--------------------------------------------------------------------------------
  Date: Wed Dec 11 09:33:44 2019 W. Europe Standard Time

           Windows : OS
                 8 : CPU(s)
             AMD64 : Machine
             64bit : Architecture
           31.7 GB : RAM
           Jupyter : Environment

  Python 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]

            0.22.4 : pyvista
             8.1.2 : vtk
            1.15.4 : numpy
             2.5.0 : imageio
             1.4.3 : appdirs
             0.3.0 : scooby
             3.1.0 : matplotlib
             5.9.2 : PyQt5
             7.5.0 : IPython

  Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for
  Intel(R) 64 architecture applications
--------------------------------------------------------------------------------
```

**Comment by banesullivan** [comment]
Hi @pytzcarraldo, this is definitely an annoying issue that we need to resolve. Unfortunately, I have no idea what might be causing this... it seems to me like a weird environment thing on windows with IPython and MPL which I don't know how to approach in investigating

Most folks with Windows machines appear to have success if just using the `q`-key to close plotting windows (not the exit button) - can you try this?

**Comment by pytzcarraldo** [comment]
Hey @banesullivan, thanks for the quick response! I generally close the plotting window using the `q`-key anyways, so it definitely does not depend on that (on my machine at least) 🤔

**Comment by banesullivan** [comment]
How does PyVista behave in normal IPython from the command line? Can you try creating a few plotters there? And then copy/paste the output like:

```py
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 14:38:56)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.6.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import pyvista as pv

In [2]: pv.Sphere().plot()
Out[2]:
[(-0.41175970401626527, 2.805067358518657, 1.7594511749715018),
 (0.0, 0.0, 0.0),
 (-0.4010862526825017, -0.5282804243577366, 0.7483646244642502)]

In [3]: pv.Sphere().plot(show_edges=True)
Out[3]:
[(0.8162372312158437, 0.8162372312158437, -0.5678510761392037),
 (0.0, 0.0, 0.0),
 (0.31212471648883383, 0.31212471648883383, 0.8973050332598888)]
```

**Comment by banesullivan** [comment]
@pyvista/developers, does anyone have a Windows machine that can reproduce and debug this issue? Also, can you look at #186?

**Comment by banesullivan** [comment]
@pytzcarraldo, can you see if #502 resolves this?

**Comment by pytzcarraldo** [comment]
Hey @banesullivan! I've installed the `patch/win-exit` branch and it now works perfectly. I can quit the plotting window using both the `q`-key or the window exit button and re-open any pyvista plot without any issues. 

Thanks a lot! 😃

**Comment by banesullivan** [comment]
Awesome! Thanks for checking @pytzcarraldo 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
