### ISSUE TITLE
errata-ai/vale-action@review-dog GitHub Actions raise error

### ISSUE THREAD

**Issue by tkoyama010** [pyvista/pyvista#4193]
### Describe what maintenance you would like added.

It appears that [errata-ai/vale-action@review-dog](https://github.com/errata-ai/vale-action/issues) is terminating in error due to a deprecated message in the Node.js library.
https://github.com/pyvista/pyvista/actions/runs/4531501610/jobs/7981727784
I'm sure the maintainer of the vale-aciton will eventually fix this, but as it stands we're being shown the error. @akaszynski Can I commenting out this action for a while?

**Comment by akaszynski** [comment]
Yes, please comment it out.
