### ISSUE TITLE
Adding a personal logo

### ISSUE THREAD

**Issue by bellonet** [pyvista/pyvista#4236]
I'm creating a PyVista based python package that allows researchers in a specific field to generate videos of their earth data.
The only part I'm missing is the ability for the user to add a logo of their institute to their video that will always be present e.g. in the right bottom corner.

Thus, I want to add to the plotter `p` an image that is always in the front of the scene and does not move with the camera - just like `p.add_text` or `p.add_legend` have an absolute location.

I understand that I can hack it so that at every scene I move the "logo mesh" based on the camera position to achieve this, but it doesn't seem like the proper way to go about it and I'm hoping I missed something in the documentation.

PyVista is amazing! Thank you so much for creating it and your support!

**Comment by banesullivan** [comment]
Excellent question/request!! This has popped up in my mind a few times in the past but never had a strong need.

We would need to implement https://vtk.org/doc/nightly/html/classvtkLogoWidget.html in PyVista.

Here is a VTK+PyVista example to do this yourself until someone finds a way to fully implement this

```py
import pyvista as pv

def add_logo(plotter, image):
    import vtk
    logoRepresentation = vtk.vtkLogoRepresentation()
    logoRepresentation.SetImage(image)
    logoRepresentation.SetPosition(.75, .8)
    logoRepresentation.SetPosition2(.2, .2)
    logoRepresentation.GetImageProperty().SetOpacity(1.0)
    logoWidget = vtk.vtkLogoWidget()
    logoWidget.SetInteractor(plotter.iren.interactor)
    logoWidget.SetRepresentation(logoRepresentation)
    logoWidget.On()
    plotter.logo_widget = logoWidget  # have to keep a reference to the widget
    return logoWidget

logo = pv.read('/Users/bane.sullivan/Software/pyvista/pyvista/doc/source/_static/pyvista_logo.png')

pl = pv.Plotter()
pl.add_mesh(pv.Cone())
w = add_logo(pl, logo)
pl.show()
```

![screenshot (6)](https://user-images.githubusercontent.com/22067021/230150213-4f7408fc-8b49-4908-b502-7003a8f7c0ce.png)

**Comment by akaszynski** [comment]
PyVista Logo you can use in the example above.

![pyvista_logo](https://user-images.githubusercontent.com/11981631/230150685-905d0d29-19b8-4363-b849-b27cf3b281eb.png)

Download from your browser and "save as" `pyvista_logo.png`.

**Comment by banesullivan** [comment]
> PyVista based python package that allows researchers in a specific field to generate videos of their earth data.

@bellonet, I would love to know more about this package! Can you point me to a repository, website, etc? Perhaps there other small things I can help with/review? I love seeing more earth scientists using PyVista!

**Comment by bellonet** [comment]
Hi @banesullivan Thank you so much for the spot on and quick response! Works great!

I'm still implementing this logo feature and see will try to add the PyVista logo in there @akaszynski (but might be a bit tight, as I need both the logo of my funding platform and the optional logo of the video creator institute).

Here is a link to the project repo:  
https://gitlab.com/ida-mdc/earth-watch/-/tree/main/

Thanks again!

**Comment by banesullivan** [comment]
Please feel no obligation to add the pyvista logo!!
