### ISSUE TITLE
Exported HTML does not render in browser since last week

### ISSUE THREAD

**Issue by rudimytro** [pyvista/pyvista#4239]
### Describe the bug, what's wrong, and what you expected.

Up until recently I was successfully exporting 3D visualizations into HTML files and opening them in the browser. A week or two ago all my exported HTMLs started showing blank pages with nothing rendered, this is the same for old HTMLs that were opening correctly before. 

I've tried opening it on 3 different computers with Edge, Chrome, and Firefox - the same situation. Asked my teammates to reproduce and they confirm that the issue is also started happening to them.

**If** I manually change the HTML file code to load `0.19.0` of `@jupyter-widgets/html-manager` instead of `0.20.0` (or any later version) everything works as expected and browser renders a 3D scene. But it was working fine with 0.20.0 in the past

### Steps to reproduce the bug.

```python
import pyvista as pv

plotter = pv.Plotter()
sphere = pv.Sphere()  # Add something to fill the scene
plotter.add_mesh(sphere, color=color)
plotter.export_html(output_file_directory)
plotter.close()
```
Open generated HTML file in browser
Check console for javascript errors

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Thu Apr 06 15:12:34 2023 CEST

                OS : Linux
            CPU(s) : 12
           Machine : x86_64
      Architecture : 64bit
               RAM : 31.3 GiB
       Environment : Jupyter
       File system : ext4
        GPU Vendor : NVIDIA Corporation
      GPU Renderer : NVIDIA GeForce RTX 3080/PCIe/SSE2
       GPU Version : 4.5.0 NVIDIA 470.161.03

  Python 3.8.10 (default, Mar 14 2023, 14:51:09)  [GCC 11.3.0]

           pyvista : 0.38.5
               vtk : 9.2.6
             numpy : 1.21.0
           imageio : 2.26.0
            scooby : 0.7.1
             pooch : v1.7.0
        matplotlib : 3.7.1
           IPython : 8.11.0
        ipywidgets : 8.0.4
             scipy : 1.10.1
              tqdm : 4.65.0
         pythreejs : 2.4.2
      nest_asyncio : 1.5.6

  Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904
  for Intel(R) 64 architecture applications
--------------------------------------------------------------------------------
```

### Screenshots

![Browser Console Image](https://user-images.githubusercontent.com/13711526/230386065-7645c72b-4f18-47ba-86d1-ae3227693a7a.png)

**Comment by akaszynski** [comment]
@banesullivan, I think it's becoming more and more critical to have HTML export working in trame since we might not be able to rely on jupyter widgets.
