### ISSUE TITLE
select_enclosed_points false negative

### ISSUE THREAD

**Issue by jptreble2** [pyvista/pyvista#4240]
### Describe the bug, what's wrong, and what you expected.

When calling the function on a complex, but closed and manifold geometry i get a false negative for a point.

On inspection the point is clearly inside the geometry and if I move it by a small amount in any direction I get a postive response

### Steps to reproduce the bug.

I can send the geometry data on request

### System Information

```shell
running on ubuntu 20 through wsl. newest pip version of pyvista
```

**Comment by banesullivan** [comment]
Can you provide the mesh and code to reproduce the problem? 

> running on ubuntu 20 through wsl. newest pip version of pyvista

Would you please follow the instructions to post a PyVista Report? This helps us now which versions of PyVista's dependencies (like VTK) and hardware you have.

**Comment by jptreble2** [comment]
Here is the pv report.

Can I share the files privately with you?
--------------------------------------------------------------------------------
  Date: Fri Apr 07 12:52:07 2023 GMT
                OS : Linux
            CPU(s) : 12
           Machine : x86_64
      Architecture : 64bit
               RAM : 17.5 GiB
       Environment : IPython
       File system : ext4
       GPU Details : error
  Python 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0]
           pyvista : 0.37.0
               vtk : 9.1.0
             numpy : 1.23.4
           imageio : 2.13.5
            scooby : 0.5.11
             pooch : v1.6.0
        matplotlib : 3.6.1
           IPython : 8.9.0
             scipy : 1.9.3
              tqdm : 4.62.3
            meshio : 4.4.6
--------------------------------------------------------------------------------

**Comment by banesullivan** [comment]
> Here is the pv report.

Please also note you are running an older version of VTK, and you may want to upgrade to a newer version to see if the issue remains.

> Can I share the files privately with you?

If upgrading VTK doesn't help, please join our Slack workspace and find me there: slack.pyvista.org

**Comment by jptreble2** [comment]
Thanks... I tried upgrading to 9.2.6, but the issue still persists. I will try the slack channel

**Comment by banesullivan** [comment]
(data and reproducible example shared privately)

This is very odd. The point is indeed clearly within the bounds of the closed, manifold surface and adjacent to another point that has no issue. Toying with the `tolerance` parameter would get the point to register inside the surface, but otherwise, it fails to register when it should.

This is an upstream bug in the implementation of `vtkSelectEnclosedPoints`

**Comment by akaszynski** [comment]
> Reopening as the original poster's issue has not been resolved

My bad. Thanks @banesullivan

**Comment by banesullivan** [comment]
Now I'm tempted to close this again, lol -- it's not very actionable for us. The example to reproduce the example cannot be shared publically, and as far as I can tell, it may be an upstream issue. 

Going to re-close this 🙃 until a publically shareable example can be made, and perhaps this is reported upstream
