### ISSUE TITLE
BUG: Intersphinx broken

### ISSUE THREAD

**Issue by larsoner** [pyvista/pyvista#4283]
### Describe the bug, what's wrong, and what you expected.

As of today the previously working intersphinx link is broken. I'd recommend adding a HTML redirect from `https://docs.pyvista.org/objects.inv` to `https://docs.pyvista.org/version/stable/objects.inv` as I think it would solve the problem.

### Steps to reproduce the bug.

In a `conf.py`
```python
intersphinx_mapping = {
    'pyvista': ('https://docs.pyvista.org/', None),
}
```

### System Information

```shell
N/A
```

### Screenshots

```
WARNING: failed to reach any of the inventories with the following issues:
intersphinx inventory 'https://docs.pyvista.org/objects.inv' not fetchable due to <class 'requests.exceptions.HTTPError'>: 404 Client Error: Not Found for url: https://docs.pyvista.org/objects.inv
```

**Comment by akaszynski** [comment]
Resolved in 77388b2eedb3d4967bb515efd5ff20c8056b3682

I tried your original suggestion of creating a html redirect using b73d1428ae8c3af02340dbb0a87499338cc594f8, but `Sphinx` can't work with that. Setting up a 301 redirect as we have no control over the server config.

**Comment by adamjstewart** [comment]
It seems like https://docs.pyvista.org/version/stable/objects.inv disappeared now?

**Comment by akaszynski** [comment]
Just fixed this (again!).
