### ISSUE TITLE
Volume render opacity doesn't make sense

### ISSUE THREAD

**Issue by keltonhalbert** [pyvista/pyvista#430]
**Transparent Volumes are Too Bright**

This image is of the same volume with a linear opacity curve, varying the colormap orientation (thermal vs thermal_r). What ends up happening is that even though the opacity values are well below 0.5, perhaps even closer to 0.1, the yellows are way too bright and wash out what should be the more opaque part of the volume. 

On the whole, when manually specifying opacity to the volume render engine, you have to get to incredibly low values to get it to display with transparency. An opacity of 0.5 might as well be solid. 

What's expected is that the transfer function for the opacity should mean that the darker colors are still visible in spite of the lighter, more transparent colors. I also expect that opacity should have more impact on the volume than it currently does - it seems like opacity is too bright overall. 

-----

**To Reproduce**

I can't provide example data, but this is the functional code:
```py
p = pv.Plotter(notebook=False,
               window_size=[3072, 2224], 
               multi_samples=16)

p.add_volume(grid, scalars="vortmag", clim=[1e-03, 1e1], cmap="thermal", opacity="linear", mapper="gpu", n_colors=256*2, ambient=0)
p.camera_position = [(9240.182974604228, 2813.0796919414984, 11182.54953530958),
 (-4091.4200075561566, -2186.2488077169264, 851.0583580728803),
 (-0.4980097002215671, -0.32957308048380274, 0.8021021899394379)]

p.show_grid()
p.show()
p.screenshot("example_1.png")


p = pv.Plotter(notebook=False,
               window_size=[3072, 2224], 
               multi_samples=16)

p.add_volume(grid, scalars="vortmag", clim=[1e-03, 1e1], cmap="thermal_r", opacity="linear", mapper="gpu", n_colors=256*2, ambient=0)
p.camera_position = [(9240.182974604228, 2813.0796919414984, 11182.54953530958),
 (-4091.4200075561566, -2186.2488077169264, 851.0583580728803),
 (-0.4980097002215671, -0.32957308048380274, 0.8021021899394379)]

p.show_grid()
p.show()
p.screenshot("example_2.png")
```

**Screenshots**
![Selection_125](https://user-images.githubusercontent.com/1411265/67907693-b9957700-fb70-11e9-8989-bbfbbb2290ac.png)
![Selection_124](https://user-images.githubusercontent.com/1411265/67907699-bdc19480-fb70-11e9-8b5c-62cfc34023c9.png)

-----

**System Information:**
 Please run the following code wherever you are experiencing the bug and paste the output below. This report helps us track down bugs and it is critical to addressing your bug:

```py
# Get system info
import pyvista as pv
print(pv.Report())
```
![Selection_126](https://user-images.githubusercontent.com/1411265/67907737-e0ec4400-fb70-11e9-9720-2140432d81ff.png)
```txt
# Paste system info here

```

**Comment by banesullivan** [comment]
Thanks, @keltonhalbert! Beat me to it!

I posted another issue at the same time with a reproducible example in #431

**Comment by keltonhalbert** [comment]
Possibly related, is that the clim max/min does not respect any data above/below the max/min. 

For example, this is the same volume as described in the code above, but with clim varying from [1e-3, 10] to [1e-3, 1].

In the example where the max is 10, you can see that the volume is full. However, when the max is set to 1, there is a donut hole where the data max > 1. 

**CLIM = [1e-3, 10]**
![Selection_130](https://user-images.githubusercontent.com/1411265/67908590-fb73ec80-fb73-11e9-9714-038466f81c69.png)
**CLIM = [1e-3, 1]**
![Selection_129](https://user-images.githubusercontent.com/1411265/67908598-fdd64680-fb73-11e9-9026-62754eb7b49d.png)

**Comment by keltonhalbert** [comment]
One last example, you can really see some fun stuff when you have a semitransparent black contour. I think starting with "why does black behave this way" would be a good first step to diagnosing the problem.  

```py
isosurf = grid.contour([30, 40, 50], scalars="winterp") ## 3 specific contour levels in m/s
p = pv.Plotter(notebook=True,
               window_size=[1920*2, 1080*2], 
               multi_samples=16)
p.add_mesh(isosurf, scalar="winterp", cmap="bone", opacity=0.75, clim=[30,50], mapper="gpu")
p.camera_position = [(10461., -11557., 5004.),
                     (-188., -294., -64.),
                     (0, 0, 1)]
p.show_grid()
p.screenshot("example1.png")
```
![example1](https://user-images.githubusercontent.com/1411265/67920669-fbd4ad80-fb9c-11e9-978a-63dd256ebb0d.png)

**Comment by banesullivan** [comment]
@keltonhalbert, #464 fixes this. Check out this example snippet to play with the feature that fixes the opacity issues. It uses a slider widget to interactively adjust the `opacity_unit_distance` and it has shading enabled:

```py
p = pv.Plotter(notebook=False,
              #window_size=[3072, 2224],
              multi_samples=16)
va = p.add_volume(grid, scalars="thrhopert", 
             cmap="jet",
             opacity="sigmoid_4", mapper="smart", 
             opacity_unit_distance=grid.length / 25,
             shade=True)
p.show_grid()

f = lambda val: va.GetProperty().SetScalarOpacityUnitDistance(val)
p.add_slider_widget(f, [0, grid.length/4], title="Opacity Distance")

p.show()
```
![2019-11-21 23 21 15](https://user-images.githubusercontent.com/22067021/69402686-d4619400-0cb5-11ea-879e-f4715c3ac84c.gif)
