### ISSUE TITLE
Electronics cooling example - volumetric plot doesn't look right in the docs:

### ISSUE THREAD

**Issue by akaszynski** [pyvista/pyvista#4306]
Thanks for addressing the comments.  Not sure of the cause but the volumetric plot doesn't look right in the docs:
![image](https://user-images.githubusercontent.com/39341281/230781254-b0927548-eb48-44f0-9769-497e50a29c4a.png)

_Originally posted by @MatthewFlamm in https://github.com/pyvista/pyvista/issues/4235#issuecomment-1501152268_

**Comment by banesullivan** [comment]
This currently looks good in our dev docs and for the last release: https://docs.pyvista.org/version/dev/examples/99-advanced/openfoam-cooling.html#sphx-glr-examples-99-advanced-openfoam-cooling-py
![sphx_glr_openfoam-cooling_005](https://github.com/pyvista/pyvista/assets/22067021/d306bef9-04d6-48a4-877f-27ca68695ba4)
