### ISSUE TITLE
Icosphere Primitive

### ISSUE THREAD

**Issue by MosGeo** [pyvista/pyvista#4319]
### Describe the feature you would like to be added.

I am new to pyvista and I am just exploring the different features.

It would be great if pyvista would support a quick way to create an icosphere (an icohedron projected into a sphere). See this image for an example.  The image is taken from https://en.wikipedia.org/wiki/Geodesic_polyhedron

![image](https://user-images.githubusercontent.com/10503349/233863624-cedfc26d-3e75-4597-a2c0-8b3703b485de.png)

**Comment by darikg** [comment]
Agreed, that'd be nice to have out of the box. I think it's just this:


```python
from pyvista import Icosahedron
import numpy as np

def Icosphere(radius=1.0, center=(0.0, 0.0, 0.0), nsub=2):
    m = Icosahedron().subdivide(nsub=nsub)  # centered at origin
    r = np.linalg.norm(m.points, axis=1, keepdims=True)  # distance from origin
    m.points = m.points * (radius / r) + center  # scale to desired radius and translate origin
    return m
```

**Comment by MosGeo** [comment]
> Agreed, that'd be nice to have out of the box. I think it's just this:
> 
> ```python
> from pyvista import Icosahedron
> import numpy as np
> 
> def Icosphere(radius=1.0, center=(0.0, 0.0, 0.0), nsub=2):
>     m = Icosahedron().subdivide(nsub=nsub)  # centered at origin
>     r = np.linalg.norm(m.points, axis=1, keepdims=True)  # distance from origin
>     m.points = m.points * (radius / r) + center  # scale to desired radius and translate origin
>     return m
> ```

@akaszynski @darikg Nice :) That is actually very close to what I ended up doing except I didn't use the elegent and probably more efficient `norm` function. I've used 

```python
mesh.points = mesh.points / np.sqrt(np.sum(mesh.points**2, axis=1, keepdims=True))
```

In any case, thanks for adding it quickly to pyvista. It looks like pyvista is very powerful and easy to use. Looks like it is going to be a great companion for me for playing with granular packs (e.g., https://github.com/MosGeo/ParticlePack).

**Comment by akaszynski** [comment]
> Looks like it is going to be a great companion for me for playing with granular packs (e.g., https://github.com/MosGeo/ParticlePack).

If you want to visualize closely packed particles, be sure to use [SSAO](https://docs.pyvista.org/version/stable/examples/02-plot/ssao.html). You'll get much nicer looking plots of the particles.

**Comment by MosGeo** [comment]
> > Looks like it is going to be a great companion for me for playing with granular packs (e.g., https://github.com/MosGeo/ParticlePack).
> 
> If you want to visualize closely packed particles, be sure to use [SSAO](https://docs.pyvista.org/version/stable/examples/02-plot/ssao.html). You'll get much nicer looking plots of the particles.

Thanks very much! the visiualization looks indeed much better in the example. Actually, I am thinking further than just visualization for pyvista. I can use it for creating the irregular grains for analysis, creating the binary 3D image of the grain pack, and analyzing each grain (e.g., curvature). Currently, the grains are created in C# inside unity script, and external analysis is handled by Matlab codes that I have in the repo.

**Comment by MightyBOBcnc** [comment]
Would it be too much of a heavy lift to ask for the possibility of subdividing the icosphere by frequency as an option instead of recursive subdivision (see MosGeo's original Wikipedia link)?  (Also should I ask this on a separate issue or discussion?)

**Comment by tkoyama010** [comment]
@MightyBOBcnc It is recommended to open a new Discussion as it is rare to get a response to an issue once it has been closed :)
