### ISSUE TITLE
Bug in visualizing wireframe for a mixed (Lines / Triangles) UnstructuredGrid

### ISSUE THREAD

**Issue by mhoeijm** [pyvista/pyvista#4328]
Visualizing the edges of a mixed unstructured grid (triangles and beams) is a bit buggy. See also https://github.com/pyansys/pydpf-core/issues/741 for the original issue. I managed to reproduce on a simple sphere: 

![image](https://user-images.githubusercontent.com/102799582/234056304-04b50ac4-c4f5-4c1d-b60f-813bd9f2b7a5.png)

MWE
```Python
"""Pyvista beam visualization bug"""

import pyvista as pv
import numpy as np

poly_sphere = pv.Sphere(radius=10)
grid_sphere = poly_sphere.cast_to_unstructured_grid()

# create unstructured grid with line-elements only on bottom half of sphere.
mask = grid_sphere.points[:,2] < 0

num_lines = np.sum(mask)
cell_types = np.array([pv.CellType.LINE] * num_lines)
cells_lines = np.hstack(
    [
        np.array(([2] * num_lines))[:, None],
        np.argwhere(mask),
        np.argwhere(mask),
    ]
)
cells_lines[:, -1] += 1
cells_lines = np.reshape(cells_lines, (cells_lines.shape[0] * 3))

grid_beams = pv.UnstructuredGrid(cells_lines, cell_types, grid_sphere.points)

# combine sphere and beam-only grid
combined = grid_sphere + grid_beams

# plot all grids
plotter = pv.Plotter(shape=(2,2))
# original sphere
plotter.subplot(0,0)
plotter.add_mesh(grid_sphere, show_edges=True )
plotter.add_title("Sphere")
# reconstructed grid
plotter.subplot(0,1)
plotter.add_mesh(grid_beams, show_edges=True)
plotter.add_title("Beams")
# combined method 1
plotter.subplot(1,0)
plotter.add_mesh(combined, show_edges=True)
plotter.add_title("Combined 1")

# combined method 2
plotter.subplot(1,1)
plotter.add_mesh(grid_sphere, show_edges=True)
plotter.add_mesh(grid_beams, show_edges=True)
plotter.add_title("Combined 2")

plotter.link_views(True)
plotter.show()
```
@banesullivan. Looking at this more closely I am pretty sure the issue in this specific example is not related to the issue posted here: https://github.com/pyvista/pyvista/issues/3738. 

_Originally posted by @ansmhoeij in https://github.com/pyvista/pyvista/issues/3738#issuecomment-1520454125_

**Comment by akaszynski** [comment]
Here's an even more minimal example:

```py
import pyvista as pv
import numpy as np


points = np.array(
    [[0.0, 0.0, -0.5], [-0.5, 0.0, 0.0], [0.25, 0.43, 0.0], [0.25, -0.43, 0.0]]
)

out = pv.UnstructuredGrid(
    [3, 1, 2, 0, 3, 3, 1, 0, 2, 2, 3],
    [pv.CellType.TRIANGLE, pv.CellType.TRIANGLE, pv.CellType.LINE],
    points,
)
out.plot(show_edges=True, line_width=5, cpos="xy")
```

![tmp](https://user-images.githubusercontent.com/11981631/234125543-b811a45d-c23b-43a0-a4e1-ae16fdf0c3e8.png)

This is most likely a pure VTK issue and has been reported upstream in https://gitlab.kitware.com/vtk/vtk/-/issues/18958

**Comment by akaszynski** [comment]
Note that the same issue occurs with `PolyData`:

```py
import pyvista as pv
import numpy as np
pv.set_plot_theme('document')

points = np.array(
    [[0.0, 0.0, -0.5], [-0.5, 0.0, 0.0], [0.25, 0.43, 0.0], [0.25, -0.43, 0.0]]
)

out = pv.PolyData(out.points, faces=[3, 1, 2, 0, 3, 3, 1, 0], lines=[2, 2, 3])
out.plot(show_edges=True, line_width=5, cpos="xy")
```

**Comment by banesullivan** [comment]
Adding a relevant link for my reference: https://stackoverflow.com/questions/13708661/how-to-draw-one-line-on-top-of-another-in-opengl-without-z-fighting

**Comment by banesullivan** [comment]
This was fixed upstream in https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10269

I've pulled VTK `master` and built a wheel to check this with PyVista and indeed all is working well now. This will be reflected in the next release of VTK (presumably 9.2.7)

| Case 1 | Case 2 |
|---|---|
| ![screenshot (3)](https://github.com/pyvista/pyvista/assets/22067021/1cc13b17-aa3d-4804-8211-dabe468ef397) | ![screenshot (2)](https://github.com/pyvista/pyvista/assets/22067021/9081a927-e6d2-499c-99ed-81a7804754f2) |
