### ISSUE TITLE
point_array renamed to point_data

### ISSUE THREAD

**Issue by kamtchou98** [pyvista/pyvista#4339]
I just went into the source for `pyvista.voxelize` and saw that `mask` was exactly what you were looking for in terms of a numpy bool array describing which voxel is in or out of the surface mesh.

```python
from pyvista import examples
import pyvista
import numpy as np

mesh = examples.download_foot_bones()
density = mesh.length / 100
x_min, x_max, y_min, y_max, z_min, z_max = mesh.bounds
x = np.arange(x_min, x_max, density)
y = np.arange(y_min, y_max, density)
z = np.arange(z_min, z_max, density)
x, y, z = np.meshgrid(x, y, z)

# Create unstructured grid from the structured grid
grid = pyvista.StructuredGrid(x, y, z)
ugrid = pyvista.UnstructuredGrid(grid)

# get part of the mesh within the mesh's bounding surface.
selection = ugrid.select_enclosed_points(mesh.extract_surface(),
                                         tolerance=0.0,
                                         check_surface=False)
mask = selection.point_data['SelectedPoints'].view(np.bool)
mask = mask.reshape(x.shape)

pyvista.plot(grid.points, scalars=mask)
```
![desktop 1_157](https://user-images.githubusercontent.com/11981631/77123273-f559ac00-6a3f-11ea-9f1f-b4ff65a75fa4.png)

_Originally posted by @akaszynski in https://github.com/pyvista/pyvista-support/issues/141#issuecomment-601459353_

Hi,

This solution doesn't seem to working for the current iteration of PyVista. Could you please offer a fix, thanks.

**Comment by kamtchou98** [comment]
The error thrown up is 'UnstructuredGrid' object has no attribute 'point_arrays'

**Comment by akaszynski** [comment]
I updated the example code above just in case someone copy-pastes it (which I tend to do all the time).

**Comment by koenterheegde0507** [comment]
I'm using this to get a binary 3D array from a voxelized mesh. I would like to only plot the values that are 'True', but to me it seems like I don't get the right plot. This is the voxelized mesh I want to get the binary array of:
<img width="960" alt="pyvista_voxelization" src="https://github.com/pyvista/pyvista/assets/152174547/25a38f59-2c5b-4eee-a183-0a698bde55c7">

I've used this code:
`import os
import tkinter as tk 
from tkinter import filedialog
import pyvista as pv
import numpy as np 
import skimage
from skimage.morphology import skeletonize_3d
import matplotlib.pyplot as plt
import skeletor as sk
from stl import mesh
import trimesh

root = tk.Tk()
root.withdraw()
root.title('Pick patient data')
file_path = filedialog.askopenfilename()

chosenMesh = pv.read(f'{file_path}')
density = chosenMesh.length/200
voxels = pv.voxelize(chosenMesh, density)

voxel_plotter = pv.Plotter()
voxel_plotter.add_mesh(voxels)
voxel_plotter.show()

x_min, x_max, y_min, y_max, z_min, z_max = chosenMesh.bounds
x = np.arange(x_min, x_max, density)
y = np.arange(y_min, y_max, density)
z = np.arange(z_min, z_max, density)
x, y, z = np.meshgrid(x, y, z)

grid = pv.StructuredGrid(x, y, z)
ugrid = pv.UnstructuredGrid(grid)

selection = ugrid.select_enclosed_points(chosenMesh.extract_surface(),
                                         tolerance=0.0,
                                         check_surface=False)


mask = selection.point_data['SelectedPoints'].view(bool)
mask = mask.reshape(x.shape)

custom_colormap = ['purple','red']
pv.plot(grid.points, scalars=mask.astype(int), cmap=custom_colormap)`

And get this result:
<img width="960" alt="pyvista_binaryImage" src="https://github.com/pyvista/pyvista/assets/152174547/882051e6-bd6a-4889-b83f-6b122ac3ef0e"> This seems to work, as you zoom in you can see the red points that are part of the voxelization. I would like to only plot those red points but then I get a strange result: 

`test = np.where(mask==1)

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.scatter(test[0], test[1], test[2], c='black')
plt.show()`

<img width="960" alt="image" src="https://github.com/pyvista/pyvista/assets/152174547/976b70fa-dfef-42e1-b31a-77cb2209cf3c">

This doesn't look remotely close to the voxelized mesh and I can't figure out why. I don't know whether it's a mistake in the plotting or related to how I acquire the points. 

Could somebody help me out?

**Comment by banesullivan** [comment]
Hi @koenterheegde0507, I'm not sure what's going wrong here but I want to encourage you to open a new Discussion topic for this which will have a lot more visibility. This issue has been closed for a long time and doesn't get as much traffic. Please post on https://github.com/pyvista/pyvista/discussions
