### ISSUE TITLE
Enable Depth Peeling to avoid opacity issues

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#437]
Should we enable depth peeling to correctly render translucent opacities? See [this example for details](https://lorensen.github.io/VTKExamples/site/Cxx/Visualization/CorrectlyRenderTranslucentGeometry/) as it is not supported on all machines.

### Example

Here I show a quick difference using PyVista.

No depth peeling
```py
import pyvista as pv

centers = [(0, 0, 0), (1, 0, 0), (-1, 0, 0), 
           (0, 1, 0), (0, -1, 0)]
radii = [1, 0.5, 0.5, 0.5, 0.5]

spheres = pv.MultiBlock()
for i, c in enumerate(centers):
    spheres.append(pv.Sphere(center=c, radius=radii[i]))

pv.plot(spheres, opacity=0.5)
```
![download](https://user-images.githubusercontent.com/22067021/68041849-1723e380-fc97-11e9-9bcc-4f5a93a63256.png)

Some depth peeling
```py
p = pv.Plotter()
p.add_mesh(spheres, opacity=0.5)

# 1. Use a render window with alpha bits (as initial value is 0 (false)):
p.ren_win.SetAlphaBitPlanes(True)

# 2. Force to not pick a framebuffer with a multisample buffer
# (as initial value is 4):
p.ren_win.SetMultiSamples(0)

# 3. Choose to use depth peeling (if supported) (initial value is 0 (false)):
p.renderer.SetUseDepthPeeling(True)

# 4. Set depth peeling parameters
#  - Set the maximum number of rendering passes (initial value is 4):
p.renderer.SetMaximumNumberOfPeels(4)
#  - Set the occlusion ratio (initial value is 0.0, exact image):
p.renderer.SetOcclusionRatio(0.0)

p.show()
```

![download](https://user-images.githubusercontent.com/22067021/68041932-4f2b2680-fc97-11e9-92f1-91d6ff5fa5a9.png)

**Comment by akaszynski** [comment]
Absolutely, or at least add it as an option. I’ve had issues with this opacity issue on Linux.

**Comment by banesullivan** [comment]
VTK 8.2 might fix your opacity issues

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by akaszynski** [comment]
The problem is I'm not using conda, and many of the organizations I work with don't use anaconda either.  Would be great if I could get the wheel on PyPi for automatic deployment.

**Comment by banesullivan** [comment]
Shouldn’t be long before PyPI is updated!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by keltonhalbert** [comment]
I'm in favor of this opacity change - looks more intuitive, cleaner, and may also be responsible for some of the weirdness in my own issue I opened.

**Comment by keltonhalbert** [comment]
As an aside, I ran my isosurface code using your settings to show a real-world rendering and I have to say, this behavior is highly preferred in terms of showing depth. The first image is without depth peeling, and the second is with depth peeling. I think the results speak for themselves - you can really tell which geometry belongs where. Also looks way better while interactively rendering. 

From reading the docs, it sounds like that while it'll be slower to render, it wont affect CPU rendering either. I think the question is, how would this be best implemented? As a function in the plotter class, or as a keyword argument somewhere? 
![example1-1](https://user-images.githubusercontent.com/1411265/68164422-a9a4db00-ff54-11e9-928d-3eee318e3d7e.png)
![example1](https://user-images.githubusercontent.com/1411265/68164428-ab6e9e80-ff54-11e9-99e0-c9180883f2b3.png)
