### ISSUE TITLE
Error in write_frame method with latest version of PyVista and ImageIO

### ISSUE THREAD

**Issue by maxcapodi78** [pyvista/pyvista#4371]
### Describe the bug, what's wrong, and what you expected.

Updating to lastest version of Image IO  to latest version (2.28.1) I get the error attaached!
![image](https://user-images.githubusercontent.com/77293250/235624453-f7ef3449-b59a-41df-a2ea-d9f8794e93c2.png)
Reverting to 2.28.0 it works again

### Steps to reproduce the bug.

```python
pv = pv.Plotter(notebook=self.is_notebook, off_screen=True, window_size=self.windows_size)
add a mesh here
pv.write_frame()

```

### System Information

```shell
.
```

**Comment by akaszynski** [comment]
@maxcapodi78, this will be included in the next release, `pyvista==0.38.6`, which should be out today.
