### ISSUE TITLE
screenshot on_screen not working

### ISSUE THREAD

**Issue by MPenaR** [pyvista/pyvista#438]
## Description
Hello, when saving a screenshot to a file, I get a completely different file when not using the *off_screen* option. 

That is, the next code:

```
In [1]: import pyvista as pv                                                                                                                                                                                       

In [2]: s = pv.Sphere()                                                                                                                                                                                            

In [3]: s.plot(screenshot='on_screen',window_size=[1080,768])                                                                                                                                                      
Out[3]: 
[(1.9264490110725325, 1.9264490110725325, 1.9264490110725325),
 (0.0, 0.0, 0.0),
 (0.0, 0.0, 1.0)]

In [4]: s.plot(off_screen=True, screenshot='off_screen',window_size=[1080,768])                                                                                                                                    
Out[4]: 
[(1.9264490110725325, 1.9264490110725325, 1.9264490110725325),
 (0.0, 0.0, 0.0),
 (0.0, 0.0, 1.0)]
```
produces the files **on_screen.png** (unexpected behaviour):
![on_screen](https://user-images.githubusercontent.com/9216537/68409791-020fee80-0188-11ea-986f-cc9a4ab9dfa0.png)
and **off_screen.png** (expected behaviour):
![off_screen](https://user-images.githubusercontent.com/9216537/68409843-181daf00-0188-11ea-9b6a-bef4ba51afd4.png)

Am I doing something wrong? or is this a bug?

Thanks

**Comment by MPenaR** [comment]
> Could you copy/paste a system report...

Sure! there you have it:
```
In [1]: import pyvista as pv                                                    

In [2]: print(pv.Report())                                                      

--------------------------------------------------------------------------------
  Date: Fri Nov 08 12:48:00 2019 CET

             Linux : OS
                 6 : CPU(s)
            x86_64 : Machine
             64bit : Architecture
           IPython : Environment

  Python 3.5.3 (default, Sep 27 2018, 17:25:39)  [GCC 6.3.0 20170516]

             0.6.4 : panel
             8.1.2 : vtk
             2.6.1 : imageio
            0.22.4 : pyvista
            1.16.2 : numpy
             1.0.0 : colorcet
             0.4.3 : scooby
             7.3.0 : IPython
             1.4.3 : appdirs
            5.13.1 : PyQt5
             7.5.1 : ipywidgets
             2.0.0 : matplotlib
--------------------------------------------------------------------------------
````

**Comment by banesullivan** [comment]
How did you close the on-screen renderer? Did you hit the exit button or use the `q`-key?

**Comment by MPenaR** [comment]
I closed it clicking on the X of the window.

**Comment by banesullivan** [comment]
Does anything change for you if you use the q key instead?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MPenaR** [comment]
Nothing changes, I get the same unexpected result.

**Comment by math-artist** [comment]
I got a similar issue from a rendering window in a QtWidget.
I was getting correct pictures from the original PyVista source code, then I added a line to get a higher resolution image in the image property:
`        ifilter.SetScale(4, 4)`
This resulted in an off center image like the issue above, and about 25 % of the right side of the image was on the left of the exported image.

**Comment by MPenaR** [comment]
If I don't set `window_size` I get the same unexpected results. I was sing it to have a more "standard" description of the problem.

**Comment by GuillaumeFavelier** [comment]
I was looking at your report and I noticed that it is very similar to mine but so far somehow I can't manage to reproduce.

**Comment by banesullivan** [comment]
@MPenaR, can you confirm that this is still an issue on `pyvista==0.23.0`?

**Comment by MPenaR** [comment]
Finally! I get the expected behaviour!

**Comment by banesullivan** [comment]
@MPenaR, can we close this issue now that all is working on `v0.23.0`?

**Comment by MPenaR** [comment]
Sure!
