### ISSUE TITLE
Control the seed point of CylinderStructured

### ISSUE THREAD

**Issue by math-artist** [pyvista/pyvista#439]
Hi Bane,

thanks for this very useful method to quickly build a cylindrical array.

After getting more serious with it, I found out that the seed point can be randomly located. If we extract the cells and unravel to get numpy arrays, the location of the first array around the cylinder cannot be controlled. It would be very useful to specify a second direction to be able to control where the cell starts.
We can identify the first cell with proper opacity setting and because the points are repeated at the beginning and end of the grid.
![image](https://user-images.githubusercontent.com/53714128/68446869-00f0b880-01ac-11ea-9374-15d7ba91e27a.png)

**Comment by banesullivan** [comment]
> I found out that the seed point can be randomly located.

Huh, this is very strange to me... I thought that the seed would always be located at 0 radians in a cylindrical coordinate system as that is how I created it... Upon running it a few times, I too am seeing this "random" behavior. The only random part of the whole code in this function is when the mesh is rotated to match the given direction.

I'll see if I can patch that to no longer be random

**Comment by banesullivan** [comment]
@math-artist, the changes over in #442 should do the trick

**Comment by math-artist** [comment]
Great, thanks!
