### ISSUE TITLE
Images from docstring examples not always captured in docs

### ISSUE THREAD

**Issue by MatthewFlamm** [pyvista/pyvista#4405]
### Describe what maintenance you would like added.

#4383 switched the order of commands to get the plot rendered in the documentation.  I see this in other places of the documentation like https://docs.pyvista.org/version/dev/api/examples/_autosummary/pyvista.examples.downloads.download_electronics_cooling.html#pyvista.examples.downloads.download_electronics_cooling

But in other places like
https://docs.pyvista.org/version/dev/api/examples/_autosummary/pyvista.examples.downloads.download_exodus.html#pyvista.examples.downloads.download_exodus

it renders fine.

**Comment by adeak** [comment]
I suspect the kicker is that there was a non-plotting `DOCTEST:+SKIP` line that in #4383 was moved from before the `show()` to after it. In most cases skipping a line can lead to missing names, so in many cases there's no point evaluating anything after; I bet that's what's going on here (i.e. doctesting stops at the _first_ SKIP). Just a hunch, I haven't looked into any of this at all.

**Comment by akaszynski** [comment]
> I bet that's what's going on here (i.e. doctesting stops at the first SKIP)

I've seen that behavior as well.

> I assume the reason why that skip was there is because of numerical uncertainty in the result. Which is not a very good reason, and I don't know if we can do better. 

This is the case for some examples, but not all. I think if there's numerical instability, we probably shouldn't output the result at all and instead use an approximate comparison like `np.isclose` or `np.allclose`.

**Comment by adeak** [comment]
I misremembered, it's `# may vary`, see e.g. bottom block at https://numpy.org/doc/stable/reference/generated/numpy.var.html.

**Comment by MatthewFlamm** [comment]
We don't doctest with sphinx right? I assume the purpose of including `sphinx.ext.doctest` is only to strip the doctest flags?  Yet it has this annoying byproduct.  There is this option to do this already in base sphinx https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-trim_doctest_flags.  Can we get rid of this extension?
