### ISSUE TITLE
Improve VTK imports to avoid GL-dependencies in core module

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#4445]
Following up on some threads:

- https://github.com/pyvista/pyvista/discussions/3283
- https://github.com/pyvista/pyvista/pull/4337

Since the early days of PyVista, users have requested to use PyVista's `core` module and its robust wrappings of VTK mesh data types without having the needed GL dependencies of PyVista's plotting module. In the linked threads and various others there are compelling reasons why this should be supported.

Over time, we've become increasingly entrenched in cobbling all of the VTK imports together, forcing users to have the necessary libGL dependencies. This has been fine because the overwhelming majority of users also wanted to plot with PyVista. However, the tide is shifting and we're seeing more and more requests to use PyVista's well-documented and feature-rich core API for data processing needs outside of plotting (a testament to how truly powerful this API has become).

There are many ways to go about making this happen, but the approach in mind that keeps coming up as the simplest and likely easiest to maintain would be to *import the used VTK classes directly where they are needed* (rather than having a single `_vtk.py` module that imports everything).

Perhaps the even simpler approach would be to have two `_vtk.py` modules -- one in PyVista's `core` subpackage and one in the `plotting` subpackage (the plotting one would import the core one to keep functionality the same). Then users who want to avoid using the plotting module would change their import to `import pyvista.core as pvc`, keeping `import pyvista as pv` working the same (brings in all plotting capabilities as well).

There will be some nuances to address (like binding `pyvista.plot()` as the `plot()` method on data types) but we can address these fairly easily.

Overall, I think this is the simplest approach that will be generally easy to maintain.

The end goal for me here is to better isolate the `core` and `plotting` modules so that maybe one day, with enough community buy-in and momentum, we could split these into two separate packages (hopefully still in a mono-repo though)

Thoughts, @pyvista/developers?

**Comment by larsoner** [comment]
> users who want to avoid using the plotting module would change their import to import pyvista.core as pvc, keeping import pyvista as pv working the same (brings in all plotting capabilities as well). 

I'm not 100% sure but don't think this bit will work -- if you import a submodule I think you get the higher-level one "for free" / automatically / unavoidably, e.g.:
```
>>> import pyvista.plotting
>>> import sys
>>> sys.modules['pyvista']
<module 'pyvista' from '/home/larsoner/python/pyvista/pyvista/__init__.py'>
```
and just to make sure it's not specific to PyVista at the moment:
```
larsoner@bunk:~/Desktop$ mkdir temp
larsoner@bunk:~/Desktop$ touch temp/__init__.py
larsoner@bunk:~/Desktop$ mkdir temp/whatever
larsoner@bunk:~/Desktop$ touch temp/whatever/__init__.py
larsoner@bunk:~/Desktop$ python -c "import temp.whatever; import sys; print(sys.modules['temp'])"
<module 'temp' from '/home/larsoner/Desktop/temp/__init__.py'>
```

**Comment by adeak** [comment]
Indeed, alas. Same goes for `from` imports, even failed ones! E.g. `from logging imoort potato` -> now `logging` is loaded. Makes sense especially with things like module getattr functions that we now have.

**Comment by banesullivan** [comment]
Ah, I definitely overlooked this. I'll brainstorm this issue and see what I can come up with

**Comment by akaszynski** [comment]
I think the way to work around this would be to separate out submodules in the same way that scipy does: completely independent modules as in https://docs.scipy.org/doc/scipy/reference/.

This would mean that at the base level, importing pyvista would do nothing (or next to nothing) and would only load in the absolutely core features (like the data API). We would then have users import plotting via:
```py
from pyvista import plotting as pvplot

plt = pvplot.Plotter()
...
```

This means that we would have to remove "import everything" within `pyvista/__init__.py`.

This would be the breaking change necessary to move to v1.0.0 IMO, but potentially worth it. I don't like importing everything and the kitchen sink.

**Comment by adeak** [comment]
> I think the way to work around this would be to separate out submodules in the same way that scipy does: completely independent modules as in https://docs.scipy.org/doc/scipy/reference/.

Just to add to that a bit, the fun thing about SciPy is that as of not so long ago they have [this cute thing in `scipy/__init__.py`](https://github.com/scipy/scipy/blob/6c1b431ccc341c5d0d5b38690c106116b61ca800/scipy/__init__.py#L187-L196):
```py
    def __getattr__(name):
        if name in submodules:
            return _importlib.import_module(f'scipy.{name}')
        else:
            try:
                return globals()[name]
            except KeyError:
                raise AttributeError(
                    f"Module 'scipy' has no attribute '{name}'"
                )
```
So while the subpackages are independent and lazy loaded, you get them auto-loaded even if you don't spell out the specific import. In other words, originally you couldn't do `scipy.optimize.curve_fit` without first doing `import scipy.optimize`. Now you can do `import scipy as sp; sp.optimize.curve_fit` because the main package getattr autoloads `sp.optimize` the first time you use it.

**Comment by akaszynski** [comment]
@adeak, that's smart, and it's one way to maintain backwards compatibility as we converge towards a stable API. This is even something we could roll out for v0.40 if we were ambitious.

**Comment by adeak** [comment]
My experience from https://github.com/pyvista/pyvista/pull/3764 is that this is a pain in the ass, but we might want to start with adding `__all__` and removing star imports anyway. It was a lot of work that I gave up on eventually, and anyone would be better off starting from scratch. The hard part would be making sure that the "(accidentally) public API" would be unaffected. Which is a lot of words to say that I'd expect 0.40 to be very ambitious.

**Comment by akaszynski** [comment]
> My experience from #3764 is that this is a pain in the ass, but we might want to start with adding `__all__` and removing star imports anyway. It was a lot of work that I gave up on eventually, and anyone would be better off starting from scratch. The hard part would be making sure that the "(accidentally) public API" would be unaffected. Which is a lot of words to say that I'd expect 0.40 to be very ambitious.

I think incrementally updating our API over the next few releases might be the way to go. I agree that a complete overhaul might be out of scope for a single release.

**Comment by adeak** [comment]
I'm wondering how messy/hard to maintain it would be to
1. pull out the plotting-related imports from `_vtk.py` to `_vtk_plotting.py` (so far similar to what @banesullivan suggested)
2. add a helper function to `_vtk.py` that, when called, pulls in all the names from `_vtk_plotting.py` to the `_vtk` namespace
3. make sure that all the plotting-related things in `_vtk` are always used as `from ... import _vtk; _vtk.vtkPlottyThing` rather than `from pyvista._vtk import vtkPlottyThing`
4. decorate all the plotting-related PyVista functions and classes with a `needs_plotting()` decorator (name pending) that calls the helper function in `_vtk`.

Unless there's another major flaw in this idea, it could mean minimal impact on our existing codebase, because we'd only have to add the decorators to each plotting-relevant function and class, and standardise `_vtk` import style, but we wouldn't have to disentangle the imports at compile time.

**Comment by adeak** [comment]
Unless I'm missing something, the above decorator could also catch import errors to tell the user nicely that they can only use the given functionality with GL.

**Comment by banesullivan** [comment]
What I set out to do here has mostly been accomplished in 

- #4486
- #4507 
- #4508 
- #4515

**Comment by banesullivan** [comment]
This is mostly complete. The next step would be to ship the core subpackage as a standalone package which should be tracked in a separate issue
