### ISSUE TITLE
Pressing V Crashes

### ISSUE THREAD

**Issue by akaszynski** [pyvista/pyvista#447]
Pressing `v` kills the renderer:

```
~/.local/lib/python3.7/site-packages/pyvista/plotting/plotting.py in <lambda>()
    229         b_left_down_callback = lambda: self.iren.AddObserver('LeftButtonPressEvent', self.left_button_down)
    230         self.add_key_event('b', b_left_down_callback)
--> 231         self.add_key_event('v', lambda: self.isometric_view_interactive())
    232 
    233 

~/.local/lib/python3.7/site-packages/pyvista/plotting/plotting.py in isometric_view_interactive(self)
    420         interactor = self.iren.GetInteractorStyle()
    421         renderer = interactor.GetCurrentRenderer()
--> 422         renderer.view_isometric()
    423 
    424     def update(self, stime=1, force_redraw=True):

AttributeError: 'NoneType' object has no attribute 'view_isometric'
```

**Comment by banesullivan** [comment]
Weird... I don't have this issue. why would the `interactor.GetCurrentRenderer()` call be returning `None`?

**Comment by GuillaumeFavelier** [comment]
I confirm that I can reproduce although my application does not crash. The scenario where I reproduce it is when I don't click or interact at all with the window and just press 'v'. In this case, I get the message once and then I can continue using the application without perturbation.

**Comment by banesullivan** [comment]
I suppose we could add a check if the current renderer returned is None, then amuse the active renderer that the plotter is tracking.  Should be a small patch

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
