### ISSUE TITLE
Parallelize add_mesh to avoid MultiBlock bottle neck

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#453]
With the new https://github.com/pyvista/pyiges library, its not uncommon to have a `MultiBlock` dataset with over 2,000 blocks (all PolyData). When the number of blocks get high, iterating over that dataset to plot each mesh individually is slowed down drastically in this for loop:

https://github.com/pyvista/pyvista/blob/c64c4b3d7443bd6c54595a083e913badba597da7/pyvista/plotting/plotting.py#L877

I'm wondering if we should make the `add_mesh` function parallelizable so we can fire off a number of threads to add all the meshes to the scene without having that for loop slow everything down

**Comment by banesullivan** [comment]
Considering that the `add_mesh` method adds the attributes `self.mesh` and `self.mapper`, and other methods/calls use those, this might require a serious refactor

**Comment by akaszynski** [comment]
Pyiges development may not continue; its turning out to be quite a bit of work with brep geometry.  I vote to close this issue.

**Comment by banesullivan** [comment]
I use `MultiBlock` containers a lot and with not that big of datasets and this still has a slight bottleneck. For example, the following dataset has 22 blocks with a size of ~380MB when saved to the disk as a VTM file set. If I instantiate a `BackgroundPlotter`, then add that `MultiBlock` dataset to the scene, it looks like this which takes ~11.5 seconds to add it to the scene.

![2019-11-24 12 04 01](https://user-images.githubusercontent.com/22067021/69499727-9ed5ca00-0eb2-11ea-9193-6176deb89372.gif)


If I merge the meshes into a single `UnstructuredGrid`, it takes ~10.5 seconds so that bottleneck isn't really a bottleneck...

Considering that difference is negligible, I agree that we should close this issue. Maybe down the road, it will make sense to parallelize this so that different threads can add datasets to a scene, but for now, this isn't necessary.
