### ISSUE TITLE
GeoVista Integration Testing

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#4565]
@bjlittle has created a truly amazing extension to PyVista for 3D cartographic rendering and I'm using it pretty heavily in my work lately. Considering this project is gaining a good bit of traction, I think we should add it to our integration tests to make sure we account for how it uses PyVista when changing our API.

See https://github.com/bjlittle/geovista

**Comment by bjlittle** [comment]
Wowzers! That would be pretty darn amazing. Thanks for the consideration 🍻

**Comment by tkoyama010** [comment]
We are big fans of GeoVista. We hope to see more development of this package.
