### ISSUE TITLE
Clean up and clarify sampling-like filters

### ISSUE THREAD

**Issue by MatthewFlamm** [pyvista/pyvista#4571]
### Describe what maintenance you would like added.

There was a discussion on slack on the use of sampling-like filters, i.e. `sample`, `probe`, and `interpolate`.  One issue is that it is hard to figure out when to use which filter.  The other issue is that `probe` has the opposite behavior of `sample` and `interpolate` in regards to order of operation (see below).

### Pseudocode or Screenshots

```python
import pyvista as pv

small = pv.ImageData(dimensions=(5, 5, 5))
large = pv.ImageData(dimensions=(10, 10, 10))
print(small.n_points)
print(large.n_points)
print(small.probe(large).n_points)  # gives different result
print(small.sample(large).n_points)
print(small.interpolate(large).n_points)
```

This  gives

```txt
125
1000
1000
125
125
```

**Comment by MatthewFlamm** [comment]
`probe` uses [vtkProbeFilter](https://vtk.org/doc/nightly/html/classvtkProbeFilter.html).  Note that `vtkCompositeDataProbeFilter` is a subclass, and adds the ability to use Composite Data as in input (only one of the two slots in the algorithm).

`sample` uses [vtkResampleWithDataSet](https://vtk.org/doc/nightly/html/classvtkResampleWithDataSet.html#details).  This uses `vtkCompositeDataProbeFilter` under the hood, but also allows composite data to be used in both the source and the input.

So I propose that we deprecate `probe` and only keep `sample` and `interpolate`.

`imterpolate` is separate from the other two since it uses a different sampling/interpolation method.

**Comment by MatthewFlamm** [comment]
The pyvista standard, at least in my experience, is that we should generally expect the shape of the mesh to be equal to the mesh on which the filter attribute is called.  That is, `mesh1.filter(mesh2)` should return a mesh closer to `mesh1`.  This also enables `inplace=True` usage when possible.

So, if we were to keep `probe` we should switch the order of operation, and the deprecation/breaking change would have to be done carefully.  I still think it should be removed entirely instead as above, but wanted to lay out other options.

**Comment by adeak** [comment]
> So, if we were to keep `probe` we should switch the order of operation, and the deprecation/breaking change would have to be done carefully. I still think it should be removed entirely instead as above, but wanted to lay out other options.

From a design standpoint, we'd probably have to do the deprecation the same way: deprecating the od method and introducing a new one that has the right semantics. Switching the input and output is not the kind of change we should subject downstream to.

**Comment by darikg** [comment]
+1 to this, I've definitely been confused by it before. 

> The pyvista standard, at least in my experience, is that we should generally expect the shape of the mesh to be equal to the mesh on which the filter attribute is called. 

+1 again

> From a design standpoint, we'd probably have to do the deprecation the same way: deprecating the old method and introducing a new one that has the right semantics. Switching the input and output is not the kind of change we should subject downstream to.

deprecate `probe` and introduce `eborp` 😉

**Comment by banesullivan** [comment]
+1 for `eborp`

**Comment by punyidea** [comment]
I'd like to add here that probe() currently has functionality which is not present in sample() or interpolate(). To my knowledge, if one is probing an unstructured grid one will get the value of the scalars which the VTK object has at those points exactly. Sample() will use nearest neighbor or something like it, and interpolate() uses other interpolation methods. I'm not a VTK expert myself but I think the functionality of probe is practical, especially if we are reading in vtk objects written from some FEM solver like FENICS.

**Comment by MatthewFlamm** [comment]
> To my knowledge, if one is probing an unstructured grid one will get the value of the scalars which the VTK object has at those points exactly. Sample() will use nearest neighbor or something like it, and interpolate() uses other interpolation methods.

Can you give an example that illustrates the difference?  As you can see in the discussion above `probe` uses the exact same underlying vtk algorithm as `sample`.  But, `sample` uses a class that enables more features like supporting composite data sets.

**Comment by punyidea** [comment]
That is a good question! I remember obtaining different results from sample and probe when I was working with FEniCS objects and I was interested in the exact cell value between sample points. But I just tried the following example and saw no difference. It might have been just a result of some quirks in how I was constructing the dataset, and confusion at reading the documentation of sample(), which may make one think that points are being chosen from nearest neighbor.


```
import pyvista as pyv
import numpy as np

square_points = np.array([[0.,0.,0],[0.,1.,0],[1,1,0],[1,0,0]])
f_val = np.array([0,1,3,2])

pyv_square = pyv.PolyData(square_points)
pyv_triangles = pyv_square.delaunay_2d()

square_mesh = pyv.UnstructuredGrid(pyv_triangles)
assert all(square_mesh.cell_types==5)
square_mesh.set_active_scalars('f',preference='point')

interp_points = pyv.PolyData(np.array([[0,0,0],[.66,.266,0],[.5,.5,0]]))
interp_mesh = interp_points.delaunay_2d()
interp_sample = interp_mesh.sample(square_mesh)
interp_probe = square_mesh.probe(interp_mesh,categorical=False)

print(interp_sample['f'],)
print(interp_probe['f'],) # originally expected non-integer value

p = pyv.Plotter()
p.add_mesh(square_mesh)
p.show()
```

I think this can stay closed, thanks for answering.

**Comment by MatthewFlamm** [comment]
I'm going to assume the behavior with integers is clouded by precision issues.  Try it with a larger range of ints.

**Comment by MatthewFlamm** [comment]
See the discussion here https://docs.pyvista.org/version/stable/examples/01-filter/resample#sphx-glr-examples-01-filter-resample-py.

It tries to explain what the difference is between interpolate and sample.  I think the naming of the filters is confusing, but they are taken partly from vtk
