### ISSUE TITLE
numpydoc needs to run as its own CI check

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#4608]
The doc build takes a long time and very often the only failures are coming from `numpydoc`. This should be a dedicated CI check to help reduce total build time and isolate checks

**Comment by MatthewFlamm** [comment]
We should wait for next release of numpydoc or forge ahead and use the rc here https://github.com/numpy/numpydoc/releases/tag/v1.6.0rc0.  It has a pre-commit check hook and I also think the ability to run as a command line check.  There is currently no good way I know to do this on the current version.

**Comment by akaszynski** [comment]
Pre-commit is the way to go.

I vote using the release candidate if this is a huge pain @banesullivan. I agree that it's frustrating to have it fail 50 minutes into CI when a local check would be ideal.
