### ISSUE TITLE
Plotter not usable through virtual machine/remote connection

### ISSUE THREAD

**Issue by GGDRriedel** [pyvista/pyvista#465]
**Describe the bug, what's wrong, and what you expect:**

Initializing the plotter  throws Error Messages since certain graphics libraries can't be initiated

I figured out it's due to the RDP connection not using the GFX-card, I am working on a fix/looking for a solution. 

**To Reproduce**

Please include a code snippet to reproduce the bug in the block below:

```py
# Insert code here
 plotter = pv.Plotter()
ERROR:root:failed to get wglChoosePixelFormatARB
ERROR:root:failed to get valid pixel format.
ERROR:root:GLEW could not be initialized.
ERROR:root:GLEW could not be initialized.
ERROR:root:failed to get wglChoosePixelFormatARB
ERROR:root:failed to get valid pixel format.
ERROR:root:GLEW could not be initialized.
ERROR:root:GLEW could not be initialized.
```

-----

**System Information:**
 Please run the following code wherever you are experiencing the bug and paste the output below. This report helps us track down bugs and it is critical to addressing your bug:

```py
# Get system info
import pyvista as pv
print(pv.Report())
```

```txt
# Paste system info here
--------------------------------------------------------------------------------
  Date: Fri Nov 22 11:01:21 2019 Mitteleuropäische Zeit

           Windows : OS
                 2 : CPU(s)
             AMD64 : Machine
             64bit : Architecture
           16.0 GB : RAM
           Jupyter : Environment

  Python 3.6.3 |Anaconda, Inc.| (default, Oct 27 2017, 12:22:41) [MSC v.1900
  64 bit (AMD64)]

            0.22.4 : pyvista
             8.1.0 : vtk
            1.16.4 : numpy
             2.6.1 : imageio
             1.4.3 : appdirs
             0.4.3 : scooby
             2.2.2 : matplotlib
             5.9.2 : PyQt5
             7.9.0 : IPython

  Intel(R) Math Kernel Library Version 2019.0.5 Product Build 20190808 for
  Intel(R) 64 architecture applications
--------------------------------------------------------------------------------
```

**Comment by banesullivan** [comment]
If this is a local virtual machine it has more to do with the VM software than PyVista. The only VM software that I know of to support the use of graphics Libraries is VMWare (Parallels doesn’t for example)

As for remote connections, if your running PyVista on a headless setup, you may need to follow the steps in the install section about that: https://docs.pyvista.org/getting-started/installation.html#running-on-remote-servers

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by banesullivan** [comment]
Closing as following the setup guide in the docs or properly configuring the VM will resolve this and isn't in the scope of the project.

**Comment by adizhol** [comment]
@banesullivan 
After following the guide in the docs, I get this error:
```
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  52
  Current serial number in output stream:  53
```

**Comment by Farnsworth1** [comment]
This problem occurs on my Windows 10 machine when accessing it via a remote desktop.
the following error is displayed:
```

2021-01-19 13:39:00.009 (   3.550s) [                ]vtkWin32OpenGLRenderWin:635    ERR| vtkWin32OpenGLRenderWindow (000001B8B31CA530): failed to get wglChoosePixelFormatARB
ERROR:root:failed to get wglChoosePixelFormatARB
2021-01-19 13:39:00.013 (   3.555s) [                ]vtkWin32OpenGLRenderWin:713    ERR| vtkWin32OpenGLRenderWindow (000001B8B31CA530): failed to get valid pixel format.
ERROR:root:failed to get valid pixel format.
2021-01-19 13:39:00.015 (   3.556s) [                ]vtkOpenGLRenderWindow.c:569    ERR| vtkWin32OpenGLRenderWindow (000001B8B31CA530): GLEW could not be initialized: Missing GL version
ERROR:root:GLEW could not be initialized: Missing GL version
Windows fatal exception: access violation
```

**Comment by Farnsworth1** [comment]
I found these suggestions that may help
[](https://stackoverflow.com/questions/51705471/current-state-and-solutions-for-opengl-over-windows-remote)
