### ISSUE TITLE
Extend "fit_plane_to_points" so that it returns a plane that is correctly sized to the extents of points

### ISSUE THREAD

**Issue by user27182** [pyvista/pyvista#4650]
### Describe the feature you would like to be added.

Currently, [`fit_plane_to_points`](https://docs.pyvista.org/version/0.40/api/utilities/_autosummary/pyvista.fit_plane_to_points.html) returns a plane mesh that does not actually "fit" the points in the sense that the size of the plane returned is always static and does not scale with the input data. Perhaps this can even be considered to be a bug (?). The behaviour I expected and would have liked from this function is that the plane be scaled such that it becomes more an oriented 2D bounding box which fully encloses all input points.

For example, the following code fits a plane to a cow and plots both cow and plane.
``` python
import pyvista as pv
import numpy as np
from pyvista import examples
cow = examples.download_cow()
plane, center, normal = pv.fit_plane_to_points(cow.points, return_meta=True)

pl = pv.Plotter()
pl.add_mesh(cow)
pl.add_mesh(plane, color='lightblue', style='wireframe', line_width=4)
pl.show(cpos=[(13.0, 7.6, -13.85), (0.44, -0.4, -0.37), (-0.28, 0.9, 0.3)])
```
However, since the plane is not scaled to fit the cow, it is not visible in the plot:
![image](https://github.com/pyvista/pyvista/assets/89109579/2f4a4538-ae5a-4741-93d9-77908388728e)

We can see the (too small) plane if we plot the cow as wireframe:
![image](https://github.com/pyvista/pyvista/assets/89109579/06c8e0f6-e01f-4fc6-b08d-c4db3ce1474e)

### Pseudocode or Screenshots

My proposed solution is to modify [`fit_plane_to_points`](https://docs.pyvista.org/version/0.40/api/utilities/_autosummary/pyvista.fit_plane_to_points.html) so that the plane which is returned is scaled to fit the input data. In the code below, scaling is done by first projecting the input points onto the best-fit plane, then transforming the points to the plane's coordinate system so that we can calculate the extents of the projection. These extents are then used to control the size of the plane with the  `i_size` and `j_size` parameters of `pv.Plane()`.

``` python 
import pyvista as pv
import numpy as np
from pyvista import examples


def fit_plane_to_points(points, return_meta=False):
    poly = pv.PolyData(points)
    data = np.array(points)
    center = poly.center
    result = np.linalg.svd(data - center)
    i_vector = result[2][0]
    j_vector = result[2][1]
    normal = np.cross(i_vector, j_vector)

    def get_transform(i_vec, j_vec, k_vec, center):
        # get transform that moves data from 'center' to the origin and rotates data to align with i, j, k vectors
        i_vec = np.array(i_vec)
        j_vec = np.array(j_vec)
        k_vec = np.array(k_vec)
        center = np.array(center)

        dim = len(center)

        # create rotation and translation matrices from inputs
        rotate = np.eye(dim + 1)
        rotate[:dim, :dim] = np.vstack((i_vec, j_vec, k_vec))
        translate = np.eye(dim + 1)
        translate[:dim, dim] = -center

        matrix = rotate @ translate
        return matrix

    projected = poly.project_points_to_plane(origin=center, normal=normal)
    transform = get_transform(i_vector, j_vector, normal, center)
    projected.transform(transform)
    i_size = np.max(projected.points[:, 0]) - np.min(projected.points[:, 0])
    j_size = np.max(projected.points[:, 1]) - np.min(projected.points[:, 1])

    plane = pv.Plane(center=center, direction=normal, i_size=i_size, j_size=j_size)
    if return_meta:
        return plane, center, normal
    return plane


cow = examples.download_cow()
plane, center, normal = fit_plane_to_points(cow.points, return_meta=True)

pl = pv.Plotter()
pl.add_mesh(cow)
pl.add_mesh(plane, color='lightblue', style='wireframe', line_width=4)
pl.show(cpos=[(13.0, 7.6, -13.85), (0.44, -0.4, -0.37), (-0.28, 0.9, 0.3)])
```

Running the code will generate the following screenshot with a properly sized plane.
![image](https://github.com/pyvista/pyvista/assets/89109579/4493cc18-0a58-463c-be87-80747f998950)

Alternatively, instead of scaling the plane automatically by default, maybe add a new parameter, e.g. `scale=True`, to control this behaviour.

**Comment by banesullivan** [comment]
+1 for making this properly scaled version the new default

**Comment by banesullivan** [comment]
@user27182, would you be up for implementing this new feature in PyVista?

**Comment by user27182** [comment]
> @user27182, would you be up for implementing this new feature in PyVista?

Sure thing, I can give it a go.
