### ISSUE TITLE
Trame client mode JupyterLab: connection closed error

### ISSUE THREAD

**Issue by dennissergeev** [pyvista/pyvista#4652]
### Describe the bug, what's wrong, and what you expected.

I have recently updated my `pyvista` environment, and I can't get the trame widget working in Jupyter Lab, when I use it both on a remote server _and_ on my local PC.

The error I'm getting is "Connection closed", exactly the same as described by @dannymcculloch in #3979. This happens if I plot the global topographical map example. A "simpler" example such as the cone object does get plotted ok (albeit with a warning: `WARNING:aiohttp.websocket:Client protocols [''] don’t overlap server-known ones ()`).

I primarily use `pyvista` on a remote server via an SSH tunnel. However, I discovered that exactly the same behaviour occurs when I try to do it on my local PC too.

I'm using the latest versions of the key packages (see below).

Thanks in advance.

P.S. On a related note, I typically use pyvista in a separate conda environment (and no, it doesn't help if I install it in the `base` environment either). What is the correct way to setup `trame` and `jupyter-server-proxy` if I use multiple environments? I launch Jupyter Lab from the base environment where I have `nb_conda_kernels` installed.

### Steps to reproduce the bug.

```python
import pyvista as pv
import numpy as np
from pyvista import examples

pv.global_theme.trame.server_proxy_enabled = True
pv.set_jupyter_backend("client")

pv.Cone().plot()  # works

examples.download_topo_global().plot()  # fails
```

I've also tried using the code suggested as a workaround in #3979:
<details>
<summary>host_address workaround</summary>

```python
import os
os.environ['TRAME_DEFAULT_HOST'] = host_address

import pyvista as pv
from pyvista.trame.jupyter import elegantly_launch, launch_server

elegantly_launch(host_address)
# or:
# await launch_server(host_address).ready

pv.global_theme.trame.server_proxy_enabled = True
pv.global_theme.trame.server_proxy_prefix = f"{host_address}:"

pv.set_jupyter_backend("client")
```
</details>

but alas it doesn't help.

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Thu Jul 13 11:26:21 2023 BST

                OS : Linux
            CPU(s) : 8
           Machine : x86_64
      Architecture : 64bit
               RAM : 31.2 GiB
       Environment : Jupyter
       File system : ext4
        GPU Vendor : Intel
      GPU Renderer : Mesa Intel(R) UHD Graphics 620 (KBL GT2)
       GPU Version : 4.6 (Core Profile) Mesa 22.2.5-0ubuntu0.1~22.04.3
  MathText Support : False

  Python 3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:17) [GCC
  12.2.0]

           pyvista : 0.40.1
               vtk : 9.2.6
             numpy : 1.25.1
        matplotlib : 3.7.2
            scooby : 0.7.2
             pooch : v1.7.0
           imageio : 2.31.1
             PyQt5 : 5.15.7
           IPython : 8.14.0
          colorcet : 3.0.1
           cmocean : v3.0.3
        ipyvtklink : 0.2.2
        ipywidgets : 8.0.7
             scipy : 1.11.1
             trame : 2.2.6
      trame_client : 2.9.4
      trame_server : 2.8.1
         trame_vtk : 2.5.4
      nest_asyncio : 1.5.6
--------------------------------------------------------------------------------
```

**Comment by dennissergeev** [comment]
Thank you @banesullivan for the quick response!

> Can you elaborate on this? Are you seeing the same timeout issues with this? Because you shouldn't.. I'm curious if the failure mode for this is different.

To be honest, I'm not sure I'm doing it 100% correctly: I'm getting 500 Internal Server Error. What exactly should I put as `host_address` there? Should I also open a second port-forwarding connection?

In any case, what puzzles me is that even on my local laptop I get the same issue (with no SSH involved!)

> Best solution for now is to just use server-side rendering:
OK, so this works. But it's incredibly slow...

**Comment by banesullivan** [comment]
Ah, if you're getting an error then I suspect it's the wrong address. This can be tricky in remote environments as the connection to the port that trame is launched on will be HTTP and if your Jupyter is HTPPS, then you'll get errors in the browser accessing that.

> OK, so this works. But it's incredibly slow...

"Incredibly"... hm. It shouldn't be too bad...

**Comment by banesullivan** [comment]
I think we need to figure out https://github.com/jupyterhub/jupyter-server-proxy/issues/403 until trame/wslink taps into the JupyterComms infrastructure

**Comment by dennissergeev** [comment]
> Then maybe just setting the port that trame uses ahead of time will work (but you need a different port fro every kernel that runs)

@banesullivan sorry but could you clarify how to set this up please?

> We would just need a good reproducible example.

@jourdain thanks! The easiest example is
```python
from pyvista import examples
examples.download_topo_global().plot()
```

**Comment by Tonione** [comment]
Dear all, I join here since I encountered the same issues as @dennissergeev. Have any of you found a workaround? I found, like @dennissergeev , that setting server mode does indeed end up working, but it is extremely slow and not really usable for large meshes. Thanks in advance for any heads up!

**Comment by jourdain** [comment]
More a FYI that anything else right now.

We are currently working on a trame-jupyter-extension to leverage jupyter-comm infrastructure which will solve that issue while also removing the need to proxy network since everything will go through the Jupyter infrastructure. 

Time wise, we are hopping to have a release of that extension within the next 8 weeks.

**Comment by jourdain** [comment]
Also trame v3.6 which chunk message might actually solve that issue.

**Comment by banesullivan** [comment]
Considering that `trame-jupyter-extension` has been published and solves this issue along with other potential solutions like the chunked messaging, I'm going to mark this issue as closed now (though noting that its still broken under the default jupter-server-proxy configuration)

**Comment by jourdain** [comment]
What is the problem with the default configuration of jupter-server-proxy that does not work?
