### ISSUE TITLE
I referenced the code for creating point clouds in the tutorial and generated point clouds in jupyterab，but result warning "No module named 'trame'"

### ISSUE THREAD

**Issue by leeM2001** [pyvista/pyvista#4654]
### Describe the bug, what's wrong, and what you expected.

import numpy as np
import pyvista as pv
points = np.random.rand(100, 3)
mesh = pv.PolyData(points)
mesh.plot(point_size=10, style='points', color='tan')

D:\anaconda\user\lib\site-packages\pyvista\jupyter\notebook.py:58: UserWarning: Failed to use notebook backend: 

No module named 'trame'

Falling back to a static output.
  warnings.warn(

Why is this happening

### Steps to reproduce the bug.

```python
Insert code here
```
import numpy as np
import pyvista as pv

points = np.random.rand(100, 3)
mesh = pv.PolyData(points)
mesh.plot(point_size=10, style='points', color='tan')

### System Information

```shell
Date: Thu Jul 13 22:35:32 2023 中国标准时间

                OS : Windows
            CPU(s) : 16
           Machine : AMD64
      Architecture : 64bit
               RAM : 13.9 GB
       Environment : Jupyter
ATI Technologies Inc. : GPU Vendor
AMD Radeon(TM) Graphics : GPU Renderer
4.5.14761 Core Profile Context 21.30.02.07 30.0.13002.7003 : GPU Version
                 0 : MathText Support

  Python 3.10.9 | packaged by Anaconda, Inc. | (main, Mar  1 2023, 18:18:15)
  [MSC v.1916 64 bit (AMD64)]

           pyvista : 0.40.1
               vtk : 9.0.3
             numpy : 1.23.5
        matplotlib : 3.7.0
            scooby : 0.5.2
             pooch : v1.4.0
           imageio : 2.26.0
             PyQt5 : 5.15.7
           IPython : 8.10.0
          colorcet : 3.0.1
        ipywidgets : 7.6.5
             scipy : 1.10.0
              tqdm : 4.64.1
            meshio : 4.0.4
        jupyterlab : 3.5.3
      nest_asyncio : Version unknown

  Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904
  for Intel(R) 64 architecture applications
```

**Comment by leeM2001** [comment]
> 您需要`pip install trame ipywidgets`

yeah,thank you,I'll give it a try

**Comment by MRiabov** [comment]
Hmm. Why wouldn't that be installed as a dependency? I imagine `pip` can do that.
