### ISSUE TITLE
HTML ipywidgets broken with v8.x and jupyterlab v4.x

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#4684]
We use `ipywidgets.widgets.HTML` in: 

https://github.com/pyvista/pyvista/blob/781849e0a78b322a1e27e0fd1eef88daa15d24f2/pyvista/trame/jupyter.py#L66

This hasn't been working with ipywidgets v8.x and is giving the classic "Error displaying widget" message

**Comment by banesullivan** [comment]
This might actually be an issue with JupyterLab 4.x

**Comment by alesgenova** [comment]
I have investigated the problem with Jupyterlab v4.x and I think I figured it out (see screenshot):

- When using jupyterlab v4.x we need to use ipywidgets v8.x
- However one of the deprecated pyvista backends (ipyvtklink) forces ipywidgets v7.x even when v8.x is requested
- The end result is that when installing pyvista + jupyterlab + ipywidget you end up with jupyterlab v4.x and ipywidgets v7.x, which breaks most of the backends (client, server, trame)

I see that there is a pending draft PR (https://github.com/pyvista/pyvista/pull/4687) which removes several deprecated backends, including ipyvtklink.
If this PR gets merged I would expect the broken jupyterlab v4.x to get fixed automatically.

![Screenshot 2023-08-16 at 14-16-55 lab - JupyterLab](https://github.com/pyvista/pyvista/assets/15913822/e41a83e0-7034-4434-923c-1f9927a1efe4)

**Comment by adeak** [comment]
@alesgenova did #4687 indeed fix this?

**Comment by alesgenova** [comment]
@adeak It should have, but when testing it I noticed that Jupyter Lab integration is currently broken because of #4844, and should be fixed once v0.4.2.1 is released in the next few hours

**Comment by banesullivan** [comment]
Was this resolved in that release, @alesgenova ?

**Comment by alesgenova** [comment]
@banesullivan I tested it out, as expected it works on `v0.42.1`
