### ISSUE TITLE
Option to use Vuetify 3 in Trame widgets

### ISSUE THREAD

**Issue by annehaley** [pyvista/pyvista#4776]
### Describe the feature you would like to be added.

Trame is migrating its default client type from vue 2 to vue 3 in December 2023 (see item 2 in [this discussion](https://github.com/Kitware/trame/discussions/295)). The current implementation of the trame widgets in `pyvista/trame/ui.py` uses vuetify 2, which is incompatible with the vue 3 client type.

### Pseudocode or Screenshots

Switching over can be as simple as changing the import. In my development version, adding the following lines to `pyvista/trame/ui.py` makes my simple app compatible with the vue 3 client type:
```python
from trame.app import get_server

CLIENT_TYPE = get_server().client_type
if CLIENT_TYPE == 'vue2':
    from trame.widgets import vuetify
else:
    from trame.widgets import vuetify3 as vuetify
```

However, a more robust approach may be desired by the pyvista team. The above "quick fix" has some limitations:
- The trame server client type must be set before the desired widgets are imported
- The vuetify API has slight differences between vuetify 2 and 3. Here are a couple I noticed within the file:
    - `dense=True` -> `density='compact'`
    - `on_icon` -> `true_icon`
    - `off_icon` -> `false_icon`
- The default spacing with vuetify is also slightly different (see below screenshot of plotter controls)
![image](https://github.com/pyvista/pyvista/assets/44912689/bd805eb7-64c0-49e9-b139-60a8ab820b49)

**Comment by akaszynski** [comment]
I'm good with moving to vuetify 3 if you want to submit a PR for it.
