### ISSUE TITLE
module  vtkImageDilateErode3D not found

### ISSUE THREAD

**Issue by paulostrobel** [pyvista/pyvista#4815]
### Describe the bug, what's wrong, and what you expected.

When import Pyvista on remote servers I am getting this error:

File "/gpfs/home/pyvista/pyvista/core/_vtk_core.py", line 380, in <module>
    from vtkmodules.vtkImagingMorphological import vtkImageDilateErode3D
ModuleNotFoundError: No module named 'vtkmodules.vtkImagingMorphological'

### Steps to reproduce the bug.

import pyvista as pv

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Tue Aug 29 11:33:00 2023 BST

                  OS : Linux
              CPU(s) : 32
             Machine : x86_64
        Architecture : 64bit
                 RAM : 125.6 GiB
         Environment : Python
         File system : xfs
          GPU Vendor : Mesa/X.org
        GPU Renderer : llvmpipe (LLVM 14.0.3, 256 bits)
         GPU Version : 4.5 (Core Profile) Mesa 22.0.3
    MathText Support : False

  Python 3.10.8 (main, Feb 11 2023, 20:57:00) [GCC 12.2.0]

             pyvista : 0.42.dev0
                 vtk : 9.0.20210922
               numpy : 1.22.3
          matplotlib : 3.7.1
              scooby : 0.7.1
               pooch : v1.7.0
              pillow : 9.5.0
             imageio : 2.27.0
             IPython : 8.14.0
            colorcet : 3.0.1
             cmocean : v3.0.3
          ipywidgets : 7.8.0
               scipy : 1.8.1
                tqdm : 4.66.1
              meshio : 5.3.4
          jupyterlab : 4.0.5
               trame : 3.1.0
        trame_client : 2.11.2
        trame_server : 2.11.7
           trame_vtk : 2.5.8
       trame_vuetify : 2.3.1
jupyter_server_proxy : 4.0.0
        nest_asyncio : 1.5.7
```

**Comment by tkoyama010** [comment]
Thank you for your report. Your error message is that a particular module of vtk cannot be imported. I could not find the `vtk` version `9.0.20210922` in PyPI. Could you please check import by installing the latest version of vtk using the following command?
```bash
pip install --upgrade vtk
```

**Comment by banesullivan** [comment]
This sounds like an incompatibility with conda-forge's 9.0 VTK build. We need to handle `vtkImageDilateErode3D`'s import with caution.

Unfortunately, at this time, our testing matrix for VTK versions only validates the official wheels on PyPI.

Thanks for raising this! It should be an easy fix to handle this import like this import:

https://github.com/pyvista/pyvista/blob/46a2d12051cf1fd6923477526ec98aed0bdde6b6/pyvista/core/_vtk_core.py#L411-L414
