### ISSUE TITLE
HTML Export is empy 

### ISSUE THREAD

**Issue by OlfwayAdbayIgbay** [pyvista/pyvista#4819]
### Describe the bug, what's wrong, and what you expected.

When trying to export a point cloud as html, it's just empty. The Plotter.show() function works fine, just the html is empty. 

I've also tried this on two different machines, one MacOS the other Ubuntu, both reproduce the same bug. 

### Steps to reproduce the bug.

A minimal example to reproduce this:

```python
import pyvista as pv
import matplotlib.cm as cm
coords = [[0.,0.,0.],[1.,1.,1.],[2.,2.,2.]]
colors = [0.1,0.2,0.3]
c_ = cm.rainbow(colors)
points = pv.PointSet(coords)
points["point_color"] = c_
p = pv.Plotter()
p.add_points(points, style="points_gaussian", point_size=8)
p.export_html("test.html")
p.show()

```

the plot shown in the window works fine, three differently colored points. The html plot is empty. 

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Wed Aug 30 17:56:54 2023 CEST
                OS : Darwin
            CPU(s) : 8
           Machine : x86_64
      Architecture : 64bit
               RAM : 8.0 GiB
       Environment : IPython
       File system : apfs
        GPU Vendor : Apple
      GPU Renderer : Apple M1
       GPU Version : 4.1 Metal - 76.3
  MathText Support : False
  Python 3.9.4 (default, Apr  9 2021, 09:32:38)  [Clang 10.0.0 ]
           pyvista : 0.41.1
               vtk : 9.2.6
             numpy : 1.22.4
        matplotlib : 3.4.2
            scooby : 0.7.2
             pooch : v1.7.0
           imageio : 2.26.1
           IPython : 8.11.0
        ipywidgets : 8.0.4
             scipy : 1.9.1
              tqdm : 4.60.0
             trame : 3.2.4
      trame_client : 2.11.2
      trame_server : 2.11.7
         trame_vtk : 2.5.8
      nest_asyncio : 1.5.6
--------------------------------------------------------------------------------
```

**Comment by tkoyama010** [comment]
`export_html` method uses [vtkjs](https://kitware.github.io/vtk-js/index.html) and `points_gaussian` style is not supported by vtkjs now. So if you want to plot your `points_gaussian` style plot in your browser you need to use [Trame](https://kitware.github.io/trame/). You can [find trame examples file in PyVista repository](https://github.com/pyvista/pyvista/tree/main/examples_trame).

**Comment by banesullivan** [comment]
I want to clarify on @tkoyama010's answer. `export_html()` is actually all going through Trame's export mechanisms which serialize the scene to be rendered in-browser with VTK.js. At this time, VTK.js and Trame's serializing/export mechanisms do not support the `points_gaussian` representation style. I recommend tracking this issue in https://github.com/Kitware/trame-vtk/issues

Closing since I do not think there is much action we can take directly in PyVista for this

**Comment by bdpedigo** [comment]
hi @banesullivan - I ran into the same issue here, but could not find an issue about this raised at the repo you linked. Is there something open already that I'm missing? 

thanks!
