### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by titiger1611** [pyvista/pyvista#4845]
Hi,

For plotting in a Jupyter notebook, I use the recommended backend, `'trame'`:
```python
import pyvista
pyvista.set_jupyter_backend('trame')
```
I can export a scene into an [interactive HTML file](https://github.com/pyvista/pyvista/discussions/1542#discussioncomment-1047907) by clicking on the "Export scene as HTML" button in the scene. However, I would like to export the whole notebook like this. In Jupyter, *File --> Save and Export Notebook As... --> HTML* does not render the PyVista widget, showing only its textual representation:
```
Widget(value="<iframe src=...)
```
Is it possible to export the notebook as an HTML file with the **interactive** scene embedded? If not, I would need to fall back to the `'static'` backend.

_Originally posted by @CsatiZoltan in https://github.com/pyvista/pyvista/discussions/4809_

**Comment by titiger1611** [comment]
import pyvista
pyvista.set_jupyter_backend('trame')

**Comment by titiger1611** [comment]
Widget(value="<iframe src=...)

**Comment by tkoyama010** [comment]
This is a duplication of the https://github.com/pyvista/pyvista/discussions/4809. Let's discuss this there.
