### ISSUE TITLE
Introductory example Finite Element Analysis not running

### ISSUE THREAD

**Issue by benwebr** [pyvista/pyvista#4846]
### Describe the bug, what's wrong, and what you expected.

I installed pyvista on Windows with conda and tried the introductory example Finite Element Analysis. I got the following error:

AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

### Steps to reproduce the bug.

```python
from pyvista import examples
mesh = examples.download_notch_stress()
mesh.plot(scalars='Nodal Stress', component=0, cmap='turbo', cpos='xy')
```

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Tue Sep 05 17:44:14 2023 Mitteleuropäische Sommerzeit

                OS : Windows
            CPU(s) : 8
           Machine : AMD64
      Architecture : 64bit
               RAM : 15.8 GiB
       Environment : IPython
       GPU Details : error
  MathText Support : False

  Python 3.11.4 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 13:38:37)
  [MSC v.1916 64 bit (AMD64)]

           pyvista : 0.42.0
               vtk : 9.0.3
             numpy : 1.24.3
        matplotlib : 3.7.2
            scooby : 0.7.2
             pooch : v1.4.0
            pillow : 9.4.0
           imageio : 2.26.0
             PyQt5 : 5.15.7
           IPython : 8.12.2
          colorcet : 3.0.1
        ipywidgets : 8.0.4
             scipy : 1.11.1
              tqdm : 4.65.0
            meshio : 4.4.6
        jupyterlab : 3.6.3
      nest_asyncio : 1.5.6

  Intel(R) oneAPI Math Kernel Library Version 2023.1-Product Build 20230303
  for Intel(R) 64 architecture applications
--------------------------------------------------------------------------------
```

**Comment by MatthewFlamm** [comment]
I cannot reproduce this error given the code provided but using vtk 9.2.5.  Is this a vtk version problem and not a pyvista one?  Can you provide the full traceback?  It will tell you where this error is raised.  If it is vtk problem, you will either have to upgrade vtk version or downgrade numpy version.

**Comment by benwebr** [comment]
I have upgraded to vtk 9.2.6, and the example works fine. now. Thanks for the hint!
Sorry for the false alarme. I had thought that by installing anaconda, I had compatible versions of all packages. I am completely new to python installation and I am still trying to understand the difference between `conda `and `pip`
