### ISSUE TITLE
Interactive plotters in documentation are now static in dev version

### ISSUE THREAD

**Issue by AlejandroFernandezLuces** [pyvista/pyvista#4877]
### Describe the bug, what's wrong, and what you expected.

The plotters of the landing page that previously were interactive now they show static images. I think this is happening after 0.42 release, but can't confirm, since the latest documentation couldn't be deployed properly due to #4868. The documentation of `pyansys-geometry` was affected by this, by the time we decided to downgrade to PyVista 0.41 and with that version everything seems to work fine.

### Steps to reproduce the bug.

n/a

### System Information

```shell
n/a
```

### Screenshots

![Recording 2023-09-13 at 15 20 36](https://github.com/pyvista/pyvista/assets/17165476/31a0780a-90ee-488a-962b-58b45f071670)

**Comment by tkoyama010** [comment]
Yes, we switched it to the Trame plot in #4687 which other backends have been removed. We have decided that this is unavoidable due to the imperfections of `vtkjs` based backends other than Trame. 
`pyvista-plot` directive which you mentioned is also we should fix to use `Trame`, but it is too complicated for us and we set it to `static`. We need the contribution for it.

**Comment by AlejandroFernandezLuces** [comment]
Thanks for the quick response @tkoyama010 🙂

**Comment by akaszynski** [comment]
This is a frequent request, and was one of the biggest detractors IMO for going over to `trame` as the default (and only) backend. While I do not contest the move, I feel that a `__repr_html_` that allows for the export of trame widgets 
 automagically would be quite valuable. I think this is the scope of `trame`'s vision, and it's indeed possible with Three.js as demonstrated in [jupyter-widgets/pythreejs](https://github.com/jupyter-widgets/pythreejs). This also will allow users to save jupyterlab notebooks as static HTML pages; something that's invaluable for sharing research with those who don't have jupyterlab installed.

Pinging @annehaley and @jourdain to see if we can get any momentum behind this for development.

**Comment by jourdain** [comment]
To clarify, the trame vtk local view widget already allows [exporting the scene](https://github.com/Kitware/trame-vtk/blob/master/trame_vtk/widgets/vtk/common.py#L891), so it can be visualized by a plain js/html viewer. The missing part is to streamline that capability.
