### ISSUE TITLE
PolyData: bad normals when saving PLY/STL meshes

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#488]
**Describe the bug, what's wrong, and what you expect:**

From @AndrewAnnex on slack:
> I am running into an issue where pyvista is not saving out valid ply files or stl files from a `PolyData` object. for ply I get a “bad vertex in face” error from meshlab and ccViewer says the mesh is not triangular. STL files output are less than a kilobyte which is clearly off (ply binary file is 82.9mb). This is all after running triangulate on the mesh, and I am running pyvista 0.22.4 and vtk 8.2.0 in a conda environment. 

-----

**To Reproduce**

Please include a code snippet to reproduce the bug in the block below:

```py
# Some polydata surface mesh
mesh.save("foo.ply")
```

----

**To Fix**

We can fix this by properly computing the normals before saving PolyData meshes

Should we automatically can `self.compute_normals(inplace=True)` in the `save` method for PolyData to mitigate this issue?

**Comment by akaszynski** [comment]
I think this is a good fix.  It will make saving a file take a bit longer, but this would be an annoying bug to track down for most users.  I've never had this issue with `vtk==8.12.0`, so it might be an issue with the latest version on conda.

Either way, I'd rather have working code than fast code, though it's not like normal calculation will really add that much time.

**Comment by banesullivan** [comment]
We can default computing the normals to true only when saving as a none-VTK format to maintain speed when using vtk/vtp formats

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by banesullivan** [comment]
I deal with large VTP meshes often, so I'm in favor of keeping things fast where possible

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
