### ISSUE TITLE
Typo fix sublot -> subplot

### ISSUE THREAD

**Issue by tkoyama010** [pyvista/pyvista#4917]
### Describe the bug, what's wrong, and what you expected.

The word "sublot" shown below is a typo for the "subplot". Please correct it. Please also check for the same typo in other files.
https://github.com/pyvista/pyvista/blob/8330e41310b75d421d9f3a5e7194d0dfd4db1bd2/pyvista/plotting/render_window_interactor.py#L973

### Steps to reproduce the bug.

None

**Comment by yr1404** [comment]
Can I work on this issue?

**Comment by tkoyama010** [comment]
@yr1404 Of course. Please. Thanks!
