### ISSUE TITLE
Bug/Feature Request: add `user_matrix` argument to `add_mesh/add_volume`

### ISSUE THREAD

**Issue by FelipeCybis** [pyvista/pyvista#4929]
### Describe the feature you would like to be added.

In relation to #4928

If we have a scene with an actor and we want to add a second actor to this scene but we want to use a `user_matrix` to this actor, when getting the actor from `add_mesh` or `add_volume` and setting a new `user_matrix`, the bounds axes are not update and we need to call `show_grid` or `show_bounds` again.

```python
# Download a volumetric dataset
import pyvista as pv
from pyvista import examples
import numpy as np

vol = examples.download_knee_full()
# scaling
zoom = np.eye(4)
np.fill_diagonal(zoom[:3,:3], 4)

# translation 
translate = np.eye(4)
translate[:3, 3] = [2, 2, 0]

# rotation
rot = np.eye(4)
rot[1,1] = np.cos(-np.pi/4)
rot[2,2] = np.cos(-np.pi/4)
rot[1,2] = -np.sin(-np.pi/4)
rot[2,1] = np.sin(-np.pi/4)

# shear
shear = np.eye(4)
shear[0, 1] = -1

pl = pv.Plotter()

pl.add_mesh(vol, show_scalar_bar=False)
pl.show_grid()

volume = pl.add_mesh(vol, show_scalar_bar=False)
volume.user_matrix = translate @ rot @ zoom @ shear
# pl.show_grid()

pl.show()
```

![screenshot](https://github.com/pyvista/pyvista/assets/41338087/adb0af4d-9d76-4a0f-996c-b8bb248661e1)

Uncommenting the second `# pl.show_grid()` or if, which is my feature request, there was a `user_matrix` argument in `add_mesh` (and in `add_volume` if ... is accepted) and the user matrix is passed to the actor BEFORE it is added to the renderer, the renderer will know the correct bounds and renderer this:

![screenshot](https://github.com/pyvista/pyvista/assets/41338087/4a15bb73-258b-43f1-a241-c64684682ac3)

**Comment by tkoyama010** [comment]
Close this as #4931 is merged.
