### ISSUE TITLE
pyansys -> ansys

### ISSUE THREAD

**Issue by tkoyama010** [pyvista/pyvista#4930]
### Describe what maintenance you would like added.

We have been using some GitHub Actions from pyansys but recently the organization has changed from pyansys to [ansys](https://github.com/ansys/actions). Please help us by modifying the path.
https://github.com/pyvista/pyvista/blob/17ed0eb49a942b297e61a83a1c8ba828c5922b99/.github/workflows/docs.yml#L136

### Pseudocode or Screenshots

None

**Comment by MihirKohli** [comment]
Can you assign me this issue?

**Comment by tkoyama010** [comment]
Sure. thanks!

**Comment by MihirKohli** [comment]
Resolved https://github.com/pyvista/pyvista/pull/4935

**Comment by MihirKohli** [comment]
Do stable docs also need to be renamed?

**Comment by tkoyama010** [comment]
@MihirKohli Yes. Please.

**Comment by MihirKohli** [comment]
Made changes in commit https://github.com/pyvista/pyvista/pull/4935
