### ISSUE TITLE
Filled Sphere geometric object

### ISSUE THREAD

**Issue by MatthewFlamm** [pyvista/pyvista#4943]
### Describe the feature you would like to be added.

We have `pv.Sphere` which creates the outer surface of a Sphere, but there is also need for using a filled 3D Spheres.  This was discussed in #4914.

### Pseudocode or Screenshots

![image](https://github.com/pyvista/pyvista/assets/39341281/cdbc8e26-c61d-435f-80e8-e279f69998ec)

**Comment by MatthewFlamm** [comment]
The example in that discussion used 1D arrays for radial positions, theta, and phi to define the mesh. This allows for nonlinear sampling in spherical coordinates in any direction. `pyvista.Sphere` only allows for linear sampling by specifying starting and ending phi and theta and the resolution of r, phi and theta.  It would be ideal to design the API to be consistent with `pyvista.Sphere`, but still allow for this flexible sampling.

**Comment by tkoyama010** [comment]
Great idea! It may be a good way to create `pyvista.SphereStructured` like we already have [`pyvista.CylinderStructured`](https://docs.pyvista.org/version/stable/api/utilities/_autosummary/pyvista.CylinderStructured.html) in my mind.

**Comment by MatthewFlamm** [comment]
Good point, in this case it should be `pyvista.SphereUnstructured`?

**Comment by tkoyama010** [comment]
Yeah. It good naming.
