### ISSUE TITLE
Get different result in these two cases for `pv.CylinderSource`

### ISSUE THREAD

**Issue by tkoyama010** [pyvista/pyvista#4956]
### Describe the bug, what's wrong, and what you expected.

We get different result in these two cases for `cyl_source = pv.CylinderSource()`, `cyl_source.output.plot()` and `pl.add_mesh(cyl_source)`.  I think the latter will not have this rotation and translation?

_Originally posted by @MatthewFlamm in https://github.com/pyvista/pyvista/pull/4890#discussion_r1336030697_

### Steps to reproduce the bug.

<table>
<tr>
<td>
<p align="center">
correct
</p>
</td>
<td>
<p align="center">
not correct
</p>
</td>
</tr>
<tr>
<td>

```python
import pyvista as pv

pl = pv.Plotter()
cyl_source = pv.CylinderSource()
cyl_source.output.plot()
```

</td>
<td>

```python
import pyvista as pv

cyl_source = pv.CylinderSource()
pl.add_mesh(cyl_source)
pl.show()
```

</td>
</tr>
<tr>
<td>

![image](https://github.com/pyvista/pyvista/assets/7513610/5e094167-a6c9-4586-afe5-626589d8808b)

</td>
<td>

![image](https://github.com/pyvista/pyvista/assets/7513610/720cb545-317d-42a3-b334-5390134d5773)

</td>
</tr>
</table>

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Tue Sep 26 06:51:19 2023 JST

                  OS : Linux
              CPU(s) : 20
             Machine : x86_64
        Architecture : 64bit
                 RAM : 62.5 GiB
         Environment : IPython
         File system : ext4
          GPU Vendor : Intel
        GPU Renderer : Mesa Intel(R) Graphics (ADL GT2)
         GPU Version : 4.6 (Core Profile) Mesa 23.0.4-0ubuntu1~23.04.1
    MathText Support : False

  Python 3.11.4 (main, Jun  9 2023, 07:59:55) [GCC 12.3.0]

             pyvista : 0.43.dev0
                 vtk : 9.2.4
               numpy : 1.25.2
          matplotlib : 3.7.2
              scooby : 0.7.2
               pooch : v1.7.0
              pillow : 10.0.0
             imageio : 2.31.2
             IPython : 8.15.0
            colorcet : 3.0.1
             cmocean : v3.0.3
          ipywidgets : 8.1.0
               scipy : 1.11.2
                tqdm : 4.66.1
              meshio : 5.3.4
          jupyterlab : 4.0.5
      pytest_pyvista : 0.1.8
               trame : 3.2.4
        trame_client : 2.11.2
        trame_server : 2.11.7
           trame_vtk : 2.5.8
       trame_vuetify : 2.3.1
jupyter_server_proxy : 4.0.0
        nest_asyncio : 1.5.7
--------------------------------------------------------------------------------
```

**Comment by Arnav-2004** [comment]
The problem here is: `cyl_source.output.plot()` does the following:
```py
output.rotate_z(-90, inplace=True)
translate(output, self.center, self.direction)
``` 
because of which the orientation changes

**Comment by Arnav-2004** [comment]
We just want to have the orientation same in both the cases, doesn't matter what direction it is defaulting to right?

**Comment by Arnav-2004** [comment]
Should I make a pr, if you don't mind?

**Comment by tkoyama010** [comment]
Direction is important. We need to make it align the direction of NOT CORRECT to CORRECT.
> Should I make a pr, if you don't mind?

Yes, please. It helps a lot thanks!

**Comment by Arnav-2004** [comment]
Hey, I made some progress and fixed the orientation. However, right now my current solution for this is checking for `isinstance(mesh, pyvista.CylinderSource)` because of which the orientation of `ConeSource` and `MultipleLinesSource`

If I check for `isinstance(cyl_source, _vtk.vtkCylinderSource)` the condition evaluates to `True` but it doesn't seem to be rotating it
```py
>>> isinstance(cyl_source, _vtk.vtkCylinderSource) 
True
```

**Comment by tkoyama010** [comment]
@Arnav-2004 
Thank you for your research! Your understanding sounds right. Could you produce a PR and show it to us?
