### ISSUE TITLE
Button Release Events

### ISSUE THREAD

**Issue by emielkemmm** [pyvista/pyvista#4976]
### Describe the feature you would like to be added.

I'm trying to play around with button release events, but not getting any traction. I've included a minimal working example below.

If I change the event to just `LeftButtonPressEvent`, I can get the callback to work. But otherwise, I'm not seeing what I would expect. In fact, there appear to be numerous events that are not handled. Is there a way to do this?

### Links to VTK Documentation, Examples, or Class Definitions.

https://vtk.org/doc/nightly/html/classvtkCommand.html#a59a8690330ebcb1af6b66b0f3121f8fea9f5bb78d69ea168492a544c1ebc5248c

### Pseudocode or Screenshots

```python

import pyvista as pv
p = pv.Plotter()
s = pv.Sphere()

def cb(s,e):
    print(e,flush=True)

p.iren.add_observer('LeftButtonReleaseEvent',cb)
p.show()

```
Or drag your screenshot here!

**Comment by banesullivan** [comment]
Are you in jupyter? I suspect the event handling is different with the trame interface

**Comment by banesullivan** [comment]
Hm. I just confirmed that `add_observer` isn't working for me either in this example.

Perhaps try using this if you are specifically working with clicks: https://docs.pyvista.org/version/stable/api/plotting/_autosummary/pyvista.Plotter.track_click_position.html

Or you could look at the internal implementation to see how to get it right

**Comment by emielkemmm** [comment]
The use case was specific to handling a release, so although the track click position would give me the position, it would not handle at the correct time. 

I'll look more into internal documentation and see if I can figure it out.

**Comment by banesullivan** [comment]
I wanted to look into this a bit more. It seems there is an issue with registering. `LeftButtonReleaseEvent` specifically (well other click events too) on the interaction.

We can validate that registering callbacks for other events work, like the `MouseMoveEvent`:

```py
import pyvista as pv
import vtk


class CallBack:
    def __init__(self, plotter):
        self.plotter = plotter
        self._i = 0

    def __call__(self, s, e):
        self.plotter.add_text(f"{e}-{self._i}", name="text")
        self._i += 1


pl = pv.Plotter()
pl.add_mesh(pv.Cone())

cb = CallBack(pl)
pl.iren.add_observer(vtk.vtkCommand.MouseMoveEvent, cb)
pl.show()
```

https://github.com/pyvista/pyvista/assets/22067021/b73079f1-380b-474d-83e8-e59800656840

And this similarly works for `LeftButtonPressEvent`:

<img width="624" alt="Screenshot 2023-10-31 at 7 15 22 PM" src="https://github.com/pyvista/pyvista/assets/22067021/ac1907d9-fbc6-4378-8ec3-35a05eabc162">

But this fails for the `LeftButtonReleaseEvent` and `RightButtonReleaseEvent` event 😕 

Which lead me to this post by @jspanchu: https://discourse.vtk.org/t/why-does-vtkrenderwindowinteractor-eat-up-leftbuttonrelease-event/5950

That gave me the idea of adding the observer onto the VTK interaction style which seems to do the trick:

```py
import pyvista as pv
import vtk


class CallBack:
    def __init__(self, plotter):
        self.plotter = plotter
        self._i = 0

    def __call__(self, s, e):
        self.plotter.add_text(f"{e}-{self._i}", name="text")
        self._i += 1


pl = pv.Plotter()
pl.add_mesh(pv.Cone())

cb = CallBack(pl)
pl.iren.interactor.GetInteractorStyle().AddObserver(vtk.vtkCommand.LeftButtonReleaseEvent, cb)
pl.show()
```


https://github.com/pyvista/pyvista/assets/22067021/32a93cc5-0539-46b2-b4dd-c5807894d4dc


I'm not sure if this might have any unintended consequences but hopefully this provides a working solution for you

**Comment by banesullivan** [comment]
Ah, I actually forgot that we expose the observe API on styles a little better (though still a private API):

```py
import pyvista as pv


class CallBack:
    def __init__(self, plotter):
        self.plotter = plotter
        self._i = 0

    def __call__(self, s, e):
        self.plotter.add_text(f"{e}-{self._i}", name="text")
        self._i += 1


pl = pv.Plotter()
pl.add_mesh(pv.Cone())

cb = CallBack(pl)
pl.iren._style_class.add_observer('LeftButtonReleaseEvent', cb)
pl.show()
```

I'm going to open a quick PR to make this a bit more accessible

**Comment by banesullivan** [comment]
Usage pattern in original comment will be possible after #5160
