### ISSUE TITLE
Add `spherical_transform` function

### ISSUE THREAD

**Issue by tkoyama010** [pyvista/pyvista#4979]
### Describe the feature you would like to be added.

`SphericalTransform` will convert (r,phi,theta) coordinates to (x,y,z) coordinates and back again. The equation that is used is $x = r \sin(phi) \cos(theta)$ , $y = r \sin(phi) \sin(theta)$ , $z = r \cos(phi)$ .

_Originally posted by @tkoyama010 in https://github.com/pyvista/pyvista/pull/4965#discussion_r1341733386_

### Links to VTK Documentation, Examples, or Class Definitions.

https://vtk.org/doc/nightly/html/classvtkSphericalTransform.html#details

**Comment by tkoyama010** [comment]
Also see https://github.com/pyvista/pyvista/pull/4965/files#r1341746631

**Comment by user27182** [comment]
See also these related existing undocumented pyvista functions mentioned in this [comment](https://github.com/pyvista/pyvista/pull/4965/files#r1342005467):
- [transform_vectors_sph_to_cart](https://github.com/pyvista/pyvista/blob/9ab97a6532fec0aea0d30c48b4a1ec1b4eb7daa7/pyvista/core/utilities/features.py#L174)
- [grid_from_sph_coords](https://github.com/pyvista/pyvista/blob/9ab97a6532fec0aea0d30c48b4a1ec1b4eb7daa7/pyvista/core/utilities/features.py#L147)
- [cartesian_to_spherical](https://github.com/pyvista/pyvista/blob/9ab97a6532fec0aea0d30c48b4a1ec1b4eb7daa7/pyvista/core/utilities/features.py#L212)
