### ISSUE TITLE
ImageData.points doesn't handle DirectionMatrix

### ISSUE THREAD

**Issue by alexiscltrn** [pyvista/pyvista#5066]
### Describe the bug, what's wrong, and what you expected.

It seems that the ImageData.points property is not handling the image DirectionMatrix correctly. In fact, it has been ignored.

### Steps to reproduce the bug.

```python

import pyvista as pv
import numpy as np

img = pv.ImageData(dimensions=(2,3,4), spacing=(0.5,1.0,1.5), origin=(0., 0.5, 1.0))
img.SetDirectionMatrix((-1, 0, 0, 0, 1, 0, 0, 0, 1))

img.points
#array([[0. , 0.5, 1. ],
#       [0.5, 0.5, 1. ],
#       [0. , 1.5, 1. ],
#       [0.5, 1.5, 1. ],
#       [0. , 2.5, 1. ],
#       [0.5, 2.5, 1. ],
#       [0. , 0.5, 2.5],
#       [0.5, 0.5, 2.5],
#       [0. , 1.5, 2.5],
#       [0.5, 1.5, 2.5],
#       [0. , 2.5, 2.5],
#       [0.5, 2.5, 2.5],
#       [0. , 0.5, 4. ],
#       [0.5, 0.5, 4. ],
#       [0. , 1.5, 4. ],
#       [0.5, 1.5, 4. ],
#       [0. , 2.5, 4. ],
#       [0.5, 2.5, 4. ],
#       [0. , 0.5, 5.5],
#       [0.5, 0.5, 5.5],
#       [0. , 1.5, 5.5],
#       [0.5, 1.5, 5.5],
#       [0. , 2.5, 5.5],
#       [0.5, 2.5, 5.5]])

np.array([img.GetPoint(i) for i in range(img.number_of_points)])
#array([[ 0. ,  0.5,  1. ],
#       [-0.5,  0.5,  1. ],
#       [ 0. ,  1.5,  1. ],
#       [-0.5,  1.5,  1. ],
#       [ 0. ,  2.5,  1. ],
#       [-0.5,  2.5,  1. ],
#       [ 0. ,  0.5,  2.5],
#       [-0.5,  0.5,  2.5],
#       [ 0. ,  1.5,  2.5],
#       [-0.5,  1.5,  2.5],
#       [ 0. ,  2.5,  2.5],
#       [-0.5,  2.5,  2.5],
#       [ 0. ,  0.5,  4. ],
#       [-0.5,  0.5,  4. ],
#       [ 0. ,  1.5,  4. ],
#       [-0.5,  1.5,  4. ],
#       [ 0. ,  2.5,  4. ],
#       [-0.5,  2.5,  4. ],
#       [ 0. ,  0.5,  5.5],
#       [-0.5,  0.5,  5.5],
#       [ 0. ,  1.5,  5.5],
#       [-0.5,  1.5,  5.5],
#       [ 0. ,  2.5,  5.5],
#       [-0.5,  2.5,  5.5]])

```

### System Information

```shell
Date: Thu Oct 12 14:37:23 2023 CEST

                OS : Linux
            CPU(s) : 8
           Machine : x86_64
      Architecture : 64bit
               RAM : 15.0 GiB
       Environment : Python
       File system : ext4
        GPU Vendor : AMD
      GPU Renderer : RENOIR (renoir, LLVM 15.0.7, DRM 3.49, 6.2.0-34-generic)
       GPU Version : 4.6 (Core Profile) Mesa 23.0.4-0ubuntu1~22.04.1
  MathText Support : False

  Python 3.9.13 (main, May 30 2022, 12:53:10)  [GCC 11.2.0]

           pyvista : 0.42.3
               vtk : 9.2.6
             numpy : 1.23.4
        matplotlib : 3.5.2
            scooby : 0.5.12
             pooch : v1.6.0
            pillow : Module not found
           imageio : 2.19.3
           IPython : 8.4.0
        ipywidgets : 7.7.0
             scipy : 1.10.1
              tqdm : 4.64.0
            meshio : 5.3.4
        jupyterlab : 3.4.2
             trame : Version unknown
      trame_client : Version unknown
      trame_server : 2.9.1
         trame_vtk : Version unknown
     trame_vuetify : Version unknown
      nest_asyncio : Version unknown
```

**Comment by MatthewFlamm** [comment]
Good catch.  It looks like PyVista does not use `GetPoint` or similar and ignores this `DirectionMatrix`.  We will either have to implement internal handling for `DirectionMatrix` or leverage the existing vtk methods to get the point positions.  My preference is the latter to avoid more problems like this in the future.

**Comment by banesullivan** [comment]
I agree we should try to use VTK directly for this. Unfortunately iterating over all points with `GetPoint` will not scale and there is no `GetPoints()` for `ImageData` since the points are implicitly defined.

**Comment by banesullivan** [comment]
I think it would be great to open this as a feature request in VTK directly to be able to generate the points array C++ side

**Comment by user27182** [comment]
> I think it would be great to open this as a feature request in VTK directly to be able to generate the points array C++ side

Your wish has been granted! This functionality has been implemented recently. Other structured classes get this functionality too. It's merged in vtk main 10 months ago but not yet released, may be part of 9.4? See `vtkImageData::GetPoints()`:

https://github.com/Kitware/VTK/blob/5c543172ac9ef420b1fac3331888f250e8349ad8/Common/DataModel/vtkImageData.cxx#L171-L178

**Comment by banesullivan** [comment]
Oh just saw your PR, I'll try to help review!

**Comment by user27182** [comment]
> Oh just saw your PR, I'll try to help review!

Thanks! We should definitely use `GetPoints` once that feature is released, but in the mean time (and to support legacy code) I think we can modify our current implementation of `points` to use the direction matrix (this is done as part of #6612)
