### ISSUE TITLE
Capitalize the first letter of the sentence

### ISSUE THREAD

**Issue by tkoyama010** [pyvista/pyvista#5075]
### Describe the bug, what's wrong, and what you expected.

This is a typo. The first letter of the sentence must be capitalized.
https://github.com/pyvista/pyvista/blob/3f8b06f0ee7b05dacf177a10f6219b77e57ac8ff/pyvista/plotting/text.py#L366

### Steps to reproduce the bug.

None

### System Information

```shell
None
```

**Comment by dyaramatreya** [comment]
Hi @tkoyama010 Can I please assign this good first issue to me?

**Comment by tkoyama010** [comment]
@dyaramatreya Done. Thanks!
