### ISSUE TITLE
`pyvista.PolyData.from_regular_faces` Examples section need to show plot output

### ISSUE THREAD

**Issue by tkoyama010** [pyvista/pyvista#5096]
### Describe the bug, what's wrong, and what you expected.

The `pyvista.PolyData.from_regular_faces` example has no plot output, as shown in the code below. Please add plot output so that the results are displayed in the documentation.
https://github.com/pyvista/pyvista/blob/6c55c7ddb90a6fb7f975a58fedfb80332cfb9838/pyvista/core/pointset.py#L898-L905

### Steps to reproduce the bug.

Go to [pyvista.PolyData.from_regular_faces document](https://docs.pyvista.org/version/dev/api/core/_autosummary/pyvista.PolyData.from_regular_faces.html#pyvista.PolyData.from_regular_faces).

### System Information

```shell
None
```

**Comment by TruDarksider** [comment]
This appears to be fixed but not closed. Website and code both have plot calls

**Comment by tkoyama010** [comment]
> This appears to be fixed but not closed. Website and code both have plot calls

Thanks! I didn't notice that!
