### ISSUE TITLE
More complete linking of API methods in Gallery Examples

### ISSUE THREAD

**Issue by MatthewFlamm** [pyvista/pyvista#5111]
### Describe what maintenance you would like added.

The gallery examples are extremely useful to help users get started.  But, often I want to jump from the example to the detailed documentation for the particular method that is used in the example.  An example of a gallery example that does this well is https://docs.pyvista.org/version/stable/examples/01-filter/clipping.html, where links to `clip`, `clip_box` and so on are provided.  An example of a gallery example that does not currently do this well is https://docs.pyvista.org/version/stable/examples/01-filter/project-plane.html where there is no link to `project_points_to_plane`.

### Links to source code.

Example that links to detailed documentation:
https://github.com/pyvista/pyvista/blob/v0.42.3/examples/01-filter/clipping.py

Example that doesn't link to detailed documentation:
https://github.com/pyvista/pyvista/blob/v0.42.3/examples/01-filter/project-plane.py

**Comment by RequieMa** [comment]
I'd like to help this while learning the examples. 
Which branch should I merge if I create a pull request?

**Comment by MatthewFlamm** [comment]
You can use #5811 as an example.  Fork this repo, create a branch off `main`, make changes on that branch, then make PR here requesting to merge to main.
