### ISSUE TITLE
GitHub Dev convatiner needs `OFF_SCREEN`

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#5125]
We need to make sure `OFF_SCREEN=True` is set by default in the codespaces dev container so that pyvista will work out of the box in this environment

**Comment by tkoyama010** [comment]
Ping @MatthewFlamm

**Comment by MatthewFlamm** [comment]
It does work out of the box, at least for me.  Maybe we documentation on it though.  You can open up a live desktop and get an interactive window.

We should make a second container that is off screen though.

**Comment by MatthewFlamm** [comment]
https://github.com/devcontainers/features/tree/main/src/desktop-lite

**Comment by MatthewFlamm** [comment]
I can take the action to make multiple devcontainers and provide some documentation around it.  We can have one devcontainer that uses the current `desktop-lite` feature without `OFF_SCREEN=True``.  We can have one devcontainer that does _not_ have `desktop-lite` feature and uses an OSMESA vtk build with `OFF_SCREEN=True`.  One question is which one should be the default one.  I'd propose the `desktop-lite` feature flavor, but with some documentation around it.

I think we can also add in some text that gets pasted to the default terminal to alert users of the need to open the built-in vnc viewer (or their own vnc client), if we want to go that far.

**Comment by MatthewFlamm** [comment]
It is a game changer...  I only codespaces for developing pyvista now.  I can do a little bit here and little bit there all on different machines and all on the same environment.
