### ISSUE TITLE
multi-window plotting with separated slide bar

### ISSUE THREAD

**Issue by Hailey-Liu** [pyvista/pyvista#513]
Hello all,

I am trying to make 2 by 2 subplots and each of them have their own widget method. However, I could only get all subplots sharing the same widget method. Any ideas on it? Thanks!
 
<img width="514" alt="Screen Shot 2019-12-19 at 5 41 41 PM" src="https://user-images.githubusercontent.com/44219935/71223084-9e4d0b00-2287-11ea-908c-7457694fcf6f.png">

**Comment by banesullivan** [comment]
Huh, I've been playing around with this and I too cannot get the slider widgets to work across difference viewports (subplots). At the moment, this appears to be a bug around the viewport coordinates being used by the slider widgets' representation. I'll keep investigating...

**Comment by banesullivan** [comment]
I can barely get anything to work in the normalized viewport coordinate, so I set the coordinates to use normalized display port coordinates and then run

```py
import pyvista as pv
from pyvista import examples

mesh = examples.load_uniform()


p = pv.Plotter(notebook=0, shape=(1,2))

p.subplot(0,0)
p.add_mesh_threshold(mesh, pointa=(0,0.5), pointb=(0.5,0.5))
p.subplot(0,1)
p.add_mesh_threshold(mesh, pointa=(0,0.5), pointb=(0.5,0.5))

p.link_views()
p.show()
```

<img width="624" alt="Screen Shot 2019-12-19 at 9 55 59 PM" src="https://user-images.githubusercontent.com/22067021/71226604-715e1f80-22aa-11ea-946d-93f52833ccbd.png">

this result makes no sense to me... @GuillaumeFavelier, since you were playing with this earlier in #511, any thoughts on how we might fix this?

**Comment by GuillaumeFavelier** [comment]
I'll take a look and report in here. But looking at your experiments, I'm really surprised by the results in normalized display coordinates, it seems counter intuitive.

**Comment by GuillaumeFavelier** [comment]
I played a bit with `SetCoordinateSystemToNormalizedDisplay()` and I noticed that you can make sense of it if you 'normalize' by the `shape`:

```py
import pyvista as pv


def foo(val):
    pass


def normalize(point, shape):
    return (point[0] / shape[1], point[1] / shape[0])


shape = (2, 4)
# input points lives in normalized coordinates [0, 1]
pointa = (0.2, 0.5)
pointb = (0.8, 0.5)

p = pv.Plotter(shape=shape)

for i in range(shape[0]):
    for j in range(shape[1]):
        p.subplot(i, j)
        p.add_mesh(pv.Sphere())
        p.add_slider_widget(
            callback=foo,
            rng=[0, 1],
            pointa=normalize(pointa, shape),
            pointb=normalize(pointb, shape)
        )

p.show()
```

![2020-01-16_1920x1080](https://user-images.githubusercontent.com/18143289/72530624-059eb080-3870-11ea-919e-8456e3d20573.png)

I still need to investigate for the viewport coordinates.

**Comment by GuillaumeFavelier** [comment]
I went ahead and opened https://github.com/pyvista/pyvista/pull/549

**Comment by banesullivan** [comment]
#549 has a bug handling when the plotter shape is specified by a string like `"1|2"`

```py
p = pv.Plotter(notebook=0, shape="1|2")
p.add_mesh(pv.Sphere())
p.add_slider_widget(lambda *args: args, [0,1])
p.show()
```
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-9-057fb37b6da9> in <module>
      1 p = pv.Plotter(notebook=0, shape="1|2")
      2 p.add_mesh(pv.Sphere())
----> 3 p.add_slider_widget(lambda *args: args, [0,1])
      4 p.show()

~/Software/pyvista/pyvista/pyvista/plotting/widgets.py in add_slider_widget(self, callback, rng, value, title, pointa, pointb, color, pass_widget, event_type)
    756             return (point[0] / shape[1], point[1] / shape[0])
    757 
--> 758         pointa = normalize(pointa, self.shape)
    759         pointb = normalize(pointb, self.shape)
    760 

~/Software/pyvista/pyvista/pyvista/plotting/widgets.py in normalize(point, shape)
    754 
    755         def normalize(point, shape):
--> 756             return (point[0] / shape[1], point[1] / shape[0])
    757 
    758         pointa = normalize(pointa, self.shape)

IndexError: tuple index out of range
```

**Comment by dcbr** [comment]
If I understand correctly, you need to normalize the slider's points w.r.t. the active renderer's viewport? In that case, I think changing the normalize function to:
```
def normalize(point, viewport):
        return (point[0]/(viewport[2]-viewport[0]),point[1]/(viewport[3]-viewport[1])
```
and calling it like `pointa = normalize(pointa,self.renderer.GetViewport())` should do the trick?
Note that this is just an idea and untested, if you want I can try it out next weekend!

**Comment by banesullivan** [comment]
@dcbr, I think that normalize function you suggest will work! If you are able to open a PR for this, it would be greatly appreciated - then we can resolve this issue and move forward with #696.

Some brute force testing will be required (like putting a bunch of slider widgets all over the grouped subplots) and making sure the tests/cases from #549 all still work
