### ISSUE TITLE
Separating tests by utility

### ISSUE THREAD

**Issue by pandas-a11y-11** [pyvista/pyvista#5169]
### Describe the feature you would like to be added.

Tests are hard to run with base requirements only installed (without documentation-related packages & tests, as documentation tests are not in fact separated). This makes development for core functionality & features harder, e.i. only core-function, without optional dependencies, should be located in .

**Comment by akaszynski** [comment]
There's a few ways we can do this:
1. Change the structure of the tests.
2. Mark any test requiring documentation dependencies to be excluded with something like:
```py
import pytest

@pytest.mark.optional_dependency
def test_function():
    # test code that requires the optional dependency
```

For the moment, running `pytest tests/core` should be sufficient to test the "core" functionality, but did you have a different approach in mind?

**Comment by pandas-a11y-11** [comment]
Second approach would exactly suffice, as long as it removes documentation-specific requirements from running tests that are not documentation-tests.
