### ISSUE TITLE
SurfaceNets to visualize 3D label maps

### ISSUE THREAD

**Issue by jmargeta** [pyvista/pyvista#5170]
### Describe the feature you would like to be added.

Hi folks, I often a need to visualize semantic label maps from 3D medical images.

These are regular grids, where each voxel of the label map is a discrete label that usually represents some tissue.  
Image thresholding followed by surface extraction (as discussed [here](https://github.com/pyvista/pyvista/discussions/2434)) works ok, but is extremely slow for many labels. Moreover, as each label is handled separately, there are no guarantees for consistency of the generated contours.

![image](https://github.com/pyvista/pyvista/assets/1239359/4f227944-5589-4b0a-984f-cede2b2cb764)

[SurfaceNets by S. Frisken](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9623606/) solve these issues. They are superfast (easily a few orders of magnitude faster for my use case), look better and are much more accurate.

Not long ago, they have been implemented in VTK and are now available in a pre-release Python version. Although wrapping this is not too hard and having an extra function is fine too, supporting this in PyVista out of the box would be fantastic.

I think that this fits the best into uniform_grid filters. However, I am not sure about keeping the original name, SurfaceNets.

Everyone should be able to visualize segmentation maps, parcelations, multi-label machine learning ground-truth and outputs, etc.

What do you think?

### Links to VTK Documentation, Examples, or Class Definitions.

[Blog post about this being in VTK](https://www.kitware.com/really-fast-isocontouring/)
[My gist with a simple functional wrapper](https://gist.github.com/jmargeta/1e8d383fe121458a1c5ecf6a109c82cc/) and [X post with some more examples](https://twitter.com/jmargeta/status/1719489527541100931)
[Slicer issue about integrating this](https://github.com/Slicer/Slicer/issues/7103)
[vktSurfaceNets3d class definition](https://vtk.org/doc/nightly/html/classvtkSurfaceNets3D.html)
[Frisken SF. SurfaceNets for Multi-Label Segmentations with Preservation of Sharp Boundaries. J Comput Graph Tech. 2022 Jan-Mar;11(1):34-54. Epub 2022 Feb 28. PMID: 36325473; PMCID: PMC9623606.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9623606/)

### Pseudocode or Screenshots

This is a minimal example to generate the image above, see the [gist](https://gist.github.com/jmargeta/1e8d383fe121458a1c5ecf6a109c82cc/) for the functional wrapper.
```python
"""A quick conversion of label maps to colored meshes."""

import pooch
import pyvista as pv
import vtk

root = "https://github.com/neurodata/neuroparc/raw/master/atlases/label/Human"
file_name = pooch.retrieve(
    f"{root}/Schaefer1000_space-MNI152NLin6_res-1x1x1.nii.gz",
    known_hash="c3efe797aab3b3d9e705645bf29fac4e932c88dbe54ccaeb03982f11e66b3249"
)
label_map = pv.read(file_name)

sn = vtk.vtkSurfaceNets3D()
sn.SetInputData(label_map)
sn.GenerateLabels(1000, 1, 1000)
sn.SmoothingOn()
sn.Update()

mesh = pv.wrap(sn.GetOutput())
mesh.plot(cmap="glasbey_bw", show_scalar_bar=False)
```

**Comment by akaszynski** [comment]
We'd be happy to have that functionality. Would you mind submitting a PR for this? Ideally with an example (as described in this PR).
