### ISSUE TITLE
Grid.cast_to_polydata?

### ISSUE THREAD

**Issue by darikg** [pyvista/pyvista#5174]
### Describe the feature you would like to be added.

There's a bunch of other convenient `cast_to` methods but no `cast_to_polydata` for the various grid classes. Is `extract_surface()` always the right method here? I wonder if adding a `class Grid: def cast_to_polydata(self): return self.extract_surface()` would aid discoverability because I always forget that method exists.

**Comment by akaszynski** [comment]
I'd consider a cast to be keeping the topology constant the same but changing how it's represented. Extracting the surface changes the topology, so I'd say it's not valid for `Grid` --> `PolyData` using `extract_surface`.

**Comment by darikg** [comment]
You're right of course. I was thinking of cases like `poly_data.extract_cells(...)` which returns an UnstructuredGrid, which, in my mind, as a subset of a PolyData is itself already surface, so I have trouble thinking of `extract_surface` as the right thing to convert back to a PolyData.
