### ISSUE TITLE
Documentation Coverage

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#519]
I’m realizing that not all of the API is covered in the documentation. Is there a way we can run sphinx and report the coverage for what is autodoc’d in the docs?

It would be ideal to have this at 100%

**Comment by tkoyama010** [comment]
FYI this may works. Thank @tk0miya for advice.
https://www.sphinx-doc.org/en/master/usage/extensions/coverage.html

**Comment by tkoyama010** [comment]
@banesullivan I made a PR #605 . But it may not be what you want.

**Comment by GuillaumeFavelier** [comment]
Is this issue solved by #605 ?

**Comment by banesullivan** [comment]
I don't think so

**Comment by tkoyama010** [comment]
I agree this is not enough.
