### ISSUE TITLE
`n_faces` does not update after `.clean()`

### ISSUE THREAD

**Issue by Louis-Pujol** [pyvista/pyvista#5201]
### Describe the bug, what's wrong, and what you expected.

Hello,

Just found something that looks like a bug in the example provided in [the `clean()` documentation](https://docs.pyvista.org/version/stable/api/core/_autosummary/pyvista.PolyDataFilters.clean.html). Actually the code :

```python
import pyvista as pv
import numpy as np

points = np.array(
    [[0, 0, 0], [0, 1, 0], [1, 0, 0]], dtype=np.float32
)
faces = np.array([3, 0, 1, 2, 3, 0, 2, 2])
mesh = pv.PolyData(points, faces)
mout = mesh.clean()
mout.faces

print(f"faces: {mout.faces}")
print(f"n_faces: {mout.n_faces}")
```

returns

```
faces: [3 0 1 2]
n_faces: 2
```
I was expected `n_faces: 1` instead. Inspecting the `_get_output` function, it seems that VTK does not update the number of cells when cleaning a PolyData (but it updates n points as I expteced). It looks weird to me, but perhaps there is a reason for this behavior. Do you think it should be kept as it is in PyVista or the `n cells` attribute must be updated in this situation ?

Thanks,

### Steps to reproduce the bug.

```python
import pyvista as pv
import numpy as np

points = np.array(
    [[0, 0, 0], [0, 1, 0], [1, 0, 0]], dtype=np.float32
)
faces = np.array([3, 0, 1, 2, 3, 0, 2, 2])
mesh = pv.PolyData(points, faces)
mout = mesh.clean()
mout.faces

print(f"faces: {mout.faces}")
print(f"n_faces: {mout.n_faces}")
```

### System Information

```shell
Date: Fri Nov 17 14:20:47 2023 CET

                OS : Linux
            CPU(s) : 20
           Machine : x86_64
      Architecture : 64bit
               RAM : 31.0 GiB
       Environment : Jupyter
       File system : ext4
        GPU Vendor : NVIDIA Corporation
      GPU Renderer : NVIDIA RTX A2000 8GB Laptop GPU/PCIe/SSE2
       GPU Version : 4.5.0 NVIDIA 545.23.06
  MathText Support : False

  Python 3.9.18 (main, Aug 25 2023, 13:20:04)  [GCC 9.4.0]

           pyvista : 0.42.3
               vtk : 9.3.0
             numpy : 1.26.2
        matplotlib : 3.8.1
            scooby : 0.9.2
             pooch : 1.8.0
            pillow : 10.1.0
...
              tqdm : 4.66.1
             trame : Version unknown
      nest_asyncio : 1.5.8
```

**Comment by darikg** [comment]
that's confusing! I think what's happening is `clean` is converting the second degenerate face to a line.

```python
print(f"lines: {mout.lines}")
print(f"n_lines: {mout.n_lines}")
```
> lines: [2 0 2]
n_lines: 1

`PolyData.n_faces` returns `PolyData.n_cells` which returns `vtkPolyData.GetNumberOfCells()`. That must be include the number of lines in the count.

`mout.GetPolys().GetNumberOfCells()` correctly returns 1

Alternatively, `mesh.clean(polys_to_lines=False)` won't create that line cell, so `mout.n_faces == 1`

**Comment by darikg** [comment]
Strips and vertices also contribute to the total n_faces count:

```python
mesh = pv.PolyData([[1.0, 0.0, 0.0], [1.0, 1.0, 1.0]])
print(f'faces={mesh.faces}, n_faces={mesh.n_faces}, n_verts={mesh.n_verts}')
# faces=[], n_faces=2, n_verts=2

mesh = pv.Rectangle().extrude((0, 0, 1), capping=False)
print(f'faces={mesh.faces}, n_faces={mesh.n_faces}, n_strips={mesh.n_strips}')
# faces=[], n_faces=4, n_strips=4
```

Could maybe define a new property `n_faces_strict = self.GetPolys().GetNumberOfCells()` and add notes to `n_faces`? Changing the behavior of `n_faces` would be difficult to handle in a backwards compatible way

**Comment by MatthewFlamm** [comment]
This is a problem.  We already have `n_cells` and `vtkPolyData` has a `GetNumberOfPolys` method.  If we want to avoid a hard to find switch, Id rather deprecate and then remove `n_faces` and implement something like `n_faces_strict`.  Then reintroduce `n_faces` later.  Or we do an even harder change and switch everything to the vtk `polys` naming instead.
 https://vtk.org/doc/nightly/html/classvtkPolyData.html#a717fbb31ac839efa175f57bbfa737b8c

**Comment by darikg** [comment]
yeah I'm thinking now that `n_faces` is such an intuitive spelling, and like you said we already have `n_cells`, that it's probably worth the whole tedious deprecation cycle to reintroduce `n_faces`.

**Comment by tkoyama010** [comment]
@darikg Is it OK to close this issue?
