### ISSUE TITLE
Check that arrays with padding are valid

### ISSUE THREAD

**Issue by Louis-Pujol** [pyvista/pyvista#5217]
### Describe the feature you would like to be added.

Hi !

I realized that `PolyData` can be initialized with `strips`, `faces` or `lines` that are invalid, as in the following examples :

```python
import pyvista as pv
import numpy as np

faces = np.array([3, 0, 1, 2, 3, 0])
points = np.random.rand(4, 3)
mesh = pv.PolyData(points, faces=faces)
print(mesh.faces)
>>> [   3    0    1    2    3    0   64 1009]

strips = np.array([5, 0, 1, 2])
points = np.random.rand(4, 3)
mesh = pv.PolyData(points, strips=strips)
print(mesh.strips)
>>> [   5    0    1    2   48 2529]

lines = np.array([5, 0, 1, 2])
points = np.random.rand(4, 3)
mesh = pv.PolyData(points, lines=lines)
print(mesh.lines)
>>> [   5    0    1    2   48 4609]
```

It seems that the memory is read outside the numpy arrays. I wrote a checker to assess that an array with padding is valid :

```python
def is_valid(list_padding):
    """Determines if a list with padding is valid."""
    if len(list_padding) == 0:
        return True
    
    offset = list_padding[0]
    if len(list_padding) < offset + 1:
        return False

    return is_valid(list_padding[offset + 1:])
```

Do you think it could be a good idea to integrate it somewhere ? (in [`validation`](https://github.com/pyvista/pyvista/pull/5100) ?) Let me know, I can work on the integration if requested.

### Pseudocode or Screenshots

```python
Insert code here
```
Or drag your screenshot here!

**Comment by tkoyama010** [comment]
@Louis-Pujol I'm fine to add this. Could you open a PR for this?
