### ISSUE TITLE
Image as background

### ISSUE THREAD

**Issue by dennissergeev** [pyvista/pyvista#522]
## Description

I'm probably being too lazy, but I haven't found any example of setting a background of `Plotter` to an image. Is it possible at all? `Plotter.set_background()` seems to work only with colours.

Thanks.

**Comment by GuillaumeFavelier** [comment]
If you don't mind I can expriment with this one, I have a prototype running:

![output](https://user-images.githubusercontent.com/18143289/73972514-43e43880-4921-11ea-9cf0-c2ec909f506f.gif)

**Comment by banesullivan** [comment]
@GuillaumeFavelier! Super cool! I'd love to see your PR for this or if it fits into #367

**Comment by dennissergeev** [comment]
Thanks @GuillaumeFavelier ! This is brilliant!
