### ISSUE TITLE
macOS: quit Python spawned by BackgroundPlotter

### ISSUE THREAD

**Issue by sampotter** [pyvista/pyvista#523]
On macOS, when I use BackgroundPlotter from a Jupyter notebook (Jupyter Lab, specifically),  a new instance of Python appears to be started when BackgroundPlotter is called (e.g., it shows up in the Dock). If I close this Qt window or try to quit this instance of Python, it has no effect. To prevent a ton of Python instances from polluting my dock, I need to force quit each one after I'm done.

(I did search through some of the closed issues, and it seems that this may not be new...)

**Comment by sampotter** [comment]
Sorry, I was mistaken. It appears that new Python instances are not being spawned each time BackgroundPlotter is called.

**Comment by banesullivan** [comment]
Hey, @sampotter - this is an annoying issue that I've been aware of at least. To my knowledge, a the icon in the doc is not a new instance of Python but rather something the MacOS does as soon as the running Python thread has a GUI.

Matplotlib will do the same thing if you use the `%matplotlib qt` magic command from the notebook environment.

We've been meaning to make a nice custom logo for that icon that appears (ref https://github.com/pyvista/pyvista/issues/201#issuecomment-515565924)

**Comment by banesullivan** [comment]
Added the `wontfix` label as to my knowledge, this is something we simply cannot control. If someone knows how to control the icon that appears, please chime in!
