### ISSUE TITLE
make embeddable jupyter widget compatible with `nbconvert`

### ISSUE THREAD

**Issue by francesco-ballarin** [pyvista/pyvista#5231]
### Describe the feature you would like to be added.

The embeddable jupyter widget introduced in #5168 is not yet compatible with `nbconvert`, see https://github.com/pyvista/pyvista/pull/5168#issuecomment-1820845809

It would be great if
```
jupyter nbconvert --to html --execute notebook.ipynb
```
produced an html file with the widget correctly rendered.

### Pseudocode or Screenshots

<img src="https://private-user-images.githubusercontent.com/11783908/284579903-3f2f01b6-16a3-4817-849f-58b561bc77ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwMzA3NzcsIm5iZiI6MTcwMTAzMDQ3NywicGF0aCI6Ii8xMTc4MzkwOC8yODQ1Nzk5MDMtM2YyZjAxYjYtMTZhMy00ODE3LTg0OWYtNThiNTYxYmM3N2VhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI2VDIwMjc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0NjRmNTJhNWM5OTkyZjRkNGU3NmZkMWM4ZTRmMWUyN2FiMGU1NzQ4Y2E1NGQ0NjJkZTZhMWFhYmY3OWFlNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YGYtkntV0GKLN9LReAdt67G0zpCJslnBkg5JVgoOXcA">

**Comment by FelipeCybis** [comment]
Hi all, I am also trying to get the offline viewer to work in standalone html... here is my results (code and html https://github.com/FelipeCybis/trame_quarto_example):

`jupyter nbconvert --to html .\test_pyvista_quarto.ipynb --execute` works out of the box
```
pyvista==0.43.1
nbconvert==7.13.0
ipywidgets==8.1.1
trame==3.4.0
trame-client==2.14.1
trame-server==2.13.1
```

With [Quarto](https://quarto.org/) which is what I would like to use, there is a mess up in the embedding of the ipywidget and I made this question https://github.com/quarto-dev/quarto-cli/discussions/7968 to see if they have any suggestions.

**Comment by francesco-ballarin** [comment]
Thanks @FelipeCybis, updating the version of `nbconvert` did the trick for me!

I can confirm that I am now able to export to html file with nbconvert and see the html widget, see for instance
https://multiphenics.github.io/tutorials/03_lagrange_multipliers/tutorial_lagrange_multipliers_linear.html


@FelipeCybis, can you confirm that the remaining issue you have is due to Quarto itself, rather than pyvista? If so, I think I can close this issue. Future readers who encounter the same may want to double check that `nbconvert` is indeed up to date.
