### ISSUE TITLE
Make handling vector values easier: Feature Request(s)

### ISSUE THREAD

**Issue by MatthewFlamm** [pyvista/pyvista#524]
**Describe the bug, what's wrong, and what you expect:**
Please let me know if this should be 2 or 3 separate issues/requests, but they are all potentially related to the same use case, and implementation of one might make another moot.  So I submitted as a single issue.

This example code only plots the second component of the vector valued `values`.  This was not my expected behavior.  Paraview (at least the GUI) defaults to the magnitude of the vector.  So the first request would be to default to the magnitude of the vector in this case.

```py
import pyvista as pv
import numpy as np
values = np.empty((1000, 2))
values[:, 0] = 0
values[:, 1] = 10
shape = (20, 5, 10)
grid = pv.UniformGrid()
grid.dimensions = np.array(shape) + 1
grid.origin = (100, 33, 55.6)  # The bottom left corner of the data set
grid.spacing = (1, 5, 2)  # These are the cell sizes along each axis
grid.cell_arrays["values"] = values
# Plots only the second component of values, i.e. values[:, 1]
grid.plot(show_edges=True, scalars="values")
```

The second request would be to enable accessing the individual components for plotting or other purposes.  Something like `grid.plot(scalars="values", component=0)`.  The only way I know how to do this now is to create a new scalar, which is not ideal if the dataset is very large.  

It also has its own quirky issues to deal with.  For example, the easiest attempt fails because `values[:, 0]` is not C_CONTIGUOUS, so we have to wrap it with np.ascontiguousarray.

```py
grid.cell_arrays["values_component0"] = values[:, 0] # fails
grid.cell_arrays["values_component0"] = np.ascontiguousarray(values[:, 0]) # works
```

The third request (possibly made moot if the second request is implemented), would be to wrap non-C_CONTIGUOUS arrays internally so the user doesn't have to think about it.

**System Information:**
 Please run the following code wherever you are experiencing the bug and paste the output below. This report helps us track down bugs and it is critical to addressing your bug:

```py
# Get system info
import pyvista as pv
print(pv.Report())
```

```txt
--------------------------------------------------------------------------------
  Date: Thu Jan 09 14:44:03 2020 EST

             Linux : OS
                56 : CPU(s)
            x86_64 : Machine
             64bit : Architecture
           IPython : Environment

  Python 3.7.3 (default, Mar 27 2019, 22:11:17)  [GCC 7.3.0]

            0.22.4 : pyvista
             8.2.0 : vtk
            1.15.4 : numpy
             2.6.1 : imageio
             1.4.3 : appdirs
             0.4.3 : scooby
             3.0.2 : matplotlib
               5.6 : PyQt5
             7.2.0 : IPython
             7.4.2 : ipywidgets
--------------------------------------------------------------------------------
```

Thanks in advance for considering.

**Comment by banesullivan** [comment]
Hi @MatthewFlamm, thanks for posting!

### First Issue

> This example code only plots the second component of the vector valued values. This was not my expected behavior. Paraview (at least the GUI) defaults to the magnitude of the vector. So the first request would be to default to the magnitude of the vector in this case.

PyVista will plot the norm of any multi-component array (`np.linalg.norm(arr, axis=1)`) which is what you are seeing. This is the same as ParaView; if you save the `grid` and load it in ParaView, you'll get the same scalar mapping (`grid.save("~/Desktop/foo.vtk")`)

https://github.com/pyvista/pyvista/blob/86a45088696f157c9c5751f214d4feb49a1091fa/pyvista/plotting/plotting.py#L1134

Note how after plotting the `grid` has a newly computed array called `"values-normed"` - that's actually what is mapped

### Second issue

> The second request would be to enable accessing the individual components for plotting or other purposes. Something like grid.plot(scalars="values", component=0). The only way I know how to do this now is to create a new scalar, which is not ideal if the dataset is very large.

This is an interesting idea and something we could implement rather simply! I'll leave this as the main feature request of this issue.


### Third issues

Huh, I'll look into this. We've done some work in the past so that users shouldn't have to think about the array ordering... pinging @akaszynski on this

**Comment by MatthewFlamm** [comment]
You are totally right on the first one :man_facepalming: .  Somehow I had convinced myself otherwise, and then cooked up a really poor example with a component with value=0.  Maybe I can change this request to document this behavior better.  I don't see it called out anywhere in the documentation.

The third issue I think is moot in my use case if the second issue is fixed.

**Comment by banesullivan** [comment]
Sounds good! I'll see if I can get around to implementing the component argument.

I'll also add the `documentation` and `FRIDocs` tags to better document how multi-component arrays are handled

**Comment by MatthewFlamm** [comment]
I'm coming back to trying to implement this.  The approach in #543 and #598 utilized the current implementation of either directly extracting the norm of the vector or a single component.  Another approach to this is to try and utilitze the in-built vtk functionality.

Here are some findings on using vtk functionality for this:

[This comment](https://github.com/pyvista/pyvista/pull/543#issuecomment-579635250) couldn't use `SetArrayComponent` of `vtkMapper`.  Reading this class closer, [`SelectColorArray`](https://vtk.org/doc/nightly/html/classvtkMapper.html#a3514b38abe732117ce44f51d28fd2838) specifically states that

> The lookup table will decide how to convert vectors to colors.

vtkLookupTable has a (`MapVectorsThroughTable`)[https://vtk.org/doc/nightly/html/classvtkScalarsToColors.html#a55abf196da147f0cb284a6c0a663ae68] function.  This class also has a lot of settings that may obviate the need for a lot of the logic in `add_mesh`, including RGB arrays and vectors.
