### ISSUE TITLE
Wrong result - Rename the "implicit_distance" after compute_implicit_distance filter

### ISSUE THREAD

**Issue by Jimmy-KL** [pyvista/pyvista#5244]
### Describe the bug, what's wrong, and what you expected.

After the _implicit distance_ of a dataset is computed, I tried to rename it using the method `rename_array`.  But I got a different data array result from the original one which means not only the name was changed.
I noticed the `rename_array` uses the `pop` method of` point_data` or `cell_data`. Then I did more research and found it seems there is a bug in the `pop` method.
I did a simple example (check the code in the next block) and got the same bug in my project. However, the strange thing is that in my data array can work well with the method `rename_array`, only the _implicit distance_ data array cannot work.

### Steps to reproduce the bug.

Here is a simple example
```python
import pyvista as pv

sphere = pv.Sphere(radius=5)
plane = pv.Plane()

new_sphere = sphere.compute_implicit_distance(plane)
new_sphere["pd"] = range(new_sphere.n_points)
new_sphere.plot(scalars="implicit_distance")

new_sphere.rename_array("implicit_distance", "im")
new_sphere.rename_array("pd", "pdc")
new_sphere.plot(scalars="im")
```
The bug is obvious when running the above example.

### System Information

```shell
Date: Tue Nov 28 19:39:51 2023

                OS : Windows
            CPU(s) : 16
           Machine : AMD64
      Architecture : 64bit
               RAM : 15.8 GiB
       Environment : Python
        GPU Vendor : Intel
      GPU Renderer : Intel(R) UHD Graphics
       GPU Version : 4.5.0 - Build 31.0.101.1999
  MathText Support : False

  Python 3.11.5 | packaged by conda-forge | (main, Aug 27 2023, 03:23:48) [MSC
  v.1936 64 bit (AMD64)]

           pyvista : 0.42.3
               vtk : 9.2.6
             numpy : 1.24.3
        matplotlib : 3.7.1
            scooby : 0.7.2
             pooch : v1.7.0
            pillow : 10.0.0
           imageio : 2.31.2
           IPython : 8.14.0
             scipy : 1.11.1
            meshio : 5.3.4
      nest_asyncio : 1.5.6

  Intel(R) oneAPI Math Kernel Library Version 2023.1-Product Build 20230303
  for Intel(R) 64 architecture applications
```

### Screenshots

Original Data
![original_data](https://github.com/pyvista/pyvista/assets/114913030/6c48a178-af58-458e-80d0-426fa2c11f58)
Renamed Data
![renamed_data](https://github.com/pyvista/pyvista/assets/114913030/a1fc76f4-af12-4534-83c2-d5c8722a78f4)

**Comment by darikg** [comment]
Interesting. I think you're on the right track suspecting `pop`. It looks to me like that's decreasing the reference count, so that when the python array goes out of scope the reference count drops to zero, triggering VTK's garbage collection. The same problem can be made to occur with manual array assignment as long as it's assigned inside of a function. Here's an MRE:

```python
import pyvista as pv
import numpy as np

def rename(point_data, old, new):
    point_data[new] = point_data.pop(old)

def make_mesh():
    mesh = pv.Sphere()
    mesh.point_data['orig'] = np.ones(mesh.n_points)
    return mesh

# Doesn't always happen on the first try, presumably due to GC vagaries
for i in range(1000):
    mesh = make_mesh()
    rename(mesh.point_data, 'orig', 'renamed')
    if (mesh.point_data['renamed'] != 1).any():
        print(f'Failed on iter {i}')
        break
else:
    print(f'Success')
```

It can be fixed with something like

```python
def rename(point_data, old, new):
    arr = point_data.pop(old)
    arr.VTKObject.SetReferenceCount(arr.VTKObject.GetReferenceCount() + 1)
    point_data[new] = arr
```

but I don't know enough about the pyvista/vtk memory management interaction to know if that's the right thing to do at all

**Comment by darikg** [comment]
Ah, here's a much better way:

```python
def rename(point_data, old, new):
    arr = point_data.pop(old)
    arr.VTKObject.SetName(new)
    point_data[new] = arr
```

This prevents a [copy](https://github.com/pyvista/pyvista/blob/71b33d105ab00f779ca224f41071512b0c4805e9/pyvista/core/datasetattributes.py#L750C68-L750C68) of the array which is the real problem I think. I'll submit a PR when I get a chance.
