### ISSUE TITLE
PyVista types are not compatible with `ArrayLike`

### ISSUE THREAD

**Issue by user27182** [pyvista/pyvista#5250]
### Describe what maintenance you would like added.

Some of PyVista's new type definitions from #5171  are not compatible with numpy's `ArrayLike` type. This is surprising because `ArrayLike` handles nested sequences and should be an all-encompasing type. That is, I expected the pyvista type `FloatMatrix` to be compatible with `ArrayLike`.

Instead, `mypy` complains when doing the following:

``` python
import numpy.typing as npt
from pyvista.core._typing_core import FloatMatrix

def foo(obj: npt.ArrayLike): 
    return

x: FloatMatrix = np.eye(3)
foo(x)  # mypy error here
```

The (formatted) mypy error that is generated is:
``` python
error: Argument 1 to "foo" has incompatible type
  "
      ndarray[Any, dtype[floating[Any]]] | 
      Sequence[ndarray[Any, dtype[floating[Any]]] | 
      Sequence[float]]
  "
expected 
  "
      _SupportsArray[dtype[Any]] | 
      _NestedSequence[_SupportsArray[dtype[Any]]] |
       bool | int | float | complex | str | bytes | 
      _NestedSequence[bool | int | float | complex | str | bytes]
  "
[arg-type]
```

Not sure if types are incompatible due to PyVista's types supporting finite sequences, whereas numpy's nested sequences are generic.  This may be a `mypy` issue, since in [`numpy._typing._array_like.py`](https://github.com/numpy/numpy/blob/8216139d9200aea5f93e5d775a011526387ffb47/numpy/_typing/_array_like.py#L56C6-L56C6) they define finite sequences but not use them, citing ```# TODO: Wait until mypy supports recursive objects in combination with typevars```

This issue was encountered while trying to incorporate the new types as part of #5226. I intended to use `npt.ArrayLike` as the input array type for the `validate_array` function, but I think I'll set the type to `Any` for now to avoid these unexpected type errors.

**Comment by darikg** [comment]
does mypy freak out if you define `pyvista._typing_core.ArrayLike = Union[npt.ArrayLike, npt._FiniteNestedSequence]`?

**Comment by MatthewFlamm** [comment]
Is it the `Sequence[np.ndarray]` part that isn't supported in `ArrayLike`?  If so, this feels like a numpy typing problem to me.
