### ISSUE TITLE
Add `empty` or `is_empty` attribute to meshes 

### ISSUE THREAD

**Issue by AlexanderJuestel** [pyvista/pyvista#5260]
### Describe the feature you would like to be added.

I was wondering if there is an `empty` or `is_empty` attribute for meshes and if not if there would be interest in adding this attribute. 

In particular, I have a list of many small vtk features (salt structures for instance) and use `clip_box` to clip all meshes to the working area. Some structures are still returned as empty meshes and it would be nice to filter for them and kick them out. 

### Pseudocode or Screenshots

```python
mesh.empty

True
```
Or drag your screenshot here!

**Comment by banesullivan** [comment]
I'm decidedly against adding additional properties (at this point in PyVista maturity) that do not have a clear upstream equivalent in VTK, and unfortunately, there's no upstream equivalent to this (as far as I'm aware). 

With that said, I would like to encourage you to use `mesh.n_points` for this. We use `mesh.n_points` throughout PyVista internally to this effect. If a mesh is empty, it will have 0 points. This means `mesh.n_points` will be true/false for this semantic condition.
