### ISSUE TITLE
Proposal to enable depth peeling by default

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#527]
#450 brought depth peeling to PyVista which was a major improvement and sometimes I am amazed at how much better it makes a visualization. I'm thinking we should enable it by default as most users probably want its effects but won't know to use it.

Here's something I've been working on lately where the differences are stark:

<img width="1379" alt="Screen Shot 2020-01-09 at 10 57 53 PM" src="https://user-images.githubusercontent.com/22067021/72129441-79eac880-3333-11ea-91b3-11fd27d3b249.png">

Does anyone have objections, concerns, or thoughts in general?

**Comment by banesullivan** [comment]
FWIW, ParaView enables depth peeling by default but has an option to turn it off as there is a possibility that it can hinder performance

**Comment by akaszynski** [comment]
According to VTK on of the disadvantages is:
> The algorithm is inherently slow due to rendering the geometry multiple times.

Since it was implemented over a decade earlier, performance may no longer be an issue.  If paraview has it implemented by default, it's probably not an issue with modern hardware.
