### ISSUE TITLE
Wrong number of labels in `download_frog_tissue` example.

### ISSUE THREAD

**Issue by user27182** [pyvista/pyvista#5291]
### Describe the bug, what's wrong, and what you expected.

There is an issue with the number of labels or data range for the [download_frog_tissue](https://docs.pyvista.org/version/stable/api/examples/_autosummary/pyvista.examples.downloads.download_frog_tissue.html#pyvista-examples-downloads-download-frog-tissue) example.

This has caused intermittent doctest failures (see #5290) and also results in an incorrect image shown in the documentation.

Current image from the 0.42 release docs:
![](https://docs.pyvista.org/version/stable/_images/pyvista-examples-downloads-download_frog_tissue-1_00_00.png)

Expected image from when the example was originally added (#4801):
![image](https://github.com/pyvista/pyvista/assets/89109579/6f020c38-6ec1-405e-9068-29c3f3db8357)

### Steps to reproduce the bug.

See #5290.

### System Information

```shell
See #5290.
```

**Comment by MatthewFlamm** [comment]
I haven't figured this out completely, but if I run one doctest for only `pack_labels`, then it passes.  If I run all doctests in that module, i.e. `pyvista.core.filters.data_set` then it fails.

**Comment by MatthewFlamm** [comment]
Sorry for the noise, it seems to be more random than this, even though I could have sworn that it was consistent over several tries at first.  This behavior is reproducible on the default codespaces environment.

**Comment by user27182** [comment]
> If I run `pytest --doctest-modules pyvista/core/filters/data_set.py::pyvista.core.filters.data_set.DataSetFilters.cell_data_to_point_data pyvista/core/filters/data_set.py::pyvista.core.filters.data_set.DataSetFilters.pack_labels -v` it _always_ fails.

This seems suspicious. `cell_data_to_point_data` is called internally by the `connectivity` filter. And the docstring for `download_frog_tissue` uses both the `connectivity` filter and `sort_labels`.  Since the order of tests clearly matters, is it possible that one test is corrupting the namespace or setup for the others?

**Comment by MatthewFlamm** [comment]
Something is corrupting something else for sure.  I cannot figure out why.  This has now been a few months, I remember that I set breakpoints and saw differences that would explain the change in behavior.  But I couldn't make heads or tails of what was causing this, but you may want to do something similar to pinpoint the exact operation that gets corrupted.

**Comment by MatthewFlamm** [comment]
Just went back and now I _cannot_ reproduce the failures using:

> pytest --doctest-modules pyvista/core/filters/data_set.py::pyvista.core.filters.data_set.DataSetFilters.cell_data_to_point_data pyvista/core/filters/data_set.py::pyvista.core.filters.data_set.DataSetFilters.pack_labels -v

**Comment by MatthewFlamm** [comment]
Sorry for the additional noise.  I can reproduce this still on a codespaces with our devcontainer, but I cannot reproduce it on a local machine with seemingly all the same python packages.  It is very curious.

> pytest --doctest-modules pyvista/core/filters/data_set.py::pyvista.core.filters.data_set.DataSetFilters.cell_data_to_point_data pyvista/core/filters/data_set.py::pyvista.core.filters.data_set.DataSetFilters.pack_labels -v

**Comment by MatthewFlamm** [comment]
I have an even more subtle report but it can be reproduced without doctest and it does **not** rely on `cell_data_to_point_data`.  It gives a different error.

```py
import pyvista as pv
from pyvista import examples
import numpy as np

pv.plot(pv.Sphere())
pv.plot(pv.Sphere())  # comment this out and it will run fine

# The following is the pack_labels doctest but rewritten for a script
image_labels = examples.download_frog_tissue()

image_labels.get_data_range() == (0, 29)

label_numbers = np.unique(image_labels.active_scalars)
label_max = np.max(label_numbers)
missing_labels = set(range(label_max)) - set(label_numbers)
assert len(missing_labels) == 4

packed_labels = image_labels.pack_labels()

assert packed_labels.get_data_range() == (0, 25)
```

**Comment by user27182** [comment]
> I can reproduce this still on a codespaces with our devcontainer, but I cannot reproduce it on a local machine with seemingly all the same python packages. It is very curious.

This is consistent with test results from #5706. (I opened that PR to try to get better coverage or reproducibility of the root issue with the `download_frog_tissue` docstring example , not for the flaky pack_label/sort_label docstring test)

There, all the windows tests fail when `shade=True` in `plot_volume`. But this works fine when testing locally on a windows machine. All tests with vtk < 9.3 on Linux also fail, though I can't tell if the failures are cause by a different number of labels generated or if they're caused by differences in the renderings alone.

**Comment by user27182** [comment]
> I have an even more subtle report but it can be reproduced without doctest and it does **not** rely on `cell_data_to_point_data`. It gives a different error.

Great! I think simplifying this further and removing `pack_labels` from the equation altogether would also be good to add to #5706, in addition to the regression test
```python
import pyvista as pv
from pyvista import examples
import numpy as np

image_labels = examples.download_frog_tissue()
image_labels.get_data_range() == (0, 29)
label_numbers = np.unique(image_labels.active_scalars)
num_labels = len(label_numbers)
assert num_labels == 29
```

**Comment by MatthewFlamm** [comment]
I agree, this issue is actually in `download_frog_tissue` and is either related to the dataset downloaded, the reader itself, or both.  I get the feeling it is some bug in the vtk reader, but it is hard to put your finger on because it requires creating two plotters on certain environments to reproduce.
