### ISSUE TITLE
Cannot sample data with only cell data array mesh

### ISSUE THREAD

**Issue by Jimmy-KL** [pyvista/pyvista#5319]
### Describe the bug, what's wrong, and what you expected.

If the target mesh has only cell data, the [sample filter](https://docs.pyvista.org/version/stable/api/core/_autosummary/pyvista.DataSetFilters.sample.html#pyvista.DataSetFilters.sample) cannot work.
Here is the error message: `ERROR:root:No input scalars!`

### Steps to reproduce the bug.

Here is the sample code.
```python
import pyvista as pv
import numpy as np

sphere = pv.Sphere()
sphere["celldata"] = np.full(sphere.n_cells, 1)
sphere2 = pv.Cube()
sphere2.sample(sphere, categorical=True)
```

### System Information

```shell
Date: Tue Nov 28 19:39:51 2023

                OS : Windows
            CPU(s) : 16
           Machine : AMD64
      Architecture : 64bit
               RAM : 15.8 GiB
       Environment : Python
        GPU Vendor : Intel
      GPU Renderer : Intel(R) UHD Graphics
       GPU Version : 4.5.0 - Build 31.0.101.1999
  MathText Support : False

  Python 3.11.5 | packaged by conda-forge | (main, Aug 27 2023, 03:23:48) [MSC
  v.1936 64 bit (AMD64)]

           pyvista : 0.42.3
               vtk : 9.2.6
             numpy : 1.24.3
        matplotlib : 3.7.1
            scooby : 0.7.2
             pooch : v1.7.0
            pillow : 10.0.0
           imageio : 2.31.2
           IPython : 8.14.0
             scipy : 1.11.1
            meshio : 5.3.4
      nest_asyncio : 1.5.6

  Intel(R) oneAPI Math Kernel Library Version 2023.1-Product Build 20230303
  for Intel(R) 64 architecture applications
```

**Comment by MatthewFlamm** [comment]
Does this also occur when using `categorical=False`?

**Comment by MatthewFlamm** [comment]
> Does this also occur when using `categorical=False`?

Tested this myself, it does work when `categorical=False`.  Since cell data is not interpolated, there is no need to use `categorical=True`.

**Comment by Jimmy-KL** [comment]
> > Does this also occur when using `categorical=False`?
> 
> Tested this myself, it does work when `categorical=False`. Since cell data is not interpolated, there is no need to use `categorical=True`.

Do you mean since cell data is not interpolated, there is no need to use `categorical=True`, right?

**Comment by Jimmy-KL** [comment]
en..., it's clear now. I didn't understand it clearly when reading the docs.
Sorry, what do you mean by PR?

**Comment by MatthewFlamm** [comment]
Sorry for the obtuse language here.  I meant that if you have a suggestion for better wording to make it clearer for others, you can suggest those changes by opening a Pull Request (PR).  The documentation for this filter starts here:

https://github.com/pyvista/pyvista/blob/4c9519b7ba9b7539ec749ac34dd98ad66be4c71c/pyvista/core/filters/data_set.py#L3510

You have to change the branch/ref to "main" first (can be tricky to find at first), then you can propose wording changes right in your browser (if you want to do that way), commit those changes to your fork of pyvista (this will happen during the process), then open a pull request here.

This way you can contribute directly to this open source package.

**Comment by MatthewFlamm** [comment]
Here is a better link that goes straight editing to the main branch version of this file, but you will have to scroll or search for the `sample` function 
http://github.com/pyvista/pyvista/edit/main/pyvista/core/filters/data_set.py

**Comment by MatthewFlamm** [comment]
I am going to close this issue as there is no bug, but feel free to update the documentation if you feel it is needed.
