### ISSUE TITLE
Timestamp extraction from XdmfReader

### ISSUE THREAD

**Issue by leonardotoledo** [pyvista/pyvista#5331]
### Describe the feature you would like to be added.

Hey, guys!

I needed to extract the timestamps from a .xdmf file, but I couldn't find a clear and easy way to do that using pyvista's XdmfReader. I noticed that the XdmfReader class does not inherit from the TimeReader class, so that is probably the reason. 

In the following code snippet, I found a workaround to this issue, which is to call the methods from the vtkXdmfReader original class inside the pyvista reader object. However, this is not an ideal solution. Is there anyway this could be integrated into pyvista in future updates?

```python
import pyvista as pv
import numpy as np
import vtk

file_path = "file.xdmf"

# Create an Xdmf reader
pv_reader = pv.XdmfReader(path=file_path)

# Get the field names
field_names = pv_reader.point_array_names

# Get the output information
info = pv_reader.reader.GetOutputInformation(0)

# Get the time steps
timestamps = info.Get(vtk.vtkCompositeDataPipeline.TIME_STEPS())
```

### Links to VTK Documentation, Examples, or Class Definitions.

An example can be found in the code snippet I provided.

### Pseudocode or Screenshots

```python
import pyvista as pv
import numpy as np
import vtk

file_path = "file.xdmf"

# Create an Xdmf reader
pv_reader = pv.XdmfReader(path=file_path)

# Get the field names
field_names = pv_reader.point_array_names

# Get the output information
info = pv_reader.reader.GetOutputInformation(0)

# Get the time steps
timestamps = info.Get(vtk.vtkCompositeDataPipeline.TIME_STEPS())
```

**Comment by tkoyama010** [comment]
Thanks for your comments, this is a feature we should add as it is our goal to make use of VTK Python-like. We will consider adding it before the next minor upgrade.
