### ISSUE TITLE
installing pyvista with pip results in vtk related error

### ISSUE THREAD

**Issue by frodo4fingers** [pyvista/pyvista#534]
hi :-)

i run manjaro linux and am using python 3.8.1
trying to install pyvista via `pip install pyvista` (or similar) currently results in the following error on my machine:
```bash
ERROR: Could not find a version that satisfies the requirement vtk (from pyvista) (from versions: none)
ERROR: No matching distribution found for vtk (from pyvista)
```
even with vtk installed beforehand the error persisted.

## workaround
+ install vtk (v8.2.0-9) form community (via pacman or similar)
+ install pyvista (v0.23.0) from (github)[https://github.com/pyvista/pyvista]

since this is not a *real* issue and i don't really know where the problem itself lies (pyvista/vtk/python3.8), you might consider this as temporary workaround for those who stumble over the same problem

is anyone else experiencing this? any thoughts on stability?

**Comment by GuillaumeFavelier** [comment]
Hello @frodo4fingers ! Thanks for reporting your issue in here with a corresponding workaround.

VTK is actually a dependency of PyVista so when you try to install it with `pip install pyvista`, `pip` will try to do `pip install vtk` at some point and I think the error in your case is related to the fact that the latest version of `vtk` [currently available on `pypi`](https://pypi.org/project/vtk/8.1.2/) [does not support `python==3.8`](https://gitlab.kitware.com/vtk/vtk/issues/17670).

Apparently a patch is available on the master branch of VTK but is not released yet on `pypi`. To my knowledge, a way to have such a recent version of `vtk` locally without waiting would be to compile VTK from source with `VTK_WRAP_PYTHON=On` and `VTK_PYTHON_VERSION=3.8` in the `cmake` cache flags . This could be a tedious operation if you are not familiar with the procedure. My guess is that the maintainers of `vtk` for ArchLinux and Manjaro did all of this already as they packaged a version slightly more recent [8.2.0-9](https://www.archlinux.org/packages/community/x86_64/vtk/). Most likely the patch is integrated.

> any thoughts on stability?

I wouldn't be concerned about that but you can still report in here if you encounter any other issue.

**Comment by frodo4fingers** [comment]
many thanks :-)
i actually made a mistake reporting.. vtk from community is 8.2.0-9. will edit this.

**Comment by banesullivan** [comment]
FYI: conda-forge has builds of VTK for python 3.8: https://anaconda.org/conda-forge/vtk/files

**Comment by florian-wagner** [comment]
Just for reference for non-conda users: Python wheels for vtk 9.0 [are available on the Kitware website](https://vtk.org/download/). Under Linux with Python 3.8, I had success with: 

``` bash
pip3 install https://www.vtk.org/files/release/9.0/vtk-9.0.0-cp38-cp38-linux_x86_64.whl
pip3 install pyvista
```

**Comment by akaszynski** [comment]
VTK 9.0 is also on [PyPi](https://pypi.org/project/vtk/)

**Comment by florian-wagner** [comment]
Yes, but for some reasons the wheels are only uploaded for mac and windows (https://pypi.org/project/vtk/#files). This is why `pip install pyvista` fails for me on a fresh Ubuntu 20.04 LTS with python 3.8:

``` bash
 florian@x380 ~ sudo pip3 install pyvista                                                                                                  
Collecting pyvista
  Using cached pyvista-0.24.2.tar.gz (1.2 MB)
Requirement already satisfied: appdirs in /usr/local/lib/python3.8/dist-packages (from pyvista) (1.4.4)
Requirement already satisfied: imageio in /usr/local/lib/python3.8/dist-packages (from pyvista) (2.8.0)
Requirement already satisfied: meshio<5.0,>=4.0.3 in /usr/local/lib/python3.8/dist-packages (from pyvista) (4.0.13)
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from pyvista) (1.17.4)
Requirement already satisfied: scooby>=0.5.1 in /usr/local/lib/python3.8/dist-packages (from pyvista) (0.5.4)
ERROR: Could not find a version that satisfies the requirement vtk (from pyvista) (from versions: none)
ERROR: No matching distribution found for vtk (from pyvista)
```

**Comment by akaszynski** [comment]
> Yes, but for some reasons the wheels are only uploaded for mac and windows

My bad!  I've been using the RC for some time now and didn't actually checkout the downloads from PyPi.  Thanks for this workaround.

**Comment by ttsesm** [comment]
Hi guys, 

for some reason on a windows machine I am getting the following error:

```
C:\Users\TTxxxxxx\Desktop\dev\radio\r_venv\Scripts\python.exe C:/Users/TTxxxxxx/Desktop/dev/radio/tests/test_icocell.py
Traceback (most recent call last):
  File "C:\Users\TTxxxxxx\Desktop\dev\radio\r_venv\lib\site-packages\vtkmodules\__init__.py", line 13, in <module>
    from . import vtkCommonCore
ImportError: cannot import name 'vtkCommonCore' from partially initialized module 'vtkmodules' (most likely due to a circular import) (C:\Users\TTxxxxxx\Desktop\dev\radio\r_venv\lib\site-packages\vtkmodules\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/TTxxxxxx/Desktop/dev/radio/tests/test_icocell.py", line 3, in <module>
    from utils import Isocell
  File "C:\Users\TTxxxxxx\Desktop\dev\radio\utils\__init__.py", line 10, in <module>
    from utils.ldc import LightDistributionCurve
  File "C:\Users\TTxxxxxx\Desktop\dev\radio\utils\ldc.py", line 10, in <module>
    import pyvista as pv
  File "C:\Users\TTxxxxxx\Desktop\dev\radio\r_venv\lib\site-packages\pyvista\__init__.py", line 6, in <module>
    from pyvista.plotting import *
  File "C:\Users\TTxxxxxx\Desktop\dev\radio\r_venv\lib\site-packages\pyvista\plotting\__init__.py", line 5, in <module>
    from .export_vtkjs import export_plotter_vtkjs, get_vtkjs_url
  File "C:\Users\TTxxxxxx\Desktop\dev\radio\r_venv\lib\site-packages\pyvista\plotting\export_vtkjs.py", line 55, in <module>
    import vtk
  File "C:\Users\TTxxxxxx\Desktop\dev\radio\r_venv\lib\site-packages\vtk.py", line 30, in <module>
    all_m = importlib.import_module('vtkmodules.all')
  File "C:\Users\TTxxxxxx\AppData\Local\Programs\Python\Python38-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\TTxxxxxx\Desktop\dev\radio\r_venv\lib\site-packages\vtkmodules\__init__.py", line 15, in <module>
    import _vtkmodules_static
ModuleNotFoundError: No module named '_vtkmodules_static'

Process finished with exit code 1
```
I know that it is not `pyvista` related per se but rather than a `vtk` issue but if you have any idea how to solve it I would appreciate any feedback. Giving `pip install vtk` did not find anything on `pypi` thus, I had to manually install `vtk-9.0.0-cp38-cp38-win_amd64.whl` which I downloaded it from https://vtk.org/download/. However, I had to rename it to `vtk-9.0.0-cp38-none-any.whl` otherwise I was getting a compatibility error to my system although it is the correct wheel for my system.

**Comment by ttsesm** [comment]
Issue solved, just in case that someone might come upon a similar problem I had the wrong version of python installed 32bit instead of 64bit.

**Comment by banesullivan** [comment]
> install error in conda / python 3.11 / pip

3.11 is a little too bleeding edge. There are no VTK wheels for 3.11 on PyPI yet.

We may be able to provide a wheel for this in https://github.com/pyvista/pyvista-wheels/pull/7
