### ISSUE TITLE
Trame Plotter Viewer UI Menu has incorrect positioning.

### ISSUE THREAD

**Issue by landynfrancis** [pyvista/pyvista#5364]
### Describe the bug, what's wrong, and what you expected.

When trying to run [the example](https://tutorial.pyvista.org/tutorial/09_trame/index.html) in the PyVista Tutorial for Trame, the Plotter UI Menu is incorrectly placed behind the AppBar when the code is changed to use Vuetify3. 

This issue seems to lie in the definition of the VCard that houses the UI Menu.
https://github.com/pyvista/pyvista/blob/11f4dea8bb102310d53ee6d3e4d20b6184fb77f5/pyvista/trame/ui/vuetify3.py#L291-L293
With `position: absolute` this VCard will always be placed 20px away from the top and left corners of the page. Changing this to `position: relative` seems to fix the problem. It would be nice if there were a way to access this VCard component from the `plotter_ui` or if it were set to always be `position: relative`. I can make a pull request for changing the position styling to relative, if this is the desired behavior.

### Steps to reproduce the bug.

1. Run [this code](https://tutorial.pyvista.org/tutorial/09_trame/index.html#d-visualization-in-web-applications)
```python
from trame.app import get_server
from trame.ui.vuetify import SinglePageLayout
import pyvista as pv
from pyvista.trame.ui import plotter_ui

# Always set PyVista to plot off screen with Trame
pv.OFF_SCREEN = True

server = get_server()
state, ctrl = server.state, server.controller

mesh = pv.Wavelet()

pl = pv.Plotter()
pl.add_mesh(mesh)

with SinglePageLayout(server) as layout:
    with layout.content:
        # Use PyVista's Trame UI helper method
        #  this will add UI controls
        view = plotter_ui(pl)

server.start()
```
2. Observe the UI Menu is appropriately placed below the AppBar. ([Screenshot 1](https://github.com/pyvista/pyvista/assets/154266384/1c58f531-8c42-4768-bdca-b1968552e0c4))
3. Run this code.
```python
from trame.app import get_server
from trame.ui.vuetify3 import SinglePageLayout # Changed to vuetify3
import pyvista as pv
from pyvista.trame.ui import plotter_ui

# Always set PyVista to plot off screen with Trame
pv.start_xvfb()
pv.OFF_SCREEN = True

server = get_server()
state, ctrl = server.state, server.controller
server.client_type = "vue3" # Add this so Trame does not complain about "vue2".

mesh = pv.Wavelet()

pl = pv.Plotter()
pl.add_mesh(mesh)


with SinglePageLayout(server) as layout:
    with layout.content:
        # Use PyVista's Trame UI helper method
        #  this will add UI controls
        view = plotter_ui(pl)


def start_server():
    server.start()
```
4. Observe that the UI Menu is now missing, (it is behind the App Bar) ([Screenshot 2](https://github.com/pyvista/pyvista/assets/154266384/5d64c1e2-4472-4883-893e-665a789ca6ef))
5. Go to https://github.com/pyvista/pyvista/blob/11f4dea8bb102310d53ee6d3e4d20b6184fb77f5/pyvista/trame/ui/vuetify3.py#L291-L293
7. Change `position: absolute;` to `position: relative;`
8. Re-run the code.
9. Observe the UI Menu is now appropriately placed below the App Bar. ([Screenshot 1](https://github.com/pyvista/pyvista/assets/154266384/1c58f531-8c42-4768-bdca-b1968552e0c4))

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Mon Dec 18 14:22:18 2023 EST

                OS : Linux
            CPU(s) : 32
           Machine : x86_64
      Architecture : 64bit
               RAM : 125.8 GiB
       Environment : Python
       File system : ext4
       GPU Details : error
  MathText Support : False

  Python 3.11.6 (main, Nov  2 2023, 14:08:07) [GCC 8.5.0 20210514 (Red Hat
  8.5.0-4)]

           pyvista : 0.42.3
               vtk : 9.2.6
             numpy : 1.26.1
        matplotlib : 3.8.1
            scooby : 0.9.2
             pooch : 1.8.0
            pillow : 10.0.1
           imageio : 2.31.6
             PyQt5 : 5.15.10
           IPython : 8.17.2
        ipywidgets : 8.1.1
             scipy : 1.11.3
              tqdm : 4.63.1
            meshio : 5.3.4
             trame : 3.2.8
      trame_client : 2.12.6
      trame_server : 2.12.1
         trame_vtk : 2.5.9
     trame_vuetify : 2.3.1
      nest_asyncio : 1.5.8
--------------------------------------------------------------------------------
```

### Screenshots

Result of Steps 2 and 8.
![chrome_5QZdvZRNgb](https://github.com/pyvista/pyvista/assets/154266384/1c58f531-8c42-4768-bdca-b1968552e0c4)
Result of Step 4
![chrome_iVvPIHJ8Np](https://github.com/pyvista/pyvista/assets/154266384/5d64c1e2-4472-4883-893e-665a789ca6ef)

**Comment by jourdain** [comment]
@annehaley
