### ISSUE TITLE
`from_irregular_faces` with different number of points in each face

### ISSUE THREAD

**Issue by tkoyama010** [pyvista/pyvista#5367]
### Describe the feature you would like to be added.

Currently, [from_regular_faces](https://docs.pyvista.org/version/stable/api/core/_autosummary/pyvista.PolyData.from_regular_faces.html) all assume the same number of points. However, using Python lists, it is possible to define a different number of points for each face. I want to execute the following script.
```python
import pyvista as pv

points = [
    [0.0, 0.0, 0.0],
    [1.0, 0.0, 0.0],
    [1.0, 1.0, 0.0],
    [0.0, 1.0, 0.0],
    [2.0, 0.0, 0.0],
    [2.5, 0.0, 0.0],
    [2.0, 1.0, 0.0],
]
# Different size elements
faces = [[0, 1, 2, 3], [1, 4, 6, 2], [4, 5, 6]]
mesh = pv.PolyData.from_irregular_faces(points, faces)
```

### Links to VTK Documentation, Examples, or Class Definitions.

relate to https://github.com/pyvista/pyvista/pull/4637

### Pseudocode or Screenshots

None

**Comment by darikg** [comment]
I think I originally had this in #4637 but took it out for simplicity. I'll have a look around in my git history
