### ISSUE TITLE
Change property name from `pyvista.DataSet.cell` to `pyvista.DataSet.cells`

### ISSUE THREAD

**Issue by tkoyama010** [pyvista/pyvista#5386]
### Describe what maintenance you would like added.

I find it strange that only [pyvista.DataSet.cell](https://docs.pyvista.org/version/stable/api/core/_autosummary/pyvista.dataset.cell) is singular while [pyvista.DataSet.points](https://docs.pyvista.org/version/stable/api/core/_autosummary/pyvista.dataset.points) is plural. This is noticeable when writing the following code.
```python
for cell in mesh.cell:
    cell = ...
```
This can be more easily understood by applying the following.
```python
for cell in mesh.cells: 
    cell = ...
```

### Links to source code.

None

### Pseudocode or Screenshots

None

**Comment by tkoyama010** [comment]
It is because this is a generator?

**Comment by MatthewFlamm** [comment]
This was done because we have the unfortunate conflict with https://docs.pyvista.org/version/stable/api/core/_autosummary/pyvista.UnstructuredGrid.cells.html

**Comment by tkoyama010** [comment]
Got it thanks!
