### ISSUE TITLE
'>f8' dtype arrays not properly converted by VTK

### ISSUE THREAD

**Issue by sampotter** [pyvista/pyvista#540]
When trying to, e.g., scatter plot an array of points with the `'>f8'` dtype, the bounding box is set to garbage during construction, resulting in a blank plot.

```
points = np.random.randn(100, 3).astype('>f8')
poly = pv.PolyData(points)
poly
```

![image](https://user-images.githubusercontent.com/6035363/72472351-649df000-37b2-11ea-8685-c0e14ddcb7df.png)

If we try to plot this...

```
plt = pv.Plotter(window_size=(512, 512))
plt.add_mesh(poly)
plt.show()
```

![image](https://user-images.githubusercontent.com/6035363/72472575-cc543b00-37b2-11ea-8c58-ff2ae34c4e97.png)

If we do this using `np.float64` instead of `'>f8'`, it works as expected.

My system information:

```
--------------------------------------------------------------------------------
  Date: Wed Jan 15 16:18:28 2020 EST

            Darwin : OS
                 8 : CPU(s)
            x86_64 : Machine
             64bit : Architecture
           Jupyter : Environment
        GPU Vendor : Intel Inc.
      GPU Renderer : Intel Iris Pro OpenGL Engine
       GPU Version : 4.1 INTEL-12.10.12

  Python 3.7.6 (default, Dec 30 2019, 19:38:28)  [Clang 11.0.0
  (clang-1100.0.33.16)]

            0.23.0 : pyvista
             8.1.2 : vtk
            1.18.1 : numpy
             2.6.1 : imageio
             1.4.3 : appdirs
             0.5.0 : scooby
             3.1.2 : matplotlib
            5.14.1 : PyQt5
            7.11.1 : IPython
             1.0.0 : colorcet
--------------------------------------------------------------------------------
```

**Comment by banesullivan** [comment]
This is looking like a VTK bug to me where `vtk.util.numpy_support.numpy_to_vtk` is improperly converting the `'>f8'` type.

```
>>> import numpy as np
>>> import vtk.util.numpy_support as nps
>>> points = np.random.randn(100, 3).astype('>f8')
>>> arr = nps.numpy_to_vtk(points)
>>> arr
(vtkCommonCorePython.vtkDoubleArray)0x7f99198586a8
>>> arr.GetValue(0)
-1.0577725915134108e+79
```

'>f8' is not a double.... so it looks like the conversion is totally messing up the values

**Comment by banesullivan** [comment]
We could handle this case in `pyvista.convert_array` much like we did with string data types but it would be best to open a PR with the numpy support module in VTK

**Comment by banesullivan** [comment]
@sampotter, any reason that you closed this?
