### ISSUE TITLE
Some entries of pv.Report() are backwards

### ISSUE THREAD

**Issue by sampotter** [pyvista/pyvista#541]
My system report:

```
--------------------------------------------------------------------------------
  Date: Wed Jan 15 16:18:28 2020 EST

            Darwin : OS
                 8 : CPU(s)
            x86_64 : Machine
             64bit : Architecture
           Jupyter : Environment
        GPU Vendor : Intel Inc.
      GPU Renderer : Intel Iris Pro OpenGL Engine
       GPU Version : 4.1 INTEL-12.10.12

  Python 3.7.6 (default, Dec 30 2019, 19:38:28)  [Clang 11.0.0
  (clang-1100.0.33.16)]

            0.23.0 : pyvista
             8.1.2 : vtk
            1.18.1 : numpy
             2.6.1 : imageio
             1.4.3 : appdirs
             0.5.0 : scooby
             3.1.2 : matplotlib
            5.14.1 : PyQt5
            7.11.1 : IPython
             1.0.0 : colorcet
--------------------------------------------------------------------------------
```

I'm not sure if this function is a bespoke implementation for pyvista or what, but usually the colon separated entries in this sort of thing are of the form "key : value". The entries above don't seem to be organized in a consistent fashion. I would expect the versions to come after the modules in the second section, and the first few lines of the first section to be organized like "OS : Darwin", "CPU(s) : 8", etc. The way it's organized now is confusing to read.

**Comment by banesullivan** [comment]
Thanks, @sampotter! This was introduced in https://github.com/banesullivan/scooby/pull/39 (and is really a `scooby` issue than a PyVista issues). The inconsistency if from the GPU info being somewhat lengthy and not fitting on the left side. I've been meaning to switch everything in `scooby` to have the `"key : value"` convention but haven't had a chance to do it. If you're up for it, it wouldn't be too bad of a PR

**Comment by sampotter** [comment]
Ah, thanks for the explanation. I would certainly be happy to help out, but I'm currently busy with a deadline. If no one has taken care of this by then (around a week from now), I'll see what I can do.
