### ISSUE TITLE
Make the `sphinx-gallery` scraper more flexible

### ISSUE THREAD

**Issue by Louis-Pujol** [pyvista/pyvista#5433]
### Describe the feature you would like to be added.

Hi !

A few weeks ago I've done some [work](https://github.com/smarie/mkdocs-gallery/pull/91) on integrating pyvista into [mkdocs-gallery](https://github.com/smarie/mkdocs-gallery). [Here](https://smarie.github.io/mkdocs-gallery/generated/gallery/plot_11_pyvista/) is the example.

The work did there was to copy/paste the scraper from `pyvista.plotting.utilities.Scraper` and adapt it in two ways:
- modify the structure of the inputs (`mkdocs` has its own versions of `block_vars` and `gallery_conf` sphinx's variables)
- at the end, instead of calling `figure_rst`, call an equivalent that convert the list of image names + the source path to a markdown text

The code is mainly duplicated, which is bad, I was wondering if the code inside the class `Scraper` could be reorganized to add more flexibility to let the user the freedom to reuse the generation of pyvista images outside sphinx. The `__call__()` method has 3 steps:

https://github.com/pyvista/pyvista/blob/84ac2a3990a5e429b30383e988f5065c907c071f/pyvista/plotting/utilities/sphinx_gallery.py#L94-L119

- 1/ Iterate over `pyvista.plotting.plotter._ALL_PLOTTERS` to identify active plotters
- 2/ save static/animated/dynamic scenes into files and save name fils in `image_names`
- 3/ call `html_rst` which generate the viewer in reST

Perhaps moving steps 1 and 2 into another function (something like `generate_images_names(image_path_iterator, dynamic= True or False)`) will increase flexibility. Then
- the `sphinx-gallery` scraper will use `generate_image_names` + `figure_rst()`
- user can combine `generate_image_names` with its own generator of `html`/`markdown`/... to integrate pyvista views wherever he wants

If you think it is a good idea, i can start a PR.

**Comment by tkoyama010** [comment]
@Louis-Pujol I love this idea. Could you open PR for this?

**Comment by Louis-Pujol** [comment]
Done #5445
