### ISSUE TITLE
Garbled output when plotting triangle mesh with opacity

### ISSUE THREAD

**Issue by sampotter** [pyvista/pyvista#547]
I have a mesh of a building that I would like to plot with some opacity so that all rooms are visible simultaneously. I've attached the OBJ file:

[room__surface_mesh.obj.zip](https://github.com/pyvista/pyvista/files/4083597/room__surface_mesh.obj.zip)

When I load it in ParaView and set the opacity to something other than 1 this is what I see:

![image](https://user-images.githubusercontent.com/6035363/72688519-105a7f00-3ad6-11ea-9deb-603cf175414d.png)

This is what I would expect.

On the other hand, using PyVista in a Jupyter notebook:

![Screen Shot 2020-01-19 at 4 10 59 PM](https://user-images.githubusercontent.com/6035363/72688544-4ac41c00-3ad6-11ea-9e91-e8d8cb4c441f.png)

It looks like there's some issue with the orientation of the individual triangles... Maybe their orientation is being chosen arbitrarily (e.g., cross product of v2 - v1 with v3 - v1 will not necessarily yield consistently oriented face normals... which, for this mesh, should all be pointing into the interior).

Here is a more precise view of the triangulation (from MeshLab):

![Screen Shot 2020-01-19 at 4 12 05 PM](https://user-images.githubusercontent.com/6035363/72688566-71825280-3ad6-11ea-89be-e9caf4d29eba.png)

System info:

![Screen Shot 2020-01-19 at 4 14 25 PM](https://user-images.githubusercontent.com/6035363/72688587-c45c0a00-3ad6-11ea-9222-656123d3a0f6.png)

**Comment by banesullivan** [comment]
Enabling depth peeling (`plotter.enable_depth_peeling()`) shold help with this. Also depth peeling is now on by default if you're on the master branch per #529 

```py
import pyvista as pv
mesh = pv.read("room__surface_mesh.obj")
p = pv.Plotter()
p.add_mesh(mesh, opacity=0.5, show_edges=False)
p.enable_depth_peeling()
p.show()
```

![download](https://user-images.githubusercontent.com/22067021/72689364-ea30e100-3acd-11ea-850b-6d301e4758d3.png)

**Comment by banesullivan** [comment]
There are still a few artifacts that I can seem to get rid of... tried cleaning the mesh but had no effect

**Comment by banesullivan** [comment]
@sampotter, did the depth peeling help for you?

It would be good for us to investigate why ParaView handles this opacity issue so much better than PyVista

**Comment by sampotter** [comment]
Sorry, haven't had much time to look at this since our last conversation. The results above are too poor quality to be of use to me. :-( I need to make presentation-quality video demonstrations, and the those results are still quite unprofessional looking.

I agree that understanding what's going wrong is important. In principle, I would be happy to help figure this out. I'm very busy at the moment, but if you have any specific things you can suggest for me to take a look at, I can try to fit it in. I'm interested in contributing to this project in the long run, it's been tremendously useful to me so far.

**Comment by GuillaumeFavelier** [comment]
> I'm interested in contributing to this project in the long run.

Your contributions are very welcome! We have the tag `low-hanging fruit` for contributors who are looking for a place to start.

> pyvista has been tremendously useful to me so far.

This is awesome news! :+1:

**Comment by GuillaumeFavelier** [comment]
> It would be good for us to investigate why ParaView handles this opacity issue so much better than PyVista

I totally agree with you @banesullivan, I'm really puzzled by this

**Comment by sampotter** [comment]
@GuillaumeFavelier Any particular suggestions related to this issue? It's a show stopper for me.

**Comment by GuillaumeFavelier** [comment]
I didn't investigate myself yet unfortunately. 

Looking at @banesullivan results when he enables `depth_peeling`, I think that the mesh might needs some work. Do you have duplicated triangles? Can you provide the vertex/normals as a vector field? Did you try with smooth shading?

**Comment by GuillaumeFavelier** [comment]
I plan to dive into ParaView code when I have the time, I will report in here then.

**Comment by sampotter** [comment]
@GuillaumeFavelier Oops, you're right. There are duplicated faces. This mesh is output of a CGAL function---didn't look carefully at what was being generated.

Regardless, I would argue that this behavior is still a bug on the part of pyvista.

I will check whether deduplicating the faces and orienting the normals correctly fixes the problem (I would do this now, but I didn't see a simple way of reorienting the normals consistently in pyvista---if there is one, please let me know and I can check this quickly).

**Comment by banesullivan** [comment]
I think it’s more of an issue on our end than anything with the mesh. When I load the same mesh in ParaView, there are no artifacts. It makes me think we are just forgetting to set some option for coincident topology or depth peeling

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by GuillaumeFavelier** [comment]
>> I think that the mesh might needs some work

> I think it’s more of an issue on our end than anything with the mesh

Sorry, I will rephrase: we might need to do some work on the mesh.

**Comment by GuillaumeFavelier** [comment]
Taken from the old `views_and_representations.xml` file in the ParaView source code (which does not exists on `master` anymore apparently) the [default value for the maximum number of peels is 4](https://gitlab.kitware.com/paraview/paraview/blob/860d3994f4a75f2b30e61e65870c5455bce2ae6b/ParaViewCore/ServerManager/SMApplication/Resources/views_and_representations.xml#L2140-2155) and then I would suggest to set `occlusion_ration=0`.

I personally obtain something very satisfying:

```py
import pyvista as pv
mesh = pv.read("room__surface_mesh.obj").clean()
p = pv.BackgroundPlotter()
p.enable_depth_peeling(number_of_peels=4, occlusion_ratio=0)
p.add_mesh(mesh, opacity=0.5)
p.enable_anti_aliasing()
```

![image](https://user-images.githubusercontent.com/18143289/73748032-eef5c600-4758-11ea-8322-faabba6fa075.png)

**Comment by GuillaumeFavelier** [comment]
I invite you to try it out @sampotter

**Comment by banesullivan** [comment]
Should we add the `occlusion _ratio` to the `rcParams` as 0 and switch the number of peels to 4, or is 5 good?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by banesullivan** [comment]
@sampotter, could we use this mesh in our example gallery to demonstrate depth peeling?

**Comment by GuillaumeFavelier** [comment]
Finding default parameters for this is difficult and so data/usage dependant. I think 5 is okay for the maximum number of peels but keeping the occlusion ratio at 0 is maybe too much. On my laptop (which is not particularly new) interacting with this dataset (100k cells, 25k points) was not perfectly smooth. We need to find a tradeoff I guess

**Comment by sampotter** [comment]
Would one of you mind pointing me to the corresponding VTK documentation for these "depth peeling" and "occlusion ratio" parameters? I would like to understand what they do.

@banesullivan You're welcome to use it, but please attribute the mesh to me in some way.

**Comment by banesullivan** [comment]
The documentation on depth peeling is sparse but [this](https://vtk.org/Wiki/VTK/Depth_Peeling) has been helpful for me.

> You're welcome to use it, but please attribute the mesh to me in some way.

will do. Would mentioning you in the docstring for the download method (`examples.download_room_surface()`) and in the [depth peeling example](https://docs.pyvista.org/examples/02-plot/depth-peeling.html) suffice?

**Comment by sampotter** [comment]
@GuillaumeFavelier It works, thanks :-)

![Screen Shot 2020-02-04 at 2 30 54 PM](https://user-images.githubusercontent.com/6035363/73779656-07ff7680-475b-11ea-976f-edc098bd0475.png)

**Comment by sampotter** [comment]
@banesullivan Sure, that works for me. Thanks!

**Comment by banesullivan** [comment]
@sampotter, the changes in #584 should help with this, but the biggest difference would come from using VTK 8.2 from `conda-forge` (see https://github.com/pyvista/pyvista/pull/584#issuecomment-582731572)

I'd highly recommend using `conda` to install PyVista as it will install VTK 8.2 (whereas PyPI can only install up to VTK 8.1.2 at this time): https://anaconda.org/conda-forge/pyvista

```
conda install -c conda-forge pyvista 
```


With that, the rendering differences between PyVista and ParaView can be explained by the VTK version and this issue is resolved.

**Comment by sampotter** [comment]
Thank you guys again for fixing this issue!

In case you're curious, I was finally able to revisit this and make the video that I wanted to make. Please enjoy.

https://vimeo.com/406979024

**Comment by banesullivan** [comment]
Super cool! Thanks for sharing!

**Comment by akaszynski** [comment]
That's great!
