### ISSUE TITLE
Numpy 2.0 compatibility

### ISSUE THREAD

**Issue by drammock** [pyvista/pyvista#5472]
### Describe what maintenance you would like added.

Over in MNE-Python we're now testing against NumPy 2.0 pre-release, and we're getting a bunch of `AttributeError`s when importing Pyvista due to deprecated dtype aliases like `np.float_` (which should instead be `np.float64`). Here's a link to the failures in our CIs:

https://github.com/mne-tools/mne-python/actions/runs/7506386773/job/20437722876?pr=12354

### Links to source code.

here is one example of where `np.float_` occurs:

https://github.com/pyvista/pyvista/blob/7636dc7b65fb8eb9fc986bb985d6405e96ec3d33/pyvista/plotting/mapper.py#L666

### Pseudocode or Screenshots

n/a

**Comment by user27182** [comment]
Closed by #5460.
