### ISSUE TITLE
Testing against VTK master branch is failing

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#5514]
Looks like our routine tests against VTK's master branch are failing for 5 different tests:

```
FAILED tests/core/test_reader.py::test_openfoam_decompose_polyhedra - AttributeError: 'vtkmodules.vtkIOParallel.vtkPOpenFOAMReader' object has no attribute 'SetDecomposePolyhedra'
FAILED tests/plotting/test_picking.py::test_single_cell_picking - assert False
 +  where False = <test_picking.test_single_cell_picking.<locals>.PickCallback object at 0x7f41412f1d90>.called
FAILED tests/plotting/test_picking.py::test_cell_picking_interactive - IndexError: list index out of range
FAILED tests/plotting/test_picking.py::test_cell_picking_interactive_subplot - IndexError: list index out of range
FAILED tests/plotting/test_picking.py::test_switch_picking_type - assert []
```

See jobs under https://github.com/pyvista/pyvista/actions/workflows/vtk-pre-test.yml

cc @berkgeveci @pyvista/kitware

**Comment by banesullivan** [comment]
Last successful run was on Nov 17, 2023 in 18m 15s

**Comment by berkgeveci** [comment]
How does one run individual tests? Can it be done on Mac? (I read something about image tests running on Linux only?) I can try to do a bisect.

**Comment by MatthewFlamm** [comment]
95+% of the tests that use image regression are in `tests/plotting/test_plotting.py`.  None of the failing tests above are in there, so it is likely OK if that is the only issue with Mac testing.  We also decorate tests to skip on Mac, so you will know.

You can run individual test by doing this `pytest tests/plotting/test_picking.py::test_cell_picking_interactive`.  Note that you can copy and paste directly from the lines above to make your life easier.

Some of these changes will require not trivial changes to the code.  Do you have a recommended way we should tag or name branches to get the testing right?  A way to run the tests via tag would be the most flexible in my opinion.

The one related to OpenFoamReader is a deprecation/removal cycle in vtk.

https://github.com/Kitware/VTK/blob/5b8982f91c2b24e66629c9d6188647659ed5e4b3/Documentation/release/9.3.md?plain=1#L973-L974

We can do as `hasattr` and guard tests appropriately.

**Comment by berkgeveci** [comment]
I tracked the interaction test failures to several commits around this one: 1da4867f7a26530ce8ca60ad41eeb4af3b8ff6ae
I'll ask the author of those commits to take a look.

**Comment by mwestphal** [comment]
Hi,

I did indeed commit this, see here for info:

https://discourse.vtk.org/t/about-keycode-keysym-modifiers-crossplatform-and-reliable-code/12598

I'm sure you should be able to update accordingly to the new (correct) behavior.

**Comment by banesullivan** [comment]
Thank you @berkgeveci and @mwestphal for tracking this down and outlining the change for us! Seems like this is a simple fix of changing `SetKeyCode` to `SetKeySym` for our mocked keypresses

**Comment by banesullivan** [comment]
```
FAILED tests/core/test_reader.py::test_openfoam_decompose_polyhedra - AttributeError: 'vtkmodules.vtkIOParallel.vtkPOpenFOAMReader' object has no attribute 'SetDecomposePolyhedra'`
```

Might be more involved if this API was removed. I briefly searched through recently merged MRs for VTK and didn't see anything obvious regarding this. @berkgeveci, I'm curious if you have a hunch on this before we git-bisect for this test

**Comment by mwestphal** [comment]
deprecated in  8f08c964478f5230af395d3840cc2802f0ae652b, removed in 5bf9edd61315113a4226f01e5666e281f909f8f2
