### ISSUE TITLE
spurious `v3.0.0` tag

### ISSUE THREAD

**Issue by francesco-ballarin** [pyvista/pyvista#5528]
### Describe what maintenance you would like added.

It seems that `dependabot` has tagged a spurious `v3.0.0` version at https://github.com/pyvista/pyvista/releases/tag/v3.0.0

Can you drop this tag? Keeping it around means that any automated check of new `pyvista` releases will think that the newest release is `v3.0.0`, rather than any `v0.*.*`.

**Comment by tkoyama010** [comment]
Thanks for the report.
@pyvista/admin It seems that Dependabot released the tag. I do not know the cause. They tagged the main branch so nothing happened. If you two don't know anything. I will remove it.

**Comment by akaszynski** [comment]
> I will remove it.

Thanks!

**Comment by banesullivan** [comment]
Let's not delete it just yet since there were no side affects. I think we should report this to GitHub support or Dependabot support if there is one. This is not okay, @dependabot

**Comment by banesullivan** [comment]
I've created a GitHub support ticket for this to see how this happened and how we can prevent this in the future

**Comment by tkoyama010** [comment]
> I've created a GitHub support ticket for this to see how this happened and how we can prevent this in the future

Thanks!

**Comment by tkoyama010** [comment]
@francesco-ballarin Please be patient until we get GitHub reply.

**Comment by francesco-ballarin** [comment]
> @francesco-ballarin Please be patient until we get GitHub reply.

Sure, no problem :)

**Comment by akaszynski** [comment]
Tags can be deleted with:
```
git push --delete origin v3.0.0
```

I've done this.

**Comment by banesullivan** [comment]
Thanks for deleting @akaszynski. I wanted to keep it around for GitHub support to investigate. I got a response this weekend and apparently I'm to blame for this. The push for the tag came from one of my computers. I'm going to investigate my bash history and get to the bottom of the mistake I made.

Sorry all, I'll do better!

**Comment by akaszynski** [comment]
> Thanks for deleting @akaszynski. I wanted to keep it around for GitHub support to investigate. I got a response this weekend and apparently I'm to blame for this. The push for the tag came from one of my computers. I'm going to investigate my bash history and get to the bottom of the mistake I made.
> 
> Sorry all, I'll do better!

If I had a dollar for every time I pushed a tag accidentally...
