### ISSUE TITLE
Some problems with pyvista on binder

### ISSUE THREAD

**Issue by mmagnuski** [pyvista/pyvista#556]
When launching the binder that is linked on the repo readme some of the examples do not work as expected:
* `point_cloud.plot(eye_dome_lighting=True)` does not give `eye_dome_lighting`:
![pyvista_binder_problem_00](https://user-images.githubusercontent.com/8452354/72840854-6f1a2700-3c95-11ea-9ad7-5beee4f4f28b.PNG)

* `point_cloud.plot(render_points_as_spheres=True)` does not render spheres:
![pyvista_binder_problem_01](https://user-images.githubusercontent.com/8452354/72840982-b7394980-3c95-11ea-9083-697bcbffd785.PNG)

* reading the dolphin data gives KeyError (seems that lxml is not present on binder)
```python-traceback
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/srv/conda/envs/notebook/lib/python3.7/site-packages/pyvista/utilities/fileio.py in read(filename, attrs, file_format)
    206         try:
--> 207             reader = get_reader(filename)
    208             return standard_reader_routine(reader, filename)

/srv/conda/envs/notebook/lib/python3.7/site-packages/pyvista/utilities/fileio.py in get_reader(filename)
     83     ext = get_ext(filename)
---> 84     return READERS[ext]() # Get and instantiate the reader
     85 

KeyError: '.xml'

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-719b69211249> in <module>
----> 1 dolfin = pv.read(saved_file)
      2 dolfin

/srv/conda/envs/notebook/lib/python3.7/site-packages/pyvista/utilities/fileio.py in read(filename, attrs, file_format)
    212                 from meshio._exceptions import ReadError
    213                 try:
--> 214                     return read_meshio(filename)
    215                 except ReadError:
    216                     pass

/srv/conda/envs/notebook/lib/python3.7/site-packages/pyvista/utilities/fileio.py in read_meshio(filename, file_format)
    281 
    282     # Read mesh file
--> 283     mesh = meshio.read(filename, file_format)
    284 
    285     # Extract cells from meshio.Mesh object

/srv/conda/envs/notebook/lib/python3.7/site-packages/meshio/_helpers.py in read(filename, file_format)
     65         raise ReadError(msg)
     66 
---> 67     return reader_map[file_format](filename)
     68 
     69 

/srv/conda/envs/notebook/lib/python3.7/site-packages/meshio/dolfin/_dolfin.py in read(filename)
    106 
    107 def read(filename):
--> 108     points, cells, cell_type = _read_mesh(filename)
    109     cell_data = _read_cell_data(filename, cell_type)
    110     return Mesh(points, cells, cell_data=cell_data)

/srv/conda/envs/notebook/lib/python3.7/site-packages/meshio/dolfin/_dolfin.py in _read_mesh(filename)
     15 
     16 def _read_mesh(filename):
---> 17     from lxml import etree as ET
     18 
     19     dolfin_to_meshio_type = {"triangle": ("triangle", 3), "tetrahedron": ("tetra", 4)}

ModuleNotFoundError: No module named 'lxml'
```
I just checked some of the examples so I am sure I didn't catch all of the problems on binder.

**Comment by banesullivan** [comment]
The binder is set up to embed the renderings in the notebook using vtkjs and panel which doesn't support eye dome lighting or rendering as spheres. Effectively, PyVista scene's data and color mappings are exported to the vtkjs format that then rerenders everything in the notebook.

If you want to see those features, you must pass `use_panel=False` on the `.show()` or `.plot()` call to not embed a vtkjs rendering but a static screenshot of the PyVista renderer

----


As for readign the dolphin mesh, I just added `lxml` to the [cookie-cutter](https://github.com/pyvista/cookiecutter-pyvista-binder), so on the next build, the environment should be updated with that package!

Thanks for pointing this out!
