### ISSUE TITLE
`black` and `flake8` disagree on code style

### ISSUE THREAD

**Issue by user27182** [pyvista/pyvista#5591]
### Describe the bug, what's wrong, and what you expected.

Running pre-commit on something like:

``` python
def foo():
    ...
```

will cause `black` to modify it to one-line:
``` python
def foo(): ...
```

after which, `flake8` will complain with `E704 multiple statements on one line (def)`, to which the solution is:
``` python
def foo():
    ...
```

and the cycle continues...

Not sure if this is introduced by #5581 ...

### Steps to reproduce the bug.

See above.

### System Information

```shell
See pre-commit config from #5581
```

**Comment by user27182** [comment]
Looks like `ruff` is in on the fight too.

If I add `# noqa: E704` comments to the lines to suppress the `flake8` errors, then `ruff` will step up and remove those and spit out:
```
ruff.....................................................................Failed
- hook id: ruff
- files were modified by this hook

warning: The top-level linter settings are deprecated in favour of their counterparts in the `lint` section. Please update the following options in `pyproject.toml`:
  - 'external' -> 'lint.external'
```
and then we're back at square one.

**Comment by user27182** [comment]
See https://github.com/psf/black/issues/4173

**Comment by MatthewFlamm** [comment]
We should only have one tool that does formatting.  Otherwise, these problems will continue to crop up.
