### ISSUE TITLE
Is there a way to improve the hardware selection to be more generic and manage more than one mesh?

### ISSUE THREAD

**Issue by math-artist** [pyvista/pyvista#560]
I often have many meshes visible at the same time. The current implementation is limited to a single node:
`cellids = selector.Select().GetNode(0)`
I tried a few trhings, but I can't figure a way to track which node is from which mesh. Is there a way to access an array (like the name of the mesh) from a vtkSelectionNode?

If there was a way to return all nodes with their corresponding meshes (or provide optionally a list of meshes instead on one), I could manage the behavior on a higher level depending on cases, and it would avoid a bad visual when the target mesh doesn't correspond to the ids selected.

**Comment by math-artist** [comment]
I found a way to get the actor:
```
selector.Select().GetNode(0).GetProperties().Get(vtk.vtkSelectionNode.PROP())
```
but I am a bit lost after that.

**Comment by banesullivan** [comment]
Just to be clear, this question appears to be for **visible** cell picking: `.enable_cell_picking(through=False)`. With **through** cell picking, we do not have a clean way to manage more than one mesh.

But with visible cell picking, #571 adds some improvements that might help with your issues by keeping each selection separated.

Also, note that using the snippet you shared:

```py
mesh = selector.Select().GetNode(0).GetProperties().Get(vtk.vtkSelectionNode.PROP()).GetMapper().GetInputAsDataSet()
```

will break if #570 is merged as the mesh given to the mapper is technically a different mesh than the one you are managing. We could mitigate that though...

**Comment by banesullivan** [comment]
This was implemented somewhere along the way
