### ISSUE TITLE
Crinkle clip duplicates cells in the unclipped surface 

### ISSUE THREAD

**Issue by swnlia001** [pyvista/pyvista#5667]
### Describe the bug, what's wrong, and what you expected.

When I implement the crinkle clip feature in pyvista.DataSetFilters.clip and set crinkle=True and return_clipped=True there are common cells between the clipped and unclipped datasets. I would expect that the unclipped surface would be effectively the original surface, without the clipped part. 

It would be great if this could be changed because I would like to continue clipping the unclipped surface again but without the duplicated cells at interface.

Thanks! 

### Steps to reproduce the bug.

```python
import pyvista as pv
import numpy as np

dataset = pv.examples.download_bunny_coarse()
clipped, unclipped = dataset.clip('y', return_clipped=True, crinkle=True)

clipped.save(".../bunny_top.vtk")
unclipped.save(".../bunny_bottom.vtk")
```

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Thu Feb 22 15:43:29 2024 GMT Standard Time
            
                OS : Windows
            CPU(s) : 36
           Machine : AMD64
      Architecture : 64bit
               RAM : 255.7 GiB
       Environment : IPython
        GPU Vendor : NVIDIA Corporation
      GPU Renderer : Quadro RTX 4000/PCIe/SSE2
       GPU Version : 4.5.0 NVIDIA 536.67
  MathText Support : False
  Python 3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]
           pyvista : 0.42.2
               vtk : 9.2.6
             numpy : 1.20.1
        matplotlib : 3.3.4
            scooby : 0.7.2
             pooch : v1.7.0
            pillow : 8.2.0
           imageio : 2.9.0
             PyQt5 : 5.9.2
           IPython : 7.22.0
        ipywidgets : 7.6.3
             scipy : 1.6.2
              tqdm : 4.59.0
        jupyterlab : 3.0.14
      nest_asyncio : 1.5.1
  Intel(R) oneAPI Math Kernel Library Version 2021.2-Product Build 20210312
  for Intel(R) 64 architecture applications
--------------------------------------------------------------------------------
```

### Screenshots

![image](https://github.com/pyvista/pyvista/assets/46969157/b489e1fc-55be-442b-b2c6-aa30fe61d21c)

**Comment by banesullivan** [comment]
Actually, I think the issue is that if using the `return_clipped` option, then there is no crinkling happening at all as the code currently returns before crinkling:

https://github.com/pyvista/pyvista/blob/05ac920de42913f531bdc53049afe69c9e20df07/pyvista/core/filters/data_set.py#L72-L81

**Comment by banesullivan** [comment]
I think the changes in #6060 will fix this, would you please review these changes?
