### ISSUE TITLE
Surface area deviation when converting from cell to point data

### ISSUE THREAD

**Issue by njpatter** [pyvista/pyvista#5746]
### Describe the bug, what's wrong, and what you expected.

I understand that conversion from cell to point data is not likely to be perfect, but the deviation in surface area appears to be much worse with higher mesh refinement. 

For a relatively low poly count (~200 tris) STL:
Area of sphere_normalized.stl: Original - 3.0471608009244546 vs After Computing - 3.0471608009244546 vs Point Sum - 2.727006205896471 (with mean=0.013367677479884661 and std=0.004922642704804401)

For a modified and refined version (~92k tris) of the same shape (which will have an initial area that is expected to be different):
Area of sphere_normalized_modified.stl: Original - 3.3346393946423287 vs After Computing - 3.3346393946423287 vs Point Sum - 1.6482664228430108 (with mean=3.5449639169885814e-05 and std=7.057096649820191e-06)

### Steps to reproduce the bug.

```python
def calculate_areas(filename=""):
    mesh = pyvista.read(filename)
    og_area = mesh.area
    mesh = mesh.compute_cell_sizes()
    mesh = mesh.cell_data_to_point_data()
    print(
        f"Area of {filename}: Original - {og_area} vs After Computing - {mesh.area} vs Point Sum - {mesh['Area'].sum()} (with mean={mesh['Area'].mean()} and std={mesh['Area'].std()})"
    )
)
```

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Fri Mar 08 05:36:44 2024 Central Standard Time

                OS : Windows
            CPU(s) : 16
           Machine : AMD64
      Architecture : 64bit
               RAM : 15.7 GiB
       Environment : Python
        GPU Vendor : Intel
      GPU Renderer : Intel(R) UHD Graphics
       GPU Version : 4.5.0 - Build 31.0.101.4255
  MathText Support : False

  Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64
  bit (AMD64)]

           pyvista : 0.43.2
               vtk : 9.3.0
             numpy : 1.24.4
        matplotlib : 3.7.4
            scooby : 0.9.2
             pooch : 1.8.0
            pillow : 10.2.0
           imageio : 2.33.1
           IPython : 8.12.3
        ipywidgets : 8.1.2
             scipy : 1.10.1
              tqdm : 4.66.1
      nest_asyncio : 1.6.0
--------------------------------------------------------------------------------
```

**Comment by njpatter** [comment]
It is used as part of the NVidia Modulus mesh graph net example focusing on aerodynamics:
[Modulus - Ahmed Body Example](https://github.com/NVIDIA/modulus/tree/1658a43ead87b7466c510be6fd638919bd842bb1/examples/cfd/ahmed_body_mgn)

The areas are calculated following mesh loading:
[Ahmed data loading and area calculation](https://github.com/NVIDIA/modulus/blob/main/modulus/datapipes/gnn/ahmed_body_dataset.py#L248)
 and are used post-inference to determine drag forces/coefficients based on inferred pressure and shear stress data. 

I found this when running my own models and the resulting forces were off by approximately the same factor that the area numbers were misaligned.

**Comment by MatthewFlamm** [comment]
A couple of points here, is it possible to use `integrate_data` filter to integrate the point data you are interested in over the area?  This would be the way I would do this.

If you must use point data with area converted to point data, you will have to account for the number of points in each cell and the area of each cell that is connected to each point.  This is doable, but not trivial. You cannot simply do a `sum` of the point data.  This will give you the wrong answer as you obtained.

**Comment by njpatter** [comment]
Just to make sure I understand, you're suggesting:
1. Load mesh, don't save point area
2. Train and run inference
3. Add inferred pressure and shear stress data to original mesh as point data (multiplied by normals as needed for force directionality)
4. Run integrate_data on the mesh
5. Use integrated values for pressure and shear stress for forces

If that's correct I can test it out later today on a dataset I'm running now

**Comment by MatthewFlamm** [comment]
Sounds better to me

**Comment by njpatter** [comment]
Went well for the smaller data set, so I ran a much larger one.  Results are within 2% between OpenFOAM and NVidia Modulus... I need to test with a lot more models but for now I'm going to take this as a win.

Thanks for the suggestion!
