### ISSUE TITLE
`download_osmnx_graph` produces a deprecation warning  for the `shapely` package

### ISSUE THREAD

**Issue by user27182** [pyvista/pyvista#5812]
### Describe what maintenance you would like added.

Running 
```bash
pip install pyvista osmnx | python -c "from pyvista.examples.downloads import download_osmnx_graph; download_osmnx_graph()"
```

Gives a deprecation warning:
```
UserWarning: Unpickling a shapely <2.0 geometry object. Please save the pickle again; shapely 2.1 will not have this compatibility.
  return pickle.load(open(filename, 'rb'))
```

This dataset was originally added in https://github.com/pyvista/pyvista/pull/1611

cc @akaszynski 

EDIT:
The maintenance to be done is perhaps to update the example? Or maybe add a note to the example about the `shapely` version requirements.

Link to the docs page for this example: [link](https://docs.pyvista.org/version/stable/api/examples/_autosummary/pyvista.examples.downloads.download_osmnx_graph.html)
Line generating the warning:
https://github.com/pyvista/pyvista/blob/3d6e327a7c43d9035ad54de936228f3ac7c5a88a/pyvista/examples/downloads.py#L3932

Note: This warning was found while running some tests locally as part of #5787

**Comment by akaszynski** [comment]
Let's drop this example. I think we already have a ton of dependencies in our examples, and we might consider separating out some of our extended examples into a separate repo.
