### ISSUE TITLE
render call forces window to appear prematurely

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#585]
I believe the changes to the `render` method of `BasePlotter` in #548 forces the render window to appear prematurely

pinging @GuillaumeFavelier 

This is occurring on the `master` branch (not on the last release)

-----

**To Reproduce**

```py
(dev) ➜  docs git:(master) python
Python 3.7.3 | packaged by conda-forge | (default, Dec  6 2019, 08:36:57)
[Clang 9.0.0 (tags/RELEASE_900/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvista as pv
>>> import vtk
>>> p = pv.Plotter()
>>> p.add_actor(vtk.vtkActor())
((vtkRenderingOpenGL2Python.vtkOpenGLActor)0x7fa5f0778a68, (vtkRenderingOpenGL2Python.vtkOpenGLProperty)0x7fa5f0778d08)
>>> # and an unresponsive window appears
```

**Screenshots**

![2020-02-04 14 46 36](https://user-images.githubusercontent.com/22067021/73790123-2cf4e900-475d-11ea-948c-51ae9cc4946e.gif)

**Comment by banesullivan** [comment]
Can confirm it's `render`. Doing the following causes it to happen:

```py
>>> import pyvista as pv
>>> p = pv.Plotter()
>>> p.render()
>>>
```

**Comment by banesullivan** [comment]
My vote is to add a check of `self._first_time` in `def render()` and have nothing happen if a user calls `render()` before `show()` (and of course document this behavior in `render()`)

**Comment by GuillaumeFavelier** [comment]
+1 for the `self._first_time`. You want to take care of it? Otherwise I can.
