### ISSUE TITLE
axes_range is reset by simultaneous use of all_edges=True

### ISSUE THREAD

**Issue by TSGut** [pyvista/pyvista#5856]
### Describe the bug, what's wrong, and what you expected.

This seems closely related to issue https://github.com/pyvista/pyvista/issues/5649 and PR https://github.com/pyvista/pyvista/pull/5670

Therein, it was described how using `axes_range` wasn't having any effect in either `show_grid()` and `show_bounds()`, which was recently fixed (thank you, it had been affecting me!). However, some similar bugs remain. In particular, setting `all_edges=True` appears to make `axes_range` have no effect. I doubt this is intended.

### Steps to reproduce the bug.

```python
import pyvista as pv

pl = pv.Plotter()
pl.add_mesh(pv.Sphere())
pl.show_grid(axes_ranges=[5, 10, 5, 10, 5, 10], all_edges=True)
pl.show()
```

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Tue Apr 02 22:55:13 2024 Pacific Daylight Time

                OS : Windows
            CPU(s) : 12
           Machine : AMD64
      Architecture : 64bit
               RAM : 15.7 GiB
       Environment : IPython
       GPU Details : error
  MathText Support : False

  Python 3.11.7 | packaged by Anaconda, Inc. | (main, Dec 15 2023, 18:05:47)
  [MSC v.1916 64 bit (AMD64)]

           pyvista : 0.43.4
               vtk : $PKG_VERSION
             numpy : 1.26.4
        matplotlib : 3.8.0
            scooby : 0.9.2
             pooch : 1.7.0
            pillow : 10.2.0
           imageio : 2.33.1
             PyQt5 : 5.15.10
           IPython : 8.20.0
          colorcet : 3.0.1
        ipywidgets : 7.6.5
             scipy : 1.11.4
              tqdm : 4.65.0
        jupyterlab : 4.0.11
      nest_asyncio : 1.6.0

  Intel(R) oneAPI Math Kernel Library Version 2023.1-Product Build 20230303
  for Intel(R) 64 architecture applications
--------------------------------------------------------------------------------
```

### Screenshots

Result with `all_edges=True` (odd behavior, probably a bug):

![image](https://github.com/pyvista/pyvista/assets/34382069/3a73e990-014e-4754-a9b2-266446e6005b)

Result with `all_edges=False` (as expected & correct):

![image](https://github.com/pyvista/pyvista/assets/34382069/906f7e42-913b-4850-bc68-5266614d050f)

**Comment by tkoyama010** [comment]
ping @kmarchais
