### ISSUE TITLE
`GeoVista` integration tests are failing

### ISSUE THREAD

**Issue by user27182** [pyvista/pyvista#5871]
### Describe what maintenance you would like added.

See failure here:
https://github.com/pyvista/pyvista/actions/runs/8576853557/job/23508600334?pr=5822#step:9:51

Looks like it has to do with `cmocean`. And a new version was just released 2 hrs ago on `PyPI`
https://pypi.org/project/cmocean/#history

**Comment by bjlittle** [comment]
@user27182 I've rerun the failing pyvista integration test for GeoVista on https://github.com/pyvista/pyvista/pull/5822 successfully.

It pulled in cmocean 4.0.3, which is the latest patch release on PyPI, and thankfully this works 😅

Seems like the released some bad builds over on cmocean, but they've now fixed that blip.

Happy to close this pull-request now?

**Comment by user27182** [comment]
Good to know, thanks. It was version 4.0.2 when I opened this issue. If everything is working again as-is then yes this and the GeoVista PR can be closed 👍
