### ISSUE TITLE
Corrupted gif / movie 

### ISSUE THREAD

**Issue by hichamjanati** [pyvista/pyvista#597]
I cannot reproduce the doc examples [Orbiting](https://docs.pyvista.org/examples/02-plot/orbit.html#sphx-glr-examples-02-plot-orbit-py) or [create a gif](https://docs.pyvista.org/examples/02-plot/gif.html)

```python
import pyvista as pv
from pyvista import examples

mesh = examples.download_st_helens().warp_by_scalar()
p = pv.Plotter()
p.add_mesh(mesh)
p.show(auto_close=False)
path = p.generate_orbital_path(n_points=20, shift=mesh.length)
p.open_gif("orbit.gif")
p.orbit_on_path(path, write_frames=True)
p.close()
```

I get corrupted gif / mp4 like this one for both examples. I can however plot the examples and take a single screenshot  just fine.

![orbit](https://user-images.githubusercontent.com/17051500/74090511-68b8e700-4aac-11ea-933c-63232ab2e6ac.gif)

```txt
  Date: Sat Feb 08 19:48:24 2020 CET

            Darwin : OS
                 4 : CPU(s)
            x86_64 : Machine
             64bit : Architecture
           16.0 GB : RAM
           IPython : Environment
        GPU Vendor : Intel Inc.
      GPU Renderer : Intel(R) Iris(TM) Plus Graphics 650
       GPU Version : 4.1 INTEL-14.3.9

  Python 3.6.8 |Anaconda, Inc.| (default, Dec 29 2018, 19:04:46)  [GCC 4.2.1
  Compatible Clang 4.0.1 (tags/RELEASE_401/final)]

            0.23.1 : pyvista
             8.1.2 : vtk
            1.17.3 : numpy
             2.2.0 : imageio
             1.4.3 : appdirs
             0.5.0 : scooby
             3.1.1 : matplotlib
            5.14.1 : PyQt5
             6.2.1 : IPython

  Intel(R) Math Kernel Library Version 2019.0.1 Product Build 20180928 for
  Intel(R) 64 architecture applications


```

**Comment by banesullivan** [comment]
well this isn’t good... a few thoughts. When the plotter shows, are you by chance pressing the exit button? Maybe try using the q-key instead.

If that fails, can you save normal screenshots okay?:

```py
import pyvista as pv
mesh = pv.Sphere()
p = pv.Plotter()
p.add_mesh(mesh, show_edges=True)
p.screenshot(“test.png”)
p.show()
```

and is there any difference if you do:
```py
p = pv.Plotter()
p.add_mesh(mesh, show_edges=True)
p.show(auto_close=False)
p.screenshot(“test.png”)
p.close()
```

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hichamjanati** [comment]
Awesome, it works ! yes, i was using the exit button. 
about your snippet, again it works only If I quit  by pressing q.

**Comment by banesullivan** [comment]
At first glance, this seems like a known issue which we tried to document see [`show()`](https://docs.pyvista.org/plotting/plotting.html#pyvista.Plotter.show):

> Please use the q-key to close the plotter as some operating systems (namely Windows) will experience issues saving a screenshot if the exit button in the GUI is prressed.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by banesullivan** [comment]
Glad you got it working! Let us know if you think there is a way to better document that the exit button can cause this... perhaps we should put it in the `open_gif`/`screenshot` methods’ docs

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hichamjanati** [comment]
Yes, perhaps in these examples involving screenshots, between `p.show(auto_close=False)` and the rest of the code, add a warning (close with q) in text. If you agree with that, I can make a PR.
