### ISSUE TITLE
Scrollbars in interactive viewer in jupyter 

### ISSUE THREAD

**Issue by ChristosT** [pyvista/pyvista#5976]
### Describe the bug, what's wrong, and what you expected.

As mentioned in a  previous PR https://github.com/pyvista/pyvista/pull/4847

>  Or maybe there should never be scroll bars, or maybe we can detect when they should be there...?

Do we really need these scrollbars in the generated iframes ? In all the examples that I have seen they introduce only a small amount of scrolling which is never really useful. 

Is there any issue with adding `scrolling='no'` in the html widget of trame in pyvista ? https://github.com/pyvista/pyvista/blob/main/pyvista/trame/jupyter.py#L70 

Or there is a better way to fix this issue ?

cc: @pyvista/kitware  @banesullivan 

### Steps to reproduce the bug.

Run any example in `jupyter` or through `nbconvert`  e.g
![Screenshot from 2024-04-25 12-16-40](https://github.com/pyvista/pyvista/assets/6725596/ba317d60-53c2-4795-b6dd-49cdc67b1c5c)

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Thu Apr 25 12:20:12 2024 EDT

                OS : Linux
            CPU(s) : 16
           Machine : x86_64
      Architecture : 64bit
               RAM : 62.5 GiB
       Environment : Python
       File system : ext4
        GPU Vendor : NVIDIA Corporation
      GPU Renderer : NVIDIA RTX A2000 Laptop GPU/PCIe/SSE2
       GPU Version : 4.5.0 NVIDIA 535.171.04
  MathText Support : True

  Python 3.10.14 (main, Apr  6 2024, 18:45:05) [GCC 9.4.0]

           pyvista : 0.44.dev0
               vtk : 9.3.0
             numpy : 1.26.4
        matplotlib : 3.8.4
            scooby : 0.9.2
             pooch : 1.8.1
            pillow : 10.3.0
           imageio : 2.34.0
           IPython : 8.23.0
          colorcet : 3.1.0
           cmocean : 4.0.3
        ipywidgets : 8.1.2
             scipy : 1.13.0
              tqdm : 4.66.2
            meshio : 5.3.5
        jupyterlab : 4.1.6
    pytest_pyvista : 0.1.8
             trame : 3.6.0
      trame_client : 3.0.2
      trame_server : 3.0.0
         trame_vtk : 2.8.6
     trame_vuetify : 2.4.3
      nest_asyncio : 1.6.0
--------------------------------------------------------------------------------
```

**Comment by banesullivan** [comment]
I don't see these scrollbars on my end... I'm wondering if this is a system-level or browser-level configuration?

I found that on MacOS, I can change these settings and the behavior changes:

<img width="475" alt="Screenshot 2024-04-26 at 5 46 23 PM" src="https://github.com/pyvista/pyvista/assets/22067021/30e54d4c-92ae-445a-b0e7-81b6535feffc">

With what I have selected above, there are no scroll bars present or the ability to scroll.

**Comment by jourdain** [comment]
PyVista viewer needs to add a `client.Style("html{overflow: hidden;}")` under its layout.

**Comment by ChristosT** [comment]
> PyVista viewer needs to add a `client.Style("html{overflow: hidden;}")` under its layout.

This helps on Firefox but not on Chrome on Linux  

See below
![Screenshot from 2024-04-28 21-34-18](https://github.com/pyvista/pyvista/assets/6725596/5ea24cec-8ab9-4281-8942-85493431de50)
![Screenshot from 2024-04-28 21-35-12](https://github.com/pyvista/pyvista/assets/6725596/95d37a0f-39a0-47b2-bfe8-4b88f71dfe0e)

**Comment by jourdain** [comment]
@ChristosT let's chat tomorrow.

**Comment by ChristosT** [comment]
The issue is fixed upstream in vtk-js (https://github.com/Kitware/vtk-js/pull/3065) that provides the embedded viewer. 
The latest version of trame-vtk `2.8.8` brings the updated viewer.
