### ISSUE TITLE
meshio version spec, `<4`

### ISSUE THREAD

**Issue by nschloe** [pyvista/pyvista#606]
For the meshio dependency you probably want `<4`. meshio follows [semver](https://semver.org/), major version bumps mean API breakage.

**Comment by banesullivan** [comment]
Thanks @nschloe, is `v4`  planned to release soon? Will there be a list of what changed exactly so we can adjust.

**Comment by nschloe** [comment]
>  is v4 planned to release soon? 

Inshallah.

> Will there be a list of what changed exactly so we can adjust.

Perhaps it's time for us to start getting a little more serious about changelogs now. Well, anyhow, put `<4` and you have all the time in the world.

**Comment by banesullivan** [comment]
Will do, we are having some issues with recent changes (#600) so it will be a while before we can push a release with that spec. Hopefully, we beat you to a release

> Perhaps it's time for us to start getting a little more serious about changelogs now.

We'd greatly appreciate that in cases where the API changes now that we are a dependency of `meshio`. General releases probably do not need a full changelog though

**Comment by banesullivan** [comment]
Note to self because I will totally forget: before closing this issue make sure the version is set in the conda-forge feedstock recipe as well

**Comment by keurfonluu** [comment]
> Thanks @nschloe, is `v4` planned to release soon? Will there be a list of what changed exactly so we can adjust.

I'll PR something when it's out.

The only thing issue that I can think of right now is ``meshio`` v4 dropping support for Python 3.5. Should PyVista handle this case by keeping the old code when ``meshio<4.*`` is detected?

**Comment by akaszynski** [comment]
We plan on keeping support for Python 3.5 for some time as it seems that it's downloaded fairly often according to our [PyPi stats](https://pypistats.org/packages/pyvista).

Most likely, we'll just require <v4 until we drop Python3.5 support.  I think getting off Python 3.5 would be nice, but we'll probably do it in 2021-2022.

**Comment by nschloe** [comment]
> Most likely, we'll just require <v4 until we drop Python3.5 support.

:+1: 

> We plan on keeping support for Python 3.5 for some time as it seems that it's downloaded fairly often according to our PyPi stats.

Not really. It peaked around last October and now accounts for around 5% of your downloads. That's on par with your Python 2 users.

![pv](https://user-images.githubusercontent.com/181628/74276177-86d55000-4d15-11ea-93af-dcbbdf9378fa.png)

> I think getting off Python 3.5 would be nice, but we'll probably do it in 2021-2022.

[Python 3.5 EOL is in September this year](https://devguide.python.org/#status-of-python-branches), so perhaps you wouldn't want to stretch your own support to far beyond that.

**Comment by akaszynski** [comment]
All good points.  I'm having to do some extra steps on Azure for CI, so it would be great to be able to drop support for Python 3.5.  We'll plan to do it at the end of the year, if that's fine with @pyvista/developers...

**Comment by banesullivan** [comment]
I'm all for following the Python 3.5 EOL, so September or end of 2020 sounds good to me

**Comment by nschloe** [comment]
Okay so quick update, I adapted meshio to support 3.5, and it will do until Python 3.5 EOL. I think that's a solid policy for a package as far downstream as meshio. f-strings are cool, but upstream compatibility is cooler.

There will other breaking changes in meshio 4, so don't hesitate to `<4` for now anyway.
