### ISSUE TITLE
`PolyData` initializes verts as faces and does not raise error (and may crash Python)

### ISSUE THREAD

**Issue by user27182** [pyvista/pyvista#6115]
### Describe the bug, what's wrong, and what you expected.

This is allowed though I don't think it should be.
``` python
import pyvista as pv
poly = pv.PolyData([[1.,2.,3.],[4,5,6]],[1,0,1,1])
poly.verts  # []
poly.faces  # [1 0 1 1]
```
The issue is that these are vertex cells not faces. If debugging with PyCharm, accessing the `faces` property will crash Python (PyCharm auto-evaluates / accesses all attributes by default for some reason).

This should probably either be detected as vertices or raise an error saying to use `verts` explicitly, e.g. this works fine:
```python
poly = pv.PolyData([[1.,2.,3.],[4,5,6]], verts=[1,0,1,1])
poly.verts  # [1 0 1 1]
poly.faces  # []
```

### Steps to reproduce the bug.

See above

### System Information

```shell
OS : Darwin
            CPU(s) : 8
           Machine : arm64
      Architecture : 64bit
               RAM : 16.0 GiB
       Environment : Python
       File system : apfs
        GPU Vendor : Apple
      GPU Renderer : Apple M2
       GPU Version : 4.1 Metal - 88
  MathText Support : True

  Python 3.12.2 (v3.12.2:6abddd9f6a, Feb  6 2024, 17:02:06) [Clang 13.0.0
  (clang-1300.0.29.30)]

           pyvista : 0.44.dev0
               vtk : 9.3.0
             numpy : 1.26.4
        matplotlib : 3.8.2
            scooby : 0.9.2
             pooch : 1.8.0
            pillow : 10.2.0
           imageio : 2.34.0
           IPython : 8.21.0
          colorcet : 3.1.0
           cmocean : 3.1.3
        ipywidgets : 8.1.2
             scipy : 1.12.0
              tqdm : 4.66.2
            meshio : 5.3.5
        jupyterlab : 4.1.4
    pytest_pyvista : 0.1.8
             trame : 3.5.3
      trame_client : 2.16.1
      trame_server : 2.17.2
         trame_vtk : 2.8.5
     trame_vuetify : 2.4.3
      nest_asyncio : 1.6.0
```

**Comment by darikg** [comment]
just to clarify, the underlying issue is faces with a single element?

**Comment by user27182** [comment]
> just to clarify, the underlying issue is faces with a single element?

Yes that's the bug reported above.  But it looks like it also applies to faces with two elements (lines).

Similar to above, the lines get stored as faces, there's no error, and PyCharm will crash:
``` python
python -c "import pyvista as pv;poly = pv.PolyData([[1.,2.,3.]],[2,0,1]); print(poly.lines, poly.faces)" 
[] [2 0 1]
```

And here's the expected output when setting ``lines`` explicitly:
``` python
python -c "import pyvista as pv;poly = pv.PolyData([[1.,2.,3.]],lines=[2,0,1]); print(poly.lines, poly.faces)"
Out: [2 0 1] []
```

**Comment by MatthewFlamm** [comment]
I do not get an error here although I'm not using PyCharm.  While unexpected, the behavior is consistent with how the `faces` work.  That is faces assumes that it is a Polygonal face, except when it can be represented by a special 2D cell like `vtkQuad`.  vtk apparently does not require a Polygonal face cell to have more than 2 points.  I wouldn't be surprised if reading in some file formats would end up with this representation.

One point per cell is a Polygonal cell with only 1 point

```py
import pyvista as pv
p = pv.PolyData([[1., 2., 3.]], [1, 0])
p.get_cell(0)
```

gives 

```txt
Cell (0x7585efab3e20)
  Type:        <CellType.POLYGON: 7>
  Linear:      True
  Dimension:   2
  N Points:    1
  N Faces:     0
  N Edges:     1
  X Bounds:    1.000e+00, 1.000e+00
  Y Bounds:    2.000e+00, 2.000e+00
  Z Bounds:    3.000e+00, 3.000e+00
```

Two points is a Polygonal cell with only two points.

```py
import pyvista as pv
p = pv.PolyData([[1., 2., 3.], [4., 5., 6.]], [2, 0, 1])
p.get_cell(0)
```

gives

```txt
Cell (0x7585efa4bee0)
  Type:        <CellType.POLYGON: 7>
  Linear:      True
  Dimension:   2
  N Points:    2
  N Faces:     0
  N Edges:     2
  X Bounds:    1.000e+00, 4.000e+00
  Y Bounds:    2.000e+00, 5.000e+00
  Z Bounds:    3.000e+00, 6.000e+00
```

This last example has the correct area (0) and length (5.196). All the operations I have tried, e.g. `compute_normals`, that might assume a non-degenerate cell haven't given an error.  Can you pinpoint which part crashes your system?

**Comment by user27182** [comment]
> Note this is not the `repr` from the `PolyData` but the `repr` from the only cell in that object. Since it is a polygonal cell, vtk returns the number of points for the number of edges, e.g. a quadrilateral has 4 points and thus 4 edges. A 1 or 2 point polygon is degenerate, but it seems vtk happily accepts it for vtkPolygon.

Gotcha, you're right I missed that it was the repr for the Cell.

So, in terms of the original issue, it seems there's no bug after all, I just need to read the docs more carefully. 

> > python -c "import pyvista as pv;poly = pv.PolyData([[1.,2.,3.]],[2,0,1]); poly.cell_normals"
> 
> This example is fatally flawed as there is no second point to reference. It isn't caused by the polygonal cell only having one or two points in it.

Yup you're right, the polygon is just defined incorrectly. But I wouldn't necessarily know that if I loaded a large mesh and got a mysterious crash. Or if I'm processing this array manually and introduce a bug somewhere. For this case maybe a simple warning (or error) would be good to add, e.g. add this check to init or when setting faces or any other properties which modify the connectivity :

``` python
def warn_connectivity(poly):
    if np.max(poly._connectivity_array) >= poly.n_points:
        warnings.warn(f'\nThe faces/polygons reference point ids that do not exist. The connectivity\n'
                      f'array should not have values that exceed the number of points ({poly.n_points}).\n'
                      f'This can cause Python to crash with some filters.')
```

**Comment by user27182** [comment]
The "init verts as faces" part of this issue is not a bug:
> While unexpected, the behavior is consistent with how the faces work.

so this issue can be closed.

For the crashing part caused by invalid connectivity, a similar issue https://github.com/pyvista/pyvista/issues/4735 was previously raised, so we can track that there.
