### ISSUE TITLE
Stale reference to requirements.txt in CONTRIBUTING.md

### ISSUE THREAD

**Issue by adeak** [pyvista/pyvista#625]
[This commit](https://github.com/pyvista/pyvista/commit/33b8e0946c6c209bc83c1ed4bfd5ebf333ae1922) renamed requirements.txt to requirements_test.txt, but there was a reference to the old name left in [CONTRIBUTING.md](https://github.com/pyvista/pyvista/blob/master/CONTRIBUTING.md). `git grep` doesn't seem to show any other instances of the old name.

**Comment by adeak** [comment]
Is it worth opening a PR for this trivial doc change (especially considering the broken CI)? Or can a member just push a change with it?

**Comment by GuillaumeFavelier** [comment]
I tried to change it directly but I can't, maybe @akaszynski or @banesullivan can take care of it otherwise a PR might be necessary. 

About the CIs, this should be solved now. You can even update #624 with `master`
