### ISSUE TITLE
Return type hint in plotting/plotter.py

### ISSUE THREAD

**Issue by kmarchais** [pyvista/pyvista#6257]
### Describe the feature you would like to be added.

Hello, I would like to have a return type hint for methods in `plotting/plotter.py`.

For example with `add_mesh()` I would like to have a return type `Actor` so that my IDE (VS code) understand that the variable is an `Actor` and make it easier to navigate into the code.

In short, I would like to go from the first picture to the second:
![image](https://github.com/pyvista/pyvista/assets/22714778/a4122262-7462-4a04-a9f0-f9c358e0f03e)
![image](https://github.com/pyvista/pyvista/assets/22714778/f6bd93b6-ba65-406e-8e57-75240aff452a)

I wanted to make a PR but it seems I need to fix some additional ruff rules and mypy errors shown by pre-commit so I am a bit stuck. 
Is there a way to implement the return type hints? Or maybe a different way to solve my problem?

Thanks

**Comment by MatthewFlamm** [comment]
I personally find running `mypy` through pre-commit to be extremely awkward.  This is compounded by the fact that running mypy locally after doing `pip install -r requirements_docs.txt` etc. does not result in the same `mypy` environment as in pre-commit.
