### ISSUE TITLE
Change implementation and behaviour of BasePlotter.index_to_loc?

### ISSUE THREAD

**Issue by adeak** [pyvista/pyvista#626]
I came across the implementation of [`BasePlotter.index_to_loc`](https://github.com/pyvista/pyvista/blob/4769fdcd77978639c1caee66609d40acaa712c29/pyvista/plotting/plotting.py#L239-L248):

```py
    def index_to_loc(self, index):
        """Convert a 1D index location to the 2D location on the plotting grid."""
        if len(self.shape) == 1:
            return index
        sz = int(self.shape[0] * self.shape[1])
        idxs = np.array([i for i in range(sz)], dtype=int).reshape(self.shape)
        args = np.argwhere(idxs == index)
        if len(args) < 1:
            raise RuntimeError('Index ({}) is out of range.')
        return args[0]
```

I noticed that most of the function is a reimplementation of [`numpy.unravel_index`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.unravel_index.html):
```py
import numpy as np 
 
def index_to_loc(index, shape): 
    # snip: 1d case 
    sz = int(shape[0] * shape[1]) 
    idxs = np.array([i for i in range(sz)], dtype=int).reshape(shape)
    args = np.argwhere(idxs == index) 
    # snip: error bounds checking 
    return args[0] 
 
n,m = shape = (2, 3)  # example 2d shape 
for i in range(n * m): 
    print(index_to_loc(i, shape), np.unravel_index(i, shape))

# output:
# [0 0] (0, 0)
# [0 1] (0, 1)
# [0 2] (0, 2)
# [1 0] (1, 0)
# [1 1] (1, 1)
# [1 2] (1, 2)
```

It might make sense to reimplement `index_to_loc` as a thin wrapper of `np.unravel_index`. But this raises a few other questions/remarks:

  1. Tuples rather than arrays would be returned even in the 2d case; I don't believe this should be an issue in any use case.
  2. The 1d case would automatically work with the same function call. However, e.g. `np.unravel_index(2, (3,))` returns `(2,)` as opposed to `2`. This is great for type consistency, but would change the current behaviour of `index_to_loc`, which returns an `int` for the 1d case.
  3. From a quick search on github I couldn't find a single call to `index_to_loc` in this context, so not many people should be affected.
  4. Presumably the output of `index_to_loc` should primarily be used in `BasePlotter.subplot`. But this is defined such that the two indices would have to be passed as `subplot(*loc)`. Which would _also_ work with a `loc` in a 1-tuple, which is to say 1d and 2d cases would be treated on an equal footing. The cost is that if someone wants a proper scalar (`int`) index for the 1d case they have to unpack/index manually to get it.
  5. The current implementation doesn't check bounds for the 1d case. Using `np.unravel_index` would automatically raise a `ValueError` for out-of-bounds indices.

The main cons to the change I can think of:

  1. "_Don't fix what ain't broken_", although arguably a single library function call would be more maintainable.
  2. There might be affected users out there whose code could suddenly break (a bit).
  3. This could be part of https://github.com/pyvista/pyvista/issues/299 if that gets "fixed".

**Comment by akaszynski** [comment]
I'd prefer to use a numpy function rather than our own function, but we would have to account for the edge cases you noted.  As for your remarks:
1.  Not an issue as AFAIK
2.  We can simply return a single int when the length of the output tuple is one.
3.  It doesn't seem to be called at all (even in testing) which is troubling since we should have unit testing for it.
4.  Solved by 3
5.  Bounds checking would be great.

As for the cons:
1.  It's not broken, but it's also not used internally.  We need to either add tests and a proper docstring, or remove it.
2.  If we return an int when the length of the output tuple is 1, we should be good to go.
3.  #299 isn't going to happen until we've fixed the background plotter, so we have time.

I propose we move to cleanup `index_to_loc` by making it a wrapper to `unravel_index` as you mentioned.  Please add unit testing and cleanup the docstring.  @banesullivan added that a while back, do you have any objections?

**Comment by adeak** [comment]
> We can simply return a single int when the length of the output tuple is one.

Well that's way too obvious a solution ;)

Thanks, I'll wait for banesullivan's feedback but I'll gladly tackle this.

**Comment by GuillaumeFavelier** [comment]
We use it in `mne-python` to do `renderer picking` (from a list of renderers to subplot coordinates):

https://github.com/mne-tools/mne-python/blob/master/mne/viz/_brain/_timeviewer.py#L687-L689

**Comment by adeak** [comment]
@GuillaumeFavelier you got me worried for a second that I missed something when searching for that function, but it seems to me that the call was added in a commit 8 days ago :) Thanks for the link.

By the way: will that function call work correctly for cases when the subplots are 1d (from what I could tell, when the shape is `'1|3'` or `'1/3'`)? I think `index_to_loc` would return a scalar in that case, which you cannot unpack into `row, col`. But perhaps your use case is such that you always have a 2d grid.

**Comment by GuillaumeFavelier** [comment]
> your use case is such that you always have a 2d grid.

It is indeed the case so all good for folks on `mne-python` but I understand the concerns when using this type of `shape`. Something similar happens in https://github.com/pyvista/pyvista/issues/513#issuecomment-578283137

**Comment by adeak** [comment]
As of https://github.com/pyvista/pyvista/pull/696 the implementation has changed so much that this issue no longer applies. The implementation of `BasePlotter.index_to_loc` has been greatly simplified, and the new subplot grid feature would make `np.unravel_index` a no-go anyway :)
