### ISSUE TITLE
error in mp4 example

### ISSUE THREAD

**Issue by RubendeBruin** [pyvista/pyvista#627]
When running the Create a MP4 Movie example in python (not jupyter) the plot shows but no movie is created. 

ref: https://docs.pyvista.org/examples/02-plot/movie.html#sphx-glr-download-examples-02-plot-movie-py

cause:
```py

plotter = pv.Plotter()
...
# Render and do NOT close
plotter.show(auto_close=False)
```

opens a window and pauses execution until the window is closed. 

solution:

```py
plotter = pv.Plotter(off_screen=True)   # create an offscreen renderer

# plotter.show(auto_close=False)  # no need for show
```

**Comment by akaszynski** [comment]
Part of the reason why we have that there is so the user can setup the movie orientation beforehand, but if you want to see the move and have it start automatically you can with:
```python
plotter.show(interactive=False, auto_close=False)
```
If this seems like a good idea, I'll make a quick PR for it.

**Comment by RubendeBruin** [comment]
Hi @akaszynski 

I think what I did wrong was closing the windows using the "close" button instead of pressing the Q-key.

When I use the q-key everything works fine. If I close the window using the exit button then I get the following error:

C:\Users\beneden\Miniconda3\envs\vtk_tests\lib\site-packages\pyvista\plotting\plotting.py:3788: UserWarning: `auto_close` ignored: by clicking the exit button, you have destroyed the render window and we have to close it out.
  warnings.warn("`auto_close` ignored: by clicking the exit button, you have destroyed the render window and we have to close it out.")
Traceback (most recent call last):
  File "C:/data/hes/vtk_tests/test1.py", line 22, in <module>
    plotter.write_frame()  # write initial data
  File "C:\Users\beneden\Miniconda3\envs\vtk_tests\lib\site-packages\pyvista\plotting\plotting.py", line 2721, in write_frame
    self.mwriter.append_data(self.image)
  File "C:\Users\beneden\Miniconda3\envs\vtk_tests\lib\site-packages\imageio\core\format.py", line 484, in append_data
    self._checkClosed()
  File "C:\Users\beneden\Miniconda3\envs\vtk_tests\lib\site-packages\imageio\core\format.py", line 275, in _checkClosed
    raise RuntimeError(msg)
RuntimeError: I/O operation on closed Writer.


So maybe it is enough to just add a line:

print("Orient the view and then press 'q' to produce movie")

**Comment by banesullivan** [comment]
@RubendeBruin, would you be up for a small PR to put that print statement into that example? And perhaps the GIF one as well?

**Comment by RubendeBruin** [comment]
cando

**Comment by GuillaumeFavelier** [comment]
I reference https://github.com/pyvista/pyvista/issues/597 because I think it is related
