### ISSUE TITLE
DOCS: "Hide Cells with Ghosting" broken 0.43

### ISSUE THREAD

**Issue by ljrobins** [pyvista/pyvista#6334]
### Describe the bug, what's wrong, and what you expected.

The "[Hide Cells with Ghosting](https://docs.pyvista.org/version/stable/examples/02-plot/ghost-cells#sphx-glr-examples-02-plot-ghost-cells-py)" example shows correctly ghosted cells in the thumbnail image, but within the example the cells are opaque

### Steps to reproduce the bug.

[here](https://docs.pyvista.org/version/stable/examples/02-plot/ghost-cells#sphx-glr-examples-02-plot-ghost-cells-py)

### System Information

```shell
N.A.
```

**Comment by banesullivan** [comment]
Thanks for pointing this out! Something weird must have happened during that build of the documentations. I'll see if I can fix this

**Comment by MatthewFlamm** [comment]
Was this fixed in https://github.com/pyvista/pyvista/pull/5695?

**Comment by MatthewFlamm** [comment]
The dev docs look fine, although it is unclear to me how fresh those are.  https://docs.pyvista.org/version/dev/examples/02-plot/ghost-cells.html

**Comment by ljrobins** [comment]
Yup, looks good on dev!

**Comment by user27182** [comment]
The stable `0.44` docs are now live, and the example is working, this can probably be closed.
https://docs.pyvista.org/version/stable/examples/02-plot/ghost-cells.html
