### ISSUE TITLE
Help on Integrating Pyvista with Tkinter

### ISSUE THREAD

**Issue by lMavisl** [pyvista/pyvista#634]
Hi, I'm searching for ways to integrate Pyvista interactive plot onto Tkinter. Is it feasible? 
What i have right now is when i click a button on Tkinter, Python will run a script that process a set of data and plot a 3D visualization on a separate window using Pyvista. What i want is to plot the Pyvista interactive 3D visualization on the same Tkinter window where the button is.

**Comment by akaszynski** [comment]
Hello,

Sorry for the delayed response.  I've never worked with `tkinter` and vtk, but here's a demo that works with `tkinter` and vtk.  You can probably adapt the demo to utilize `pyvista` instead.  Let me know if need help getting the demo to work.
https://github.com/Kitware/VTK/blob/master/Examples/Modelling/Python/SpherePuzzle.py

**Comment by lMavisl** [comment]
Thank you!!

**Comment by akaszynski** [comment]
Please close the issue if you think it's solved.  We've got to do some spring cleaning for the other 73 issues...

**Comment by supergra** [comment]
Link above is broken, found a clone here: https://gitlab.kitware.com/cory.quammen/vtk/-/blob/3342a3279c6711c85612d3ee102abfc743356bfe/Examples/Modelling/Python/SpherePuzzle.py

**Comment by supergra** [comment]
There's a quick demo on this StackOverflow post as well: https://stackoverflow.com/questions/60649673/is-there-a-way-to-integrate-pyvista-with-tkinter  

It worked out of the box for me, without any of the special compiling it said would be necessary.

**Comment by akaszynski** [comment]
Thanks @supergra!
