### ISSUE TITLE
Broken documentation links

### ISSUE THREAD

**Issue by armoured-moose** [pyvista/pyvista#636]
Not sure if the docs need rebuilding? But for example they refer to a docs/examples folder which does not exist.

**To Reproduce**

visit [here](https://docs.pyvista.org/examples/01-filter/extract-edges.html) and click on 'edit on github'

**Comment by GuillaumeFavelier** [comment]
This is a very good point, I can reproduce this too. I never clicked on `Edit on Github` so I'm not sure what's happening here.

Maybe the linking is just not correct,  would redirect to the following for example:

https://github.com/pyvista/pyvista/blob/master/examples/01-filter/extract-edges.py

**Comment by GuillaumeFavelier** [comment]
It seems this has been reported already on `sphinx-gallery`:

https://github.com/readthedocs/readthedocs.org/issues/5131

**Comment by GuillaumeFavelier** [comment]
Anyway, thanks for reporting @armoured-moose, I asked for feedback on `sphinx-gallery`, we'll see how it goes. But maybe we'll disable the `Edit on github` button at least for the examples. I think it's better than having a broken link.

**Comment by armoured-moose** [comment]
Ah apologies! I did not find that! Glad to have been of (some) use.

**Comment by akaszynski** [comment]
Found the issue I think:
```
'github_version': 'master/docs',
```

When we changed the build pipeline, I must have changed the way docs were being deployed.

**Comment by akaszynski** [comment]
Solved in #639 by just removing the button.
