### ISSUE TITLE
Duplicate ray tracing example in 0.44 docs

### ISSUE THREAD

**Issue by ljrobins** [pyvista/pyvista#6396]
### Describe what maintenance you would like added.

There are two instances of the ray tracing example in the docs:

https://docs.pyvista.org/version/stable/examples/01-filter/poly-ray-trace#sphx-glr-examples-01-filter-poly-ray-trace-py
https://docs.pyvista.org/version/stable/examples/99-advanced/ray-trace#sphx-glr-examples-99-advanced-ray-trace-py

Since the example isn't very "advanced", I think it would be safe to remove it from that category.

**Comment by banesullivan** [comment]
Thanks for pointing this out! Indeed I also had the same thought of "this isn't very advanced"... not sure how its stuck around for so long: https://github.com/pyvista/pyvista/pull/949/files#r517094067

Feel free to open a PR deleting this example!
