### ISSUE TITLE
PyVista TypeError: SetSpacing argument

### ISSUE THREAD

**Issue by Camkash** [pyvista/pyvista#642]
I have also posted this issue on StackOverflow.
https://stackoverflow.com/questions/60737919/pyvista-typeerror-setspacing-argument

I previously ran the following with no issues.

```
grid=pv.UniformGrid()
grid.points=np.array([x_surf,y_surf,z_surf]).transpose()
```

Today, I ran it and received the following. I have already tried reinstalling the package.

```
Traceback (most recent call last):

  File "C:\Users\camramez\Documents\Meshing\gen_terrain.py", line 28, in <module>
    grid.points=np.array([x_surf,y_surf,z_surf]).transpose()

  File "C:\ProgramData\Anaconda3\envs\mesh\lib\site-packages\pyvista\core\grid.py", line 470, in points
    self._from_specs((nx,ny,nz), (dx,dy,dz), (ox,oy,oz))

  File "C:\ProgramData\Anaconda3\envs\mesh\lib\site-packages\pyvista\core\grid.py", line 435, in _from_specs
    self.SetSpacing(xs, ys, zs)

TypeError: SetSpacing argument %Id: %V
```

The SetSpacing function on its own works fine. I have done the following as a quick fix, which works, but it does not technically solve the error.

```
try:
    grid.points=np.array([x_surf,y_surf,z_surf]).transpose()
except:
    1
```

**Comment by GuillaumeFavelier** [comment]
Although you don't specify `spacing` explictly, it is automatically computed in `grid.points` with the user-given `points`. It is possible that something unexpected happens during this step. This is difficult for me to debug if I can't reproduce, I tried the following:

```py
import numpy as np
import pyvista as pv

x_surf = y_surf = z_surf = range(10)

grid = pv.UniformGrid()
grid.points = np.array([x_surf, y_surf, z_surf], dtype=np.int32).transpose()
grid.plot(show_edges=True)
```

There is a developer warning at :

https://github.com/pyvista/pyvista/blob/master/pyvista/core/grid.py#L466

Which makes me think that your particular use case is not tested.

By any chance, could you modify your code snippet to integrate:

```py
# points is the numpy array sent to grid.points
x = np.unique(points[:,0])
y = np.unique(points[:,1])
z = np.unique(points[:,2])
dx, dy, dz = np.unique(np.diff(x)), np.unique(np.diff(y)), np.unique(np.diff(z))
```

And give some infos about `(dx, dy, dz)`?

**Comment by Camkash** [comment]
**The realisation**
I realised my mistake now.

grid is supposed to be a flat surface. It works when I just do
```
grid.points=np.array([x_surf,y_surf]).transpose()
```
And then add and warp by scalars later.

#############################################
**Before the realisation:**
Interestingly enough the top code in your previous message works.

I tried specifying grid spacing but received the same error.
I tried specifying dtype as np.int32 but received the same error


Considering it works if I ignore the error:
```
try:
    grid.points=np.array([x_surf,y_surf,z_surf]).transpose()
except:
    1
```
And then considering the bottom code in your previous message:
```
x1 = np.unique(grid.points[:,0])
y1 = np.unique(grid.points[:,1])
z = np.unique(grid.points[:,2])
dx1, dy1, dz1 = np.unique(np.diff(x1)), np.unique(np.diff(y1)), np.unique(np.diff(z1))
```
x1.shape is (80,)
y1.shape is (80,)
z1.shape is (1,)
dx1 returns array([1., 1.])
dy1 returns array([1., 1.])
dz1 returns array([], dtype=float64)

**Comment by GuillaumeFavelier** [comment]
Thanks for trying it out! Also, I'm glad to you were able to solve your issue.

Based on your tests, I believe I can reproduce now:

```py
import numpy as np
import pyvista as pv

x_surf = y_surf = range(80)
z_surf = np.ones(80)

grid = pv.UniformGrid()
grid.points = np.array([x_surf, y_surf, z_surf]).transpose()
grid.plot(show_edges=True)
```

Which leads on my configuration to:

```
Traceback (most recent call last):
  File "/tmp/bug.py", line 8, in <module>
    grid.points = np.array([x_surf, y_surf, z_surf]).transpose()
  File "/home/guillaume/source/pyvista/pyvista/core/grid.py", line 477, in points
    self._from_specs((nx,ny,nz), (dx,dy,dz), (ox,oy,oz))
  File "/home/guillaume/source/pyvista/pyvista/core/grid.py", line 435, in _from_specs
    self.SetSpacing(xs, ys, zs)
TypeError: SetSpacing argument 3: only size-1 arrays can be converted to Python scalars
```

I still think it should be tested :smile: zso I'll take care of it
