### ISSUE TITLE
Plots do not show

### ISSUE THREAD

**Issue by baloe** [pyvista/pyvista#6434]
### Describe the bug, what's wrong, and what you expected.

For some reason pyvista does not produce any plots anymore.  
It won't even open a window when running the show function. 

I tried three examples from the examples page and am clueless what else to do.

### Steps to reproduce the bug.

1. Download the `cmap.py` from here:  
    https://docs.pyvista.org/examples/02-plot/cmap#sphx-glr-download-examples-02-plot-cmap-py

3. Run `python -i cmap.py`

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Mon Jul 29 15:59:17 2024 CEST

                OS : Linux (Ubuntu 20.04)
            CPU(s) : 8
           Machine : x86_64
      Architecture : 64bit
               RAM : 31.2 GiB
       Environment : Python
       File system : ext4
        GPU Vendor : Mesa
      GPU Renderer : llvmpipe (LLVM 18.1.8, 256 bits)
       GPU Version : 4.5 (Core Profile) Mesa 24.1.4
  MathText Support : True

  Python 3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:36:13) [GCC
  12.3.0]

           pyvista : 0.44.1
               vtk : 9.3.1
             numpy : 1.26.4
        matplotlib : 3.9.1
            scooby : 0.10.0
             pooch : 1.8.2
            pillow : 10.4.0
           imageio : 2.34.2
             PyQt5 : 5.15.9
           IPython : 8.16.1
          colorcet : 3.1.0
        ipywidgets : 8.1.3
             scipy : 1.14.0
              tqdm : 4.66.4
            meshio : 5.3.5
        jupyterlab : 4.0.7
      nest_asyncio : 1.6.0
--------------------------------------------------------------------------------
```

**Comment by baloe** [comment]
Mh after creating a fresh conda environment and installing pyvista from conda-forge there, the report actually lists my GPU and pyvista functions as usual.

**Comment by banesullivan** [comment]
I wonder if you had installed a variant of VTK like `vtk-osmesa` that was forcing off-screen rendering? 

Going to close this issue since the issue seems to be resolved.

**Comment by LeErnst** [comment]
What was the solution? I have exactly the same problem...

**Comment by panziyi1** [comment]
> I wonder if you had installed a variant of VTK like `vtk-osmesa` that was forcing off-screen rendering?
> 
> Going to close this issue since the issue seems to be resolved.

How do we know if a variant is being used or off_screen is activated?
