### ISSUE TITLE
Cannot import pyvista with pythonw

### ISSUE THREAD

**Issue by FedeMiorelli** [pyvista/pyvista#644]
I am not able to import pyvista if using pythonw, which causes stderr to be None.

Below is a code to reproduce. I have to direct output to a file to save the output both when running python and pythonw.

-----

**To Reproduce**

Run this snippet with "python" - output.txt contains "OK"
Run this with "pythonw" -  it goes in the exception handler and it contains "Exception!:  sys.stderr is None"

```py

from contextlib import redirect_stdout

with open('output.txt', 'w') as fid, redirect_stdout(fid):
    try:
        import pyvista as pv
        print("OK")
        
    except Exception as exc:
        print('Exception!: ', str(exc))

```

-----

**System Information:**
 Please run the following code wherever you are experiencing the bug and paste the output below. This report helps us track down bugs and it is critical to addressing your bug:

```txt

--------------------------------------------------------------------------------
  Date: Wed Mar 18 16:20:43 2020 W. Europe Standard Time

                OS : Windows
            CPU(s) : 4
           Machine : AMD64
      Architecture : 64bit
               RAM : 7.7 GB
       Environment : Python
        GPU Vendor : Intel
      GPU Renderer : Intel(R) HD Graphics 620
       GPU Version : 4.5.0 - Build 23.20.16.4973

  Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64
  bit (AMD64)]

           pyvista : 0.24.0
               vtk : 8.1.2
             numpy : 1.18.1
           imageio : 2.8.0
           appdirs : 1.4.3
            scooby : 0.5.2
        matplotlib : 3.0.3
             PyQt5 : 5.14.1
           IPython : 7.13.0
             scipy : 1.4.1
--------------------------------------------------------------------------------


```

**Comment by akaszynski** [comment]
Interesting!  I'm going to test this locally on windows and get back to you.

**Comment by FedeMiorelli** [comment]
Yes, really strange! Took me forever to track down the issue as it was never happening while debugging :)
Thanks for looking into this.

**Comment by akaszynski** [comment]
I can reproduce this error on my end.  `pyvista==0.21.0` doesn't have this issue so until we get this patched, please use an earlier version.  I think it's because we're capturing `std.stderr` and `pythonw.exe` doesn't have that (apparently!).
