### ISSUE TITLE
Add a figure of CellTypes to explain the shape and the order of node in `pyvista.CellType` section

### ISSUE THREAD

**Issue by tkoyama010** [pyvista/pyvista#6549]
### Describe what maintenance you would like added.

We a figure of CellTypes to explain the shape and the order of node in [`pyvista.CellType` section](https://docs.pyvista.org/api/utilities/_autosummary/pyvista.celltype#pyvista-celltype).

### Links to source code.

https://docs.pyvista.org/api/utilities/_autosummary/pyvista.celltype#pyvista-celltype

### Pseudocode or Screenshots

![image](https://github.com/user-attachments/assets/d1820a75-fd96-4a15-95b0-d083598f1c3f)

**Comment by user27182** [comment]
It should be possible to directly link to the example images for the cells here. E.g. for the [line cell example](https://dev.pyvista.org/api/examples/_autosummary/pyvista.examples.cells.line#pyvista.examples.cells.Line), we can link to the figure anywhere in the docs with this directive:

``` rst
.. image:: /../_build/plot_directive/api/examples/_autosummary/pyvista-examples-cells-Line-1_00_00.png
```

This is how the [Dataset Gallery](https://dev.pyvista.org/api/examples/dataset_gallery) works. All the thumbnails there are taken from the generated images in the docs.

So, as long long as there is an example written for the cell, we can grab its image and display it in [pyvista.CellType](https://docs.pyvista.org/api/utilities/_autosummary/pyvista.celltype#pyvista-celltype).

**Comment by user27182** [comment]
There is also a full example generating 16 linear cells here:https://dev.pyvista.org/examples/00-load/linear-cells#plot-all-linear-cell-types
This example should probably be cross-ref'd in [pyvista.CellType](https://docs.pyvista.org/api/utilities/_autosummary/pyvista.celltype#pyvista-celltype).
