### ISSUE TITLE
`MultiBlock` self-mutates during iteration and breaks `zip`

### ISSUE THREAD

**Issue by user27182** [pyvista/pyvista#6600]
### Describe the bug, what's wrong, and what you expected.

`MulitBlock.__next__` stores an internal counter which self-mutates during iteration. This breaks things like `zip` when iterating over multiple copies of the same `MultiBlock` instance.

### Steps to reproduce the bug.

``` python
# Zip a MultiBlock with two blocks
import pyvista as pv
multi = pv.MultiBlock([pv.Sphere(), None])
multi2=multi
print(list(zip(multi, multi2)))

# Expected four items, but got two instead.
[(PolyData (0x130847ca0)
  N Cells:    1680
  N Points:   842
  N Strips:   0
  X Bounds:   -4.993e-01, 4.993e-01
  Y Bounds:   -4.965e-01, 4.965e-01
  Z Bounds:   -5.000e-01, 5.000e-01
  N Arrays:   1, None)]

# Compare with 4 items returned by `tuple` (as expected):
tup = (1,2)
tup2=tup
print(list(zip(tup, tup2)))
[(1, 1), (2, 2)]
```

### System Information

```shell
Dev branch
```

**Comment by user27182** [comment]
This might be a good test for this:
``` python
def test_multi_block_zip():
    # This tests `__iter__` and `__next__` internally
    list_ = [None, None]
    multi = MultiBlock(list_)
    zipped_multi = list(zip(multi,multi))
    zipped_list = list(zip(list_, list_))

    assert len(zipped_multi) == len(zipped_list)
    assert len(zipped_multi[0]) == len(zipped_list[0])
    for i in range(2):
        for j in range(2):
            assert zipped_multi[i][j] is zipped_list[i][j] is None
```

I played around a bit trying to fix this but it may require creating a separate class to encapsulate the iteration, so perhaps not a simple fix.

**Comment by banesullivan** [comment]
I'm pretty sure this is due to me being an amateur 6 years ago see 😄 https://github.com/pyvista/pyvista/commit/1349fc060bc51c5d2ae7e27cd8cb2490a5e3b050

I think a more robust implementation is needed here

**Comment by MatthewFlamm** [comment]
The implementation is easy after #3031.  Will make a PR for it.
