### ISSUE TITLE
align function does not return transformation matrix

### ISSUE THREAD

**Issue by NamTran838P** [pyvista/pyvista#6635]
### Describe the bug, what's wrong, and what you expected.

Hello, I am referring to https://docs.pyvista.org/api/core/_autosummary/pyvista.datasetfilters.align

The documentation says that the align function returns 2 things: aligned dataset and transformation matrix.

In reality, the align function returns only the aligned dataset. This is evidenced by the example on https://docs.pyvista.org/api/core/_autosummary/pyvista.datasetfilters.align

I have run the example to confirm that. I would like to get the transformation matrix as well. Please advise.

Thanks a lot,
Nam

### Steps to reproduce the bug.

Simply run the example on https://docs.pyvista.org/api/core/_autosummary/pyvista.datasetfilters.align#pyvista.DataSetFilters.align

```python
import pyvista as pv
import numpy as np
source = pv.Cylinder(resolution=30).triangulate().subdivide(1)
transformed = source.rotate_y(20).translate([-0.75, -0.5, 0.5])
aligned = transformed.align(source)
_, closest_points = aligned.find_closest_cell(
    source.points, return_closest_point=True
)
dist = np.linalg.norm(source.points - closest_points, axis=1)
```

### System Information

```shell
OS : Windows
            CPU(s) : 8
           Machine : AMD64
      Architecture : 64bit
               RAM : 15.6 GiB
       Environment : Python
        GPU Vendor : Intel
      GPU Renderer : Intel(R) Iris(R) Plus Graphics
       GPU Version : 4.5.0 - Build 27.20.100.9664
  MathText Support : False

  Python 3.9.4 (tags/v3.9.4:1f2e308, Apr  6 2021, 13:40:21) [MSC v.1928 64 bit
  (AMD64)]

           pyvista : 0.44.1
               vtk : 9.2.6
             numpy : 1.24.1
        matplotlib : 3.8.4
            scooby : 0.5.12
             pooch : v1.7.0
            pillow : Module not found
           imageio : 2.9.0
             PyQt5 : 5.15.6
           IPython : 8.4.0
        ipywidgets : 7.7.1
             scipy : 1.11.2
              tqdm : 4.64.1
            meshio : 5.3.5
        jupyterlab : 3.4.3
      nest_asyncio : Version unknown
```

**Comment by user27182** [comment]
> I would like to get the transformation matrix as well. Please advise.

Use `return_matrix=True` to return the transformation matrix as well as the aligned mesh.

**Comment by NamTran838P** [comment]
Got it. Thanks a lot!
