### ISSUE TITLE
Include mesh intersection in `voxelize_binary_mask`

### ISSUE THREAD

**Issue by GuillaumeBroggi** [pyvista/pyvista#6677]
### Describe the feature you would like to be added.

When using `voxelize_binary_mask` (added in #6611) on a mesh that contains two intersecting surfaces, the intersection is not included in the foreground.

```python
mesh = pv.Cylinder() + pv.Cylinder((0, 0.75, 0))
mesh.plot(jupyter_backend="notebook")

binary = mesh.voxelize_binary_mask().points_to_cells()
binary.plot(jupyter_backend="notebook")
```
![image](https://github.com/user-attachments/assets/fa171795-6a82-41e5-b0f5-a0b7a19af687)

![image](https://github.com/user-attachments/assets/6cdeb469-490d-41fa-9421-467d65fd9604)

**Comment by GuillaumeBroggi** [comment]
However, this behavior makes sense, for instance, for concentric tubes.

```python
mesh = pv.Tube(radius=2) + pv.Tube(radius=3) + pv.Tube(radius=4)
mesh.plot(jupyter_backend="notebook")

binary = mesh.voxelize_binary_mask(dimensions=(20, 20, 20)).points_to_cells()
binary.plot(jupyter_backend="notebook")
```
![image](https://github.com/user-attachments/assets/87d6bf28-4687-42be-9216-fe6d0cf50d08)
![image](https://github.com/user-attachments/assets/2e4cb944-b74f-4378-ad48-1b2e3809d23f)

**Comment by user27182** [comment]
Interesting cases! These examples might also be useful to include in the docs.

**Comment by GuillaumeBroggi** [comment]
I have included these examples in the docs: https://github.com/pyvista/pyvista/pull/6680

If the behaviour for internal surfaces is expected, then one could take the boolean union of the two surfaces to include the intersection.

Sadly, the boolean union output is ... unreliable. This might be related to #2788.

```python
cylinder_1 = pv.Cylinder().triangulate()
cylinder_2 = pv.Cylinder((0, 0.75, 0)).triangulate()
mesh = cylinder_1.boolean_union(cylinder_2).extract_surface()
mesh.plot(jupyter_backend="notebook")

binary = mesh.voxelize_binary_mask(dimensions=(2, 20, 10)).points_to_cells()
binary.plot(jupyter_backend="notebook")
```
![image](https://github.com/user-attachments/assets/ec9495e9-e74c-4fcd-bd86-2c0fbbe06bb1)
![image](https://github.com/user-attachments/assets/bc7f41f1-37ed-413a-8e76-d6e2dfcf6200)

It leaves us with the following options:
- we process the mesh without VTK (see the suggestions in #2788 for bool operations)
- we use a mesh without internal surfaces
- we apply `voxelize_binary_mask` sequentially

The latter is doable but assumes that intersecting parts of the mesh can be isolated and is not user-friendly.

```python
cylinder_1 = pv.Cylinder()
cylinder_2 = pv.Cylinder((0, 0.75, 0))

reference_volume = pv.ImageData(
    dimensions=(1, 100, 50),
    spacing=(1, 0.0175, 0.02),
    origin=(0, -0.5 + 0.0175 / 2, -0.5 + 0.02 / 2),
)

binary_mask_1 = cylinder_1.voxelize_binary_mask(
    reference_volume=reference_volume
).points_to_cells()
binary_mask_2 = cylinder_2.voxelize_binary_mask(
    reference_volume=reference_volume
).points_to_cells()

binary_mask_1["mask"] = binary_mask_1["mask"] | binary_mask_2["mask"]

plot = pv.Plotter()
_ = plot.add_mesh(binary_mask_1)
_ = plot.add_mesh(cylinder_1.slice(), color='red')
_ = plot.add_mesh(cylinder_2.slice(), color='red')
plot.show(jupyter_backend="notebook", cpos="yz")
```
![image](https://github.com/user-attachments/assets/e58b8ad0-2adb-4f82-a293-025b31ab924b)

Notice that intermediate results are created. The intermediate results could be eliminated if it was possible to not alter the background and/or foreground of the reference image. This could be implemented, for instance, by passing `None` to `background_value` and `foreground_value`, respectively.

**Comment by GuillaumeBroggi** [comment]
Examples added to the doc by #6680
