### ISSUE TITLE
A capability to add border to background of point label in add_point_labels

### ISSUE THREAD

**Issue by rajesh1359** [pyvista/pyvista#6681]
I am trying to create a report using pyvista where I need to create many labels and for better visibility and distinction between labels, I was looking for a capability to add border edge as well. If it is already possible, please let me know.

**Comment by user27182** [comment]
you can use `fill_shape=False` for a border effect. E.g. adding this keyword to the example in the docs for [add_point_labels](https://docs.pyvista.org/api/plotting/_autosummary/pyvista.plotter.add_point_labels#pyvista.Plotter.add_point_labels):
``` python
import numpy as np
import pyvista as pv
pl = pv.Plotter()
points = np.array(
    [[0.0, 0.0, 0.0], [1.0, 1.0, 0.0], [2.0, 0.0, 0.0]]
)
labels = ['Point A', 'Point B', 'Point C']
actor = pl.add_point_labels(
    points,
    labels,
    italic=True,
    font_size=20,
    point_color='red',
    point_size=20,
    render_points_as_spheres=True,
    always_visible=True,
    shadow=True,
    fill_shape=False,
)
pl.camera_position = 'xy'
pl.show()
```
<img width="624" alt="point_labels" src="https://github.com/user-attachments/assets/12415c0f-08ab-49b8-81e4-72efe5798ecf">

**Comment by rajesh1359** [comment]
@user27182 Thanks for your suggestion. I would like to have white background for each label so I was using fill_shape=True.

With fill_shape=False, it create boarder like effects but I look background color.

![image](https://github.com/user-attachments/assets/bacf15b8-3fce-4a39-b306-440f61af19f9)

**Comment by rajesh1359** [comment]
@user27182 I was using pyvista 0.43.4 which did not allow use of background_color, just upgraded to 0.44 and it works. as expected,.

![image](https://github.com/user-attachments/assets/de00ed92-634c-4af6-b1d0-99edfd78176f)
