### ISSUE TITLE
Plotter.export_html trame compatibility

### ISSUE THREAD

**Issue by zmladen** [pyvista/pyvista#6682]
### Describe the bug, what's wrong, and what you expected.

Hello,

when i try to run the example [https://docs.pyvista.org/api/plotting/_autosummary/pyvista.plotter.export_html](url) i get the error

> ImportError: Please install trame to export

I have installed the latest version of trame and trame-vtk.

pyvista: Version: 0.44.1
trame: Version: 3.6.5
trame-vtk: Version: 2.8.10.

Only after installing these versions the code is working:

pyvista==0.37.0 trame==2.5.2 trame-vtk==2.5.8.

Regards,
zmladen

### Steps to reproduce the bug.

```python
import pyvista as pv
from pyvista import examples
mesh = examples.load_uniform()
pl = pv.Plotter(shape=(1, 2))
_ = pl.add_mesh(
    mesh, scalars='Spatial Point Data', show_edges=True
)
pl.subplot(0, 1)
_ = pl.add_mesh(
    mesh, scalars='Spatial Cell Data', show_edges=True
)
pl.export_html('pv.html')  
```

### System Information

```shell
Windows 10


Name: pyvista
Version: 0.44.1
Summary: Easier Pythonic interface to VTK
Home-page:
Author:
Author-email: PyVista Developers <info@pyvista.org>
License: MIT
Location: C:\Work\Python\pyvista-example\venv\Lib\site-packages
Requires: matplotlib, numpy, pillow, pooch, scooby, typing-extensions, vtk
Required-by:
```

**Comment by banesullivan** [comment]
This is intended behavior. Trame is a required dependency for the export and the given error message is informative.

**Comment by zmladen** [comment]
Hello, thanks for the reply. I understand that Trame is also required. My question was why I cannot use the latest versions of pyvista to run the example. When I use the latest pyvista version and the latest trame version I get the mentioned error. Which trame version I should use with latest pyvista version?

**Comment by banesullivan** [comment]
Ooh I'm sorry, I think there's an issue here with the decencies or there's an additional one that needs to be installed which isn't in the error message. I'll make sure to look into to this

**Comment by zmladen** [comment]
Sounds great. Thank you!

**Comment by banesullivan** [comment]
`pip install 'pyvista[jupyter]'` should be all you need for this. I have clarified this error message in #6695

**Comment by nflores99** [comment]
Hi,

I had the same error described here and tried to install 'pyvista[jupyter]' from Anaconda running `conda install 'pyvista[jupyter]'` . The error keeps appearing even though all the packages needed seem to be installed. Should I run a different command to install the required packages with Anaconda?

Thanks in advance :)

**Comment by banesullivan** [comment]
You'll need to run `conda install -c conda-forge trame`

I don't think conda supports the extra dependency groups (e.g. `[jupyter]`) like pip does
