### ISSUE TITLE
Geometric objects: add scale argument to Arrow

### ISSUE THREAD

**Issue by tomsal** [pyvista/pyvista#670]
I think the geometric object `Arrow` is missing a simple way to scale it. After the transformation rescaling won't do the trick.
See here what I mean and how I would implement it:
https://github.com/tomsal/pyvista/commit/acc8b3b97b01e686e2a77e3547d8180103d64328

I think this is an intuitive way to solve this. I'd be happy to create a pull request, if you agree with the changes.

**Comment by banesullivan** [comment]
This is interesting... at first, I thought this isn't needed as the user can just scale the `.points` as needed after creating the arrow. However, I do like the "auto-scaling" feature you added.

Generally, I am a bit hesitant to add scaling arguments like that as it can become confusing when also using the radius arguments. Thoughts, @akaszynski? Also, would we want to do this for other geometric objects as well?

**Comment by tomsal** [comment]
After translating it to the start point, simply scaling it as in `arrow.points *= scale` won't work right? The it would not be at the start_point anymore. Thus, it is easier to it before translation.

**Comment by banesullivan** [comment]
Ahh, you're right. The translation/rotation that is performed prevents the scaling from working.

Feel free to make a PR! Though we may ask that this feature be implemented more widely across the geometric objects.

Also, I do not use those methods all too often so it would be nice to have some other folks chime in first

**Comment by tomsal** [comment]
After no other folks have chimed in, I created a PR.
