### ISSUE TITLE
pv.Disc is not creating a correct PolyData mesh when creating a solid disc

### ISSUE THREAD

**Issue by jpmorr** [pyvista/pyvista#6710]
### Describe the bug, what's wrong, and what you expected.

PyVista provides a `Disc` geometry to 

> "Create a polygonal disk with a hole in the center."

This has both an `inner` radius and `outer` radius which can be set to create an [annulus](https://en.wikipedia.org/wiki/Annulus_(mathematics)). When creating an annulus, all elements in the mesh will be quads, so you have a nice regular `PolyData` mesh.

If you actually try to make a disc (no hole in the middle) by setting the `inner` radius to zero, you should get a `PolyData` mesh that is made up of triangles and quads, such as the one in the image which looks correct.

However, if you query the created mesh, you will find that it is a regular mesh consisting of only quads, which is not correct. The generation seems to create the inner segments by duplicating the origin and assigning it different ids - there are therefore a significant number of points all overlapping at the origin and the number and type of cells is therefore wrong.

### Steps to reproduce the bug.

```python

  mesh = pv.Disc(center=(0,0,0), inner=0, outer=2,   c_res=24, r_res=4)

```

This should create a mesh that has 97 points, 72 quads and 24 triangular elements. 

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Thu Oct 17 20:12:47 2024 GMT Summer Time
                OS : Windows (10 10.0.22631 SP0 Multiprocessor Free)
            CPU(s) : 16
           Machine : AMD64
      Architecture : 64bit
               RAM : 31.8 GiB
       Environment : IPython
        GPU Vendor : NVIDIA Corporation
      GPU Renderer : Quadro RTX 5000/PCIe/SSE2
       GPU Version : 4.5.0 NVIDIA 552.86
  MathText Support : False
  Python 3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:27:10) [MSC
  v.1938 64 bit (AMD64)]
           pyvista : 0.44.1
               vtk : 9.3.1
             numpy : 2.0.1
        matplotlib : 3.9.1
            scooby : 0.10.0
             pooch : 1.8.2
            pillow : 10.4.0
           imageio : 2.34.2
         pyvistaqt : 0.11.1
             PyQt5 : 5.15.9
           IPython : 8.26.0
          colorcet : 3.1.0
        ipywidgets : 8.1.3
             scipy : 1.14.0
              tqdm : 4.66.5
            meshio : 5.3.5
        jupyterlab : 4.2.4
             trame : 3.6.3
      trame_client : 3.2.2
      trame_server : 3.0.3
      nest_asyncio : 1.6.0
--------------------------------------------------------------------------------
```

### Screenshots

![image](https://github.com/user-attachments/assets/b7298bba-274b-465f-ac0f-6c1900311e9c)

**Comment by jpmorr** [comment]
I believe this also affect the `pyvista.CylinderStructured` class when creating a solid 3D mesh for a cylinder:
```python
        radius = np.linspace(0, 0.5, 10)

        mesh = pv.CylinderStructured(center=(0,0,0), radius=radius, height=1, z_resolution=60,
                             theta_resolution=40,)
```

This will create what looks like a very nice structured cylinder mesh, but if you save to a `vts` file and import into ParaView you will find that the mesh contains only hexahedra which is also not correct because of the central wedges which should be `VTK_WEDGE` elements. I believe that a closed cylinder like this should only exist as a `PolyData` mesh and that the `StructuredGrid` is only suitable for rectangular toroids when all the elements can be `HEXAHEDRONS`.

**Comment by jpmorr** [comment]
@MatthewFlamm Thanks for the very useful answer! 

I assumed my use case was beyond the scope of what was being considered since the examples all showed a non-zero inner radius. Also first-time I've come across the term non-degenerate for a mesh - there always a proper term for things! I do use `pv.SolidSphere` a bit which is how I came across this discrepancy as I was expecting these meshes to also do the same.

I did not know about the `clean` method and that it would achieve what I was expecting for the circular disc. That has solved that problem - thank you! Side note: this might be a really useful little snippet to include in the documentation in the future!

Looking at the `clean` mesh, I have some further questions - since the mesh has mixed types I can see that `irregular_faces` is now a `tuple` of varying length lists of 3 and 4 as expected, but the `regular_faces` is now an `ndarray`  with dimensions of (n, 3) - I'm not sure I understand what the `regular_faces` represents now. Has it just chopped of the last column of the quads? Maybe this is a bug? Since it's no longer structured, should this be empty now?

I can definitely look at the `pv'CylinderStructured()` implementation and see if I can create a non-degenerate semi-structured mesh for the cylinder which would also be a `PolyData` mesh. Won't be straight away though.

**Comment by darikg** [comment]
> Looking at the `clean` mesh, I have some further questions - since the mesh has mixed types I can see that `irregular_faces` is now a `tuple` of varying length lists of 3 and 4 as expected, but the `regular_faces` is now an `ndarray` with dimensions of (n, 3) - I'm not sure I understand what the `regular_faces` represents now. Has it just chopped of the last column of the quads? Maybe this is a bug? Since it's no longer structured, should this be empty now?

The `regular_faces` documentation has this little warning note:

> This property does not validate that the mesh’s faces are all actually the same size. If they’re not, this property may either raise a ValueError or silently return an incorrect array.

**Comment by jpmorr** [comment]
@MatthewFlamm The points you raised about cleaning made me think last night and I thought I could put together a solution to this problem by just creating two separate grids, one of `WEDGES` for the core (`generate_inner_wedges()`) and the rectangular toroid using the existing code which returns a `StructuredGrid`.

```python
    # if inner radius is zero / less than sensible tolerance, we create
    if inner_radius < 1e-6:
        core_grid = generate_inner_wedges(centre=center, radius=radii[1], height=height,
                                          num_circum_cells=theta_resolution, num_vert_cells=z_resolution)

    # cast hollow cylinder to unstructured grid
    grid = grid.cast_to_unstructured_grid()

    # merge two grids and clean
    merged = grid.merge([core_grid])
    merged = merged.clean(remove_unused_points=True, tolerance=1e-12)
```

A quick check on the cell types in the new mesh to see if it has the two correct meshes:
```python
np.unique(merged.celltypes)
Out[9]: array([12, 13], dtype=uint8)
```

And with a reasonable tolerance set to remove duplicates, I also get the expected number of points in the mesh. I think this would work as a solution, even if it is a bit of a shortcut compared to creating the whole connectivity from scratch. Need to test it out properly to ensure it works

**Comment by MatthewFlamm** [comment]
Glad this worked.  You are probably about 75% of the way done making the whole thing without having to fiddle with tolerances.  Either way, if you can, please share the  your code for generating either the wedges or the whole mesh. This will help others who want to make a very specific kind of mesh in the future.
