### ISSUE TITLE
dev.pyvista.org is offline

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#674]
Just so we don't forget: the docs are deploying to dev.pyvista.org from every build on every branch. It should only be on `master` branch.

docs.pyvista.org is only deployed on releases

**Comment by akaszynski** [comment]
This doesn't seem to be occurring:

We for docs.pyansys.com we deploy only on tags (releases).
```
and(succeeded(), contains(variables['Build.SourceBranch'], 'refs/tags/'))
```

For dev.pyansys.com we have:
```
condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
```

Correct me if I'm wrong @banesullivan, but I think we can close this issue.

**Comment by banesullivan** [comment]
Code from:

https://github.com/pyvista/pyvista/blob/46dcf4ba474fb591dd9cc6976584b835740be367/azure-pipelines.yml#L413

Huh, that seems right to me. However it doesn't explain how https://github.com/pyvista/pyvista/pull/671#pullrequestreview-390402056 happened. 

Also... the site is down right now??? https://dev.pyvista.org

**Comment by banesullivan** [comment]
Okay, #691 showed all is good. However, the site is currently down. so I will repurpose this issue to that

**Comment by banesullivan** [comment]
@pyvista/developers, I cannot even build the documentation locally... what is going on? `make html` does not currently produce html output

**Comment by banesullivan** [comment]
The new `SPHINXOPTS` in #605 seems to be causing this. Cc @tkoyama010
