### ISSUE TITLE
Add Radio Button Widgets

### ISSUE THREAD

**Issue by nathmay** [pyvista/pyvista#6763]
### Describe the feature you would like to be added.

Pyvista currently has a checkbox button widget. I think it could be useful to add a **radio button** widget - where only one button in a group of buttons can be on.  Example use case: switching active scalar of a displayed mesh.

### Links to VTK Documentation, Examples, or Class Definitions.

I have a basic working version implemented in my forked repo [under feat/radio_button](https://github.com/nathmay/pyvista/blob/1f17c70fc4d0d5a0c25b4755a1364242c20737fc/pyvista/plotting/widgets.py#L2628). 

### Pseudocode or Screenshots

**Example application 1:** Switching background color
```python
import pyvista as pv

plotter = pv.Plotter()

def set_bg(color):
  def wrapped_callback():
    plotter.background_color = color
  return wrapped_callback

plotter.add_radio_button_widget(set_bg('white'), 'bgcolor', position=(10.0,200.0), value=True, title="White")
plotter.add_radio_button_widget(set_bg('lightblue'), 'bgcolor', position=(10.0,140.0), title="Light Blue")
plotter.add_radio_button_widget(set_bg('pink'), 'bgcolor', position=(10.0,80.0), title="Pink")
plotter.show()
```

**Example application 2:** Switching scalar of plotted mesh
```python
import pyvista as pv

sphere = pv.Sphere()
# Add example scalars for demonstration
sphere['X_Values'] = sphere.points[:,0]
sphere['Y_Values'] = sphere.points[:,1]
sphere['Z_Values'] = sphere.points[:,2]

plotter = pv.Plotter()
sphere.set_active_scalars('X_Values')
actor = plotter.add_mesh(sphere)

# Callback function for changing active scalar
def set_scalar(scalar):
  def wrapped_callback():
    global actor
    plotter.remove_actor(actor)
    sphere.set_active_scalars(scalar)
    actor = plotter.add_mesh(sphere)
  return wrapped_callback

# Add radio buttons
plotter.add_radio_button_widget(set_scalar('X_Values'), 'scalar', position=(10.0,200.0),
                                title="X Values", value=True)
plotter.add_radio_button_widget(set_scalar('Y_Values'), 'scalar', position=(10.0,140.0),
                                title="Y Values")
plotter.add_radio_button_widget(set_scalar('Z_Values'), 'scalar', position=(10.0,80.0),
                                title="Z Values")
plotter.show()
```
<img width="1036" alt="image" src="https://github.com/user-attachments/assets/99741363-e754-46e1-9579-a234dbfd45d9">

**Comment by tkoyama010** [comment]
> I have a basic working version implemented in my forked repo [under feat/radio_button](https://github.com/nathmay/pyvista/blob/1f17c70fc4d0d5a0c25b4755a1364242c20737fc/pyvista/plotting/widgets.py#L2628).

We always welcome your contributions! Would you like to create a pull request?
