### ISSUE TITLE
equality used to compare floating point numbers

### ISSUE THREAD

**Issue by drew-parsons** [pyvista/pyvista#6805]
### Describe the bug, what's wrong, and what you expected.

Orientation tests in plotting/test_axes_assembly.py use equality to test orientation at 
https://github.com/pyvista/pyvista/blob/3f0fad3f42d9b491679e6aa50e52d93c1a81c042/tests/plotting/test_axes_assembly.py#L298
likewise l.304.

The reference orientation is integer `(1,2,4)`, but the orientation property of axes_assembly is floating point. Comparison by equality `==` therefore inevitably fails.  For instance the 32-bit calculation on i386 fails the test. Test log at https://ci.debian.net/data/autopkgtest/testing/i386/p/python-pyvista/54415875/log.gz) 

Since the orientation property in general is floating point,  the test needs to be done with floating point comparison e.g. `np.allclose`.  The same likely applies to other tests throughout test_axes_assembly.py (and perhaps other test files), which also use `==` instead of floating point comparison.

### Steps to reproduce the bug.

```shell
pytest-3 -v tests/plotting/test_axes_assembly.py -k test_axes_assembly_orientation
```

### System Information

```shell
142s --------------------------------------------------------------------------------
142s   Date: Sun Nov 17 21:43:09 2024 UTC
142s 
142s                 OS : Linux
142s             CPU(s) : 2
142s            Machine : i686
142s       Architecture : 32bit
142s        Environment : Python
142s        GPU Details : error
142s   MathText Support : False
142s 
142s   Python 3.12.7 (main, Nov  8 2024, 17:55:36) [GCC 14.2.0]
142s 
142s            pyvista : 0.44.1
142s                vtk : 9.3.0
142s              numpy : 1.26.4
142s         matplotlib : 3.8.3
142s             scooby : 0.10.0
142s              pooch : 1.8.2
142s             pillow : 10.4.0
142s            imageio : 2.36.0
142s            IPython : 8.29.0
142s           colorcet : 3.1.0
142s              scipy : 1.13.1
142s               tqdm : 4.67.0
142s             meshio : 5.3.5
142s --------------------------------------------------------------------------------
```

### Screenshots

1852s ________________________ test_axes_assembly_orientation ________________________
1852s 
1852s axes_assembly = AxesAssembly (0xdee85ec8)
1852s   Shaft type:                 'cylinder'
1852s   Shaft radius:               0.025
1852s   Shaft length:...E-01, 1.007E+00
1852s   Y Bounds                    -1.217E-01, 1.006E+00
1852s   Z Bounds                    -1.366E-01, 1.004E+00
1852s 
1852s     def test_axes_assembly_orientation(axes_assembly):
1852s         assert axes_assembly.orientation == (0, 0, 0)
1852s         orientation = (1, 2, 4)
1852s         axes_assembly.orientation = orientation
1852s >       assert axes_assembly.orientation == orientation
1852s E       assert (0.9999999999999999, 1.9999999999999998, 4.0) == (1, 2, 4)
1852s E         
1852s E         At index 0 diff: 0.9999999999999999 != 1
1852s E         
1852s E         Full diff:
1852s E           (
1852s E         -     1,
1852s E         -     2,
1852s E         +     0.9999999999999999,
1852s E         +     1.9999999999999998,
1852s E         -     4,
1852s E         +     4.0,
1852s E         ?      ++
1852s E           )
1852s 
1852s tests/plotting/test_axes_assembly.py:293: AssertionError
1852s _____________________ test_axes_assembly_orientation_init ______________________
1852s 
1852s     def test_axes_assembly_orientation_init():
1852s         orientation = (1, 2, 4)
1852s         axes_assembly = pv.AxesAssembly(orientation=orientation)
1852s >       assert axes_assembly.orientation == orientation
1852s E       assert (0.9999999999999999, 1.9999999999999998, 4.0) == (1, 2, 4)
1852s E         
1852s E         At index 0 diff: 0.9999999999999999 != 1
1852s E         
1852s E         Full diff:
1852s E           (
1852s E         -     1,
1852s E         -     2,
1852s E         +     0.9999999999999999,
1852s E         +     1.9999999999999998,
1852s E         -     4,
1852s E         +     4.0,
1852s E         ?      ++
1852s E           )
1852s 
1852s tests/plotting/test_axes_assembly.py:299: AssertionError

**Comment by user27182** [comment]
Thanks for reporting!
