### ISSUE TITLE
vtkLabelPlacementMapp object has no attribute 'dataset'

### ISSUE THREAD

**Issue by rajesh1359** [pyvista/pyvista#6859]
### Describe the bug, what's wrong, and what you expected.

I found a bug while using PyMAPDL example!

It throws error saying,   

File "D:\Workshop\demo\pyvista_contri\pyvista\pyvista\plotting\plotter.py", line 7195, in meshes
    return [actor.mapper.dataset for actor in self.actors.values() if hasattr(actor, 'mapper')]
  File "D:\Workshop\demo\pyvista_contri\pyvista\pyvista\plotting\plotter.py", line 7195, in <listcomp>
    return [actor.mapper.dataset for actor in self.actors.values() if hasattr(actor, 'mapper')]
AttributeError: 'vtkmodules.vtkRenderingLabel.vtkLabelPlacementMapp' object has no attribute 'dataset'

### Steps to reproduce the bug.

I run this example and when it tries to plot lines, plotter throws this error.

https://mapdl.docs.pyansys.com/version/stable/examples/gallery_examples/00-mapdl-examples/2d_plate_with_a_hole.html#sphx-glr-examples-gallery-examples-00-mapdl-examples-2d-plate-with-a-hole-py

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Mon Nov 25 20:57:54 2024 India Standard Time

                OS : Windows (10 10.0.19045 SP0 Multiprocessor Free)
            CPU(s) : 12
           Machine : AMD64
      Architecture : 64bit
               RAM : 31.7 GiB
       Environment : Python
        GPU Vendor : Intel
      GPU Renderer : Intel(R) UHD Graphics
       GPU Version : 4.5.0 - Build 30.0.101.1404
  MathText Support : True

  Python 3.10.12 (remotes/origin/3b5d0b535dfa1177dc4fc3b6f40c990a1085eaab-
  dirty:3b5d0b53, Mar 25 2) [MSC v.1920 64 bit (AMD64)]

           pyvista : 0.45.dev0
               vtk : 9.4.0
             numpy : 2.1.3
        matplotlib : 3.9.2
            scooby : 0.10.0
             pooch : 1.8.2
            pillow : 11.0.0
           IPython : 8.29.0
        ipywidgets : 8.1.5
             scipy : 1.14.1
              tqdm : 4.67.1
        jupyterlab : 4.3.1
             trame : 3.7.0
      trame_client : 3.5.0
      trame_server : 3.2.3
         trame_vtk : 2.8.12
     trame_vuetify : 2.7.2
      nest_asyncio : 1.6.0
--------------------------------------------------------------------------------
```

**Comment by banesullivan** [comment]
I suspect this is a compatibility issue with VTK 9.4, ref #6731

**Comment by banesullivan** [comment]
For posterity, this is easily reproducible. `Plotter.meshes` breaks anytime after using `Plotter.add_point_labels`
