### ISSUE TITLE
Test collection fails due to non-unique names

### ISSUE THREAD

**Issue by beroda** [pyvista/pyvista#6867]
### Describe the bug, what's wrong, and what you expected.

After a fresh editable install of `pyvista[dev]` following the contributing guide, pytest complains to collect tests due to non-unique test module names.

![image](https://github.com/user-attachments/assets/79d3b9e9-73b4-4800-971e-168a1e1f0e06)

Tried to remove `__pycache__` and `.pyc` files as suggested without any success.
However, following pytest `guidelines` [here](https://docs.pytest.org/en/latest/explanation/goodpractices.html#choosing-an-import-mode), adding an `__init__.py` inside `tests/core` fixes the issue.

Apparently, switching pytest import mode to [`importlib`](https://docs.pytest.org/en/latest/explanation/pythonpath.html#import-modes) could also help. Might be overkill though.

### Steps to reproduce the bug.

```shell
pytest --collect-only
```

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Mon Nov 25 23:58:11 2024 CET

                OS : Linux (Ubuntu 20.04)
            CPU(s) : 8
           Machine : x86_64
      Architecture : 64bit
               RAM : 15.5 GiB
       Environment : Python
       File system : ext4
        GPU Vendor : Intel
      GPU Renderer : Mesa Intel(R) HD Graphics 630 (KBL GT2)
       GPU Version : 4.6 (Core Profile) Mesa 21.2.6
  MathText Support : True

  Python 3.11.7 (main, Feb 23 2024, 11:15:59) [GCC 8.4.0]

           pyvista : 0.45.dev0
               vtk : 9.3.1
             numpy : 1.26.4
        matplotlib : 3.9.2
            scooby : 0.10.0
             pooch : 1.8.2
            pillow : 11.0.0
           imageio : 2.36.0
           IPython : 8.29.0
          colorcet : 3.1.0
           cmocean : 4.0.3
        ipywidgets : 8.1.5
             scipy : 1.14.1
              tqdm : 4.66.6
            meshio : 5.3.5
        jupyterlab : 4.2.5
    pytest_pyvista : 0.1.8
             trame : 3.7.0
      trame_client : 3.5.0
      trame_server : 3.2.3
         trame_vtk : 2.8.11
     trame_vuetify : 2.7.1
      nest_asyncio : 1.6.0
--------------------------------------------------------------------------------
```

**Comment by beroda** [comment]
Confirmed that `--import-mode=importlib` is fixing the issue. I can open a PR if the bug is reproducible.

**Comment by user27182** [comment]
+1 for a fix, I also have this issue (running `pytest -k contour` as part of #6732)

**Comment by user27182** [comment]
Can also confirm that adding `__init__.py` to `tests/core` fixes this. But then it only runs the tests found in core. So it's necessary to also add `__init__.py` to `tests/plotting`. And now pytest properly picks up all tests in core _and_ plotting without issue.

**Comment by beroda** [comment]
> Can also confirm that adding `__init__.py` to `tests/core` fixes this. But then it only runs the tests found in core. So it's necessary to also add `__init__.py` to `tests/plotting`. And now pytest properly picks up all tests in core _and_ plotting without issue.

Weird, I am not seeing this behavior locally. Adding only one  `__init__.py` in either folder makes me discover the same amount of tests.
Did you also try with `--import-mode=importlib` ?

**Comment by user27182** [comment]
> Weird, I am not seeing this behavior locally. Adding only one `__init__.py` in either folder makes me discover the same amount of tests. 

I double checked and you're right, adding a single init in either folder works.

> Did you also try with `--import-mode=importlib` ?

Yes this also works.
