### ISSUE TITLE
Better error types

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#687]
We should overhaul all places and error is `raise`d in the API. `AssertionError`, `Exception`, and `RuntimeError` are overused (and inappropriately used):

- `AssertionError` is raised 47 times
- `Exception` is raised 49 times
- `RuntimeError` is raised 56 times

ref https://github.com/pyvista/pyvista/pull/685#pullrequestreview-393235207

**Comment by JevinJ** [comment]
Quick reference for when to use the common exceptions, which I think are conventional.

TypeError - When the value is of wrong type, or None if that's not expected.

ValueError - When the value is of the correct type, but wrong value.

AssertionError - Assert should really only be used in testing 99.9% of the time.

RuntimeError - Encountered an error which can not be recovered from.

IOError - Should be rarely used, maybe for a corrupt file.

FileNotFoundError - Self explanatory.

Exception - Almost never, should keep an eye out for this or bare except in try-excepts too.

**Comment by banesullivan** [comment]
Thanks for that list @JevinJ! It will be helpful to follow those guidelines when fixing this issue

**Comment by akaszynski** [comment]
@JevinJ please close this if you think we've solved this issue.

**Comment by JevinJ** [comment]
I forgot about AssertionError and RuntimeErrors, I'll close this and open a PR for the others.
