### ISSUE TITLE
Support for Nek5000 (.nek5000) files

### ISSUE THREAD

**Issue by mattfalcone1997** [pyvista/pyvista#6885]
### Describe the feature you would like to be added.

It would be very useful if pyvista could have the ability to read nek5000 files. The particular applications in mind are for post-processing Nek5000/ NekRS data.

### Links to VTK Documentation, Examples, or Class Definitions.

The documentation for the [vtkNek5000Reader](https://vtk.org/doc/nightly/html/classvtkNek5000Reader.html). I have also attached a basic implementation below. The resulting code should behave similarly to other time readers.

The Nek5000 Reader inherits from `BaseReader`, `TimeReader` and `PointCellDataSelection` classes. Nek5000 only produces point data. As a result, the `vtkNek5000Reader` class does not have methods for enabling cell arrays as far as I can tell. It therefore could be useful to disable the cell array routines inherited from `PointCellDataSelection` in the implementation. I should add the caveat that I am no expert in VTK, so there are almost certainly better ways to implement this.

```python
import vtk

from pyvista.core.utilities import (BaseReader, 
                                                    PointCellDataSelection,
                                                    TimeReader)

class Nek5000Reader(BaseReader, PointCellDataSelection, TimeReader):
    """
    Class for reading .nek5000 files produced by Nek5000 and NekRS
    """
    _vtk_module_name = "vtkIOParallel"
    _vtk_class_name = "vtkNek5000Reader"

    @property
    def number_time_points(self):  # noqa: D102
        """Return number of time points or iterations available to read.

        Returns
        -------
        int

        """ 
        return self.reader.GetNumberOfTimeSteps()
    
    @property
    def time_values(self):
        """All time or iteration values.

        Returns
        -------
        list[float]

        """
        key = vtk.vtkStreamingDemandDrivenPipeline.TIME_STEPS()
        vtkinfo = self.reader.GetExecutive().GetOutputInformation(0)
        return [vtkinfo.Get(key, i) for i in range(self.number_time_points)]

    def time_point_value(self, time_point):  # noqa: D102i
        """Value of time point or iteration by index.

        Parameters
        ----------
        time_point : int
            Time point index.

        Returns
        -------
        float

        """
        return self.time_values[time_point]

    @property
    def active_time_value(self):  # noqa: D102
        """Active time or iteration value.

        Returns
        -------
        float

        """
        return self.time_values[self._active_time_point]

    def set_active_time_value(self, time_value):  # noqa: D102
        """Set active time or iteration value.

        Parameters
        ----------
        time_value : float
            Time or iteration value to set as active.

        """
        try:
            index = self.time_values.index(time_value)
        except ValueError:
            raise ValueError(f"Time {time_value} not present") from None

        self.set_active_time_point(index)
    def set_active_time_point(self, time_point):  # noqa: D102
        """Set active time or iteration by index.

        Parameters
        ----------
        time_point : int
            Time or iteration point index for setting active time.

        """
        self._active_time_point = time_point
        self.reader.SetTimeStepRange(time_point,time_point)
        self.reader.Update()
```

### Pseudocode or Screenshots

```python
Insert code here
```
Or drag your screenshot here!

**Comment by MatthewFlamm** [comment]
If this particular reader cannot support cell data and it crashes due to missing vtk methods, we can override those methods in the pyvista Reader class and use `NotImplementedError` or something like this.  Not sure that is the best error type here though...  Please open PR as it seems like you are close enough to implementing.  We like to have a sample dataset for testing against.  It would go into https://github.com/pyvista/vtk-data.

**Comment by mattfalcone1997** [comment]
I have added Nek5000 test data to the vtk-data repository so that the unit tests for the Nek5000Reader can work
