### ISSUE TITLE
Always says "Please install trame to export" when export to html

### ISSUE THREAD

**Issue by Dan2712** [pyvista/pyvista#6997]
### Describe the bug, what's wrong, and what you expected.

I've already installed the trame and trame-vtk, and the version is:
trame == 3.7.1
trame == 2.8.12
but when I export the mesh to html file, it always report a error:
ImportError: Please install trame to export

For the error line is:
try:
    from pyvista.trame import PyVistaLocalView
    from pyvista.trame.jupyter import elegantly_launch
    from pyvista.trame.views import get_server
except ImportError:  # pragma: no cover
    raise ImportError('Please install trame to export')

It cannot find the class PyVistaLocalView, but I found it in the pyvista.trame.views file. 
Please help with this.

### Steps to reproduce the bug.

```python
Insert code here
```
plotter.export_html('pv.html')

### System Information

```shell
Traceback (most recent call last):
  File "/xxxx/xxxx/.venv/lib/python3.9/site-packages/pyvista/plotting/plotter.py", line 638, in export_html
    data = self.export_vtksz(filename=None)
  File "/xxxx/xxxx/.venv/lib/python3.9/site-packages/pyvista/plotting/plotter.py", line 681, in export_vtksz
    raise ImportError('Please install trame to export')
ImportError: Please install trame to export
```

### Screenshots

![image](https://github.com/user-attachments/assets/db528f90-3e9c-4e88-9385-9ea6f0eac9a7)

**Comment by user27182** [comment]
Might be similar to #6841

**Comment by Dan2712** [comment]
> Might be similar to #6841

Yes, it works 👍 waiting for merging to the release version
