### ISSUE TITLE
Need to set initial colormap in PlotterITK

### ISSUE THREAD

**Issue by leeping** [pyvista/pyvista#714]
**Describe the bug, what's wrong, and what you expect:** 

I would like to change the initial colormap when using PlotterITK in my Jupyter notebook.  

At the moment, all PlotterITK windows are created using the default viridis colormap, and it is possible to switch color maps using the GUI.  However, I would like to change the initial colormap that is used when the window is created.  This is because I am often re-creating the PlotterITK object with different meshes.

Admittedly, I'm not sure if my issue should be reported for this package, or for https://github.com/InsightSoftwareConsortium/itkwidgets .  If this report is misplaced, my apologies.

**To Reproduce**

The behavior can be reproduced by going to my "Binder" which contains a tool to plot the hydrogen atomic orbitals for students in my quantum mechanics course:

https://mybinder.org/v2/gh/leeping/hydrogen-orbitals/master

The isosurfaces are initially shown in yellow and dark purple (the extremes of the viridis colormap), and I would like to change it to red and blue (e.g. the coolwarm or jet colormap).  Although I can do this in the UI, I would like the "initial" colors to use a colormap of my choice, not just to save clicks, but also because I'm distributing this to my students and would like to change the initial colors when they use it.

1) There is no API to change the default colormap that I know about.

2) If I understand correctly, the following "custom" code should be able to create a PlotterITK window with a user-specified choice of color map, but the window that is created still uses the viridis colormap.

```
from itkwidgets import view, cm
view(geometries=pl._geometries,
     geometry_colors=pl._geometry_colors,
     geometry_opacities=pl._geometry_opacities,
     point_set_colors=pl._point_set_colors,
     point_sets=pl._point_sets,
     ui_collapsed=True,
     cmap=cm.jet, # Does nothing
     actors=pl._actors)
```

![Screenshot 2020-05-13 07 00 53](https://user-images.githubusercontent.com/1441560/81822111-8e102380-94e7-11ea-9d8d-d843b51a2888.png)

**System Information:**

The following information is for my local machine but the behavior also exists on Binder.

```
txt
# Paste system info here
--------------------------------------------------------------------------------
  Date: Wed May 13 07:02:20 2020 PDT

                OS : Darwin
            CPU(s) : 8
           Machine : x86_64
      Architecture : 64bit
               RAM : 16.0 GB
       Environment : Python
        GPU Vendor : ATI Technologies Inc.
      GPU Renderer : AMD Radeon R9 M370X OpenGL Engine
       GPU Version : 4.1 ATI-2.11.21

  Python 3.6.7 | packaged by conda-forge | (default, Feb 28 2019, 02:16:08)
  [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]

           pyvista : 0.24.2
               vtk : 8.2.0
             numpy : 1.17.3
           imageio : 2.8.0
           appdirs : 1.4.3
            scooby : 0.5.4
        matplotlib : 3.0.3
             PyQt5 : 5.6
           IPython : 7.9.0
          colorcet : 1.0.0
             scipy : 1.0.0
--------------------------------------------------------------------------------
```

Your help is greatly appreciated!

Sincerely,

Lee-Ping Wang

**Comment by akaszynski** [comment]
This is a known issue and setting an initial colormap isn't supported just yet by ITK I'll keep this issue open and we can work on it as soon as ITK has that capability.

**Comment by leeping** [comment]
Thanks, that's great to know! :)

**Comment by leeping** [comment]
Hello there,

I'm revisiting this issue as I'm teaching the same course material again. :)

Do you know whether setting an initial color map is supported by ITK at this time?  

Thanks,

- Lee-Ping

**Comment by banesullivan** [comment]
I believe this is tracked in https://github.com/InsightSoftwareConsortium/itkwidgets/issues/174.... so I don't think so

**Comment by banesullivan** [comment]
PlotterITK was deprecated and removed in #3737
