### ISSUE TITLE
Support for Format EnsightGold (.case)

### ISSUE THREAD

**Issue by LucaZampieri** [pyvista/pyvista#722]
[Here I assume ensightGold, but it probably be extended to other ensight formats]

Hi! I really love what you guys are doing with pyvista! Here I propose to add support for the ensight gold format that is widely used in CAE softwares. I would gladly submit a PR for this.

## What? 
Support for EnSightGold format. more infos about the ensight format [here](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=2ahUKEwjjkN7_gLbpAhUsxYUKHcWyAjAQFjAAegQIAxAB&url=http%3A%2F%2Fwww3.ensight.com%2FEnSight10_Docs%2FUserManual.pdf&usg=AOvVaw0WWEvL6XEvSKdnLjxWEu4O). If link is dead I referenced the ensight user manual which can be found by google search. 
Under section `EnSight Gold Casefile Format` there are specifications.

## Why?
This format is widely used by CAE softwares for the ouputs of simulations (usually meshes with scalars/vector fields). For example Ansys and STAR-CCM can export in this format and openfoam can export in .encase

## How?
In my case a working version can be achieved by:
1.-  adding  `".case": vtk.vtkGenericEnSightReader, ` to the list of supported readers, 
2.- adding ".case" as multiblock data
3.- under `composite.py`, if extesion is ".case", use ` vtk.vtkGenericEnSightReader` and set file name as `reader.SetCaseFileName(filename)`. (for read and save)

**Comment by akaszynski** [comment]
Hello,

I'd appreciate a PR with this new feature.  If possible, would it be possible to add a unit test for this as well?  I'd rather not include a sample file in the repo to avoid bloating, but you could load the sample file here and I can add it to our examples git repo for testing.

**Comment by LucaZampieri** [comment]
Cool, thanks!  
Of course for the unittest :) I haven't provided the file yet as the one I have is proprietary but as soon as I find a light one I will provide it here.

**Comment by LucaZampieri** [comment]
For the files I could not find any with an open license so I converted some of my openfoam result into Ensight with the `foamToEnsight` command.  Here is the zip, let me know it it would work as an example.

[EnSight.zip](https://github.com/pyvista/pyvista/files/4638840/EnSight.zip)

**Comment by LucaZampieri** [comment]
Converting the ensight gold to vtm can be done with the following function
```python 
import vtk
def vtk_convert_sample(fname, foutname, reader=vtk.vtkGenericEnSightReader(), writer=vtk.vtkXMLMultiBlockDataWriter()):
    reader.SetCaseFileName(fname)
    reader.Update()
    
    writer.SetFileName(foutname)
    writer.SetInputConnection(reader.GetOutputPort());
    writer.Update();
```

**Comment by LucaZampieri** [comment]
the PR is mostly ready. I will wait for a conclusion on the `.case` sample to be included in the example before doing the PR, to adapt the unittest. 

The provided sample does not slow down too much the unittests
```python
0.25s call     tests/test_composite.py::test_ensight_multi_block_io[vtmb-False]
0.22s call     tests/test_composite.py::test_ensight_multi_block_io[vtm-False]
0.07s call     tests/test_composite.py::test_ensight_multi_block_io[vtm-True]
0.05s call     tests/test_composite.py::test_multi_block_io[vtm-False]
0.05s setup    tests/test_composite.py::test_multi_block_io[vtm-True]
0.05s setup    tests/test_composite.py::test_ensight_multi_block_io[vtm-True]
0.05s setup    tests/test_composite.py::test_multi_block_io[vtmb-False]
0.05s setup    tests/test_composite.py::test_multi_block_list_index
0.05s setup    tests/test_composite.py::test_combine_filter
0.04s setup    tests/test_composite.py::test_multi_block_negative_index
0.04s setup    tests/test_composite.py::test_ensight_multi_block_io[vtm-False]
```

**Comment by akaszynski** [comment]
Tests look fast. Thanks for verifying that!  We’ve been better about speeding up testing, but we still have a ways to go.

**Comment by LucaZampieri** [comment]
Here I was just looking at the speed of `test_composite.py`, for all pyvista I get: 
```python
5.91s call     tests/test_plotting.py::test_closing_and_mem_cleanup
2.56s call     tests/test_plotting.py::test_volume_rendering
1.82s call     tests/test_plotting.py::test_plot_texture
1.66s call     tests/test_plotting.py::test_plot
1.59s call     tests/test_qt_plotting.py::test_background_plotting_orbit
1.22s call     tests/test_itk_plotting.py::test_itk_plotting
1.09s call     tests/test_plotting.py::test_multi_renderers
1.03s call     tests/test_qt_plotting.py::test_background_plotter_export_files[True]
1.01s call     tests/test_qt_plotting.py::test_background_plotting_add_callback
0.93s call     tests/test_qt_plotting.py::test_qt_interactor
0.90s call     tests/test_qt_plotting.py::test_background_plotting_close[False-q_key_press]
0.87s call     tests/test_qt_plotting.py::test_background_plotting_close[False-menu_exit]
0.86s call     tests/test_qt_plotting.py::test_background_plotting_close[False-del_finalizer]
0.84s call     tests/test_qt_plotting.py::test_background_plotting_close[False-plotter_close]
0.83s call     tests/test_qt_plotting.py::test_background_plotting_close[False-window_close]
0.83s call     tests/test_qt_plotting.py::test_background_plotter_export_files[False]
0.76s call     tests/test_examples.py::test_creatingagifmovie
0.75s call     tests/test_common.py::test_translate_should_match_vtk_transformation
0.74s call     tests/test_qt_plotting.py::test_background_plotting_toolbar
0.61s call     tests/test_qt_plotting.py::test_background_plotter_export_vtkjs[True]
0.59s call     tests/test_qt_plotting.py::test_background_plotting_menu_bar
0.59s call     tests/test_plotting.py::test_user_annotations_scalar_bar
0.58s call     tests/test_qt_plotting.py::test_background_plotting_close[True-q_key_press]
0.55s call     tests/test_qt_plotting.py::test_background_plotting_axes_scale[False]
0.53s call     tests/test_qt_plotting.py::test_background_plotter_export_vtkjs[False]
0.52s call     tests/test_export.py::test_export_texture
0.52s call     tests/test_qt_plotting.py::test_background_plotting_axes_scale[True]
0.51s call     tests/test_filters.py::test_select_enclosed_points
0.51s call     tests/test_qt_plotting.py::test_background_plotting_close[True-menu_exit]
0.49s call     tests/test_qt_plotting.py::test_background_plotting_close[True-window_close]
0.49s call     tests/test_plotting.py::test_plot_eye_dome_lighting
0.48s call     tests/test_qt_plotting.py::test_background_plotting_close[True-plotter_close]
0.48s call     tests/test_plotting.py::test_plot_compar_four
0.47s call     tests/test_plotting.py::test_plot_show_bounds_params[all-front]
```
As the worst in term of speed on my machine running ubuntu 18.04

**Comment by akaszynski** [comment]
Great!  Feel free to push the PR when you get a chance
