### ISSUE TITLE
Move classes to their own file.

### ISSUE THREAD

**Issue by JevinJ** [pyvista/pyvista#757]
It would be nice to factor out major classes to their own file so it's easier to find what you're looking for.

eg: common.py would become dataobject.py and dataset.py(Common should be renamed DataSet as well since that appears to be the vtk equivalent)

This can be done without overwriting history, but I'm unsure how difficult this would be to merge existing PRs. Thoughts @pyvista/developers?

**Comment by akaszynski** [comment]
I’m in agreement here.  Pythonically, one class to one file is standard, and we are moving in the direction of being more and more like VTK in terms of structure (which I see as a good thing).  

This will also help with huge file sizes, which really slows down code checking and navigation, especially for `plotting.py`.


This will have to happen slowly, and not before the next release.  How do you propose keeping the history when moving large blocks of code around?

**Comment by JevinJ** [comment]
From testing the flow is something like this:

1. Create branch A from main
2. Treat the file you're changing as the new file, remove everything you don't want and rename it.
3. Commit changes to A.
4. Repeat 1 - 3 for each new file you want to split out.
5. Merge A, B, ... into main.
 
The result is essentially just renaming the original file multiple times and cutting out what you don't want, renaming the file shouldn't remove history. It works in pycharm at least, I still have annotations for dataset.py and dataobject.py.

**Comment by banesullivan** [comment]
I'm in agreement here - please try your best to preserve history as much as possible. 

The only issue I can see in redoing this is that each file in `core` holds classes that share a common base class which is defined in that file.. should we move all of those abstract classes to a single file? or where should we keep classes like `Grid`, `PointGrid`, `PointSet`, etc. when multiple classes that will be in multiple files need to import them without cross imports

**Comment by banesullivan** [comment]
Also, if you don't want to do it, @JevinJ, I'd be happy to take this one on when I can

**Comment by akaszynski** [comment]
> The only issue I can see in redoing this is that each file in `core` holds classes that share a common base class which is defined in that file.. should we move all of those abstract classes to a single file? or where should we keep classes like `Grid`, `PointGrid`, `PointSet`, etc. when multiple classes that will be in multiple files need to import them without cross imports

Cross imports will be a challenge for sure, and I don't think putting all the abstract methods into one module will help with organization.  Here's a really good answer for dealing with circular imports, 
https://stackoverflow.com/a/37126790/3369879, but it looks like there won't be an easy solution for classes.

Perhaps if some classes are so tightly coupled, it might make sense just leaving them in the same file.

**Comment by banesullivan** [comment]
> Perhaps if some classes are so tightly coupled, it might make sense just leaving them in the same file.

I think the current structure makes sense in this way with related classes in the same file/module but I'm pretty sure I was the one that organized them this way and I tried to base the organization on the underlying VTK class hierarchy

**Comment by imsodin** [comment]
I don't see the problem with having the base classes in one common or separate files, then importing from that in the derived classes? If that becomes too many files and confusing (i.e. no longer clear what belongs to what), one could make subdirectories based on the related classes.

**Comment by JevinJ** [comment]
I've added #760 to showcase this, the method requires 2 commits for each split, one to isolate the class, and another that renames the file.

**Comment by banesullivan** [comment]
so far, I like #760. But what about also splitting the `filters.py` module? That has become quite a long file as well with 5 class definitions. Should each data class and it's respective filters class be in a single file? Leaving all the base data classes and `DataSetFilters` in a common module?

**Comment by JevinJ** [comment]
Could just move the resulting filters into a /filters/ folder. Or there could be folders at /core/ level which are similar to what we have now, eg /core/pointset/ would contain the classes that are in pointset.py.

**Comment by akaszynski** [comment]
> Could just move the resulting filters into a /filters/ folder

This is a good approach, just like how we have a plotting submodule.

**Comment by banesullivan** [comment]
I like it - it'll make each module of the software more intentional. Though, should we have `filters/` under `core/` (i.e. `core/filters/` finance the classes in `core` inherit the classes in `filters` to avoid importing from outside the module?

**Comment by JevinJ** [comment]
Probably, because it's only relevant at that level.
