### ISSUE TITLE
stop include docs/ in PyPI source upload

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#787]
We are including the `docs/` directory in the source upload to PyPI. These docs are sort of useless because we don't include the `conf.py` or anything to actually generate the documentation.

Just an observation... it adds only 850 KB so not a big deal and I doubt it has anything to do with the longer install times we were seeing on windows before uploading wheels

**Comment by banesullivan** [comment]
Actually it normally only includes 97KB but the last release had some of the `_build` files since it was a manual upload.

**Comment by banesullivan** [comment]
I'm seeing now that `docs/*.rst` is listed in the manifest so this was intentional at some point, but should we keep it? Or if we do keep it, should we make it so the user can actually run `make html` to generate the full docs?

**Comment by akaszynski** [comment]
> Actually it normally only adds 97KB but the last release had some of the `_build` files since it was a manual upload.

Sorry, that's my fault.  It's amazing how many things there are to mess up when doing things manually.

> I'm seeing now that `docs/*.rst` is listed in the manifest so this was intentional at some point, but should we keep it? Or if we do keep it, should we make it so the user can actually run `make html` to generate the full docs?

There's no reason to include it in my opinion.  Users should clone the repo if they want to build the docs; PyPi isn't designed for building software but for hosting built software.  Everything is setup on GitHub for building the documentation and we really don't need two methods for building it.
