### ISSUE TITLE
Need type checking for boolean operations

### ISSUE THREAD

**Issue by akaszynski** [pyvista/pyvista#789]
We need to include type checking for our boolean filters.  Currently, attempting a boolean operation between `PolyData` and an `UnstructuredGrid` yields the following (not so helpful) error:
```
AttributeError: 'UnstructuredGrid' object has no attribute 'is_all_triangles'
```
See https://github.com/pyvista/pyvista-support/issues/176 for more details.

**Comment by banesullivan** [comment]
Agreed, we need type checking for those filters and any other filters that accept another mesh.

Also, we might want to add `is_all_triangles` to `UnstructuredGrid`s as well as that might be useful

**Comment by banesullivan** [comment]
Also.... why did github-actions post here.... it is supposed to only do that on a user's first issue in the repo

**Comment by akaszynski** [comment]
> Also, we might want to add `is_all_triangles` to `UnstructuredGrid`s as well as that might be useful

We could add this, but I don't feel it's all that applicable considering that unstructured grids are generally not used for triangular meshes.

> Also.... why did github-actions post here.... it is supposed to only do that on a user's first issue in the repo

Going to make another issue to see if this persists.

**Comment by akaszynski** [comment]
Issue didn't pop up.  It might have been a while since I posted an issue here...

**Comment by banesullivan** [comment]
> We could add this, but I don't feel it's all that applicable considering that unstructured grids are generally not used for triangular meshes.

Actaully that's fair. Let's not add that method as it could be misleading
