### ISSUE TITLE
GitHub Actions fail for new user PRs

### ISSUE THREAD

**Issue by akaszynski** [pyvista/pyvista#790]
**Describe the bug, what's wrong, and what you expect:**
See #789

**Comment by banesullivan** [comment]
I'm going to reopen this because the action is actually failing for new PRs

**Comment by banesullivan** [comment]
I think it has something to do with the formatting of the YAML file under `.github`

**Comment by akaszynski** [comment]
Editor within GitHub is great.  I use that since I don't know of an IDE that can dynamically check GitHub yml files.
