### ISSUE TITLE
Closed Surface Clipping

### ISSUE THREAD

**Issue by yetisir** [pyvista/pyvista#794]
Apologies if this has been implemented/discussed before - I couldn't find anything related in my search.

The current implementation of the PolyData clipping filter uses the vtkClipPolyData class which leaves the clipped edge open. This is nice because it is simple and flexible wrt to handling complex clip arguments. However, this can be annoying to deal with when manipulating manifold surface meshes for computational analyses, among other use cases.

In the case that we are using a plane to clip a watertight (or sufficiently close) PolyData, there is a vtkClipClosedSurface class that will close the surface for us. 

https://vtk.org/doc/nightly/html/classvtkClipClosedSurface.html

I have used this feature in the past without many issues. Let me know if this is of interest and/or any corresponding thoughts on the issue . I am happy to put in the leg work to draft a PR if no one has done it already.

**Comment by akaszynski** [comment]
Hello,

AFAIK, we have not implemented `vtkClipClosedSurface` in `pyvista`.  Also, a quick rgrep of the source showed that it doesn't occur in `pyvista`.  If you'd like, feel free to to draft a PR and I'll be sure to take a look at it.

**Comment by banesullivan** [comment]
I implemented this in #797 with single planes. If you're up for adding a user-friendly interface for defining plane collections we'd gladly add that in!

**Comment by FCalderon3006** [comment]
Hello guys, I have a problem with calculate a volume between surface in stl format of a mine pit, and a plane in constant height, for example polygon with boundary of the surface and z = 4500, any idea to solve ? I tried with cliped_box but don´t result.
