### ISSUE TITLE
Camera is resetting in add_point_labels

### ISSUE THREAD

**Issue by rodrigomologni** [pyvista/pyvista#804]
`add_point_labels` is resetting the camera. I fixed the bug including `reset_camera=False` in `self.add_mesh`, at line 3106 of `plotting.py`.

**Comment by banesullivan** [comment]
@rodrigomologni, thanks for point this out - good find!

**Comment by banesullivan** [comment]
We do want the camera to reset by default, so I will add `reset_camera=None` to `add_point_labels` arguments which we'll pass to that `add_mesh` call. If you don't want it to reset, then as a user you'll need to pass `reset_camera=False`.

See #805

**Comment by rodrigomologni** [comment]
@banesullivan I who thank you! :-)
