### ISSUE TITLE
version on master out of sync with release

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#814]
master is at 0.25.2 and the release branch is at 0.25.3

**Comment by akaszynski** [comment]
I don't think it's critical to have master and the latest release branch with the same version.  In fact, we might consider having an entirely separate version on the master branch (i.e. bump it to `0.26.0b`).  That way it's clear that there are new features on the master branch, but it's also a beta release.

**Comment by banesullivan** [comment]
I like that idea
