### ISSUE TITLE
Greek alphabet support in labels

### ISSUE THREAD

**Issue by Hypothesis-Z** [pyvista/pyvista#822]
I am working with the 3d plot of a surface, but the Greek alphabet doesnot display when I run the following code. 

```python
import pyvista as pv
plotter = pv.Plotter()
plotter.add_mesh(structed_grid)
plotter.show_bounds(xlabel='X/μm', ylabel='Y/μm', zlabel='Z/μm')
plotter.show()
```

By the way, it's better if latex is supported.

**Comment by banesullivan** [comment]
This is a duplicate of https://github.com/pyvista/pyvista/issues/83

Basically, all we need is https://github.com/conda-forge/vtk-feedstock/issues/79

or for you to build VTK locally with math-tex

**Comment by tkoyama010** [comment]
> Basically, all we need is conda-forge/vtk-feedstock#79

I close this issue.
