### ISSUE TITLE
QtDeprecationError is unclear

### ISSUE THREAD

**Issue by RobertKoenig1337** [pyvista/pyvista#826]
Hello all, 

I am working on a simulation of a machining process. Therefore I need to update the visualization permanently while the simulation is running. I want to use pyvista with the BackgroundPlotter for this task. I set up the library in my Anaconda Python 3 with PyCharm. I installed the pyvista package, numpy and pyvistaqt (and a few others). When I am trying to process the example given by PyVista for BackgroundPlotting I run into an error. (https://docs.pyvista.org/plotting/plotting.html#background-plotting)
I just started programming recently sorry if the reason is an obvious mistake. 

```py
Traceback (most recent call last):
  File "C:/Abtragsimulation/Programm with Conda/test files/testing pv.py", line 14, in <module>
    plotter = pv.BackgroundPlotter()
  File "C:\Users\Robert\miniconda3\envs\Programm with Conda\lib\site-packages\pyvista\plotting\__init__.py", line 35, in __init__
    raise QtDeprecationError('BackgroundPlotter')
pyvista.plotting.QtDeprecationError: `BackgroundPlotter` has moved to pyvistaqt.
    You can install this from PyPI with: `pip install pyvistaqt`
    See https://github.com/pyvista/pyvistaqt
```

When I try installing pyvistaqt as the error suggests, the terminal prompts a list with all packages needed and says that the requirements are all already satisfied. 
[Requirements already satisfied.txt](https://github.com/pyvista/pyvistaqt/files/4903247/Requirements.already.satisfied.txt)

How can I fix the problem? Is this even the right way to visualize a model that is changing all the time while the simulation is running? 

Python CODE: 
[Backgroundplotter error.txt](https://github.com/pyvista/pyvistaqt/files/4903223/Backgroundplotter.error.txt)

Thank you very much in advance.

**Comment by RobertKoenig1337** [comment]
Thank you very much for your help. 
I think the new way you proposed makes it much clearer, at least to me.
For me, as a beginner, it would be great if you adapt the example on your website (https://docs.pyvista.org/plotting/plotting.html#background-plotting). 

Thank you very much. 
BR

**Comment by banesullivan** [comment]
Keeping this open so that we actually implement this new message.
