### ISSUE TITLE
Method to add tensor data?

### ISSUE THREAD

**Issue by jrwrigh** [pyvista/pyvista#827]
I know that adding a scalar or vector to a data set is simply:
``` py
grid['data_name'] = data_nparray
```
where `data_nparray` is Nx1 for a scalar and Nx3 for a vector.

But I'm not sure how to go about adding tensor data. Is that a supported feature? If so, what order should the data be in?

Note: In response the bot, I'll add that I submitted this as an issue since either A) the feature doesn't exist or B) the feature isn't' documented. That said, the scalar and vector operations I reference above don't seem to be documented anywhere either.

**Comment by banesullivan** [comment]
You're right that tensor data aren't well supported/documented in PyVista 

VTK (the underlying library to PyVista) supports Tensor data as 9 component arrays. I've been meaning for a long time to put together an example of how to use tensors with PyVista. 

In the time being, this example dataset from our `examples` module does have tensors:

```py
from pyvista import examples
tmesh = examples.download_tensors()
tensors = tmesh['tensors1'].reshape((-1, 3, 3))
tensors
```

Then you can plot them via this (just what I thought to do, not a standard thing)
```py
nodes = np.repeat(tmesh.points, 3, axis=0)
vecs = tensors.reshape((-1, 3))

vecs /= np.linalg.norm(vecs, axis=1)[:, None]
vecs[np.isnan(vecs)] = 0.0

p = pv.Plotter()
p.add_mesh(tmesh, opacity=0.75)
p.add_arrows(nodes, vecs, mag=0.5, color=True)
p.show()
```

![download](https://user-images.githubusercontent.com/22067021/87192455-7cb77d80-c2c4-11ea-9674-04f6f6a044ee.png)

**Comment by banesullivan** [comment]
So effectively, just ravel your tensors from `(3, 3)` to `(9,)`

**Comment by jrwrigh** [comment]
Sweet. Yep that worked. Also, VTK supports symmetric tensors as well, so you only have to give it 6 of the components. Ordering for that is XX, YY, ZZ, XY, YZ, XZ as [denoted here.](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/1837)

**Comment by banesullivan** [comment]
Thanks for the link!

I am going to move this to the support repo for archiving there
