### ISSUE TITLE
Feature request (willing to implement): compute vorticity, divergence, etc.

### ISSUE THREAD

**Issue by jrwrigh** [pyvista/pyvista#831]
**Feature:**

As apart of `vtkGradientFilter`, there are options to compute vorticity, divergence, and QCriterion (a vortex visualization quantity). Currently in the `compute_gradient` method, there is not option to activate these options. I'd propose two different solutions (that could possibly both be done):

### Option 1
A single `compute_derivative` method that effectively wraps `vtkGradientFilter`. It would have options for all four quantities that could be calculated. Using the similar syntax to the original `compute_gradient` method: https://github.com/pyvista/pyvista/blob/24d572e5b64756e14fa632ed59e982cfd9acebe1/pyvista/core/filters.py#L2172-L2173 
I'd propose something like this:

```py
def compute_gradient(dataset, scalars=None, gradient=None, vorticity=None,
                     qcriterion=None, divergence=None, preference='point'):
```
The options (`gradient`, `vorticity`, `qcriterion`, or `divergence`) could either be `True` and they would be calculated with some default name set for them or be set to a string that would be used as the output array name. 

### Option 2
Have all the quantities (gradient, vorticity, divergence, and QCriterion) have their own separate function, analagous to the current implementation of `compute_gradient`.  Even if this was chosen, I think it would be worthwhile to have an overall function as I would assume that the `vtkGradientFilter` reuses data when calculating the above quantities (*Edit: [It does]( https://gitlab.kitware.com/vtk/vtk/blob/master/Filters/General/vtkGradientFilter.cxx#L61-85)*) and would thus be more efficient by calling `vtkGradientFilter` once rather than multiple times.

Let me know what y'all's thoughts are on this.

**Comment by jrwrigh** [comment]
Note that I'm also currently having some issues with `compute_gradient`, so it might be worth waiting for that to be resolved before moving forward with this.

**Comment by banesullivan** [comment]
I'm all for this!!! It would be totally awesome if you could draft this PR and make your first feature PR to PyVsita. I'd be happy to guide/review your work in the process.

I like option 1 a bit more. I'd like the filter we make to be as close to ParaView's gradient filter as possible in terms of usage. So it'd be great to keep the name `compute_gradient` and change the arguments to match ParaView's options:

<img width="494" alt="Screen Shot 2020-07-13 at 8 55 15 AM" src="https://user-images.githubusercontent.com/22067021/87306847-a0f2a480-c4e6-11ea-97b1-8effee68e2d0.png">

If there is a depreciation in the arguments, we'll just throw a warning/error about it

**Comment by banesullivan** [comment]
I like the name`compute_derivative` too. That might be better.

Perhaps we should create this new `compute_derivative` method with all these options and have `compute_gradient` wrap that method with a deprecation warning like we've done for the `wireframe` filter
