### ISSUE TITLE
Feature: Support pathlib objects

### ISSUE THREAD

**Issue by jrwrigh** [pyvista/pyvista#833]
**Describe the bug, what's wrong, and what you expect:**

Python's standard library has a [`pathlib`](https://docs.python.org/3/library/pathlib.html#pathlib.Path) module that acts as a OS agnostic method of manipulating paths. I quite like it and many libraries support it as a replacement input for strings when file paths are requested. At least `pyvista.UnstructuredGrid()` does not support pathlib objects, though I'd imagine even more do. 

To add flexibility (and increase the "pythonic"ness of the library), it might be worth also adding support for other python file-type objects. See code in [`numpy.loadfile`](https://github.com/numpy/numpy/blob/dd883ce53d0744c616de472215287d680c660ac5/numpy/core/records.py#L914-L919) and it's supporting function [`isfileobj`](https://github.com/numpy/numpy/blob/dd883ce53d0744c616de472215287d680c660ac5/numpy/compat/py3k.py#L53-L54). 

I'd imagine this would need to be implemented in [`_load_file`](https://github.com/pyvista/pyvista/blob/3be2baeb4f45cd566b0796974fde5937157a0261/pyvista/core/common.py#L49).

-----

**To Reproduce**

```py
import pyvista as pv
from pathlib import Path
vtuFilePath = Path(r'./test.vtu')
pv.UnstructuredGrid(vtuFilePath)
 # Errors with 'TypeError: Cannot work with input type <class 'pathlib.PosixPath'>'
```

**Comment by akaszynski** [comment]
I agree that this would be great to support, and it would even simply our tests as we often have to convert between `pathlib` instances to strings to get our paths to work.

We'd have to implement this is many places in `pyvista`.  Would you mind submitting a PR for this?  You can start with the `UnstructuredGrid` class and perhaps move on to other classes/functions if you feel comfortable with it.

**Comment by jrwrigh** [comment]
Sure, I can work on it. Just to outline before I start writing code:

1) Make `pyvista.UnstrucutredGrid()` accept pathlib objects to pass to `_load_file`
2) Change `_load_file` to recognize and use pathlib objects

Do we also want to throw in the general file objects akin to numpy, or just stick with pathlib objects for right now?

**Comment by banesullivan** [comment]
With this, we should just do a bit of refactoring to have the `fileio` module in `utilities` handle all file IO overhead like this.

**Comment by banesullivan** [comment]
> Do we also want to throw in the general file objects akin to numpy, or just stick with pathlib objects for right now?

I don't think we can do this as we have to pass a string filename/path to the VTK readers/writers. The meshio file stuff could probably support that though

**Comment by banesullivan** [comment]
@jrwrigh, It may be a bit confusing for you to try to do this as our file io stuff is a bit fragmented/all over the place. It may make sense for one of the core devs to handle this and do a better job of centralizing our IO routines so that we can have one place where we handle pathlib objects rather than adding support for them all over the place in each methods `_from_file`

**Comment by akaszynski** [comment]
@banesullivan, this doesn't sound too bad to implement.

**Comment by banesullivan** [comment]
I think you or I can tackle it pretty easily, but it may be pretty confusing for a first-timer to PyVista. I may do some OS coding tonight... let me know if you don't have time

**Comment by akaszynski** [comment]
Will do.  Tough to find time to code OS these days...

**Comment by jrwrigh** [comment]
Sounds fine to me. 

I started looking at the fileio stuff and noticed this though:
https://github.com/pyvista/pyvista/blob/6639b6567a6165356d132f75b9056d099dc1c081/pyvista/utilities/fileio.py#L60

If y'all are interested in supporting PHASTA files, I could possibly help with that. My research group develops PHASTA, so I'm sure I'd probably like the support eventually if it isn't already there.

**Comment by banesullivan** [comment]
Oh yeah, I think the only reason we didn't implement it was because we didn't have example data. Could you open a new issue for supporting this format and link a sample file?
