### ISSUE TITLE
Feature: Support PHASTA files

### ISSUE THREAD

**Issue by jrwrigh** [pyvista/pyvista#834]
Support for PHASTA files as mentioned in this comment:

https://github.com/pyvista/pyvista/blob/6639b6567a6165356d132f75b9056d099dc1c081/pyvista/utilities/fileio.py#L60

Let me see if I can find a reasonably sized example data set.

**Comment by banesullivan** [comment]
Actually, I don't think we can support this. the reader isn't built with VTK by default. I can only find it in ParaView: https://kitware.github.io/paraview-docs/latest/cxx/classvtkPPhastaReader.html

@jrwrigh, if you're hoping to add PHASTA support to PyVista, it may be better to go through [meshio](https://github.com/nschloe/meshio)

**Comment by jrwrigh** [comment]
Huh. Yeah, you're completely right. Guess I didn't think they'd name a Paraview-only object with the `vtk` prefix.
