### ISSUE TITLE
Add new Renderer.zoom method

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#863]
Here is a method that can be used to zoom a plotter. We should add this to the `Renderer`, wrap it in `BasePlotter`, then fix the up/down key callbacks to use this as they are currently not triggering a render call (bug)

```py
import pyvista as pv

def zoom(plotter, value):
    if not plotter.camera_set:
        plotter.camera_position = plotter.get_default_cam_pos()
        plotter.reset_camera()
        plotter.camera_set = True
    plotter.camera.Zoom(value)
    plotter.render()
    
# Monkey patch it
pv.Plotter.zoom = zoom
```

And here is an exampple of it in use:
```py
from pyvista import examples

mesh = examples.load_airplane()

p = pv.Plotter()
p.add_mesh(mesh)
p.zoom(5)
p.show()
```

![download](https://user-images.githubusercontent.com/22067021/90025141-f7343e00-dc72-11ea-800e-3cb658a9d9d6.png)

**Comment by banesullivan** [comment]
Note that this is a true zoom and not a camera movement

**Comment by banesullivan** [comment]
We should also think about adding more camera movement methods like `dolly`, `pan`, etc. to make programatic moving of the camera better

**Comment by GuillaumeFavelier** [comment]
Do you think it's a good candidate for `low-hanging-fruit`?

**Comment by GuillaumeFavelier** [comment]
(or `hacktoberfest`)

**Comment by akaszynski** [comment]
I think the camera is indeed difficult to handle and adding methods like `zoom` would be really helpful.

We might consider creating a `pyvista.Camera` class and wrap the existing class instead of adding a ton of methods to the `BasePlotter`.  We're already sitting at or over 4k LOC, and we have a ton of methods for the plotter.  If we nested some of the methods, we might be able to clean up the plotter a bit:  For example:

```py
from pyvista import examples

mesh = examples.load_airplane()

p = pv.Plotter()
p.add_mesh(mesh)
p.camera.zoom(5)
p.camera.up(10)
p.show()
```
We could add a `__repr__` (or `__str__`) for the camera and add some setters/getters as well, like position:
```py
p.camera.position = [[1, 0, 0], [1, 0, 0], [0, 0, 0]]
```

Having something like this makes it much easier to browse through methods since you don't have to look through 100s of methods to find one, and it will make for some very self-documenting code.

**Comment by banesullivan** [comment]
I like this idea of migrating the camera methods to a camera wrapper class. Hopefully someone can take this on for Hacktoberfest?!

**Comment by tkoyama010** [comment]
> I think the camera is indeed difficult to handle and adding methods like zoom would be really helpful.

I tried to add Camera object in #945 . But I have a problem. Could you give me a opinion?

https://github.com/pyvista/pyvista/blob/726fe0c656c1058067e36d2a2a53f3d0f5ac1d02/pyvista/plotting/plotting.py#L625-L628

When setting camera we use `vtkCamera` object. So I wrapped the `vtkCamera` object by Camera object and set it.

https://github.com/pyvista/pyvista/blob/726fe0c656c1058067e36d2a2a53f3d0f5ac1d02/pyvista/plotting/plotting.py#L620-L623

But when I get it, it became `vtkOpenGLCamera`. So I added monkey by patch to `vtkOpenGLCamera` in #945 . Do you have a good idea to wrap `vtkOpenGLCamera`?

![object 2020-10-11 14-43-58](https://user-images.githubusercontent.com/7513610/95671314-5f9a8f80-0bd0-11eb-8d9c-6c2a89369fdb.png)

**Comment by tkoyama010** [comment]
Maybe I should check this.
https://docs.enthought.com/mayavi/mayavi/mlab.html#moving-the-camera

**Comment by akaszynski** [comment]
In an effort to get 0.27.0 out, I'm moving this out of the milestone and voting that we make a `pyvista.Camera` class.
