### ISSUE TITLE
How to plot colorful point cloud

### ISSUE THREAD

**Issue by EthanZhangYi** [pyvista/pyvista#880]
I want to plot a point cloud with colors for each points, and save it as an image from a specific view. Like the image below.
How to do it? Can anyone give some help?
![Selection_001](https://user-images.githubusercontent.com/13479831/91930118-9b5d5200-ed12-11ea-8529-04c4db2685da.png)

**Comment by akaszynski** [comment]
Hello,

I'd take a look at the docs for creating and working with meshes:
https://docs.pyvista.org/examples/00-load/create-point-cloud.html#sphx-glr-examples-00-load-create-point-cloud-py

Additionally, you can color points by specifying values for each point.  For example:

```py
import numpy as np
import pyvista as pv

cloud = pv.PolyData(np.random.random((400, 3)))
cloud['point_color'] = cloud.points[:, 2]  # just use z coordinate

pv.plot(cloud, scalars='point_color', cmap='jet', show_bounds=True, cpos='yz')
```

![image](https://user-images.githubusercontent.com/11981631/92062876-f2851600-ed56-11ea-822b-a55ca4e5d7dc.png)
