### ISSUE TITLE
EDL forces background to be black

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#892]
I'm not sure what caused this but the background is now forced to be black when enabling eye dome lighting. See docs that were just updated from the release: https://docs.pyvista.org/examples/02-plot/edl.html

I believe a fairly recent change did this as I would have noticed it sooner i think

**Comment by banesullivan** [comment]
This appears to be broken again, look at the example on the documentation built from `master` on `dev.pyvista.org`: https://dev.pyvista.org/examples/02-plot/edl.html#sphx-glr-examples-02-plot-edl-py

**Comment by banesullivan** [comment]
It's good on the last release though: https://docs.pyvista.org/examples/02-plot/edl.html

**Comment by banesullivan** [comment]
Though locally, `master` works fine for me:

```py
>>> import pyvista as pv
>>> pv.Sphere().plot(edl=True)
```
<img width="624" alt="Screen Shot 2020-10-07 at 7 03 52 PM" src="https://user-images.githubusercontent.com/22067021/95403583-ddf4ea00-08cf-11eb-83f7-5872db374469.png">

**Comment by banesullivan** [comment]
The release docs are no longer relevant because I manually updated the published docs recently

**Comment by akaszynski** [comment]
I see that.  We're going to have to patch this for the next release.  Adding this to the release milestone.

**Comment by akaszynski** [comment]
Current dev docs indicate this problem has been solved:
https://dev.pyvista.org/examples/02-plot/edl.html#sphx-glr-examples-02-plot-edl-py

Having rolling dev-docs is the best.

**Comment by banesullivan** [comment]
Yeah, I noticed it was fixed today... puzzles me what changed
