### ISSUE TITLE
Get corresponding nodes/vertices  with respect to faces

### ISSUE THREAD

**Issue by ghazalbangash** [pyvista/pyvista#898]
mesh.faces gives us the faces of the mesh in this format : array([   3,    0,    1, 5,3,6,3,2.....])
is there any way i could get the face connectivity in this format : [([x1,y1,z1],[x2,y2,z2],[x3,y3,z3])  , ([x1,y1,z1],[x2,y2,z2],[x3,y3,z3])......]
where i get the the 3 points that are connected to make a face
i have written a work around code but its tooo time consuming.
thank you

**Comment by akaszynski** [comment]
If your mesh is composed of all triangles you can reshape your faces array and just get the connectivity with:
```py
conn = mesh.faces.reshape(-1, 4)[:, 1:]
points_per_face = mesh.points[conn]
```

If it's not triangular, you'll have to loop it.  Try converting to all triangles with `triangulate`

**Comment by ghazalbangash** [comment]
thank you soooooooooooo much triangulate solved my problem
