### ISSUE TITLE
[Support] Storing Polygon Meshes to VTK

### ISSUE THREAD

**Issue by captain-pool** [pyvista/pyvista#903]
Hey Guys,
I'm trying to save a Polygon Mesh to VTK using PyVista, but I couldn't find something that can help me with it.
In my case, I'm having a numpy array of (N, 3) points, and a Jagged List of connected vertices. For example,
the vertex set looks like:
```
array([[0, 0, 0],
       [1, 0, 1.5],
       [1, 0.4, 0.1],
       [0.8, 0.5, 0.12]
       [0.1, 0.2, 0.3]])
```
and the edge set looks something like:
```
[[0, 1, 2],
 [0, 2, 3, 1],
 [0, 2, 4],
 [2, 3, 4, 5]]
```
**NOTE**: These values are randomly chosen, not sure if they represent something useful or not. My point is, I have an `ndarray` object for vertices and a nested list for the faces.

Does anyone know anything that I can use to write to disk / visualize this kind of mesh?
Thanks!

**Comment by akaszynski** [comment]
Closing this issue as it's in support.  I'll answer it there momentarily.
