### ISSUE TITLE
flip_normals Filter doesn't work

### ISSUE THREAD

**Issue by liushuya7** [pyvista/pyvista#904]
The provided example code doesn't show the flip_normals() is working.
```py
>>> import pyvista as pv
>>> sphere = pv.Sphere()
>>> sphere.plot_normals(mag=0.1)  
>>> sphere.flip_normals()
>>> sphere.plot_normals(mag=0.1)  
```

**Comment by akaszynski** [comment]
Interesting, because this works for me:

## Before flip
![PyVista_226](https://user-images.githubusercontent.com/11981631/94295047-e9363600-ff1d-11ea-811c-6b5ed0969966.png)

## After flip
![PyVista_227](https://user-images.githubusercontent.com/11981631/94295059-ed625380-ff1d-11ea-9687-d18a3dea7959.png)

**Comment by akaszynski** [comment]
Can you please provide screenshots and a ``pyvista.Report()``?

**Comment by liushuya7** [comment]
**Before flip**
![Screenshot 2020-09-25 131729](https://user-images.githubusercontent.com/6867028/94296945-ad0cd080-ff31-11ea-86b9-8e15648e13f3.png)

**After flip**
![Screenshot 2020-09-25 131645](https://user-images.githubusercontent.com/6867028/94297122-fbba6a80-ff31-11ea-87f5-b8c6547677dd.png)

`pyvista.Report()`:
```
--------------------------------------------------------------------------------
  Date: Fri Sep 25 13:17:49 2020 Eastern Daylight Time

                OS : Windows
            CPU(s) : 8
           Machine : AMD64
      Architecture : 64bit
               RAM : 15.9 GB
       Environment : Python
             Intel : GPU Vendor
Intel(R) HD Graphics 4600 : GPU Renderer
4.3.0 - Build 20.19.15.5063 : GPU Version

  Python 3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 01:53:57)
  [MSC v.1916 64 bit (AMD64)]

           pyvista : 0.25.3
               vtk : 9.0.1
             numpy : 1.19.1
           imageio : 2.9.0
           appdirs : 1.4.3
            scooby : 0.5.6
            meshio : 4.1.1
        matplotlib : 3.3.1
         pyvistaqt : 0.2.0
             PyQt5 : 5.12.3
           IPython : 7.18.1
             scipy : 1.5.2

  Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for
  Intel(R) 64 architecture applications
--------------------------------------------------------------------------------
```

**Comment by liushuya7** [comment]
Oh, it turned out that I was using an older version of pyvista. I did an update [pyvista 0.25.3-py_0 --> 0.26.1-py_0]
Now it works. Thanks!
