### ISSUE TITLE
Disable / hide normal vectors of the clip plane

### ISSUE THREAD

**Issue by leminhson** [pyvista/pyvista#908]
Hi everyone,

I am wondering that it is possible to disable or hide the normal vectors of the clip plane ?

I need this method because, when I apply set_scale to the plotter, the corresponding normal vector is scaled as well and it will be distorted.

In addition, sometime we do not want users to rotate the clip plane, only slide them along the axis.

**Comment by mforbes** [comment]
Yes.  Set their opacity to be zero:

```python
w = plotter.add_plane_widget(...)
w.GetNormalProperty().SetOpacity(0)
```

This will hide the normal vectors and make them no-longer selectable, so the plane cannot be rotated.

See: 

https://itk.org/pipermail/vtkusers/2006-July/036465.html

**Comment by leminhson** [comment]
@mforbes : Thank you for your solution. Now I can solve my problem.
However, if I apply the method 'set_scale' to the plotter, it is really difficult to select the clip plane for sliding

**Comment by banesullivan** [comment]
@mforbes, thanks for sharing that simple solution (this had been bugging me a really long time and I never thought to set the opacity 🤦🏻‍♂️ )

I will add a PR with thiis
