### ISSUE TITLE
Memory leak in OBBTree

### ISSUE THREAD

**Issue by Keou0007** [pyvista/pyvista#914]
When I loop across a large number of vtk files and perform a ray trace on each one, the memory usage continually increases during the loop. If the number of files is large, the memory in the machine fills up causing swapping that slows everything down to an unworkable level.

Reading the files in the loop shows steady memory usage, as measured using psrecord.

```
from glob import glob
import pyvista as pv

files = glob("*.vtp")
for file in files:
  mesh = pv.read(file)
```

![readonly](https://user-images.githubusercontent.com/14357794/94832623-78c57280-0451-11eb-93d9-f22f195c6f17.png)

Adding a ray_trace to the same loop shows continually increasing memory usage.

```
from glob import glob
import pyvista as pv

files = glob("*.vtp")
for file in files:
  mesh = pv.read(file)
  ip, ic = mesh.ray_trace([0, 0, 2], [0, 0, 0], first_point=True)
```

![pvtrace](https://user-images.githubusercontent.com/14357794/94832766-ad392e80-0451-11eb-96c8-330f85dc5285.png)

And doing the same thing directly with VTK works fine, no leak.

```
import os
from glob import glob
import vtk

files = glob("*.vtp")

for file in files:
    reader = vtk.vtkXMLPolyDataReader()
    reader.SetFileName(os.fspath(file))
    reader.Update()
    locator = vtk.vtkOBBTree()
    locator.SetDataSet(reader.GetOutput())
    locator.BuildLocator()
    points = vtk.vtkPoints()
    locator.IntersectWithLine((0, 0, 2), (0, 0, 0), points, None)
```

![vtktrace](https://user-images.githubusercontent.com/14357794/94832676-867af800-0451-11eb-8b49-356b137cdf3f.png)

my file is too big to upload, it's a polydata file with about 5M cells, but this should be reproducible with any similarly large surface mesh file.

**System Information:**

examples above were run on my mac, but I first saw the problem on CentOS 7 so I don't think it's platform specific.

```txt
--------------------------------------------------------------------------------
  Date: Fri Oct 02 01:41:42 2020 AEST

                OS : Darwin
            CPU(s) : 4
           Machine : x86_64
      Architecture : 64bit
               RAM : 16.0 GB
       Environment : Python
        GPU Vendor : ATI Technologies Inc.
      GPU Renderer : AMD Radeon R9 M395 OpenGL Engine
       GPU Version : 4.1 ATI-3.10.16

  Python 3.8.5 (default, Sep  4 2020, 02:22:02)  [Clang 10.0.0 ]

           pyvista : 0.26.1
               vtk : 8.2.0
             numpy : 1.19.1
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.6
            meshio : 4.2.1
        matplotlib : 3.3.1
             scipy : 1.5.0
              tqdm : 4.48.2

  Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for
  Intel(R) 64 architecture applications
--------------------------------------------------------------------------------

```

**Comment by banesullivan** [comment]
Thank you for this detailed report, @Keou0007! We'll get looking into this

**Comment by Keou0007** [comment]
how does your release schedule work? More specifically, when will I be able to add a min version number in my dependencies to make sure this fix is included, and what will that version number be?

**Comment by akaszynski** [comment]
I'm thinking of doing a minor release soon as we've patched a ton of bugs lately.  So, plan for 0.27.0 by the end of the week.

@pyvista/developers, any objections?

**Comment by banesullivan** [comment]
I too would like a release soon here, though I want a few of the open PRs to make it

**Comment by akaszynski** [comment]
> I too would like a release soon here, though I want a few of the open PRs to make it

Sounds good.  Want to make a milestone with the ones you want merged?  I'll work on getting those done for the release.

**Comment by banesullivan** [comment]
Will do, and I'll wrap up the ones I'm eager to land
