### ISSUE TITLE
add_mesh rendering in dark blue before rendering the sent color

### ISSUE THREAD

**Issue by math-artist** [pyvista/pyvista#927]
Yesterday, I did an upgrade from 0.23.1 to 0.26.1 (and feel a little bit ashamed about it that it took me that much time to make the switch since pyvistaqt exists).

Well, it works now, except that new behavior. When adding a mesh with `add_mesh`, on line 1504 in plotting:

```
        actor, prop = self.add_actor(self.mapper,
                                     reset_camera=reset_camera,
                                     name=name, culling=culling,
                                     pickable=pickable)
```
This renders the mesh without props. On my side (using large meshes) this is a 300ms to 600ms dark blue mesh before the right color is rendered. What renders the mesh with the right color is me forcing a refresh right after the `add_mesh` function with `iren.ReInitialize()`.

First, is anyone having that behavior on their side? This seems like old code, and I always had to update the renderer explicitely on my side, so it is possible that this is caused more by an earlier rendering of the mesh than the `add_mesh `logical changes.

It may also mean that to fix it, `add_actor` should be sent a prop parameter instead of using the one provided by it, to make sure that the actor is rendered as expected on the first draw.

Any thoughts on this?

**Comment by akaszynski** [comment]
I like your implementation in #929 and didn't realize that we had this in the wrong order.

**Comment by banesullivan** [comment]
Are we good to close this?

**Comment by math-artist** [comment]
Yes.
