### ISSUE TITLE
extract_cells filter does not keep text fields.

### ISSUE THREAD

**Issue by math-artist** [pyvista/pyvista#930]
The picking method with `visible_pick_call_back ` does not keep text fields in arrays anymore.

The `visible_pick_call_back ` depends on `extract_cells`, line 162 in picking.py:

`picked.append(smesh.extract_cells(cids_to_get))`

after this line, all my text arrays are stripped. I noticed that I had to remove .decode() in my code because text arrays are not binary anymore in pyvista, so it may have to do with that change. I use text arrays to recover the name and category of the data picked (top app categories, not pyvista data types).

**Comment by math-artist** [comment]
How is that information transfered when using filters? Is it normally saved in the original vtk object, or is it applied when using wrap?

In the `_get_output `method, I clearly see 7 arrays for `data `and 9 arrays for `ido`, so there is clearly lost data with the algorithm.

I am trying to figure out if this is caused by vtk not keeping the text fields or by pyvista not getting them back into a pyvista object.

**Comment by akaszynski** [comment]
VTK, not the `pyvista.wrap` method, takes care of transferring the fields from the parent to the child.

**Comment by math-artist** [comment]
I have made my own fix to enforce field arrays:

```
        for array_name in ido.array_names:
            if array_name not in data.array_names and len(ido[array_name]) == 1:
                data.add_field_array(ido[array_name], array_name)
```
in
```
def _get_output(algorithm, iport=0, iconnection=0, oport=0, active_scalars=None,
                active_scalars_field='point'):
    """Get the algorithm's output and copy input's pyvista meta info."""
    ido = algorithm.GetInputDataObject(iport, iconnection)
    data = wrap(algorithm.GetOutputDataObject(oport))
    if not isinstance(data, pyvista.MultiBlock):
        data.copy_meta_from(ido)
        for array_name in ido.array_names:
            if array_name not in data.array_names and len(ido[array_name]) == 1:
                data.add_field_array(ido[array_name], array_name)
        if active_scalars is not None:
            data.set_active_scalars(active_scalars, preference=active_scalars_field)
    return data
```
and I am open to suggestions, because that seems like a change on a core function. Is there a better way to do it?

**Comment by banesullivan** [comment]
I suspect `vtkExtractSelection` is not passing the field arrays (ref [`extract_cells`](https://github.com/pyvista/pyvista/blob/8a16a7c99f1844cb74a7317e9efac363e59f9c37/pyvista/core/filters.py#L2069))

Perhaps we should add a line in `copy_meta_from` to copy the `.field_arrays`? After all, they are "meta" data though not in the sense that PyVista refers to "meta" data. There's a risk it may copy those arrays twice though as most filter will pass through the field arrays.

**Comment by banesullivan** [comment]
Wait are you talking about field arrays or point/cell arrays that contain text values?

**Comment by math-artist** [comment]
I am talking about field arrays when you do `mesh.add_field_array(my_array, field_name)`

**Comment by math-artist** [comment]
>  There's a risk it may copy those arrays twice though as most filter will pass through the field arrays.

If they are dict keys then a simple .update should add the missing keys without duplicating

**Comment by banesullivan** [comment]
Perhaps within `_get_output` then we should just do:

```py
data.field_arrays.update(ido.field_arrays)
```

**Comment by math-artist** [comment]
if that works. I got a false for isinstance(data.field_arrays, dict)

**Comment by banesullivan** [comment]
Umm... yeah those `*_arrays` attributes are `dict`-like... They used to be subclasses of `dict` directly but now we go through some convoluted wrapping with VTK and implemented all of the `dict` methods manually.

**Comment by banesullivan** [comment]
As shown, it may copy the arrays twice (once in the VTK filter and once in our call):

https://github.com/pyvista/pyvista/blob/8a16a7c99f1844cb74a7317e9efac363e59f9c37/pyvista/core/datasetattributes.py#L321-L333

**Comment by math-artist** [comment]
I can't be of much help here. I am a big fan of Python dictionaries but I don't fully understand the current implementation of the [] for arrays.

Do you mean that they look like dicts, but don't behave like dicts, or do you mean that this update method may be called twice?

**Comment by banesullivan** [comment]
For all intents and purposes, you can treat the array containers like `dict`s. e.g. `mesh.point_arrays` is essentially a `dict` and same for `cell_arrays` and `field_arrays`

**Comment by math-artist** [comment]
Sadly, field_arrays are not the same object for ido and data, but we could compare the keys before updating, to save on time:

```
%timeit data.field_arrays.update(ido.field_arrays)
239 µs ± 1.04 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
%timeit data.field_arrays.keys() == ido.field_arrays.keys()
22.2 µs ± 201 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

```
if data.field_arrays.keys() != ido.field_arrays.keys():
    data.field_arrays.update(ido.field_arrays)
```

**Comment by math-artist** [comment]
If we assume that data.field_arrays is always empty when the algorithm fails to keep them, we could even do that:

```
%timeit not data.field_arrays and ido.field_arrays
5.43 µs ± 22.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```
