### ISSUE TITLE
Some texture mapping examples are broken in the documentation

### ISSUE THREAD

**Issue by adeak** [pyvista/pyvista#950]
The examples starting from the first puppy example [here](https://docs.pyvista.org/examples/02-plot/texture.html#applying-textures) are missing the actual texture. The only texture that's visible on the rest of the page is the last one with a collection of puppies.

Current puppy figure:

![sphx_glr_texture_004](https://user-images.githubusercontent.com/17914410/96180931-7a079c80-0f33-11eb-9c00-2469564a16ba.png)

An older version of the same figure from a local doc build of mine:

![sphx_glr_texture_003](https://user-images.githubusercontent.com/17914410/96181156-d8cd1600-0f33-11eb-8641-54ac93df9e75.png)

---

I've now found https://github.com/pyvista/pyvista/pull/853 so I guess it's a known bug, but I couldn't find a duplicate issue so I'll leave this here for the time being.

**Comment by banesullivan** [comment]
Great... thanks for pointing this out. This must have been a very recent bug

**Comment by adeak** [comment]
Ugh, I didn't even think to check if this was a bug outside the docs :facepalm: 

It seems that `.elevation` messes this up:
```py
import pyvista as pv
from pyvista import examples
import numpy as np

x = np.arange(-10, 10, 0.25)
y = np.arange(-10, 10, 0.25)
x, y = np.meshgrid(x, y)
r = np.sqrt(x ** 2 + y ** 2)
z = np.sin(r)
curvsurf = pv.StructuredGrid(x, y, z)
curvsurf.texture_map_to_plane(inplace=True)

elevated = curvsurf.elevation()  # comment this out to fix the puppy

tex = examples.download_puppy_texture()
curvsurf.plot(texture=tex)
```

**Comment by GuillaumeFavelier** [comment]
Finding a consistent way to test this to avoid regression is as important as fixing the bug itself in my opinion.

Do you think the bug is caused by a wrong active scalar array @adeak ?

**Comment by adeak** [comment]
I have absolutely no idea, just fumbling around to see what makes the puppy break, @GuillaumeFavelier :)

**Comment by adeak** [comment]
So this is weird. there's only one scalars array:
```
>>> curvsurf.n_arrays
1
>>> curvsurf.point_arrays
pyvista DataSetAttributes
Association: POINT
Contains keys:
	Texture Coordinates
```

But when something activates that scalars array, be it any of
```
curvsurf.active_scalars_name
curvsurf.active_scalars_info
curvsurf.set_active_scalars('Texture Coordinates')
```

I don't know _what_ is used as scalars when the puppy doesn't break :)

**Comment by banesullivan** [comment]
I think I know what is happening here... the active TCoords are likely being disabled when DataSetAtributes actives it as a point array. I will look into fixing this asap as texture mapping with point arrays is of high importance to me

**Comment by adeak** [comment]
> Finding a consistent way to test this to avoid regression is as important as fixing the bug itself in my opinion.

Regarding that: I know that matplotlib uses baseline images to compare results against, see e.g. https://github.com/matplotlib/matplotlib/blob/cf83ec4f46ae03668a1d89273b28147497ab65f2/lib/matplotlib/tests/test_arrow_patches.py#L30-L48 that compares the result with https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/tests/baseline_images/test_arrow_patches/boxarrow_test_image.png.

Might be worth adopting something like that for pyvista, although this increases maintenance burden in case of false positives (i.e. output slightly changing for a good reason). All things considered it might be a good investment. One question is how pixel-perfectly reproducible pyvista plots are across various environments (I would expect them to be pretty much, for what it's worth).

**Comment by akaszynski** [comment]
> Regarding that: I know that matplotlib uses baseline images to compare results against, see e.g. https://github.com/matplotlib/matplotlib/blob/cf83ec4f46ae03668a1d89273b28147497ab65f2/lib/matplotlib/tests/test_arrow_patches.py#L30-L48 that compares the result with https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/tests/baseline_images/test_arrow_patches/boxarrow_test_image.png.

I'm in favor of implementing this as well, and we can even use `vtk.vtkImageDifference` (wrapped in `pyvista` of course).


Here's what I came up with:
```py
import vtk

import pyvista as pv


def window_to_image(pl):
    ifilter = vtk.vtkWindowToImageFilter()
    ifilter.SetInput(pl.ren_win)
    ifilter.ReadFrontBufferOff()
    if pl.image_transparent_background:
        ifilter.SetInputBufferTypeToRGBA()
    else:
        ifilter.SetInputBufferTypeToRGB()
    ifilter.Update()
    return ifilter.GetOutput()


def compare_plotters(pl1, pl2):
    img_diff = vtk.vtkImageDifference()
    img_diff.SetInputData(window_to_image(pl1))
    img_diff.SetImageData(window_to_image(pl2))
    img_diff.Update()
    return img_diff.GetError()


def compare_images(im1, im2):
    img_diff = vtk.vtkImageDifference()
    img_diff.SetInputData(im1)
    img_diff.SetImageData(im2)
    img_diff.Update()
    return img_diff.GetError()


pl1 = pv.Plotter(off_screen=True)
pl1.add_mesh(pv.Sphere(), smooth_shading=True)
pl1.screenshot('/tmp/img.png')

pl2 = pv.Plotter(off_screen=True)
pl2.add_mesh(pv.Sphere(), smooth_shading=True, show_edges=False)



im1 = pv.read('/tmp/img.png')

compare_plotters(pl1, pl2)
compare_images(im1, window_to_image(pl2))
```

We could use cached images (simulated with `/tmp/img.png') and then compare that across builds.  There are many issues with this approach, including version changes with VTK, cosmetic changes that improve examples, etc.  Therefore, I think we should include tests only within our unit testing framework and not from our sphinx-gallery.
