### ISSUE TITLE
The parameters of the `extract_surface` function are not working

### ISSUE THREAD

**Issue by rodrigomologni** [pyvista/pyvista#962]
Hi, Team! I am using the PyVista 0.26.1. The parameters of the `extract_surface` function are not working. The point array `vtkOriginalPointIds` and the cell arrays `vtkOriginalCellIds` and `original_cell_ids` are added to the extracted surface mesh regardless of the value of the parameters `pass_pointid` and `pass_cellid`. The cell array `original_cell_ids` has the same values of the cell array `vtkOriginalCellIds`.

**Comment by tkoyama010** [comment]
Thank you for your report. Could you give us a minimum example to reproduce the issue?

**Comment by rodrigomologni** [comment]
Hi @tkoyama010! I was writing an example for you when... I realized that was my mistake! :man_facepalming:

The arrays `vtkOriginalPointIds`, `vtkOriginalCellIds` and `original_cell_ids` are in the input mesh. That is, it is not the `extract_surface` that is producing these arrays.

Sorry for my mistake! Thank you for your help! :v:
