### ISSUE TITLE
Qt Interactive Renderer Mouse Location Bug

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#97]
Something isn't right with the Qt renderer mouse locations. When interacting with the axes widget, it detects that the user is hovering over it at the wrong locations... see video below.

Perhaps this is why we can't move the interactive scalar bar widget in #79 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/22067021/52975575-443b9a80-3383-11e9-83ee-07775164dde4.gif)

**Comment by banesullivan** [comment]
Code to reproduce this:

```py
import vtki
from vtki import examples
import vtk

data = examples.load_uniform()

p = vtki.BackgroundPlotter()
p.add_mesh(data.threshold_percent([0.25, 0.75]))
p.add_mesh(data.outline_corners())
p.add_axes(interactive=True)
```

**Comment by banesullivan** [comment]
Another video showing how the mouse location/speed is not working as expected:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/22067021/52982655-81fceb00-33a4-11e9-981a-a3ec4a6b1815.gif)

**Comment by akaszynski** [comment]
I’ll have to investigate this.  There’s several reasons why this might be a problem, and it might have to do with how I’m implementing the class.

**Comment by banesullivan** [comment]
This is just flat out weird.... noticed randomly today while working that the interactive stuff was working as expected. Haven't rebooted my computer or made any changes to the plotting code.

I have no idea why it would randomly change behavior....

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/22067021/53145301-e8c50480-355c-11e9-85e9-1219c00fa8c4.gif)

**Comment by akaszynski** [comment]
I’ve also been unable to reproduce this on my end.  I’ll keep an eye out to see if this happens again.

**Comment by sjtu-xx** [comment]
I've met the same problem on both ubuntu and mac, then I update my vtk to v8.2.0. It seems that the problem is caused by some bugs in older version.
Try the new version, please!

**Comment by GuillaumeFavelier** [comment]
Thanks for your suggestion @sjtu-xx ! I tried on my Linux Manjaro and everything works fine.

**Comment by banesullivan** [comment]
Thanks for reminding me of this, @sjtu-xx - I upgraded to VTK v8.2.0 a while back and haven't experienced this bug in a while. I'm going to close this since it appears to be a bug on an older version of VTK rather than anything we can control in PyVista.
