### ISSUE TITLE
Eventually compare plots across unit tests?

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#982]
This discussion has come up many times so I thought I'd open an issue.

Should we implement a testing suite to compare screenshots of the unit tests? Perhaps each release has a cache of screenshots and every subsequent job compares against that baseline?

See https://github.com/pyvista/pyvista/issues/950#issuecomment-718337994

I've always been hesitant to approach this testing style as it would be very flaky

**Comment by akaszynski** [comment]
> I've always been hesitant to approach this testing style as it would be very flaky

Maybe, or maybe not.  It doesn't have to be a perfect match, and my example in #950 can give us a threshold.

We can cache the screenshots, compare against them and have an allowable, warning, and error score.  Maybe we can keep out the error scores and just have warnings so we don't have to manually check the docs to see if things look weird.

**Comment by akaszynski** [comment]
This will be solved by #998.  We can consider adding more tests to the plotter, though getting "plotting coverage" might be hard to measure.
