### ISSUE TITLE
plot function returns nothing when passing screenshot=True

### ISSUE THREAD

**Issue by RoyJames** [pyvista/pyvista#986]
**Describe the bug, what's wrong, and what you expect:**

I'm hoping to get the image data from your plot function, and according to your doc [here](https://docs.pyvista.org/plotting/plotting.html#convenience-functions), the screenshot parameter should control this behavior. However, no matter how I toggle this flag, w/ and w/o notebook=True in a jupyter notebook, the plot function returns nothing. If I instead use
```
cpos, img = sphere.plot(screenshot=True, notebook=True)
```
the error says "cannot unpack non-iterable NoneType object". When I use an actual path for screenshot, it can save the picture file normally. But I hope to be able to extract the image data right here. 

-----

**To Reproduce**

Please include a code snippet to reproduce the bug in the block below:

```py
import pyvista as pv
sphere = pv.Sphere()

# short example
cpos = sphere.plot(screenshot=True, notebook=True)
print(cpos)
```

**Screenshots**
![pyvista_plot](https://user-images.githubusercontent.com/8073842/98183612-82ba1580-1ed6-11eb-89a5-bc0e723246dd.png)

-----

**System Information:**
 Please run the following code wherever you are experiencing the bug and paste the output below. This report helps us track down bugs and it is critical to addressing your bug:

```py
# Get system info
import pyvista as pv
print(pv.Report())
```

```txt
--------------------------------------------------------------------------------
  Date: Wed Nov 04 19:47:19 2020 EST

                OS : Linux
            CPU(s) : 32
           Machine : x86_64
      Architecture : 64bit
       Environment : Jupyter
        GPU Vendor : VMware, Inc.
      GPU Renderer : llvmpipe (LLVM 10.0.0, 256 bits)
       GPU Version : 3.3 (Core Profile) Mesa 20.0.8

  Python 3.7.9 (default, Aug 31 2020, 12:42:55)  [GCC 7.3.0]

           pyvista : 0.26.1
               vtk : 9.0.1
             numpy : 1.19.2
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.6
            meshio : 4.3.3
        matplotlib : 3.3.2
           IPython : 7.19.0
             scipy : 1.5.2
              tqdm : 4.51.0

  Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for
  Intel(R) 64 architecture applications
--------------------------------------------------------------------------------

```

**Comment by akaszynski** [comment]
You have to have ``notebook=False`` to get a screenshot.  This behavior may change in the future once we implement a better notebook plotter, but for now, disable notebook plotting.

**Comment by RoyJames** [comment]
> You have to have `notebook=False` to get a screenshot. This behavior may change in the future once we implement a better notebook plotter, but for now, disable notebook plotting.

Thanks! That works.
