### ISSUE TITLE
Scalar bar background fill and outline

### ISSUE THREAD

**Issue by mcgoldba** [pyvista/pyvista#987]
When applying a background or outline to the scalar bar, the background or outlined area does not encompass the labels.  The desired effect should be that the `0.000`, `1.00`, and `U [m/s]` labels are within the outlined / background area, so that they are legible.

![image](https://user-images.githubusercontent.com/50269816/98379054-d9c60480-2014-11eb-89c7-dba432599e95.png)

![image](https://user-images.githubusercontent.com/50269816/98379329-2c9fbc00-2015-11eb-8037-a7f730587b08.png)

**Comment by banesullivan** [comment]
I'm afraid this may be an upstream VTK issue though we look into this to double-check and potentially provide a workaround. Hang tight.
